### ISSUE TITLE
Pin tRPC packages' versions to each other?

### ISSUE THREAD

**Issue by KATT** [trpc/trpc#1020]
For example, right now the `@trpc/client` depends on a `^9.x.y` - maybe it should be `9.x.y` so that dependabot will automatically always update them altogether.

I'm getting tired of doing `npx npm-check-updates --filter /@trpc/ -u  && yarn` everytime I release a new version 😅

**Comment by alii** [comment]
Might this be possible with yarn berry workspaces and constraints?

**Comment by KATT** [comment]
> Might this be possible with yarn berry workspaces and constraints?

Could you elaborate? Not used yarn berry! Feel free to have a stab at a PR 😄
