### ISSUE TITLE
Unable to infer mutation input type from zod validation schema

### ISSUE THREAD

**Issue by alanrsoares** [trpc/trpc#1200]
Hi team. First of all, I'd like to say I'm really enjoying trpc, but have had some trouble integrating it on an existing project based on react-query.

If I define a mutation route with an `zod` input validation schema, the generated hooks `mutate` and `mutateAsync` methods have `void` for variables. However, replacing it with a `yup` schema gets me a different result.

Consider the following router:

```ts
const signupRouter = createRouter()
  .mutation('signup', {
    input: z.object({
      email: z.string().email(),
      firstName: z.string().nonempty(),
      // ....
    }),
   resolve: () => { 
     // ...
   }
  })
```

This is what I get when I try to use the mutation hook:

![Screen Shot 2021-11-03 at 10 26 25 AM](https://user-images.githubusercontent.com/273334/139954119-7d13b31a-0626-4508-b171-93808a6e5742.png)

Now, switching to `yup` ...

```ts
const signupRouter = createRouter()
  .mutation('signup', {
    input: yup.object({
      email: yup.string().email(),
      firstName: yup.string().required(),
      // ....
    }),
   resolve: () => { 
     // ...
   }
  })
```

This is what I get, still not optimal as there's a weird `void | T` union type

![Screen Shot 2021-11-03 at 10 19 02 AM](https://user-images.githubusercontent.com/273334/139953561-aaa87831-03ee-4a24-9f0d-e9177cbf65bd.png)

**Comment by KATT** [comment]
Here's a helper function:

```tsx
import type { AppRouter } from 'server/routers/_app';

export type inferMutationOutput<
  TRouteKey extends keyof AppRouter['_def']['mutations'],
> = inferProcedureOutput<AppRouter['_def']['mutations'][TRouteKey]>;

// usage

type TPostAddInput = inferQueryInput<'post.add'>
```

Does that help? 

If you think you've found an issue, please make a reproduction example - the tests for the validators are here: https://github.com/trpc/trpc/blob/main/packages/server/test/validators.test.ts

**Comment by KATT** [comment]
Also see discussion in #1172

**Comment by KATT** [comment]
@alanrsoares i think you need `.required()` on the yup object too as its not required as default.

**Comment by KATT** [comment]
I will close this as I don't think it's an issue with trpc, feel free to re-open if you disagree

**Comment by amantiwari1** [comment]
Hey @KATT ,

almost similar, I am using `zodjs` with similar error 
![image](https://user-images.githubusercontent.com/53963065/156880585-d2a72f1d-80f3-43a1-b43c-7fa3f80005ef.png)

**Comment by sachinraja** [comment]
What's the error @amantiwari1? You may have to [enable strict mode in your tsconfig](https://trpc.io/docs/react#2-enable-strict-mode).

**Comment by amantiwari1** [comment]
WOW! it works after enable strict mode

thanks! @sachinraja
