### ISSUE TITLE
Upgrade tRPC from 9.12.0 to 9.12.2 breaks my existing code

### ISSUE THREAD

**Issue by danielyogel** [trpc/trpc#1242]
Hey,

I've just upgraded tRPC to 9.12.2 from 9.12.0 (client and server libs) - and my project immediately failed to compile with 147 type errors.
Still have no idea what is the problem, maybe the way I must configure the router has changed?
Thanks.

**Update:**

Found the problem.
`npm install --legacy-peer-deps` won't do it anymore, I'll have to change some other dependencies from my project for this upgrade, because `npm install` is not working for them.

**Comment by KATT** [comment]
How did your package.json look before the upgrade? You always need to upgrade all `@trpc/*` together, that's what I intended to enforce with this change.

**Comment by KATT** [comment]
Oh yeah, I read on it now `--legacy-peer-deps` shouldn't be needed anymore, since [9.12.1](https://github.com/trpc/trpc/releases/tag/v9.12.1) we don't have for instance `@trpc/server` as a hard dependency of `@trpc/client`, instead it's a peer dependency, so it won't ever be installed twice.

**Comment by KATT** [comment]
Closing this as I don't see it as an issue - feel free to reopen if you disagree :)
