### ISSUE TITLE
enabling ReactQueryDevtools? 

### ISSUE THREAD

**Issue by JulienDemarque** [trpc/trpc#1253]
I am looking on how to enable ReactQueryDevtools within trpc client.

**Comment by merelinguist** [comment]
There's nothing special to do, just include the Devtools component somewhere in your app https://react-query.tanstack.com/devtools.

**Comment by merelinguist** [comment]
See an example here https://github.com/trpc/trpc/blob/d2afc0c7bcec5bc7530540a157ba1d3e1d9052c4/examples/next-prisma-starter/src/pages/index.tsx#L93-L95
