### ISSUE TITLE
One example project failing since TypeScript 4.5.2 upgrade

### ISSUE THREAD

**Issue by KATT** [trpc/trpc#1291]
- Unsure why (didn't reproduce when I did a quick test locally) 
- Bad commit: #1288 (maybe should revert?)
- Node.js 16 and specific to one example
- [Failing test on Node 16](https://github.com/trpc/trpc/runs/4255431938?check_suite_focus=true)
- [Same test on Node 14](https://github.com/trpc/trpc/runs/4255431890?check_suite_focus=true)

How to build the failing example locally

```bash
yarn 
cd examples/standalone-server
yarn build
```
---

<img width="587" alt="Screenshot 2021-11-19 at 16 20 40" src="https://user-images.githubusercontent.com/459267/142646918-c7d7642a-2b4a-4977-b5b7-b2b180492a98.png">

**Comment by Remeic** [comment]
Hi @KATT , can't reproduce the bug on my macbook with node 16.13.0 and yarn 1.22.17, there something i miss? 

Maybe i can try to clone again the project

**Comment by KATT** [comment]
I reverted the upgrade for now, but would want it to work of course ☺

**Comment by KATT** [comment]
Replaced by #1295
