### ISSUE TITLE
Can't pass an updater function to setQueryData

### ISSUE THREAD

**Issue by JulienDemarque** [trpc/trpc#1308]
According to react-query doc it should accept a function:
`updater: TData | (oldData: TData | undefined) => TData`
https://react-query.tanstack.com/reference/QueryClient#queryclientsetquerydata

**Comment by JulienDemarque** [comment]
Also the typing is wrong when the query to update is an infiniteQuery it seems...

**Comment by KATT** [comment]
Hmm, this might be right, I've not used `setQueryData` with infinite queries.

Feel free to try to make a PR with a repro or a fix 🙏

**Comment by JulienDemarque** [comment]
It's actually also missing on setQueryData with normal queries on our repo...

**Comment by KATT** [comment]
You can use the raw query client too through `trpc.useContext().queryClient`.

I don't know what's the issue in your repo, but respectfully, please spend more time on your issue reports - I'm not a support team on your paid enterprose product, I'm a solo developer who, for free, is maintaining a large toolkit that your company is saving a lot of time and money by using.
