### ISSUE TITLE
@trpc/next with ssr: true breaks react 18's useId

### ISSUE THREAD

**Issue by MarcGuiselin** [trpc/trpc#1343]
Demo repo: [MarcGuiselin/trpc-useid-error](https://github.com/MarcGuiselin/trpc-useid-error)

Dependencies:

```json
"@trpc/client": "9.16.0",
"@trpc/next": "9.16.0",
"@trpc/react": "9.16.0",
"@trpc/server": "9.16.0",
"next": "12.0.7",
"react": "18.0.0-rc.0",
"react-dom": "18.0.0-rc.0",
```

Using `withTRPC` with ssr enabled in `_app.tsx`
```js
export default withTRPC({
  ssr: true,
  config: () => ({
    url: 'http://localhost:3000/api/trpc',
  }),
})(MyApp)
```

`index.tsx`:
```tsx
import { useId } from 'react'

export default function Home({}) {
  useId() // Throws an error

  return <div></div>
}
```

Throws the following error: `TypeError: dispatcher.useId is not a function`

The `useId` function is defined itself, but internally react's `dispatcher.useId` is undefined when using ssr. I'm lost as to how or what in the pipeline is modifying react's internals.

The folks at [@radix-ui](https://www.radix-ui.com/docs/primitives/utilities/id-provider) are depreciating their own id generator for react's new `useId` prompting me to look into why `useId` wasn't working in my project.

Could this be related to [react-ssr-prepass](https://github.com/FormidableLabs/react-ssr-prepass)?

**Comment by KATT** [comment]
My guess would be the same as yours.. maybe do a test to see if prepass works with that or not?

I honestly probably won't be able to work on this before the end of the year.

**Comment by MarcGuiselin** [comment]
We're several months ahead of a release, so that's no issue. I'll take some time to look into it and I'll let you know what I find. Keep up the great work and enjoy the holidays!

**Comment by MarcGuiselin** [comment]
https://github.com/FormidableLabs/react-ssr-prepass/pull/76 should fix this issue
