### ISSUE TITLE
Add `setInfiniteQueryData` helper

### ISSUE THREAD

**Issue by alexgorbatchev** [trpc/trpc#1358]
if you have `useInifiteQuery(['foo', {}])` then `args` in `setQueryData<..., TInput, ...>(['foo', {}], args => ...`  is incorrectly typed. Types say that `args` is `TInput` where the actual value of `args` if inspected is `{ pageParams: ...,  pages: TInput[] }`

**Comment by KATT** [comment]
Hmm, what do you think is best, maybe we should expose a `setInfiniteQueryData` for this?

I'm on holiday and will completely delete all work-related apps for a few weeks from today. If you make a PR I'll merge it on the 10th of Jan.

**Comment by KATT** [comment]
**Original title:** 

> `setQueryData` of `useInfiniteQuery` doesn't expose correct `Updater`

**Comment by KATT** [comment]
Potential others

- `getInfiniteQueryData` (?)
- `refetchInfiniteQueries`

**Comment by KATT** [comment]
Needs

- [ ] Added in https://github.com/trpc/trpc/blob/main/packages/react/src/internals/context.tsx
- [ ] Added in https://github.com/trpc/trpc/blob/main/packages/react/src/createReactQueryHooks.tsx
- [ ] Test added in https://github.com/trpc/trpc/tree/main/packages/server/test
