### ISSUE TITLE
Server/client example img not populating

### ISSUE THREAD

**Issue by Neilblaze** [trpc/trpc#1373]
#### Description :- 

The `Server/client` example image isn't populating in either of the [readme.md](https://github.com/trpc/trpc#readme) & or [here](https://trpc.io/).

![image](https://user-images.githubusercontent.com/48355572/148673143-9c079230-d05b-410f-a9eb-ce010155ff42.png)
&
![image](https://user-images.githubusercontent.com/48355572/148673148-f8920e5c-8cdc-4ac5-81af-0300ab865542.png)

➡️ I'd like to fix this if approved! But for that, I need the real Image source as [this](https://storage.googleapis.com/trpc/trpcgif.gif) doesn't return anything.
➡️ Also, I'd like to add PR / Issues templates in workflows.

**Comment by KATT** [comment]
My credit card expired to GCP where I host it, will fix ASAP, thanks for highlighting

**Comment by KATT** [comment]
Should be fixed!
