### ISSUE TITLE
`nodeHTTPRequestHandler` stripping out headers, body, and middlewares with Fastify

### ISSUE THREAD

**Issue by sb55555** [trpc/trpc#1406]
Hello, we've been trying out TRPC on professional projects with Fastify.

We noticed the `requestHandler` or `nodeHTTPRequestHandler` is using `reply.raw` skipping all middleware-defined headers and functionalities including CORS making it unfortunately unusable for production.

according to https://www.fastify.io/docs/latest/Reference/Reply/#raw
```
.raw
This is the http.ServerResponse from Node core. Whilst you are using the Fastify Reply object, the use of Reply.raw functions is at your own risk as you are skipping all the Fastify logic of handling the HTTP response. e.g.:
```

as shown on #524
```
await nodeHTTPRequestHandler({
        req: req.raw,
        res: reply.raw, <----- HERE
        router,
        createContext,
        path: (req.params as any).path,
      });
```
how can we help ?

thank you

**Comment by sb55555** [comment]
based on #655 

we found a workaround to copy headers set by Fastify Middlewares to tRPC response headers.
that allows to make CORS work, this may need more work to handle all middlewares use-cases.

```
app.all('/trpc/:path', (req, reply) => {
  const res = reply.raw;
  Object.keys(reply.getHeaders()).map((headerKey: string) => {
    const headerValue = reply.getHeader(headerKey);
    if (headerValue) {
      res.setHeader(headerKey, headerValue);
    }
  });

  nodeHTTPRequestHandler({
    req: req.raw,
    res: res,  // <---- replaced
    router: appRouter,
    createContext,
    path: (req.params as any).path,
  });
});
```

**Comment by KATT** [comment]
I see. It seems to me like we should provide a lower level primitive for adapters, where the consumer control the flow of the output rather than tRPC doing `res` directly.

I'll have a look at this in the next few weeks, for now, shim `res` as you're doing. Great that you found a workaround.

**Comment by KATT** [comment]
> We cannot shim the resulting `req.raw` as `http.IncomingMessage` type does not allow a `body` key to be set.

Do what all JS-developers has since the beginning of node: `(req as any).body = X`

**Comment by sb55555** [comment]
Well, that fix the issue easily. Thank you !

Here is is the resulting middleware for reference.

```
app.all('/trpc/:path', (req, reply) => {
  // pass fastify body to node
  const reqNode = req.raw;
  (reqNode as any).body = req.body;

   // pass fastify headers to node
  const resNode = reply.raw;
  Object.keys(reply.getHeaders()).map((headerKey: string) => {
    const headerValue = reply.getHeader(headerKey);
    if (headerValue) {
      resNode.setHeader(headerKey, headerValue);
    }
  });

  nodeHTTPRequestHandler({
    req: reqNode,
    res: resNode,
    router: appRouter,
    createContext,
    path: (req.params as any).path,
  });
});
```

**Comment by KATT** [comment]
Thank you! If you want, you could make an official fastify adapter

- Add it in here https://github.com/trpc/trpc/tree/main/packages/server/src/adapters
- Add it in entrypoints https://github.com/trpc/trpc/blob/main/packages/server/package.json#L22
- Run `yarn dev` in the project root
- Add tests
- `yarn test --watch

**Comment by KATT** [comment]
@sb55555 - @skarab42 built a Fastify adapter over at #1406 which is in the latest version of trpc :)

**Comment by KATT** [comment]
Let me know if this is still an issue after using the adapter. Feel free to open a new issue :)
