### ISSUE TITLE
useQueries hook for fetching unknown number of entities

### ISSUE THREAD

**Issue by kripod** [trpc/trpc#1454]
When fetching an **unknown amount** of entities, the [`useQueries` hook](https://react-query.tanstack.com/reference/useQueries#_top) comes handy, e.g.:

```ts
let filteredUsers: number[] = [/* Unknown amount of IDs */];
const results = useQueries(
  filteredUsers.map((id) => ["user.find", id] as const);
)
```

The typings of `useQueries` went through significant [overhauls](https://github.com/tannerlinsley/react-query/releases/tag/v3.34.10) lately, which might make it less cumbersome to infer tRPC’s end-to-end types.

**Comment by KATT** [comment]
Yeah, it's very hard to deal with the types on this one which is why I haven't added support for it. 

@TkDodo, the react-query maintainer, even brought up on Twitter today that he can barely follow how the types work himself 😅 https://twitter.com/TkDodo/status/1487804403356680201

To me, this feels like an edge-case and I'm unsure if I want to support this as part of the wrapper, to be honest. 

However, you can still use `useQueries` and achieve this if you want:

```tsx
import { useRouter } from 'next/router';
import { trpc } from 'utils/trpc';
import { useQueries } from 'react-query';

const PostViewPage = () => {
  const { client } = trpc.useContext();
  const postIds = ['1', '2'];
  const posts = useQueries(
    postIds.map((id) => ({
      queryKey: ['post.byId', { id }],
      queryFn: (args: any) => {
        const input = args.queryKey[1];
        return client.query('post.byId', input);
      },
    })),
  );
  // [..]
  return <></>
}
```

**Comment by tianhuil** [comment]
Thank you for providing this workaround @KATT.  Let me try to convince you that it's not an edge case.

> To me, this feels like an edge-case and I'm unsure if I want to support this as part of the wrapper, to be honest.

The big reason for having a native `trpc.useQueries` would be smart cache validation (https://tanstack.com/query/v4/docs/guides/query-invalidation).  I would like to query for 10 todos (by id) and then update a single one of them without having to refetch all 10.  Ideally, the code would be something like ...

```ts
const {data, isLoading} = trpc.useQueries(todos.map((id) => ['todo', { id }]))

const editedId = ...
const mutation = trpc.useMutation(['todo', { id: editedId }])
```

**Comment by JesusTheHun** [comment]
The reason behind the complex type of `useQueries` is that it supports an array of any query function.
We good enough start would be to support an array of the same function. I think that covers 99% of the use cases.

**Comment by TkDodo** [comment]
> FWIW - I think this will be a lot easier or redundant soon™ with the https://github.com/reactjs/rfcs/pull/229-hook.

> It'll be something like const myPosts = use(Promise.all([ postIds.map((id) => trpc.post.byId.fetch({ id })])

can't really agree with that. `fetch` only triggers a fetch once and will give you a Promise, which you can await with `use`. However, it will _not_ create an `Observer`, which subscribes you to the queryCache and re-renders the component when changes come in. It's similarly wrong to just call `queryClient().getQueryData(key)` in the react component.

This is what `useQuery` and `useQueries` does under the hood.

**Comment by KATT** [comment]
Duplicate: #3188
