### ISSUE TITLE
Inconsistent behavior between httpLink and httpBatchLink

### ISSUE THREAD

**Issue by friggeri** [trpc/trpc#1462]
I have a procedure that doesn't expect an input, if I use the `httpBatchLink` I can call it without any issue, however if I try using the `httpLink`, the server fails with a `BAD_REQUEST` and complains that an input has been provided. Did a little digging and it appears that in that case the client sends a `{}` instead of `null`.

**Comment by KATT** [comment]
Hmm - I can't seem to reproduce it, I had an attempt [here](https://github.com/trpc/trpc/tree/katt/repro-1462) but it seems to work.

Are you able to do a reproduction repo based on one of the example apps or provide more info?

**Comment by KATT** [comment]
Closing as @friggeri isn't responding with a repro. Feel free to open a new issue.
