### ISSUE TITLE
tRPC adapter ESM import ergonomics

### ISSUE THREAD

**Issue by leonzalion** [trpc/trpc#1487]
Firstly, thanks for this amazing package!

I'm using ts-node + ESM in my project, and when importing the adapter from tRPC, I have to resort to using the full path with extensions like so:

```javascript
import { nodeHTTPRequestHandler } from '@trpc/server/adapters/node-http/dist/trpc-server-adapters-node-http.cjs.js';
```

I've tried enabling extension-less imports with `--experimental-specifier-resolution=node`, but it doesn't seem to work with ts-node ([here's a repo with the reproduction](https://github.com/leonzalion/trpc-esm)). Based on some digging around in ts-node's code, it looks like they never check the package.json so the "module" key  pointing to the esm export at https://github.com/trpc/trpc/blob/main/packages/server/adapters/node-http/package.json isn't being read, and thus ts-node is unable to find the full path of the esm file (and I'm not sure whether this is intentional by design or a ts-node bug).

It'd be optimal if tRPC re-exported the above adapter file from a file with a shorter name, maybe `@trpc/server/adapters/node-http/index.js`? I'm far from an expert on extensions and packages, so I'm not sure if that's feasible or not.

Let me know if I'm missing anything and/or if there's a better way to import the adapter!

**Comment by sachinraja** [comment]
I've been working on supporting esm with package.json `exports` in #1466 (still working out a few things though). It should fix any errors with esm import paths.

**Comment by KATT** [comment]
Yeah, this is being worked on. TBD yet if it'll be in the `9.x` line as well or just straight into next major `10.x`. Moving to discussions as this is already  covered by a few different tickets and PRs

**Comment by KATT** [comment]
Or yeah, feel free to open it again or a new one if you find your questions unanswered
