### ISSUE TITLE
Add support for codecs ( `stringify` and `parse` ) in transformer

### ISSUE THREAD

**Issue by darioielardi** [trpc/trpc#1495]
I'd like to have `stringify`/`encode` and `parse`/`decode` support in transformers along with `serialize` and `deserialize`, to replace `encodeURIComponent` with something like [jsurl](https://github.com/Sage/jsurl) which makes the resulting url way more readable and short, especially with superjson. 

I'd probably use this only for queries, not mutations, so we need to handle the two separately. Also, you shouldn't be allowed to provide only one of the two methods ( only `parse` or `stringify` ).

I was thinking something like this: 
```ts
type DataCodec = {
  parse(value: string): any; // or decode
  stringify(value: any): string; // or encode
}

type DataTransformer = {
  serialize(object: any): any;
  deserialize(object: any): any;
  queryCodec?: DataCodec;
  mutationCodec?: DataCodec;
}
```

Example:
```ts
import jsurl from 'jsurl'
import superjson from 'superjson'

const router = trpc.router().transformer({
  serialize: superjson.serialize,
  deserialize: superjson.deserialize,
  queryCodec: {
    parse: jsurl.parse,
    stringify: jsurl.stringify,  
  },
  mutationCodec: {
    // ...
  }
}) //...
```

In case you think this is worth it and agree on the design I'll work on it myself. Let me know if you want me to move this in discussions.

**Comment by KATT** [comment]
I think it's a good idea to opt-in on. I agree pretty urls are nice.

**Comment by KATT** [comment]
I'll have a think about the design. Potentially we should put a pin on it until next version as I'm doing a lot of breaking changes.

**Comment by darioielardi** [comment]
Sure, no problem. I'll wait for next version release (any ETA?), let me know about the design for this when you have some time and I'll work on it.

**Comment by KATT** [comment]
No ETA, but I'm not rushed so if you think you'll bash this out within the next few weeks, I'd say go for it
