### ISSUE TITLE
Still mantained?

### ISSUE THREAD

**Issue by brunoalano** [trpc/trpc#1498]
Hello, is this project still being maintained? Most recent commits are just automated version bumps

**Comment by timcole** [comment]
Of course! :) @KATT has been working hard with the community figuring out various new things and changes for v10 over on [trpc/v10-playground](https://github.com/trpc/v10-playground) feel free to also join us on the [Discord](https://trpc.io/discord).

**Comment by KATT** [comment]
Haha, yes, it's very maintained and very stable in its current form, the only known bugs are some Suspense issues with ssr and another ssr issue that is out of my hands because of next.js. (look in issues/PRs on the bugs label)
