### ISSUE TITLE
next-i18next not working correctly with wrapped tRPC when SSR is enabled

### ISSUE THREAD

**Issue by medihack** [trpc/trpc#1507]
## Describe the bug
When wrapping an app with [`withTRPC`](https://trpc.io/docs/nextjs#4-configure-_apptsx) that is already wrapped with `appWithTranslation` leads to the error `react-i18next:: You will need pass in an i18next instance by using initReactI18next` on the server console when SSR is enabled for tRPC (otherwise everything works fine).
I also opened an issue at next-i18next (https://github.com/isaachinman/next-i18next/issues/1682) as I am not sure which "fault" it is. Just stumbled upon it.

## Occurs in next-i18next version
"next-i18next": "^10.2.0"
"@trpc/next": "^9.18.0"

## Steps to reproduce
```
export default withTRPC<AppRouter>({
  config({ ctx }) {
    let url = process.env.TRPC_URL!
    return { url }
  },
  ssr: true, // // no error when set to false
})(appWithTranslation(MyApp))
```

## Expected behaviour
It should also work with tRPC.

## OS (please complete the following information)
 - Device: Gitpod Cloud (but also tested locally)
 - Browser: Chrome

**Comment by KATT** [comment]
Thanks for this report, @medihack!

I've added you as a collaborator in case you want to make a repro in the examples folder (you can just modify the existing Prisma starter), that will make it easier for me to work on it.

You can also try digging into the withTRPC function.to see if you can get a fix in place yourself ☺

**Comment by KATT** [comment]
It might be that you're using getServerSide props which can't be used together with ssr: true - #1361

**Comment by medihack** [comment]
@KATT You are absolutely right. That is the same problem. I will disable the tRPC SSR feature for now, too. I also voted the [Next.js issue up](https://github.com/vercel/next.js/discussions/28183). A little hint in the docs would be cool. Otherwise a superb library!!!
