### ISSUE TITLE
Update example to use Playwright's own test runner

### ISSUE THREAD

**Issue by KATT** [trpc/trpc#1523]
Currently the [next-prisma-starter](https://github.com/trpc/trpc/tree/main/examples/next-prisma-starter) uses jest-playwright. It would be better to use Playwright's own test runner.

For reference, one can look at [`calcom/cal.com`](https://github.com/calcom/cal.com/tree/main/apps/web) for how to setup Playwright's own runner

**Comment by emilbryggare** [comment]
I've been wanting to take a closer look at Playwright, I will give this a go.
