### ISSUE TITLE
How to throw 409 error?

### ISSUE THREAD

**Issue by ASgmbv** [trpc/trpc#1561]
Hi, thank you all for your great project.
I was building a signup endpoint where I need to throw an HTTP 409 error when a user tries to create a new account with an email that is already used, it seems like there is no suitable trpcError code for this case?
Thank you

**Comment by ahhshm** [comment]
The [Error Handling](https://trpc.io/docs/error-handling) section needs a major improvement.

**Comment by ASgmbv** [comment]
> I think you can throw an error with whatever code that you like:
> 
> ```ts
> import { TRPCError } from '@trpc/server';
> 
> throw new TRPCError({
>   code: 'CONFLICT',
>   message: 'Optional Message',
>   // optional: pass your thrown error to TRPCError to retain stack trace
>   cause: myError,
> });
> ```
> 
> Check out the [docs](https://trpc.io/docs/error-handling) for more information.

TypeScript gives an error when you try to put anything except provided code values.

**Comment by sachinraja** [comment]
You'd also have to handle that custom code in [`formatError`](https://trpc.io/docs/error-formatting) to set the status to 409.

**Comment by KATT** [comment]
Feel free to add this.

- https://github.com/trpc/trpc/tree/main/packages/server/src/rpc
- #1194 <-- very similar PR
