### ISSUE TITLE
Pass request object to the teardown function in createExpressMiddleware

### ISSUE THREAD

**Issue by olehmisar** [trpc/trpc#1562]
I need to access some request information in the teardown function:
```typescript
app.use(
  trpcExpress.createExpressMiddleware({
    router: appRouter,
    teardown() {
      // need access to request object here
    }
  })
);
```
  
I would like to use it like this:
```typescript
teardown(req) {
  console.log(req.url, "done")
}
```

**Comment by KATT** [comment]
Hey @olehmisar 

What do you need this function for? Are you sure you don't want to have a logger middleware?

https://trpc.io/docs/middlewares#logging

**Comment by olehmisar** [comment]
Hi @KATT. Looks like it is exactly what I need! Thanks.
