### ISSUE TITLE
UseTRPCQueryOptions helper

### ISSUE THREAD

**Issue by mmkal** [trpc/trpc#1573]
Small request - a couple of times we’ve wanted to make a thin abstraction on top of `trpc.useQuery` or `trpc.useMutation`, but it’s been awkward to allow passing in `opts` to use `onSuccess` or similar. Right now the signature is:

```ts
    UseTRPCQueryOptions<
      TPath,
      TQueryValues[TPath]['input'],
      TQueryValues[TPath]['output'],
      TError
    >
```

but getting `TQueryValues` and `TError` is tricky.

It’d be nice to be able to have a helper where all we need is the path:

```ts
const useFooBar = (opts?: UseQueryOpts<typeof trpc, 'foo'>) => {
  return trpc.useQuery(['foo', { bar: 123 }], opts)
}
```

The `typeof trpc` arg would presumably be necessary since `trpc` has all the type info baked into it.

What do you think?

**Comment by KATT** [comment]
Could you expand a bit on what sort of scenarios you use it for?

**Comment by charkour** [comment]
I ran into a similar issue while using v10. KATT on the discord suggested the following. 

```ts
const useFooBar = (opts?: Parameters<typeof trpc['getOrder']['useQuery']>[1]) => {
  return trpc.foo.useQuery({ bar: 123 }, opts)
}
```

For v9, it would probably work like this. 

```ts
const useFooBar = (opts?: Parameters<typeof trpc['getOrder']['useQuery']>[1]) => {
  return trpc.useQuery(['foo', { bar: 123 }], opts)
}
```

**Comment by charkour** [comment]
From there, we could make a type utility to get the `opts` type.
