### ISSUE TITLE
WebSockets - Critical Vulnerability

### ISSUE THREAD

**Issue by jlalmes** [trpc/trpc#1575]
Not typically an issue if using `@trpc/client` to interact with your WebSocket endpoint, but a bad/unknowing actor could send the following payload to a trpc WebSocket endpoint and cause it to throw an uncaught runtime error `TRPCError: 'id' is required` and crash the NodeJS process.

```json
{
  "id": null,
  "method": "query",
  "params": {
    "path": "test"
  }
}
```

**Comment by KATT** [comment]
Seems like a bug! Will fix it ASAP

**Comment by jlalmes** [comment]
Great job @KATT 🎉
