### ISSUE TITLE
Rewrite subscriptions with new observables

### ISSUE THREAD

**Issue by KATT** [trpc/trpc#1596]
Related to #1592 / the [`next`](https://github.com/trpc/trpc/tree/next) branch.

Now that we have rxjs added, we might want to use it for our subscription support.

### Before

https://github.com/trpc/trpc/blob/ed62629326ceaa5d56ab91fe3b09ccda25a4dd6c/examples/next-prisma-starter-websockets/src/server/routers/post.ts#L130-L140

### After

```ts
  .subscription('onAdd', {
    resolve() {
      return observable<Post>((emit) => {
        const onAdd = (data: Post) => emit.data(data);
        ee.on('add', onAdd);

        return () => {
          ee.off('add', onAdd);
        };
      });
    },
  })
```

---

The underlying event emitter in the example could also be observables:

https://github.com/trpc/trpc/blob/ed62629326ceaa5d56ab91fe3b09ccda25a4dd6c/examples/next-prisma-starter-websockets/src/server/routers/post.ts#L13-L28

**Comment by john-schmitz** [comment]
Just for context; why was the issue blocked?
I'm very new to the repository and trcps internals

**Comment by sachinraja** [comment]
We were evaluating whether or not to use rxjs and decided not to (see discussion in #1592 for more details).

**Comment by KATT** [comment]
Yeah, what @sachinraja said.

Additionally, this would include moving the observables from `@trpc/client/observables` to server
