### ISSUE TITLE
Decouple `@trpc/server` from node

### ISSUE THREAD

**Issue by KATT** [trpc/trpc#1597]
Related to the [`next`](https://github.com/trpc/trpc/tree/next) branch.

---

Currently, `@trpc/server` is using a lot of Node-based dependencies, i.e. `url`, `http`, etc.

It would be great to decouple `@trpc/server` completely from a node in order to easier deploy tRPC to i.e. CF workers (#1375).

## Proposal

> Please DM me on Discord before addressing this, there might be better implementations ideas, below are my first thoughts.

Rough steps:

- Rename `@trpc/server` to `@trpc/node` (and update all examples, etc)
- Create a new package, `@trpc/core`
- Gradually extract all non-node-specific stuff into a package named `@trpc/core` or similar
  - This requires a lot of refactoring as there are a lot of functions that like [`resolveHTTPResponse`](https://github.com/trpc/trpc/blob/next/packages/server/src/http/resolveHTTPResponse.ts) should still exist as part of `@trpc/core` but with a slightly different signature.
- For ease of installation, `@trpc/node` could have a hard dependency (rather than a peerDep) of `@trpc/core` and `export * from '@trpc/core'`
- Make a CF example in the `./examples` folder
- Make deno.land-module
- This should be done in the [`next`](https://github.com/trpc/trpc/tree/next)-branch

## Payment

I'll pay $200 if someone addresses it. If you think that isn't enough, feel free to contact me. Payment will be through GitHub sponsors - see #1599.

**Comment by KATT** [comment]
cc @esamattis @icflorescu

**Comment by KATT** [comment]
Excited about this! Thanks for taking ownership, @sachinraja!

**Comment by sachinraja** [comment]
Closing this as we've now been able to deploy on CF Workers and Deno
