### ISSUE TITLE
Upgrade to TypeScript `4.6`

### ISSUE THREAD

**Issue by KATT** [trpc/trpc#1600]
The project builds fine when updating the typescript-version, but there is some issue introduced in 4.5 that stops one of the tests. See #1295.

Likely requires some refactoring in order to get it to build reliably.

I think the culprit was https://github.com/trpc/trpc/blob/main/packages/client/src/links/wsLink.ts

Related: 

- #1295
- #1588

**Comment by jsjoeio** [comment]
It looks like this can be closed via https://github.com/trpc/trpc/pull/1777 (thought technically in the `next`) branch.
