### ISSUE TITLE
Cache playwright deps in CI

### ISSUE THREAD

**Issue by KATT** [trpc/trpc#1650]
Most of the CI fails is because Playwright's install deps function fails. It also takes over a minute when it doesn't. Would be nice if it could be cached

https://playwright.dev/docs/ci#caching-browsers

**Comment by sachinraja** [comment]
That's how you can cache the browser binary but the installation of system dependencies is taking the longest. According to https://github.com/microsoft/playwright-github-action/issues/56#issuecomment-1019553187 there's no way to cache them.

**Comment by KATT** [comment]
💔

**Comment by KATT** [comment]
Seems like we could do some improvements:

https://twitter.com/aslushnikov/status/1506697170073706501
