### ISSUE TITLE
Websockets example layout borked on mobile 

### ISSUE THREAD

**Issue by KATT** [trpc/trpc#1691]
Cc @toyamarinyon

![Screenshot_20220324-232124](https://user-images.githubusercontent.com/459267/160025734-fde865c1-f261-4fd1-ae60-69620da5710c.jpg)

**Comment by toyamarinyon** [comment]
I'll check it!

By the way,  When I checked it on iPhone 12, it's be properly. Please let me know the device you checked.
<img src="https://user-images.githubusercontent.com/535254/160092968-e050689b-aa9e-4594-a864-46811c36a9ca.PNG" width="200" />

**Comment by KATT** [comment]
![Screenshot_20220325-195235](https://user-images.githubusercontent.com/459267/160191795-7deda376-f421-4dc5-9c6a-259d33fe938d.jpg)

**Comment by toyamarinyon** [comment]
@KATT thanks! I tried to resolve it at #1729.
