### ISSUE TITLE
feat: if no transformer is defined - serialize types as JSON would

### ISSUE THREAD

**Issue by KATT** [trpc/trpc#1694]
## Goal

Automatically make a safe data transfer object to corresponds to what `JSON.parse(JSON.stringify(obj))` would do.

These 2 are likely two separate PRs/implementations:

- For _outputs_ it's pretty straight-forward
- For _inputs_ we somehow need to disable complex types that are not serializable? Or do some other wild stuff.

**Let's start with outputs.**

<details><summary>Example</summary>
## Example

**Convert this...**

```ts
interface Post {
  author: string
  title: string
  datePublished: Date
}
```

**... into this:**

```ts
// to:
type Post = {
  author: string
  title: string
  datePublished: string // <-- automatic transform according to `JSON.parse()`
}
```

Using only TypeScript generics!

</details>

## Bounty 🤑 

$200

## Overview of how to do it

- Should be done on the `@trpc/client` / `@trpc/react`-level. 
- `router.createCaller()` should not be affected
- We have a `DefaultDataTransformer` that can be used to check if a router or procedure is using a transformer (see #3254 for some initial hacks)
- Might be some tests that have the types assertions (i.e. using `undefined` instead of `null` - update those). If the tests are in `interop/*`, do whatever hack you need to do to make them work

### References

Both MIT, so we can vendor one of these:

- https://github.com/sindresorhus/type-fest/blob/main/source/jsonify.d.ts
- https://github.com/remix-run/remix/blob/main/packages/remix-server-runtime/serialize.ts

**Comment by ecwyne** [comment]
This is a very good idea. This has gotten me in the past

**Comment by KATT** [comment]
Feel free to have a stab at it! :)
