### ISSUE TITLE
Update HTTP headers handling of `undefined`

### ISSUE THREAD

**Issue by ArnaudBarre** [trpc/trpc#1712]
The current typing of headers in `CreateTRPCClientOptions` allow undefined, which at runtime sends `"undefined"`, because the browser expects `Record<string, string>`. 

The simple solution is to remove undefined from typing, the other is to filter out undefined headers (which could be a nice DX when merging auth headers with always sent headers, at the cost to be not very consistent with other libs)

**Comment by jlalmes** [comment]
Opened a PR, please review @ArnaudBarre https://github.com/trpc/trpc/pull/1713
