### ISSUE TITLE
Fastify adapter: Custom content-type parser for application/json is breaking normal REST api requests on a fastify server

### ISSUE THREAD

**Issue by soulsam480** [trpc/trpc#1715]
https://github.com/trpc/trpc/blob/d5808b863490f95ff76defce4886833b11672e88/packages/server/src/adapters/fastify/fastifyTRPCPlugin.ts#L25-L31

This works just fine for tRPC endpoints but breaks other REST api endpoints as `request.body` is a string where it's expected to an object. This can be easily reproduced on the official fastify examples by creating a REST `POST` endpoint and sending some data inside body.

**Comment by soulsam480** [comment]
Currently this is what I'm doing as a hack to fix the issue: 
```ts
  fastify.post<{ Body: LoginPayload }>('/', async ({ body }, reply) => {
    body = typeof body === 'string' ? JSON.parse(body) : body

    const { email, password } = body
```
putting in a runtime check for type `string` and parsing it using `JSON.parse`. This works but is there any way to fix this thing properly ?

**Comment by soulsam480** [comment]
From the fastify docs, I see that contentTypeParse can't be set for some specific set of routes. But a viable solution would be using the request param to check the URL for trpc and only make the body string for that. https://www.fastify.io/docs/latest/Reference/ContentTypeParser/#usage .

I think the user passes the trpc prefix for the server, so maybe we can use that to add a check something like this 
```ts
  fastify.all(`${opts.prefix ?? ''}/:path`, async (req, res) => {
   // make the body string here instead of using contentTypeParser
   
   req.body = JSON.stringify(req.body)
  // this should work as fastify uses JSON.parse to parse body

    const path = (req.params as any).path;
    await fastifyRequestHandler({ ...opts.trpcOptions, req, res, path });
  });
```
@skarab42 Do you think this is possible ?

**Comment by skarab42** [comment]
I need to do some tests and see what would be best to fix the problem.

**Comment by skarab42** [comment]
@soulsam480 I found the problem, I am working on a fix... 

Reading the docs:
> As with the other APIs, `addContentTypeParser` is encapsulated in the scope in which it is declared. This means that if you declare it in the root scope it will be available everywhere, while if you declare it inside a plugin it will be available only in that scope and its children.

I probably broke the encapsulation system with the use of [fastify-plugin](https://github.com/fastify/fastify-plugin), I'm reworking the plugin to allow its use with or without [fastify-plugin](https://github.com/fastify/fastify-plugin).

**Comment by soulsam480** [comment]
Yes exactly. I think if we can match the fastify-plugin type, we don't need to encapsulate it and can use it directly. Thanks for the quick fix.
