### ISSUE TITLE
Testing with Jest

### ISSUE THREAD

**Issue by Raphael0010** [trpc/trpc#1737]
Hi, there is a way to test trpc query with Jest ?.

I'm actually trying to do that : 

```ts
import { trpcClient } from '@project/trpc/dist/trpc'

test('getAllBids', () => {
  const bids = trpcClient.query('bid.getAll')
  expect(bids).toBe('test')
})
```

But I got this error : "Argument of type 'string' is not assignable to parameter of type 'never'."
But when I use it on Next App it's work.
I see nothing about testing in the documentation.

**Comment by LouisHaftmann** [comment]
Have you tried using a route caller?

```tsx
appRouter.createCaller(/* context object */).query('bid.getAll')
```

**Comment by sachinraja** [comment]
You could also use the client if you [pass the type of your router as a type arg](https://trpc.io/docs/vanilla#initialize-a-trpc-client) and your trpc server is running during your tests. Hard to help more than that without a reproduction.

**Comment by KATT** [comment]
There is both jest and playwright in the starter

https://github.com/trpc/examples-next-prisma-starter/tree/main/src/server/routers
