### ISSUE TITLE
Simplify tRPC Request/Response/Message Interfaces

### ISSUE THREAD

**Issue by jlalmes** [trpc/trpc#1778]
Originally posted by @KATT 

> See @jlalmes' PR https://github.com/trpc/trpc/pull/1759
> 
> Potential things. Not definitive, just ideas.
> 
> 
> ## Remove  unused fields
> 
> Before:
> 
> ```js
> [
>   {
>     "id": null,
>     "result": {
>       "type": "data",
>       "data": {
>         "id": "1",
>         "title": "Hello tRPC",
>         "body": "..."
>         // ...
>       }
>     }
>   },
> ]
> ```
> 
> After:
> 
> ```js
> [
>   {
>     "result": {
>       "data": {
>         "id": "1",
>         "title": "Hello tRPC",
>         "body": "..."
>         // ...
>       }
>     }
>   },
> ]
> ```
> 
> ## Changed response to a mapped object
> 
> Potential ease of allowing for streaming... maybe we could start sending response as procedures are finalised and not wait for _all of them_ to be finalized before returning... but it also breaks HTTP-codes so not sure.
> 
> Probably not a good idea, just a thought
> 
> ```js
> {
>   // 0 means index 0 of the batch
>   "0": { 
>     "id": null,
>     "result": {
>       "type": "data",
>       "data": {
>         "id": "1",
>         "title": "Hello tRPC",
>         "body": "..."
>         // ...
>       }
>     }
>   },
> ]
> ```
> 
> ## Remove JSONRPC 
> 
> Remove JSNORPC stuff on the request/response for internal requests...
> 
>

**Comment by jlalmes** [comment]
> cc @KATT

## Documenting the current tRPC API

Thought this would be good for visibility.

#### HTTP Queries
```jsonc
// HTTP Query
/* --> GET /sayHello?input=%7B%22name%22%3A%22tRPC%22%7D */ 
// no body sent
/* <-- */ 
{ "id": null, "result": { "type": "data", "data": { "greeting": "Hello tRPC" } } }

// HTTP Query with request batching
/* --> GET /sayHello,sayHello?batch=1&input=%7B%220%22%3A%7B%22name%22%3A%22tRPC%22%7D%2C%221%22%3A%7B%22name%22%3A%22tRPC2%22%7D%7D */ 
// no body sent
/* <-- */ 
[
  { "id": null, "result": { "type": "data", "data": { "greeting": "Hello tRPC" } } },
  { "id": null, "result": { "type": "data", "data": { "greeting": "Hello tRPC2" } } }
]
```

#### HTTP Mutations
```jsonc
// HTTP Mutation
/* --> POST /sayHello */ 
{ "name": "tRPC" }
/* <-- */ 
{ "id": null, "result": { "type": "data", "data": { "greeting": "Hello tRPC" } } }

// HTTP Mutation with request batching
/* --> POST /sayHello,sayHello?batch=1 */ 
{ "0": { "name": "tRPC" }, "1": { "name": "tRPC2" } }
/* <-- */ 
[
  { "id": null, "result": { "type": "data", "data": { "greeting": "Hello tRPC" } } },
  { "id": null, "result": { "type": "data", "data": { "greeting": "Hello tRPC2" } } }
]
```

#### Websocket Queries
```jsonc
// WS Query
/* --> */ 
{ "id": 1, "jsonrpc" :"2.0", "method": "query", "params": { "input": { "name": "tRPC" }, "path": "sayHello" } }
/* <-- */ 
{ "id": 1, "result": { "type": "data", "data": { "greeting": "Hello tRPC" } } }
```

#### Websocket Mutations
```jsonc
// WS Mutation
/* --> */ 
{ "id": 1, "jsonrpc": "2.0", "method": "mutation", "params": { "input": { "name": "tRPC" }, "path": "sayHello" } }
/* <-- */ 
{ "id": 1, "result": { "type": "data", "data": { "greeting": "Hello tRPC" } } }
```

#### Websocket with message batching
```jsonc
// WS Batched query & mutation
// WS Mutation
/* --> */ 
[
  { "id": 1, "jsonrpc": "2.0", "method": "query", "params": { "input": { "name": "tRPC" }, "path": "sayHello" } }, 
  { "id": 2, "jsonrpc": "2.0", "method": "mutation", "params": { "input": { "name": "tRPC2" }, "path": "sayHello" } }
]
/* <-- */ 
{ "id": 1, "result": { "type": "data", "data": { "greeting": "Hello tRPC" } } }
/* <-- */ 
{ "id": 2, "result": { "type": "data", "data": { "greeting": "Hello tRPC2" } } }
```

#### Websocket Subscriptions
```jsonc
// WS Subscription
/* --> */ 
{ "id": 1, "jsonrpc": "2.0", "method": "subscription", "params": { "input": { "name": "tRPC" }, "path": "sayHello" } }
/* <-- */ 
{ "id": 1, "result": { "type": "started" } }
/* <-- */ 
{ "id": 1, "result": { "type": "data", "data": { "greeting": "Hello tRPC" } } }
```

**Comment by KATT** [comment]
> ## Documenting the current tRPC API
> Thought this would be good for visibility.

YES!  Thank you. Inlining my ideas below.


> 
> #### HTTP Queries
> ```js
> // HTTP Query
> /* --> GET /sayHello?input=%7B%22name%22%3A%22tRPC%22%7D */ 
> // no body sent
> /* <-- */ 
> { "id": null, "result": { "type": "data", "data": { "greeting": "Hello tRPC" } } }

- Keep req as-is
- Res could be `{ "result": { "data": { "greeting": "Hello tRPC" } }`

> 
> // HTTP Query with request batching
> /* --> GET /sayHello,sayHello?batch=1&input=%7B%220%22%3A%7B%22name%22%3A%22tRPC%22%7D%2C%221%22%3A%7B%22name%22%3A%22tRPC2%22%7D%7D */ 
> // no body sent
> /* <-- */ 
> [
>   { "id": null, "result": { "type": "data", "data": { "greeting": "Hello tRPC" } } },
>   { "id": null, "result": { "type": "data", "data": { "greeting": "Hello tRPC2" } } }
> ]
> ```
> 
> #### HTTP Mutations
> ```js
> // HTTP Mutation
> /* --> POST /sayHello */ 
> { "name": "tRPC" }
> /* <-- */ 
> { "id": null, "result": { "type": "data", "data": { "greeting": "Hello tRPC" } } }
> 
> // HTTP Mutation with request batching
> /* --> POST /sayHello,sayHello?batch=1 */ 
> { "0": { "name": "tRPC" }, "1": { "name": "tRPC2" } }
> /* <-- */ 
> [
>   { "id": null, "result": { "type": "data", "data": { "greeting": "Hello tRPC" } } },
>   { "id": null, "result": { "type": "data", "data": { "greeting": "Hello tRPC2" } } }
> ]
> ```
> 
> #### Websocket Queries
> ```js
> // WS Query
> /* --> */ 
> { "id": 1, "jsonrpc" :"2.0", "method": "query", "params": { "input": { "name": "tRPC" }, "path": "sayHello" } }
> /* <-- */ 
> { "id": 1, "result": { "type": "data", "data": { "greeting": "Hello tRPC" } } }
> ```
> 
> #### Websocket Mutations
> ```js
> // WS Mutation
> /* --> */ 
> { "id": 1, "jsonrpc": "2.0", "method": "mutation", "params": { "input": { "name": "tRPC" }, "path": "sayHello" } }
> /* <-- */ 
> { "id": 1, "result": { "type": "data", "data": { "greeting": "Hello tRPC" } } }
> ```
> 
> #### Websocket with message batching
> ```js
> // WS Batched query & mutation
> // WS Mutation
> /* --> */ 
> [
>   { "id": 1, "jsonrpc": "2.0", "method": "query", "params": { "input": { "name": "tRPC" }, "path": "sayHello" } }, 
>   { "id": 2, "jsonrpc": "2.0", "method": "mutation", "params": { "input": { "name": "tRPC2" }, "path": "sayHello" } }
> ]
> /* <-- */ 
> { "id": 1, "result": { "type": "data", "data": { "greeting": "Hello tRPC" } } }
> /* <-- */ 
> { "id": 2, "result": { "type": "data", "data": { "greeting": "Hello tRPC2" } } }
> ```
> 
> #### Websocket Subscriptions
> ```js
> // WS Subscription
> /* --> */ 
> { "id": 1, "jsonrpc": "2.0", "method": "subscription", "params": { "input": { "name": "tRPC" }, "path": "sayHello" } }
> /* <-- */ 
> { "id": 1, "result": { "type": "started" } }
> /* <-- */ 
> { "id": 1, "result": { "type": "data", "data": { "greeting": "Hello tRPC" } } }
> ```

**Comment by jlalmes** [comment]
🔧   _I have added the missing websocket subscription messages to the documentation above._

## 🤝  Change proposals

### HTTP
Remove `"id": null` from response envelopes  
  > Res should be one of these:
  
  Option 2

### WS
Remove `"jsonrpc": "2.0"` key on client->server messages (https://github.com/trpc/trpc/pull/1759)

## 💭  Some additional thoughts: 

#### HTTP Mutations
> Potentially it could be { "input": { "name": "tRPC" } }

I prefer keeping the request payload as-is currently (unwrapped). This keeps input payloads consistent between queries & mutations.

#### HTTP Batched Requests

> potentially change `?batch=1` to `?batch` without the =

Although it's valid, are you sure we want to do this? I rarely see query params without a value pair - could be confusing 🤷‍♂️

> Keep req as-is

Currently the client sends the `input` payload of batched requests as an indexed object: `{ "0": { "name": "tRPC" }, "1": { "name": "tRPC2" } }`. Is there a reason why we don't we send these payloads as an array type? i.e. `[{ "name": "tRPC" }, { "name": "tRPC2" }]`. The resulting input strings from `encodeURIComponent(JSON.stringify(...))` are far shorter as an array type than an indexed object.

#### WS server->client messages

> As always, "type" could be omitted.

I'm not sure this can be omitted if we are still supporting the `"type": "started"`,  `"type": "ended"` messages?

**Comment by jlalmes** [comment]
### Another thought about HTTP Response envelopes

*Original*
```jsonc
{ "id": null, "result": { "type": "data", "data": { "greeting": "Hello tRPC" } } }
```

*After omit `"id": null`& `"type": "data"` (proposed above)*
```jsonc
{ "result": { "data": { "greeting": "Hello tRPC" } } }
```

**Why don't we also just remove the `result.data` wrapper?**
```jsonc
{ "greeting": "Hello tRPC" }

// batched request response
[
  { "greeting": "Hello tRPC" },
  { "greeting": "Hello tRPC2" }
]
```

**Comment by jlalmes** [comment]
> > Is there a reason why we don't we send these payloads as an array type?
> 
> To correctly serialize `undefined`: [#669 (comment)](https://github.com/trpc/trpc/pull/669#issuecomment-882703759)

Thanks @sachinraja! Understood 👍

**Comment by KATT** [comment]
> **Why don't we also remove the `result.data` wrapper?**
> 
> ```js
> { "greeting": "Hello tRPC" }
> 
> // batched request response
> [
>   { "greeting": "Hello tRPC" },
>   { "greeting": "Hello tRPC2" }
> ]
> ```

It's a good idea and I was thinking about that for a while but I probably will want to decorate responses with extra metadata in the future.

One of the ideas I've been toying with is an edge-cached tRPC service that could work a bit like [GraphCDN](https://graphcdn.io/) - for that to work I would need to provide caching hints for each individual procedure.
