### ISSUE TITLE
Add test for `jsonrpc` being included in response

### ISSUE THREAD

**Issue by KATT** [trpc/trpc#1785]
We need a test that actually asserts this otherwise I will break it eventually, guaranteed

Here's a websocket raw client test we can use as a base 

https://github.com/trpc/trpc/blob/97039a761b8704b980fe1a62eaadb5af84942754/packages/server/test/websockets.test.ts#L473-L510

_Originally posted by @KATT in https://github.com/trpc/trpc/pull/1780#discussion_r850320892_

**Comment by jlalmes** [comment]
Closed by https://github.com/trpc/trpc/pull/1786
