### ISSUE TITLE
Next example is not working in Next 12.1.5

### ISSUE THREAD

**Issue by Dimirolz** [trpc/trpc#1789]
Hi, when I try to use the [NextJS documentation example](https://trpc.io/docs/nextjs), I get an error.
`TypeError: Cannot read properties of null (reading 'client')`
It's happend in NextJS 12.1.5 version.

When lower version to 12.1.4 everything starts working correctly.

**Comment by sachinraja** [comment]
See vercel/next.js#36115, this is an issue with next.

**Comment by Dimirolz** [comment]
Thanks for fast feedback!
You can close this issue.

**Comment by sachinraja** [comment]
I think we should keep this open until it's fixed in Next so people can see we are aware of it

**Comment by KATT** [comment]
I also locked the version in the examples (#1781), but yeah, could keep it open.

**Comment by p6l-richard** [comment]
Updating to NextJS' 12.1.6 canary resolved the issue for me.

I see that the version has been updated also in the example.

**Comment by bratsos** [comment]
Is this still an issue for anyone else? I tried upgrading `next` to `12.1.6`, `12.1.7-canary` and `12.1.4` and `@trpc/*` to `9.23.4` but I'm still getting this error. I also tried `rm -rf node_modules && rm -rf .next && yarn install` after each change on `package.json`

**Comment by Je12emy** [comment]
I'm also facing this issue after moving my code from the root directory on a newly created next app into a `src` directory, before this move tRPC was working fine, but now I receive this same error, here's a repository to replicate my issue: https://github.com/Je12emy/twitter-nextjs/tree/trpc_port
