### ISSUE TITLE
Add tailwind to docs site

### ISSUE THREAD

**Issue by KATT** [trpc/trpc#1800]
**Goals:**

- Be able to use tailwind on the frontpage
- Being able to import smart components in the mdx and use tailwind in those
- Not breaking the whole standard layout and still have the current page look good without much tweaking

I've pinged @sajclarke who made [this post](https://dev.to/sajclarke_62/using-tailwindcss-v3-in-docusaurus-in-5-steps-5c26) to see if he wants to help :)

**Comment by katungi** [comment]
Hey @KATT, i'd be willing to pick this one up if @sajclarke doesn't pick it up :)

**Comment by sajclarke** [comment]
I took a swing at it @katungi but feel free to review
