### ISSUE TITLE
Idea: Add `maxBatchURILength` config option to `httpBatchLink`

### ISSUE THREAD

**Issue by jlalmes** [trpc/trpc#1801]
https://trpc.io/docs/links#setting-a-maximum-batch-size

## Idea: 
The maximum number of requests that can be batched at one time is currently limited by the `maxBatchSize` config option. There are cases where queries contain large input payloads and therefore, when batched, exceed the maximum URI length of the deployment environment before being split up by the `maxBatchSize` limit (cc. https://github.com/trpc/trpc/discussions/1792)

### Proposal
Add a new config option `maxBatchURILength`(?) to the `httpBatchLink` that will split the batch into smaller chunks before sending requests if the initial batch URI exceeds the limit.

**Comment by KATT** [comment]
Yep. Would be better, this was initially what I wanted to do but it required a lot of refactoring so I took the shortcut. 

Happy to do a breaking change on this for the next major - both features do not need to exist.

See the original issue at #506

**Comment by KATT** [comment]
I changed it to "Maybe" as it's a nice-to-have but feel free to attack it, @jlalmes!

**Comment by jlalmes** [comment]
Note to self: #1812
