### ISSUE TITLE
Make example with ultra

### ISSUE THREAD

**Issue by KATT** [trpc/trpc#1804]
An example using [Ultra](https://ultrajs.dev/docs) would be awesome. Looks like a nice future for doing React 18 - @mashaal has done some incredible work. 

I don't have time to tinker with this myself with all the other v10 features, but if someone feels inclined, feel free to do so **using the [`next`](https://github.com/trpc/trpc/tree/next)** branch.

@sachinraja has previously done a build of tRPC that should(?) work in Deno - would be super cool to see the Ultra + tRPC  projects work together.

**Comment by sachinraja** [comment]
It has a lot of issues that need upstream fixes, but https://github.com/sachinraja/trpc-ultra
