### ISSUE TITLE
Swap HTTP Status for mixed responses statuses?

### ISSUE THREAD

**Issue by KATT** [trpc/trpc#1809]
Given 2 procedures, this is what tRPC currently returns:

- 2x `NOT_FOUND` errors  ==> `404`
- 2x succeeds => `200`
- 1x succeeds + 1x `NOT_FOUND` error => `207`

I picked `207 Multi-Status` as it seemed the most appropriate code, but since it's a `2XX` it also doesn't show up as a "failed" request in for instance chrome network tab. Unsure what HTTP-caching layers do with it (hopefully not cache it).

I'm debating with myself if this should be switched to another one. 

The only appropriate one I can think of in the [Wikipedia page of List of HTTP status codes](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes) is "424 Failed Dependency": 

> The request failed because it depended on another request and that request failed (e.g., a PROPPATCH).[[16]](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#cite_note-RFC_4918-17)

Does anyone have any good ideas about what would be good here?

**Comment by Rinzlit** [comment]
Seems like you've nailed it with 207, at least from what I've seen from. https://www.rfc-editor.org/rfc/rfc4918.html
They seemed to be thinking almost the same thing.

**Comment by Rinzlit** [comment]
Also looked into Cloudflare and found their default caching is 

> 
HTTP status code | Default TTL
-- | --
200, 206, 301 | 120m
302, 303 | 20m
404, 410 | 3m
403 | 0s
500, 502, 503, 504 | 0s
> 
Source: https://developers.cloudflare.com/cache/how-to/configure-cache-status-code/

There should not be any issues with Cloudflare at least when using HTTP status code `207`
