### ISSUE TITLE
Context swapped in by middleware is lost after chaining through another middleware

### ISSUE THREAD

**Issue by matthijscollabai** [trpc/trpc#1833]
### Scenario:
- Add a middleware on a router that has context set to A
  - Call `next` with a new context B
- Stack another middleware on top
  - Call `next` without passing on a specific context
- Add a query and use the context

### Expected result:
The query's context is context B

### Actual result:
The query's context is context A (but in Typescript, the context type now suggests it is context B)

### Code sample:
```
const router = createRouter()
    .middleware(({ next }) => {
        return next({ ctx: "modified" });
    })
    .middleware(({ ctx, next }) => {
        // ctx is "modified"
       return next();
    })
    .query("foo", {
        resolve({ ctx }) {
            // ctx is now "original" again
        }
    });

app.use(
  '/trpc',
  trpcExpress.createExpressMiddleware({
    router,
    createContext() {
        return "original";
    },
  })
);
```

**Comment by KATT** [comment]
If this is the case, it's a bug, will investigate

Cc @mmkal @jlalmes

**Comment by KATT** [comment]
@all-contributors add @matthijscollabai for bug report
