### ISSUE TITLE
Different types of `middlewareMarker`

### ISSUE THREAD

**Issue by luixo** [trpc/trpc#1900]
Hello,

We have two separate folder for backend and frontend in our repo (no workspace setup) as they are compiled in their respective directories.

In an attempt to introduce `trpc` I stumbled upon an issue that we have two copies of `@trpc/server` package - both in server's and in client's `node_modules`.
The problem is that when I import `AppRouter` type from the server to client - I get a type mismatch of the `middlewareMarker` which is a symbol created in [middlewares.ts](https://github.com/trpc/trpc/blob/4c91e920529daa4f7c1a88cbc7b0db8a5ed405ce/packages/server/src/internals/middlewares.ts#L4).
It seems like I have two symbols that are by definition different.

Is it intended to be so?
Do I have to migrate to common `node_modules` (via workspaces) or there is a way around it?

The code:
```ts
// backend/index.ts
import * as trpc from "trpc/server";

const router = trpc.router();
export type AppRouter = typeof router;
```

```ts
// frontend/index.ts
import {createReactQueryHooks} from "@trpc/react";
import type { AppRouter } from "../backend/index";

export const trpc = createReactQueryHooks<AppRouter>();
```

The error:
```ts
(property) BaseHandlerOptions<AnyRouter<any>, e.Request<ParamsDictionary, any, any, QueryString.ParsedQs, Record<string, any>>>.router: AnyRouter<any>
Type 'Router<Context, Context, {}, Record<"path", Procedure<Context, Context, {}, undefined, undefined, BlockView, unknown, BlockView>>, Record<...> & ... 37 more ... & Record<...>, Record<...>, DefaultErrorShape>' is not assignable to type 'AnyRouter<any>'.
  The types of '_def.middlewares' are incompatible between these types.
    Type 'MiddlewareFunction<Context, Context, {}>[]' is not assignable to type 'MiddlewareFunction<any, any, any>[]'.
      Type 'MiddlewareFunction<Context, Context, {}>' is not assignable to type 'MiddlewareFunction<any, any, any>'.
        Types of parameters 'opts' and 'opts' are incompatible.
          Type '{ ctx: any; type: ProcedureType; path: string; rawInput: unknown; meta?: any; next: { (): Promise<MiddlewareResult<any>>; <T>(opts: { ctx: T; }): Promise<MiddlewareResult<T>>; }; }' is not assignable to type '{ ctx: Context; type: ProcedureType; path: string; rawInput: unknown; meta?: {} | undefined; next: { (): Promise<MiddlewareResult<Context>>; <T>(opts: { ...; }): Promise<...>; }; }'.
            The types returned by 'next()' are incompatible between these types.
              Type 'Promise<MiddlewareResult<any>>' is not assignable to type 'Promise<MiddlewareResult<Context>>'.
                Type 'MiddlewareResult<any>' is not assignable to type 'MiddlewareResult<Context>'.
                  Type 'MiddlewareOKResult<any>' is not assignable to type 'MiddlewareResult<Context>'.
                    Type 'MiddlewareOKResult<any>' is not assignable to type 'MiddlewareOKResult<Context>'.
                      Types of property 'marker' are incompatible.
                        Type 'typeof import("/.../backend/node_modules/@trpc/server/dist/declarations/src/internals/middlewares").middlewareMarker' is not assignable to type 'typeof import("/.../frontend/node_modules/@trpc/server/dist/declarations/src/internals/middlewares").middlewareMarker'.ts(2322)
BaseHandlerOptions.d.ts(11, 5): The expected type comes from property 'router' which is declared here on type 'NodeHTTPHandlerOptions<AnyRouter<any>, Request<ParamsDictionary, any, any, ParsedQs, Record<string, any>>, Response<any, Record<string, any>>>'
```

**Comment by KATT** [comment]
Hmmmm. That's unfortunate. I'm lost for ideas for a workaround other than making sure that you only have one `@trpc/*` in `node_modules`.

I'd like this not to be a requirement though, but failing to think of a good solution. I'm surprised it complains, to be honest.

Maybe it could be a branded type with a `_tag: string` rather than a `_middlewareMarker: Symbol`.

@mmkal - a penny for your thoughts 🙏

**Comment by mmkal** [comment]
Yes, I didn’t realise this would happen in non-monorepo setups but I suppose it makes sense. A symbol is probably overly strict in that case. I imagine there’ll be a way to make it work but I agree, a string would be fine as a replacement.

**Comment by sachinraja** [comment]
I also think the branded type would be better. I think it would help fix some type errors in Deno.
