### ISSUE TITLE
Type Errors

### ISSUE THREAD

**Issue by grebaldi** [trpc/trpc#1904]
Hi there,

first of all: Thanks a lot for creating trpc :) I just recently stumpled upon it and I'm quite enthusiastic about it's design.

Now to the problem:

I'm trying to use trpc in a pnpm-driven monorepo. When I try to compile the package that's using trpc (both `@trpc/server` and `@trpc/client`), `tsc` fails with:

```
../../../../node_modules/.pnpm/@trpc+server@9.23.4/node_modules/@trpc/server/dist/declarations/src/adapters/node-http/types.d.ts:3:16 - error TS2307: Cannot find module 'qs' or its corresponding type declarations.

3 import qs from 'qs';

[...]

../../../../node_modules/.pnpm/@trpc+server@9.23.4/node_modules/@trpc/server/dist/declarations/src/adapters/standalone.d.ts:5:107 - error TS2344: Type 'IncomingMessage' does not satisfy the constraint 'NodeHTTPRequest'.
  Type 'IncomingMessage' is not assignable to type '{ method?: string; query?: any; body?: unknown; }' with 'exactOptionalPropertyTypes: true'. Consider adding 'undefined' to the types of the target's properties.
    Types of property 'method' are incompatible.
      Type 'string | undefined' is not assignable to type 'string'.
        Type 'undefined' is not assignable to type 'string'.

5 export declare type CreateHTTPHandlerOptions<TRouter extends AnyRouter> = NodeHTTPHandlerOptions<TRouter, http.IncomingMessage, http.ServerResponse>;
```

The first one
```
TS2307: Cannot find module 'qs' or its corresponding type declarations.
```

can be fixed by installing `@types/qs`. However, I don't think that should be necessary.

The second one
```
TS2344: Type 'IncomingMessage' does not satisfy the constraint 'NodeHTTPRequest'.
```
isn't explicable to me but at least resembles one of the errors documented in #1022.

This issue was closed by  #1151, which should be included with the trpc version I'm using (9.23.4).

It's possible that this is related to my use of pnpm.

Any hint would be appreciated :) I'll keep you posted, if I find anything myself.

**Comment by grebaldi** [comment]
For anybody passing by here:

Using `skipLibCheck` in the respective `tsconfig.json` can be a viable workaround for this issue:
```json
{
  "compilerOptions": {
    "skipLibCheck": true
  }
}
```

It comes with its own drawbacks though: https://www.typescriptlang.org/tsconfig#skipLibCheck (Therefore it's not a replacement for a proper solution of the underlying problem)

**Comment by KATT** [comment]
Can you try installing `@types/node`?

**Comment by KATT** [comment]
Otherwise, please create a reproduction repo and we'll have a look

**Comment by sachinraja** [comment]
Are you using pnpm@7?

**Comment by grebaldi** [comment]
@sachinraja 
> Are you using pnpm@7?

Good point. I thought I did, but apparently I don't. I'll update and see if that changes anything.

**Comment by sachinraja** [comment]
I didn't properly read the error, it's caused by your use of `exactOptionalPropertyTypes: true` in which `method?: string` and `method?: string | undefined` are no longer the same thing. For the qs error, we should remove our dependence on `@types/qs`.

**Comment by sachinraja** [comment]
As a side note, what server side handler are you using? I think most people don't get the `@types/qs` error because they have `@types/express` installed.

**Comment by grebaldi** [comment]
@sachinraja 

> As a side note, what server adapter are you using? I think most people don't get the `@types/qs` error because they have `@types/express` installed (which depends on `@types/qs`).

Then it's plausible I'm getting the error, because I'm using `fastify` :)

@KATT

Here's a minimal reproduction: https://github.com/grebaldi/trpc-1904-repro

**Comment by grebaldi** [comment]
Thanks a lot, @sachinraja & @KATT - fix works like a charm.

You guys are great! :+1:
