### ISSUE TITLE
Types suddenly breaks

### ISSUE THREAD

**Issue by bartoszkrawczyk2** [trpc/trpc#1916]
Hi!

I have an issue with next project and types. After installing some packages (completely unrelated to trpc) every query now returns "any". I've tried reverting all the changes, removing node_modules and installing it again, but all trpc queries returns any and `next build` throws `Parameter '{some variable from trpc.useQuery}' implicitly has an 'any' type`.

Do you have any ideas what could cause it?

It's hard to give example code to reproduce because I used exact configuration as in trpc docs: https://trpc.io/docs/nextjs and it worked fine util I've run `yarn add {something}`

Thanks

**Comment by bartoszkrawczyk2** [comment]
It was an issue with Prisma, not with tRPC. Prisma broke and was returning any from all my tRPC routes.

**Comment by elspecal** [comment]
had the same issue. in my case the ts lang server started to report false error messages. i fixed that by removing and re-installing `node_modules`. that is when i faced the above `implicit any` issue. had to regenerate the prisma client by running `prisma generate`
