### ISSUE TITLE
Bug: Type does not satisfy the constraint 'Router<any, any, any, any, any, any, any>'.

### ISSUE THREAD

**Issue by michealroberts** [trpc/trpc#1941]
Hi, since upgrading to the latest version of tRPC (v9.23.6 for both client and server) ... I'm seeing the following error:

```
Type 'Router<NotAuthed | IsAuthed, NotAuthed | IsAuthed, {}, Record<"", Procedure<NotAuthed | IsAuthed, NotAuthed | IsAuthed, ... 5 more ..., { ...; }>> & Prefixer<...>, Prefixer<...>, Prefixer<...>, DefaultErrorShape>' does not satisfy the constraint 'Router<any, any, any, any, any, any, any>'.
```
As well as:

```
The inferred type of 'client' cannot be named without a reference to '@observerly/pleiades/node_modules/@trpc/server/dist/declarations/src/internals/procedure'. This is likely not portable. A type annotation is necessary.
```

I'm not sure if this is VScode, or an issue with tRPC. But I would really welcome some help on this issue...

<img width="1349" alt="Screenshot 2022-05-26 at 15 33 28" src="https://user-images.githubusercontent.com/84131395/170509839-0b8f4db2-d4e2-4b55-8058-cba52bb4279f.png">

<img width="1153" alt="Screenshot 2022-05-26 at 15 33 50" src="https://user-images.githubusercontent.com/84131395/170509902-91c22f17-52af-4e8c-968e-b6dd36c7dd7a.png">

The breaking code in question is here:

```ts
/**
 *
 * Creates tRPC Client for query and mutation calls
 *
 */
export const client = createTRPCClient<AppRouter>({
  url: 'http://0.0.0.0:8980/api/v1'
})
```

But it is exactly as the documentation describes ... 🤔 

Help! :)

**Comment by michael-observerly** [comment]
Closing

reason: version mismatches between monorepo packages (@trpc/server v.9.23.4 / 9.23.6).
