### ISSUE TITLE
Support timeout on SSR

### ISSUE THREAD

**Issue by luixo** [trpc/trpc#1942]
Hello,
I recently started to migrate a big project on Next.js to TRPC and stumbled upon a problem.

Some of my queries might be quite slow and I want to serve user a page with semi-loaded content to load it later on client-side. As for now, I didn't find anything easy-to-use to bail-out after some timeout and just dehydrate whatever cache I get at the moment.

I used `patch-package` to fit it in my setup and got this diff:

```diff
diff --git a/packages/next/src/withTRPC.tsx b/packages/next/src/withTRPC.tsx
index e7fdf745..7d62a69e 100644
--- a/packages/next/src/withTRPC.tsx
+++ b/packages/next/src/withTRPC.tsx
@@ -54,6 +54,7 @@ function transformQueryOrMutationCacheErrors<
 export type WithTRPCConfig<TRouter extends AnyRouter> =
   CreateTRPCClientOptions<TRouter> & {
     queryClientConfig?: QueryClientConfig;
+    ssrTimeout?: number;
   };

 export function withTRPC<TRouter extends AnyRouter>(
@@ -185,7 +186,7 @@ export function withTRPC<TRouter extends AnyRouter>(
           }

           // wait until the query cache has settled it's promises
-          await new Promise<void>((resolve) => {
+          const prefetchPromise = new Promise<void>((resolve) => {
             const unsub = queryClient.getQueryCache().subscribe((event) => {
               if (event?.query.getObserversCount() === 0) {
                 resolve();
@@ -193,6 +194,19 @@ export function withTRPC<TRouter extends AnyRouter>(
               }
             });
           });
+          if (typeof config.ssrTimeout === 'number') {
+            await Promise.race([
+              prefetchPromise,
+              new Promise((resolve) => {
+                setTimeout(() => {
+                  void queryClient.cancelQueries();
+                  resolve(undefined);
+                }, config.ssrTimeout);
+              }),
+            ]);
+          } else {
+            await prefetchPromise;
+          }
         }
         const dehydratedCache = dehydrate(queryClient, {
           shouldDehydrateQuery() {
```

It's not really flexible (I may want to change `ssrTimeout` depending on ctx - say, path), but good enough for me.
I tried to manage this problem through a link, but couldn't work it out.

Could it be that I missed some other opportunity to handle that by overseeing some features?
If not - I'm ready to make a proper PR with maintainers blessings and architectural decision.

**Comment by luixo** [comment]
It happens in my project that the same query might take .5s or 10s to load depending on parameters, and the page might have multiple queries rendered on it.
So I prefer to have some timeout in which all the queries might be already fetched or some of them might not.
I'll do my best to make a PR with all the batteries included :)

**Comment by sachinraja** [comment]
I would suggest opting out of SSR for specific queries ([docs](https://trpc.io/docs/reactjs/usequery)) if you know they take a long time. I don't think there's enough of a need here to add an `ssrTimeout` though.
