### ISSUE TITLE
react hooks not using data transformer

### ISSUE THREAD

**Issue by baldwin-dev-co** [trpc/trpc#1979]
I've setup my react project according to the docs, but when I use the hooks, it doesn't seem to use the data transformer.

Here is my trpc setup
```tsx
import type { Router } from '..'
import superjson from 'superjson'

export const trpc = createReactQueryHooks<Router>()

export const trpcClient = trpc.createClient({
	url: 'http://localhost:8080',
	transformer: superjson,
	headers: () => ({ Authorization: getAuthHeader() }),
})

export const queryClient = new QueryClient({
	defaultOptions: {
		queries: { refetchOnWindowFocus: false, retry: false, refetchOnMount: false },
		mutations: { retry: false },
	},
})

ReactDOM.render(
	<React.StrictMode>
		<trpc.Provider client={trpcClient} queryClient={queryClient}>
			<QueryClientProvider client={queryClient}>
				<App />
			</QueryClientProvider>
		</trpc.Provider>
	</React.StrictMode>,
	document.getElementById('root')
)
```

And this is how I am using the hooks inside the
```tsx
const AppHeader: React.FC = () => {
	const { data: school, isLoading } = trpc.useQuery([
		'school.get',
		{ id: schoolId }, //schoolId is a bigint here
	])

	return <></>
}
```
And i'm getting this error `Uncaught TypeError: BigInt value can't be serialized in JSON` which shouldn't happen if the transformer was being called.

**Comment by jlalmes** [comment]
Have you added `.transformer(superjson)` to your server-side tRPC router?

**Comment by baldwin-dev-co** [comment]
Yes I have, but this error is occurring on the client side before any requests are being sent so it's not a server issue

**Comment by sachinraja** [comment]
You need to add the transformer to your client too: https://trpc.io/docs/data-transformers#2-add-to-createtrpcclient-or-withtrpc-config

**Comment by sachinraja** [comment]
Do you have a reproduction?

**Comment by baldwin-dev-co** [comment]
just put this together [sandbox](https://codesandbox.io/embed/suspicious-gauss-jhcq7x?fontsize=14&hidenavigation=1&theme=dark)

**Comment by jlalmes** [comment]
Looks like this is an issue with `react-query` being unable to create a hash of a `BigInt` here: https://github.com/TanStack/query/blob/cca1bbfb9abf12bf3341c7cfb6e034a5ebab1379/src/core/utils.ts#L267-L278

`trpc` & `superjson` transformers are working correctly otherwise. @baldwin-dev-co, do you want to create an issue with this bug in [react-query](https://github.com/TanStack/query) GitHub repo or shall I?

**Comment by sachinraja** [comment]
Good debugging @jlalmes. It seems like you would have to provide your own hash function though: https://github.com/TanStack/query/discussions/2450

**Comment by jlalmes** [comment]
Excellent @sachinraja! So to be clear the solution is as follows (tested):

```ts
const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      queryKeyHashFn: (queryKey) => {
        return JSON.stringify(superjson.serialize(queryKey))
      },
    },
  },
});
```

**Comment by baldwin-dev-co** [comment]
Perfect, that got it working, thanks for your help
