### ISSUE TITLE
Procedure specific custom request headers

### ISSUE THREAD

**Issue by KATT** [trpc/trpc#2018]
### Discussed in https://github.com/trpc/trpc/discussions/2017

<div type='discussions-op-text'>

<sup>Originally posted by **skovhus** June 17, 2022</sup>
From the documentation and code example it seems like Client side HTTP headers can only be configured in the tRPC client and not call site when doing a query or mutation. 

But there are use cases where you want to pass in specific headers for a single procedure. What is the recommended way here? Is that something we lack support for? 

Example use case: Elevated privileges that would update the authorization header for a single procedure. </div>

**Comment by KATT** [comment]
@skovhus 

It's totally possible to dynamically opt-out of batching for the ones you have: https://trpc.io/docs/links#using-a-splitlink-to-control-request-flow

I see something like this

It could be something like:

### Client usage

```ts
const postResult = client.query('posts', null, {
  context: {
    headers: {
       x: 'y',
    }
  },
})
```

### Link

```ts
const client = createTRPCClient<AppRouter>({
  links: [
    // call subscriptions through websockets and the rest over http
    splitLink({
      condition(op) {
        // check for context property `skipBatch`
        return op.context.headers;
      },
      // when condition is true, use normal request
      true: httpLink({
        url,
        headers: op.context.headers,
      }),
      // when condition is false, use batching
      false: httpBatchLink({
        url,
      }),
    }),
  ],
});
```

**Comment by KATT** [comment]
@skovhus have a look at the above (just updated)... not super happy with the API, it's a quite implicit and frail relationship

**Comment by skovhus** [comment]
Thanks for the proposal. So if I understand this correctly splitLink is running for each procedure? Is a procedure the same as an operation? Why is headers given a list of operations? Does an operation map to procedure? For this to work then the headers operation needs to be running after the splitLink code. 

Is the only thing missing for this to work some support for retrieving information from the procedures in the headers function?

**Comment by KATT** [comment]
> Thanks for the proposal. So if I understand this correctly splitLink is running for each procedure? Is a procedure the same as an operation? 

Correct, an "operation" is a procedure **call** from the client.

> Why is headers given a list of operations? 

Because the request can be several calls at once in the case of batching

> Does an operation map to procedure? For this to work then the headers operation needs to be running after the splitLink code.

Yeah, the headers-callback runs at the very end, it's reused for both batchLink and httpLink (in the current design (maybe this should be decoupled?))

> 
> Is the only thing missing for this to work some support for retrieving information from the procedures in the headers function?

Yes, that's what I think

**Comment by skovhus** [comment]
What I would add to this is support for the header function to be async + make it possible to type the `context`. A good case for this is when using elevated authentication for some endpoints:

```typescript
const postResult = client.query('posts', null, {
  context: {
    auth: 'elevated'
  },
})

const client = createTRPCClient<AppRouter>({
  links: [
    splitLink({
      condition(op) {
        // check for context property `skipBatch`
        return op.context.auth === 'elevated';
      },
      // when elevated, use normal request to only send elevated access token to this procedure
      true: httpLink({
        url,
      }),
      // when not elevated, use batching
      false: httpBatchLink({
        url,
      }),
    }),
  ],
  headers: async ({ operations }) => {
    if (operations.length === 1 && operations[0].context.auth === 'elevated') {
      // NOTE: this is async as it might require the user to type in a code or click a link in an email
      const bearer = await getElevatedAccessToken()
      return {
             ...(bearer && {Authorization: `Bearer ${bearer}`}),
      };
    }
    const bearer = getRegularAccessToken()
    return {
       ...(bearer && {Authorization: `Bearer ${bearer}`}),
    }
  }
});
```

**Comment by KATT** [comment]
Thinking about this a bit more, it might be better to instead move `headers()`-fn to the `httpBatchLink`/`httpLink`/etc, so they can have a bit less confusing signature.. additionally, tRPC isn't tied to the transport format so it might make more sense to decouple this completely from `TRPCClient`.

So rather than doing what you propose above, I might be more inclined to do this:


```ts
const postResult = client.query('posts', null, {
  context: {
    auth: 'elevated'
  },
})

const client = createTRPCClient<AppRouter>({
  links: [
    splitLink({
      condition(op) {
        // check for context property `skipBatch`
        return op.context.auth === 'elevated';
      },
      // when elevated, use normal request to only send elevated access token to this procedure
      true: httpLink({
        url,
        // optional:
        async headers({op}) {
           // single operation is passed to `op`
           // [...]
           return {}
        }
      }),
      // when not elevated, use batching
      false: httpBatchLink({
        url,
        // optional:
        async headers({ ops }) {
           // here `ops` is an array of operations
           // [...]
           return {}
        }
      }),
    }),
  ],
});
```

The outstanding question is what should happen if someone has headers **both** in their link and defined in the client? Which takes precedence? Do we throw an error / show a warning?


Another thing that I've had in mind before, is how one can access React's context within these as they are defined "outside" of React -- I don't have a good answer to that.


@jlalmes, @sachinraja -- a penny for your thoughts 🙏

**Comment by KATT** [comment]
cc @zomars @abhayvatsa @leog


The question to answer is _"How do we handle when a specific procedure should be called with custom headers?"_

Please read through the thoughts above 🙏

**Comment by sachinraja** [comment]
> move headers()-fn to the httpBatchLink/httpLink/etc, so they can have a bit less confusing signature

This is a great idea! I'm all for decoupling where it makes sense.

> what should happen if someone has headers both in their link and defined in the client

Maybe this shouldn't be possible at all? I thought the proposal was to remove it from the client. If you mean to avoid a breaking change, I think it's fine to break here. If you don't want to break, then I would prefer throwing an error, don't see a point in having a warning when introducing a new feature.

> how one can access React's context within these as they are defined "outside" of React -- I don't have a good answer to that, but probably doable already as long as the client is defined within the main <App />

I assume it's possible too for the same reason. I think Next's upcoming new routing will help solve some these issues.

**Comment by skovhus** [comment]
> Maybe this shouldn't be possible at all? I thought the proposal was to remove it from the client.

I assume the common use case if to add a header to all request, and procedure specific custom request headers is the edge case. I don't really like the ergonomics of removing `headers` from client if it means everyone needs to define the httpBatchLink and httpLink in order to send a header.

> what should happen if someone has headers both in their link and defined in the client

My suggestion would be to merge the two, but take precedence to the headers defined in the link. The client headers can be seen as base headers that can be overridden by links. In the use case I presented (elevated auth token), the default `Authorization` header would be set on the client, but this header might be overridden in some cases in the links.

An alternative to the magic merging would be to pass in the baseHeaders to the links functions. 

> how one can access React's context within these as they are defined "outside" of React -- I don't have a good answer to that, but probably doable already as long as the client is defined within the main <App />

Can you explain why this is needed to support this? :)

**Comment by KATT** [comment]
> > Maybe this shouldn't be possible at all? I thought the proposal was to remove it from the client.
> 
> I assume the common use case if to add a header to all request, and procedure specific custom request headers is the edge case. I don't really like the ergonomics of removing `headers` from client if it means everyone needs to define the httpBatchLink and httpLink in order to send a header.
> 
> > what should happen if someone has headers both in their link and defined in the client
> 
> My suggestion would be to merge the two, but take precedence to the headers defined in the link. The client headers can be seen as base headers that can be overridden by links. In the use case I presented (elevated auth token), the default `Authorization` header would be set on the client, but this header might be overridden in some cases in the links.
> 
> An alternative to the magic merging would be to pass in the baseHeaders to the links functions.

I think the best solution is to keep it on the respective ending links and not be smart about merging. Will be easy to deprecate.

> > how one can access React's context within these as they are defined "outside" of React -- I don't have a good answer to that, but probably doable already as long as the client is defined within the main
> 
> Can you explain why this is needed to support this? :)

Ignore this :)

**Comment by zomars** [comment]
Just my two cents... Why don't we just can pass headers to individual endpoint. I think that's the expected location to be and then core can separate those endpoints and leave them out of batching (We should document this behavior tho). So we can just do:

```ts
// By setting custom headers HERE, you're opting out of batching (as stated in the future docs)
// You can add headers to a batch using a splitLink in config
const postResult = client.query('posts', null, {
  context: {
    headers: {
       x: 'y',
    }
  },
})
```

**Comment by skovhus** [comment]
> Why don't we just can pass headers to individual endpoint.

That was also my initial though, to abstract this away... Works well for static headers, but it doesn’t work that when getting header values are async (example use case: elevated authentication). But maybe it could be an async function that you pass.

**Comment by zomars** [comment]
I don't this that should be tRPC's responsibility @skovhus Similar on how you can pass options to `fetch` however you like. Also with this we're going more into `react-query` territory than tRPC's.

**Comment by KATT** [comment]
> I don't think that should be tRPC's responsibility @skovhus Similar on how you can pass options to `fetch` however you like. Also with this we're going more into `react-query` territory than tRPC's.

There's no limitation AFAIK in the tRPC "link" system (esp in v10) that wouldn't make it possible to make a feature-complete react-query alternative




> Just my two cents... Why don't we just can pass headers to individual endpoint. I think that's the expected location to be and then core can separate those endpoints and leave them out of batching (We should document this behavior tho). So we can just do:
> 
> ```ts
> // By setting custom headers HERE, you're opting out of batching (as stated in the future docs)
> // You can add headers to a batch using a splitLink in config
> const postResult = client.query('posts', null, {
>   context: {
>     headers: {
>        x: 'y',
>     }
>   },
> })
> ```

This is implicit behavior, I don't want that, just because there's a "header" I don't want to automatically map to X or Y, also both links might not be added to the project... or maybe neither might be added if you do only wsLink.


I really don't see a better solution here than to move the stuff to `(ws|http|httpBatch)Link` and deprecate them on the client.

**Comment by cayter** [comment]
I am wondering why can't we separate the single and batch calls?

So this is how `axios` does the concurrent API calls which introduces N round trips:
```ts
await Promise.all([
  axios.post('/users', { ... }, { headers: { ... } }),
  axios.post('/posts', { ... }, { headers: { ... } }),
  axios.post('/comments', { ... }, { headers: { ... } }),
  ...
])
```

Possible for us to do this explicitly? IMHO, letting the users decide when to do batch calls would cover more use cases better.
```ts
await client.batch([
  { type: 'mutation', input: { ... } },
  { type: 'query', input: { ... } },
  ...
], { headers?: { ... } }
```

**Comment by cayter** [comment]
I am wondering why can't we separate the single and batch calls?

So this is how `axios` does the concurrent API calls which introduces N round trips:
```ts
await Promise.all([
  axios.post('/users', { ... }, { headers: { ... } }),
  axios.post('/posts', { ... }, { headers: { ... } }),
  axios.post('/comments', { ... }, { headers: { ... } }),
  ...
])
```

Possible for us to do this explicitly? IMHO, letting the users decide when to do batch calls would cover more use cases better, i.e. less magic = less burden for both maintainers/users.
```ts
await client.batch(
  [
    { type: 'mutation', input: { ... } }, // or batchMutation({ ... })
    { type: 'query', input: { ... } }, // or batchQuery({ ... })
    ...
  ], 
  { 
    headers?: { ... } 
  }
)
```

**Comment by tibotiber** [comment]
Hi, this seems a bit dated, I understand headers are now async and moved to the links, but is getting the `op` as argument something that's possible or being considered?

**Comment by tibotiber** [comment]
More about my use-case:
I have procedures that can be called publicly or authenticated and will be processed slightly differently on the server. I want to set headers on a per operation basis. I am using httpLink, so no batching involved. The auth data (whether to authenticate or not, as well as a potential token) are available in my component (call site) but not via session/cookies/etc., and not at the top of my tree where the httpLink gets configured. So headers being async is great, but I'd love to have the operation's context available there as well. 

Am I missing something mayne?

**Comment by tibotiber** [comment]
Would providing a custom fetcher option on @trpc/react-query be a solution? A bit similar to how graphql-codegen's react-query implementation lets users provide a custom fetcher (https://the-guild.dev/graphql/codegen/plugins/typescript/typescript-react-query#fetcher).

**Comment by tibotiber** [comment]
@KATT isn't `headers(op)` what you had in #2024?

https://github.com/trpc/trpc/pull/2024/files#diff-671e79295e2c31c75769e93c3c10ebaea24b2dc466d3a82d0865548a8a1e318dR10-R16

**Comment by tibotiber** [comment]
Hello, I'm still wondering if there is any chance you may bring back (or be open to helping out on a PR) `headers(op)` on non batch http link?
```
type GetHeadersFn = (opts: {
  op: Operation<unknown>;
}) => HTTPHeaders | Promise<HTTPHeaders>;
```

Let me know if there is a better channel to ask about this.

**Comment by KATT** [comment]
Oh, I have completely missed all your messages, thanks for persisting!.. 

On my phone now, but you should be able to work around this by making a custom link that returns a httpLink with the headers you want. I realise this isn't ideal, but could get it working.

Down to getting more data into the headers callback, please open a separate feat req

**Comment by tibotiber** [comment]
Thanks for reverting 🙏. I've open #4071. I'll try your suggestion in the meantime but i'm not entirely sure how I would set that up as the header values do not exist when i'd create the link.

**Comment by KATT** [comment]
Both `httpLink` and `httpBatchLink` now have callback-fns that return info on the operation so this should be doable.
