### ISSUE TITLE
Refactoring paths

### ISSUE THREAD

**Issue by lkj4** [trpc/trpc#2028]
Not an issue but a discussion: Refactoring endpoint paths is in REST and GraphQL is a pain because paths are just strings and tsserver can't refactor them. With trpc paths are again strings and I was wondering if there's an option to make automatic refactors possible not having to go through all your codebase and hope not to miss replace an old API call.

This is more a language tooling topic but still an important one.

**Comment by dodas** [comment]
This will be fixed in the next major version!
Procedures will be organized using object keys, rather than string "paths".
See [v10 docs (wip)](https://github.com/trpc/trpc/blob/next/.tmp/v10-docs.md)

**Comment by lkj4** [comment]
Cool, I skimmed the spec and I would base my work on V10, when do think we'll it me merges with main?
