### ISSUE TITLE
Enforce properties in procedures

### ISSUE THREAD

**Issue by mariandaniel24** [trpc/trpc#2065]
Hello,

We've recently started to migrate a large project over to tRPC and we have decided on enforcing the `meta` property as a way to define per-procedure access control (roles and misc. settings).
This control is being handled in by a middleware, however, the "issue" is that `meta` is still an optional property and it would be nice if this could be caught at compile time, rather than having the middleware throw an error at runtime.

```ts
interface Meta {
  auth: {
    /* .... */
  };
}
export const appRouter = trpc
  .router<Context, Meta /* 👈 when this is defined, `meta` should be required in procedures   */>()
  // handles error formatting to client
  .formatError(errorHandler)
  // makes sure procedure meta information like
  // procedure authorization guards etc. is correctly parsed
  .middleware(metaMiddleware)
  // all routes
  .merge('auth/', authRouter)
  .merge('invitation/', invitationRouter)
  .merge('equipment/', equipmentRouter);

```

Perhaps it would also be possible to make `input` and `output` properties non-optional, maybe an opt-in flag/generic?
The main reasoning behind this is to provide consistent code and enforce endpoints to be fully written.

**Comment by KATT** [comment]
This is easy to do in v10 by doing a base procedure callback
