### ISSUE TITLE
Input is not the same schema as expected

### ISSUE THREAD

**Issue by arturbunko** [trpc/trpc#2068]
Hello,
I was trying, to migrate my next API to trpc.
I generate trpc cache using createSSGHelpers (because for us need static generation) and in static props request end successfully. But on client I getting the error **TRPCError: No input expected.** I created log in onError in createNextApiHandler, and input is  `{ json: null, meta: { values: [ 'undefined' ] } }  `.

**Comment by jlalmes** [comment]
Please make sure you have added `superjson` to both your FE (`withTRPC.config`) AND your BE (`trpc.router`).

https://trpc.io/docs/data-transformers#using-superjson
