### ISSUE TITLE
Support query or mutation level middleware

### ISSUE THREAD

**Issue by SamSokolin** [trpc/trpc#2081]
Express allows me to define middleware per route:
https://expressjs.com/en/guide/using-middleware.html#middleware.router
while tRPC effectively only allows you to attach middleware to the router.

I'd love to be able to do something like this:
```typescript
export const dogRouter = createRouter()  
  .query("getDog", {
    input: GetDogInput,
    middleware: [GetAuthorizerMiddleware("READ", "Dog")],
    resolve({ input }) {
      return getDog(input.id);
    },
  })
  .query("createDog", {
    input: CreateDogInput,
    middleware: [GetAuthorizerMiddleware("WRITE", "Dog")],
    resolve({ input }) {
      return createDog(input);
    },
  });
```

Currently I'd need to put the middleware evaluation logic in the `resolve` function.

**Comment by sachinraja** [comment]
We will have procedure level middlewares in the upcoming v10!

**Comment by huzaifahj** [comment]
@sachinraja in v10 how do we attach middleware to the whole router? It no longer has the `.middleware()` property.

**Comment by sachinraja** [comment]
See the docs: https://trpc.io/docs/v10/middlewares

**Comment by huzaifahj** [comment]
@sachinraja The docs only show adding middleware to a procedure, not the whole router?

**Comment by KATT** [comment]
We don't have it on the router anymore, instead you can do something like this:

```ts
import { initTRPC } from '@trpc/server';
interface Context {
  user?: {
    id: string;
    isAdmin: boolean;
    // [..]
  };
}
export const t = initTRPC.context<Context>().create();
const isAdmin = t.middleware(async ({ ctx, next }) => {
  if (!ctx.user?.isAdmin) {
    throw new TRPCError({ code: 'UNAUTHORIZED' });
  }
  return next({
    ctx: {
      user: ctx.user,
    }
  });
});
const adminProcedure = t.procedure.use(isAdmin);

const adminRouter = t.router({
  secretPlace: adminProcedure.query(() => 'a key'),
  secretPlace2: adminProcedure.query(() => 'another key'),
});
```

**Comment by huzaifahj** [comment]
Isn't the whole point of middleware that it's router-wide? Although the option to apply specific middleware to a procedure is good, this is very tedious when doing things like authentication and logging

**Comment by KATT** [comment]
Here's an authed procedure that you can reuse anywhere:

```ts
import { TRPCError, initTRPC } from '@trpc/server';
import { Context } from '~/server/context';

export const t = initTRPC.context<Context>().create();

export const isAuthed = t.middleware(async ({ ctx, next }) => {
  const user = ctx.session?.user;

  if (!user) {
    throw new TRPCError({
      code: 'UNAUTHORIZED',
    });
  }

  return next({
    ctx: {
      user,
    },
  });
});

export const authedProcedure = t.procedure.use(isAuthed);

```

Name `authedProcedure` something very short and it's not any more tedious than defining a procedure w/o it :)

**Comment by KATT** [comment]
Previous middleware structure didn't allow for granular middlewares deep in a router, new architecture does.

**Comment by KATT** [comment]
Please raise a discussion in GH discussions or on Discord if you want to continue chatting about this. I'll miss comments on closed issues
