### ISSUE TITLE
Support typed metadata on errors

### ISSUE THREAD

**Issue by SamSokolin** [trpc/trpc#2099]
I have a use case in my app where I return an error on delete because a user needs to delete some related resources first. In that case, I'm returning an error with some data like so:
```typescript
res.status(NOT_ALLOWED_ERROR_CODE).json({ associatedResources });
```

In the tRPC world I can achieve the same thing by setting the cause to `associatedResources` which is of type `string[]`. It would be awesome if tRPC could somehow infer the type of that "error metadata" on client.

**Comment by SamSokolin** [comment]
Also been cutting what feels like a few nit-picky issues lately so just wanted to say that tRPC is awesome!!! Just unloading ideas for the project as I think of them 😄

**Comment by SamSokolin** [comment]
Actually looks like formatting errors only seems to be working for the top level router. If I add a `formatError` clause to one of the inputs to a merged router, it doesn't get picked up.

**Comment by KATT** [comment]
I started adding error inference in the next major but decided to drop it because of complexity, might be picked up in the future. 

The annoying thing with inferring errors is that there'll always be a set of errors that can happen outside of your control - runtime errors in the backend & network errors.

Won't be for a while.

**Comment by SamSokolin** [comment]
@KATT formatError actually seems adequate for my use case! Would it be super complex to extend the existing formatError functionality to account for merged routers? I’d need to look at how merged routers are composed to see for myself

**Comment by KATT** [comment]
You should only have one formatError in the top app router, otherwise tRPC will crash your server and complain that have duplicate formatters

**Comment by PointSingularity** [comment]
@KATT Is there anything planned for having formatErrors per route?
