### ISSUE TITLE
Intellisense not reading correct types

### ISSUE THREAD

**Issue by marwinhormiz** [trpc/trpc#2103]
![f41100c49740b59f3df2234dc02dd01c](https://user-images.githubusercontent.com/56167333/177582889-a5350c13-49ee-4f98-bdbb-08231d67f4b0.png)

Today I created a new folder for my seperate routes for the API called "routes" and updated the import path in the index file where the main appRouter is merging these seperate routes. In my user.ts I have a simple mutation route that takes an input of an object with email, username and password and typescript didn't complain about types before I moved the file into the "routes" folder. But when I made the change and moved the user.ts file into "routes" folder, typescript started to complain on client side where I use the useMutation hook that the "variables" parameter is a void and my arguments being sent to the input is not valid.

When I highlight the red it says: "Argument of type '{ email: string; password: string; username: string; }' is not assignable to parameter of type 'void'. ts(2345)"

![e4588ce260ef710b966213b9ea99648f](https://user-images.githubusercontent.com/56167333/177583837-180d00f4-d569-415d-8ba9-488a4c9dc180.png)

Though the API still works and when I make the mutation it returns the correct variables on success but I don't understand why typescript is complaining about the first argument of the mutation hook being a void and not the type of the object written in the user route file. 

![f5269694d9d9dc1d52824642ebdd9b2a](https://user-images.githubusercontent.com/56167333/177584577-c8f33097-4ce7-411e-bd8a-9670fff20964.png)

**Comment by ixahmedxi** [comment]
have you enabled `"strict": true` in your tsconfig?

**Comment by marwinhormiz** [comment]
I did not have it on strict mode, just enabled it and it works, that's my bad. Thank you for your help!
