### ISSUE TITLE
Proper npm readme of all packages

### ISSUE THREAD

**Issue by KATT** [trpc/trpc#2107]
These all look very boring:

- https://www.npmjs.com/package/@trpc/server
- https://www.npmjs.com/package/@trpc/client
- https://www.npmjs.com/package/@trpc/react
- https://www.npmjs.com/package/@trpc/next

Maybe we can find a way to copy `/README.md` as part of the build process or write short bespoke readmes for each package.

**Comment by ixahmedxi** [comment]
I think having a short README that expresses what each of this package does is better than copying the project readme. I will tackle this now.
