### ISSUE TITLE
Write a migration guide for V10

### ISSUE THREAD

**Issue by KATT** [trpc/trpc#2112]
https://alpha.trpc.io/docs/migrate-from-v9-to-v10

Can be split into different parts

The main chunks of this can be found [here](https://github.com/trpc/trpc/blob/next/.tmp/v10-docs.md#interopability-mode-for-old-routers--migration-path): 

95% use-case:

- [x] Transforming old API for backward-compatabiltiy
- [ ] Add your first router in the new way
- [ ] Briefly explain new Router API
- [ ] Briefly ew client API with proxy
- [ ] [...]

The 5%:

- [ ] New Links
- [ ] New subscriptions with breaking changes
- [ ] [...]

**Comment by minsk-dev** [comment]
I can help with this. I'll start a PR for the "first router" tomorrow
