### ISSUE TITLE
Rewrite current docs to be V10 compliant

### ISSUE THREAD

**Issue by KATT** [trpc/trpc#2115]
In regards to the [`next`-branch](https://github.com/trpc/trpc/tree/next).

### The draft docs for v10:

> Most patterns should be able to be copy/pastad from the below.

https://github.com/trpc/trpc/blob/next/.tmp/v10-docs.md

### How to the website to run locally

```bash
git clone git@github.com:trpc/trpc.git
cd trpc
git checkout next
cd www/
yarn
yarn dev
```

All docs are in https://github.com/trpc/trpc/tree/main/www

### More detailed description

In general, it's about blitzing through this (on `next`): https://github.com/trpc/trpc/tree/next/www/docs

And aligning everything to this doc: https://github.com/trpc/trpc/blob/next/.tmp/v10-docs.md

Example commit: https://github.com/trpc/trpc/commit/02e57d1e5ed68cea52ef4ce5c7ba73e8fecb248b

Not changing any copy, just updating code to comply to v10.

**Comment by sachinraja** [comment]
If anyone wants to help out with this, please join the Discord so we can discuss rewrites/changes first.

**Comment by ajcwebdev** [comment]
Slightly different command sequence I ran to get spun up in case anyone else needs it:

```bash
git clone https://github.com/trpc/trpc.git
cd trpc
git checkout next
cd www/
yarn
yarn dev
```

**Comment by KATT** [comment]
FYI @nexxeln @ajcwebdev - I think @sachinraja & @ixahmedxi are going to blitz through as much as possible of this today :)
