### ISSUE TITLE
Migrate `zart` to v10

### ISSUE THREAD

**Issue by KATT** [trpc/trpc#2118]
It would be nice if we could modernize https://github.com/trpc/zart to v10

- Migrate to V10
- Turborepo?
- Maybe we should use https://github.com/nandorojo/solito?

**Comment by CaptainObi** [comment]
I'm willing to help out here. I've set up things like turborepo, rn, and trpc in the past.

**Comment by CaptainObi** [comment]
Does anyone have any preferences in terms of Turborepo or Solito?

**Comment by juliusmarminge** [comment]
> Does anyone have any preferences in terms of Turborepo or Solito?

🙋Turbo

**Comment by nandorojo** [comment]
The [Solito starter](https://github.com/nandorojo/solito/tree/master/example-monorepos/blank) uses Turborepo too – feel free to reference that!

**Comment by CaptainObi** [comment]
Okay, I think I'll use Solito unless there are any major objections?

**Comment by KATT** [comment]
> Okay, I think I'll use Solito unless there are any major objections?

Sounds good to me, whatever works! I haven't played with it but @nandorojo usually makes cool shit

**Comment by nandorojo** [comment]
if you're adding navigation, then you should add solito. it'll look the same as Next router/link with the same functionality, in addition to working on iOS/Android

**Comment by CaptainObi** [comment]
Anyone got name ideas?

**Comment by KATT** [comment]
> Anyone got name ideas?

zart

**Comment by CaptainObi** [comment]
Should it not be differentiated from the Turbo/Expo version somehow?
