### ISSUE TITLE
`@babel/runtime` dependency in `client`

### ISSUE THREAD

**Issue by colinhacks** [trpc/trpc#212]
Is there a way to get rid of this?

**Comment by KATT** [comment]
it cherry-picks and uses the thing it actually uses.

since we have another lib (react-query) that _also_ requires @babel/runtime it actually shouldn't produce any extra stuff, so it's better than precompiling and "bundling" it since many libs can depend on it but they share the same runtime

**Comment by KATT** [comment]
also your app's tree shaking ensures that only things that is used is included

**Comment by colinhacks** [comment]
Cool cool
