### ISSUE TITLE
Allow onError to swallow mutateAsync errors

### ISSUE THREAD

**Issue by SamSokolin** [trpc/trpc#2126]
When calling mutateAsync, it would be great if we could fully defer error handling to the `onError` function. Effectively do something like this:

```typescript
const { mutateAsync, isLoading } = trpc.useMutation("deleteResource", {
  // Handle error here because the error is automatically typed as a TRPCClientError
  onError: async (error) => {
    if (error.data?.code === "PRECONDITION_FAILED") {
      // If there are associated resources, do not allow deletion.
      setAssociatedResources(error.data.associatedResources ?? []);
      setShowDeleteWarningModal(true);
    } else if (error.data?.code === "UNAUTHORIZED") {
      toast.error("User is unauthorized to perform this action")
    } else {
      toast.error("There was an error deleting the resource. Please try again later.")
    }
  },
});

// Handler for deleting a resource
const onDelete = async () => {
  // Swallow error here because it's already handled within onError above
  await mutateAsync({ resourceId: resource.id }).catch(null);
};
```

The solution above effectively accomplishes my goal but the `catch(null)` feels a little ugly. Fwiw, I'm aware that tRPC is adopting react-query's precedent here. However, given that onError receives a properly typed TRPCClientError `error` argument in the tRPC world, it's decidedly preferable to handle logic there vs. in a traditional try-catch in `onDelete` where you would need to cast the `any` error to a TRPCClientError.

**Comment by SamSokolin** [comment]
Realized I can also do something like this myself by writing a thin `trpc.useMutation` wrapper. Looks like this:

```typescript
type UseMutatationArgs = Parameters<typeof trpc.useMutation>;
type TRPCMutation = ReturnType<typeof trpc.useMutation>;

export function useMutation(pathAndInput: UseMutatationArgs[0], opts: UseMutatationArgs[1]): TRPCMutation {
  const mutation = trpc.useMutation(pathAndInput, opts);
  return {
    ...mutation,
    mutateAsync: async (input) => {
      try {
        return await mutation.mutateAsync(input);
      } catch (error) {
        if (isTRPCClientError(error) && opts?.onError) {
          return;
        }
        throw error;
      }
    },
  };
}
```

**Comment by sachinraja** [comment]
Your wrapper is not typed properly and making it the correct type is difficult and subject to change. I agree it does make sense for us try catch the error automatically if `onError` is provided since all errors are known.

**Comment by sachinraja** [comment]
Your wrapper is not typed properly (needs generics) and making it the correct type is difficult and subject to change. I think you should use `mutate` here?
See https://tkdodo.eu/blog/mastering-mutations-in-react-query

**Comment by SamSokolin** [comment]
Sorry should have included what `trpc` is here:

```
export const trpc = createReactQueryHooks<TrpcAppRouter>();
```

I believe it should be typed correctly because I'm using the type of my app router to construct the wrapper.

**Comment by sachinraja** [comment]
It won't. You need generics

**Comment by sachinraja** [comment]
Closing this because I believe just using `mutate` is what you want.
