### ISSUE TITLE
Client: query building should not add a slash blindly after the URL

### ISSUE THREAD

**Issue by Lilja** [trpc/trpc#2158]
Something I've dealt with with building the aws-lambda handler is that I've added a `<url>:<port>/`. There is a leading slash here, tRPC will just append `/<query|mutation>` to the URL, making it look like `<url>:<port>//<query|mutation>`.

I would think that the query builder should look at the last character of the url-string and not add a slash to it if there already is a leading one.

Today:
`"/"` => `//greet`
`""` => `/greet`

Desired:
`"/"` => `/greet`
`""` => `/greet`

**Comment by sachinraja** [comment]
Why? Seems odd for us to special case this, especially when we don't recommend this naming scheme.

With [the new API](https://alpha.trpc.io/) it'll be especially odd to have a slash in your procedure name.

**Comment by KATT** [comment]
Cleaning up and closing, feel free to re-open or submit a PR if it's still causes you issues
