### ISSUE TITLE
createSSGHelpers function throws error with example from docs

### ISSUE THREAD

**Issue by zanzlender** [trpc/trpc#2160]
I have been following the NextJS example at [tRPC - SSG Helpers](https://trpc.io/docs/ssg-helpers). It says we should be able to use getServerSideProps like so:

```(javascript)
export async function getServerSideProps(
  context: GetServerSidePropsContext<{ id: string }>,
) {
  const ssg = await createSSGHelpers({
    router: appRouter,
    ctx: {},  // <-- this throws an TS error
    transformer: superjson,
  });
  const id = context.params?.id as string;

  // Prefetch `post.byId`
  await ssg.fetchQuery('post.byId', {
    id,
  });

  // Make sure to return { props: { trpcState: ssg.dehydrate() } }
  return {
    props: {
      trpcState: ssg.dehydrate(),
      id,
    },
  };
}
```

Everything works, but leaving the **ctx** object empty throws an error: 
`Type '{}' is missing the following properties from type '{ req: NextApiRequest | undefined; res: NextApiResponse<any> | undefined; session: Session | null | undefined; prisma: PrismaClient<PrismaClientOptions, never, RejectOnNotFound | ... 1 more ... | undefined>; }': req, res, session, prisma`. 

Idk if this is a bug or if it's just my lack of TS skills, but can someone please shed some light on it for me 👍

**Comment by KATT** [comment]
Yeah, that would contradict my recommendations. I wouldn't pass `req`/`res` around in the ctx propagation.

Here's a better context file: https://github.com/trpc/examples-next-prisma-starter/blob/main/src/server/context.ts


Feel free to open an issue on their repo and @ me.
