### ISSUE TITLE
Make `createContext` optional

### ISSUE THREAD

**Issue by colinhacks** [trpc/trpc#218]
Default to `()=>({})`

Simplifies use cases where it isn't required. e.g if the user is passing a token in the input.

**Comment by KATT** [comment]
I don't see many real-world usecases for this, I even use the ctx object for passing Prisma around as its nicer to have it injected than imported. 

That said, I wouldn't object to making it optional if you or someone else want to make a PR, but it might require a bit of typescript trickery.

**Comment by colinhacks** [comment]
It's honestly just about making the sample code simpler in the basic examples

**Comment by KATT** [comment]
I'm fine with this change!

However, I don't really think it's a threat to adoption; Apollo Client & GraphQL has always been super convoluted to setup but it have gotten great adoption - we all realise its just something we need to copy/paste and rarely touch.
