### ISSUE TITLE
How about Flutter support?

### ISSUE THREAD

**Issue by cayter** [trpc/trpc#2211]
Is it possible to generate the client code for Flutter dart? Or is there a way for us to emit the API JSON schema so that the community can work on various clients other than just Typescript to call tRPC APIs? Yes, I'm aware of the drawback of no more Typescript's automatic type inferring.

**Comment by FerasAloudah** [comment]
You can use https://github.com/jlalmes/trpc-openapi to generate an OpenAPI document to make it easy for different clients to work with tRPC.

**Comment by cayter** [comment]
> You can use https://github.com/jlalmes/trpc-openapi to generate an OpenAPI document to make it easy for different clients to work with tRPC.

Ahhh okay, thanks!
