### ISSUE TITLE
Type safety is not active on client side

### ISSUE THREAD

**Issue by thisduck** [trpc/trpc#2218]
I've created a repo where the backend and frontend are two different npm projects with their own package.json files. This is an express backend and a vue frontend (though I think this should not be relevant).

https://github.com/thisduck/trpc-example

On the `main` branch, the type checking on the client side doesn't work. Both calls to the query and mutation are passed the wrong params and no typescript errors are showing. The response is not typed either.
https://github.com/thisduck/trpc-example/blob/main/frontend/src/main.ts#L14-L21

However, once I add the `@trpc/server` package to the *client* project, type checking works. (On the `working` branch: https://github.com/thisduck/trpc-example/commit/0c1c591898ca3b179695437a078b36b9b51a3279)

This is not what I expected given the docs. The Quickstart page indicates that we need to add `@trpc/server` to the server codebase and `@trpc/client` to the client codebase.

All examples in the trpc repo have the client and server share a package.json project. So the server and client package in the same project is implicit in all the examples.

I'm not sure if this is expected behaviour.

**Comment by sachinraja** [comment]
`@trpc/server` is a peerDependency of `@trpc/client`. Feel free to send a PR to update the docs. ALso if you have a monorepo you should use ["workspaces"](https://docs.npmjs.com/cli/v8/using-npm/workspaces).

**Comment by thisduck** [comment]
Thanks @sachinraja, I added PR #2219.

I will be using workspaces eventually, just wanted to follow the docs to get a quick working example first. And ended up running into this.
