### ISSUE TITLE
QOL Improvement - Include tRPC Error schema in package?

### ISSUE THREAD

**Issue by iway1** [trpc/trpc#2220]
I need to do some global error handling to log a user out in the front end of my React Native app. I just want to check for an unauthorized response and log users out. In my endless pursuit of DRY code, I've decided to do this in the default options of the query client (which is only possible because you all made the awesome decision to build this library on top of `react-query`). To check whether or not some error is a tRPC authorization error, I opt for a zod schema to get that sweet, sweet zero-cost type safety runtime type safety:

```js
const TRPCErrorSchema = z.object({
  data: z.object({
    httpStatus: z.number(),
    stack: z.string(),
    path: z.string(),
    code: z.enum([
      'BAD_REQUEST',
      'UNAUTHORIZED',
      'FORBIDDEN',
      'NOT_FOUND',
      'TIMEOUT',
      'CONFLICT',
      'PRECONDITION_FAILED',
      'PAYLOAD_TOO_LARGE',
      'METHOD_NOT_SUPPORTED',
      'CLIENT_CLOSED_REQUEST',
      'INTERNAL_SERVER_ERROR',
    ])
  })
})

const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      onError: (error: unknown)=>{
        const trpcErrorParse = TRPCErrorSchema.safeParse(error);
        if(trpcErrorParse.success) {
          if(trpcErrorParse.data.error.data.code == 'UNAUTHORIZED') {
            authStore.getState().logout();
          }
        }
      }
    }
  }
});
```

I have no problem with this code at all, it works quite easily and provides me with a fire-and-forget type solution for handling auth with tRPC, and I have achieved maximum DRY-ness within my project as far as authentication is concerned. However, I would like to also achieve dryness across my projects.

With this solution I'm going to have to copy and paste that zod schema to every project in which I use tRPC (which is hopefully every project in the foreseeable future). That schema isn't something I can really put into my own package in any logical sort of manner, because it has a really niche use case, it's a utility for use with tRPC only.

SO, what do we think about some sort of utility function that gets exported from tRPC for simply type checking an error? Something like:

```js
function isTrpcError(error: unknown): error is TRPCError {
  
}
```

Of course probably wouldn't want to use Zod here since tRPC is a package and all, but a utility like this could keep me and future devs from having to typecheck trpc errors manually which just be pretty darn cool IMO.

It wouldn't really matter as much in situations where we were guaranteed to only be using the query client indirectly through trpc, but it doesn't seem like too common a use case to use the query client for other stuff.

**Comment by KATT** [comment]
I like this idea a helper, but we won't ship something that is tied to a specific validator in the project.

It'd like have to be something like `isTRPCError<AppRouter>(x)`

**Comment by KATT** [comment]
Feel free to reopen if you wanna work on it
