### ISSUE TITLE
clarifying trpc comparisons and what it does

### ISSUE THREAD

**Issue by AndrewCathcart** [trpc/trpc#2223]
Shall we spruce up the docs both here & on the official docs site? 

There was a lovely dumpster fire of a thread over on /r/programming where people just did not understand what this was for.

I won't link the thread directly here unless prompted (not sure of the rules etc) but here's a few areas of confusion / places people had questions about;
- Did not know it was for fullstack TS. 
- Did not know if it was just for REST API's
- Why this over GraphQL / using something like protobuf
- Confusion over the name

**Comment by KATT** [comment]
This would be good indeed :)

@sachinraja has made a really good starting point of new docs structure & @jlalmes + @ixahmedxi have started on designs for the new landing page :)

**Comment by sachinraja** [comment]
I would take anything on Reddit with a grain of salt. People there generally don't like reading anything at all. I do agree we can improve the docs to be more accessible to more people though.
