### ISSUE TITLE
How do you perform client request cancelation in v10?

### ISSUE THREAD

**Issue by KATT** [trpc/trpc#2283]
### Discussed in https://github.com/trpc/trpc/discussions/2282

<div type='discussions-op-text'>

<sup>Originally posted by **IgnusG** July 21, 2022</sup>
I noticed that v10 abandoned the cancelable promise design returning instead a plain promise. How can you cancel a request that is already in progress?</div>

We should do something with an `AbortController` signal in the extra parameters we can send. We can look at react-query for inspiration

**Comment by IgnusG** [comment]
An `AbortController` signal would definitely be the best way to streamline adoption. 

I actually had a wrapper in v9 that accepted an AbortController signal and called the `cancel` method on the cancelable promise to bring trpc v9 inline with other fetch/query libraries.

**Comment by gabriel-frattini** [comment]
@IgnusG @KATT would you give an example of how the `abortController` would be used as a paramter inside a request?

**Comment by KATT** [comment]
Just as a note here, this probably should be a breaking change where we get rid of `.cancel()` and our own odd cancellable promise abstractions. 

> @IgnusG @KATT would you give an example of how the `abortController` would be used as a paramter inside a request?


Can't as I'm on my phone, but one would pass in an abort controller signal as a param.

**Comment by juliusmarminge** [comment]
> Just as a note here, this probably should be a breaking change where we get rid of `.cancel()` and our own odd cancellable promise abstractions. 
> 
> 
> 
> > @IgnusG @KATT would you give an example of how the `abortController` would be used as a paramter inside a request?
> 
> 
> 
> 
> 
> Can't as I'm on my phone, but one would pass in an abort controller signal as a param. 

Interesting... so you want the user to pass in the signal themselves?

```ts
const ac = new AbortController();
const testQuery = trpc.test.query({ signal: ac.signal });

// cancel
ac.abort();
```

For react, similar to how `@tanstack/react-query` does it:

```ts
const testQuery = trpc.test.useQuery();
const utils = trpc.useContext();

// cancel
utils.test.cancelQuery();
```

**Comment by IgnusG** [comment]
> > Just as a note here, this probably should be a breaking change where we get rid of `.cancel()` and our own odd cancellable promise abstractions. 
> > 
> > 
> > 
> > > @IgnusG @KATT would you give an example of how the `abortController` would be used as a paramter inside a request?
> > 
> > 
> > 
> > 
> > 
> > Can't as I'm on my phone, but one would pass in an abort controller signal as a param. 
> 
> Interesting... so you want the user to pass in the signal themselves?
> 
> ```ts
> const ac = new AbortController();
> const client = createTRPCProxyClient()
> const testQuery = client.test.query(..., { signal: ac.signal });
> 
> // cancel
> ac.abort();
> ```
> 
> For react, similar to how `@tanstack/react-query` does it:
> 
> ```ts
> const testQuery = trpc.proxy.test.useQuery(...);
> const utils = trpc.proxy.useContext();
> 
> // cancel
> utils.test.cancelQuery();
> ```
> 

Passing the abort controller directly to the query is how native fetch does it too. Think it's better to follow that pattern over react query. 

You could also always wrap it in something custom to avoid this if you prefer that pattern.
