### ISSUE TITLE
useQuery without first parameter - different ReactQuery Keys in v10

### ISSUE THREAD

**Issue by SebastianSiedler** [trpc/trpc#2290]
When using `useQuery` via the new proxy api without a first parameter, but ReactQuery options as a second parameter, the ReactQuery Key is different compared to the "old" api.

```ts
// v10 Syntax 
// ReactQuery Key -> ["spiel.list", null]
trpc.proxy.spiel.list.useQuery(undefined, {...});

// v9 Syntax
// ReactQuery Key -> ["spiel.list"]
trpc.useQuery(['spiel.list'], {...});
```

**Comment by KATT** [comment]
I think we should treat `undefined` and missing the same way. That's the approach I'll take.
