### ISSUE TITLE
Potential for future type error in TRPCError & TRPCClientError

### ISSUE THREAD

**Issue by henrikvtcodes** [trpc/trpc#2292]
While working on a project with tRPC (based on the `fastify-server` example), I came across a type error while attempting to build the project.
```
node_modules/@trpc/client/dist/declarations/src/TRPCClientError.d.ts:13:14 - error TS2416: Property 'cause' in type 'TRPCClientError<TRouter>' is not assignable to the same property in base type 'Error'.
  Type 'Maybe<Error>' is not assignable to type 'Error | undefined'.
    Type 'null' is not assignable to type 'Error | undefined'.

13     readonly cause: Maybe<Error>;
                ~~~~~

node_modules/@trpc/server/dist/declarations/src/TRPCError.d.ts:7:14 - error TS2416: Property 'cause' in type 'TRPCError' is not assignable to the same property in base type 'Error'.
  Type 'unknown' is not assignable to type 'Error | undefined'.

7     readonly cause?: unknown;
               ~~~~~
```  
  
I managed to figure out what causes the bug: There is a breaking change in `typescript@4.6.2`, [this one](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-6.html#object-rests-drop-unspreadable-members-from-generic-objects) I believe  
Through more testing, I also figured out a few workarounds:  
- Use `typescript@4.5.5`
- Set the `target` in `tsconfig.json` to `ES2021`
- Set the `target` in `tsconfig.json` to `ES6`  
  
I was going to file a PR, but then I wasn't sure exactly what needs to be fixed(?). Is this a bug that needs fixing within tRPC itself? Should there be a warning in the docs? Should the examples use the aforementioned `tsconfig` workaround? Should the entire repo use the `tsconfig` workaround?  
  
I am very willing to help with a fix but I need some insight.

**Comment by sachinraja** [comment]
Sorry for the very late response, but this should have been fixed. I'll close this now, but if you're still seeing it, please re-open.

**Comment by moltar** [comment]
We are still seeing this issue:

```
node_modules/@trpc/client/src/TRPCClientError.ts:18:19 - error TS2416: Property 'cause' in type 'TRPCClientError<TRouter>' is not assignable to the same property in base type 'Error'.
  Type 'Maybe<Error>' is not assignable to type 'Error | undefined'.
    Type 'null' is not assignable to type 'Error | undefined'.

18   public readonly cause;
```

With the following deps:

```
    "typescript": "4.8.4",
    "@trpc/client": "9.27.2",
    "@trpc/react": "9.27.2",
    "@trpc/server": "9.27.2",
```

**Comment by henrikvtcodes** [comment]
What does your tsconfig look like?
