### ISSUE TITLE
[v10] Make interop non-proxy string literals & and new proxy calls mutually exclusive

### ISSUE THREAD

**Issue by KATT** [trpc/trpc#2311]
## Problem

Currently, it's possible to use the old client APIs to call the new ways of defining routers and procedures and the other way around. This creates quite a heavy load on TypeScript performance as we flatten all procedures on the router, whether it's used or not.

Seeing that we are stepping away from string literals, this is an undesirable bottleneck & makes tRPC slower.

## Proposed solution

- Procedures defined with old way (i.e. `trpc.router().query('oldProc', { resolve: () => '..' )`) should **not** be callable through a proxy, and **only** with the legacy string literals
- Procedures defined with new way, (i.e. `t.router({ newProc: t.query(() => '..') })`), should not be callable **except through a proxy**

## Implications

- Proxy will be the only way to call things in the default tRPC clients
- People who want to support environments [which can't support `Proxy`](https://caniuse.com/#search=Proxy) will need another tRPC client *(TBD if we make one of those ourselves)*
- We need to change the way we define interop mode on the client
- We will deprecate `createTRPCClient` & `createReactQueryHooks` in favor of proxy-based APIs
- We will need to define interop clients or make the current clients automatically expose a `.proxy` object
- This **should not** make incremental migration from v9->v10 harder

## Proposed APIs

Given the following backend:

```ts
const t = initTRPC()();
const legacyRouter = trpc
  .router()
  .query('legacyProc', {
    input: z.string().optional(),
    resolve({ input }) {
      return `hello ${input ?? 'world'}`;
    },
  })
const newAppRouter = t.router({
  newProc: t.procedure.query(() => "I am just a test, I don't know! "),
});
const appRouter = t.mergeRouters(legacyRouter.interop(), newAppRouter);
```

### `@trpc/client`

**New way of creating a client:**
```ts
// Create new client
const client = createTRPCProxyClient<AppRouter>({ 
  url: 'http://localhost:3001',
})

// Usage:
client.newProc.query();
```

**Interop:**

```ts
// Will show deprecation error
const client = createTRPCClient<AppRouter>({
  url: 'http://localhost:3001',
})

// Expose a proxy prop automatically:
const proxy = client.proxy;

// ✅ These calls will work
proxy.newProc.query();
client.query('legacyProc');

// ❌ These will now show TypeScript error
proxy.legacyProc.query();
client.query('newProc');
```

### `@trpc/react`

**New default way of creating a client:**

```tsx
const trpc = createTRPCReact<AppRouter>();

// Calls:
trpc.newProc.useQuery();
```

**Interop:**

```tsx
const trpc = createReactQueryHooks<AppRouter>();

const proxy = trpc.proxy;

// ✅ These calls will work
proxy.newProc.useQuery();
trpc.useQuery(['legacyProc']);

// ❌ These will now show TypeScript error
proxy.legacyProc.useQuery();
trpc.useQuery(['newProc']);
```

**Comment by romanzy-1612** [comment]
> Procedures defined with old way should not be callable through a proxy, and only with the legacy string literals

I think this is a good change, migration workflow will be nice.
Initial setup is simple: slap `interop` on legacy router and merge with empty modern router. Check that everything works.

And then its rinse and repeat:
- on server upgrade a route to v10.
- follow squiggles to change client where needed.

The good is that client side migration follows server side, one step at a time.
When migration is done, removing interop should not cause a backlog of issues.

But will with work with nested routers? Can I go outside in (from leafs to root rooter) while making changes?

**Comment by KATT** [comment]
You gotta do it 1 full router at a time unfortunately.

**Comment by sachinraja** [comment]
done in #2408
