### ISSUE TITLE
Cannot set `Set-Cookie` response header

### ISSUE THREAD

**Issue by emme1444** [trpc/trpc#2312]
I'm working with implementing authentication using `trpc`. I use the `fetch` adapter. I need to set the `Set-Cookie` response header. However in trying so I discovered that `fetch`'s `Response` objects do not allow setting this header, as per the spec [here](https://fetch.spec.whatwg.org/#forbidden-response-header-name).

> A forbidden response-header name is a [header name](https://fetch.spec.whatwg.org/#header-name) that is a [byte-case-insensitive](https://infra.spec.whatwg.org/#byte-case-insensitive) match for one of:
>
> - `Set-Cookie`
> - `Set-Cookie2`

After some debugging, I was able to come to the conclusion that the problem lies with the `res.headers.set(...)` call on line `52`. The `Headers` object's implementation silently ignores calls to this (and `.append` I think) with the `key` set to one of the above alternative from the spec.

https://github.com/trpc/trpc/blob/2af7a0070f3bc01b81fe6f14f591e77c549520a7/packages/server/src/adapters/fetch/fetchRequestHandler.ts#L42-L59

Fortunately there is a potential solution in my eyes. This would be to extract the header keys and values from `result.headers` before constructing the `Response` object. Passing the new `headers` record into the `headers` option.

```ts
const headers = {};

// collect headers...

const res= new Response(result.body, {
  status: result.status,
  headers,
});
```

I am a little worried this solution might cause problems considering I don't know if this approach would bypass all of `Headers` addition checks. Maybe if this is the case, only extract and inject the "forbidden response-header names" before constructing the `Response` object and continue using the current approach for all rest.

If this behaviour is intentional, or if you require more information please let me know.

Thanks.

### Info

- `trpc`: `10.0.0-alpha.40`

**Comment by KATT** [comment]
Thanks for the write-up! 

Without digging too much to give definite agreement here, I think it definitely should be possible to `set-cookie` just as well as any other header.

If you want, feel try to hack around with a PR to address this, [I've added you as a contributor](https://github.com/trpc/trpc/invitations) to the project :)

**Comment by emme1444** [comment]
Hi @KATT 

I could not have hoped for a better reply!

I will make a pr as soon as I get the chance.

**Comment by emme1444** [comment]
I'm in the process of hacking a fix together for this.

The only problem I can see with this is the fact that we will not be able to send multiple `Set-Cookie` headers, which means only one cookie. You see `Set-Cookie` is a special header which, in the response headers, can appear multiple times. If the value was an array, calling `.append` only concats the values with a `, `. Which is not enough for the browser to understand the there are multiple cookies. The rest will be interpreted as a value. A semicolon instead causes the browser to ignore the rest.

The `headers` init option does not accept an array of values for one header name. It's type is `string[][] | Record<string, string> | Headers`. And passing in an array with multiple instances of the same header name will cause the `Headers` object to concat like with the `.append` call above.

Currently I'm only handling the `Set-Cookie` (and `Set-Cookie2` cause why not) header before creating the `Response` object. Should I just ignore if the value for the `Set-Cookie` header is an array or should this be warned or something?

**Comment by KATT** [comment]
Let's change the record to support array values to make sure this is supported? I think I just decided to have it being a string for simplicity; sort of _"we'll fix it when we need to"_ and now it seems like we need to :)

**Comment by KATT** [comment]
If you setup github sponsors I'll also send you some $ when you're done :)

**Comment by emme1444** [comment]
I can't tell if we're on the same page, but I'll make a pr so you can take a look.

**Comment by KATT** [comment]
Feel free to reopen if you wanna work on this. Not sure what the issue is and I'm doing some cleanup of stale issues.
