### ISSUE TITLE
Delete babel runtime helpers in `@trpc/client`?

### ISSUE THREAD

**Issue by KATT** [trpc/trpc#2314]
Creating an issue for this just so we can track it on the roadmap. 

### Discussed in https://github.com/trpc/trpc/discussions/2232

<div type='discussions-op-text'>

<sup>Originally posted by **KATT** July 17, 2022</sup>
> Previously brought up by @mmkal

We could potentially remove babel runtime helpers in `@trpc/client`. The reason they are there is to add a transformation for `async`/`await` and other modern JS features.

However, it adds some unnecessary build times and complexity, maybe we can just get rid of it?

Is there even simple ways of people of transpiling the client themselves according to their browser requirements?</div>

**Comment by juliusmarminge** [comment]
Done in #2385 via #2422.
