### ISSUE TITLE
Not showing error when object value length isn't correct

### ISSUE THREAD

**Issue by MrAmericanMike** [trpc/trpc#2328]
Given the created route

```js
.mutation("takeObject", {
		input: z.object({ name: z.string().min(5) }),
		async resolve(req) {
			return {
				data: req.input
			};
		}
	})
```

If I call it from the client side with

```js
CLIENT.mutation("takeObject");
```

I do correctly get an error saying that it expects 2 to 3 arguments, but got only 1. So I add a 2nd argument which as suggested it's looking for an object containing a name string.

So I go ahead and do:

```js
CLIENT.mutation("takeObject", {name: "LALA"});
```

Everything perfect, even if I change name to something like "text" I get an error letting me know that:

```
Argument of type '{ text: string; }' is not assignable to parameter of type '{ name: string; }'.
```

However... Shouldn't I get also an error on "LALA" complaining that it doesn't meet the minimum length requirement of 5?

Which is the error that will trigger on that call.

**Comment by KATT** [comment]
If zod would support that, we could piggyback on that in tRPC, but currently that type information doesn't exist as far as I know.
