### ISSUE TITLE
`trpc.useQuery()` is not linted by `eslint-plugin-react-hooks`

### ISSUE THREAD

**Issue by itsMapleLeaf** [trpc/trpc#2330]
See the playground here: https://codesandbox.io/s/eslint-react-hooks-does-not-lint-on-lowercase-named-namespaces-ojbcw8?file=/src/App.js

The linter rule only recognizes un-namespaced hooks, like `useQuery()`, or if the namespace is capitalized, like `Trpc.useQuery()`

I don't think this requires a change in API, but it might be worth changing the convention in the docs with this in mind.

**Comment by iway1** [comment]
I just do this:
```
const {useQuery, useMutation} = trpc;
```

Then use those in components directly. It's just more dev friendly IMO to import useQuery or useMutation instead of doing `trpc.useQuery`

**Comment by KATT** [comment]
Interesting, I didn't know this! Do you know which lint rule it is? I'd like to open an issue

**Comment by itsMapleLeaf** [comment]
> Interesting, I didn't know this! Do you know which lint rule it is? I'd like to open an issue

The lint rule is `react-hooks/rules-of-hooks`, and it lives on the react repo https://github.com/facebook/react/tree/main/packages/eslint-plugin-react-hooks

**Comment by KATT** [comment]
Blocked: https://github.com/facebook/react/issues/25065

**Comment by TkDodo** [comment]
This seems pretty important for v10. Anything we can do to speed-up things on react's side?

**Comment by KATT** [comment]
> This seems pretty important for v10. Anything we can do to speed-up things on react's side?

If you have any strings to pull in the React team, pull 'em. ☺
