### ISSUE TITLE
Improve docs section for "Inferring Types"

### ISSUE THREAD

**Issue by BigDog1400** [trpc/trpc#2342]
Currently in the docs section for [Inferring Types](https://trpc.io/docs/infer-types), there is not code snippet for getting the proper types in the options object for mutations. I think it will be helpful to add because there may be a lot of people who wants to create a custom hook wrapping their mutations and want to add proper types for options parameter.

Here is a code snippet from a custom hook that i created with a mutation:

```ts
import { InferTRPCMutationOptions, trpc } from "@/lib/trpc";

interface UseAddProductParams {
  options?: InferTRPCMutationOptions<"product.add">;
}

function useAddProduct({ options }: UseAddProductParams) {
  const productMutation = trpc.useMutation(["product.add"], options);

  return productMutation;
}
export { useAddProduct };
```

This is what InferTRPCMutationOptions looks like:

```ts
type TError = TRPCClientErrorLike<AppRouter>;

export type InferTRPCMutationOptions<
  TRouteKey extends keyof AppRouter["_def"]["mutations"]
> = UseTRPCMutationOptions<
  inferMutationInput<TRouteKey>,
  TError,
  inferMutationOutput<TRouteKey>,
  unknown
>;
```

inferMutationInput and inferMutationOutput are exactly the same as the docs suggest

**Comment by sachinraja** [comment]
It'd be difficult for us to add inference helpers for *everything* in our docs, so I'm unsure if we should add this. We could add a basic example of how to build an inference helper and pass generics to external types.
