### ISSUE TITLE
Next.js HOC overwrites custom App.getInitialProps

### ISSUE THREAD

**Issue by system32uwu** [trpc/trpc#2348]
**Describe the bug**
Passing whatever props to _app's MyApp through getInitialProps gets deleted

**To Reproduce**

1: create t3-app: `pnpm dlx create-t3-app@latest`
2: Create a custom getInitialProps function for MyApp (_app.tsx), toggle the commented out exports to see the difference (HOC deletes the variables passed, while without it they get passed fine):

```tsx
import * as M from '@mantine/core'
import { getCookie, setCookie } from 'cookies-next'
import { SessionProvider } from 'next-auth/react'
import App, {
  AppContext,
  AppInitialProps,
  AppProps
} from 'next/app'
import Head from 'next/head'
import { useState } from 'react'

type AppOwnProps = { colorScheme: M.ColorScheme; test: string }

export function MyApp({
  Component,
  pageProps,
  colorScheme,
  test
}: AppProps & AppOwnProps) {
  console.log(colorScheme, test)

  const [_colorScheme, setColorScheme] =
    useState<M.ColorScheme>(colorScheme)

  const toggleColorScheme = (value?: M.ColorScheme) => {
    const nextColorScheme =
      value || (_colorScheme === 'dark' ? 'light' : 'dark')
    setColorScheme(nextColorScheme)
    // when color scheme is updated save it to cookie
    setCookie('mantine-color-scheme', nextColorScheme, {
      maxAge: 60 * 60 * 24 * 30
    })
  }

  return (
    <>
      <Head>
        <title>App</title>
        <meta
          name="viewport"
          content="minimum-scale=1, initial-scale=1, width=device-width"
        />
      </Head>
      <SessionProvider session={pageProps.session}>
        <M.ColorSchemeProvider
          colorScheme={_colorScheme}
          toggleColorScheme={toggleColorScheme}
        >
          <M.MantineProvider
            withGlobalStyles
            withNormalizeCSS
          >
            <Component {...pageProps} />
          </M.MantineProvider>
        </M.ColorSchemeProvider>
      </SessionProvider>
    </>
  )
}

MyApp.getInitialProps = async (
  context: AppContext
): Promise<AppOwnProps & AppInitialProps> => {
  const ctx = await App.getInitialProps(context)
  return {
    ...ctx,
    test: 'test',
    colorScheme:
      (getCookie(
        'mantine-color-scheme',
        context.ctx
      ) as M.ColorScheme) || 'light'
  }
}

const getBaseUrl = () => {
  if (typeof window !== 'undefined') {
    return ''
  }
  if (process.env.VERCEL_URL)
    return `https://${process.env.VERCEL_URL}` // SSR should use vercel url

  return `http://localhost:${process.env.PORT ?? 3000}` // dev SSR should use localhost
}

// export default withTRPC<AppRouter>({
//   config({ ctx }) {
//     /**
//      * If you want to use SSR, you need to use the server's full URL
//      * @link https://trpc.io/docs/ssr
//      */
//     const url = `${getBaseUrl()}/api/trpc`

//     return {
//       url,
//       transformer: superjson
//       /**
//        * @link https://react-query.tanstack.com/reference/QueryClient
//        */
//       // queryClientConfig: { defaultOptions: { queries: { staleTime: 60 } } },
//     }
//   },
//   /**
//    * @link https://trpc.io/docs/ssr
//    */
//   ssr: false
// })(MyApp)

// export default MyApp

```

**Expected behavior**

MyApp should receive the variables `colorScheme` and `test`

**Screenshots**

---

As a workaround I just patched the package and changed [this](https://github.com/trpc/trpc/blob/main/packages/next/src/withTRPC.tsx#L146) to this:
```tsx
const originalPageProps = isApp
            ? { ...originalProps.pageProps, ...originalProps } ??
              {}
            : originalProps
```
Which doesn't really make sense to me as later you're returning the object including both props, it should be passing them correctly as is from my understanding.

**Comment by erikbg7** [comment]
Not sure it is related, but 2 considerations:

1. NextJS recommends `getStaticProps` and `getServerSideProps` over `getInitialProps` [[1]](https://nextjs.org/docs/api-reference/data-fetching/get-initial-props)
2. `getStaticProps` cannot be used in `_app`, `_document` and `_error` files [[2]](https://nextjs.org/docs/basic-features/data-fetching/get-static-props#where-can-i-use-getstaticprops)

In any case, I see you have SSR set to `false` in the HoC, so maybe you could try setting it to `true`.

Let us know if it works!

**Comment by erikbg7** [comment]
I can confirm that attaching `getinitialProps` to `MyApp` does not pass the props. 

However, the following code seems to be working fine: 

``` tsx
import Head from 'next/head';
import { withTRPC } from '@trpc/next';

const MyApp = ({ Component, pageProps, title }: any) => {
  return (
    <>
      <Head>
        <title>{title}</title>
      </Head>
      <Component {...pageProps} title={title} />
    </>
  );
};

const WrappedApp = withTRPC({
  config: () => ({ url: '/api/trpc' }),
  ssr: true,
})(MyApp);

WrappedApp.getInitialProps = (ctx: any) => {
  return { title: 'title' };
};

export default WrappedApp;

```

The only difference is that we attach the initial props to the wrapper.

The result is the title correctly passed and used as props:

![image](https://user-images.githubusercontent.com/37018474/183121282-d51c544f-9cca-41c6-b676-7f2c47182811.png)

**Comment by KATT** [comment]
This is not a bug.

- See here: https://next-prisma-starter-cg9fz4lds-trpc.vercel.app/
- See working code code in #2382



I think you're both missing to pass stuff within a prop called `pageProps: {}`


![Screenshot 2022-08-05 at 19 33 08](https://user-images.githubusercontent.com/459267/183130565-da60080c-e781-4a90-9f09-41c621c6b8a4.png)

**Comment by system32uwu** [comment]
Thank you both for taking a look at it, I ended up submitting my work with the patch I made to the next adapter and it's working fine, will take what was discussed here as a reference for future projects with TRPC. Have a nice weekend

**Comment by mcmillion** [comment]
I've noticed that using `App.getInitialProps` removes the `trpcState` key from `pageProps`. Is that okay or does this cause problems?
