### ISSUE TITLE
~React~ TanStack Query 4 support

### ISSUE THREAD

**Issue by KATT** [trpc/trpc#2352]

**Comment by gynekolog** [comment]
There is already issue https://github.com/trpc/trpc/issues/2243

**Comment by dyaa** [comment]
It seems like we'll need to make a breaking naming change to the `OperationContext` property name from `context` to something else _ex. `requestContext`_ to avoid naming colliding with `@tanstack/react-query`.

More context can be found here https://github.com/trpc/trpc/pull/2240#discussion_r940177822

**Comment by KATT** [comment]
See further discussion on #2395
