### ISSUE TITLE
createCaller docs

### ISSUE THREAD

**Issue by sachinraja** [trpc/trpc#2362]
See v10 API in #2233

`createCaller` should be documented. We should also explain when to use it (testing).

**Comment by gioboa** [comment]
I can work on this

**Comment by gioboa** [comment]
I'm investigating the functionalities of `createCaller`, where should I insert the explanation? do I create another section inside https://github.com/trpc/trpc/tree/main/www/docs/server ?

**Comment by sachinraja** [comment]
Yes, that would be great

**Comment by gioboa** [comment]
Which is the right branch to study and prepare the explanation?

**Comment by sachinraja** [comment]
You can check out the tests here: https://github.com/trpc/trpc/blob/next/packages/server/test/caller.test.ts
