### ISSUE TITLE
RFC: Content Types

### ISSUE THREAD

**Issue by sachinraja** [trpc/trpc#2387]
This is a proposal for a new content type API that will augment or replace the current [`transformer` API](https://trpc.io/docs/data-transformers).

Draft implementation in #2351
discussion in #1937
### Why? Is it necessary to support more than just JSON?
I'll argue in favor of this. Supporting more content types allows us to shrink the size of the query URLs with smaller inputs and the size of the responses from the API. Most users also use [Superjson](https://github.com/blitz-js/superjson) to support a wider range of data types. However, Superjson is very inefficient at this (see https://github.com/blitz-js/superjson/issues/38) and JSON may not be the best format. Other formats like https://github.com/pieroxy/lz-string compress data to be much smaller.

Another important goal of this API is to enable streaming files from the client. We only support JSON currently so the current solution is for the client to request a pre-signed storage URL (for something like S3) and stream the file to that URL or encode the file to base64 and send that string in the JSON body, which is slow and inefficient. Having the ability to define a procedure that accepts a file stream has the potential to greatly simplify this flow.

> Why use tRPC vs. a normal API route then?

If you define it within the tRPC router, you can keep the same context and middleware flow instead of having to redefine that as an API route. You can also, of course, upload files to your API route in a typesafe manner.

### Server
The goals of content types on the server are enabling streaming requests and responses, supporting additional JS data types, and faster serialization. 
The entry point for most users can look something like this, similar to how you would define a transformer:
```ts
const t = initTRPC()({
  contentTypes: [superjsonContentType]
})

// per procedure?
t.procedure.contentTypes([superjsonContentType]).query(() => {
  return {
    createdAt: new Date()
  }
})
```
We also must provide some way of specifying content types per procedure. For example, you might want one specific procedure to only accept the multipart data content type. This makes batching requests very difficult. One way it could work is the content types would indicate if they support batching. Then on the client, requests in a batch would be grouped based on their content types and individual requests would be fired for each content type group. This is a very complex solution and I'm not sure we want to go down that route, but I also can't think of an alternative.

Here, `superjsonContentType` will be an object with methods for deserializing and serializing in different situations. The same object will be passed to `initTRPC` on the server and also imported on the client. For the server's needs, the content type should have methods to do the following:
- for queries, accept input via a URL parameter and be able to deserialize it 
- for mutations, accept a stream or string from the client and be able to deserialize it
  - passing a stream to the content type is considerably difficult because we're agnostic to the server framework. Ideally, we'd coerce everything to the Fetch API (related: #1853)
- for responses, they should be streamable or just strings

> **Note**
> I am purposefully not outlining what an API for defining content types could look like. Instead, I am only going to define our goals/requirements for them.

### Client
On the client side, content types will unlock the usage of all contents with tRPC, not just JSON-based ones. The API could look like the following:
```ts
const client = createTRPCClient({
  // this would be used for all requests if there isn't an override specified
  defaultContentType: superjsonContentType
})

const proxy = createTRPCClientProxy(client)

// specify/override per query
const user = proxy.uploadFile(/* multipart data stream */, {
  contentType: multipartContentType
})
```

As I said above, we must consider the batching implications. Different content types must be different requests, but batching is still essential for us to support.

For the client, the content type should be able to do the following:
- for mutations, be able to stream input
- for receiving streamed responses, be able to deserialize output as it's being read from the stream

### JSON Interfaces
I \*really do not\* want a `transformer` and content type API. tRPC's config is already complex as is. If anything at this point, we should be seeking to simplify it.

However, there are special considerations for things that will serialize to JSON anyway. An example is the SSR/[SSG flow with Next.js](https://alpha.trpc.io/docs/ssg-helpers#nextjs-example). We send a prop to the page from the server called `trpcState` which is serialized to JSON by Next.js. In this case, we will incur the cost of serialization twice, once when serializing the data with the content type and again when Next.js serializes the serialized data to JSON. I'm not sure what solutions we can offer for this. We may be forced to keep the `transformer` prop around or accept a special method on each content type to handle coercion to a JSON-serializable object.

### Additional Considerations
This RFC is purposefully vague on implementation details. I'd rather we first discuss the goals and then build an API based on those.

I believe this proposal would introduce more complexity into the codebase, especially considering interop with `transformer`. Interop is definitely possible but it makes the implementation more difficult. This also may take a bit of time, an important consideration when we also have the new proxy API to focus on. It could be in our best interest right now to ignore this and address it after v10.

---

If there's anything that isn't clear or I missed something that I should have addressed, please leave a comment.

**Comment by KATT** [comment]
Questions/comments in random order as I think about this:

- Could you move this conversation to #1937 so we only have 1 thread on content types?
- I do think we should continue to support transformers in the short/mid-term
- I don't think "superjsonContentType" is a good one -- if we send a different content-type header on that we'll lose stuff like auto-formatting in the Network tab
- I think a `link` should be able to decide the content type for a specific procedure call. I.e. a `splitLink` can be used on a mutation like `uploadProfilePhoto` to define that it should be passed as binary
- How do we deal with "mixing" content types,
  - For inputs, it's easy to split stuff with links
  - Let's say a query `profile.photo` returns a binary, we need to make sure that's not called in a batchLink that expects JSON in the response

> ```ts
> // specify/override per query
> const user = proxy.uploadFile(/* multipart data stream */, {
>   contentType: multipartContentType
> })
> ```

Maybe should be something like this:

```ts
const user = proxy.uploadFile(/* multipart data stream */, {
   context: {
     contentType: multipartContentType
  },
})
```

This is very complex and steps on so many things. I will need a good few hours to properly think about this and tinker with different solutions before I can give proper feedback on what I _actually_ think is best.

Some base principles to follow through:

- JSON should always be supported as a default without configuration
- I don't think we should get rid of transformers in the short-term
- I think the "ending link" should be able to contain the logic of understanding different content types
  - `httpBatchLink` for JSON will probably be a distinctly different link than `httpBatchLink` for a binary types
-

**Comment by sachinraja** [comment]
will continue discussion in #1937
