### ISSUE TITLE
TanStack query `context` versus tRPC's `context`

### ISSUE THREAD

**Issue by KATT** [trpc/trpc#2395]
From @dyaa in https://github.com/trpc/trpc/issues/2352#issuecomment-1208122411

> It seems like we'll need to make a breaking naming change to the `OperationContext` property name from `context` to something else _ex. `requestContext`_ to avoid naming colliding with `@tanstack/react-query`.
> 
> More context can be found here [#2240 (comment)](https://github.com/trpc/trpc/pull/2240#discussion_r940177822)

_From @KATT in https://github.com/trpc/trpc/pull/2240#discussion_r940286482_

> @sachinraja @jlalmes what do you think we should do here now that the `context` keyword is taken?
> 
> Some options:
> 
> - Put all trpc option under `trpc` - quite annoying for the 99% use-case but also nice to have a distinct place for "our" versus "theirs" in options
> - Call it `trpcContext`? Potentially prefix all our vars with `trpc`?
> - `operationContext`?
> - `opContext`?
> - `callContext`?
>

**Comment by jlalmes** [comment]
> Put all tRPC options under `trpc: { ... }`

Without thinking too much about it - this would be my choice. It seems like the most simple, clean a concise API solution.

**Comment by dyaa** [comment]
I like @jlalmes's suggestion, Should I go ahead?

**Comment by KATT** [comment]
Let's give it some time to marinate and for other people to chime in. I know @TheoBr would like it

**Comment by mmkal** [comment]
I like that idea too 👍

**Comment by KATT** [comment]
I'm happy to move everything to a `trpc` prop for `next`.

Ideally, we'd add support for this & deprecate the existing behavior on `main`.
