### ISSUE TITLE
docs: How to gracefully shut down @trpc/server

### ISSUE THREAD

**Issue by IsaacLeeWebDev** [trpc/trpc#2405]
### Area of Improvement

I'd like to see more in-depth documentation on the best practices related to graceful shutdown, such as the implementation of process signal handlers. 

### Additional information

Node has a guide on how to gracefully shut down an express server here:

https://nodejs.dev/learn/how-to-exit-from-a-nodejs-program

I think a similar, tRPC-focused guide would help!

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing the suggested changes!

**Comment by KATT** [comment]
Unless you have subscriptions, tRPC shouldn't work any differently to how i.e. an Express-server works, could you elaborate more on what you're looking for?

**Comment by IsaacLeeWebDev** [comment]
Hi @KATT ! Thanks so much for the quick reply!

If subscriptions are the only thing you need to consider for graceful shutdowns, I think [the guide on subscriptions](https://trpc.io/docs/subscriptions#creating-a-websocket-server) covers everything I want within the `process.on('SIGTERM', ...` snippet! 

Admittedly, it wasn't obvious to me that this is the only tRPC-specific concern there was around graceful shutdowns. 

Maybe the deeper feature request I didn't know I had was a production-readiness checklist of which graceful shutdowns are one part. One example of that I can think of is [Hasura's Production Checklist](https://hasura.io/docs/latest/deployment/production-checklist/). Maybe tRPC doesn't have enough concerns around production readiness prep to really warrant a guide. In any case, that request would probably be best captured by a separate issue! :)

**Comment by KATT** [comment]
This is the only thing I do:
https://github.com/trpc/examples-next-prisma-starter-websockets/blob/5b89006abb71163f19c4d8c6a2d4fe53eb5356b6/src/server/prodServer.ts#L31-L35
