### ISSUE TITLE
docs: twitter wall script

### ISSUE THREAD

**Issue by KATT** [trpc/trpc#2406]
### Area of Improvement

I would like this file to have some more info on where to get the keys to pull down a new twitter wall :)

https://github.com/trpc/trpc/blob/fee394f351fb723eafdc73b3525270db3cfa7ef3/www/src/components/TwitterWall/script.ts#L11-L17

### Link to related docs

https://github.com/trpc/trpc/blob/fee394f351fb723eafdc73b3525270db3cfa7ef3/www/src/components/TwitterWall/script.ts

### Additional information

@juliusmarminge made it, maybe he knows? :)

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR implementing the suggested changes!

**Comment by juliusmarminge** [comment]
Yea authenticating this was a shitshow...

Here is the appropriate docs for how to generate your oauth stuff, maybe there is a better way? https://developer.twitter.com/en/docs/authentication/oauth-1-0a

**Comment by juliusmarminge** [comment]
Generally, how I did it was I got my consumer key and tokens from the twitter developer portal, then made a request using Postman to sign the certificate then use those credentials in the script...
