### ISSUE TITLE
bug: tRPC in a next.js app swallows errors such that @sentry/nextjs cannot log server errors

### ISSUE THREAD

**Issue by reuben-pct** [trpc/trpc#2414]
### Provide environment information

```
System:
    OS: macOS 12.4
    CPU: (10) arm64 Apple M1 Pro
    Memory: 532.77 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.0 - /usr/local/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.5.5 - /usr/local/bin/npm
  Browsers:
    Chrome: 104.0.5112.79
    Safari: 15.5
  npmPackages:
    @trpc/client: ^9.26.2 => 9.26.2 
    @trpc/next: ^9.26.2 => 9.26.2 
    @trpc/react: ^9.26.2 => 9.26.2 
    @trpc/server: ^9.26.2 => 9.26.2 
    next: 12.2.3 => 12.2.3 
    react: 18.2.0 => 18.2.0 
    react-query: 3.39.2 => 3.39.2 
    @sentry/nextjs: 7.9.0 => 7.9.0
```

### Describe the bug

I've just been wrestling an integration detail between `tRPC`, `next.js` and `sentry`'s error monitoring sdk for next.js (`@sentry/nextjs`). I finally got to the bottom of it and wanted to post it to save some poor souls the hours. 

I don't know that this should be fixed. Maybe it could be added to some documentation as a recommendation for integrating these tools. Happy to make that PR and close this issue if ya'll agree.

Basically I have tRPC implemented in my next.js app (used create-t3-app) and I'm adding sentry error monitoring. Sentry thankfully supplies an sdk for next.js to take care of the dual server/client nature of next.js and log exceptions thrown in both environments - `@sentry/nextjs`. 

However, it seems that errors thrown in a tRPC resolver function are **not** logged to sentry. I went down the rabbit hole with [this thread](https://github.com/getsentry/sentry-javascript/issues/3917) and a couple others before proving you can manually put a try/catch in the resolver function and log it as follows
```
export const someRouter = createRouter().query('something', {
  async resolve() {
    try {
      // some error throwing code
    } catch (e) {
      Sentry.captureException(e)
      throw e
    }
  }
})
```
_Note unless you are wrapping your tRPC router in `@sentry/nextjs`'s `withSentry` method (even through it fails to log the exceptions themselves) to ensure sentry gets initialized via your sentry.server.config.js config, you'll need to also Sentry.init({dsn: ...}) before you can capture the exception_

That resulted in 3 (or whatever your react-query retry threshold is set to) errors thrown for every error thrown in my tRPC query. 

That's not what we want, but this led me to believe that tRPC's internal react-query implementation may be capturing any errors thrown so it can execute its retries before eventually sending the error to client side, so from sentry's perspective the errors are all "handled", and therefore do not get logged via the `withSentry` method.

The solution I ended up with seems reasonably clean. It ensures
- tRPC errors are only thrown once all retries have failed
- the error capturing code is in a centralised location, so no need to implement it on every query
- no need to handroll sentry.init'ing

```
// src/pages/api/trpc/[trpc.ts]
import { createNextApiHandler } from '@trpc/server/adapters/next'
import { createContext } from 'server/router/context'
import { appRouter } from 'server/router'
import { withSentry, captureException } from '@sentry/nextjs'

export default withSentry(
  createNextApiHandler({
    router: appRouter,
    createContext: createContext,
    onError({ error }) {
      if (error.code === 'INTERNAL_SERVER_ERROR') {
        captureException(error)
      }
    }
  })
)
```

### To reproduce

- create a new app via [create-t3-app](https://github.com/t3-oss/create-t3-app)
- integrate sentry following [this guide](https://docs.sentry.io/platforms/javascript/guides/nextjs/)
- throw an error in the example api query
- confirm the log never arrives in your sentry issues tab

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

**Comment by KATT** [comment]
On the server you can:

- [Use `onError`](https://trpc.io/docs/error-handling#handling-errors), or
- [Use  a custom middleware ](https://trpc.io/docs/middlewares#logging)

On the client, you can [create your own link](https://trpc.io/docs/links#creating-a-custom-link) to log request failures.


Unsure what else you'd expect from tRPC here? I think it works very similarly how it would work in for instance Apollo server + client

**Comment by reuben-pct** [comment]
Yep i've opted for `onError` on the server and that solution works fine. I agree i'm not sure there is anything to action in terms of code change here.

> I don't know that this should be fixed. Maybe it could be added to some documentation as a recommendation for integrating these tools. Happy to make that PR and close this issue if ya'll agree.

I'm logging this more as an effort to save someone else the pain when integrating these tools, as tRPC is awesome and sentry is a very common error tracking tool, so as tRPC grows I can only imagine more people will encounter this. 

I can't see how sentry would solve this either, but maybe I should log this in their github instead? I just know from a user perspective i would hunt around tRPC for a solution, rather than sentry, as the issue seems to be specific to the tRPC/nextjs integration rather than sentry - it's just watching for unhandled errors but tRPC swallows them (i think that's what's going on at least).

**Comment by KATT** [comment]
Will close as its not a bug in tRPC, feel free to make contributions to the docs where you'd see it fit! 🙏
