### ISSUE TITLE
@trpc/next: multiple server instances

### ISSUE THREAD

**Issue by juliusmarminge** [trpc/trpc#2418]
### Describe the feature you'd like to request

With growing interest of the Edge runtime, I wonder if having multiple “real” endpoints so that one can choose to run some on the edge, and some not.

### Describe the solution you'd like to see

```ts
// api/trpc/edge/[trpc].ts

// tRPC stuff

export const config = {
  experimentalRuntime: ‘edge’,
};

// api/trpc/notEdge/[trpc].ts

// tRPC stuff

// will run on regular runtime
```

### Desribe alternate solutions

Idk if this is interesting or even useful, maybe it is even possible today using custom links? Just an idea that popped into mind.

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

**Comment by KATT** [comment]
I'm pretty sure this is possible with links already, see #1226 for a SOA example where the client is using links to stich together different apis.

Unsure if we support the edge runtime though 🤔 not tested it

**Comment by sachinraja** [comment]
We probably do since I got it working as a middleware (see https://github.com/sachinraja/trpc-nextjs-middleware) and we support CF workers.

**Comment by juliusmarminge** [comment]
Cool. Then I guess my thought wasn't as unique as I thought ;)
