### ISSUE TITLE
@trpc/react query cache is shared between Next.js pages

### ISSUE THREAD

**Issue by Sendouc** [trpc/trpc#242]
Hey there I noticed potentially a big problem with the instructions on how to use library with security implications.

I noticed this issue https://github.com/Sendouc/sendou.ink/issues/354 and started investigating it. Essentially the query cache is shared between pages. In my case it just added useless bloat to the `getStaticProps` JSONs since it had queries from various pages but of course if you use say `getServerSideProps` with sensitive information then cache being shared like this between requests is dangerous.

Here is how I fixed it: https://github.com/Sendouc/sendou.ink/commit/e42bc3c690c76d36071bb06938633395c7776626

I noticed a discrepancy between how trpc docs instruct to do it: https://trpc.io/docs/nextjs#2-create-a-trpc-client and how React Query docs do: https://react-query.tanstack.com/guides/ssr#using-hydration (see the bolded part especially).

**Comment by KATT** [comment]
@all-contributors add @Sendouc for bug reporting
