### ISSUE TITLE
bug: server side calls not serializing non-json types

### ISSUE THREAD

**Issue by juliusmarminge** [trpc/trpc#2440]
### Provide environment information

```
 System:
    OS: macOS 12.4
    CPU: (8) arm64 Apple M1 Pro
    Memory: 243.75 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
  Browsers:
    Chrome: 104.0.5112.79
    Firefox: 103.0
    Safari: 15.5
  npmPackages:
    @tanstack/react-query: ^4.1.0 => 4.1.0
    @trpc/client: ^10.0.0-alpha.45 => 10.0.0-katt-fix-error-inference-2022-08-10-15-04-30.0+bd693740
    @trpc/next: ^10.0.0-alpha.45 => 10.0.0-katt-fix-error-inference-2022-08-10-15-04-30.0+bd693740
    @trpc/react: ^10.0.0-alpha.45 => 10.0.0-katt-fix-error-inference-2022-08-10-15-04-30.0+bd693740
    @trpc/server: ^10.0.0-alpha.45 => 10.0.0-katt-fix-error-inference-2022-08-10-15-04-30.0+bd693740
    next: 12.2.4 => 12.2.4
    react: 18.2.0 => 18.2.0
```

### Describe the bug

When calling queries on the server using `router.createCaller`, then returning it to the client through `getStaticProps`, the data fails to serialize if it contains e.g. `Date` and throws the following error:
```
Error: Error serializing `.twitterFeed[0].createdAt` returned from `getStaticProps` in "/".
Reason: `object` ("[object Date]") cannot be serialized as JSON. Please only return JSON serializable data types.
```

### To reproduce

```ts
export const getStaticProps = async () => {
  const caller = appRouter.createCaller({});
  const twitterFeed = await caller.twitter.feed();
  //    ^? void | { createdAt: Date, ... }
  return { props: { twitterFeed }, revalidate: 3600 };
};

const FeedPage: NextPage<InferGetStaticPropsType<typeof getStaticProps>> = ({
  twitterFeed,
}) => {
  return <TwitterFeed feed={twitterFeed} />;
};
export default FeedPage;
```

### Additional information

Related PR: https://github.com/trpc/trpc/pull/2233

Reason I would like to do this is to use Next.js's ISR and fetch the feed on the server at some intervals.

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

**Comment by sachinraja** [comment]
Looks like you should really be using the SSG helpers here. Looks like you really want the [SSG Helpers](https://alpha.trpc.io/docs/ssg-helpers).

**Comment by juliusmarminge** [comment]
> Looks like you really want the [SSG Helpers](https://alpha.trpc.io/docs/ssg-helpers).

I looked into that, but that doesnt work in v10 since we "banned string keys for proxy procedures".

Didnt really look into that so might be wrong on that one though.

**Comment by sachinraja** [comment]
Ah yeah let me create an issue for that.

**Comment by juliusmarminge** [comment]
> Ah yeah let me create an issue for that.

Thanks. Was gonna do it but ran out of time so didnt get to it and now I am not on my computer for the weekend 👍

**Comment by sachinraja** [comment]
Mind if I close this issue in favor of #2450?
