### ISSUE TITLE
proxy API for SSG Helpers

### ISSUE THREAD

**Issue by sachinraja** [trpc/trpc#2450]
### Describe the feature you'd like to request

Add function for using the proxy API for SSG helpers.

### Describe the solution you'd like to see

```ts
const ssg = await createProxySSGHelpers({
  router: appRouter,
  ctx: {},
  transformer: superjson,
});

ssg.post.byId.prefetch(1)

```

### Desribe alternate solutions

none

### Additional information

Related issue
- #2440

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

**Comment by KATT** [comment]
Merging that PR and copying my comment from my review in here:

> Looks awesome!
> 
> I'd do a couple of things:
> 
> * [ ]  Update this code to use the new helper https://github.com/trpc/trpc/blob/d33ab65ea244efb5a34afcfb3b2ff1f81bb875e4/examples/next-prisma-todomvc/src/pages/%5Bfilter%5D.tsx#L371-L390
> * [ ]  Update this code to use the new helper https://github.com/trpc/trpc/blob/d33ab65ea244efb5a34afcfb3b2ff1f81bb875e4/examples/next-prisma-starter/src/pages/index.tsx#L95-L119
> * [ ]  Add `@deprecated` on the old functions

**Comment by awkaiser-tr** [comment]
Thanks @sachinraja & @KATT! Happy to see SSG helpers land for the proxy API. 🍻 

It looks like #2451 would have gone out with `10.0.0-alpha.47` but:
```jsx
import { createProxySSGHelpers } from '@trpc/react/ssg';
```
... is not working: `Module '"@trpc/react/ssg"' has no exported member 'createProxySSGHelpers'`

Looking in `@trpc/react/dist/ssg.{mjs|js}` only `createSSGHelpers` is exported in published `alpha.47` package

----

![Screen Shot 2022-08-16 at 6 28 26 PM](https://user-images.githubusercontent.com/85895815/185014646-50f6ee5d-546e-4257-a209-55861981f475.png)
