### ISSUE TITLE
docs: include an inference helper in documentation

### ISSUE THREAD

**Issue by juliusmarminge** [trpc/trpc#2482]
### Area of Improvement

Currently in V10, we infer the types like this:
```ts
// sample router
const router = t.router({
  post: t.procedure.input(z.string()).mutation(() => {
    // ...
    return post.id;
  })
});
type AppRouter = typeof appRouter;

// usage
import type { inferProcedureInput } from "@trpc/server";
import type { AppRouter } from "routers/_app";

export type PostInput = inferProcedureInput<AppRouter['post']>;
```

the double import here is kinda annoying imo, would be nice to provide a wrapper in the documentation that would allow for something like this:
```ts
// utils/trpc.ts
import type{ inferProcedureInput } from "@trpc/server";
import type { AppRouter } from "routers/_app";

export type InferProcedureInput[path] = inferProcedureInput<AppRouter[path]>;

// usage
import type { InferProcedureInput } from "utils/trpc";

type PostInput = InferProcedureInput['post'];
```

### Link to related docs

https://alpha.trpc.io/docs/infer-types

### Additional information

Not a TS-Wizard so I don't know how to make such generic type, since routers can be arbitrary deep. Is it possible?

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing the suggested changes!

**Comment by mmkal** [comment]
In V9, we do something like this:

server/trpc.ts:
```ts
export type RouterTypes = {
  queries: {
    [K in keyof AppRouter['_def']['queries']]: {
      input: trpc.inferProcedureInput<AppRouter['_def']['queries'][K]>
      output: trpc.inferProcedureOutput<AppRouter['_def']['queries'][K]>
    }
  }
  mutations: {
    [K in keyof AppRouter['_def']['mutations']]: {
      input: trpc.inferProcedureInput<AppRouter['_def']['mutations'][K]>
      output: trpc.inferProcedureOutput<AppRouter['_def']['mutations'][K]>
    }
  }
}
```

client/utils/trpc.ts:

```ts
import type {AppRouter, RouterTypes} from '@ourcompany/api/trpc'

export const trpc = createReactQueryHooks<AppRouter>()
export type trpc = RouterTypes
```

client/SomeComponent.tsx:
```tsx
import {trpc} from '~/utils/trpc'

export const SomeComponent = () => {
  const user = trpc.useQuery(['user/lookup', {id: 123}])
  
  if (user.isLoading) return <div>loading</div>
  if (!user.data) return <div>no user found</div>

  const formatted = formatUser(user.data)
  return <div>{formatted.summary}</div>
}

export function formatUser(user: trpc['queries']['user/lookup']['output']) {
  return {
    summary: [data.givenName, data.familyName].filter(Boolean).join(' '),
    redactedEmail: redactEmail(data.email),
  }
}
```

It's nice because you just import `trpc` and typescript is smart enough to know when you want a value and when you want a type. You don't need to add/remove imports as you refactor helper functions or re-use API types.

**Comment by sachinraja** [comment]
This is definitely possible by mapping over the router type:
```ts
import { AnyRouter, inferProcedureInput, Procedure } from '@trpc/server';

type assertProcedure<T> = T extends Procedure<any> ? T : never;

export type GetInferProcedureInput<TRouter extends AnyRouter> = {
  [TKey in keyof TRouter['_def']['record']]: TRouter['_def']['record'][TKey] extends AnyRouter
    ? GetInferProcedureInput<TRouter['_def']['record'][TKey]>
    : inferProcedureInput<assertProcedure<TRouter['_def']['record'][TKey]>>;
};

type InferProcedureInput = GetInferProcedureInput<AppRouter>;
type PostInput = InferProcedureInput['post']; // string
```
One benefit of this pattern is that we could export inference helpers from core instead of having users copy them.

**Comment by carlosbaraza** [comment]
> In V9, we do something like this:
> 
> server/trpc.ts:
> 
> ```ts
> export type RouterTypes = {
>   queries: {
>     [K in keyof AppRouter['_def']['queries']]: {
>       input: trpc.inferProcedureInput<AppRouter['_def']['queries'][K]>
>       output: trpc.inferProcedureOutput<AppRouter['_def']['queries'][K]>
>     }
>   }
>   mutations: {
>     [K in keyof AppRouter['_def']['mutations']]: {
>       input: trpc.inferProcedureInput<AppRouter['_def']['mutations'][K]>
>       output: trpc.inferProcedureOutput<AppRouter['_def']['mutations'][K]>
>     }
>   }
> }
> ```
> 
> client/utils/trpc.ts:
> 
> ```ts
> import type {AppRouter, RouterTypes} from '@ourcompany/server/trpc'
> 
> export const trpc = createReactQueryHooks<AppRouter>()
> export type trpc = RouterTypes
> ```
> 
> client/SomeComponent.tsx:
> 
> ```tsx
> import {trpc} from '~/utils/trpc'
> 
> export const SomeComponent = () => {
>   const user = trpc.useQuery(['user/lookup', {id: 123}])
>   
>   if (user.isLoading) return <div>loading</div>
>   if (!user.data) return <div>no user found</div>
> 
>   const formatted = formatUser(user.data)
>   return <div>{formatted.summary}</div>
> }
> 
> export function formatUser(user: trpc['queries']['user/lookup']['output']) {
>   return {
>     summary: [data.givenName, data.familyName].filter(Boolean).join(' '),
>     redactedEmail: redactEmail(data.email),
>   }
> }
> ```
> 
> It's nice because you just import `trpc` and typescript is smart enough to know when you want a value and when you want a type. You don't need to add/remove imports as you refactor helper functions or re-use API types.
> 
> Might be nice to have such a `RouterTypes` built-in if others also think this pattern would be useful. We kinda expected it would start to get sluggish since it's a big type, but it hasn't been too bad.

Just wanted to say that this is an elegant solution. Love this, quite a nice API to use.
