### ISSUE TITLE
bug: v10 @trpc/client has undefined `global` in workers

### ISSUE THREAD

**Issue by colelawrence** [trpc/trpc#2493]
### Provide environment information

```
  System:
    OS: macOS 12.5
    CPU: (8) arm64 Apple M1
    Memory: 158.41 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.5.0 - ~/.nvm/versions/node/v18.5.0/bin/node
    Yarn: 1.22.17 - ~/.yarn/bin/yarn
    npm: 8.12.1 - ~/.nvm/versions/node/v18.5.0/bin/npm
  Browsers:
    Chrome: 104.0.5112.101
    Chrome Canary: 106.0.5249.0
    Firefox Developer Edition: 104.0
    Safari: 15.6
  npmPackages:
    @trpc/client: 10.0.0-alpha.47 => 10.0.0-alpha.47 
    @trpc/server: =10.0.0-alpha.47 => 10.0.0-alpha.47 
```

### Describe the bug

When attempting to deploy my app I was getting the following error:
```
✘ [ERROR] A request to the Cloudflare API (/accounts/000000011111111122222222/workers/scripts/app-edge) failed.

  Uncaught ReferenceError: global is not defined
    at worker.js:10:10
   [code: 10021]

  
  If you think this is a bug, please open an issue at:
  https://github.com/cloudflare/wrangler2/issues/new/choose
```

### To reproduce

Try to deploy something using something akin to my gist for [wrapping Durable Objects in TRPC](https://gist.github.com/colelawrence/ba912db3cd1539ee820c3fe5e67654df)

### Additional information

I was able to fix in the short term by adding a `banner` via esbuild: `if (typeof global === "undefined") { globalThis.global = globalThis; }`

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

**Comment by KATT** [comment]
Unsure what the `global` is? We don't use any unless you import `adapters/ws`? Please upgrade to latest alpha


<img width="755" alt="Screenshot 2022-08-24 at 18 50 16" src="https://user-images.githubusercontent.com/459267/186476798-c9720f6d-4908-4826-9203-f2f9ac4febc8.png">

**Comment by KATT** [comment]
Ahhhh `@trpc/client`


Is `global` a banned word to use in CF?
