### ISSUE TITLE
feat: reduce number of jobs

### ISSUE THREAD

**Issue by KATT** [trpc/trpc#2528]
### Describe the feature you'd like to request

We run 24? jobs as part of the CI on `next`. We can safely reduce that.

### Describe the solution you'd like to see

- Maybe only have 1 or 2 tests for `./interop`
- Only have 1 or 2 tests for node versions < 16
- Maybe run the full test suite only when a certain label is added?

### Desribe alternate solutions

- Find a way of auto retrying jobs on failures up to `N` times

### Additional information

This happens too much

<img width="1189" alt="Screenshot 2022-08-24 at 19 25 59" src="https://user-images.githubusercontent.com/459267/186484245-f7a8e8e9-bb6c-4a33-bdc4-b7854fdd27e7.png">

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

**Comment by juliusmarminge** [comment]
I'd consider looking into caching and maybe adding `turbo` as a task runner instead of `Lerna`. Many of these tasks would then be omitted when changes are made to parts that doesn't relate.

**Comment by KATT** [comment]
I think all the examples

> I'd consider looking into caching and maybe adding `turbo` as a task runner instead of `Lerna`. Many of these tasks would then be omitted when changes are made to parts that doesn't relate.

I think all the examples would still need to run whenever there was a change to any of the packages, but yeah, not for stuff like changing copy on the website

**Comment by KATT** [comment]
> Fair point. Although a lot of times when we just update docs or examples its kinda annoying having to wait up to 10 mins just to get something to share. Not sure if we can prioritize the `www` deployment since that seems to always take a bunch of time?

shiki made it slow, it was snappy before

**Comment by juliusmarminge** [comment]
> 
> 
> > Fair point. Although a lot of times when we just update docs or examples its kinda annoying having to wait up to 10 mins just to get something to share. Not sure if we can prioritize the `www` deployment since that seems to always take a bunch of time?
> 
> 
> 
> shiki made it slow, it was snappy before

Aah I see :/
