### ISSUE TITLE
docs: Suggestions

### ISSUE THREAD

**Issue by josvanos** [trpc/trpc#2556]
### Area of Improvement

I have a couple suggestions for the docs /website. 

## Home page subtitle
```html
Move Fast and Break Nothing.
End-to-end typesafe APIs made easy.
Leverage the full power of Typescript by calling your backend functions as if they live on the client  
```
I don't know if it is the perfect subtitle, however I think that the subtitle must me more in line with the following quote in ` docs / introduction`.

> "you can share types directly between your client and server, without relying on code generation." 

## Explain what TRPC is 
I think it is a missed opportunity the home page does not have a section about what TRPC really is in detail. The docs / introduction also doesn't really dive into this matter.

I would propose two new sections into the docs / introduction: 

 - [x] TRPC from a rest api background 
 - [ ] TRPC from a graphql background 

I am down to write those sections if there is interest. 

## Terminology Points (?)
-I had never heard of a brownfield project before (Home > advantages) ... I would just say web frameworks with further explanation in the section below.
 - I think Svelktekit is doing a good job in explaining there terminology (https://kit.svelte.dev/docs/appendix). I would recommend to explain in this manner the term 'procedure'. While writing this I have the felling you guys are also improving the docs. So good luck.

### Link to related docs

https://trpc.io/docs/v10/

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR implementing the suggested changes!

**Comment by KATT** [comment]
I like this! Feel free to do a PR with copy changes and @trpc/website-docs will have a look! ❤️
