### ISSUE TITLE
docs: Needs to mention peer dependency of react-query@^3.37.0

### ISSUE THREAD

**Issue by dca123** [trpc/trpc#2558]
### Area of Improvement

Hi,

When following the ` usage with nextjs` the only react-query that's required to be installed is `@tanstack/react-query`. However, when doing this, I don't have any of the typings provided by react query as shown below

![image](https://user-images.githubusercontent.com/3579142/186955829-2960a815-cff2-4235-88a3-e9020cb005aa.png)

I had to install the peer dependency of `"react-query": "^3.39.2",` as mentioned in the yarn install `warning " > @trpc/next@9.27.2" has unmet peer dependency "react-query@^3.37.0".` to get my typings to work again as shown in this image

![image](https://user-images.githubusercontent.com/3579142/186955767-0c2927fb-04be-4f19-ab55-a9d25bf4a029.png)

I'm interested in knowing why this is happening ? Is it possible that the docs for trpc 10.0 snuck in somehow ?

### Link to related docs

https://trpc.io/docs/v9/nextjs

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR implementing the suggested changes!

**Comment by juliusmarminge** [comment]
tRPC v9 is react-query@3.

tRPC v10 is @tanstack/query@4

Docs should be correct on this. Make sure you select the correct versioned docs 👍 

https://trpc.io/docs/v9/nextjs
https://trpc.io/docs/v10/nextjs

**Comment by KATT** [comment]
Ooops, I prob broke this in #2545

**Comment by dca123** [comment]
😆 , I thought I was gaslighting myself since I swore I saw this change on 9.0. Seem slike a good first issue, I'll give it a doc change !

**Comment by dca123** [comment]
Was gonna add the docs for this, but the docs do mention `react-query@3` now thought I can't pin down which commit might have fixed this. Closing the issue 😃

**Comment by juliusmarminge** [comment]
> Was gonna add the docs for this, but the docs do mention `react-query@3` now though I can't pin down which commit might have fixed this. Closing the issue 😃

I believe it was tagged in #2614
