### ISSUE TITLE
feat: remove `PATCH` relics

### ISSUE THREAD

**Issue by KATT** [trpc/trpc#2575]
### Describe the feature you'd like to request

> we used to have some experimental HTTP support for subscriptions with long-polling and that used PATCH (so we could separate it from a mutation/query)

https://discord.com/channels/867764511159091230/1012740470947983462/1013464002162073610

### Describe the solution you'd like to see

- Delete remains of `PATCH` in project
- In http links, make sure to return an error straight-away with information that you need to setup a `wsLink` in case it's called with a subscription

### Desribe alternate solutions

Do nothing

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

**Comment by Grubba27** [comment]
Not sure if it was for taking but I've started implementing it. Hope to have some feedback if I'm on the right track on solving this issue :)
