### ISSUE TITLE
[v10] bug: Subscriptions' return type in onData shouldn't be wrapped in TRPCResultMessage

### ISSUE THREAD

**Issue by JSEverything** [trpc/trpc#2576]
### Provide environment information

```
System:
    OS: Windows 10 10.0.19044
    CPU: (12) x64 Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz        
    Memory: 16.64 GB / 31.95 GB
  Binaries:
    Node: 16.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.15.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (104.0.1293.70)     
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @trpc/client: ^10.0.0-proxy-alpha.57 => 10.0.0-proxy-alpha.57 
    @trpc/server: ^10.0.0-proxy-alpha.57 => 10.0.0-proxy-alpha.57
```

### Describe the bug

[internals/TRPCClient.ts:281](https://github.com/trpc/trpc/blob/next/packages/client/src/internals/TRPCClient.ts#L281) handles the result message and calls `onData()` with just the data, but type defs in [createTRPCClientProxy.ts:42](https://github.com/trpc/trpc/blob/next/packages/client/src/createTRPCClientProxy.ts#L42) wrap it in `TRPCResultMessage`.

In the example below `val` is typed as `TRPCResultMessage<{randomNumber: number;}>` and on autocomplete has `.id?`, `.result` and `.jsonrpc?` (all of which are actually undefined) but outputs `{ randomNumber: 0.864038269589827 }` into console and `val.randomNumber` is marked as non-existent in VS Code but works

### To reproduce

Create any router with a subscription like in https://trpc.io/docs/v10/subscriptions , for example:
```ts
export const appRouter = t.router({
  randomNumber: t.procedure.subscription(() => {
    return observable<{ randomNumber: number }>((emit) => {
      const timer = setInterval(() => {
        emit.next({ randomNumber: Math.random() });
      }, 1000);
      return () => {
        clearInterval(timer);
      };
    });
  }),
});
```
client:
```ts
proxy.randomNumber.subscribe(null, {
  onData(val) {
    console.log(val);
  },
});
```

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

**Comment by KATT** [comment]
Cc @jlalmes

**Comment by jlalmes** [comment]
Confirmed this bug is with the `onData` typing, but only affects the raw client (`useSubscription` works as expected). 

Fixed in https://github.com/trpc/trpc/pull/2578.
