### ISSUE TITLE
feat: update v10 sqlite example 

### ISSUE THREAD

**Issue by KATT** [trpc/trpc#2603]
### Describe the feature you'd like to request

fix v10 example, this is the one linked in the announcement bar

### Describe the solution you'd like to see

- [x] https://github.com/trpc/trpc/blob/next/examples/next-prisma-starter-sqlite/src/server/routers/post.test.ts
- [x] https://github.com/trpc/trpc/blob/next/examples/next-prisma-starter-sqlite/src/utils/trpc.ts
- [x] https://github.com/trpc/trpc/blob/next/examples/next-prisma-starter-sqlite/src/pages/index.tsx

### Desribe alternate solutions

n/a

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

**Comment by gioboa** [comment]
I can work on this 👍

**Comment by KATT** [comment]
@gioboa when do you think you'll do it? :)

**Comment by gioboa** [comment]
I plan this activity next week because now I am on holiday 🌴 is it ok for you?

**Comment by KATT** [comment]
Cool, I might pick it up tomorrow then
