### ISSUE TITLE
feat: Definitive declaration of context types

### ISSUE THREAD

**Issue by iDuuck** [trpc/trpc#2606]
### Describe the feature you'd like to request

I am currently writing an API with trpc, and I am using `ctx` to pass down a user object once an auth header is being sent to the server. However, I am always falling back to using `ctx.user!.id` because the user attribute *can be* (but not must be) `null`/`undefined`.

Is there a way to strictly typing the context for specific routers?

### Describe the solution you'd like to see

I'd love to see a solution for typing the context for different behaviors. Or at least, when there is a middleware, and the middleware is checking for existence of any context variable, so that the context is being "re-typed" with the checked presence in the middleware.

### Desribe alternate solutions

As written above, I am currently using `ctx.user!.id`, which **is working**, but is not ideal.

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

**Comment by KATT** [comment]
I think this is already covered by "Context Swapping" https://trpc.io/docs/v9/middlewares#context-swapping

Also, you might want to check out the middlewares in the next major too, they are a bit more flexible - https://trpc.io/docs/v10/middlewares

**Comment by iDuuck** [comment]
Already looking forward to the new major version, but still waiting for the "stable"/GA release.

I will check out the guide you linked, and come back to this issue, when I have more questions. Closing this until then.
