### ISSUE TITLE
feat: Add option to append Server Timing header in @trpc/server

### ISSUE THREAD

**Issue by mohsen1** [trpc/trpc#2608]
### Describe the feature you'd like to request

[Server Timing](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Server-Timing) can be very useful for getting insights into server performance in production. Please consider adding this as an option where each operation appends a new header for the duration it took.

### Describe the solution you'd like to see

In `nodeHTTPRequestHandler.ts` measure how long it takes to resolve a query:

https://github.com/trpc/trpc/blob/152dd03d899f7a72e15ee31d70b29a60c4dd0291/packages/server/src/adapters/node-http/nodeHTTPRequestHandler.ts#L49

Optionally, append additional headers to the response with those measurements using the Server Timing API standard:
https://github.com/trpc/trpc/blob/152dd03d899f7a72e15ee31d70b29a60c4dd0291/packages/server/src/adapters/node-http/nodeHTTPRequestHandler.ts#L69-L75

### Desribe alternate solutions

Doing this in user-land right now. But should be automatic

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

**Comment by sachinraja** [comment]
This definitely seems like something that should be user-land to me. Could you share your user-land solution?

**Comment by mohsen1** [comment]
Being able to inject server timing markers when request batching is enabled made me believe this should be here. Also going with next.js philosophy of sensible defaults this makes sense (to me).

**Comment by KATT** [comment]
This should [already] be possible in userland by making i.e. using an express middleware or a wrapper fn around the API handler, but could be nice to have some easier way of plugging this in. Unsure what API would be suitable as we likely want to include more headers too.
