### ISSUE TITLE
individual array entries for query key path

### ISSUE THREAD

**Issue by sachinraja** [trpc/trpc#2611]
### Describe the feature you'd like to request

change query key shape so you can invalidate entire routers

### Describe the solution you'd like to see

```ts
["todo.detail.get",1] 
--> 
["todo", "detail", "get",1] 

["todo.list.get", { done: true }]
--> 
["todo", "list", "get", { done: true }]
```

This way you can invalidate entire routers too:
```ts
utils.todo.invalidate()
utils.todo.list.invalidate()
```

suggested by @TkDodo in the Discord: 
https://discord.com/channels/867764511159091230/1014458860355981332/1014505247902797886

### Desribe alternate solutions

none

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

**Comment by JonParton** [comment]
Hi There! 

I started having a bit of a look at this as I have been looking for a chance to contribute and I'm really keen to get V10 out there ASAP too so I can use it in one of our products 😂

I wanted a bit of advice in implementing this and also check I am OK to give it a shot. 

First off I noticed that the code base relies heavily on the first element of the query key being the path and all others being the input args. If we were to start putting the procedure path elements into the array individually rather then concatenated by `.`'s it will be an arbitrary length and hard to tell apart from the input args. 

ie 
```tsx
const key = ["todo","detail","get", { done:true }]
// ^ How would you know for sure how many levels the path goes?
```

However, one idea would be to use a sub array instead as the first element of the key so: 

```tsx
const key = [["todo","detail","get"], { done:true }]
// ^ First key is always an array to the full procedure path! 
```

After a bit of testing this still seems to allow us to do the intended DX improvement

```tsx
queryClient.invalidateQueries([["todo"]]) //Notice the sub array
// This will still invalidate all queries related to the todo router ... what utils.todo.invalidate() would do

queryClient.invalidateQueries([["todo", "list"]]) //Notice the sub array
// This will invalidate all queries at the todo.list sub router ... what utils.todo.list.invalidate() would do
```

[Example sandbox](https://codesandbox.io/s/trusting-montalcini-v6t2fl?file=/src/index.jsx) to show this in action. 

@TkDodo --> Any issues you see with doing this? 

Not sure how big a change across the trpcReact / trpcNext codebase this would be yet ... Feel like it could be quite large unless we wanted to patch/hack it into only doing a conversion to an array at the point of putting it into the actual `tanstack-query` cache rather then changing the `.` separated `path` that is currently passed around everywhere in the client... thoughts here would be useful but I can investigate further if we think the sub array as the first key element has value as a jumping off point.

**Comment by JonParton** [comment]
Another one just for any comments - I noticed this around the Perfromance of the Helper Utils being a concern: 

https://github.com/trpc/trpc/issues/2634#issue-1361198540

Are we OK adding to these in this change / feature request? 

I think we are going to have to add to them to allow you to chain an `.invalidate()` at any point in the router path tree!

**Comment by sachinraja** [comment]
> First off I noticed that the code base relies heavily on the first element of the query key being the path and all others being the input args. If we were to start putting the procedure path elements into the array individually rather then concatenated by .'s it will be an arbitrary length and hard to tell apart from the input args.

This is true for v9, but not true for the proxy setup in v10. Also there can only be one input arg anyway.

> Also happy if it's only some thinking / investigation I have done that contributes to this too if @sachinraja still wants to implement!

I'd love for you to take over this issue!

> Another one just for any comments - I noticed this around the Performance of the Helper Utils being a concern:

Don't worry about that. This shouldn't affect that (at least not noticeably). 

I'm a little confused by your examples since this is likely going to be a v10-only thing. Here's the expected behavior:
This should only be implemented for the new proxy API. We can't really ask users to update their interop queries (that would diminish the whole point of the interop mode).
```ts
// this should use the query key: ['post', 'byId']
// this is much easier to implement since users have no control over the path part of the query key
trpc.post.byId.useQuery({ id: 1 })

// this should be equivalent to queryClient.invalidateQueries(['post', 'byId'])
trpc.post.byId.invalidate()

// this should be equivalent to queryClient.invalidateQueries(['post'])
trpc.post.invalidate()

/* v9 behavior, you should not have to change any code related to this */

// this should not be changed
// this should use the exact query key inputted: ['post.byId', { id: 1 }]
useQuery(['post.byId', { id: 1 }])

// this should be equivalent to queryClient.invalidateQueries(['post.byId'])
utils.invalidateQueries(['post.byId'])
```

**Comment by luixo** [comment]
I'm using getting / updating queries for partial keys in v9 as well.
It would be awesome to have something like
```ts
trpc.post.setQueries(([vars, prevData]) => {
  console.log(vars); // { id: 1 }
  console.log(prevData); // <data> | undefined
});
```
Or at least let it happen not by building keys manually.

**Comment by JonParton** [comment]
Thanks @sachinraja for getting back so quickly!

> I'm a little confused by your examples since this is likely going to be a v10-only thing. Here's the expected behavior:
This should only be implemented for the new proxy API. We can't really ask users to update their interop queries (that would diminish the whole point of the interop mode).

Nope - totally agree. Was never planning on changing how the V9 Interop worked only how things through the proxy were working. Although my examples show building of keys this was just so I could keep my example extremely minimal while I was investigating and not create trpc routers etc ... The key building would happen by the proxy but the end effect would be the same in terms of invalidating multiple queries etc as per the sandbox! 

> This is true for v9, but not true for the proxy setup in v10. Also there can only be one input arg anyway.

Ah OK - I was finding it hard initially to fully separate the V9 and V10 implementations as some parts seemed to cross over and I saw lots of `path, ...others` type deconstruction in the code. Feel I need to look deeper to confirm this isn't happening any where! Also hadn't appreciated the input arg had to be an object and so only 1 item in the array... That will be good to remember as it would always be the last element in the key array!..

I'll take another look as to if we could implement this with the path constituents being at the same level as the input arg rather than being a sub array ... but if the sub array is easier to implement can you see a reason not to do it? In my head almost feels neater keeping them bundled up and knowing they will always be the first element if there is no functional difference. 

> I'd love for you to take over this issue!

Thanks! I'll try and make time to push this forward but feel free to prod me and also take over if I haven't managed to do it by the time you get some headspace to look at it. I won't be precious about it 🙂 Focussed on results and helping to get V10 out rather than how it looks on me etc!

**Comment by JonParton** [comment]
Just a quick confirm on your code examples: 

```tsx
// this should use the query key: ['post', 'byId']
// this is much easier to implement since users have no control over the path part of the query key
trpc.post.byId.useQuery({ id: 1 })
```

Assuming this should have been a query key of `['post', 'byId', {id: 1}]`?

**Comment by JonParton** [comment]
Just to confirm in your code examples: 

```tsx
// this should use the query key: ['post', 'byId']
// this is much easier to implement since users have no control over the path part of the query key
trpc.post.byId.useQuery({ id: 1 })
```

Assuming this should have been a query keyb of 


> I'm using getting / updating queries for partial keys in v9 as well. It would be awesome to have something like
> 
> ```ts
> trpc.post.setQueries(([vars, prevData]) => {
>   console.log(vars); // { id: 1 }
>   console.log(prevData); // <data> | undefined
> });
> ```
> 
> Or at least let it happen not by building keys manually.

Interesting! 

Feel like this may be a separate feature request however to include a `setQueries` util helper rather than directly related to the keys and invalidation! 

Can certainly see the value although I reckon the type inference for the `prevData` etc could be a nightmare as many different types could live at a partial path match! 

Might have to do some kind of discriminated union using the path as the discriminating `type`....

**Comment by sachinraja** [comment]
> I'll take another look as to if we could implement this with the path constituents being at the same level as the input arg rather than being a sub array ... but if the sub array is easier to implement can you see a reason not to do it? In my head almost feels neater keeping them bundled up and knowing they will always be the first element if there is no functional difference.

Definitely something to ask @TkDodo about, it's a good idea IMO.

> Thanks! I'll try and make time to push this forward but feel free to prod me and also take over if I haven't managed to do it by the time you get some headspace to look at it. I won't be precious about it slightly_smiling_face Focussed on results and helping to get V10 out rather than how it looks on me etc!

Thank you! Here are some key files:
https://github.com/trpc/trpc/blob/a038f20c3a9a76fce15dffd5474a9292c3293bf6/packages/react/src/createTRPCReact.tsx#L154
https://github.com/trpc/trpc/blob/next/packages/react/src/shared/proxy/decorationProxy.ts#L17-L30

> Assuming this should have been a query key of ['post', 'byId', {id: 1}]?

Yes

**Comment by luixo** [comment]
> Can certainly see the value although I reckon the type inference for the prevData etc could be a nightmare as many different types could live at a partial path match!

Probably you don't have to invent the wheel here.
I have a helper in my project to figure out any procedure by key (and type):
```ts
// say, we need an output of `posts.byId`:
type MyOutput = TRPCQueryOutput<"posts.byId">;

type TRPCQueryOutput<Path extends TRPCQueryKey> = inferProcedureOutput<
  TRPCQueryValues[Path]
>;

type TRPCQueryKey = keyof TRPCQueryValues;

type TRPCQueryValues = UnionToIntersection<
  FlattenObject<AnyProcedure, QueriesProcedureValues>
>;

type QueriesProcedureValues = ProceduresValues<typeof appRouter, "queries">;

// that is quite a nightmare, I admit
type ProceduresValues<
  Router extends AnyRouter,
  Type extends TypeKey,
  Procedures extends Router["_def"]["procedures"] = Router["_def"]["procedures"],
  ProcedureKeys extends keyof Procedures = keyof Procedures
> = {
  [K in ProcedureKeys]: Procedures[K] extends AnyRouter
    ? ProceduresValues<Procedures[K], Type>
    : Type extends "queries"
    ? Procedures[K] extends QueryProcedure<any>
      ? Procedures[K]
      : never
    : Procedures[K] extends MutationProcedure<any>
    ? Procedures[K]
    : never;
};

// Generic helpers
type FlattenObject<
  Terminator,
  T extends Record<string, unknown>,
  PrevKey extends string = "",
  Key = keyof T
> = Key extends string
  ? T[Key] extends never
    ? never
    : T[Key] extends Terminator
    ? {
        [K in PrevKey extends "" ? `${Key}` : `${PrevKey}.${Key}`]: T[Key];
      }
    : T[Key] extends Record<string, unknown>
    ? FlattenObject<
        Terminator,
        T[Key],
        PrevKey extends "" ? `${Key}` : `${PrevKey}.${Key}`
      >
    : never
  : never;

// https://stackoverflow.com/questions/50374908/transform-union-type-to-intersection-type/50375286#50375286
export type UnionToIntersection<U> = (
  U extends any ? (k: U) => void : never
) extends (k: infer I) => void
  ? I
  : never;
```

From here you can pick only procedures that satisfy starting from prefix (separated by comma) and get tuples of `[path, input, tuple]` for the update.

Now as I wrote that I think that might be a separate feature 😄

**Comment by sachinraja** [comment]
It's definitely possible @luixo. We do have to keep TS perf in mind though. Feel free to make a different feature request for it.

**Comment by TkDodo** [comment]
> I'll take another look as to if we could implement this with the path constituents being at the same level as the input arg rather than being a sub array ... but if the sub array is easier to implement can you see a reason not to do it? In my head almost feels neater keeping them bundled up and knowing they will always be the first element if there is no functional difference.

I see no problem with the sub-array, as the user has no control over the keys anyways. So if we generate:

```
['post', 'byId', {id: 1}]
```

or 

```
[['post', 'byId'], {id: 1}]
```

doesn't make a difference in terms of invalidation.

**Comment by JonParton** [comment]
Awesome - thanks for confirming @TkDodo!!

When ever I manage to grab some time I keep getting deeper into this but as I do I notice there is a decision to be made with how deep we go with the array keys being passed around vs the `.` seperated version.

As some of the core is shared between proxy and legacy a line needs to be drawn some where and I may have to make shared parts aware of if it has been called from a proxy or legacy to handle the differences... Or make the legacy version still store keys as arrays under the hood... Which may be a breaking change if anyone is currently playing with invalidation or updating of data in the cache manually at the moment assuming the `. ` seperates keys...

Anyways when I fully get my head around it I'll post a better explanation on the decision or put in a few PR's with implementation options to choose between...

**Comment by TkDodo** [comment]
thank you so much for this feature - it works perfectly ❤️
