### ISSUE TITLE
Website FAQ page

### ISSUE THREAD

**Issue by ixahmedxi** [trpc/trpc#2654]
### Area of Improvement

A lot of the questions that get asked on discord are very common and can probably be summarised in some sort of a FAQ page, we can gather around some of those questions here on this issue before starting to implement that page.

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR implementing the suggested changes!

**Comment by ixahmedxi** [comment]
Is v10 stable enough for production?

**Comment by KATT** [comment]
"I get `any` everywhere / IT DOESNT WORK"

**Comment by juliusmarminge** [comment]
Might be related to the above but "my input parsers doesn't give me the correct types" - make sure to use strict mode

**Comment by KATT** [comment]
cc @trpc/website-docs

**Comment by KATT** [comment]
"How to enable CORS"

**Comment by rhenriquez28** [comment]
Should we add the FAQ from the SSR docs here as well or do we just reference it? Asking because a lot of questions I see on discord tend to be related to how to use tRPC with SSR

**Comment by KATT** [comment]
See responses here

- https://twitter.com/anthonyShewDev/status/1574032184066813952
- https://twitter.com/alexdotjs/status/1574121827034886144

**Comment by KATT** [comment]
https://github.com/trpc/trpc/discussions/2940

**Comment by KATT** [comment]
"The types are wrong" / `strict: true` / recommend tsconfig - https://github.com/trpc/trpc/issues/3307#issuecomment-1333078390
