### ISSUE TITLE
bug: no way to specify error meta

### ISSUE THREAD

**Issue by ollydixon** [trpc/trpc#2655]
### Provide environment information

System:
    OS: macOS 12.4
    CPU: (8) arm64 Apple M1 Pro
    Memory: 97.84 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.7.0 - /opt/homebrew/bin/node
    npm: 8.15.0 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 105.0.5195.102
    Firefox: 104.0.1
    Safari: 15.5

### Describe the bug

We want to be able to get custom error meta objects.
At the moment it doesn't seem possible.

```
// Invalid phone number
  if (body.status === '3') {
    throw new TRPCError({
      code: 'BAD_REQUEST',
      message: 'Bad phone number',
      cause: 'invalid-number',
    });
  }
```

We need to read 'cause' as message is a user friendly coding error.
It would also be nice to pass meta JSON objects; sometimes error messages need to contain more data.

There seems to be no way to pass though that data.

```
{ [TRPCClientError: Your request is incomplete and missing the mandatory parameter: number] [cause]: undefined, originalError: undefined, shape: {
    message: 'Your request is incomplete and missing the mandatory parameter: number',
    code: -32600,
    data: {
      code: 'BAD_REQUEST',
      httpStatus: 400,
      stack: ''
      path: 'user.enter-phone-number'
    }
  }, data: {
    code: 'BAD_REQUEST',
    httpStatus: 400,
    stack: ''
    path: 'user.enter-phone-number'
  }, isDone: false, name: 'TRPCClientError' }
```

### To reproduce

^^

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

**Comment by ollydixon** [comment]
To fix this I had to add the following

```
.formatError(({ shape, error }) => {
    console.log(error);
    // @ts-ignore
    shape.data.cause = error.cause;
    return {
      ...shape,
    };
  });
```

**Comment by KATT** [comment]
See [the docs](https://trpc.io/docs/v9/error-formatting).


What you want is something like this:

```ts
const router = trpc.router<Context>()
  .formatError(({ shape, error }) => {
    return {
      ...shape,
      data: {
        ...shape.data,
        zodError:
          error.code === 'BAD_REQUEST' &&
          error.cause instanceof ZodError
            ? error.cause.flatten()
            : null,
      },
    };
  })
```

As an example, if you have a custom tree of `ApplicationError`s, you'd do


```tsx

const router = trpc.router<Context>()
  .formatError(({ shape, error }) => {
    return {
      ...shape,
      data: {
        ...shape.data,
        applicationError:
          error.cause instanceof ApplicationError ? { message: error.cause.message } : null,
      },
    };
  })
``

**Comment by KATT** [comment]
It's a bit unintuitive, but the data you change should only be under the `data:`-property, this is because wanna conform to JSON-RPC, but we might reconsider this for v10 & simplify it.

**Comment by KATT** [comment]
This should also work

```ts
const router = trpc.router<Context>()
  .formatError(({ shape, error }) => {
    return {
      ...shape,
      data: {
        ...shape.data,
        cause: error.cause,
      },
    };
  })
```

**Comment by ollydixon** [comment]
I think you should add some params to the "TRPCError" to simplify it; just an opinion though.

**Comment by KATT** [comment]
Feel free to contribute

**Comment by ollydixon** [comment]
@KATT thanks, I'll try make a pull request next week for you :-)
