### ISSUE TITLE
[v10] feat: fix CodeSandbox / stackblitz compatibility

### ISSUE THREAD

**Issue by KATT** [trpc/trpc#2669]
### Describe the feature you'd like to request

https://github.com/trpc/trpc/tree/next/examples/next-prisma-starter doesn't work in stackblitz or codesandbox. Stuff gets inferred as `any` in the frontend - I think it's because Prisma doesn't work or the types aren't setup

- https://codesandbox.io/s/github/trpc/examples-v10-next-prisma-starter-sqlite?file=/src/server/routers/post.ts
- https://stackblitz.com/github/trpc/examples-v10-next-prisma-starter-sqlite?file=src%2Fserver%2Frouters%2Fpost.ts

### Describe the solution you'd like to see

I would like it to work in CodeSandbox so we can embed examples on the tRPC.io website

### Desribe alternate solutions

Delete Prisma from examples?

### Additional information

`any` :(

![Screenshot 2022-09-09 at 18 33 46](https://user-images.githubusercontent.com/459267/189398458-9a017c8c-cc96-4515-a209-598c7738616f.png)

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

**Comment by juliusmarminge** [comment]
I think for the initial landing page we'd want something more minimal like the [next-minimal-starter](https://github.com/trpc/trpc/tree/next/examples/next-minimal-starter)?

**Comment by KATT** [comment]
Sounds good to me!
