### ISSUE TITLE
feat: transport that does not depend on global fetch

### ISSUE THREAD

**Issue by moltar** [trpc/trpc#2700]
### Describe the feature you'd like to request

I'd like to see a transport layer that is pluggable and allows for other implementations to exist and does not assume the existence of `fetch` in the `global` (or `window`) scope.

### Describe the solution you'd like to see

A well-defined interface for the transport layer that can be easily swapped out for other implementations.

### Desribe alternate solutions

Global patching, described here: https://github.com/trpc/trpc/discussions/1982

### Additional information

Related: https://github.com/trpc/trpc/discussions/1982

Node 18 announcement: https://nodejs.org/de/blog/announcements/v18-release-announce/#new-globally-available-browser-compatible-apis

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

**Comment by KATT** [comment]
You can ponyfill `fetch` and `AbortController` already when you create the tRPC-client, is that not enough?

**Comment by moltar** [comment]
It seems like the TypeScript interfaces of `node-fetch` are not compatible, so it cannot be included as a prop.

But also, I think if there was a transport layer, then other, non HTTP transports could be created.

I think generally, RPC is transport-agnostic and tying it to HTTP or WS implementation is not a good design.

**Comment by jlalmes** [comment]
Hi @moltar - this is already possible, I think you are describing the purpose of `adapters` (router-side) and `links` (client-side). Please see [`trpc-chrome`](https://github.com/jlalmes/trpc-chrome/tree/v0.1.0) as an example for web extension where the message passing transport layer is `chrome.connect()`.

**Comment by moltar** [comment]
Would it make more sense the for httpLink to accept fetch implementation than the create client factory function?

**Comment by KATT** [comment]
As a workaround @moltar, you should be able to do:

- `fetch: null as any`
- `AbortController: null as any`

.. then, make sure you don't use the httpLink if you want to do your custom ending link.

Curious, what do you want to call it with actually?

**Comment by moltar** [comment]
As a workaround, we have already used the approach outlined in another discussion that sets the fetch on the global variable.

> Curious, what do transport layer do you want to use?

Right now I'd like to use HTTP, just server-side, which then requires node-fetch. Since we already use axios heavily across the project, I'd probably just create an axios link for now. Once we upgrade to Node 16, I'd use `undici`, which supports fetch starting from Node 16, and will be the default, built-in package in Node 18.

---

As a purely experimental idea, would be cool to try a transport layer that uses pure network sockets, e.g. UDP :)

**Comment by sachinraja** [comment]
I think this has been addressed so I'm going to close it. Feel free to re-open if not.
