### ISSUE TITLE
bug: The inferred type of 'appRouter' cannot be named without a reference to '../../node_modules/@trpc/server/dist/error/formatter.js'. This is likely not portable. A type annotation is necessary.

### ISSUE THREAD

**Issue by mjgerace** [trpc/trpc#2717]
### Provide environment information

```
  System:
    OS: macOS 12.5.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 6.09 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.8.0 - ~/.volta/tools/image/node/18.8.0/bin/node
    Yarn: 1.22.17 - ~/.volta/tools/image/yarn/1.22.17/bin/yarn
    npm: 8.18.0 - ~/.volta/tools/image/node/18.8.0/bin/npm
  Browsers:
    Edge: 105.0.1343.33
    Firefox: 95.0.2
    Safari: 15.6.1
  npmPackages:
    @trpc/server: 10.0.0-proxy-alpha.76 => 10.0.0-proxy-alpha.76 
```

### Describe the bug

I have good reason to believe the following issue is back (search issue history to see previous fixes) with trpc version 10:

`The inferred type of 'appRouter' cannot be named without a reference to '../../node_modules/@trpc/server/dist/error/formatter.js'. This is likely not portable. A type annotation is necessary.` Also occurs with `'../../node_modules/@trpc/server/dist/core/internals/utils.js'`.

#1960  fixed this before, is it possible that the same bug has presented again?

### To reproduce

With an esm module, try to use trpc 10. _More specifically, set up a router with routes in the new trpc10 style_. Also, is `composite: true` required with trpc? I couldn't infer types from the client without this set, and without a `"references": [{ "path": "../bff" }],` in the client tsconfig.json.

tsconfig.json (server):

```
{
  "compilerOptions": {
    "skipLibCheck": true,
    "composite": true,
    "module": "ESNext",
    "moduleResolution": "Node16",
    "sourceMap": true,
    "outDir": "./dist",
    "pretty": true,
    "strict": true,
    "noUnusedParameters": true,
    "removeComments": true,
    "noImplicitReturns": true,
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "experimentalDecorators": true,
    "resolveJsonModule": true,
    "declaration": true,
    "declarationMap": true,
    "rootDir": "src",
    "baseUrl": ".",
    "paths": {
      "@/*": ["./src/*"],
    },
  },
  "include": [
    "./src/**/*.ts"
  ],
}
```

### Additional information

I've tried the fix in "paths", and it doesn't work for me.

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

**Comment by mjgerace** [comment]
I am going to close this with the following notes for anyone encountering the same problem:

At the core of the problem, we are using @trpc/server in both the client and the server. The client, and the server, in my case, were two entirely different folders, with unique tsconfigs, unique package.json files, etc.

Furthermore, I am taking an esm approach on my backend, setting tsconfig to have module/target "ESNext".

It seems that node has trouble resolving which one to import from in certain cases. I also needed to have `declaration: true`, `composite: true` (on my backend) and `references` appropriately set on my front-end, so that my front-end could correctly see the types from the back-end (as I understand it, typescript can't look at types cross-project without this set up correctly). The issue surfaces precisely because of those settings.

So, to fix, you would just assume you can follow one of the many popular approaches listed in a long thread - particularly, the comment relating to TRPC [here](https://github.com/microsoft/TypeScript/issues/42873#issuecomment-1140506416). Well, this didn't work for me.

So, I took it a step further, and set up [turbo](turborepo.com), which centralizes node-modules in one parent folder. I then configured the same solution from that thread, but pointed to my top-level node_modules folder. Everything finally worked.

**Comment by KATT** [comment]
Hey @mjgerace, thanks for sharing how you fixed it, do you feel like there's anything we need to add to the docs in order to improve this (or maybe the FAQ / #2654?)? Feel free to contribute if you can see some quick wins that aren't too hard to do
