### ISSUE TITLE
bug: Data seems to be incorrectly defined in latest v10

### ISSUE THREAD

**Issue by bit-void** [trpc/trpc#2718]
### Provide environment information

```

  System:
    OS: macOS 12.5.1
    CPU: (8) arm64 Apple M1
    Memory: 86.22 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.1 - ~/.nvm/versions/node/v16.17.0/bin/npm
    Watchman: 2022.07.04.00 - /opt/homebrew/bin/watchman
  Browsers:
    Brave Browser: 105.1.43.88
    Chrome: 105.0.5195.102
    Firefox: 102.0.1
    Safari: 16.0
  npmPackages:
    @trpc/client: ^10.0.0-alpha.48 => 10.0.0-proxy-alpha.76 
    @trpc/react: ^10.0.0-alpha.48 => 10.0.0-proxy-alpha.76 
    react: 18.0.0 => 18.0.0 
```

### Describe the bug

I'm receiving a weird error with latest in React Native with react-query and suspense turned on:

```
 ERROR  TypeError: _posts$data.map is not a function. (In '_posts$data.map(function (p) {
          return p.name;
        })', '_posts$data.map' is undefined)

```

### To reproduce

Given this component:

```typescript
function Something() {
  const posts = trpc.posts.all.useQuery();

  return (
    <View>
      <Text>{posts.data?.map(p => p.name).join(" ")}</Text>
      <Text>{posts.error?.toString()}</Text>
    </View>
  )
}
```

And this set up:

```typescript
export default function App() {
  const [queryClient] = useState(() => new QueryClient({
    defaultOptions: {
      queries: {
        suspense: true
      },
    }
  }))

  const [trpcClient] = useState(() =>
    trpc.createClient({
      url: 'http://localhost:2022/trpc',
    }),
  )

  return (
    <trpc.Provider client={trpcClient} queryClient={queryClient}>
      <QueryClientProvider client={queryClient}>
        <StatusBar style="dark"/>
        <View style={styles.container}>
          <Text>Open up App.tsx to start working on your app!</Text>
          <RetryLoader>
            <Something/>
          </RetryLoader>
        </View>
      </QueryClientProvider>
    </trpc.Provider>
  );
}
```

trpc set up like:

```typescript
import { createTRPCReact } from '@trpc/react';
import type {AppRouter} from "../../gateway/src/router"

export const trpc = createTRPCReact<AppRouter>();
```

The server is standard:

```typescript
import {t} from './trpc';
import {postsRouter} from "../posts/router"

export const appRouter = t.router({
  posts: postsRouter
})

export type AppRouter = typeof appRouter
```

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

**Comment by KATT** [comment]
Is the error what it's inferred incorrectly if `suspense: true` is set globally?

**Comment by mjgerace** [comment]
I fixed this by setting `composite: true` in my backend under `compilerOptions` in tsconfig, and adding `"references": [{"path": "../bff" } ],` to tsconfig on the frontend. I doubt this is required but I think v10 has a bug of some sort @KATT

**Comment by mjgerace** [comment]
I think @bit-void will find `posts` typed as `any`.

**Comment by bit-void** [comment]
It's not typed as any actually, it does infer the correct type. If I console.log the data, it is still wrapped in `json` which seems wrong?

<img width="319" alt="Screen Shot 2022-09-14 at 3 28 01 PM" src="https://user-images.githubusercontent.com/161737/190265810-9c6b6678-8cba-451f-b38f-a54067f78027.png">

```
 {"data": {"json": [[Object]]}, "dataUpdatedAt": 1663190899813, "error": null, "errorUpdateCount": 0, "errorUpdatedAt": 0, "failureCount": 0, "fetchStatus": "idle", "isError": false, "isFetched": true, "isFetchedAfterMount": false, "isFetching": false, "isLoading": false, "isLoadingError": false, "isPaused": false, "isPlaceholderData": false, "isPreviousData": false, "isRefetchError": false, "isRefetching": false, "isStale": false, "isSuccess": true, "refetch": [Function bound refetch], "remove": [Function bound remove], "status": "success"}
```

**Comment by bit-void** [comment]
@mjgerace This didn't work for me. Do you have a multi-package set up? I just have simple packages that are not nested together with a simple path based import that is technically coming from outside the project.

**Comment by bit-void** [comment]
@KATT the suspense was a red-herring. I turned off suspense and it has the same issue.

**Comment by mjgerace** [comment]
How are you handling returns in `postsRouter`? It should just be returning a plain javascript object, not serializing or anything fancy.

**Comment by bit-void** [comment]
This is how the router is defined:

```typescript
import {t} from '../router/trpc';

export const postsRouter = t.router({
  all: t.procedure
    .query(async () => {
      return [{id: 1, name: 23}]
    }),
})
```

If I log out `json` on data it works (notice the incorrect types):
<img width="358" alt="Screen Shot 2022-09-14 at 3 39 51 PM" src="https://user-images.githubusercontent.com/161737/190267617-dba416ac-3c6d-403b-a32e-8d07f6fa1541.png">

Output:
```
 [23]
```

**Comment by mjgerace** [comment]
I am using fastify as well, but not encountering this. Are you using superjson or any other serializer?

**Comment by bit-void** [comment]
Huh, that was it. If I remove `superjson` the issue goes away.

This was my setup:

```typescript
import {initTRPC} from '@trpc/server';
import superjson from 'superjson';
import {Context} from './context';

export const t = initTRPC.context<Context>().create({
  transformer: superjson,
  errorFormatter({ shape }) {
    return shape;
  },
});
```

**Comment by bit-void** [comment]
Ah, I see, superjson is adding the top level key `json`. Did the return format change in v10 and `superjson` doesn't understand this?

**Comment by mjgerace** [comment]
No problem, glad I could help. Running into a few other issues myself that seemed to be solved by setting `declaration: false`, which I found from another thread @KATT  made.

**Comment by bit-void** [comment]
Huh, I don't see how to set this up with `createTRPCReact` though. That creator doesn't take any arguments? Do you know how to get the transformer with react working?

I appreciate all the help!

**Comment by bit-void** [comment]
I figured it out from this issue: https://github.com/trpc/trpc/issues/1979, I didn't realize I was creating the client outside of that hook creator.

Thanks again for all the quick help! ❤️
