### ISSUE TITLE
bug: Query invalidation doesn't work

### ISSUE THREAD

**Issue by brandongit2** [trpc/trpc#2724]
### Provide environment information

```
  System:
    OS: macOS 12.6
    CPU: (10) arm64 Apple M1 Pro
    Memory: 93.61 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.8.0 - ~/.nvm/versions/node/v18.8.0/bin/node
    Yarn: 3.2.3 - ~/.nvm/versions/node/v18.8.0/bin/yarn
    npm: 8.18.0 - ~/.nvm/versions/node/v18.8.0/bin/npm
  Browsers:
    Chrome: 105.0.5195.125
    Firefox: 103.0
    Safari: 16.0
  npmPackages:
    @trpc/client: 10.0.0-proxy-alpha.76 => 10.0.0-proxy-alpha.76
    @trpc/next: 10.0.0-proxy-alpha.76 => 10.0.0-proxy-alpha.76
    @trpc/react: 10.0.0-proxy-alpha.76 => 10.0.0-proxy-alpha.76
    @trpc/server: 10.0.0-proxy-alpha.76 => 10.0.0-proxy-alpha.76
    next: 12.3.0 => 12.3.0
    react: 18.2.0 => 18.2.0
```

### Describe the bug

Using the `.invalidate()` method on a query doesn't seem to actually invalidate the query. However using React Query's native `queryClient.invalidateQueries()` works fine.

### To reproduce

This seems to not work:

```ts
const utils = trpc.useContext()
const {data} = trpc.user.getAll.useQuery()

const addUser = trpc.user.create.useMutation({
  onSuccess: async () => {
    await utils.user.getAll.invalidate() // Not invalidating the query
  },
})

const onAddUser: SubmitHandler<User> = async (data) => {
  addUser.mutate(data)
}
```

but this does (using native React Query `queryClient`):

```ts
const queryClient = useQueryClient()
const {data} = trpc.user.getAll.useQuery()

const addUser = trpc.user.create.useMutation({
  onSuccess: async () => {
    queryClient.invalidateQueries([`user.getAll`]) // Works
  },
})

const onAddUser: SubmitHandler<User> = async (data) => {
  addUser.mutate(data)
}
```

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

**Comment by KATT** [comment]
cc @JonParton do you wanna look at this as part of #2713

**Comment by JonParton** [comment]
@brandongit2  --> Hmmmn definitely need to do a reproduction of this as the `invalidate()` is a very light wrapper over the `invalidateQueries()` function from the `queryClient` just setting the query key for you... and all the tests related to this are still working! 

Only things I can think of is somehow the `invalidate()` function is getting the key wrong related to how your router is set up or there is some kind of timing difference where the actual data for `trpc.user.getAll` has not updated in time ... but that seems unlikely as you are using the raw `queryClient` version in the same `onSuccess` callback. 

Using the React Query Dev Tools are you seeing that the `invalidate()` method is definitely not invalidating the query or is it just the data is not coming back updated?!

Can you either provide us a code sandbox (etc) showing this not working [prefered!] or let me know how you have defined your router to see if there is any nuance there and when I get chance I'll try and reproduce?

**Comment by xiaoyu-tamu** [comment]
Do you have duplicate `QueryClientProvider` in your app? 

I'm migrating an existing project to trpc and forgot to remove the `QueryClientProvider` in my `_app.ts`.

**Comment by JonParton** [comment]
That could make sense!! 🙏

**Comment by KATT** [comment]
I'm going to give @brandongit2 some more time to supply a reproduction repo or else I'll close it

**Comment by brandongit2** [comment]
Yep, sorry I forgot about this issue. I'll add a repro on Monday.

**Comment by brandongit2** [comment]
Although one thing I think I remember noticing is that it was trying to invalidate with the key `["user.getAll", ""]` instead of `["user.getAll"]`. Not 100% sure that's what I saw though.

And there's no chance of there being a duplicate QueryClientProvider, this is a new app.

**Comment by KATT** [comment]
Closing for now, re-open if it's experienced again or if you can supply a reproduction. We should have tests that cover this behavior.
