### ISSUE TITLE
docs not fully updated to reflect changes on client initialization

### ISSUE THREAD

**Issue by charkour** [trpc/trpc#2730]
### Provide environment information

  System:
    OS: macOS 12.5.1
    CPU: (8) arm64 Apple M1
    Memory: 132.70 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
    Yarn: 1.22.15 - ~/.nvm/versions/node/v16.15.1/bin/yarn
    npm: 8.18.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
  Browsers:
    Brave Browser: 100.1.37.113
    Chrome: 105.0.5195.125
    Firefox Developer Edition: 104.0
    Safari: 15.6.1
  npmPackages:
    @trpc/client: 10.0.0-proxy-alpha.77 => 10.0.0-proxy-alpha.77 
    @trpc/next: 10.0.0-proxy-alpha.77 => 10.0.0-proxy-alpha.77 
    @trpc/react: 10.0.0-proxy-alpha.77 => 10.0.0-proxy-alpha.77 
    @trpc/server: 10.0.0-proxy-alpha.77 => 10.0.0-proxy-alpha.77 
    next: 12.2.5 => 12.2.5 
    react: 18.2.0 => 18.2.0

### Describe the bug

With version 10.0.0-proxy-alpha.77 and newer the types of the config field in `createTRPCNext` from `@trpc/next` are incorrect. I'm not sure what is the issue, or what changed, but I'll provide a reproduction.

<details>
<summary>Photo of type error</summary>

![image](https://user-images.githubusercontent.com/33156025/190701242-4e04162e-f48a-4413-a461-c13407877fac.png)

</details>

### To reproduce

[stackblitz](https://stackblitz.com/edit/trpc-trpc-r5q6yb?file=src/utils/trpc.ts) forked from the homepage with one change.

I changed the config to match what is listed in the [documentation](https://trpc.io/docs/v10/nextjs#4-create-trpc-hooks). In the documentation, `url` is returned in the config rather than `links`. Should `links` be used instead? If so, let's update the documentation!

```diff
export const trpc = createTRPCNext<AppRouter>({
  config() {
    return {
+      url: getBaseUrl() + '/api/trpc',
-       links: [
-        httpBatchLink({
-          url: getBaseUrl() + '/api/trpc',
-        }),
-      ],
    };
  },
  ssr: true,
});
```

### Additional information

Thanks for the help! Please let me know if you need more information to debug this issue.

If you're already aware of the type regression, please close this. Thanks :)

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

**Comment by KATT** [comment]
Not a bug. See:

- #2723
- #2709 
- https://trpc.io/docs/v10/migrate-from-v9-to-v10#http-specific-options-moved-from-trpcclient-to-links

However, the docs might not have been updated everywhere.

**Comment by charkour** [comment]
Great. Thanks for the quick response! I can update the docs to match the proper usage.

**Comment by KATT** [comment]
> Great. Thanks for the quick response! I can update the docs to match the proper usage.

would love that!
