### ISSUE TITLE
bug: Subscriptions/Websockets events not working

### ISSUE THREAD

**Issue by DavidIlie** [trpc/trpc#2745]
### Provide environment information

```
System:
    OS: macOS 12.5.1
    CPU: (8) arm64 Apple M2
    Memory: 414.83 MB / 24.00 GB
    Shell: 3.5.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.13.0/bin/yarn
    npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
  Browsers:
    Chrome: 105.0.5195.125
    Firefox Developer Edition: 105.0
    Safari: 15.6.1
```

### Describe the bug

Websockets successfully work, tRPC is able to communicate with my backend through websockets, but I am having trouble trying to get events working:

This is purely as a test, I want to reload the client web page when it receives a request to the query.

The WebSocket does work as I have tested using setTimeout and it is able to return a response, but for some reason through `EventEmitter` it does not see any listener and returns false on the query.

### To reproduce

This is my router:
```ts
import * as trpc from "@trpc/server";
import { EventEmitter } from "events";

import { createRouter } from "./context";

const ee = new EventEmitter();

export const configRouter = createRouter()
   .query("change-state", {
      resolve({ ctx }) {
         return ee.emit("ping");
      },
   })
   .subscription("test-ws", {
      resolve({ ctx }) {
         return new trpc.Subscription<{ done: boolean }>((emit) => {
            ee.on("ping", () => {
               console.log("hi");
               emit.data({ done: true });
            });
            return () => {
               ee.off("ping", () => emit.data({ done: true }));
            };
         });
      },
   });
```

My useSubscription:
```ts
trpc.useSubscription(["config.test-ws"], {
   onNext: () => {
      reload();
   },
});
```

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

**Comment by KATT** [comment]
This is tested many times over and definitely not a bug, plus that event emitters are party of node.

Create a repo with a reproduction if you want help.
