### ISSUE TITLE
feat: Allow to override ctx type when middleware is used

### ISSUE THREAD

**Issue by capaj** [trpc/trpc#2747]
### Describe the feature you'd like to request

I have this middleware which refines types on my `ctx`:
```ts
const isCompanyMemberMiddleware = t.middleware(({ ctx, next }) => {
  if (ctx.user?.system_role !== SystemRole.COMPANY_MEMBER) {
    throw new TRPCError({ code: 'UNAUTHORIZED' })
  }

  if (!ctx.user.company_id) {
    throw new TRPCError({ code: 'UNAUTHORIZED' })
  }
  return next({ ctx })
})

const companyProc = t.procedure.use(isCompanyMemberMiddleware)
```

but in my jobs query which uses this middleware typescript does not know that:
![image](https://user-images.githubusercontent.com/1305378/190926085-75f16a1b-1f64-4e80-b517-15fcbec71926.png)

### Describe the solution you'd like to see

It shure would be nice if we could override the `ctx` type with something like:
```ts
const companyProc = t.procedure.use(isCompanyMemberMiddleware).context<{user: {system_role: 'COMPANY_MEMBER', company_id: string}}>()
``` 

### Desribe alternate solutions

for the moment, I am just writing this in every query/mutation:

```ts
companyProc.input(z.object({})).query(async ({ input, ctx }) => {
    const user = ctx.user as ISpottedSessionCompanyMember
    return ctx.prisma.job.findMany({
      where: {
        company_id: user.company_id
      }
    })
  })
```

which works, but it's kind of annoying having to do it in every query/mutation

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

**Comment by KATT** [comment]
Exactly what you're proposing is impossible with typescript, but there's already a solution


```ts
const isCompanyMemberMiddleware = t.middleware(({ ctx, next }) => {
  if (ctx.user?.system_role !== SystemRole.COMPANY_MEMBER) {
    throw new TRPCError({ code: 'UNAUTHORIZED' })
  }

  if (!ctx.user.company_id) {
    throw new TRPCError({ code: 'UNAUTHORIZED' })
  }
  return next({ 
    ctx: {
      user: ctx.user, // will infer user as non-nullable in procedures
    }
  });
})

```

See https://trpc.io/docs/v10/middlewares#context-swapping

**Comment by capaj** [comment]
ah ok, works for me when I call next like this:
```ts
return next({
    ctx: { prisma: ctx.prisma, user: ctx.user as ISpottedSessionCompanyMember }
  })
```

without the explicit cast it does not. Thanks for the docs. I wish I was able to find that previously.

**Comment by KATT** [comment]
Hmmmmmmmmmmm, if `ctx.user.system_role` is a disctiminated union i feel like it should work

Maybe try

```ts
return next({
    ctx: { prisma: ctx.prisma, user: { ...ctx.user } }
  })
```

**Comment by KATT** [comment]
You only need to pass the _diff_ through in the ctx btw,

**Comment by KATT** [comment]
Try
```ts
return next({
    ctx: { user: { ...ctx.user } }
  })
```

**Comment by capaj** [comment]
nope, still TS thinks it's the union instead of the subtype:

![image](https://user-images.githubusercontent.com/1305378/190929421-3ca9b69b-0b80-4383-885d-8ccd169a95d4.png)

**Comment by capaj** [comment]
I have `10.0.0-proxy-alpha.81` BTW
