### ISSUE TITLE
bug: Subscriptions are not re-registered on socket reconnect

### ISSUE THREAD

**Issue by aphex** [trpc/trpc#2776]
### Provide environment information

```
  System:
    OS: Linux 5.4 Ubuntu 20.04.4 LTS (Focal Fossa)
    CPU: (16) x64 Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
    Memory: 28.23 GB / 31.32 GB
    Container: Yes
    Shell: 3.2.2 - /usr/bin/fish
  Binaries:
    Node: 14.18.3 - ~/.nvm/versions/node/v14.18.3/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 8.18.0 - ~/.nvm/versions/node/v14.18.3/bin/npm
  Browsers:
    Chrome: 102.0.5005.61
```

WSL2 though...

### Describe the bug

When the socket connect is lost to the tRPC server and then reconnect subscriptions requests are not automatically sent out again. So subscriptions will be lost.

### To reproduce

```bash
clone https://github.com/aphex/trpc-socket-issue
cd server
npm i
cd ../client
npm i
```

Terminal 1 (in server)
```bash
npm start
```

Terminal 2 (in client)
```bash
npm run dev
```

Vue page and see uptime coming in from socket
See Terminal 1 log for subscription endpoint hit and uptime emitting

Kill Server in Terminal 1
Check Console, see socket disconnected
Restart Server
```bash
npm start
```

See console shows socket is reconnected, however subscription is never receievd
See Terminal 1 subscription endpoint is never hit again, emit never happens

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

**Comment by KATT** [comment]
The behavior should be that we automatically reconnect if the WebSocket connection dies, because it's a real pain in the ass to do this manually.

If someone wants to address this:

- The code is in https://github.com/trpc/trpc/blob/next/packages/client/src/links/wsLink.ts
- The tests are (unfortunately only in v9-interop mode) but in https://github.com/trpc/trpc/blob/next/packages/server/test/interop/websockets.test.ts (might be worth looking at making a fresh test file for this that uses v10 instead)

**Comment by aphex** [comment]
I am sure it's more complicated then this but just tinkering around, maybe this helps save someone a bit of time.

Apply this patch will get things working, but likely leave things in a bad state. 

1 - Don't queue a `subscription.stop` if we are not connected to the socket. If it is queued this line here https://github.com/trpc/trpc/blob/next/packages/client/src/links/wsLink.ts#L124 will keep the request to subscribe from being sent as they both share the same `id`

2 - Prevent the error callback if we have not closed "normally". This will prevent this method from being called here https://github.com/trpc/trpc/blob/next/packages/client/src/links/wsLink.ts#L319 which keep things from being unsubscribed while the socket tried to reconnect. 

Again this likely isn't what we want, as I imagine we do want the server to get both a `subscription.stop` and a second `subscription` so it can run cleanup on the first subscription which is no longer valid. I am also not sure how the unsubscribe and observable stuff is supposed to get wired back up here if it is unsubscribed, but as I mentioned hopefully this points someone in the right direction.

```patch
diff --git a/packages/client/src/links/wsLink.ts b/packages/client/src/links/wsLink.ts
--- packages/client/src/links/wsLink.ts
+++ packages/client/src/links/wsLink.ts
@@ -211,13 +211,17 @@
       for (const [key, req] of Object.entries(pendingRequests)) {
         if (req.ws !== conn) {
           continue;
         }
-        req.callbacks.error?.(
-          TRPCClientError.from(
-            new TRPCWebSocketClosedError('WebSocket closed prematurely'),
-          ),
-        );
+
+        if (state === 'closed') {
+          req.callbacks.error?.(
+            TRPCClientError.from(
+              new TRPCWebSocketClosedError('WebSocket closed prematurely'),
+            ),
+          );
+        };
+
         if (req.type !== 'subscription') {
           delete pendingRequests[key];
           req.callbacks.complete?.();
         } else if (state !== 'closed') {
@@ -255,9 +259,9 @@
       delete pendingRequests[id];
       outgoing = outgoing.filter((msg) => msg.id !== id);
 
       callbacks?.complete?.();
-      if (op.type === 'subscription') {
+      if (activeConnection.readyState === WebSocket.OPEN && op.type === 'subscription') {
         outgoing.push({
           id,
           method: 'subscription.stop',
         });
```

**Comment by KATT** [comment]
Feel free to open a PR with those changes :) I can help with tests

**Comment by aphex** [comment]
@KATT You got it, let me know what you think.
