### ISSUE TITLE
feat: Add "TOO_MANY_REQUESTS" 429 status code to TRPCError

### ISSUE THREAD

**Issue by jaivinwylde** [trpc/trpc#2778]
### Describe the feature you'd like to request

Add the ability to set the TRPCError code to be "TOO_MANY_REQUESTS".

### Describe the solution you'd like to see

I'd like to do what was described previously. I created a middleware that handles IP rate limiting and noticed I couldn't set the TRPCError code to be 429. I'd like to be able to just set the code to something like "TOO_MANY_REQUESTS" and have the status code return with 429.

### Desribe alternate solutions

The next closest error code to use in my view would be "BAD_REQUEST" so I use that now, but covering 429 would be good.

### Additional information

This feature seems really easy to add, but I'm not familiar with the codebase, so it's probably best that an existing contributor just takes a short moment to add support for this.

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

**Comment by KATT** [comment]
See https://github.com/trpc/trpc/pull/1194 for a reference
