### ISSUE TITLE
feat:  typings for transformTRPCResponseItem

### ISSUE THREAD

**Issue by NickyMeuleman** [trpc/trpc#2804]
### Describe the feature you'd like to request

stricter typings for [transformTRPCResponseItem](https://github.com/trpc/trpc/blob/c1b3844de8f366fb8c0409e7a12c5a104e8616ab/packages/server/src/internals/transformTRPCResponse.ts#L4)

### Describe the solution you'd like to see

Inference for the `router` parameter in the `transformTRPCResponseItem` function.
Somehow typing `_def` to have a `transformers` field of type [`CombinedDataTransformer`](https://github.com/trpc/trpc/blob/c1b3844de8f366fb8c0409e7a12c5a104e8616ab/packages/server/src/transformer.ts#L14).

### Desribe alternate solutions

I worked around this in my app ([a template that wires up vite-electron-trpc-prisma ](https://github.com/NickyMeuleman/electron-trpc-prisma)) where I had to copypaste the `transformTRPCResponseItem` function by using the appRouter for my app directly, but that wouldn't be possible in the library code.

### Additional information

![image](https://user-images.githubusercontent.com/30179461/192147440-5cf85081-f3a6-4647-8d99-bdfa797fbf4d.png)

I don't have much TypeScript knowledge, and am wondering what the recommended way to achieve this might be.

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

**Comment by KATT** [comment]
Feel free to reopen if you want to fix it
