### ISSUE TITLE
bug: mutation request remains pending when payload is too big

### ISSUE THREAD

**Issue by mattiaz9** [trpc/trpc#2813]
### Provide environment information

System:
    OS: macOS 12.5
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 182.73 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.0/bin/npm
    Watchman: 2022.03.21.00 - /usr/local/bin/watchman
  Browsers:
    Brave Browser: 105.1.43.89
    Chrome: 105.0.5195.125
    Firefox: 100.0
    Safari: 15.6
  npmPackages:
    @tanstack/react-query: 4.3.4 => 4.3.4 
    @trpc/client: 10.0.0-proxy-alpha.74 => 10.0.0-proxy-alpha.74 
    @trpc/next: 10.0.0-proxy-alpha.74 => 10.0.0-proxy-alpha.74 
    @trpc/react: 10.0.0-proxy-alpha.74 => 10.0.0-proxy-alpha.74 
    @trpc/server: 10.0.0-proxy-alpha.74 => 10.0.0-proxy-alpha.74 
    next: 12.3.1 => 12.3.1 
    react: 18.2.0 => 18.2.0 
    typescript: 4.8.3 => 4.8.3 

### Describe the bug

When I try to perform a mutation with a large payload the fetch request stays blocked on pending.
When payload is below ~15kb it works, but around 20kb it doesn't.

### To reproduce

Send a mutation request like this:
```ts
// client code
const { mutateAsync } = trpc.test.testMutation.useMutation()

const send = async () => {
  const content = "0".repeat(20_000)
  await mutateAsync({ content })
}

// trpc router
export const testRouter = t.router({
  testMutation: authedProcedure
    .input(
      z.object({
        content: z.string(),
      })
    )
    .mutation(async ({ input, ctx }) => {
      console.log("OK") // It's not really OK!
    }),
})
```

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

**Comment by KATT** [comment]
https://nextjs.org/docs/messages/api-routes-response-size-limit?

I very much doubt this is a tRPC-problem, would you be able to fork the [StackBlitz-example in on our website](https://trpc.io/#try-it-out) with a repro?

**Comment by mattiaz9** [comment]
@KATT so I found out the problem is having a middleware. I can't reproduce it in StackBlitz because is throwing errors in a sandbox environment.

I fixed the issue by excluding the api routes from the middleware as explained in the nextjs docs (https://nextjs.org/docs/advanced-features/middleware#matcher):
```ts
export const config = {
  matcher: [
    /*
     * Match all request paths except for the ones starting with:
     * - api (API routes)
     * - static (static files)
     * - favicon.ico (favicon file)
     */
    "/((?!api|static|favicon.ico).*)",
  ],
}
```
