### ISSUE TITLE
We should do an overhaul of https://trpc.io/docs/v10/links

### ISSUE THREAD

**Issue by KATT** [trpc/trpc#2815]
We should document links better, especially have some dedicated docs for `httpLink`/`httpBatchLink`/`wsLink`/etc.

>        We should do an overhaul of https://trpc.io/docs/v10/links
>
> _Originally posted by @KATT in https://github.com/trpc/trpc/pull/2739#discussion_r973630192_

**Comment by rhenriquez28** [comment]
I'll take a crack at this. Will do it in the next couple of days
