### ISSUE TITLE
[v10] docs: Where is useContext()

### ISSUE THREAD

**Issue by anthonyshew** [trpc/trpc#2819]
### Area of Improvement

https://twitter.com/tomlienard/status/1574743822550147073/photo/1

### 👨‍👧‍👦 Contributing

- [x] 🙋‍♂️ Yes, I'd be down to file a PR implementing the suggested changes!

**Comment by iduuck** [comment]
It actually should be there. 

Code: https://github.com/trpc/trpc/blob/next/packages/react/src/createTRPCReact.tsx#L119
Docs: https://trpc.io/docs/v10/invalidateQueries#example-code

So, the code is fine. Is it possible to get a repro?
