### ISSUE TITLE
feat: support `.default(...)` option with zod

### ISSUE THREAD

**Issue by iduuck** [trpc/trpc#2831]
### Describe the feature you'd like to request

I would like to suggest, that we might want to support the `.default({ ... })` option for zod schemas. I just tried, and unfortunately it's not working out of the box.

### Describe the solution you'd like to see

It would be awesome to see it supported, to not spam the code with `??` or `||`

### Desribe alternate solutions

N/A

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

**Comment by KATT** [comment]
How is it not supported? Can you supply an example?

**Comment by iduuck** [comment]
Yeah, just checked the tests (and some more). Will add some more example, so we have a back-test for the `.default` use-case.

Will double-check in my (v9) project.
