### ISSUE TITLE
feat(trpc/next): allow passing complete QueryClient instead of queryClientConfig

### ISSUE THREAD

**Issue by TkDodo** [trpc/trpc#2843]
### Describe the feature you'd like to request

When using `createTRPCNext`, we can pass in a `queryClientConfig` in the [config-callback](https://trpc.io/docs/v10/nextjs#config-callback), for example:

```
export const trpc = createTRPCNext<AppRouter>({
    config({ ctx }) {
        return {
            queryClientConfig: { defaultOptions: { queries: { staleTime: 20 * 1000 } } },
        }
    },
    ssr: true,
})
```

trpc then creates the queryClient for us:

https://github.com/trpc/trpc/blob/18a2757a996187f4637f3bcd7ba3080e3c0198a1/packages/next/src/withTRPC.tsx#L105

https://github.com/trpc/trpc/blob/18a2757a996187f4637f3bcd7ba3080e3c0198a1/packages/next/src/withTRPC.tsx#L174

However, the config alone is not enough to define all defaults. If you want to use [queryClient.setQueryDefaults](https://tanstack.com/query/v4/docs/reference/QueryClient#queryclientsetquerydefaults) to set default values for some queries only, we often do this:

```
const [queryClient] = React.useState(() => {
  const client = new QueryClient({ defaultOptions: { queries: { staleTime: 20 * 1000 } } })

  client.setQueryDefaults(['todos'], { staleTime: Infinity })

  return client
})
```

this will make sure that:

- all queries have a default staleTime of 20 seconds
- queries that match the `['todos']` key have a default staleTime of Infinity

This is currently not possible to achieve in trpc because we don't have access to the queryClient after creation, but before it is put into the `QueryClientProvider`.

### Describe the solution you'd like to see

I'd like to pass the complete `QueryClient` to `createTRPCNext` instead of just the config. If we create the QueryClient on consumer side, the problem would not exist.

## alternative 1

`trpc.useContext()` could grant access to type-safe wrappers of `setQueryDefaults` / `setMutationDefaults`, like it does for `invalidate`. However:

- this access must exist on the top level (each nested router level) because we likely want fuzzy matching, so it depends on:
  - https://github.com/trpc/trpc/pull/2713
- we would technically need to read-and-set this in an effect because the operation itself is not pure, but if we render our app in the meantime, the queries would pick up the wrong defaults, and also, it wouldn't work on the server.

## alternative 2

we could amend the api of the `QueryClient` constructor in react-query so that multiple, imperative calls to `setQueryDefaults` become unnecessary. I am considering this (open for api proposals, too), but I think it would be an orthogonal change to trpc because calling `queryClient.setQueryDefaults` is still something you can do at any time in react-query, but not really in trpc at the moment.

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

**Comment by TkDodo** [comment]
Another thing that's slightly related, where I'm not sure how to address this though is that we sometimes closure over other hooks when creating the queryClient, like:

```
function Component() {
  const toast = useToast()
  const [queryClient] = React.useState(() => new QueryClient({
    queryCache: new QueryCache({
      onError: (error) =>
        toast.error(`Something went wrong: ${error.message}`)
    })),
  })
}
```

so the global `onError` callback of the `QueryCache` shows toasts which are only available from a Provider higher up the tree (a `ToastProvider` from our design-system).

since the client is put into react state by trpc, I cannot do this at all I believe ?

https://github.com/trpc/trpc/blob/18a2757a996187f4637f3bcd7ba3080e3c0198a1/packages/next/src/withTRPC.tsx#L99-L105

**Comment by KATT** [comment]
You're able to work around this, right? It's just that it's not typesafe?

https://stackblitz.com/edit/trpc-trpc-tekvb2?file=src%2Fpages%2F_app.tsx

```tsx
import { useQueryClient } from '@tanstack/react-query';
import type { AppType } from 'next/app';
import { useRef } from 'react';
import { trpc } from '../utils/trpc';

function useOnce(fn: () => void) {
  const isCalledRef = useRef(false);
  if (!isCalledRef.current) {
    fn();
    isCalledRef.current = true;
  }
}

const MyApp: AppType = ({ Component, pageProps }) => {
  const queryClient = useQueryClient();
  useOnce(() => {
    queryClient.setQueryDefaults(['some-key'], {
      // [..]
    });
  });
  return <Component {...pageProps} />;
};

export default trpc.withTRPC(MyApp);
```

**Comment by TkDodo** [comment]
Yeah potentially. The ref workaround for useOnce might not be "safe" for concurrent features, but I guess it's alright.

Do you have a suggestion for the second problem?

**Comment by KATT** [comment]
No, not right now. Would require some sort of API change where we wouldn't use the `withTRPC`-HOC and instead wire it up in a more advanced mode

**Comment by KATT** [comment]
Since I know you're using SSR, and I assume you want to continue doing so), it's a bit tricky

**Comment by TkDodo** [comment]
how would I wire it up in an advanced mode without `withTRPC` ?

right now, I cannot pass a custom `QueryCache` or `MutationCache` because they are passed to the constructor of the `QueryClient`.

I think that letting the `QueryClient` be created in user-land and having it passed to `withTRPC` would solve a lot of problems (apart from the one where we need to closure over a hook) with no (almost no?) drawback, or am I missing something?

We could even make this in a non-breaking way where users would either pass `defaultOptions`, or a complete `QueryClient`, or nothing ...

**Comment by KATT** [comment]
> how would I wire it up in an advanced mode without `withTRPC` ?


Basically, this: https://trpc.io/docs/v10/react#3-add-trpc-providers

But then we need to have a way of using the `withTRPC` `getInitialProps`-magic without using the full HOC... you can probably hack it together by copy/pasting code, but it could be nice if it was separated properly

**Comment by KATT** [comment]
See #2884

**Comment by TkDodo** [comment]
thank you, #2884 would definitely solve part 1 of my problem :)

regarding part 2 and "add-trpc-provider":

let's say I'm _not_ needing SSR of queries (I'm just thinking it's not worth the troubles right now), would I just add the providers manually _instead_ of doing `withTRPC` around my app?

**Comment by KATT** [comment]
> let's say I'm _not_ needing SSR of queries (I'm just thinking it's not worth the troubles right now), would I just add the providers manually _instead_ of doing `withTRPC` around my app?

Correct - see https://trpc.io/docs/v10/react
