### ISSUE TITLE
feat: auto-update dependencies

### ISSUE THREAD

**Issue by KATT** [trpc/trpc#2844]
### Describe the feature you'd like to request

Dependabot used to work. It doesn't now b/c of pnpm.

Apparently neither depfu nor dependabot supports pnpm.

- https://github.com/depfu/feedback/issues/46
- https://github.com/dependabot/dependabot-core/issues/1736

### Describe the solution you'd like to see

Make dependabot or soimilar to work

### Desribe alternate solutions

Canning pnpm in favor of yarn again.

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

**Comment by sachinraja** [comment]
I've used [Renovate](https://www.mend.io/free-developer-tools/renovate/) on everything and it works great

**Comment by KATT** [comment]
Ohhh, yeah, let's get renovate in!

**Comment by KATT** [comment]
I forgot that existed

**Comment by iduuck** [comment]
That's fixed, isn't it, @KATT ?
