### ISSUE TITLE
feat: lock closed issues automatically

### ISSUE THREAD

**Issue by KATT** [trpc/trpc#2849]
### Describe the feature you'd like to request

We all get many notifications on this repo. If we get notifications on issues that are already closed, it's just luck if we do see it. 

### Describe the solution you'd like to see

Lock conversations on closed issues/PRs automatically.

Ideally with a friendly message to create a new issue if they are still experiencing problems. 

### Desribe alternate solutions

Not doing it

### Additional information

There's probably some bot. I'm writing this from my phone off laptop. 

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

**Comment by iduuck** [comment]
Let's use https://github.com/dessant/lock-threads for this. Would be glad to create a new workflow for this.

**Comment by KATT** [comment]
Please do!
