### ISSUE TITLE
bug: loggerLink breaks in React Native

### ISSUE THREAD

**Issue by bit-void** [trpc/trpc#2898]
### Provide environment information

```

  System:
    OS: macOS 12.5.1
    CPU: (8) arm64 Apple M1
    Memory: 157.83 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.1 - ~/.nvm/versions/node/v16.17.0/bin/npm
    Watchman: 2022.09.12.00 - /opt/homebrew/bin/watchman
  Browsers:
    Brave Browser: 106.1.44.105
    Chrome: 105.0.5195.125
    Firefox: 105.0.1
    Safari: 16.0
  npmPackages:
    @trpc/react: ^10.0.0-proxy-beta.13 => 10.0.0-proxy-beta.13 
    react: 18.0.0 => 18.0.0 
    typescript: ~4.7.4 => 4.7.4 

```

### Describe the bug

If you enable loggerLink it fails in react native:

 ERROR  There was a problem sending log messages to your development environment [PrettyFormatPluginError: value.hasOwnProperty is not a function. (In 'value.hasOwnProperty('tag')', 'value.hasOwnProperty' is undefined)]

### Link to reproduction

https://stackblitz.com/github/trpc/examples-next-minimal-starter

### To reproduce

Enable the loggerLink

### Additional information

I believe this is related to how the loggerLink is calling the console, there's some css style stuff which tells me it's targeting a browser. I don't see a simple way of overriding the logger it uses without just forking the code.

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

**Comment by KATT** [comment]
Does it work if you do something like 

```ts
loggerLink({
  console: {
   info: () => '...',
   error: () => '...',
  }
})
```

**Comment by KATT** [comment]
You likely want to specify your own `formatter` for RN

**Comment by bit-void** [comment]
@KATT No, that doesn't work. It looks like internally it's calling to a `defaultLogger` which wraps the `console` and adds all the CSS stuff. 

https://github.com/trpc/trpc/blob/next/packages/client/src/links/loggerLink.ts#L106

I can't override `logger` easily since `LogFn` and associated types are not exported. 

https://github.com/trpc/trpc/blob/efb76a889ad6a35800eacc5c299adad2f62de9cf/packages/client/src/links/loggerLink.ts#L40

Not sure what you mean by providing your own `formatter`.

**Comment by KATT** [comment]
I meant `logger`, not formatter.

Might be that it crashes b/c we have `console` as a default value and it needs a typeof check. Will look as soon as I can, not on a computer for the rest of the day.

**Comment by bit-void** [comment]
Gotcha, yeah I can't really inject `logger` due to the above issues. No worries, easy enough to fork the `loggerLink` just figured I'd report the DX issue!

**Comment by KATT** [comment]
If you fork it, feel free to make a PR with fixes too ☺

**Comment by bit-void** [comment]
@KATT Yeah I'll take a look
