### ISSUE TITLE
bug: Error: A Node.js API is used (setImmediate) which is not supported in the Edge Runtime

### ISSUE THREAD

**Issue by chipit24** [trpc/trpc#2911]
### Provide environment information

```
  System:
    OS: macOS 12.5.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 975.86 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.16.0/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
  Browsers:
    Chrome: 106.0.5249.91
    Firefox: 104.0.2
    Safari: 15.6.1
  npmPackages:
    @tanstack/react-query: ^4.9.0 => 4.9.0
    @trpc/client: ^10.0.0-proxy-beta.13 => 10.0.0-proxy-beta.13
    @trpc/next: ^10.0.0-proxy-beta.13 => 10.0.0-proxy-beta.13
    @trpc/react: ^10.0.0-proxy-beta.13 => 10.0.0-proxy-beta.13
    @trpc/server: ^10.0.0-proxy-beta.13 => 10.0.0-proxy-beta.13
    next: 12.3.1 => 12.3.1
    react: 18.2.0 => 18.2.0
    typescript: 4.8.4 => 4.8.4
```

### Describe the bug

Same bug as in https://github.com/trpc/trpc/issues/2697, however, that issues is closed and was just locked.
I'm running Next.js with the experimental edge runtime enabled via `next.config.js`:
```js
/** @type {import("next").NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  experimental: {
    runtime: 'experimental-edge',
  },
};

module.exports = nextConfig;
```

After trying to set up tRPC, when I run my Next.js app I get the following error:
```
Error: A Node.js API is used (setImmediate) which is not supported in the Edge Runtime.
```

I've tried clearing the `.next` folder (`rm -rf .next`) and I've switched from the Next.js adapter (`trpcNext.createNextApiHandler`) to the fetch adapter (`fetchRequestHandler`) but I'm still getting the error.

It was mentioned in https://github.com/trpc/trpc/issues/2697 that the error could only come from `@trpc/server/adapters/ws` but I'm not importing that myself from anywhere.

### Link to reproduction

https://github.com/chipit24/trpc-edge-error

### To reproduce

1. Clone the repo at https://github.com/chipit24/trpc-edge-error.
2. Run `npm i && npm run dev`.

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

**Comment by sachinraja** [comment]
Setting `runtime: 'experimental-edge` in the `api/trpc` route works fine. Setting it globally does not.

Looks like this error is coming from https://github.com/FormidableLabs/react-ssr-prepass, you can fix it by setting `ssr: false`. If you still want SSR, you can use the [SSG helpers](https://trpc.io/docs/v10/ssg-helpers) in `getServerSideProps`.
