### ISSUE TITLE
bug: Hydration logic error when prefetching existing query in subroute (`v10` / Next.js)

### ISSUE THREAD

**Issue by bennettdams** [trpc/trpc#2919]
### Provide environment information

```
  System:
    OS: Linux 5.10 Ubuntu 20.04.5 LTS (Focal Fossa)
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 16.17.0 - /usr/bin/node
    npm: 8.15.0 - /usr/bin/npm
  npmPackages:
    @tanstack/react-query: ^4.9.0 => 4.9.0 
    @trpc/client: ^10.0.0-proxy-beta.13 => 10.0.0-proxy-beta.13 
    @trpc/next: ^10.0.0-proxy-beta.13 => 10.0.0-proxy-beta.13 
    @trpc/react: ^10.0.0-proxy-beta.13 => 10.0.0-proxy-beta.13 
    @trpc/server: ^10.0.0-proxy-beta.13 => 10.0.0-proxy-beta.13 
    next: 12.3.1 => 12.3.1 
    react: ^17.0.2 => 17.0.2 
    typescript: 4.8.4 => 4.8.4
```

### Describe the bug

Under specific circumstances, there is some error in the hydration logic.

The setup is the following:
 - Index route that fetches data on the client
 - Navigate to a dynamic subroute that prefetches the same query on the server
 - -> Error!

The result is the generic, well-known error message: "Can't perform a React state update on an unmounted component.":

![image](https://user-images.githubusercontent.com/29319414/194131159-2fca6dea-5739-40b2-a434-8367a7165b43.png)

I know that this is not a huge issue in itself, but maybe this still relevant for other parts of the logic and worth investigating, especially because of some weird quirks I'm describing below.

### Link to reproduction

https://github.com/bennettdams/trpc-10-unmounted-bug

## Via reproduction repo:

Steps:

1. `npm i`
2. `npm run dev`
3. Go to <http://localhost:3000>
4. Click on "Dynamic Subroute"
5. Error in console:
   ```
   Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
   at Home
   ```

### Additional information

It took me ages to even being able to create a reproduction repo, because the setup for the error is so weird.

You can make small changes in the repo that will make the error go away, changing only **one** of the following is enough:

- see `pages/_app.tsx`
  - Adding an additional `<Link />`
    or
  - Wrapping the main component (`<Component {...pageProps} />`) in a div

or
- see `pages/user/[userId].tsx`
  - comment out the prefetching (`await ssg.user.byUserId.prefetch({ userId })`)

or
- see `pages/index.tsx`
  - comment out fetching data on the client (`... trpc.user.byUserId.useQuery ...`)

I still don't know why/where exactly the issue comes from. I can only assume that it has to do with hydration because the described changes above all have something to do with that (or with the page root).

---

Now it gets really weird:

I tested & can reproduce this with two tRPC versions:
- `10.0.0-proxy-beta.1`
- `10.0.0-proxy-beta.12`
- `10.0.0-proxy-beta.13`
- `10.0.0-proxy-beta.18`

<details>
  <summary>See old comment</summary>

..but with the newest version (`10.0.0-proxy-beta.14`), this error does not occur anymore!  

I looked at the changes between version 13 and version 14, but can't find anything with my limited knowledge that is related to this behavior:

https://github.com/trpc/trpc/compare/017ac71d5b0cc37d6c1fa22d03377a99a17b6dde...ce9c0196478070f2a6b81993470f0368bb0e1606

(Maybe the [array path update](https://github.com/trpc/trpc/commit/1d187b11f83dade3a0e5643a66b3b4fe5974070c)?)

No idea whether something between 13 and 14 has fixed this or if the error message is somehow swallowed.

I added install helpers in the reproduction repo, so you can switch versions easily, e.g. via `npm run install-12`.
</details>

Update: Since "beta.14", I think that prefetching [does not work anymore](https://github.com/trpc/trpc/issues/2923) - I guess that's why this issue does not exist in beta.14.

Update no. 2: [I added a new route that uses `getServerSideProps`](https://github.com/bennettdams/trpc-10-unmounted-bug/commit/209588896d19557a484b3e88438c7221d51c1dc7) to the reproduction, where this error also occurs.

### 👨‍👧‍👦 Contributing

- [x] 🙋‍♂️ Yes, if someone gives me a hint where to start 😅

**Comment by KATT** [comment]
#2977 should have resolved this. Released in `10.0.0-proxy-beta.18`.

**Comment by bennettdams** [comment]
Hey @KATT,
unfortunately not - [I upgraded the reproduction](https://github.com/bennettdams/trpc-10-unmounted-bug/commit/9b28e874e2aa7b1bab4434f1bf0eb916d418e780) to "beta.18" and it shows the same error.

**Comment by KATT** [comment]
Interesting.

Might be some side-effect of the rehydrating here: https://github.com/trpc/trpc/blob/4e0c18aa3993005b66ae98a501657821fabd28e0/packages/next/src/withTRPC.tsx#L118-L122

**Comment by KATT** [comment]
I am at a loss on what is causing this. 


The fact that it is fixed by wrapping `<Component>` in a `<div>` is **really** strange...

**Comment by bennettdams** [comment]
I don't know if this has something to do with it, but I realized that the app code has no access to the query client:

```ts
// in the repro _app.tsx
function MyApp({ Component, pageProps }: AppProps) {
  const queryClient = useQueryClient()
  return ( ... )
```

![image](https://user-images.githubusercontent.com/29319414/195885480-8721bed0-f656-4922-9128-2152a5be1142.png)

So maybe the error coming from RQ's `hydrate` invocation has something to do with a missing/other query client?

**Comment by bennettdams** [comment]
Omfg, I can reproduce this without tRPC, this is probably a React Query or Next.js bug.


I'm so sorry for wasting all of your time.

**Comment by KATT** [comment]
> Omfg, I can reproduce this without tRPC, this is probably a React Query or Next.js bug.

Do you have a repro w/o tRPC? I'm curious to see!


> I'm so sorry for wasting all of your time.

No worries! This was quite the mindfuck 😅

**Comment by bennettdams** [comment]
Yep, created an issue for React Query with a new reproduction repo:

https://github.com/TanStack/query/issues/4335
