### ISSUE TITLE
docs: 

### ISSUE THREAD

**Issue by Fish1** [trpc/trpc#2936]
### Area of Improvement

In the quick start guide, the explanation of the NPM commands are below the commands themselves.

It took me a minute to understand what I was reading. Normally the explanation of a command is written above the command to be run.

Can the descriptions be moved above the commands?

![image](https://user-images.githubusercontent.com/13600696/194648846-a2f81690-ea18-4ff2-a8b0-d4abf15261f5.png)

### Link to related docs

https://trpc.io/docs/v10/quickstart

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR implementing the suggested changes!

**Comment by KATT** [comment]
Feel free to modify it! ☺

**Comment by KATT** [comment]
Will close this in a few days if you haven't made a PR, @Fish1
