### ISSUE TITLE
feat: use wasm pg for ci? 

### ISSUE THREAD

**Issue by KATT** [trpc/trpc#2937]
### Describe the feature you'd like to request

See if we can use supabase's in memory db to use pg in db

### Describe the solution you'd like to see

It'd be nicer to use pg than SQLite in CI,

### Desribe alternate solutions

- Not doing it. 
- Using SQLite 
- Accepting slow ci and use PG docker thing like we did before
- https://github.com/oguimbal/pg-mem (suggested by @mmkal below)

### Additional information

https://supabase.com/blog/postgres-wasm

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

**Comment by mmkal** [comment]
Another option: https://github.com/oguimbal/pg-mem - doesn't have every Postgres feature but it's designed specifically for this use case (fast CI to test application logic etc.) and the developer is really talented. Haven't tried the supabase one, it looks awesome and more full features but pretty heavyweight and with more complex dependencies.

**Comment by KATT** [comment]
Consider as part of #2835
