### ISSUE TITLE
bug: main page in site trpc.io

### ISSUE THREAD

**Issue by Flashantik** [trpc/trpc#2951]
### Provide environment information

on browser Chrome 

### Describe the bug

Error when i try to go to definition

### Link to reproduction

https://trpc.io/

### To reproduce

Cmd + click on greeting 
<img width="705" alt="Screen Shot 2022-10-09 at 22 59 03" src="https://user-images.githubusercontent.com/25429994/194772301-e39565f5-2639-4020-a853-78b14a284ac2.png">

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

**Comment by KATT** [comment]
I'm not on a laptop but I'm pretty sure this is a stackblitz issue and that it would fix itself when you reload the page and the environment has installed?

**Comment by Flashantik** [comment]
> 
<img width="599" alt="Screen Shot 2022-10-09 at 23 59 26" src="https://user-images.githubusercontent.com/25429994/194774741-ba954f5c-494f-44c6-8b85-6805a2d8c267.png">
yeah seems like the trouble with stackblitz
