### ISSUE TITLE
docs: add docs for `trpc.useContext()`

### ISSUE THREAD

**Issue by KATT** [trpc/trpc#2953]
### Area of Improvement

- We should add docs for `useContext`
- Invalidate Queries should probably be a sub-section for `useContext()`

### Link to related docs

https://trpc.io/docs/invalidateQueries

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR implementing the suggested changes!

**Comment by rhenriquez28** [comment]
I'll take this
