### ISSUE TITLE
feat: add overloads to useQuery

### ISSUE THREAD

**Issue by juliusmarminge** [trpc/trpc#2996]
### Describe the feature you'd like to request

Ref: https://discord.com/channels/867764511159091230/1030047679977357312

tanstack/query has [some overloads](https://github.com/TanStack/query/blob/main/packages/react-query/src/useQuery.ts) when passing `initialData` as options, making the type defined. This is missing in tRPC.

![image](https://user-images.githubusercontent.com/51714798/195579785-8a34e431-f0f2-459c-a2c4-8304e6704400.png)

### Describe the solution you'd like to see

add overloads that uses the `DefinedUseQueryResult`: https://github.com/TanStack/query/blob/afbd6c73776ad2d68b6d5b64ce9888c85c745a90/packages/react-query/src/types.ts#L76

### Desribe alternate solutions

not adding

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

**Comment by KATT** [comment]
Maybe start by adding some failing tests on expected behavior in like [`useQuery.test.tsx`](https://github.com/trpc/trpc/blob/next/packages/server/test/react/useQuery.test.tsx) :)
