### ISSUE TITLE
feat: allow conditional query when value exists

### ISSUE THREAD

**Issue by u007** [trpc/trpc#3022]
### Describe the feature you'd like to request

this example works, but since nextjs support ssg that causes the initial load to have empty query, it will give unnecessary query to backend

```
const { policyId } = router.query as { policyId: string };
const { isLoading, data, error, ...policyReq } = trpc.getPolicy.useQuery({ id: +policyId });
```

### Describe the solution you'd like to see

```
const { policyId } = router.query as { policyId: string };
const { isLoading, data, error, ...policyReq } = trpc.getPolicy.useQuery({ id: +policyId }, { queryWhen: () => !!policyId } );
```

### Desribe alternate solutions

not sure how i could useEffect to work around this

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

**Comment by juliusmarminge** [comment]
This is what `enabled` is for:

https://tanstack.com/query/v4/docs/guides/disabling-queries

**Comment by u007** [comment]
okay thank you
