### ISSUE TITLE
bug: Invalidate all Queries doesn't work.

### ISSUE THREAD

**Issue by martin-fv** [trpc/trpc#3067]
### Provide environment information

```
const utils = trpc.useContext();

onClick={() => {
  utils.invalidate();
}
```

### Describe the bug

Invalidating queries doesn't work. Queries should be tied to a user, so once somebody logs out they should be invalidated.
Is there any other solution.

### Link to reproduction

.

### To reproduce

I can create a reproduction if needed. 

### Additional information

related to https://github.com/trpc/trpc/issues/2724

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

**Comment by rhenriquez28** [comment]
Please create a reproduction, it'd be easier to help you that way

**Comment by JonParton** [comment]
Pretty sure this is a misunderstanding of the invalidate function... Invalidate will cause the calls that it matches to refetch from the server and when those calls return with data the new data will replace what was in the cache for those queries... 

So your backend call that is handling the user information needs to handle whatever state now says they are logged out and return when you are expecting for an un authenticated user etc! 

Without further details and a repro as mentioned above we couldn't help or know if there is actually an issue! 

P. S. General invalidation is working as proven by all the tests!

**Comment by martin-fv** [comment]
Yes you're right, now it works with:
```
import { useQueryClient } from "@tanstack/react-query";
const queryClient = useQueryClient();
queryClient.clear()
```
