### ISSUE TITLE
feat: server/links/procedureLink

### ISSUE THREAD

**Issue by deckchairlabs** [trpc/trpc#3079]
### Describe the feature you'd like to request

Came across a need to have a separate trpc client for server side that calls procedures directly. I think this is probably useful enough to be included in tRPC.

I imagine it would live within the server package, since this is only really useful in a server side context.

### Describe the solution you'd like to see

I've created an implementation here for our use case

https://github.com/exhibitionist-digital/ultra/blob/main/examples/with-trpc/src/trpc/server.tsx

### Desribe alternate solutions

Just providing docs of how to create a custom procedure that does the above.

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

**Comment by sachinraja** [comment]
Awesome, thanks for sharing this! I think this might be too specific to have in core though since it only handles queries.

**Comment by deckchairlabs** [comment]
Not a problem! I was thinking the same
