### ISSUE TITLE
transformResult generates error when called as result of 500 response from server

### ISSUE THREAD

**Issue by andrewbateman** [trpc/trpc#3085]
### Provide environment information

```
 System:
    OS: macOS 12.5
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 219.13 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.18.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.2 - /usr/local/bin/npm
  Browsers:
    Chrome: 106.0.5249.119
    Firefox: 91.0.2
    Safari: 15.6
  npmPackages:
    typescript: * => 4.8.2 

```

### Describe the bug

If the response received by TRPCClient has not been generated by TRPCServer (e.g. it is an unexpected server error, in my case due to an unresponsive database), then the error is passed through to transformResult, which produces another error at [this line](https://github.com/trpc/trpc/blob/040e0fa7fbd1941c9d3ba11faf5d2194faaf64cd/packages/client/src/links/internals/transformResult.ts#L34) ...
```
    ...((!response.result.type || response.result.type === 'data') && {
``` 
...because response.result does not exist. 

This appears to be actually caused by [resolving a promise which should actually be rejected](https://github.com/trpc/trpc/blob/040e0fa7fbd1941c9d3ba11faf5d2194faaf64cd/packages/client/src/links/httpBatchLink.ts#L88), which causes transformResult to be called when it shouldn't be.

The resultant TRPCClientError now contains no details of the actual error cause, but instead shows the line pasted above as the cause of the error.

### Link to reproduction

https://stackblitz.com/edit/github-ujrsmm

### To reproduce

Make the server return a response with error code 500 and non-TRPC standard error format. I have done this by replacing the TRPC handler with a function that mimics the error I am receiving from my server. 

At time of writing StackBlitz is having a fit and not rendering the repro app... hopefully it works shortly

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

**Comment by KATT** [comment]
What do you expect to happen here?

**Comment by andrewbateman** [comment]
See my comments in code below (from [httBatchLink.ts](https://github.com/trpc/trpc/blob/040e0fa7fbd1941c9d3ba11faf5d2194faaf64cd/packages/client/src/links/httpBatchLink.ts#L80), but same behaviour occurs in httpLink also). 

```
const loaders = { query, subscription, mutation };
return ({ op }) => {
  return observable((observer) => {
    const loader = loaders[op.type];
    const { promise, cancel } = loader.load(op);
    //I expect promise to reject immediately, because the response from the server is error code 500
    promise
    .then((res) => {
      //transformResult generates an error, because res = {"message":"Internal Server Error"}, not the shape it expects (TRPCResponseMessage | TRPCResponse)
      const transformed = transformResult(res.json, runtime);
      
      if (!transformed.ok) {
        observer.error(
          TRPCClientError.from(transformed.error, {
            meta: res.meta,
          }),
        );
        return;
      }
      observer.next({
        context: res.meta,
        result: transformed.result,
      });
      observer.complete();
    })
    //the TRPCClientError.from reports the cause as coming from transformResult, because this is where the error is generated, but real cause is that the server response is not as expected
    .catch((err) => observer.error(TRPCClientError.from(err)));
    
    return () => {
      cancel();
    };
  });
};
};
```

Digging a bit deeper, I think you could solve the issue in [httpUtils](https://github.com/trpc/trpc/blob/040e0fa7fbd1941c9d3ba11faf5d2194faaf64cd/packages/client/src/links/internals/httpUtils.ts#L84) (see comments below)
```
const promise = new Promise<HTTPResult>((resolve, reject) => {
    const url = getUrl(opts);
    const body = getBody(opts);

    const meta = {} as HTTPResult['meta'];
    Promise.resolve(runtime.headers())
      .then((headers) =>
        runtime.fetch(url, {
          method: METHOD[type],
          signal: ac?.signal,
          body: body,
          headers: {
            'content-type': 'application/json',
            ...headers,
          },
        }),
      )
      .then((_res) => {
       //check here for res.status  and throw if === 500
        meta.response = _res;
        return _res.json();
      })
      .then((json) => {
        //check here for unexpected json shape and throw if not right
        resolve({
          json,
          meta,
        });
      })
      .catch(reject);
  });
  const cancel = () => {
    ac?.abort();
  };
  return { promise, cancel };
}
```
