### ISSUE TITLE
docs: fix readme on npm

### ISSUE THREAD

**Issue by KATT** [trpc/trpc#3086]
### Area of Improvement

https://www.npmjs.com/package/@trpc/server

doesn't show readme

### Additional information

we can probably use https://assets.trpc.io

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR implementing the suggested changes!

**Comment by Armania** [comment]
Hi, I would be down to make this update. How do I get involved?

**Comment by rubiagatra** [comment]
I think this is not a problem anymore @KATT.

there is a readme at https://www.npmjs.com/package/@trpc/server
