### ISSUE TITLE
bug: @trpc/react-query breaks in typescript < 4.5

### ISSUE THREAD

**Issue by mariandaniel24** [trpc/trpc#3088]
### Provide environment information

```
  System:
    OS: Linux 5.15 Manjaro Linux
    CPU: (12) x64 AMD Ryzen 5 4600H with Radeon Graphics
    Memory: 7.99 GB / 15.05 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
    Yarn: 1.22.18 - ~/.nvm/versions/node/v16.15.0/bin/yarn
    npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
  Browsers:
    Firefox: 105.0.3
  npmPackages:
    @tanstack/react-query: ^4.13.0 => 4.13.0 
    @trpc/client: ^10.0.0-rc.1 => 10.0.0-rc.1 
    @trpc/react-query: ^10.0.0-rc.1 => 10.0.0-rc.1 
    @trpc/server: ^10.0.0-rc.1 => 10.0.0-rc.1 
    react: 17.0.1 => 17.0.1 
    typescript: ~4.3.5 => 4.3.5 
```

### Describe the bug

It is currently not possible to run `@trpc/react-query` with TypeScript versions older than 4.5 ([see TS changelog](https://devblogs.microsoft.com/typescript/announcing-typescript-4-5/#type-on-import-names)). Upgrading to 4.5 fixes this issue.

The following is thrown when running `tsc` on TS 4.3:
![image](https://user-images.githubusercontent.com/33154737/198550907-26b59463-47d2-4195-ba23-4c68bcc8b688.png)

### Link to reproduction

https://stackblitz.com/edit/github-pe2txe?file=src/main.ts

### To reproduce

1. Open the reproduction link
2. Run `npm run tsc`
3. See error

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

**Comment by sachinraja** [comment]
We're not going to support TypeScript < 4.5, but we should update the docs to say that we require the latest version of TS. Right now it says we require 4.1:
https://trpc.io/docs/v10/quickstart#installation.

**Comment by KATT** [comment]
Use a newer version. We should update docs though
