### ISSUE TITLE
feat: support `cursor` path for `useInfiniteQuery`

### ISSUE THREAD

**Issue by JesusTheHun** [trpc/trpc#3107]
### Describe the feature you'd like to request

Right now if you want to use `useInfiniteQuery`, your procedure need to accept a `cursor` property at the root of its `input`.
My request is to support a custom path for the `cursor` property.

I like to namespace stuff, and having to set a `cursor` property at the root instead of inside a `page` property clearly messes with my chakras.

### Describe the solution you'd like to see

The most simple & open solution that comes to my mind would be the following:
```ts
return trpc.myProcedure.useInfiniteQuery(someParams, {
  setCursor: (input, cursor) => merge(input, { page: { cursor }}),
});
```

### Desribe alternate solutions

Another solution could be to define the path of the cursor with a xpath-like definition: 
```ts
return trpc.myProcedure.useInfiniteQuery(someParams, {
  cursorPath: '$.page', // input: { page: { cursor: any }}
});
```

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

EDIT : before I start working on this, can I have a "go" from one of the maintainers ? So I don't work on this to see it declined because it doesn't align with the project direction :D

**Comment by KATT** [comment]
This seems quite hard to implement and get nice DX all the way through. Right now we limit so you can `.useInfiniteQuery` on things that don't have `{ cursor: any }` as the `input`.

I think I prefer to keep this opinionated - @sachinraja / @TkDodo WDYT?

**Comment by JesusTheHun** [comment]
@KATT why do you think it's si hard? I took a look and the only obstacle I found was the type received by the `useInfiniteQuery`, which can be obtained with a nice recursive conditional type.

**Comment by KATT** [comment]
We won't do this within the core team, so I'll close this, but if you have a great solution, I'm happy to review & consider it.
