### ISSUE TITLE
bug: e2e testing broken on `next-prisma-starter`

### ISSUE THREAD

**Issue by KATT** [trpc/trpc#3121]
### Provide environment information

n/a

### Describe the bug

- E2E testing is broken. 
- First bad commit was #2852 which updates Playwright so I'm suspecting that's the problem

### Link to reproduction

https://github.com/trpc/examples-next-prisma-starter

### To reproduce

n/a

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

**Comment by bnrosa** [comment]
I can work on that.

**Comment by KATT** [comment]
Cool! The actual files to edit are in https://github.com/trpc/trpc/tree/next/examples/next-prisma-starter

The repo I link is just a clone of that. 

Will invite you as a collaborator

**Comment by bnrosa** [comment]
`yarn test:e2e` works, is this already solved?

**Comment by nilskjQL** [comment]
This still does not work when I just create a fresh starter. I'm on investigating this.
