### ISSUE TITLE
bug: nested routers allow invalidation with wrong params

### ISSUE THREAD

**Issue by TkDodo** [trpc/trpc#3122]
### Provide environment information

```
  System:
    OS: macOS 12.5.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 146.83 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
  Browsers:
    Brave Browser: 107.1.45.113
    Chrome: 107.0.5304.87
    Firefox Developer Edition: 106.0
    Safari: 15.6.1
  npmPackages:
    typescript: 4.6.2 => 4.6.2 
    @tanstack/react-query: 4.10.3 => 4.10.3 
    @trpc/client: 10.0.0-rc.3 => 10.0.0-rc.3 
    @trpc/next: 10.0.0-rc.3 => 10.0.0-rc.3 
    @trpc/react-query: 10.0.0-rc.3 => 10.0.0-rc.3 
    @trpc/server: 10.0.0-rc.3 => 10.0.0-rc.3 
    next: 12.3.0 => 12.3.0 
    react: 17.0.2 => 17.0.2 
```

### Describe the bug

If you have nested routers, you can use `useContext()` and call `invalidate` on a router with wrong variables, which doesn't work at runtime and should yield a type error (but it doesn't).

### Link to reproduction

https://codesandbox.io/s/festive-star-xjoi30?file=/src/pages/index.tsx

### To reproduce

look at the code for the button that says `this doesn't do anything ❌`

it doesn't do anything at runtime, which is fine, but it should yield a type error when trying to invoke:

```
utils.todos.invalidate({ id: 5 });
```

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

**Comment by JonParton** [comment]
Interesting 🤔

I though I put in tests for this!!

**Comment by KATT** [comment]
I think if we invalidate full routers, we should not allow arguments at all? Otherwise I think the typescript inference gets a bit crazy

**Comment by JonParton** [comment]
Well... Having had a quick look at the example you sent @TkDodo... It seems like the types are correct there!? 

Although you have not instantiated a query with id 5... As far as typescript is concerned looking to invalidate a query with an id of 5 is valid and more a runtime rather then type concern? 

I mean if 5 was instantiated in another component or with a useQueries then it would actually do something right?! Also you may have mutliome sub queries in that router that have an Id input param not just the one (may make more sense when it is a named id like `userId` as it is likely to be the same thing across queries!) 

... Regarding removing this capability Katt... I still think it works and is usefull in most cases to allow you to scope the queries invalidated and reduce calls to the server no? I dont think the typescript types are that crazy now!

(P. S. Sorry if I am missing something, I'm on mobile, and on holiday in Norway 🇳🇴!)

**Comment by KATT** [comment]
I can't see an experience that is great DX.

Like, either you invalidate narrowly on specific procedure or wide on a full router or procedure. Mixing narrow input arguments with wide selector feels like it can never be not confusing

**Comment by TkDodo** [comment]
@JonParton I'm calling:

```
utils.todos.invalidate({ id: 5 });
```

the correct command to invalidate todo 5 would be:

```
utils.todos.detail.invalidate({ id: 5 });
```

note that I have nested routers - `todos` consists of `.list` and `.detail`

`utils.todos.invalidate` should _never_ allow any input arguments, because it's not a "leave" router. It's a group of routes that should match all children with react-query's fuzzy matching.

> I can't see an experience that is great DX.
Like, either you invalidate narrowly on specific procedure or wide on a full router or procedure. Mixing narrow input arguments with wide selector feels like it can never be not confusing

not sure I understand that @KATT . I think it should be pretty clear when and where _input_ is allowed or required:

- on `utils.todos.invalidate`, there is no input. any input should type error. calling this invalidate will invalidate everything todo related - all lists and all details.
- on `utils.todos.details.invalidate`, you can have optional input, because:
  - passing an input would only invalidate that specific todo
  - passing no input would invalidate all todo details.

**Comment by JonParton** [comment]
Katt was replying to me TKDodo as I was arguing we should able to do this so you could cast the net wide and get all queries that had an input of say `userId:5` and so all that relate to that user for example...

Both of you guys are agreeing this shouldn't be possible against I, that thought it may be usefull 😂

**Comment by JonParton** [comment]
Alternative is making sure that any invalidates you want to do for a particular id are done at all leaves you add, and add in the future (maintenance!) , for my little example of userid 5!

If it's better not to support it then it could be removed and let that be the solution!  ☹️ Ha.

Me trying to be too "clever" and support to much I guess!
