### ISSUE TITLE
feat: Cloudflare Workers Fetch adapter types should support env

### ISSUE THREAD

**Issue by Eduard-Hasa** [trpc/trpc#3127]
### Describe the feature you'd like to request

When using the fetch adapter, the defined request type is great for basic needs but Durable Objects are a key benefit to Cloudflare Workers and the env is required in order for them to be accessible.

### Describe the solution you'd like to see

The types: FetchHandlerRequestOptions, FetchCreateContextFnOptions, .... whatever else needs it.

Should both include the env variable so that we can access the env in each endpoint just like we would access other custom context objects. For example "ctx.env"

### Desribe alternate solutions

I have tried making my own FetchCreateContextFnOptions but then FetchHandlerRequestOptions throws an error. I guess I could for my own Fetch adapter but would rather not. Plus I think Durable Objects are a large part of Cloudflare Workers and should be supported.

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

**Comment by Eduard-Hasa** [comment]
I actually managed to get it working by setting the env to a global variable thus being able to access it inside any of the trpc routers. Im not sure if you guys think this should be a part of the fetch handler adapter, but something to think about even adding some documentation would be helpful.

**Comment by panthyy** [comment]
Isn't it possible to just send it through the context?

**Comment by KATT** [comment]
> I actually managed to get it working by setting the env to a global variable thus being able to access it inside any of the trpc routers. Im not sure if you guys think this should be a part of the fetch handler adapter, but something to think about even adding some documentation would be helpful.

Feel free to add documentation. For now I'll consider this closed
