### ISSUE TITLE
feat: prefix infinite queries differently to "normal" queries?

### ISSUE THREAD

**Issue by KATT** [trpc/trpc#3128]
### Describe the feature you'd like to request

Currently, the cache gets a bit messed up if you use an endpoint the with `.useInfiniteQuery()` in one part of the app and `.useQuery()` in another.

### Describe the solution you'd like to see

Currently, we store cache keys as `[pathArray, input]`-tuple

Maybe, we should store it as `['query' | 'infinite', pathArray, input]`-tuple?

Or a `[pathArray, 'query' | 'infinite', input]`-tuple?

### Desribe alternate solutions

Not doing it

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

**Comment by KATT** [comment]
cc @JonParton / @TkDodo - thoughts?

**Comment by JonParton** [comment]
Makes sense as the structure of the Data in the cache is different depending on which is used (infinite vs normal)

Only thing I'm considering is if it makes sense to put it at the end as in most cases it won't be very important.... Not sure if order makes any real difference to react query... Don't think so!!

It's a toss up, as semantically type then path makes sense but amount of usage and the current api with the `useQuery` at the end kind of matches up to having it later. Not a huge deal either way!

The only other thing I'm considering is I have an idea to make a `utils.todo.getById.getQueryKey(inputParams)` function on useContext... _(Which could be used at any router level)_ ... With this i guess you would also have to add a second param of `queryType` if you wanted to make a complete query key that would target only `infinite` or normal `queries` in the cache as it would not be determinate from the path!! Although only important for uses where you are going to be interacting with the cache data structure of the queries.

**Comment by TkDodo** [comment]
Can you use the same endpoint for normal and infinite queries? They do have different structures. They also definitely shouldn't share the same query key...

**Comment by KATT** [comment]
Cool, yeah, currently they share key, we just do a `[['post', 'list'], { limit: 5 }]`-style tuple and the suggestion is to change it to `['query', ['post', 'list'], { limit: 5 }]  | ['infiniteQuery', ['post', 'list'], { limit: 5 }]`

**Comment by TkDodo** [comment]
keep in mind though that this will change invalidation logic: if the identifier lives at the front, you'd need to specify which type to invalidate. Wouldn't it be better to have this be appended to the end?

```
[['post', 'list'], { limit: 5 }, 'infiniteQuery']
[['post', 'list'], { limit: 5 }, 'query']
```

because it's the same routing endpoint, and invalidation should likely target all at the same time?

**Comment by KATT** [comment]
It has to be before the `input`, unfortunately, otherwise we get errors when dehydrating/hydrating without superjson.


```js
JSON.stringify([['post', 'list'], undefined, 'query'])
// -> '[["post","list"],null,"query"]'
```

**Comment by KATT** [comment]
I guess a workaround would be to make the input a tuple too, but that also feels hairy.

**Comment by KATT** [comment]
Maybe 

```ts
[['post', 'list'], 'infiniteQuery', { limit: 5 } ]
[['post', 'list'], 'query', { limit: 5 } ]
```

**Comment by TkDodo** [comment]
> Maybe
> 
> ```ts
> [['post', 'list'], 'infiniteQuery', { limit: 5 } ]
> [['post', 'list'], 'query', { limit: 5 } ]
> ```

hmm, you still can't access all posts with a certain limit then.

How are keys currently built? if we were to put all params into an object, we wouldn't have a problem with undefined?

```
[['post', 'list'], { params: undefined }, { type: 'query' }]
// [["post","list"],{},{"type":"query"}]'

[['post', 'list'], { params: { limit: 5 }}, { type: 'infiniteQuery' }]
// '[["post","list"],{"params":{"limit":5}},{"type":"infiniteQuery"}]'
```

**Comment by KATT** [comment]
> hmm, you still can't access all posts with a certain limit then.

It's only interesting to do it distinctly based on an infinite query though since the data is different

**Comment by JonParton** [comment]
> It's only interesting to do it distinctly based on an infinite query though since the data is different

@KATT -  Although this is very much the case when filtering by the infinite query specific `limit` in the above example this also precludes you being able to filter for all queries with a particular input such as `userId: 5` like we removed from the invalidate functionality but said could be done by manual key generation...

The way I started doing it in #3135 was to not include things that are not passed: 

```ts
  //packages/react-query/src/internals/getArrayQueryKey.ts
  //....

  // Make sure we omit the type for any query key that does not want to
  // specifically select to allow react query fuzzy matching)
  // NOTE: We know type if provided will be a `string` where as input will be an `object`
  if (type === 'any') {
    return input === undefined ? [arrayPath] : [arrayPath, input];
  } else {
    return input === undefined ? [arrayPath, type] : [arrayPath, input, type];
  }
```
IE
```tsx
// Query with no inputs 
[["post","list"],"query"]

// Query with an input
[["post","list"],{userId:10},"query"]

// infinite Query with an input
[["post","list"],{limit:5, cursor:"513"},"infinite"]



// Query key used to invalidate all the `post` router
[["post"]] // ✅

// Query key I hoped would invalidate all queries in the post router
[["post"],"query"] // ❌ Won't work as "query" string is 3rd position

// Query key I hoped would invalidate all queries and infinite Queries with an input of `userId:10`
[["post"], { userId:10 }]  // ✅ Would work in the way I've currently implemented
// ... but wouldn't work if we switched around to be [path, type, input] ❌

```
However, putting what I now understand from @TkDodo onto the above and reading this [issue from react query](https://github.com/TanStack/query/discussions/3316#discussioncomment-2213648) I don't think this allows all cases. 

I want to do a little query key playground to confirm but I think the best option would be an object as the second part of the queryKey tuple, similar to what @TkDodo  suggested but with a small modification of one object not two: 

```ts
// Query with no inputs 
[["post","list"],{ type:"query" }]

// Query with an input
[["post","list"],{ type:"query", input: { userId:10 } }]

// infinite Query with an input
[["post","list"],{ type:"infinite", input: { limit:5, cursor:"513" } },]


// Query key used to invalidate all the `post` router
[["post"]] // ✅

// Query key to invalidate only `queries` in the post router
[["post"], { type:"query" }] // ✅ 

// Query key to invalidate all queries and infinite Queries with an input of `userId:10`
[["post"],{input: { userId:10 } }]  // ✅❓// I think would work!

// Query key to invalidate only queries with an input of userId:10
[["post"],{ type: "query", input: { userId:10 } }] // ✅❓

// All queries any where in the cache
[[], { type: "query" }] // ✅
```

So general key structure would be: 
```ts
[
   string[], // Array path
  {
     input?: {[string]:any}, // input if there is one!
     type?: "query" | "infinite" // Query type or missing if targeting any type in invalidate etc!!
   }
]
```

This then gives you the flexibility to filter on 
- any full or partial tRPC path (`[]` to target all)
- a specific or any query type (omit it!)
- any input that has been passed in to the query or all inputs (omit it!)

**Comment by TkDodo** [comment]
```
// Query key to invalidate all queries and infinite Queries with an input of `userId:10`
[ ["post"], { input: { userId:10 } } ]  // ✅❓// I think would work!

// Query key to invalidate only queries with an input of userId:10
[ ["post"], { type: "query", input: { userId:10 } } ] // ✅❓
```

yes, those two would work.

I also thought about having one object, but I thought that we then wouldn't be able to allow having `type` provided from the params. Having the `input` be a separate entry in the object would solve that nicely I think 👍

**Comment by KATT** [comment]
Ohhh, so react-query does like a "matches" object and not equal to object? I wasn't clear on that from the docs

Given key: `[ ['post', 'byId'], { type: "query", input: 1 } ]`

`invalidateQueries([ ['post', 'byId'], { input: 1 } ])` would invalidate that key even if we don't define the `type`?

Otherwise, I think this structure would work too:

Making `input` a tuple as well (because `undefined` becomes `null` when stringifying)


```ts
[ ['post', 'byId'], [1], 'query']
[ ['post', 'byId'], [1], 'query']
```

so without an inputundefined, it'd be


```ts
[ ['post', 'all'], [], 'infinite']
[ ['post', 'all'], [], 'query']
```

Anyway, I'm happy with either. I'd definitely pay someone $100 to fix this, it's hairy, mainly because of the interop mode with the old v9 clients.

**Comment by JonParton** [comment]
> Ohhh, so react-query does like a "matches" object and not equal to object? I wasn't clear on that from the docs

That's my understanding and confirmed by TKDodo above! 

---

Yeah Interop is definitely going to make it a little hairy, but I managed it with the Array Query key change so hopefully I can do similar! 🤔

Having worked through the different options taking on board TkDodo's comments and yours I still think the Object Route is the neatest way and is nicely explicit! 

Also means if a [Vanilla React Query function](https://tanstack.com/query/v4/docs/guides/query-invalidation#:~:text=If%20you%20find%20yourself%20wanting%20even%20more%20granularity%2C%20you%20can%20pass%20a%20predicate%20function%20to%20the) gets passed one of our keys you can get the constituent parts really easy! 

```ts
queryClient.invalidateQueries({
  predicate: query =>
    {
    const arrayPath = query.queryKey[0]
    const { input, type } = query.queryKey[1]
   // Input will be undefined if none, and type will be our union "query" | "infinite"

   // We could also export a little query key helper function to make this 
   // even easier and future proof regarding any other changes we make for developers 
   // that returns {arrayPath, input, type} given a tRPC React Query Key
   // const {arrayPath, input, type} = getTRPCArrayKeyParts(query.queryKey)  // Could include TSTypes

   //... code and conditions on if to invalidate!

    }    
})
```

I mean putting all of them in an object would be even neater but not sure our partial array path matching would work then as I've not dug that deep into the react query fuzzy matching implementation! 😂


Anyways I'll try and take a look the next few days (mostly tonight once I get a few other things out of the way!)

**Comment by TkDodo** [comment]
> Given key: [ ['post', 'byId'], { type: "query", input: 1 } ]

> invalidateQueries([ ['post', 'byId'], { input: 1 } ]) would invalidate that key even if we don't define the type?

That's exactly right. Objects have no order so the partial matching will work as you want to here. I'm going into details why the object is pretty good for query keys: https://tkdodo.eu/blog/leveraging-the-query-function-context
