### ISSUE TITLE
feat: Make client library not tied to browser

### ISSUE THREAD

**Issue by nahidakbar** [trpc/trpc#3134]
### Describe the feature you'd like to request

I wanted to use it for a project but does not look like it will be suitable.

I found the API definition side support amazing. I managed to define my types with zod schemas and managed to wire together an API in a very clean fashion in typescript. This is exactly what I wanted - define my types once and having all the work done for me.

When I tried to write a simple typescript client script to consume the API however, it didn't even compile and it was looking for predefined objects only available in the browser (e.g. fetch, WebSocket etc). I think we are assuming all consumers of the api will be web apps (maybe using nextjs or react or similar) - which I admit is the norm.

So this is not a bug report but rather a feature request. I would love to wire up systems with this wonderful tool the same way as it can use it to wire back end and front ends of a web service together.

I also thought it was a bit weird that the "client" side was importing the router definition that was importing the "@trpc/server" package.

### Describe the solution you'd like to see

Would like if there were separate libraries for a non-web trpc client vs web-trpc clients.

### Desribe alternate solutions

Also would like if we didn't have to include a @trpc/server package for client side definition. Maybe a @trpc/core that ships both with server and client? - just throwing ideas

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

**Comment by KATT** [comment]
Very similar to #2728.

I think this is a good idea!

There are workarounds already though, all you really need to do is to ponyfill or polyfill `fetch` when initializing the client.

Polyfill, this is the _easiest_ way: https://github.com/trpc/trpc/blob/731e35c7eef21a487359bec694e5f3936d6cb1a0/examples/standalone-server/src/client.ts#L14-L18

But you can also ponyfill by passing `fetch` to the `httpBatchLink` options etc

**Comment by KATT** [comment]
It's not tied to the browser & works well in nod, so closing this
