### ISSUE TITLE
feat: implement `useQueries`

### ISSUE THREAD

**Issue by JesusTheHun** [trpc/trpc#3136]
### Describe the feature you'd like to request

Create a wrapper for [useQueries](https://tanstack.com/query/v4/docs/reference/useQueries)

tRPC allows batching, it seem logical to fully benefit from that :)

### Describe the solution you'd like to see

```ts
trpc.useQueries((batchClient) => {
  someIds.forEach(id => batchClient.items.pick(id));
})
```

### Desribe alternate solutions

Right now I have to make my procedures accept arrays of id instead f enjoying batching.

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

**Comment by KATT** [comment]
Duplicate: #1454 

FWIW - I think this will be a lot easier/ or edundant soon™ with the [`use()`](https://github.com/reactjs/rfcs/pull/229)-hook.

It'll be something like `const myPosts = use(Promise.all([ postIds.map((id) => trpc.post.byId.fetch({ id })])`
