### ISSUE TITLE
bug: Unable to set TRPCError.cause

### ISSUE THREAD

**Issue by schmoli** [trpc/trpc#3139]
### Provide environment information

```
  System:
    OS: macOS 13.0
    CPU: (10) arm64 Apple M1 Max
    Memory: 560.63 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.1 - ~/.nvm/versions/node/v16.17.1/bin/node
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.1/bin/npm
  Browsers:
    Brave Browser: 106.1.44.101
    Chrome: 107.0.5304.87
    Safari: 16.1
  npmPackages:
    @trpc/server: 10.0.0-rc.6 => 10.0.0-rc.6 
```

### Describe the bug

In V9 I was able to use TRPCError.cause to send custom errors (for example, information on field names and messages for CONFLICTS in prisma during my mutations. V10 appears to not save the cause. Looking into the code briefly, it looks like it now needs the cause to be of type Error, as if you look at TRPCError.ts (V10) you'll see:
```typescript
    const cause: Error | undefined =
      opts !== undefined ? getErrorFromUnknown(opts.cause) : undefined;
```
and V9 shows: 
```typescript

TODO: 

```

### Link to reproduction

UNABLE

### To reproduce

Note, due to some crazy internet outage, I can't get a stackblitz but this is crazy easy to reproduce with node.js, but i'm seeing it in my Next.js project.
```
# package.json
{
  "name": "trpc-test",
  "version": "1.0.0",
  "description": "",
  "type": "module",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@trpc/server": "10.0.0-rc.6"
  }
}
```

Now, in index.js, with V9 I used a custom object to set Cause and it would work just fine.
In v10, it appears cause must extend Error but either of the `myError` objects below cause the issue
```
# index.js
import { TRPCError } from "@trpc/server";

// does not work in V9 or V10
/* const myError = new Error("pretend I have a custom error here"); */
// works only in V9
const myError = { message: "pretend I have a custom error here" };
const error = new TRPCError({
  code: "CONFLICT",
  cause: myError,
  originalError: myError,
});

console.log("error:\n", JSON.stringify(error, null, 2));
console.log("error.cause\n", JSON.stringify(error.cause, null, 2));
```

Output received in v9 with custom object:
```
error:
 {
  "originalError": {
    "message": "pretend I have a custom error here"
  },
  "code": "CONFLICT",
  "name": "TRPCError"
}
error.cause
 {
  "message": "pretend I have a custom error here"
}
```

Output received in V10 for both objects and v9 for the Error() object:
```
error:
 {
  "originalError": {},
  "code": "CONFLICT",
  "name": "TRPCError"
}
error.cause
 {}
```

Expected Result: the TRPC.cause object would be populated, be it with a custom object or only with an Error.

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

**Comment by sun0day** [comment]
`JSON.stringify` does not work on `Error` instance. `JSON.stringify(new Error)` always be `'{}'`
