### ISSUE TITLE
chore: get rid of `mergeRoutersGeneric`

### ISSUE THREAD

**Issue by sun0day** [trpc/trpc#3145]
### Area of Improvement

Since `t.router()._def.queries`'s type is always `{}`, `queries` infer type of `mergeRoutersGeneric`'s return_type is always `{}` in dynamic `packages/server/src/core/internals/__generated__/mergeRoutersGeneric.ts`. 

Maybe we can just use `Record<string, AnyQueryProcedure>` rather than `RP0['queries'] & RP1['queries'] & RP2['queries']` to reduce the size of `mergeRoutersGeneric.d.ts`. Same as `mutations` and `subscriptions`.

<img width="668" alt="image" src="https://user-images.githubusercontent.com/102238922/200790423-9e14db55-0574-4956-8440-d31c1d02f023.png">

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR implementing the suggested changes!

**Comment by sun0day** [comment]
> We can actually get rid of that whole generated file with a generic implementation. We used to have one but it required a higher version of TS than CodeSandbox/StackBlitz required at the time which broke all our demos

So what ts version do CodeSandbox/StackBlitz demos need now? Is it possible to upgrade?

**Comment by KATT** [comment]
The real solution is to get rid of the whole thing. 

https://github.com/trpc/trpc/blob/047d1c77b9f30b31d6487347fcd1289e6ec33e3d/packages/server/src/core/internals/mergeRoutersGeneric.ts

Here's an old implementation that can be revisited pretty easily I think

**Comment by sachinraja** [comment]
#3755
