### ISSUE TITLE
bug: `AppRouter` type has `errorShape: never`

### ISSUE THREAD

**Issue by huzaifahj** [trpc/trpc#3151]
### Provide environment information

  System:
    OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (6) x64 Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
    Memory: 11.11 GB / 15.59 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash

  Binaries:
    Node: 19.0.1 - /usr/bin/node
    npm: 8.19.2 - /usr/bin/npm

  npmPackages:
    @trpc/server: 10.0.0-rc.7 => 10.0.0-rc.7 
    typescript: 4.8.4 => 4.8.4 

### Describe the bug

I'm getting this error when using the client:

![image](https://user-images.githubusercontent.com/52999758/201058735-404787be-01d3-470c-a7b5-e7c52f549b0c.png)

```
Type 'RootConfig<{ ctx: Context; meta: { auth: "none" | "admin" | "user"; }; errorShape: never; transformer: CombinedDataTransformer; }>' is not assignable to type 'AnyRootConfig'.
        Type 'any' is not assignable to type 'never'.ts(2344)
```

I think it's caused by the `errorShape` being `never`. Not sure why it's doing that, as in the "minimal reproduction template" the `errorShape` is by default `DefaultErrorShape`.

Server initialisation:

![image](https://user-images.githubusercontent.com/52999758/201059258-f6cd9dc7-8019-42b2-957f-fc763a40a5e5.png)

### Link to reproduction

N/A

### To reproduce

I'm just using the default `initTRPC` function. Nothing else is affecting that function. If I do a simple

```
const t = initTRPC.create();
```

I still get `errorShape: never`

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

**Comment by KATT** [comment]
Send a repo where you reproduce this. It probably has something to do with your tsconfig.

**Comment by huzaifahj** [comment]
I have been able to reproduce the issue by setting `strict: false` in my `tsconfig.json`.

![image](https://user-images.githubusercontent.com/52999758/201284277-a397dd15-753b-41f0-b8dc-ecaa17abef92.png)

Repository: https://github.com/huzaifahj/examples-next-minimal-starter-strict-false

Do you know why this might be? Only seems to be an issue with `errorShape`

**Comment by KATT** [comment]
You have to use `strict: true`.

**Comment by KATT** [comment]
Feel free to reopen if you can repro with `strict: true`.

**Comment by huzaifahj** [comment]
> Feel free to reopen if you can repro with `strict: true`.

It should really say in the docs that you have to do that. Getting an opaque error like that will lead devs on a path to nowhere.
