### ISSUE TITLE
feat: add info about calls to `createContext()`-options

### ISSUE THREAD

**Issue by KATT** [trpc/trpc#3152]
### Describe the feature you'd like to request

Add more meta data about the request when creating context

### Describe the solution you'd like to see

```ts
export async function createContext(opts: trpcNext.CreateNextContextOptions) {
  console.log(opts.info)
  return {}
}
```

`opts.info` could be something like:

```ts
interface ProcedureCall {
  type: ProcedureType;
  input?: unknown;
  path: string;
}

interface TRPCRequestInfo {
  calls: ProcedureCall[];
}
```

### Desribe alternate solutions

n/a

### Additional information

This can be used to do stuff like rate limiting, preventing certain procedure types in some operations, etc

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

**Comment by Eduard-Hasa** [comment]
Would this be useful for situations like passing down env object to trpc route handlers in cloudflare workers?

Would be really nice.

**Comment by KATT** [comment]
I've never used CF workers so unsure if this helps, doesn't help, or if it is problematic today, but feel free to create a separate discussion about it :)
