### ISSUE TITLE
docs: pnpm test not picking up some code changes (Tubro)

### ISSUE THREAD

**Issue by JonParton** [trpc/trpc#3166]
### Provide environment information

```
  System:
    OS: Linux 5.10 Ubuntu 20.04.5 LTS (Focal Fossa)
    CPU: (12) x64 Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
    Memory: 21.65 GB / 31.23 GB
    Container: Yes
    Shell: 5.0.17 - /usr/bin/bash
  Binaries:
    Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.16.0 - ~/.nvm/versions/node/v16.15.0/bin/npm
  npmPackages:
    typescript: ^4.8.3 => 4.8.3 
```

### Describe the bug

I encountered an issue whilst creating #3165 that stumped me for quite a while where tests were failing that I had sworn my code changes had fixed ... Turned out Turbo was caching an old build of code and I had to do a `--force` on it to get the tests to run with my new changes ... Sounds like the dependencies of the test task in turbo are missing some files? 

Specifically my changes to `packages/react-query/src/shared/hooks/createHooksInternal.tsx` were not being picked up!

### Link to reproduction

-

### To reproduce

Run an `pnpm test` command , change some code in a trpc internal file (my issue was with `packages/react-query/src/shared/hooks/createHooksInternal.tsx`), run `pnpm test` again and old build may be used (in my case it was!)

### Additional information

Sorry I haven't got the energy to do any better repro this evening! (morning!) 💤🛌

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

**Comment by JonParton** [comment]
@juliusmarminge  --> Sorry to tag you but I reckon this may be your bag 🤔🙈

**Comment by juliusmarminge** [comment]
> @juliusmarminge  --> Sorry to tag you but I reckon this may be your bag 🤔🙈

Did you edit a type or "actual code"? I've had problems in the past that editing types doesn't trigger the dev server to rebuild.

Might be a missing output in the pipeline but don't think so. Unsure what else it might be.

**Comment by JonParton** [comment]
Was deffinitely  actual code, and I tried restarting the dev server a few times with no effect.

The only thing that fixed it was editing the `package.json` `test` command to have `--force` on the end!

**Comment by juliusmarminge** [comment]
> Was deffinitely  actual code, and I tried restarting the dev server a few times with no effect.
> 
> 
> 
> The only thing that fixed it was editing the `package.json` `test` command to have `--force` on the end! 

Were you running test or test-dev?

Maybe test-dev should depend on dev?

https://github.com/trpc/trpc/blob/c30951ae89e66884591f79a756838927f352ebde/turbo.json#L48

**Comment by JonParton** [comment]
Ah I was using `test` not `test-dev`!

Although we may need to update the [Contributing guidelines](https://github.com/trpc/trpc/blob/next/CONTRIBUTING.md#testing)  if that's what we are intended to use! 🙂

I did end up havign to go there this time developing too to realise I had to do a `build` before any of the references to server would work right too 😂 (entry point generation by looks!)

**Comment by juliusmarminge** [comment]
> Ah I was using `test` not `test-dev`!

Alright, I'll try and test it myself later today to see what's going on, both should of course work.

> Although we may need to update the [Contributing guidelines](https://github.com/trpc/trpc/blob/next/CONTRIBUTING.md#testing)  if that's what we are intended to use! 🙂

Yes can mention that there's a watch mode there. But it shouldn't matter which you use.

> I did end up havign to go there this time developing too to realise I had to do a `build` before any of the references to server would work right too 😂 (entry point generation by looks!)
> 
> That was another thing that sunk 30 minutes for me! 

Sorry about that one, I don't think there's a better way and keep the caching. Can try adding back build on post install and see if it still caches and all that.

**Comment by KATT** [comment]
Is this an issue? Maybe we just need to update the contribution docs to advise people to use `test-dev`?

**Comment by juliusmarminge** [comment]
> Is this an issue? Maybe we just need to update the contribution docs to advise people to use `test-dev`?

I haven't had an opportunity to verify/reproduce so can't say. You only use `test-dev` so you haven't run into this either?

**Comment by KATT** [comment]
Will close for now, we can improve docs though.
