### ISSUE TITLE
bug: `ReturnType` typing useQuery `data: unknown`

### ISSUE THREAD

**Issue by rag4214** [trpc/trpc#3176]
### Provide environment information

```
System:
    OS: Windows 10 10.0.22621
    CPU: (24) x64 AMD Ryzen 9 5900X 12-Core Processor
    Memory: 45.32 GB / 63.92 GB
Binaries:
    Node: 18.12.1 - C:\Program Files\nodejs\node.EXE
    npm: 9.1.1 - C:\Program Files\nodejs\npm.CMD
Browsers:
    Edge: Spartan (44.22621.819.0), Chromium (107.0.1418.42)
    Internet Explorer: 11.0.22621.1
npmPackages:
    @tanstack/react-query: 4.16.1 => 4.16.1
    @trpc/client: 10.0.0-rc.8 => 10.0.0-rc.8
    @trpc/next: 10.0.0-rc.8 => 10.0.0-rc.8
    @trpc/react-query: 10.0.0-rc.8 => 10.0.0-rc.8
    @trpc/server: 10.0.0-rc.8 => 10.0.0-rc.8
    next: 13.0.3 => 13.0.3
    react: 18.2.0 => 18.2.0
    typescript: 4.8.4 => 4.8.4
```

### Describe the bug

Trying to type a react context that uses the result of a `useQuery` call. Tried extracting just the `data` / `status` by doing
```ts
type Context = Pick<ReturnType<tyepof trpc.greeting.useQuery>, "data" | "status">;
```
but hovering using vscode / stackblitz gives me
```ts
type Context = {
  data: unknown;
  status: "error" | "success" | "loading";
}
```
when it should be
```ts
type Context = {
  data: { 
    text: string; 
  } | undefined;
  status: "error" | "success" | "loading";
}
```

### Link to reproduction

https://stackblitz.com/edit/github-qrenh4?file=src%2Fpages%2Findex.tsx

### To reproduce

Try and use `ReturnType` with trpc.

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

**Comment by rag4214** [comment]
I know [inferring types](https://trpc.io/docs/infer-types#inference-helpers) exists, but I'm trying to get the `useQuery` result with all the extra rq bits

**Comment by juliusmarminge** [comment]
> I know [inferring types](https://trpc.io/docs/infer-types#inference-helpers) exists, but I'm trying to get the `useQuery` return type with all the extra rq bits

Maybe use `UseQueryResult` from @tanstack directly?

**Comment by rag4214** [comment]
> > I know [inferring types](https://trpc.io/docs/infer-types#inference-helpers) exists, but I'm trying to get the `useQuery` return type with all the extra rq bits
> 
> Maybe use `UseQueryResult` from @TanStack directly?

The best "solution" I could find to this is something along the lines of 
```ts
export type AppRouter = typeof appRouter;
export type AppRouterOutputs = inferRouterOutputs<AppRouter>;

const appRouter = router({/* ... */});
```
```ts
type Context = Pick<
  UseQueryResult<AppRouterOutputs["greeting"], TRPCClientErrorLike<AppRouter["greeting"]>>, 
  "status" | "data"
>;
```
which is just...weird. I'm recreating the return type by hand. DRY and all that.

**Comment by KATT** [comment]
The reason is that `trpc.greeting.useQuery` takes a generic argument so you can't do that.

We should probably provide helpers for doing generic stuff around the `UseQueryResult`-stuff we have in tRPC, but hopefully, we can all start using Suspense soon and get rid of all that `UseQueryResult`-crap altogether 😅

Feel free to open an issue with what sort of helpers you want, but this is not a bug.
