### ISSUE TITLE
feat: add hyper-express adapter - performance boost

### ISSUE THREAD

**Issue by dougg0k** [trpc/trpc#3177]
### Describe the feature you'd like to request

the title 

https://github.com/kartikk221/hyper-express

https://github.com/kartikk221/hyper-express/blob/master/docs/Benchmarks.md

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

**Comment by KATT** [comment]
We won't add more adapters for the time being within core because it's a lot to maintain, but feel free to make a third party one and link it in awesome trpc
