### ISSUE TITLE
bug: head response to server not hits `responseMeta`

### ISSUE THREAD

**Issue by alex-misch** [trpc/trpc#3178]
### Provide environment information

System:
    OS: macOS 12.3.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 4.21 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.17.1 - ~/.nvm/versions/node/v16.17.1/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.1/bin/npm
    Watchman: 2022.09.26.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 107.0.5304.110
    Safari: 15.4
  npmPackages:
    @tanstack/react-query: ^4.3.8 => 4.16.1 
    @trpc/client: ^10.0.0-rc.7 => 10.0.0-rc.7 
    @trpc/next: ^10.0.0-rc.7 => 10.0.0-rc.7 
    @trpc/react-query: ^10.0.0-rc.7 => 10.0.0-rc.7 
    @trpc/server: ^10.0.0-rc.7 => 10.0.0-rc.7 
    next: 13.0.0 => 13.0.0 
    react: 18.2.0 => 18.2.0 

### Describe the bug

I'm trying fetch head of server and I get the response `HTTP/1.1 204 No Content` . But I configure response meta cors headers like this: 
```
import { createHTTPServer } from '@trpc/server/adapters/standalone';
import { appRouter } from '~/api-router';

// http server
const { server, listen } = createHTTPServer({
  router: appRouter,
  responseMeta: (opts) => {
    return {
      headers: {
        'Access-Control-Allow-Credentials': 'true',
        'Access-Control-Allow-Headers': '*',
        'Access-Control-Allow-Origin': '*',
        'Access-Control-Allow-Methods': '*',
      },
    };
  },
});
```

So I get CORS error in browser. I want to make separated server and client services. Imaging that client will be in `example.com` and my tRPC api will in `api.example.com`. I found some hardcoded point that handle it: 
https://github.com/trpc/trpc/blob/bba7d97ccf864517dc2455dcbd0e320df280215e/packages/server/src/http/resolveHTTPResponse.ts#L67

Is it a bug? How can I configure headers of head requests in standalone server?

### Link to reproduction

no need

### To reproduce

any head curl request to a server
```
curl -I "http://localhost:2022/greeting?batch=1&input=%7B%220%22%3A%7B%22name%22%3A%22123%22%7D%7D"
```

### 👨‍👧‍👦 Contributing

- [x] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

**Comment by KATT** [comment]
Wrap the response handler in something that can handle CORS
