### ISSUE TITLE
feat: support useQueries

### ISSUE THREAD

**Issue by TkDodo** [trpc/trpc#3188]
### Describe the feature you'd like to request

TanStack query supports running multiple queries in parallel via the `useQueries` hook, but this option is missing in trpc.

### Describe the solution you'd like to see

Add support for the `useQueries` hook. As discussed with Alex on Discord, the api could be something like:

```ts
trpc.useQueries(t => [
  t.post.byId({ 1 }, staleTime: Infinity)
  // ...
], { context: x })
```

```ts
trpc.useQueries(t => postIds.map(id => t.post.byId({ id }), { context: x })
```

### Desribe alternate solutions

If the `queryKey` and `queryFn` from trpc were exposed as a `raw` object (with queryKey and queryFn)

we could achieve this with `useQueries` from TanStack/query:

```ts
const utils = trpc.useContext()

useQueries({
  queries: [
    utils.todos.list.rawQuery(),
    utils.post.list.rawQuery(),
    utils.post.detail(5).rawQuery()
  ]
})
```

but it wouldn't be typesafe.

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

**Comment by siddhant1** [comment]
I can pick this up, is the API finalized?

**Comment by KATT** [comment]
Not finalized - we're open to suggestions, I think I like the callback approach best personally

Please make whatever you try can infer with both tuples `[Promise1, Promise2]` and arrays `Promise[]` correctly :).

Another API that I'd personally like would be sending an object struct with promises too , but that could be done later :) https://gist.github.com/KATT/e752815297db768e624f5eb838870dc7

**Comment by sachinraja** [comment]
hey @siddhant1 sorry, I should've assigned myself before but I'm going to take this issue as I think it's important to prioritize and has a fair amount of complexity involved.

**Comment by KATT** [comment]
@sachinraja if you don't end up working on it in the next week or so, please unassign yourslf :)
