### ISSUE TITLE
docs: recommended starter for next.js + react native should be create-t3-turbo

### ISSUE THREAD

**Issue by nexxeln** [trpc/trpc#3190]
### Area of Improvement

zART is no longer maintained and has been archived. [create-t3-turbo](https://github.com/t3-oss/create-t3-turbo) should be the recommended starting point for next.js + react native monorepos.

### Link to related docs

https://trpc.io/docs/awesome-trpc

### Additional information

Maybe create-t3-app should be a recommended starting point too instead of Extensions & community add-ons.

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR implementing the suggested changes!

**Comment by KATT** [comment]
agreed

**Comment by nexxeln** [comment]
> agreed

Will make a PR tomorrow!
