### ISSUE TITLE
bug: TRPCClientError is incorrectly formatted when using Zod validation methods.

### ISSUE THREAD

**Issue by VladislavSmolyanoy** [trpc/trpc#3193]
### Provide environment information

```
 System:
    OS: macOS 13.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 5.74 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.16.0 - /usr/local/bin/node
    npm: 8.11.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 107.0.5304.87
    Firefox: 106.0.2
    Safari: 16.2
    Safari Technology Preview: 16.4
  npmPackages:
    @tanstack/react-query: ^4.10.0 => 4.16.1 
    @trpc/client: 10.0.0-rc.4 => 10.0.0-rc.4 
    @trpc/next: 10.0.0-rc.4 => 10.0.0-rc.4 
    @trpc/react-query: 10.0.0-rc.4 => 10.0.0-rc.4 
    @trpc/server: 10.0.0-rc.4 => 10.0.0-rc.4 
    next: 13.0.2 => 13.0.2 
    react: 18.2.0 => 18.2.0 
    typescript: ^4.8.4 => 4.8.4 
```

### Describe the bug

When using Zod validations during a query or a mutation the returned TRPCClientError is not formatted correctly.
When trying to access the log message by writing error.message in query's onError it console-logs the whole object.

### Link to reproduction

https://stackblitz.com/edit/github-h5qcnm-dc9qyp?file=src/pages/api/trpc/[trpc].ts

### To reproduce

First let’s  take a look how a usual TRPClientError looks like.

in the query you can have something like `throw new TRPCClientError('ErrorMessage')`

This ErrorMessage is then accessible when you use onError like this: 
```
onError(error) {
            console.log(error.message)
},
```

This will print: `ErrorMessage`

Now let’s take a look at the errors thrown by the Zod validator. Here we have a Zod validator that only permits the string to be 1 character in length. If > 1 then it throws an error with the message "Must be 1 or fewer characters long"

```
export const userProfileRouter = router({
    get: publicProcedure
        .input(
              z.object({ 
                    userID: z.string().max(1, { message: "Must be 1 or fewer characters long" }) 
              })
        )
        .query(async ({ input, ctx }) => {
              return null;
        })
```

This should console-log `Must be 1 or fewer characters long` when accessing `error.message`, But it prints
```
[
  {
    "code": "too_big",
    "maximum": 1,
    "type": "string",
    "inclusive": true,
    "message": "Must be 1 or fewer characters long",
    "path": [
      "username"
    ]
  }
]
```

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

**Comment by Nsttt** [comment]
This happens to me as well locally.

**Comment by KATT** [comment]
This is what zod returns on the errors. See example here: https://stackblitz.com/edit/typescript-ysw11a?file=package.json,index.ts,tsconfig.json


If you want to format your zod errors nicer, see https://trpc.io/docs/error-formatting

**Comment by VladislavSmolyanoy** [comment]
The thing is, there is no type safe way to access the Zod Error message if a validation error occurs!

**Comment by VladislavSmolyanoy** [comment]
To anyone looking for a workaround because apparently this won’t be fixed...

The message in the errorFormatter received a weird string-ified json ZodError, but we can extract the error message (in this case only the first one):

```
const t = initTRPC.context<Context>().create({
    transformer: superjson,
    errorFormatter({ shape, error }) {
        return {
            ...shape,
            message:
                error.cause instanceof ZodError
                    ? JSON.parse(shape.message)[0].message
                    : shape.message,
            data: {
                ...shape.data,
                zodError:
                    error.code === 'BAD_REQUEST' &&
                    error.cause instanceof ZodError
                        ? error.cause.flatten()
                        : null,
            },
        }
    },
})
```

The important part here is `message: ...`
This goes in the `trpc.ts` file

**Comment by KATT** [comment]
- If you feel it's a bug within tRPC, feel free to open another issue
- If you feel it's missing docs, feel free to file a PR to improve docs
