### ISSUE TITLE
bug: `next-prisma-starter` includes `next-prisma-starter-websockets` code from scaffolded create next app template

### ISSUE THREAD

**Issue by nilskj** [trpc/trpc#3194]
Reproduce:
- `yarn create next-app --example https://github.com/trpc/trpc --example-path examples/next-prisma-starter trpc-starter`
- run `yarn`, `yarn dx`, then `yarn test`:

```bash
$ run-s test:*
$ vitest run

 RUN  v0.23.4 /Users/nilskjellman/Dev/trpc/trpc-10

 ✓ src/server/routers/post.test.ts (1)
 ❯ test/playwright.test.ts (0)

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Failed Suites 1 ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯

 FAIL  test/playwright.test.ts [ test/playwright.test.ts ]
Error: test/playwright.test.ts:3:28: test.setTimeout() can only be called from a test
 ❯ errorWithLocation node_modules/@playwright/test/lib/util.js:183:10
 ❯ TestTypeImpl._setTimeout node_modules/@playwright/test/lib/testType.js:176:54
 ❯ Function.setTimeout node_modules/@playwright/test/lib/transform.js:227:12
 ❯ test/playwright.test.ts:3:5
      1| import { test } from '@playwright/test';
      2|
      3| test.setTimeout(35e3);
       |     ^
      4|
      5| test('send message', async ({ browser, page }) => {



⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[1/1]⎯

Test Files  1 failed | 1 passed (2)
     Tests  1 passed (1)
  Start at  22:40:38
  Duration  1.60s (transform 510ms, setup 0ms, collect 122ms, tests 18ms)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "test:unit" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

When scaffolding the starter, I get two folders for playwright generated. `playwright` with some smoke tests and `test` containing a messaging test hooked up with next-auth:
<img width="914" alt="image" src="https://user-images.githubusercontent.com/495782/202804919-155c38bf-126b-460e-8c5e-04b9dbdd1c85.png">
That does not feel right!

**Comment by nilskj** [comment]
Does the example even use `next-auth`? It is not included as dep in `package.json` but the starter also generates an API path for it? 

<img width="1777" alt="image" src="https://user-images.githubusercontent.com/495782/202808034-e467710c-0703-4f04-b84f-f145b2815f86.png">

**Comment by nilskj** [comment]
So yes I think I have found the root cause!

The problem is in how create-next-app resolves the `--example` cli path. Apparently it kind of matches both examples and adds them together 😅 which is why we end up with files from the websocket example in the normal prisma one, and this one includes broken e2e tests obviously. 

If you try scaffold of my fork instead it actually works fine 🎉:
`yarn create next-app --example https://github.com/nilskj/trpc/tree/next/examples/next-prisma-starter trpc-fixed-starter`
I solved it by simply renaming the web socket example to avoid the name matching.

**Comment by juliusmarminge** [comment]
> The problem is in how create-next-app resolves the --example cli path. Apparently it kind of matches both examples and adds them together 😅 which is why we end up with files from the websocket example in the normal prisma one, and this one includes broken e2e tests obviously.

That's so stupid. Gonna check out next's cli and see what's up

**Comment by juliusmarminge** [comment]
Filed a PR to Next.js fixing the file matching

https://github.com/vercel/next.js/pull/43131
