### ISSUE TITLE
bug: not sure what happened, just broke all of a sudden

### ISSUE THREAD

**Issue by pencilcheck** [trpc/trpc#3202]
### Provide environment information

  System:
    OS: macOS 13.0
    CPU: (8) x64 Apple M1
    Memory: 16.57 MB / 16.00 GB
    Shell: 5.5.1 - /usr/local/bin/zsh
  Binaries:
    Node: 14.18.3 - ~/.nvm/versions/node/v14.18.3/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v14.18.3/bin/yarn
    npm: 8.13.1 - ~/.nvm/versions/node/v14.18.3/bin/npm
  Browsers:
    Brave Browser: 87.1.18.75
    Chrome: 107.0.5304.110
    Firefox: 105.0.3
    Firefox Developer Edition: 76.0
    Safari Technology Preview: 16.4

### Describe the bug

 ERROR  ERROR in client.ts:5:45                                        05:06:06
TS2344: Type 'Router<{ _config: RootConfig<{ ctx: any; meta: {}; errorShape: DefaultErrorShape; transformer: DefaultDataTransformer; }>; router: true; ... 5 more ...; isDev: boolean; }> & { ...; }' does not satisfy the constraint 'Router<AnyRouterDef<AnyRootConfig, any>>'.
  The types returned by 'createCaller(...)' are incompatible between these types.
    Type '{ query: inferHandlerFn<{}>; mutation: inferHandlerFn<{}>; subscription: inferHandlerFn<{}>; } & DecoratedProcedureRecord<{ exportReport: BuildProcedure<"query", { ...; }, { ...; }>; }>' is not assignable to type '{ query: inferHandlerFn<any>; mutation: inferHandlerFn<any>; subscription: inferHandlerFn<any>; } & DecoratedProcedureRecord<any>'.
      Type '{ query: inferHandlerFn<{}>; mutation: inferHandlerFn<{}>; subscription: inferHandlerFn<{}>; } & DecoratedProcedureRecord<{ exportReport: BuildProcedure<"query", { ...; }, { ...; }>; }>' is not assignable to type '{ query: inferHandlerFn<any>; mutation: inferHandlerFn<any>; subscription: inferHandlerFn<any>; }'.
        Types of property 'query' are incompatible.
          Type 'inferHandlerFn<{}>' is not assignable to type 'inferHandlerFn<any>'.
            Types of parameters 'path' and 'path' are incompatible.
              Type 'TPath' is not assignable to type 'never'.
                Type 'string' is not assignable to type 'never'.

### Link to reproduction

No link

### To reproduce

I don't know why it stopped working all of a sudden

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

**Comment by juliusmarminge** [comment]
Please run the `npx envinfo` command in your project root so we can see your dependency versions

**Comment by KATT** [comment]
Feel free to re-open with a reproduction.
