### ISSUE TITLE
feat: Create OSS package middleware (e.g. rate limit)

### ISSUE THREAD

**Issue by KATT** [trpc/trpc#3227]
### Describe the feature you'd like to request

Goal: showcase that it is possible to create middlewares as OSS-packages.

We could do something like https://github.com/express-rate-limit/express-rate-limit but for tRPC

### Describe the solution you'd like to see

Probably needs  #3152 before.

```ts
import { createTRPCRateLimit } from "@fantasy/trpc-rate-limit";
import {initTRPC} from "@trpc/server";

const root = initTRPC.create();

const {
  procedure
} = root;

const rateLimiter = createTRPCRateLimiter({
  root,
	windowMs: 15 * 60 * 1000, // 15 minutes
	max: 100, // Limit each IP to 100 requests per `window` (here, per 15 minutes)
	headers: true, // Return rate limit info in the `RateLimit-*` headers
});


export const rateLimitedProcedure = procedure
  .use(rateLimiter.middleware());
```

### Desribe alternate solutions

Alternative - do it in `createContext()`

```ts


/**
 * Inner function for `createContext` where we create the context.
 * This is useful for testing when we don't want to mock Next.js' request/response
 */
export async function createContextInner(_opts: CreateContextOptions) {
  return {};
}

export type Context = trpc.inferAsyncReturnType<typeof createContextInner>;

/**
 * Creates context for an incoming request
 * @link https://trpc.io/docs/context
 */
export async function createContext(
  opts: trpcNext.CreateNextContextOptions,
): Promise<Context> {
  // for API-response caching see https://trpc.io/docs/caching
  await rateLimiter.validate({
    info: opts.info,
  })

  return await createContextInner({});
}
```

### Additional information

-

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

**Comment by santosmarco-caribou** [comment]
I'm not being able to click on the `Yes, I'd be down to file a PR implementing this feature!` checkbox but I'd love to work on this.

**Comment by juliusmarminge** [comment]
I've started on this [here](https://github.com/juliusmarminge/trpc-tools/tree/main/packages/rate-limiter) but my time is limited right now so it's not a priority on my end.

**Comment by OrJDev** [comment]
i just took what @juliusmarminge and changed a few things to get it to work, seems to work fine. 
could be improved with the type safety, will keep you updated

<img width="1440" alt="Screenshot 2023-01-02 at 16 34 26" src="https://user-images.githubusercontent.com/91349014/210245372-18b21e67-95e2-44f7-92b7-1ef90a963ce3.png">
