### ISSUE TITLE
feat: Support edge-runtime on NextJS

### ISSUE THREAD

**Issue by aequasi** [trpc/trpc#3258]
### Describe the feature you'd like to request

 Support edge-runtime on NextJS:
https://nextjs.org/docs/api-reference/edge-runtime

### Describe the solution you'd like to see

Would love to see another handler for NextJS @ Edge that supports the different API endpoint requirements

### Desribe alternate solutions

I tried to look at using one of the other handlers, but it didn't seem like they worked

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

**Comment by KATT** [comment]
Think you can do this with the Fetch adapter

**Comment by KATT** [comment]
See #2697

I do think how to use Next.js edge runtime should be covered in our documentation though.
