### ISSUE TITLE
docs: add docs how to use Vercel's edge-runtime

### ISSUE THREAD

**Issue by KATT** [trpc/trpc#3259]
See #2697

I do think how to use Next.js edge runtime should be covered in our documentation though.

_Originally posted by @KATT in https://github.com/trpc/trpc/issues/3258#issuecomment-1327221207_

**Comment by QuiiBz** [comment]
Might be a good idea to add a more general documentation about how to use tRPC within **any** edge runtime following the [WinterCG](https://wintercg.org/) spec, instead of specifically Vercel's edge-runtime (Deno Deploy, CF Workers, Bun, Lagon...)

**Comment by JeanBaeez** [comment]
you guys need a general documentation or an specific documentation about the edge-runtime?
