### ISSUE TITLE
docs: @trpc/next

### ISSUE THREAD

**Issue by johnson-jesse** [trpc/trpc#3266]
### Area of Improvement

Update the `yarn` command to install @trpc/next which references the wrong @tanstack. See picture

<img width="855" alt="Screenshot 2022-11-25 at 6 57 02 PM" src="https://user-images.githubusercontent.com/10335064/204064082-47c96b07-3de8-47de-a212-8b6a814e5f0a.png">

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR implementing the suggested changes!

**Comment by QuiiBz** [comment]
This issue was already fixed in https://github.com/trpc/trpc/pull/3267
