### ISSUE TITLE
bug: TRPCClientError: Trying to deserialize unknown typed array

### ISSUE THREAD

**Issue by kstulgys** [trpc/trpc#3269]
### Provide environment information

```
  System:
    OS: macOS 13.0
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 2.50 GB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.16.0 - ~/.volta/tools/image/node/16.16.0/bin/node
    Yarn: 1.22.19 - ~/.volta/tools/image/yarn/1.22.19/bin/yarn
    npm: 8.12.2 - ~/.volta/tools/image/npm/8.12.2/bin/npm
  Browsers:
    Brave Browser: 107.1.45.118
    Chrome: 106.0.5249.119
    Chrome Canary: 109.0.5380.0
    Firefox: 103.0.1
    Safari: 16.1
  npmPackages:
    @tanstack/react-query: ^4.16.0 => 4.16.1 
    @trpc/client: ^10.0.0 => 10.1.0 
    @trpc/next: ^10.0.0 => 10.1.0 
    @trpc/react-query: ^10.0.0 => 10.1.0 
    @trpc/server: ^10.0.0 => 10.1.0 
    next: 13.0.2 => 13.0.2 
    react: 18.2.0 => 18.2.0 
    typescript: ^4.8.4 => 4.9.3 
```

### Describe the bug

Api endpoint/procedure should return buffer, but throws error `TRPCClientError: Trying to deserialize unknown typed array`

### Link to reproduction

https://stackblitz.com/edit/github-aqovgn?file=src/pages/index.tsx

### To reproduce

1. Run the example (stackblitz)
2. Click on `DOWNLOAD PDF` button
3. Check console

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

**Comment by KATT** [comment]
You can't return a Buffer. Or rather, you could potentially do it if you added support to superjson, but this is not an issue with tRPC.
