### ISSUE TITLE
feat: expose queryKey

### ISSUE THREAD

**Issue by TkDodo** [trpc/trpc#3295]
### Describe the feature you'd like to request

not all methods available on the `queryClient` are available on `useContext()` from trpc. While it might be desirable to add more methods to it (see: https://github.com/trpc/trpc/issues/3012), it doesn't have to be done for _all_ methods - only those that profit from type-safety.

There are a couple of methods exposed from TanStack/query that do not require additional typesafety, but would need access to the `queryKey`. For example:

- `queryClient.setQueryDefaults(key, defaults)`
- `queryClient.isFetching({ queryKey })`
  - or even `useIsFetching({ queryKey })`

additional type-safety is not needed because for the first example, `defaults` work the same for all keys, and for the second example, only a _number_ is returned.

It would be good if we could use these methods with queries created from trpc.

### Describe the solution you'd like to see

One way to achieve this is to expose the queryKey that was created internally, for example:

```ts
const queryClient = useQueryClient()
const utils = trpc.useContext()

const isFetching = useIsFetching(utils.post.byId.getQueryKey()) // QueryKey => [["post","byId"]]
queryClient.setQueryDefaults(utils.post.getQueryKey(), { staleTime: Infinity }) // QueryKey => [["post"]]
```

### Describe alternate solutions

we could expose _all_ methods via `trpc.useContext()`, but I think it's an uphill battle and not really needed. Some things (but not all of them) will be covered with:
- https://github.com/trpc/trpc/issues/3012

### Additional information

reference:
- https://github.com/trpc/trpc/issues/3012#issuecomment-1319653598

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

**Comment by KATT** [comment]
This makes sense to me

**Comment by juliusmarminge** [comment]
I'll take a stab at this tonight
