### ISSUE TITLE
bug: v9-v10 interop TS does not consider superjson's serialization when using v9 query in client

### ISSUE THREAD

**Issue by lakardion** [trpc/trpc#3303]
### Provide environment information

 System:
    OS: Linux 5.10 Ubuntu 20.04.4 LTS (Focal Fossa)
    CPU: (16) x64 AMD Ryzen 7 5800X 8-Core Processor
    Memory: 22.88 GB / 24.99 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 16.16.0 - ~/.local/state/fnm_multishells/51_1669587048149/bin/node
    Yarn: 1.22.19 - ~/.local/state/fnm_multishells/51_1669587048149/bin/yarn
    npm: 8.11.0 - ~/.local/state/fnm_multishells/51_1669587048149/bin/npm
  npmPackages:
    @tanstack/react-query: ^4.18.0 => 4.18.0
    @trpc/client: ^10.4.0 => 10.4.0
    @trpc/next: ^10.4.0 => 10.4.0
    @trpc/react-query: ^10.4.0 => 10.4.0
    @trpc/server: ^10.4.0 => 10.4.0
    next: 12.3.1 => 12.3.1
    react: 18.2.0 => 18.2.0
    typescript: 4.7.4 => 4.7.4

### Describe the bug

TS infers the wrong type on serializable fields on v9 queries.

IG: if a query returns a `Date`  field. A client call to `trpc.useQuery` for that query the corresponding field in `data` is inferred as string rather than Date.

### Link to reproduction

https://github.com/lakardion/trpc-v9-v10

### To reproduce

Check on https://github.com/lakardion/trpc-v9-v10/blob/642c9042e140cf6d2e769885680d13339c7bd2d7/src/pages/index.tsx#L21

`hello.myDate` should be of type `Date | undefined` instead, it is inferred as `string`.

If you run the project you can see that the serialization is actually occurring since the type of `hello.myDate` is object

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

**Comment by ludusrusso** [comment]
Hi @KATT, I'm having the same issue, but even if I update to the latest version of trpc (I've checked in the example repo) I still have type issue as described here.

Can you help mi understand what I'm missing?

**Comment by KATT** [comment]
Open a new issue with a reproduction. This issue is closed
