### ISSUE TITLE
feat: first class support for io-ts validators

### ISSUE THREAD

**Issue by Nsttt** [trpc/trpc#3306]
### Describe the feature you'd like to request

[io-ts](https://github.com/gcanti/io-ts) is a decoding/encoding library based on [fp-ts](https://github.com/gcanti/fp-ts) functional programming patterns.

Currently, the behaviour when using it with tRPC is a bit weird, it just doesn't work as it should, I believe it can be improved since I've seen a few issues already about this topic.

Its syntax is very similar to `Zod` but validators returns an `Either<Error, Data>`.

### Describe the solution you'd like to see

Currently. When using io-ts as a validator, it works like this.

```ts
import * as t from "io-ts";
import * as E from "fp-ts/Either";
import { pipe } from "fp-ts/function";

const exampleCodec = t.type({
  text: t.union([t.string, t.null]),
});

export const exampleRouter = router({
  hello: publicProcedure.input(exampleCodec.decode).query(({ input }) =>
    pipe(
      input,
      E.fold(
        (error) => {
          console.log(error);
        },
        (response) => {
          return { greeting: `Hello ${response.text ?? "world"}` };
        }
      )
    )
  ),
});

```

Here, we can see we pass the `decode` function to the input of the procedure and makes the `input` type `E.Left<t.Errors> | E.Right<{text: string | null}>`.
No problems here. This is 100% expected. Some minor improvements could be that if its an `E.Left` case, it fallback to a TRPC error.

The big issue comes when I want to use `useQuery()` on this procedure. Because the input it asks for is an `Either`. I would like to be able to pass the structure of the `E.Right` case. I can access that structure dynamically using `t.TypeOf<typeof exampleCodec>`

### Describe alternate solutions

If it seems too much effort, not do it.

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

**Comment by santosmarco-caribou** [comment]
Hey @Nsttt please take a look at this PR.

https://github.com/trpc/trpc/pull/3324

I got `io-ts` working for us. First-class type inference and parsing.

**Comment by lloydrichards** [comment]
It looks like it's a little hard to implement this directly into tRPC without the library depending on io-ts to unwrap the Either.  Your workaround is good, but I tidied it up a bit in this [comment](https://github.com/trpc/trpc/pull/3324#issuecomment-1422658244) and made it into a generic function that can take any io-ts Decoder and return the type for tRPC to infer:

```typescript
import * as t from "io-ts";
import * as E from "fp-ts/Either";
import * as A from "fp-ts/Array";
import { identity, pipe } from "fp-ts/lib/function";
import { failure } from "io-ts/lib/PathReporter";

/**
 * This is a helper function to make the error messages from io-ts
 * more readable.
 *
 * It takes the error object from io-ts and returns a string with
 * the first 3 errors.
 */
export const prettyError = (err: t.Errors) =>
  pipe(
    err,
    failure,
    A.takeLeft(3),
    (a) => a.map((s) => "- " + s),
    (a) => a.join("\n")
  );

/**
 * This is a helper function to make it easier to use io-ts
 * with trpc.
 *
 * It takes an io-ts decoder and returns a function that
 * takes a value and returns the decoded value or throws
 * an error if the value is invalid.
 */
export const ioParser =
  <T>(schema: t.Decoder<unknown, T>) =>
  (value: unknown) => {
    return pipe(
      schema.decode(value),
      E.fold((err) => {
        throw new Error(prettyError(err));
      }, identity)
    );
  };

```

**Comment by KATT** [comment]
Cleaning up and closing, feel free to re-open or submit a PR if it's still wanted.
