### ISSUE TITLE
bug: mergeRouters dosen't allow Duplicate key

### ISSUE THREAD

**Issue by matannahmani** [trpc/trpc#3310]
### Provide environment information

`  System:
    OS: Linux 5.11 Ubuntu 21.04 (Hirsute Hippo)
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
    Memory: 1.82 GB / 15.32 GB
    Container: Yes
    Shell: 5.1.4 - /bin/bash
  Binaries:
    Node: 16.17.0 - ~/.n/bin/node
    Yarn: 1.22.17 - /usr/bin/yarn
    npm: 8.15.0 - ~/.n/bin/npm
  Browsers:
    Chrome: 107.0.5304.87
    Firefox: 96.0
  npmPackages:
    @tanstack/react-query: ^4.16.1 => 4.16.1 
    @trpc/client: latest => 10.1.0 
    @trpc/next: latest => 10.1.0 
    @trpc/react-query: latest => 10.1.0 
    @trpc/server: latest => 10.1.0 
    next: 12.2.5 => 12.2.5 
    react: ^18.2.0 => 18.2.0 
    typescript: ^4.5.2 => 4.9.3 `

### Describe the bug

Merging two routers with the same base key result in an Error that prevents TRPC from starting.

### Link to reproduction

https://stackblitz.com/edit/github-s7sq9z?file=src/pages/api/trpc/[trpc].ts

### To reproduce

```
const buildingQueries = router({
  accounts: router({
    all: publicProcedure.query(async () => []),
  }),
  houses: router({
    all: publicProcedure.query(async () => []),
  }),
});

const buildingMutations = router({
  accounts: router({
    one: publicProcedure.mutation(async () => []),
  }),
  houses: router({
    one: publicProcedure.mutation(async () => []),
  }),
});

const buildingRouter = router({
  building: mergeRouters(buildingQueries, buildingMutations),
});
```

### Additional information

Expected to get a merged router with mutation and queries.
**building.accounts.all.useQuery**
**building.accounts.one.useMutation**
### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

**Comment by matannahmani** [comment]
I did some digging around and found the problem under **mergeWithoutOverrides**. I guess this only checks for keys instead of the shape of the key (for example, query/router).
I expected this to work as a deep merger, that will check recursively if there is no collusion in the key.

**Comment by KATT** [comment]
This is expected behaviour as TypeScript gets impossibly slow when merging like that. 


Separate your code on feature or domain rather than what operation it is, that'll make your codebase more scalable too.
