### ISSUE TITLE
bug: Expo + trpc: Uncaught Error: No QueryClient set, use QueryClientProvider to set one

### ISSUE THREAD

**Issue by dezerb** [trpc/trpc#3316]
### Provide environment information

  System:
    OS: macOS 13.0
    CPU: (10) arm64 Apple M1 Max
    Memory: 4.32 GB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.18.1 - ~/.nvm/versions/node/v16.18.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.18.1/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v16.18.1/bin/npm
    Watchman: 2022.11.14.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 108.0.5359.71
    Firefox: 107.0
    Safari: 16.1
  npmPackages:
    @tanstack/react-query: ^4.18.0 => 4.18.0 
    @trpc/client: ^10.4.1 => 10.4.1 
    @trpc/react-query: ^10.4.1 => 10.4.1 
    @trpc/server: ^10.4.1 => 10.4.1 
    next: ^13.0.4 => 13.0.5 
    react: 18.1.0 => 18.1.0 
    typescript: ^4.6.3 => 4.9.3 

### Describe the bug

So is my app.tsx

```
export default function App() {
  return (
    <AuthenticationProvider>
      <TRPCProvider>
        <ThemeProvider theme={theme}>
          <NavigationContainer>
            <Stack.Navigator>
              <Stack.Screen name="Criteria" component={MovieSearchComponent}/>
              <Stack.Screen name="Results" component={ResultsComponent}/>
            </Stack.Navigator>
          </NavigationContainer>
        </ThemeProvider>
      </TRPCProvider>
    </AuthenticationProvider>
  );
}
```
my component

```
import { trpc } from "../../utils/trpc-client";

export function ResultsComponent({navigation, route}) {

  const {data} = trpc.moviesRecommendation.useQuery(
     {
      runtimeMinsMin: 100
    }
  )
```
trpc-client.ts

```
import { AppRouter } from "../server/trpc";
import { createTRPCReact, httpLink } from "@trpc/react-query";

export const trpc = createTRPCReact<AppRouter>()

export const trpcClient = trpc.createClient({
  links: [httpLink({url: 'http://localhost:3000/api/trpc'})],
})
```
and trpc-provider.ts

```
export function TRPCProvider({children}: PropsWithChildren) {
  const [queryClient] = useState(() => new QueryClient())

  return (
    <trpc.Provider client={trpcClient} queryClient={queryClient}>
      <QueryClientProvider client={queryClient} contextSharing={true}>
        {children}
      </QueryClientProvider>
    </trpc.Provider>
  )
}
```
So is the web error while using useQuery:
```

Uncaught Error: No QueryClient set, use QueryClientProvider to set one
    at Object.useQueryClient (QueryClientProvider.tsx:48:1)
    at Object.useBaseQuery (useBaseQuery.ts:33:1)
    at useQuery (useQuery.ts:139:1)
    at Object.useQuery$1 [as useQuery] (createHooksInternal-808efaa7.mjs:277:1)
    at createHooksInternal-808efaa7.mjs:52:1
    at Object.apply (index-972002da.mjs:18:1)
    at ResultsComponent (results-component.tsx:11:1)
    at renderWithHooks (react-dom.development.js:16175:1)
    at mountIndeterminateComponent (react-dom.development.js:20913:1)
    at beginWork (react-dom.development.js:22416:1)
```

**Comment by KATT** [comment]
Maybe delete `contextSharing`.

99% confident this is not a bug in tRPC.

**Comment by dezerb** [comment]
@KATT without contextSharing the same problem occurs.

**Comment by dezerb** [comment]
@KATT  Could it be the wrong babel/webpack configuration? 

`const createExpoWebpackConfigAsync = require('@expo/webpack-config');
const path = require('path')

module.exports = async function(env, argv) {
    const config = await createExpoWebpackConfigAsync(env, argv);
    config.module.rules.forEach(r => {
        if (r.oneOf) {
            r.oneOf.forEach(o => {
                if (o.use && o.use.loader && o.use.loader.includes('babel-loader')) {
                    o.include = [
                        path.resolve('.'),
                        path.resolve('node_modules/@trpc/*'),
                    ]
                }
            })
        }
    })
    config.module.rules.push({
        test: /\.mjs$/,
        include: /node_modules/,
        type: "javascript/auto"
    });

    return config;
};
`

`// @generated: @expo/next-adapter@4.0.13
// Learn more: https://github.com/expo/expo/blob/master/docs/pages/versions/unversioned/guides/using-nextjs.md#shared-steps

module.exports = {
    presets: [
        '@expo/next-adapter/babel',
    ],
    plugins: [
        '@babel/plugin-proposal-export-namespace-from',
        'react-native-reanimated/plugin',
        ["@babel/plugin-proposal-private-methods", { "loose": true }]
    ]
};
`

**Comment by KATT** [comment]
My guess is that you're not actually wrapping your app with `TRPCProvider`. I'd cross-reference with @juliusmarminge's https://github.com/t3-oss/create-t3-turbo

**Comment by juliusmarminge** [comment]
Try registering the root like this maybe, instead of default exporting the app

https://github.com/t3-oss/create-t3-turbo/blob/main/apps/expo/index.ts

**Comment by dezerb** [comment]
@juliusmarminge I changed 
app.tsx to 

```
export const App = () => {
  return (
    <AuthenticationProvider>
      <TRPCProvider>
        <ThemeProvider theme={theme}>
          <NavigationContainer>
            <Tab.Navigator>
              <Tab.Screen name="Home" component={MoviesMainComponent}/>
              <Tab.Screen name="Settings" component={ProfileMainComponent}/>
            </Tab.Navigator>
          </NavigationContainer>
        </ThemeProvider>
      </TRPCProvider>
    </AuthenticationProvider>
  );
}

```

and index.js 

```
import {registerRootComponent} from 'expo';

import {App} from './App';

registerRootComponent(App);
```

but it still doesn't work. The courios thing is that iOS build is working fine but not web configuration.

**Comment by dezerb** [comment]
@juliusmarminge @KATT 
I found the solution. I created the context on myself

```
export const context = React.createContext<QueryClient | undefined>(
  undefined,
);
```

and then it was used to create trpc client

`export const trpc = createTRPCReact<AppRouter>({reactQueryContext: context})`

and  provider

```
    <trpc.Provider client={trpcClient} queryClient={queryClient}>
      <QueryClientProvider client={queryClient} context={context}>
        {children}
      </QueryClientProvider>
    </trpc.Provider>
```

The question is, why have I to do it?
