### ISSUE TITLE
feat: Query and Mutation at the same level

### ISSUE THREAD

**Issue by Ayterx** [trpc/trpc#3319]
### Describe the feature you'd like to request

a feature where you define Query and Mutation in the same procedure path

this might benefit reducing the paths you'll have to create E.g. profile.view, profile.update

```ts
const appRouter = server.router({
  profile: server.router({
    view: ...,
    update: ...
  })
})
```

### Describe the solution you'd like to see

```ts 
// server
const profileRouter = server.procedure
  .mutation(z.object({ ... }), async ({ ctx, input }) => {
    // update profile
  })
  .query(z.object({ ... }), async ({ ctx, input }) => {
    // find profile
  })

// client
const query = trpc.profile.useQuery({...}, {...})
const mutation = trpc.profile.useMutation({...})
```

### Describe alternate solutions

```ts
const appRouter = server.router({
  profile: server.procedure
    .mutation({
      meta: {}, // idk about this
      input: z.object({ ... }),
      resolve: async ({ ctx, input }) => {
        // update profile
      }
    })
    .query({
      meta: {}, // idk about this
      input: z.object({ ... }),
      resolve: async ({ ctx, input }) => {
        // find profile
      }
    })
})
  ```

### Additional information

I don't know if the implementation behind this or if this doesn't follow the standards of RPCs or if this is possible without changing many things.
just an Idea I thought I could share.

maybe v11 🤷‍♂️

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

**Comment by KATT** [comment]
- We don't accept mutations and queries to be on the same path
- We won't add chaining on a router level as it doesn't scale (TS perf gets bad, v9 had that issue)
- We won't add an alternative API at the moment, see https://github.com/trpc/trpc/issues/2975#issuecomment-1276302563
