### ISSUE TITLE
feat: Improve context docs

### ISSUE THREAD

**Issue by KATT** [trpc/trpc#3329]
### Describe the feature you'd like to request

Improve https://trpc.io/docs/context

### Describe the solution you'd like to see

- Describe how to use context, including how to write it up with the API handler which is missing right now
- Describe why you might need an "inner" and an "outer" context and infer the `Context`-type from the _inner_ one (#3325)

### Describe alternate solutions

n/a

### Additional information

> this question made a good point that the docs currently don't seem to have a section on how to set up routing and context in /pages/api in next.js. seems like it would be difficult to figure the setup out without ct3a or some other template. i could try to write something on the weekend.
https://discord.com/channels/867764511159091230/1047290845700821083https://discord.com/channels/867764511159091230/1047290845700821083

by @c-ehrlich 

https://github.com/trpc/trpc/pull/3325

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

**Comment by c-ehrlich** [comment]
Will open PR for this either tonight or tomorrow depending on how I feel about what I've written :)

**Comment by KATT** [comment]
Feel free to ask for feedback too! :)

**Comment by bennettdams** [comment]
Damn, I already started working on the docs after our [chat in the PR](https://github.com/trpc/trpc/pull/3325).

Is that okay for you, @c-ehrlich?
