### ISSUE TITLE
bug: SSR mode has stopped working in built Next.js app

### ISSUE THREAD

**Issue by austins** [trpc/trpc#3334]
### Provide environment information

```
  System:
    OS: Windows 10 10.0.22000
    CPU: (24) x64 AMD Ryzen 9 3900X 12-Core Processor
    Memory: 4.89 GB / 15.93 GB
  Binaries:
    Node: 19.2.0 - ~\scoop\apps\nodejs\current\node.EXE
    npm: 8.19.3 - ~\scoop\apps\nodejs\current\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (107.0.1418.62)
    Internet Explorer: 11.0.22000.120
  npmPackages:
    @tanstack/react-query: ^4.19.0 => 4.19.0
    @trpc/client: ^10.4.3 => 10.4.3
    @trpc/next: ^10.4.3 => 10.4.3
    @trpc/react-query: ^10.4.3 => 10.4.3
    @trpc/server: ^10.4.3 => 10.4.3
    next: 13.0.6 => 13.0.6
    react: 18.2.0 => 18.2.0
    typescript: ^4.9.3 => 4.9.3
```

### Describe the bug

With `ssr: true`, Next.js and React Query renders the tRPC query with SSR prepass as expected in **dev mode**.

However, after building the app using `npm run build` and then `npm run start`, it doesn't render the page with an SSR prepass. The initial load still shows the "Loading..." message / has no data.

`refetchOnWindowFocus` works still, so the issue is with the initial SSR prepass on a built Next.js app.

### Link to reproduction

https://github.com/austins/trpc-nextjs-ssr_not_working_in_build-repro

### To reproduce

1. Have `ssr: true`
2. Build Next.js app
3. Run built Next.js app
4. See that it doesn't load the initial data via SSR prepass

### 👨‍👧‍👦 Contributing

- [x] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

**Comment by austins** [comment]
Also occurs with Node 18.12.1 LTS.

**Comment by KATT** [comment]
My guess would be something changed within Next

**Comment by austins** [comment]
I've downgraded to next@12.3.0 and it still reproduces there, unless it started happening in an earlier version. I'll investigate further.

**Comment by austins** [comment]
I've added the loggerLink and there is an error in the prod build:
```
 << query #1 hello {
  input: { text: 'client' },
  result: TRPCClientError: fetch failed
      at TRPCClientError.from (file:///C:/trpc-nextjs-ssr_not_working_in_build-repro/node_modules/@trpc/client/dist/transformResult-4e0db787.mjs:13:16)
      at file:///C:/trpc-nextjs-ssr_not_working_in_build-repro/node_modules/@trpc/client/dist/links/httpBatchLink.mjs:200:64
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
    meta: undefined,
    shape: undefined,
    data: undefined,
    [cause]: TypeError: fetch failed
        at Object.fetch (node:internal/deps/undici/undici:11118:11)
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
      cause: [Error]
    }
  },
  elapsedMs: 25,
  context: {}
}
```

**Comment by austins** [comment]
The workaround for this bug is to set the base URL to `127.0.0.1` instead of `localhost`:

```js
function getBaseUrl() {
  if (typeof window !== "undefined")
    // browser should use relative path
    return "";
  if (process.env.VERCEL_URL)
    // reference for vercel.com
    return `https://${process.env.VERCEL_URL}`;
  if (process.env.RENDER_INTERNAL_HOSTNAME)
    // reference for render.com
    return `http://${process.env.RENDER_INTERNAL_HOSTNAME}:${process.env.PORT}`;
  // assume localhost
  return `http://127.0.0.1:${process.env.PORT ?? 3000}`;
}
```

It seems to be related to: [https://github.com/nodejs/undici/issues/1602](https://github.com/nodejs/undici/issues/1602), which I found via [https://stackoverflow.com/a/73634311](https://stackoverflow.com/a/73634311).

**Comment by austins** [comment]
The above workaround only works if Next.js is binded to 0.0.0.0 (by default) or 127.0.0.1 (i.e. `next dev --hostname localhost` or `next start --hostname localhost`). A thing to note is that the standalone mode for Next.js build explicitly sets the hostname to `localhost`.

So the better workaround would be to put this on top of the `server/trpc.ts` file:
```js
import dns from "node:dns";
dns.setDefaultResultOrder("ipv4first");
```

**Comment by austins** [comment]
Closing as this isn't a tRPC issue, but an issue with Node.
