### ISSUE TITLE
feat: Align createCaller with createTRPCProxyClient

### ISSUE THREAD

**Issue by lunaris** [trpc/trpc#3335]
### Describe the feature you'd like to request

`createCaller` lets us get a "client" that we can use to invoke a router implementation directly (in memory). `createTRPCProxyClient` lets us get a "true" client that we can use to invoke a router using actual remote calls. Currently, the types of objects returned by these functions are different, meaning that it's not possible to use a common interface to abstract over whether or not a call is in-memory or over the wire. Specifically, proxy methods must be called with `.query()` or `.mutate()` chains, while caller methods can be executed directly.

Having a common interface would be useful when e.g. building a monolith that will later be decomposed, or decomposing an existing monolith in which tRPC is being used to systematically wrap existing components. As an example, suppose an order service depends on a payment service:

```typescript
function createPaymentsRouter() {
  return t.router({
    takePayment: t.procedure.mutation(() => ...),
  })
}

function createOrdersRouter(paymentsService) {
  return t.router({
    createOrder: t.procedure.mutation(() => ... paymentsService.takePayment.mutate(...) ...)
  })
}
```

It'd be nice if we could pass either `paymentsRouter.createCaller({})` or `createTRPCProxyClient<typeof paymentsRouter>({ links: ... })` to `createOrdersRouter`, depending on whether we are composing into a monolith or a set of discrete services. Currently this isn't possible since if we pass a caller, `.mutate()` doesn't exist, and if we pass a proxy, `takePayment` is not itself callable. Hopefully this makes sense, and thanks for the amazing library!

### Describe the solution you'd like to see

I can think of a few possible solutions, but each has its drawbacks and all may be unsuitable given my ignorance of tRPC's internals:

1. Have `createCaller` return an object whose methods must be chained with `.query` and `.mutate`. `createCaller`'s return type now aligns with that of `createTRPCProxyClient`. This would be a breaking change as it would change the interface of `createCaller` in a non-backwards-compatible manner.
2. Have `createTRPCProxyClient` return an object whose methods are directly callable. I'm sure there's a good reason that proxies have `.query` and `.mutate` chain finalisers, so this is probably untenable, but if it's e.g. just cosmetic then we could look at making the properties directly callable, rather than having `.query` or `.mutate` child properties. Moreover, we could offer both interfaces (so that e.g. `.takePayment` is a `Function` with an additional `.mutate` property that calls the same code), which would be backwards compatible (I think).
3. Create a new version of `createCaller` or `createProxyTRPCClient` (or both) with compatible types.
4. Create a new type of `link` that makes an in-memory call, so that `createTRPCProxyClient` subsumes `createCaller`'s functionality.

### Describe alternate solutions

(See above)

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

**Comment by sachinraja** [comment]
I think #4 is the best option here. You can see this for an implementation of that:
https://github.com/exhibitionist-digital/ultra/blob/8e60f8ad3d59e89dbea8e33309c54d5800332efe/examples/with-trpc/src/trpc/server.tsx#L10

**Comment by nick-lehmann** [comment]
@sachinraja The link to an issue/PR that you provided is very likely broken. Would you be so kind to fix the link? 🤔

**Comment by sachinraja** [comment]
We won't align these two APIs (at least for now). I recommend using the `procedureLink` I linked above if you really want this.
