### ISSUE TITLE
feat: nuxt3 adapter

### ISSUE THREAD

**Issue by Feelixe-tin** [trpc/trpc#3346]
### Describe the feature you'd like to request

An official server adapter for [nuxt3](https://nuxt.com/modules).
There's a separate package that does the job, [trpc-nuxt](https://github.com/wobsoriano/trpc-nuxt).
But there are some drawbacks when using that.

### Describe the solution you'd like to see

An adapter similar to the one for next.js but for nuxt. It would use [unjs/h3](https://github.com/unjs/h3) to handle the incoming request.

### Describe alternate solutions

Keep the separate package 

### Additional information

I have started working on what is described above. But I'm having some issues with running the build and debugging. It would be great if someone else would like this feature and could offer some help.

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

**Comment by sachinraja** [comment]
We won't support this officially and no one in the core team uses Nuxt.

> But there are some drawbacks when using that.

What are the drawbacks?
