### ISSUE TITLE
ci fails due to prisma versions

### ISSUE THREAD

**Issue by juliusmarminge** [trpc/trpc#3348]
### Provide environment information

https://github.com/trpc/trpc/actions/runs/3628704483/jobs/6120121615

### Describe the bug

lint is failing due to missmatched prisma versions somewhere

### Link to reproduction

-

### To reproduce

Not sure, very flaky... Encountered this yesterday too and just restarted the job and it worked. Seems to have been the case here to (see consecutive run https://github.com/trpc/trpc/actions/runs/3628704483/jobs/6120274839)

### Additional information

cc @sachinraja is it cause of the deduping you think?

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

**Comment by KATT** [comment]
Weird. manypkg should make sure there's aligned versions everywhere

**Comment by sachinraja** [comment]
I think it's actually because it's out of memory. That's why we limited the postinstall scripts to 3 at once (`--child-concurrency=3`). Might need to be lower though.
