### ISSUE TITLE
feat: Expose DecoratedProcedureRecord and DecoratedProcedureUtilsRecord (rather than just @internal)

### ISSUE THREAD

**Issue by SamuelMS** [trpc/trpc#3356]
### Describe the feature you'd like to request

`DecoratedProcedureRecord` and `DecoratedProcedureUtilsRecord` are incredibly useful for building applications with dynamic scaffolding – i.e. an admin panel that introspects its database models (or in this case, its generated prisma types) and automatically builds forms, navigation, and links procedures for loading + saving data.

They're flagged as `@internal`, however, so our projects risk breakage by using them.

### Describe the solution you'd like to see

We propose removing the `@internal` comment to `DecoratedProcedureRecord` and `DecoratedProcedureUtilsRecord` to indicate they are stable & safe to use.

Example:

```typescript
// helpers to access procedures & context
type RouterProcedure = DecoratedProcedureRecord<AppRouter['_def']['record'], null>[Lowercase<Model>];
type RouterContext<T extends Model> = DecoratedProcedureUtilsRecord<AppRouter>[Lowercase<T>];

type AdminDetailViewProps<T extends Model> = {
  id?: string | NewModel;
  model: T;
  // context for updating local state on change (i.e. maps to `trpc.useContext`)
  onChange: RouterContext<T>['getOne']['setData'];
  // procedures for creating, updating, and removing supported content (i.e. maps to the trpc client)
  createItem: RouterProcedure['create']['useMutation'];     
  updateItem: RouterProcedure['update']['useMutation'];
  removeItem: RouterProcedure['remove']['useMutation'];
  // ...
}
```

By using these types, we get type-safety in our components – we can't accidentally pass in form data that doesn't align with the `model` or procedures. Usage example:

```typescript
<AdminDetailView
  id={id}
  model={Model.Question}
  onChange={utils.question.getOne.setData}
  createItem={trpc.question.create.useMutation}
  updateItem={trpc.question.update.useMutation}
  removeItem={trpc.question.remove.useMutation}
/>
```

One last note: `DecoratedProcedureUtilsRecord` works just fine when `RouterContext` is generic – we can pass in `T` and still have `onChange` work as expected – but for some reason, `DecoratedProcedureRecord` throws a type error in `createItem`, `updateItem`, and `removeItem` when `RouterProcedure` is made generic.

> TS2536: Type '"create"' cannot be used to index type 'RouterProcedure '.
> TS2536: Type '"useMutation"' cannot be used to index type 'RouterProcedure ["create"]'.

I'd guess it's just an implementation detail, but it would be nothing short of _amazing_ if we could get generic lookups on `DecoratedProcedureRecord` to work, because it'd add type safety to a few of our other routes (anything that changes data). For example:

```typescript
type RouterProcedure<T> = DecoratedProcedureRecord<AppRouter['_def']['record']>[Lowercase<T>];

type AdminDetailViewProps<T extends Model> = {
  createItem: RouterProcedure<T>['create']['useMutation'];
  //  ...
}
```

### Describe alternate solutions

We looked through the trpc typings and these seemed the best candidates for accomplishing our goal, but we're very open to using other constructs if there are already other helpers that are part of the public API.

### Additional information

* [DecoratedProcedureRecord source](https://github.com/trpc/trpc/blob/5b282f90fb664de1dd8d6efcc1f3036ffe62c1a2/packages/react-query/src/createTRPCReact.tsx#L160)
* [DecoratedProcedureUtilsRecord source](https://github.com/trpc/trpc/blob/a50be628854da18a8e857ac350b08f8110709501/packages/react-query/src/shared/proxy/utilsProxy.ts#L182)

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

**Comment by sachinraja** [comment]
Thanks for the detailed proposal! I'm struggling to understand the use case though. Why pass the `useMutation` as a prop instead of just doing `trpc.question.create.useMutation()` inside `AdminDetailView`?

**Comment by SamuelMS** [comment]
Hey @sachinraja, thanks for the follow-up! The idea is that each page in the admin panel offers the same set of core functionality – i.e. you need to be able to show some form data, create new records, update existing ones, delete old ones, and so on – and so can re-use a lot of the underlying framework. The intent is to eventually build generators for the tRPC routes as well, but that's still pretty far off in the future.

At any rate, by making `AdminDetailView` generic with `<T extends Model>`, we can re-use a single component for any number of "models" (i.e. `User`, `Company`, and more interesting app-specific things) – and the type inference flows through, meaning we get automatic validation and type inference for our forms and procedures.

A lot of this is inspired by the Django admin panel – [see this (unaffiliated) screenshot](https://django-jazzmin.readthedocs.io/img/detail_view.png) for an example.

```typescript
<AdminDetailView
      id={id}
      label={data?.name}
      isLoading={advertisementLoading || sponsorsLoading}
      model={Model.Advertisement}
      form={form}
      onChange={utils.advertisement.getOne.setData}
      createItem={trpc.advertisement.create.useMutation}
      updateItem={trpc.advertisement.update.useMutation}
      removeItem={trpc.advertisement.remove.useMutation}
    />
```

The above code can be re-used on any number of pages or even inline as necessary throughout the app, and gives us some really powerful benefits like adding validation between the `model` and `onChange` props. If `model` is set to `Model.Advertisement`, and I instead use `utils.sponsor.getOne.setData` (which is the _wrong_ procedure for the `Sponsor` router, not `Advertisement`), TypeScript throws a very helpful error:

```
Type 'Advertisement & { questions: Question[]; sponsor: Sponsor; }' is not assignable to type 'Sponsor & { advertisements: Advertisement[]; }'.
Type 'Advertisement & { questions: Question[]; sponsor: Sponsor; }' is missing the following properties from type 'Sponsor': logo, banner, active
```

This works because we defined a type helper called `RouterContext` that accepts `Model` as a generic:

```typescript
export type RouterContext<T extends Model> = DecoratedProcedureUtilsRecord<AppRouter>[Lowercase<T>];
```

As a result, this lets us reference the procedures on any given router and make sure the types align. So, by passing `Model.Advertisement` in the `model` prop, `RouterContext` will look up the `advertisement` router, find the `getOne` procedure, and check the tRPC context object to see what the `setData` method accepts – and throw a type error because it's pretty significantly different from the `utils.sponsor.getOne` procedure that we tried to pass in accepts. This is only possible because we use `DecoratedProcedureUtilsRecord`, which is currently marked as `@internal`.

We also do the same thing for the procedures themselves (rather than just context) for `createItem`, `updateItem`, and `removeItem` – but haven't been able to make this fully generic because something about how `DecoratedProcedureRecord` (also `@internal`) is implemented prevents generic lookups.

```typescript
export type RouterProcedure = DecoratedProcedureRecord<AppRouter['_def']['record'], null>[Lowercase<Model>];
```

>TS2536: Type '"create"' cannot be used to index type 'RouterProcedure '.
>TS2536: Type '"useMutation"' cannot be used to index type 'RouterProcedure ["create"]'.

**Comment by juliusmarminge** [comment]
You can pass the procedure instead of the useMutation using the `DecorateProcedure` type:

![CleanShot 2022-12-18 at 22 38 03](https://user-images.githubusercontent.com/51714798/208320888-d6ccfe6a-7928-4654-8f5f-0ea3bb9b4140.png)

**Comment by sachinraja** [comment]
I believe our (relatively) new polymorphism types can also help with this. See [docs](https://trpc.io/docs/server/infer-types#infer-react-query-options-based-on-your-router) (the second code block). Also see [types](https://github.com/trpc/trpc/tree/main/packages/react-query/src/shared/polymorphism) (specifically, [`MutationLike`](https://github.com/trpc/trpc/blob/3dbba4f95692209f94490ad953d807faa88c41d1/packages/react-query/src/shared/polymorphism/mutationLike.ts#L11))
