### ISSUE TITLE
docs: Basic Next.js example throws error

### ISSUE THREAD

**Issue by kevinmamaqi** [trpc/trpc#3358]
### Area of Improvement

The quick setup for Next.js throws an error as ssr is set to true.

```
TRPCClientError: request to https://http//localhost:3000/api/trpc/hello?batch=1&input=%7B%220%22%3A%7B%22json%22%3A%7B%22text%22%3A%22client%22%7D%7D%7D failed, reason: getaddrinfo ENOTFOUND http
    at Function.from (.../node_modules/@trpc/client/dist/transformResult-4e0db787.mjs:13:16)
    at .../node_modules/@trpc/client/dist/links/httpBatchLink.mjs:200:64
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  meta: undefined,
  shape: undefined,
  data: undefined
}
```

I am not using anything but the example in a new Nextjs project.

Related: https://github.com/trpc/trpc/issues/596

### Link to related docs

https://trpc.io/docs/nextjs

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing the suggested changes!

**Comment by sachinraja** [comment]
See https://github.com/nodejs/node/issues/40702

**Comment by austins** [comment]
Related: #3334
