### ISSUE TITLE
feat: open graph images for articles & blog posts

### ISSUE THREAD

**Issue by KATT** [trpc/trpc#3364]
### Describe the feature you'd like to request

Having open graph images for our posts would be nice. Ideally automatic, should be doable? 

### Describe the solution you'd like to  

~~Something like this would be nice https://github.com/vercel/og-image~~

This would be nicer: https://vercel.com/docs/concepts/functions/edge-functions/og-image-generation

### Additional information

https://github.com/trpc/trpc-assets

### 👨‍👧‍👦 Contributing

- [x] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

**Comment by harshsinghatz** [comment]
@KATT Can you describe this a bit more? or if you might have any design for this?

**Comment by KATT** [comment]
Anything that looks good with the colors / assets we have ☺

@jlalmes might be able to link some figma files of the og image we have now? 👀

**Comment by iway1** [comment]
@KATT I'd love to do this! 

Were you thinking having the same OG image show for every post or do something fancy like generate a new OG based on the first image in the post or something?
