### ISSUE TITLE
feat: support axios or a generic format in Links (useful for JWT)

### ISSUE THREAD

**Issue by kaminskypavel** [trpc/trpc#3384]
### Describe the feature you'd like to request

refactoring an authentication code relying on auto-refreshing JWT tokens which were based on axios, 
I was looking for a way to implement it with tRPC. 

pasting my solution for those who'll struggle in the future.

```
const BackendHttpLink = httpLink({
  url: backendTRPCUrl(),

  // the only reason it works, is since we rely on react-query to retry 3 time
  // by default, so it will fail on the first time -> fetch the access token ->
  // store it -> retry the request with the new token

  fetch: async (url, options): Promise<Response> => {
    const res = await fetch(url, options);

    if (res.status === 401) {
      const refreshResponse = await fetch(
        `${backendAPIUrl()}/settings/accessToken`
      );
      const { data } = await refreshResponse.json();
      store.accessToken = data.accessToken;
      console.log("refreshing token ", { data });
    }

    return res;
  },

  headers: () => {
    return {
      "x-access-token": store.accessToken,
    };
  },
});
```

## why is this suboptimal 1?

coming form Axios, it has interceptors, which makes it super easy to handle such situations 

```
settingsAxios.interceptors.request.use(async (config) => {
    const jwt = store.accessToken;
    if (!jwt) {

     // do the magic!

    }

}
```

but since HttpLink relies on fetch I cannot reuse Axios and had to reimplement the code
>    if (res.status === 401)  

## why is this suboptimal 2?

as i mentioned earlier, since the accessToken is manually fetched there's no option to replay the http call,
so I'm heavily relying on react-query to keep retrying it one more time, which is a fragile solution.

### Describe the solution you'd like to see

I don't fully understand the relationship between the `fetch` method in Links and the rest of tRPC , but maybe it can be formalized so we can return an Axios result?

### Describe alternate solutions

yes, mentioned earlier

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

**Comment by KATT** [comment]
You can/should do a link before the ending link that does this logic instead, see https://github.com/trpc/trpc/tree/main/packages/client/src/links for inspo, the `retryLink` is probably the best to look at (we don't export that currently, we just added it for our own testing of the link architecture). 

Maybe it could be an idea to make sure the `retryLink` can support this use-case and [export it](https://github.com/trpc/trpc/blob/87024b2012a5cbcf593850d0323fb273a408ac46/packages/client/src/links/index.ts#L8-L10).

**Comment by KATT** [comment]
Would probably be easy to let that retryLink accept an async(?) callback to "ask" if it should be retried where you could 

1. Check that it was an auth issue 
2. Do the auth call

**Comment by KATT** [comment]
We can prefix it as `unstable_` and get it out pretty quickly if you also wanna do it + docs + tests

**Comment by kaminskypavel** [comment]
IMHO, implementing another Link architecture is an overkill since the httpLink is just enough, especially when it has a `fetch` function that can be overwritten.

I think if you point me to the right direction it is easier to implement it with Axios and let it handle the whole mechanism

**Comment by KATT** [comment]
This is exactly what links are for, they are very flexible ways of controlling the data flow between the client & the server.

I know they look intimidating at first, but they're actually quite straight-forward, have a read through https://trpc.io/docs/links

**Comment by kaminskypavel** [comment]
Okay will take a look at these $observables 😅

**Comment by KATT** [comment]
Add a question to discussions or help channel or discord if you need help!
