### ISSUE TITLE
feat: minimal bun example

### ISSUE THREAD

**Issue by KATT** [trpc/trpc#3385]
### Describe the feature you'd like to request

tRPC should work with [Bun](https://bun.sh/), seeing that we don't have any deps on node

### Describe the solution you'd like to see

An example in the [`/examples`](https://github.com/trpc/trpc/tree/main/examples)-folder using Bun similar to our deno example

### Describe alternate solutions

If it doesn't work, it'd be good with issues on what is not working

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

**Comment by sachinraja** [comment]
you can use https://github.com/sachinraja/trpc-bun as a reference

**Comment by nfabredev** [comment]
Happy to take a look at that! Before i start, anything that comes to your mind that would be different from the implementation in the [linked repo](https://github.com/sachinraja/trpc-bun) ?

**Comment by gabriiels** [comment]
Can trpc be used with bun?
