### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by engelkes-finstreet** [trpc/trpc#3386]
### Provide environment information

```
  System:
    OS: macOS 12.6
    CPU: (10) x64 Apple M1 Max
    Memory: 95.50 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.19.3 - ~/.nvm/versions/node/v14.19.3/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 6.14.17 - ~/.nvm/versions/node/v14.19.3/bin/npm
  Browsers:
    Chrome: 108.0.5359.98
    Safari: 16.0
  npmPackages:
    @tanstack/react-query: ^4.16.0 => 4.19.1 
    @trpc/client: ^10.0.0 => 10.5.0 
    @trpc/next: ^10.0.0 => 10.5.0 
    @trpc/react-query: ^10.0.0 => 10.5.0 
    @trpc/server: ^10.0.0 => 10.5.0 
    next: 13.0.2 => 13.0.2 
    react: 18.2.0 => 18.2.0 
    typescript: ^4.8.4 => 4.9.4 

```

### Describe the bug

I want to use a "suspended" query in combination with `next-auth`. 

For this I created a `protectedProcedure` like this:

```ts
const isAuthed = t.middleware(({ ctx, next }) => {
  if (!ctx.session || !ctx.session.user) {
    throw new TRPCError({ code: "UNAUTHORIZED" });
  }
  return next({
    ctx: {
      // infers the `session` as non-nullable
      session: { ...ctx.session, user: ctx.session.user },
    },
  });
});

export const protectedProcedure = t.procedure.use(isAuthed);
```

and am using it in my router:

```ts
getSecretMessage: protectedProcedure.query(() => {
    return "you can now see this secret message!";
}),
```

My expectation would be that this query gets authorized even with `{suspense: true}` which is unfortunately not the case. 
Using it without suspense returns the correct data and I have a session in in my context.

```ts
const { data: secretMessage } = trpc.auth.getSecretMessage.useQuery(
    undefined, // no input
  );
```

As soon as I add the `suspense` flag it is not working anymore and the session is always null which results in an unauthorized error

```ts
const { data: secretMessage } = trpc.auth.getSecretMessage.useQuery(
      undefined, // no input
      {suspense: true}
  );
```
It is the same behaviour with `useSuspenseQuery`.

### Link to reproduction

https://github.com/engelkes-finstreet/next-auth-trpc-suspense

### To reproduce

Unfortunately I could not get the example running on Stackblitz / Codesandbox so I hope a link to my GitHub-Repository is enough as well.

Check out the repository and add any provider inside `pages/api/auth/[...nextauth].ts` and add these credentials to a `.env` file. You can copy the `.env.example` for it. Afterwards run `npx prisma migrate dev` and start the dev server with `npm run dev`. 
On the index page is a `sign in` button which you can click and sign in with your given provider. After the redirect back to the index page try to refresh the page and you will see that the authorization error occurs. 
Now you can go ahead and remove the `{ suspense: true }` from the query and refresh the page. Now you will see the secret message.

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

**Comment by KATT** [comment]
There's very very little chance this has anything to do with trpc, I don't have time to debug your project.

Likely it something sent differently in the two requests (headers perhaps?) and that when you're suspending it never reaches the thing that makes headers differently b/c the error propagates to an error boundary further up

**Comment by engelkes-finstreet** [comment]
Totally understandable that you do not have the time to debug this.
Do you maybe have some pointers where to look into?

While debugging I found out that I am hitting the `isAuthed` and there the session is missing on the `ctx` object but in my [...nextauth].ts file in my `session`-Callback there I have a valid session.

Not too sure where to look next, or maybe someone has an example repository where he is using trpc + nextauth + suspense.

**Comment by engelkes-finstreet** [comment]
Okay, nvm... 
After restarting my MacBook a third time it is working now. Thanks for your help!
