### ISSUE TITLE
feat: lower compile targets for browser-facing packages

### ISSUE THREAD

**Issue by KATT** [trpc/trpc#3393]
### Describe the feature you'd like to request

Currently, we don't do any transpilation outside of what's in tsconfig, which leads to limited browser support, even in compiled output for i.e. Next.js apps. If you search your compiled `_app.js`-bundle, it has a lot of optional chaining which all browsers doesn't support.

### Describe the solution you'd like to see

Either use babel or update tsconfig for browser-facing packages (`@trpc/react-query`, `@trpc/client`) to support older browsers.

The minimum requirement for tRPC is for the browser to support `Proxy`, so we should compile just after that.

### Describe alternate solutions

Unsure, maybe a guide how to transpile code for older browsers?

### Additional information

- In v9, we had babel: https://github.com/trpc/trpc/blob/v9.x/packages/client/package.json#L34
- Unlikely to add extra payload as the likelihood of another dep needing babel is also high.
- TanStack babel config: https://github.com/TanStack/query/blob/main/babel.config.js

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

<sub>[TRP-38](https://linear.app/trpc/issue/TRP-38/feat-lower-compile-targets-for-browser-facing-packages)</sub>

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/3393">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/3393/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/3393/pledge.svg">
</picture>
</a>

**Comment by iway1** [comment]
Probably worth mentioning that `@tanstack/core` may no longer transpile optional chaining in v5 to reduce bundle size https://github.com/TanStack/query/discussions/4252. Not sure what the plans our for react query v5 support down the road, but just something I thought of when reading this

**Comment by JoshuaKGoldberg** [comment]
What is the desired browser support range? Going back older that optional chaining is pretty far back.

> it has a lot of optional chaining which all browsers doesn't support.

Per https://caniuse.com/mdn-javascript_operators_optional_chaining, optional chaining is supported by: 
* Chrome 80 (released February 4, 2020)
* Edge 80 (released February 6, 2020)
* Safari 13.1 (released March 23, 2020)
* Firefox 74 (released March 9, 2020)

**Comment by KATT** [comment]
Is <2 years considered far nowadays? Maybe we're good then. I guess people who want to support older stuff can do their own webpack magic
