### ISSUE TITLE
docs: Home page scroll is laggy

### ISSUE THREAD

**Issue by ArnaudBarre** [trpc/trpc#3400]
### Area of Improvement

When you scroll, you feel it's not smooth (even with an high end laptop)

The scroll inside the inline editor is fine tough.

### Link to related docs

https://trpc.io/

### Additional information

Chrome, Mac Book Pro Intel

Other pages are fine

Lot of things to do, but can work on a fix in a few weeks if nobody found the issue :) 

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing the suggested changes!

**Comment by KATT** [comment]
What browser / OS?

**Comment by ArnaudBarre** [comment]
Chrome, macOS 12.6

**Comment by juliusmarminge** [comment]
Uploading CleanShot 2022-12-16 at 13.43.46.mp4…


Chrome, macOS 13.1 seems fine

**Comment by KATT** [comment]
Yeah I can't reproduce either and this feels like a wild goose chase
