### ISSUE TITLE
bug: useInfiniteQuery output type being replaced with `any`

### ISSUE THREAD

**Issue by givensuman** [trpc/trpc#3428]
### Provide environment information

```
  System:
    OS: Windows 10 10.0.19044
    CPU: (12) x64 AMD Ryzen 5 1600 Six-Core Processor
    Memory: 8.31 GB / 15.93 GB
  Binaries:
    Node: 16.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.15.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (108.0.1462.54)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @tanstack/react-query: ^4.16.0 => 4.19.1
    @trpc/client: ^10.0.0 => 10.4.3
    @trpc/next: ^10.0.0 => 10.4.3
    @trpc/react-query: ^10.0.0 => 10.4.3
    @trpc/server: ^10.0.0 => 10.4.3
    next: 13.0.2 => 13.0.2
    react: 18.2.0 => 18.2.0
    typescript: ^4.8.4 => 4.9.3
```

### Describe the bug

When creating a procedure capable of infinite querying, the type of the output appears to be ignored client-side and be replaced with `InfiniteData<any>`, even when explicitly described with the `.output()` method.

### Link to reproduction

https://stackblitz.com/edit/trpc-trpc-yu32lg?file=src/pages/index.tsx

### To reproduce

I built a quick infinite querying application to show this in the above StackBlitz link. In `src/pages/api/trpc/[trpc].ts` you can see the procedure named "characters" which has an explicit output described with Zod. Hovering over `data` in the return statement confirms this.

However, when querying this procedure in `src/pages/index.tsx`, the `data` value returned is typed as `InfiniteData<any> | undefined`. This breaks the typing in the component's return map function, with the warning `Parameter 'item' implicitly has an 'any' type.`

### Additional information

If I'm overlooking something please let me know.

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

**Comment by juliusmarminge** [comment]
Can confirm, tried some stuff to get it working but seems to be any no matter what I do...

Also tried without output parser and just parse it inside but still getting back any. Latest version and all...

![CleanShot 2022-12-19 at 13 23 38](https://user-images.githubusercontent.com/51714798/208425508-a85eb9f6-7e3f-4a31-82ba-eae2c656b8b0.png)

I don't use infiniteQuery much though so maybe @KATT has some idea what might be wrong here?

**Comment by juliusmarminge** [comment]
Oh hold on I found it...

It's cause you type the lastPage param as `any`:

![CleanShot 2022-12-19 at 13 27 19](https://user-images.githubusercontent.com/51714798/208426057-dc6662ba-39ee-4e0a-a4b7-c283d4bfdb8c.png)

If you just let trpc infer that seems to work properly on my end on latest version - both with and without output parser

**Comment by KATT** [comment]
Fixed it: https://stackblitz.com/edit/trpc-trpc-edernv?file=src%2Fpages%2Fapi%2Ftrpc%2F[trpc].ts,src%2Fpages%2Findex.tsx

- You didn't parse the data from the API
- You added `lastPage: any` which somehow messes up the types too

**Comment by givensuman** [comment]
Hmm I see why I did that. The [docs](https://trpc.io/docs/useInfiniteQuery) say

>  Your procedure needs to accept a `cursor` input of `any` type

and while I see now `lastPage` isn't a reference to the cursor, maybe the markdown code syntax around "any" is confusing when `any` is itself a type that breaks everything.

**Comment by juliusmarminge** [comment]
> Hmm I see why I did that. The [docs](https://trpc.io/docs/useInfiniteQuery) say
> 
> > Your procedure needs to accept a `cursor` input of `any` type
> 
> and while I see now `lastPage` isn't a reference to the cursor, maybe the markdown code syntax around "any" is confusing when `any` is itself a type that breaks everything.

I can see how that's confusing. Rephrased in #3440
