### ISSUE TITLE
feat: FIlter returned value of Query / Mutation using the output schema

### ISSUE THREAD

**Issue by arshia-gh** [trpc/trpc#3439]
### Describe the feature you'd like to request

Hi, wanted to know if it'd be possible to transform the output of a mutation or query using the output schema provided. Currently tRPC uses the output schema to only validate the output, but could it also be used to pick / omit keys?

This can be used to possibly hide unnecessary / protected information from the frontend like password, column ids from the database without the need of filtering the keys one by one.

### Describe the solution you'd like to see

```typescript
export const userRouter = router({
	getUser: publicProcedure
		.input(z.object({
			name: z.string(),
		}))
		// this schema is used to filter the returned value of the mutation / query
		.output(z.object({
			name: z.string(),
			email: z.string(),
			score: z.number(),
		}))
		// return value of schema should at least contain the output schema shape (or more)
		// it will be filtered using the output schema
		.query(async ({ input, ctx: { prisma } }) => {
			// user can contain more fields than the output schema like password, etc.
			return prisma.user.findUnique({
				where: {
					name: input.name,
				}
			});
		}),
});
```

### Describe alternate solutions

Currently, I can filter the keys using the Prisma `select` field

```typescript
return prisma.user.findUnique({
	where: {
		name: input.name,
	},
	select: {
		name: true,
		email: true,
		score: true,
	}
});
```

But as the user document / table grows and more fields become available I have to manually add these fields in the output schema and the select field

Although,  a utility function can be used to convert these keys to an object that can be used to filter the query.

```typescript
export const getSelectFromObjectSchema = <SchemaType extends z.ZodRawShape>(schema: z.ZodObject<SchemaType>) => {
	const select = {} as { [key in keyof SchemaType]: true };
	for (const key in schema.shape) {
		select[key] = true;
	}

	return select;
};
```

But in cases that I need these protected fields in my query, I have to manually filter them before returning the result

```typescript
return {
	// ... some other code
	user: lodash.pick(user, ['name', 'email', 'score']),
};
```

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

**Comment by arshia-gh** [comment]
Another way to address to issue is to enable middleware to be used as post processing hooks, like:
```typescript
.query(async ({ input, ctx: { prisma } }) => {
	// user can contain more fields than the output schema like password, etc.
	return prisma.user.findUnique({
		where: {
			name: input.name,
		}
	})
})
.use(middlware(() => { filtering happens here })
```

**Comment by KATT** [comment]
Hmmmm... I thought it already did work like that 🤔

**Comment by KATT** [comment]
You should be able to use e.g `z.object({}).transform()`, can't you? Does that not satisfy your usecase?

**Comment by KATT** [comment]
@arshia-gh let me know soon, will close it otherwise since we have the functionality

**Comment by arshia-gh** [comment]
@KATT Yes works as expected. I was receiving a type error due to inconsistencies in my schema, and I assumed trpc expects me to return the same type as the output schema. Sorry for the inconvenience
