### ISSUE TITLE
bug: codesandbox repro example not working

### ISSUE THREAD

**Issue by juliusmarminge** [trpc/trpc#3441]
### Provide environment information

https://stackblitz.com/github/trpc/examples-next-minimal-starter

Chrome: 108.0.5359.124
Firefox: 107.0.1

### Describe the bug

Currently, the stackblitz project doesn't start due to some swc error

<img width="702" alt="CleanShot 2022-12-20 at 09 55 21@2x" src="https://user-images.githubusercontent.com/51714798/208625352-c316db4f-3776-4654-9de1-47087a8e10f5.png">

### Link to reproduction

https://stackblitz.com/github/trpc/examples-next-minimal-starter

### To reproduce

Go to link, check console

### Additional information

Solutions:

- Move to CodeSandbox? Slow

- Look into error and figuring out what's causing it

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

**Comment by KATT** [comment]
Ummm... it has definitely worked before, seems like a StackBlitz issue?

**Comment by juliusmarminge** [comment]
> Ummm... it has definitely worked before, seems like a StackBlitz issue?

Maybe so, provide a CodeSandbox link for now?

**Comment by KATT** [comment]
🤷 

I mainly care about showing the DX for the frontpage

**Comment by juliusmarminge** [comment]
Working now. Thinking that it might be cause of the WASM build of SWC that got introduced lately:

![CleanShot 2023-01-26 at 18 11 18@2x](https://user-images.githubusercontent.com/51714798/214902827-2995e00c-71f4-4406-81b2-bec258d782a5.png)
