### ISSUE TITLE
bug: Badly formatted response/Unable to transform data from server errors in TRPC client

### ISSUE THREAD

**Issue by jacksonludwig** [trpc/trpc#3443]
### Provide environment information

```
  System:
    OS: macOS 12.6
    CPU: (8) arm64 Apple M1 Pro
    Memory: 167.42 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.17.0/bin/yarn
    npm: 9.2.0 - ~/.nvm/versions/node/v16.17.0/bin/npm
  Browsers:
    Brave Browser: 108.1.46.134
    Safari: 16.0
```

### Describe the bug

I have discussed the issue a bit here: https://github.com/trpc/trpc/discussions/3437

I am using expo react native frontend and aws-lambda backend with adapter.

In my experience, I am receiving `Badly formatted Response from Server` errors occasionally when using the TRPC client.

Furthermore, I noticed that when hitting at least **two** different endpoints in one component (e.g. two different `useQuery` calls), the frequency at which this error occurs is almost 100%.

I have verified that the data from the server is actually correct by hitting the endpoint without trpc.

### Link to reproduction

https://github.com/jacksonludwig/trpc-repro

### To reproduce

The reproduction is a bare bones CDK app using TRPC's lambda adapter, so unfortunately you need an AWS account setup to test it unless you can figure out how to run it locally.

0. run `git clone https://github.com/jacksonludwig/trpc-repro.git`
1. run `npm i` in server and `npm i --legacy-peer-deps` in client.
2. run `npx cdk deploy --all --require-approval never` in server
3. replace the api endpoint in `App.tsx` with endpoint of the restapi server output
4. run `npm start` in the client
5. open the app with a simulator or real device by scanning the QR code with the expo go app
6. examine some requests fail with `Badly formatted Response from Server` or `Could not transform Response from server`

### Additional information

The error in the repro is `Unable to transform data from server` instead of `Badly formatted response from server` as in my original discussion. I'm not sure why this is, but it looks similar enough that I would assume the cause is the same.

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

**Comment by KATT** [comment]
What does the api response look like when you encounter this? Are they always legit?

**Comment by jacksonludwig** [comment]
I believe so, but when the client error occurs prevents me from printing out anything about the payload on the client side.

I'm pretty positive the api response is fine though, as when I hit the same endpoint with only one `useQuery` call, there is no issue. When I add the second is when the errors occur.

And there are never any errors when hitting the endpoint without trpc.

**Comment by jludwiggreenaction** [comment]
@KATT I have to make a correction actually. I noticed when the error occurs, the client does not receive a response from the server. Basically AWS does not show the endpoint being hit at all.

**Comment by jacksonludwig** [comment]
@KATT I have to make a correction actually. I noticed when the error occurs, the client does not receive a response from the server. Basically AWS does not show the endpoint being hit at all.

**Comment by jacksonludwig** [comment]
Alright it seems the problem occurs only when batching is enabled. Setting `enabled = false` on the server side and using the `httpLink` over `httpBatchLink` on the client fixes the problem.

Is this user error? I can't tell if this is because I need to explicitly handle batched requests in my lambdas or if the client is sending malformed requests since I am not seeing any logs on the server.

**Comment by KATT** [comment]
This seems like an infra problem. Batching should still work with lambdas. It's fine to have 1 big endpoint even if you do lambdas, you can choose to split it up with something in a SOA-way ([example](https://github.com/trpc/trpc/tree/main/examples/soa)) if it ever ends up being a problem. GraphQL is 1 endpoint and works fine in lambdas as a ref

Could it be something like that the previous request is still processing which make the following one fail? Does it fail to automatically enqueue or spin up a new lambda to handle the next one?

Tried running the example but I guess I have to setup some aws-stuff too which I don't feel like doing right now.

**Comment by jacksonludwig** [comment]
It's not a queuing issue, lambda can handle much more extreme loads than just two requests in quick succession.

The problem is that for routing with lambda API it is most common to use `API Gateway`. I think that in order for it to work in the SOA-way as you mentioned, TRPC needs to handle the routing.

Basically TRPC is trying to trigger **two**  different handlers, but that requires triggering two lambda functions. I don't think that is a feasible thing.

**Comment by KATT** [comment]
I don't know why you need to hit two event handlers? Seems unnecessary

Anyway, I have no means/time to debug this, I need a repro without the AWS-stuff that shows it's an actual problem within tRPC and not an infra-problem

**Comment by jacksonludwig** [comment]
I now do not think it is TRPC's issue. It is just that batching does not make sense when creating an API using multiple lambdas on API gateway.

Thanks for your help, I think this issue can be closed in that case.

For the record, this is the sort of architecture that I am trying to achieve but that I think does not allow batching (unless I am misunderstanding how it works).

![image](https://user-images.githubusercontent.com/42984254/209014652-66718aac-bfb3-4cc5-81a5-cecfbc141497.png)

**Comment by KATT** [comment]
My advice would be to do single endpoint with batching until you hit any actual problems with that setup.

The overall load will be smaller since you only need to resolve context etc once per batch and you can do smart optimizations with deduping db queries and doing dataloaders in your backend.

If you ever hit problems with this, you can split up *services* within their own API endpoints, there's little/no actual value of doing this on a per procedure basis. You'll have more cold starts and heavier load on your DB (which usually is the real bottleneck) and additionally it's more work for the infra to be glued together.

Less is more.
