### ISSUE TITLE
bug: tRPC react query/mutation doesn't re-throw errors as reactQuery does

### ISSUE THREAD

**Issue by stychu** [trpc/trpc#3447]
### Provide environment information

```
System:
    OS: macOS 11.7
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 347.80 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.18.1 - ~/.nvm/versions/node/v14.18.1/bin/node
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.1/bin/npm
  Browsers:
    Brave Browser: 108.1.46.138
    Chrome: 108.0.5359.124
    Firefox: 108.0.1
    Safari: 15.6.1
  npmPackages:
    @tanstack/react-query: 4.19.1 => 4.19.1 
    @trpc/client: 10.5.0 => 10.5.0 
    @trpc/react-query: 10.5.0 => 10.5.0 
    @trpc/server: 10.5.0 => 10.5.0 
    react: 16.8.6 => 16.8.6 
    typescript: 4.9.4 => 4.9.4 
```

### Describe the bug

From https://tkdodo.eu/blog/react-query-error-handling I am able to set the `useErrorBoundary` on the `QueryClient` and then wrap components with ReactErrorBoundary so it successfully catch errors and display fallback error component.
tRPC supposedly is a wrapper around ReactQuery and I expected same behaviour when setting the `QueryClient` for tRPC react client and get same result where it catches the TRPCClientError within the Error boundary but this is not the case. Im unable to catch the error like I can do with raw ReactQuery.

Looks like tRPC client swallows the error or something instead of re-throwing it when `useErrorBoundary: true`.

If I do manual re-throw this works but this is so cumbersome to remember to write for every single query that I need to rethrow an error.

```js
 // queryClient
 
  const [queryClient] = useState(
    () =>
      new QueryClient({
        defaultOptions: {
          queries: {
            useErrorBoundary: true,
          },
        },
  )
```

```js
 // This works and Error boundary successfully catch the error
  const { data, isError, error } = trpc.someRouter.getAll.useQuery()

  if (isError) throw error
  ```

```js
 // This doesn't work and breaks the app. Error boundary unable to catch the error. 
 // With raw reactQuery this works as expected
  const { data } = trpc.someRouter.getAll.useQuery()
  ```

### Link to reproduction

...

### To reproduce

...

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

**Comment by KATT** [comment]
I'm at a bit of a loss here since I've never used the feature, but I really can't see why this wouldn't work as we just forward the options to react-query. Additionally, [Suspense works](https://trpc.io/docs/suspense). 

@TkDodo, sorry for pinging, do you have any idea?

**Comment by KATT** [comment]
Also, @stychu please make a reproduction, it's very hard to help you without something to reference.

**Comment by sachinraja** [comment]
Feel free to re-open with a reproduction

**Comment by stychu** [comment]
@KATT @TkDodo 
here is reproduction https://github.com/stychu/trpc-testo
sorry if it's a bit messy and a lot of typescript warnings. I wanted just try reproduce as close as possible to my current setup

**Comment by sachinraja** [comment]
@stychu can you try updating to react@18.2.0 and react-dom@18.2.0?

**Comment by stychu** [comment]
@sachinraja yeah bumping to react 18.2.0 solves the problem. 
Well I guess I need to go with re-throwing manually for now untill I will be able to upgrade to the newest react.
Thanks for heads-up
