### ISSUE TITLE
bug: No type for .query using client on Deno

### ISSUE THREAD

**Issue by reggi** [trpc/trpc#3450]
### Provide environment information

this uses deno!

### Describe the bug

<img width="752" alt="Screen Shot 2022-12-21 at 7 28 03 PM" src="https://user-images.githubusercontent.com/296798/209029119-c979d722-9d74-48a9-97ed-8e37f66e1921.png">
<img width="1057" alt="Screen Shot 2022-12-21 at 7 28 10 PM" src="https://user-images.githubusercontent.com/296798/209029120-5e85a8e5-d4cc-404b-a9ec-7062e0115aff.png">

`Property 'query' does not exist on type 'DecoratedProcedureRecord<unknown, BuildProcedure<"query", { _config: RootConfig<{ ctx: {}; meta: {}; errorShape: DefaultErrorShape; transformer: DefaultDataTransformer; }>; ... 5 more ...; _output_out: unique symbol; }, User | undefined>>'.deno-ts(2339)`

### Link to reproduction

https://github.com/reggi/deno-trpc-issue-temp-01

### To reproduce

mainly just followed docs

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

**Comment by reggi** [comment]
This was my first time trying out trpc forgive me if i'm using it wrong, but I'd expect query to have a type here. Oh I forgot to mention the call works!

**Comment by KATT** [comment]
Hmm... the project doesn't have a tsconfig file. 

Try putting this in the root? https://github.com/trpc/trpc/blob/main/examples/deno-deploy/tsconfig.json

**Comment by reggi** [comment]
@KATT hey thanks for the response, that didn't seem to do anything, still red squiggle under the word `query` 😭

**Comment by sachinraja** [comment]
I was able to reproduce it but this is definitely a Deno issue. Seems like nested dependencies are not working correctly.

**Comment by KATT** [comment]
Ummm.... I guess there's prob a reference to this somewhere in here: https://github.com/denoland/deno/issues?q=is%3Aissue+is%3Aopen+npm+label%3A%22node+compat%22

**Comment by reggi** [comment]
I'm closing just tested with the latest version of Deno, not seeing this issue:

```
➜  ~ deno --version
deno 1.29.4 (release, aarch64-apple-darwin)
v8 10.9.194.5
typescript 4.9.4
```
