### ISSUE TITLE
feat: Add an adapter for azure functions

### ISSUE THREAD

**Issue by leopf** [trpc/trpc#3451]
### Describe the feature you'd like to request

An adapter for [azure functions](https://learn.microsoft.com/en-us/azure/azure-functions/functions-overview). 

### Describe the solution you'd like to see

Add an adapter to server/adapters like with aws-lambda.

### Describe alternate solutions

This solution could be maintained outside of this repo. Since azure functions is a good choice of deployment, it makes sense to implement this "officially".

### Additional information

I have already created and tested this adapter. I have also provided an example in the following PR. 

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

**Comment by KATT** [comment]
> Honestly, I'd love to have this in the repo and I think you made really good work here.
> 
> However, the reality though is that we can't maintain more adapters at the moment (unless @microsoft starts sponsoring us 😅) ; we already have loads of them, the surface area of tRPC is quite large, and no one works on tRPC full-time.
> 
> This would make a great third party library to be put on https://trpc.io/awesome

_Originally posted by @KATT in https://github.com/trpc/trpc/pull/3452#pullrequestreview-1227492405_
