### ISSUE TITLE
Unhandled Runtime Error Error: Cannot find module `@tanstack/react-query`

### ISSUE THREAD

**Issue by dahal** [trpc/trpc#3465]
### Provide environment information

![Screen Shot 2022-12-22 at 11 35 53 PM](https://user-images.githubusercontent.com/3684236/209277767-8b9c9236-979b-4a14-ac37-2b0804f7e3ae.png)

### Describe the bug

I am following standard [T3 Stack's](https://create.t3.gg/) tRPC's configuration and I am not quite sure why I am getting this error. Here is the complete code for it

https://github.com/envless/envless/pull/13

### Link to reproduction

https://github.com/envless/envless/pull/13

### To reproduce

Here are the steps to reproduce this error:-

* Pull this repo/branch https://github.com/envless/envless/pull/13
* Run `yarn install`
* Run `yarn dev`

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

**Comment by sachinraja** [comment]
can't reproduce, maybe try this:
```
rm -rf node_modules
yarn install
```

**Comment by dahal** [comment]
> can't reproduce, maybe try this:
> 
> ```
> rm -rf node_modules
> yarn install
> ```

@sachinraja Yep, just tried that, still getting same error. I am on node `v18.12.1` yarn `1.16.0` and npm `8.19.2` if that helps.

**Comment by dahal** [comment]
I think i managed to fix this. I upgraded my yarn and npm to latest, but more importantly this commit may have fixed the issue
https://github.com/envless/envless/commit/c71461d2096c2984a1ff0ae74b64311f6fd43a29

**Comment by sachinraja** [comment]
nice! I was still unable to reproduce with your versions so that's odd.

**Comment by dahal** [comment]
Thanks for trying @sachinraja prolly has something to do with npm cache, basically getting rid of everything and starring over with npm/yarn versions, deleting node_modules and doing those changes on https://github.com/envless/envless/commit/c71461d2096c2984a1ff0ae74b64311f6fd43a29 solved this issue and I am no longer blocked, I have to say, I was about about to give up on [Introducing tRPC to the project](https://github.com/envless/envless/pull/13) and move to REST to solve immediate problem. 🎉

**Comment by clakr** [comment]
Hi! I've had similar issue, and quite fairly new to opening issues. Should I make a new issue regarding this? Anyways, I've done what OP did and error still persists. 

### Provide environment information
![image](https://user-images.githubusercontent.com/103111910/210162904-1fe93966-6908-488e-ab18-6a34a05d024a.png)

### Describe the bug
This project is also generated with T3 Stack few months ago, came from a break, and decided to upgrade from tRPC v9 to v10. I did follow the [https://trpc.io/docs/migrate-from-v9-to-v10](migration guide) and your codemod. Migrated the queries, then got this error.

### Link to repository
https://github.com/clakr/clark-resume
