### ISSUE TITLE
bug: migration from v9 to v10 causes Zod error in combination with Express

### ISSUE THREAD

**Issue by ollydixon** [trpc/trpc#3520]
### Provide environment information

System:
    OS: macOS 13.0.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 23.34 GB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
    npm: 8.11.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
  Browsers:
    Chrome: 108.0.5359.124
    Firefox: 108.0.1
    Safari: 16.1
  npmPackages:
    @trpc/server: ^10.7.0 => 10.7.0 

### Describe the bug

Following the migration guide from V9 to V10 I get the following error.

```

/Users/oliverdixon/Projects/testapp/testapp-node/node_modules/zod-to-ts/dist/index.cjs:79
  const { typeName } = zod._def;
          ^
TypeError: Cannot destructure property 'typeName' of 'zod._def' as it is undefined.
    at zodToTsNode (/Users/oliverdixon/Projects/testapp/testapp-node/node_modules/zod-to-ts/dist/index.cjs:79:11)
    at zodToTs (/Users/oliverdixon/Projects/testapp/testapp-node/node_modules/zod-to-ts/dist/index.cjs:75:16)
    at printTypeFromInputParser (/Users/oliverdixon/Projects/testapp/testapp-node/node_modules/trpc-playground/dist/handlers/express.cjs:246:49)
    at /Users/oliverdixon/Projects/testapp/testapp-node/node_modules/trpc-playground/dist/handlers/express.cjs:213:37
    at Array.forEach (<anonymous>)
    at buildTrpcTsType (/Users/oliverdixon/Projects/testapp/testapp-node/node_modules/trpc-playground/dist/handlers/express.cjs:210:84)
    at Object.zodResolveTypes [as resolveTypes] (/Users/oliverdixon/Projects/testapp/testapp-node/node_modules/trpc-playground/dist/handlers/express.cjs:231:12)
    at /Users/oliverdixon/Projects/testapp/testapp-node/node_modules/trpc-playground/dist/handlers/express.cjs:295:38
    at /Users/oliverdixon/Projects/testapp/testapp-node/node_modules/uttp/dist/chunk-YQ4ORDYY.cjs:9:30
    at /Users/oliverdixon/Projects/testapp/testapp-node/node_modules/uttp/dist/adapters/express/index.cjs:9:26
```

I'm using express adapter as documentation suggests

```
  app.use(
    '/trpc',
    trpcExpress.createExpressMiddleware({
      router: appRouter,
      createContext: authContext,
    }),
  );

```

### Link to reproduction

It's using express, can't get that to work in Stackbiltz

### To reproduce

Use TRPC v10 with Zod and express adapter

### Additional information

I'm thinking it could be ```at buildTrpcTsType (/Users/oliverdixon/Projects/app/app-node/node_modules/trpc-playground/dist/handlers/express.cjs:210:84)```

But not sure. 

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

**Comment by ollydixon** [comment]
In ```node_modules/zod-to-ts/dist/index.cjs``` line 79

Can change to
```let typeName = zod._def?.typeName ?? 'ZodAny';```

Starts the server, but I noticed in the playground that TRPC is no longer returning json, it's being nested? Is that normal?

<img width="202" alt="Screenshot 2022-12-29 at 19 51 50" src="https://user-images.githubusercontent.com/6940726/209996415-8c7718ab-13b0-4e9b-a2ce-36212cd2f75d.png">

Also, the server crashes if ZOD is used on any endpoints, not sure what to do here.

**Comment by ollydixon** [comment]
Removing superjson seems to fix it.

But I have to keep the change from above :-|

**Comment by ollydixon** [comment]
Our issue was using ```interlop```, without it, it seems to work fine.

But now we got a new issue, we got hundreds of endpoints like this to migrate across multiple projects and the codegen doesn't work, so I guess we will not be upgrading to V10.

<img width="383" alt="Screenshot 2022-12-29 at 20 56 57" src="https://user-images.githubusercontent.com/6940726/210005632-2ec1c55c-0e5b-4fe7-aa43-02c15aaeb58e.png">

**Comment by juliusmarminge** [comment]
Am i missing the point here or where do you have an error with tRPC? Your errors seem to be from `zod-to-ts`?

**Comment by sachinraja** [comment]
Please re-open on trpc-playground

**Comment by ollydixon** [comment]
@juliusmarminge I've explained that it's an issue using V9 and V10 together with ```interlop```

@sachinraja sure but it's not related to  ```trpc-playground```?

**Comment by sachinraja** [comment]
tRPC Playground uses a `zod-to-ts` (which is also my library), tRPC does not.

**Comment by ollydixon** [comment]
@sachinraja ah ok, didn't know, thanks
