### ISSUE TITLE
feat: Configurable delimiter for `namespace.procedure` combo (router merging)

### ISSUE THREAD

**Issue by moltar** [trpc/trpc#3537]
### Describe the feature you'd like to request

I'd like to be able to set the delimiter for the namespace and procedure.

### Describe the solution you'd like to see

Ability to pass a delimiter other than `.`

### Describe alternate solutions

Generating a path mapping for each `namespace.procedure` combo explicitly from the router configuration.

OR

Using a custom link that rewrites the request (did not try, just theoretical) 

### Additional information

Use case:

AWS API Gateway has a limitation on route definitions.

Only the following options are available ([docs](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-routes.html?icmpid=apigateway_console_help#http-api-develop-routes.evaluation)):

```
GET /pets/dog/1
GET /pets/dog/{id}
GET /pets/{proxy+}
ANY /{proxy+}
```

I want to separate the routes by router namespace, which would require a route like this:

```
GET /pets.{procedure}
```

But, unfortunately, AWS does not support the `.` in its router path config.

An error is thrown:

> One or more path parts appear to be invalid. Parts are validated against this regular expression: `^(\{[\w.:-]+\+?\}|[a-zA-Z0-9.:_-]+)$`

A solution would be to reconfigure tRPC to use a `/` as a delimiter.

```
GET /pets/{procedure}
```

I believe it is configured here:

https://github.com/trpc/trpc/blob/81d85defcd58ea0d8941f1677028d0ed4250d398/packages/server/src/core/router.ts#L254

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

<sub>[T-79](https://linear.app/trpc/issue/T-79/feat-configurable-delimiter-for-namespaceprocedure-combo-router)</sub>

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/3537">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/3537/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/3537/pledge.svg">
</picture>
</a>

**Comment by NicholasFields** [comment]
Experiencing this as well.

Assigning each (sub-)router to its own distinct lambda can be essential for securing to least-privilege, minimizing cold-start time, etc.

My current understanding is that multi-lambda tRPC would require delimiter configurability.

Still digging thru related issues, discussions, and AWS API GW docs.

If anyone has another solution or can tell me what I'm missing, please LMK!

----------

@igalklebanov's WIP changes #3692 seem dope.

Before finding them, I toyed locally with disabling batching and jankily editing the delimiter `. => /` as `url` is passed to `fetch(url, ...options)`.

This allows API GW Path: `GET /trpc/someRouter/{path+}` to function alongside `GET /trpc/anotherRouter/{path+}` 

which effectively permits a `router-per-lambda` setup

**Comment by spirobel** [comment]
why not use / by default? the . needlessly breaks away from how we expect a rest endpoint to behave. 
or am I missing something? 

is there a good reason to use a . instead of a slash like URLs typically do to delimit paths?

**Comment by KATT** [comment]
Closing this as it's been open for over a year with no one caring enough about it to either offer fundig it or building it.

Still open for grabs, but just doing some housekeeping in our issues.
