### ISSUE TITLE
bug: v10 errors are being enforced

### ISSUE THREAD

**Issue by ollydixon** [trpc/trpc#3538]
### Provide environment information

System:
    OS: macOS 13.0
    CPU: (8) arm64 Apple M1 Pro
    Memory: 69.06 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.7.0 - /opt/homebrew/bin/node
    npm: 8.15.0 - /opt/homebrew/bin/npm
  Browsers:
    Firefox: 108.0.1
    Safari: 16.1
  npmPackages:
    @trpc/server: ^10.7.0 => 10.7.0 

### Describe the bug

We use rate limiting (like any good service should).

We don't want these errors to be logged otherwise it will poison the logger and hide real errors; also make it impossible to auto-alert for real errors. They are returned to the client as an error so we can't optionally decide what to do with it.

In V9 the TRPC errors were not logged automatically when using the errorformatter, now they are in 10.

### To reproduce

Error catching

```
const t = initTRPC
  .context<Context>()
  .meta<OpenApiMeta>()
  .create({
    // Breaks zod
    // transformer: superjson,
    errorFormatter({ shape, error }) {
      // @ts-ignore
      if (error.cause == 'rate-limit-reached') {
        // There is an issue where it's still logged in V10 :-(
        console.warn(`Rated limited reached for path ${shape?.data.path}`);
      } else {
        console.log(error);
      }
      // @ts-ignore
      shape.data.cause = error.cause ?? 'unknown-cause';
      return {
        ...shape,
      };
    },
  });


```
// Example of an endpoint that registers a post view after 3 seconds, once every 5 minutes.
```
export const postRegisterView = publicProcedure
  .input(
    z.object({
      id: z.string(),
    }),
    //
  )
  .mutation(async ({ ctx, input }) => {
    // Don't log this :-/
    await rateLimit({
      numberOfRequests: 1,
      windowInSeconds: 60 * 5, // Every n minutes
      uniqueToken: getUniqueToken(ctx) + '_' + input.id,
      //
    });

    if (ctx.user?.id != input.id) {
      const post = await Post.findOne({ where: { id: input.id } });
      await post?.increment('views', { by: 1 });
      await post?.increment('trendingScore', { by: 1 });

      if (post?.originalPostId) {
        const sharedPost = await Post.findOne({ where: { id: post?.originalPostId } });
        await sharedPost?.increment('views', { by: 1 });
      }
    }

    return {
      success: 'ok',
    };
  });
```

---

Also as a side note, the 'code' variable in the TRPC error should be optional or flexible values, we don't use it.
We use 'some-string-cause' that is handled via the client. Since there are hundreds of 'cause' types.

Might be good to allow us to type anything in 'code'.

We have to use this all the time instead.

```
/**
 * Generates an error object with the given cause
 * Since the 'code' isn't flexible, so return 'PRECONDITION_FAILED' every failed request.
 */
export const returnError = (cause: String, message?: string) => {
  return new TRPCError({ code: 'PRECONDITION_FAILED', cause, message });
};
```

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

**Comment by KATT** [comment]
Is it maybe because you throw a `string` and not an `Error` instance? We might be ensure that `cause` is an error

**Comment by ollydixon** [comment]
We throw the TRPCError instance. :-)

**Comment by KATT** [comment]
Okay, we need a reproduction link because it's too hard to decipher what happens above and what you expect.

For instance, `if (error.cause == 'rate-limit-reached') {` should be an impossible state since `error.cause` has to be an `Error`-instance

**Comment by ollydixon** [comment]
@KATT I'll get back with a reproduce repo, just hang tight; both using tRPC hehe (We converted over 300 endpoints from an old GraphQL endpoint to tRPC) 🚀

**Comment by ollydixon** [comment]
It would seem that the 'message' and the 'cause' vars are being switched in V10 vs V9!

Breaking everything in our platforms hehe. We really need a 'custom' code option. It's fairly standard to return custom error message status to the client (so it can show translated dialogs and errors, and do multiple actions based off the throw error).

<img width="584" alt="Screenshot 2023-01-04 at 17 55 36" src="https://user-images.githubusercontent.com/6940726/210608179-c4b1a763-ce97-4b64-b5e3-4f68add6fc21.png">

I can create a demo project soon though!

**Comment by ollydixon** [comment]
So it would seem that ```errorFormatter``` has some additional steps.

Instead of just error.cause it's now ```error.cause.message```

Although are logging with string, not object.

```
export const returnError = (cause: String, message?: string) => {
  return new TRPCError({ code: 'PRECONDITION_FAILED', cause, message });
};
```

It would be nice if you could just add string as a union on 'code' :-)

**Comment by ollydixon** [comment]
I'll close this for now :-)
