### ISSUE TITLE
bug: wsLink in nodejs server environment crashes when accessing WebSocket.OPEN

### ISSUE THREAD

**Issue by nohum** [trpc/trpc#3539]
### Provide environment information

```
  System:
    OS: Linux 6.1 Arch Linux
    CPU: (20) x64 Intel(R) Core(TM) i9-10900K CPU @ 3.70GHz
    Memory: 34.94 GB / 62.51 GB
    Container: Yes
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: 3.2.3 - /usr/bin/yarn
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
  Browsers:
    Chromium: 108.0.5359.124
    Firefox: 108.0.1
  npmPackages:
    react: ^17.0.2 => 17.0.2 
    typescript: ^4.8.3 => 4.8.3 
```

### Describe the bug

When using TRPC with `wsLink` in a nodejs server-to-server environment, the usage of a `wsLink()` yields the error: 

```
ReferenceError: WebSocket is not defined
    at file:///xxxx/node_modules/@trpc/client/dist/links/wsLink.mjs:190:49
    at file:///xxxx/node_modules/@trpc/client/dist/links/wsLink.mjs:274:21
```

As I am within a nodejs environment, i use the Isomorphic WebSocket (package `"isomorphic-ws": "^4.0.1"` and `"ws": "^8.8.1"`) and initialize my `wsLink` like this:

```
import IsomorphicWebSocket from 'isomorphic-ws';

const WebsocketImpl = IsomorphicWebSocket as unknown as typeof WebSocket; // type whoes for typescript
const wsClient = createWSClient({
      WebSocket: WebsocketImpl,
      url: 'wss://my-url-here.com/ws',
    });
```

The problem happens in `wsLink.ts` on this line, where the `WebSocket` type is not defined (which is not defined as I am not using a polyfill). 

https://github.com/trpc/trpc/blob/81d85defcd58ea0d8941f1677028d0ed4250d398/packages/client/src/links/wsLink.ts#L268

### Link to reproduction

none-yet

### To reproduce

If necessary, I can provide a reproduction sample; First I just want to ask if the proposed solution would be viable at all or maybe there is another solution.

### Additional information

As a first idea I would suggest to replace the call to `WebSocket.OPEN` with the reference to the WebSocket given with the client options from:

```
activeConnection.readyState === WebSocket.OPEN &&
```

to:

```
activeConnection.readyState === WebSocketImpl.OPEN &&
```

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

**Comment by KATT** [comment]
Looks like an easy fix, I guess the `createClient` should return `WebSocket` and then we can use that in the link

**Comment by nohum** [comment]
As far as I see the WebSocketImpl is exclusive to the `createWSClient` (actually the `request` method inside of it).

I am going to create a pull-request, do you still want me to return the WebSocketImpl from the `createWSClient` method?

**Comment by nohum** [comment]
Just for the sake of being consistent across the codebase I can also hard-code the constant like here:

https://github.com/trpc/trpc/blob/81d85defcd58ea0d8941f1677028d0ed4250d398/packages/server/src/adapters/ws.ts#L365-L365

(Though I would prefer using the constant from the implementation.)
