### ISSUE TITLE
feat: add keep alive (ping/pong) implementation to websocket handler

### ISSUE THREAD

**Issue by nohum** [trpc/trpc#3543]
### Describe the feature you'd like to request

We are using long-living websocket connections and would like to keep them alive using websocket ping-pongs. 

### Describe the solution you'd like to see

I already have a working solution on my side, so it is just about the incorporation I guess.

However, I would modify the `applyWSSHandler` and add the ping/pong code there.

https://github.com/trpc/trpc/blob/81d85defcd58ea0d8941f1677028d0ed4250d398/packages/server/src/adapters/ws.ts#L113-L113

In the `WSSHandlerOptions` I would introduce a property `keepAliveMs?: number`. If unset, I would default to a keep-alive timeout of e.g. `20000`ms. This means that package upgrades on developer-side would automatically introduce this as an opt-in (is this regarded as a breaking change?). Additionally, you could also set the property to `0` to disable keep alive. One issue I am unsure about here is on how to expose this best to the various adapters (e.g. I am using the `fastifyTRPCPlugin`) which is the main reason why I would go for an opt-out to be honest.

Within the `applyWSSHandler` I would (if enabled) listen for new connections and set a interval for pings (set by `keepAliveMs`) and also a timeout to wait for pongs (this timeout would also be `keepAliveMs`). If no pong is received, the connection is terminated.

### Describe alternate solutions

An alternate solution would be to implement keep alive frames within TRPC as operations itself.

However, native websocket ping/pongs are supported out-of-the box by websocket implementations as part of control frames (see RFC6455) and would not pollute the messages that are sent and received by TRPC itself.

### Additional information

This issue should only be the implementation of the ping/pong part on the server.

As written in the RFC (https://www.rfc-editor.org/rfc/rfc6455#section-5.5.2), client implemenations are required to respond to pings with a pong, so the implementation of the ping-part on the server using native websocket pings should be sufficient.

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

<sub>[TRP-42](https://linear.app/trpc/issue/TRP-42/feat-add-keep-alive-pingpong-implementation-to-websocket-handler)</sub>

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/3543">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/3543/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/3543/pledge.svg">
</picture>
</a>

**Comment by KATT** [comment]
Closing this as it's been open for over a year with no one caring enough about it to either offer fundig it or building it.

Still open for grabs, but just doing some housekeeping in our issues.
