### ISSUE TITLE
feat: Stronger typing for predicate invalidation

### ISSUE THREAD

**Issue by nicolassanmar** [trpc/trpc#3545]
### Context
I'm trying to invalidate a query based on some complex rules, as I don't want to invalidate every single call to that query.
The way to do this is using `.invalidate(undefined, {predicate: (query) })`, where predicate takes a function that dictates which queries should be invalidated.
The problem I have, is that the `query` has the default `react-query` type of `Query<unknown,unknown,unknown, unknown[]>` which is not true for our TRPC queries.

### Demonstration
``` typescript
const utils = trpc.useContext()
utils.router.query.invalidate(undefined, {
  predicate: (query: Query<unknown,unknown,unknown, unknown[]>) => {
    // We will have to cast `query` here to perform the invalidation based on the input data
    return true
  }
})
```

### Describe the solution you'd like to see

We know that if `invalidate()` is called on a query defined by the user, the typing will be:
``` typescript
type RouterInput= inferRouterInputs<AppRouter>
type RouterOutput = inferRouterOutputs<AppRouter>

// desired type of  example query called with `trpc.router.fn` , in predicate invalidation
type DesiredType = Query<
          RouterInput['router']['fn'],
          TRPCClientError<AppRouter>,
          RouterOutput['router']['fn'],
          [ [['router],['fn']], { input: RouterInput10['router']['fn'] } ]
>
```

If `invalidate()` is called at a router level, the type of the query, should be a union amongst the posible `DesiredType`'s of the procedures/routers inside it.

### Describe alternate solutions

Currently, I implemented a worse version of this to cast the type of the query, but its bad since it only supports queries and only exactly two levels for the path:

``` typescript
type QueryHelper<
    RouterOutput,
    K extends keyof RouterOutput & keyof RouterInput,
    K2 extends keyof RouterOutput[K] & keyof RouterInput[K],
  > = Query<
      RouterInput[K][K2],
      TRPCClientError<AppRouter>,
      RouterOutput[K][K2],
      [K, { input: RouterInput[K][K2] }]
 >

utils.router.query.invalidate(undefined, {
      predicate: (_query) => {
          const query = _query as unknown as QueryHelper<RouterOutput10, 'router', 'query'>
          return false
      }
})
```

### 👨‍👧‍👦 Contributing

- [x] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

**Comment by JonParton** [comment]
Just a sign post to some old removed code that may help here for the router level stuff. 

Once upon a time invalidate at a router level could take a filter based on the input of the query. [This code deleted in this PR](https://github.com/trpc/trpc/pull/3124/files#diff-ef4e1d08a351372bae0fff79abe60481bb5e00914f176984386eaa48c1e209bdL148-L170) was used to do that. 

I expect it's stale now and you will want to get outputs / errors too for the predicate;  but the TS principals will still apply! 👍

**Comment by JonParton** [comment]
Also bear in mind that you may come a cropper of this stale issue https://github.com/trpc/trpc/issues/2759 ; where procedures can be defined using `.` notiation in their name and so may appear to be part of a router but not be part of the Typescript Router Deffinitions for it! 

My thought on the best way to solve this is to disallow `.`'s in procedure names which would mean they will always be defined where they should be Typescript wise! (As part of the correct sub router!!)

**Comment by SrBrahma** [comment]
I created #3547, maybe it's useful to you!

Notice that it only adds the predicate type to the procedures, not the routers. Doesn't seem useful to me so I didn't it.
