### ISSUE TITLE
bug: Next 13 Client component loses types for useInfiniteQuery

### ISSUE THREAD

**Issue by DavidTParks** [trpc/trpc#3555]
### Provide environment information

```

  System:
    OS: macOS 13.0
    CPU: (10) arm64 Apple M1 Pro
    Memory: 145.44 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.12.1/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
  Browsers:
    Brave Browser: 108.1.46.144
    Chrome: 108.0.5359.124
    Safari: 16.1
  npmPackages:
    @tanstack/react-query: ^4.18.0 => 4.18.0 
    @trpc/client: ^10.8.1 => 10.8.1 
    @trpc/react-query: ^10.8.1 => 10.8.1 
    next: ^13.1.1 => 13.1.1 
    react: 18.2.0 => 18.2.0 
    typescript: 4.9.3 => 4.9.3 
```

### Describe the bug

I am using Next 13's app directory and also trying to use a `useInfiniteQuery` but it is losing types in a client component. A normal query works fine and infers types correctly, it's just something with the useInfiniteQuery here. The query output type is `any`. 

<img width="1129" alt="Screenshot 2023-01-06 at 6 57 54 AM" src="https://user-images.githubusercontent.com/5482124/211037610-f6ae2aa8-dd38-4fe3-a182-b1eb8dc9ae1d.png">

I found https://github.com/trpc/trpc/issues/3428 but it didn't lead me to a resolution.

```
Property 'useInfiniteQuery' does not exist on type '{ getQueryKey: (input: void | { userId?: string; limit?: number; cursor?: string; initialCursor?: string; }, type?: QueryType) => QueryKey; useQuery: ProcedureUseQuery<BuildProcedure<"query", { _config: RootConfig<...>; ... 5 more ...; _output_out: unique symbol; }, { ...; }>, "notification.list">; } & object & { .....'.ts(2339)
```

### Link to reproduction

https://github.com/DavidTParks/vamp/blob/trpc-notification-list/components/notification-list.tsx

### To reproduce

Clone the repository, checkout the `trpc-notification-list` branch and navigate to `components/notification-list.tsx` and check the inferred types for the notification list query. It is `any`;

### Additional information

I understand Next 13 is in beta and this might not be possible currently! 

I followed https://github.com/trpc/next-13 to get setup a bit. 

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

**Comment by KATT** [comment]
You need to use `strict: true` in your tsconfig.

**Comment by DavidTParks** [comment]
Thank you!! @KATT
