### ISSUE TITLE
bug: examples/minimal doesn't run

### ISSUE THREAD

**Issue by Yandawl** [trpc/trpc#3568]
### Provide environment information

```
  System:
    OS: macOS 13.1
    CPU: (10) x64 Apple M1 Max
    Memory: 475.07 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.13.0 - /usr/local/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.5.0 - /usr/local/bin/npm
    Watchman: 2022.10.17.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 108.0.5359.124
    Safari: 16.2
  npmPackages:
    typescript: ^4.8.3 => 4.9.4 
 ```

### Describe the bug

Error is produced when executing `npm run dev`

```
TRPCClientError: Unexpected token < in JSON at position 0
   meta: undefined,
   shape: undefined,
   data: undefined,
   [cause]: SyntaxError: Unexpected token < in JSON at position 0
       at JSON.parse (<anonymous>)
       at packageData (node:internal/deps/undici/undici:6370:23)
       at specConsumeBody (node:internal/deps/undici/undici:6348:14)
       at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Link to reproduction

https://github.com/trpc/trpc/tree/main/examples/minimal

### To reproduce

cd to /examples/minimal and run 

1. `npm i`
2. `npm run dev`

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

**Comment by juliusmarminge** [comment]
Worked on my end: 

<img width="739" alt="CleanShot 2023-01-08 at 21 52 22@2x" src="https://user-images.githubusercontent.com/51714798/211218542-5929bd35-e2d1-4193-9474-cce7b5ec4225.png">

**Comment by KATT** [comment]
Probably npm vs pnpm. For our repo, ppl need to use pnpm

**Comment by juliusmarminge** [comment]
> Probably npm vs pnpm. For our repo, ppl need to use pnpm 

fwiw it worked using `npm run dev` too
