### ISSUE TITLE
docs: fix edge runtime docs

### ISSUE THREAD

**Issue by AmirL** [trpc/trpc#3580]
### Area of Improvement

Vercel Edge Runtime example is not working. 

`edge-runtime --listen server.ts --port 3000 ` this call just exit without any errors.

It works though, If I remove all imports 
`
// server.ts
addEventListener('fetch', (event) => {
  return event.respondWith();
});

`

Which is useless of course. I think the documentation should be fixed, or a working example should be attached. 

### Link to related docs

https://trpc.io/docs/fetch

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing the suggested changes!

<sub>[TRP-44](https://linear.app/trpc/issue/TRP-44/docs-fix-edge-runtime-docs)</sub>

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/3580">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/3580/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/3580/pledge.svg">
</picture>
</a>

**Comment by Jorgee1** [comment]
Hello, I was also trying to deploy tRPC to Vercel's edge and found that the example has issues.
After some testing I managed to get it working, here is the code:

https://github.com/Jorgee1/vercel-trpc-minimal

The "vercel.json" file is important, without it the page will throw a 404 error when accessing any tRPC endpoint.

**Comment by KATT** [comment]
@Jorgee1 @AmirL any of you feel like clicking the edit button to fix the docs? will close this for now

**Comment by AmirL** [comment]
> @Jorgee1 @AmirL any of you feel like clicking the edit button to fix the docs? will close this for now

Easy thing. Although no idea how it should be. Can you provide the correct example and I put it there? :)
