### ISSUE TITLE
[TRP-46] feat: FAQ improvements 

### ISSUE THREAD

**Issue by KATT** [trpc/trpc#3589]
### Describe the feature you'd like to request

Gathering all potential FAQ improvements here

- [ ] Better structure in general, more text
- [x] Router-middlewares https://github.com/trpc/trpc/discussions/3579
- [ ] Inner / outer context https://trpc.io/docs/context#inner-and-outer-context
- [ ] Setup problems: monorepos, tsconfig project references etc
- [ ] TS Perf:
  -   https://github.com/trpc/trpc/discussions/2448
  - https://twitter.com/TkDodo/status/1582282692577853440
- [x] Next 13?
- [x] Semver
- [ ] 

<sub>[TRP-46](https://linear.app/trpc/issue/TRP-46/feat-faq-improvements)</sub>

**Comment by nawed2611** [comment]
Is this issue open to work on?
