### ISSUE TITLE
bug: Zod Branded strings not typed end to end

### ISSUE THREAD

**Issue by aphex** [trpc/trpc#3602]
### Provide environment information

```
  System:
    OS: Linux 5.15 Ubuntu 20.04.4 LTS (Focal Fossa)
    CPU: (16) x64 Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
    Memory: 23.45 GB / 31.31 GB
    Container: Yes
    Shell: 3.2.2 - /usr/bin/fish
  Binaries:
    Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 9.1.3 - ~/.nvm/versions/node/v16.17.0/bin/npm
  Browsers:
    Chrome: 102.0.5005.6
```

### Describe the bug

When using a branded string in a procedure as an input the client only requires a `string`

### Link to reproduction

https://github.com/aphex/branded-trpc

### To reproduce

`pnpm dlx degit aphex/branded-trpc branded-trpc`
`cd branded-trpc`
`pnpm i`

Open `client.ts` in an editor and compare line 17 and 22

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

**Comment by KATT** [comment]
Okay, so I investigated this and there's unfortunately nothing we can do on our end.

## Why it doesn't work

We use the `_input` for our inputs - that's how we can support things like `z.string().transform(v => ...)` - and we can't change that. In zod, a branded string still has the _input_ of just an unbranded `string`:

### Code
```ts
import { z } from 'zod';

const brandedString = z.string().brand("branded");

type Input = typeof brandedString["_input"];
//    ^? type Input = string
type Output = typeof brandedString["_output"];
//    ^? type Output = string & z.BRAND<'branded'>
```

### Playground

https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgLzgXzgMyhEcDkyEAJvgNwBQFAxhAHYDO8ARlAIZ3ECmxAyjFGB0A5nAC8KAHRNBIgBQBKSaw7E5AIhWce6hZQowAnmC5wAknTABXeBKMmImOFu58BQ4QG11AfSHWYdQBdSgB6ULhIuAA9AH4DY1MAeRsA8Th7Lkdndm03WS9fCFSbYLCIqLiqIA


## Thoughts

I am unsure how came the gang over at zod came to the decision there to make the input and output different here but they likely did it for good reasons. Changing it would likely be seen as a breaking change within zod even if not many people likely leverage the `_input` of zod schemas.


## Potential workaround

Here's a hack that might or might not work & I don't know the implications of it: https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgLzgXzgMyhEcDkyEAJvgNwBQFAxhAHYDO8DArmAKZQBCUAhncXbEAyjCjA6AczgBeOAB4AKnHYAPGOwEM4TcVIB8ACl0AuOIoCUs-Ygpw4tRs2oALdiF6yUAOl0TJhhbeAEZ8AsZiFpR2cFDsMCxQdDqu7p682ix0ANZ0EADuyRlwAPIgwDDyMACeHBCYKW4eADQEAPoSYCww+DYAZIgddF0wZn5ScAPI3lwASgCCAHIAIkr6aJQbVI5McKH8giJi-l6sHNxhh6J6Afj7AkL4UVQ1HHAAksPdXq-s9XuXITXfwAbQAREMRmCALqUAD0cPs9gAegB+Ci-UrdEY-Wp-Br3K7HKTgtoQbHdGHwxFItFUGj0XYQYIAKy802ZLPY1BghgQMU5ZkJQOJkmaFDQFioQA

I'd suggest opening a discussion on it over at https://github.com/colinhacks/zod, I'd love to see the reasoning on it!
