### ISSUE TITLE
feat: svelte-query

### ISSUE THREAD

**Issue by david-plugge** [trpc/trpc#3608]
### Describe the feature you'd like to request

[`@tanstack/svelte-query`](https://tanstack.com/query/v4/docs/svelte/overview) was released and i´d love to see a wrapper like [the one for react](https://trpc.io/docs/react-query)!

### Describe the solution you'd like to see

Add a wrapper around [`@tanstack/svelte-query`](https://tanstack.com/query/v4/docs/svelte/overview).

### Describe alternate solutions

Don´t add it

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

**Comment by sachinraja** [comment]
None of us on the core team use Svelte (or Svelte Query) so we're going to leave this up to the community to implement. If someone wants to do it, you're free to steal the types from our React wrapper :smile:

**Comment by ottomated** [comment]
I am currently working on a preliminary version of this.

**Comment by david-plugge** [comment]
Can't wait to see what you come up with!
