### ISSUE TITLE
feat: add shorthand `{}` for sub-routers

### ISSUE THREAD

**Issue by KATT** [trpc/trpc#3630]
### Describe the feature you'd like to request

I don't wanna write `router({ })` for my sub-routers

### Describe the solution you'd like to see

These should be equivalent

```ts
const appRouter = router({
  foo: router({
    bar: publicProcedure.query(() => '...'),
  })
})
```

```ts
const appRouter = router({
  foo: {
    bar: publicProcedure.query(() => '...'),
  }
})
```

### Describe alternate solutions

Not doing it

### Additional information

If it creates tech debt, don't do it.

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

<sub>[TRP-49](https://linear.app/trpc/issue/TRP-49/feat-add-shorthand-for-sub-routers)</sub>

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/3630">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/3630/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/3630/pledge.svg">
</picture>
</a>

**Comment by Nsttt** [comment]
I'm going to take a look at this.

**Comment by radeon8** [comment]
Does this support nested object?

**Comment by Nsttt** [comment]
> Does this support nested object?

YES ! You should be able to create routers like this.

```ts
    const router = t.router({
      foo: {
        bar: {
          foo: {
            bar: {
              foo: {
                bar: t.procedure.query(() => 'Hello I am recursive'),
              },
            },
          },
        },
      },
    });
```
Or even mixing both syntaxes.

```ts
    const router = t.router({
      foo: {
        bar: t.router({
          foo: {
            bar: {
              foo: t.router({
                bar: t.procedure.query(() => 'Hello I am recursive'),
              }),
            },
          },
        }),
      },
    });
```
