### ISSUE TITLE
feat: My own method names

### ISSUE THREAD

**Issue by AlexRMU** [trpc/trpc#3634]
### Describe the feature you'd like to request

It would be nice if the procedure on the client became a function and not an object with function.

### Describe the solution you'd like to see

```ts
const router = t.router({
    query: t.procedure.input(/* ... */).query(/* ... */),
    obj: t.router({
        fn: t.procedure.input(/* ... */).mutation(/* ... */)
    })
});

// ...

await client.query(/* ... */);
await client.obj.fn(/* ... */);
// instead of
// await client.query.query(/* ... */);
// await client.obj.fn.mutate(/* ... */);
```

### Describe alternate solutions

-

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

**Comment by juliusmarminge** [comment]
afaik the `.query` and `.mutate` is the way we differentiate on queries and mutations on the frontend so this wouldn't be possible.

When you do `procedure.mutation()` or `procedure.query()` that's only a runtime value on the server, the client only knows this on the type-layer - not runtime.
