### ISSUE TITLE
feat: query invalidation should take `Partial<Type>` instead of `Type` as the input

### ISSUE THREAD

**Issue by nicolassanmar** [trpc/trpc#3648]
### Describe the feature you'd like to request

`react-query` matches query invalidation in a fuzzy way, and allows to invalidate queries without having the whole input used to call it.

From this comment on the react query forums: https://github.com/TanStack/query/discussions/4762#discussioncomment-4649876
> from a pure react-query perspective, if your `queryKey` is:
> 
> ```
> ['my-path', { a: 'b', foo: 'bar' }]
> ['my-path', { a: 'b', something: 'else' }]
> ```
> 
> it should be possible to target them both for query invalidation by doing:
> 
> ```
> queryClient.invalidateQueries({
>   queryKey: ['my-path', { a: 'b' }]
> })
> ```
> 
> because that does fuzzily match them both. It might be that trpc doesn't have a concept for that though ...

Trpc does not currently allow to match queries this way.

### Describe the solution you'd like to see

Having a query with the input type type:

``` typescript
type TInput = { id: string, name: string, lastName: string | undefined } 
```
Even though we call the query with the full TInput, the invalidation should allow to do this:
``` typescript
query.invalidate({id: 'id'})
```
This should be easy to do, as `react-query` does already behave like that, it's just a type issue. It should be a deep partialization of it.

### Describe alternate solutions

Making it `Partial<TInput>` would solve some problems, but I believe `react-query` will match everything fuzzily so the deep partialization is better.

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

**Comment by KATT** [comment]
cc @TkDodo @juliusmarminge WDYT? this makes sense to me

**Comment by juliusmarminge** [comment]
Makes sense to me

**Comment by JonParton** [comment]
Yep! This was how it was implemented the first time round I allowed filtering by input values!! 😉

Although not sure I went for a deep partial which is likely the correct way from the info above!!

**Comment by TkDodo** [comment]
> cc @TkDodo @juliusmarminge WDYT? this makes sense to me

given that wrote the initial comment on the TanStack Query issue, I agree :)
