### ISSUE TITLE
bug: Autocomplete Issue When Input Read In Query

### ISSUE THREAD

**Issue by ebg1223** [trpc/trpc#3656]
### Provide environment information

  System:
    OS: macOS 13.0.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 138.64 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.11.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.2 - /opt/homebrew/bin/npm
    Watchman: 2022.10.24.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 109.0.5414.87
    Safari: 16.1
  npmPackages:
    @tanstack/react-query: ^4.20.0 => 4.22.3 
    @trpc/client: ^10.8.1 => 10.9.0 
    @trpc/next: ^10.8.1 => 10.9.0 
    @trpc/react-query: ^10.8.1 => 10.9.0 
    @trpc/server: ^10.8.1 => 10.9.0 
    next: 13.1.2 => 13.1.2 
    react: 18.2.0 => 18.2.0 
    typescript: ^4.9.4 => 4.9.4 

### Describe the bug

When defining a procedure, if input is present such as using procedure.query(({ctx, **input**}) => {return a}), autocomplete does not work for objects that are returned by the inner function.

Example shows multiple test cases, what works, and what doesn't. To reproduce, leave the return value present, and delete the inner const createdAt=e.createdAt. Replace it with another line(above the return), such as const ca = e.(Autocomplete fails)

### Link to reproduction

https://github.com/ebg1223/t3-test-autocomplete

### To reproduce

See Repo src/server/api/routers/example.ts

### 👨‍👧‍👦 Contributing

- [x] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

**Comment by ebg1223** [comment]
I would be happy to help with PR, but I am not enough of a typescript wizard to figure this one out. If someone can help diagnose, happy to help write a fix.

**Comment by c-ehrlich** [comment]
I can't seem to reproduce this. Getting auto complete as shown below, same for all of the other examples that are indicated as auto complete not working in your reproduction repo. All I did was `pnpm i` and `npx prisma db push`

<img width="768" alt="image" src="https://user-images.githubusercontent.com/8353666/213909483-34df7909-e78a-4dcc-abaf-e24fa3c1954b.png">

**Comment by KATT** [comment]
This is most likely that you haven't generated your prisma types or something else, 99% confident it is not an issue in trpc
