### ISSUE TITLE
bug: Quickstart trpc Client Type Error

### ISSUE THREAD

**Issue by talksik** [trpc/trpc#3658]
### Provide environment information

macos
vscode
electron-vite
react

monorepo with yarn workspaces
client electron app and server app in different packages

### Describe the bug

Trying to instantiate the trpc client, I get a type mismatch error.

Here is the file. My editor shows red squiggle/type error on the `<AppRouter>`

```
import { createTRPCProxyClient, httpLink } from '@trpc/client'
import type { AppRouter } from '@flowy/server/src/router'
import CONFIG from '../config/config'

const trpc = createTRPCProxyClient<AppRouter>({
  links: [
    httpLink({
      url: `${CONFIG.API_URL}/trpc`,
      headers: () => {
        return {
          authorization: ''
        }
      }
    })
  ]
})

export default trpc
```

The error is as follows: 
```
Type 'CreateRouterInner<RootConfig<{ ctx: Context; meta: object; errorShape: DefaultErrorShape; transformer: DefaultDataTransformer; }>, { ...; }>' does not satisfy the constraint 'Router<AnyRouterDef<AnyRootConfig, any>>'.
  The types returned by 'createCaller(...)' are incompatible between these types.
    Type '{ query: inferHandlerFn<{}>; mutation: inferHandlerFn<{}>; subscription: inferHandlerFn<{}>; } & DecoratedProcedureRecord<{ hello: BuildProcedure<"query", { _config: RootConfig<...>; ... 5 more ...; _output_out: unique symbol; }, string>; ... 12 more ...; s3: CreateRouterInner<...>; }>' is not assignable to type '{ query: inferHandlerFn<any>; mutation: inferHandlerFn<any>; subscription: inferHandlerFn<any>; } & DecoratedProcedureRecord<any>'.
      Type '{ query: inferHandlerFn<{}>; mutation: inferHandlerFn<{}>; subscription: inferHandlerFn<{}>; } & DecoratedProcedureRecord<{ hello: BuildProcedure<"query", { _config: RootConfig<...>; ... 5 more ...; _output_out: unique symbol; }, string>; ... 12 more ...; s3: CreateRouterInner<...>; }>' is not assignable to type '{ query: inferHandlerFn<any>; mutation: inferHandlerFn<any>; subscription: inferHandlerFn<any>; }'.
        Types of property 'query' are incompatible.
          Type 'inferHandlerFn<{}>' is not assignable to type 'inferHandlerFn<any>'.
            Types of parameters 'path' and 'path' are incompatible.
              Type 'TPath' is not assignable to type 'never'.
                Type 'string' is not assignable to type 'never'.ts(2344)
```

The instantiation works with a solidjs client app, but not in this one.

### Link to reproduction

https://trpc.io/docs/quickstart#using-your-new-backend-on-the-client

### To reproduce

Following the quickstart docs in trpc, specifically the client side:
https://trpc.io/docs/quickstart#using-your-new-backend-on-the-client

### Additional information

I am able to ts-ignore it and use it fine, but I am surprised that the quickstart doesn't work for me and that no one else is having this problem. 

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

**Comment by juliusmarminge** [comment]
Please provide a real reproduction repo. The Quickstart does work so it must be some issue on your end setting up the monorepo.

A common pitfall is that your server and client "must" use the same trpc versions

**Comment by KATT** [comment]
Feel free to reopen with a reproduction repo

**Comment by sooohka** [comment]
same

**Comment by rolivegab** [comment]
having the same issue

**Comment by talksik** [comment]
thank you! the problem is resolved! updating version to be same across client and server fixed it! appreciate it! 🙏🏾
