### ISSUE TITLE
bug: React Native Pod Install Error

### ISSUE THREAD

**Issue by wasurocks** [trpc/trpc#3662]
### Provide environment information

**Environment Information**
System:
    OS: macOS 13.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 79.61 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.4.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 9.2.0 - /opt/homebrew/bin/npm
    Watchman: 2023.01.16.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 109.0.5414.87
    Firefox Developer Edition: 110.0
    Safari: 16.2
  npmPackages:
    typescript: ^4.4.4 => 4.7.4 

### Describe the bug

When running `npx pod-install` in a React Native project, this error is obtained:

`[!] Invalid `Podfile` file: 783: unexpected token at 'Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './package.json' is not defined by "exports"`

### Link to reproduction

- (inside a private repository / I'll try to edit with a link)

### To reproduce

Simple try and install pods with the `@trpc/client` or `@trpc/server` or `@trpc/react-query` libraries installed inside a React Native application

### Additional information

I've found that this can be fixed by adding `"./package.json": "./package.json"` in the `package.json` file for each package: `client`, `react-query`, `server` within the `@trpc` package.

I'm doing this inside a monorepo managed by Yarn workspaces.

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

**Comment by juliusmarminge** [comment]
See https://github.com/t3-oss/create-t3-turbo for a working setup.

Expo has some issues so you need to patch React Native, not an issue in tRPC

**Comment by wasurocks** [comment]
> See https://github.com/t3-oss/create-t3-turbo for a working setup.
> 
> Expo has some issues so you need to patch React Native, not an issue in tRPC

Hi, thanks for the reply. I'm not using Expo, however, so the template would be different since I'm using pure RN. I have seen the template before but I did not use it since it was coupling RN with expo.
