### ISSUE TITLE
bug: getQueryKey returns incorrect key

### ISSUE THREAD

**Issue by StireArLankar** [trpc/trpc#3677]
### Provide environment information

```
  System:
    OS: Linux 5.15 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (2) x64 AMD EPYC
    Memory: 2.03 GB / 3.84 GB
    Container: Yes
    Shell: 5.1.4 - /bin/bash
  Binaries:
    Node: 16.17.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.15.0 - /usr/local/bin/npm
    Watchman: 20220528.183901.0 - /usr/local/bin/watchman
  npmPackages:
    @tanstack/react-query: ^4.3.8 => 4.23.0 
    @trpc/client: ^10.9.0 => 10.9.0 
    @trpc/next: ^10.9.0 => 10.9.0 
    @trpc/react-query: ^10.9.0 => 10.9.0 
    @trpc/server: ^10.9.0 => 10.9.0 
    next: ^13.0.0 => 13.1.5 
    react: ^18.2.0 => 18.2.0 
    typescript: ^4.8.3 => 4.9.4 
```

### Describe the bug

getQueryKey returns incorrect key - correct one has `type` in it, while result of getQueryKey doesn't

### Link to reproduction

https://codesandbox.io/p/sandbox/admiring-cache-yg243i?file=%2Fsrc%2Fpages%2F%5Bfilter%5D.tsx&selection=%5B%7B"endColumn"%3A26%2C"endLineNumber"%3A26%2C"startColumn"%3A26%2C"startLineNumber"%3A26%7D%5D

### To reproduce

click on `not working` (which uses the result of getQueryKey(...))
data is added to cache, but because key is incorrect component still has old data

click on `working` (where key is modified with `type = 'query'`)
component gets correct data

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

**Comment by juliusmarminge** [comment]
That's cause the default `type` is `any`. You need to state what type you want:

```ts
  const queryKey = trpc.hello.getQueryKey({ id: "123" }, "query");
```

returns the correct key for your usage
