### ISSUE TITLE
docs: what about introduce `typia` like `zod` and `yup`?

### ISSUE THREAD

**Issue by samchon** [trpc/trpc#3680]
```typescript
// RUNTIME VALIDATORS
export function is<T>(input: unknown | T): input is T; // returns boolean
export function assert<T>(input: unknown | T): T; // throws TypeGuardError
export function validate<T>(input: unknown | T): IValidation<T>; // detailed
    // +) createIs, createAssert, createValidate
    // do not allow superfluous propertes

// JSON
export function application<T>(): IJsonApplication; // JSON schema
export function assertParse<T>(input: string): T; // type safe parser
export function assertStringify<T>(input: T): string; // safe and faster
    // +) isParse, validateParse 
    // +) stringify, isStringify, validateStringify

// PROTOCOL BUFFER -> NOT PUBLISHED YET, BUT SOON
export function message<T>(): string; // Protocol Buffer message
export function assertDecode<T>(buffer: Buffer): T; // safe decoder
export function assertEncode<T>(input: T): Uint8Array; // safe encoder
    // +) decode, isDecode, validateDecode
    // +) encode, isEncode, validateEncode
```

Hello, I am developer of [typia](https://github.com/samchon/typia) and hope `trpc` to introduce it.

[typia](https://github.com/samchon/typia) is a runtime validator library that can use pure TypeScript type. Therefore, it requires **only one line** and do not need any extra schema definition (`zod` case) or class definition with decorator function calls (`class-validator` case) like above.

Also, as it performs AOT (Ahead of Time) compilation skill, its validation speed is much faster than `zod`. Furthermore, as I've studied TypeScript type specs and compiler API for a long time, it can validate every TypeScript type.

Moreover, if `trpc` adapts this [typia](https://github.com/samchon/typia), it would possible to support Protocol Buffer with minimum effort in near future.

![Is Function Benchmark](https://github.com/samchon/typia/raw/master/benchmark/results/11th%20Gen%20Intel(R)%20Core(TM)%20i5-1135G7%20%40%202.40GHz/images/is.svg)

> Measured on [Intel i5-1135g7, Surface Pro 8](https://github.com/samchon/typia/tree/master/benchmark/results/11th%20Gen%20Intel(R)%20Core(TM)%20i5-1135G7%20%40%202.40GHz#is)
>
> [typia](https://github.com/samchon/typia) is much faster than other validator libraries.

Components               | [typia](https://github.com/samchon/typia) | `TypeBox` | `ajv` | `io-ts` | `zod` | `C.V.`
-------------------------|--------|-----------|-------|---------|-------|------------------
**Easy to use**          | ✅ | ❌ | ❌ | ❌ | ❌ | ❌ 
[Object (simple)](https://github.com/samchon/typia/blob/master/test/structures/ObjectSimple.ts)          | ✔ | ✔ | ✔ | ✔ | ✔ | ✔
[Object (hierarchical)](https://github.com/samchon/typia/blob/master/test/structures/ObjectHierarchical.ts)    | ✔ | ✔ | ✔ | ✔ | ✔ | ✔
[Object (recursive)](https://github.com/samchon/typia/blob/master/test/structures/ObjectRecursive.ts)       | ✔ | ❌ | ✔ | ✔ | ✔ | ✔ | ✔
[Object (union, implicit)](https://github.com/samchon/typia/blob/master/test/structures/ObjectUnionImplicit.ts) | ✅ | ❌ | ❌ | ❌ | ❌ | ❌
[Object (union, explicit)](https://github.com/samchon/typia/blob/master/test/structures/ObjectUnionExplicit.ts) | ✔ | ✔ | ✔ | ✔ | ✔ | ❌
[Object (additional tags)](https://github.com/samchon/typia/#comment-tags)        | ✔ | ✔ | ✔ | ✔ | ✔ | ✔
[Object (template literal types)](https://github.com/samchon/typia/blob/master/test/structures/TemplateUnion.ts) | ✔ | ✔ | ✔ | ❌ | ❌ | ❌
[Object (dynamic properties)](https://github.com/samchon/typia/blob/master/test/structures/DynamicTemplate.ts) | ✔ | ✔ | ✔ | ❌ | ❌ | ❌
[Array (rest tuple)](https://github.com/samchon/typia/blob/master/test/structures/TupleRestAtomic.ts) | ✅ | ❌ | ❌ | ❌ | ❌ | ❌
[Array (hierarchical)](https://github.com/samchon/typia/blob/master/test/structures/ArrayHierarchical.ts)     | ✔ | ✔ | ✔ | ✔ | ✔ | ✔
[Array (recursive)](https://github.com/samchon/typia/blob/master/test/structures/ArrayRecursive.ts)        | ✔ | ✔ | ✔ | ✔ | ✔ | ❌
[Array (recursive, union)](https://github.com/samchon/typia/blob/master/test/structures/ArrayRecursiveUnionExplicit.ts) | ✔ | ✔ | ❌ | ✔ | ✔ | ❌
[Array (R+U, implicit)](https://github.com/samchon/typia/blob/master/test/structures/ArrayRecursiveUnionImplicit.ts)    | ✅ | ❌ | ❌ | ❌ | ❌ | ❌
[**Ultimate Union Type**](https://github.com/samchon/typia/blob/master/src/schemas/IJsonSchema.ts)  | ✅ | ❌ | ❌ | ❌ | ❌ | ❌

> [typia](https://github.com/samchon/typia) can validate every TypeScript type.

Here is an example code utilizing [typia](https://github.com/samchon/typia) in `trpc`. 

Just by writing `typia.createAssert<T>()` code, everything works fine.

How about introducing [typia](https://github.com/samchon/typia) like `zod` and `yup`? It would be honor for me that if [typia](https://github.com/samchon/typia) being introduced in main README content, but I may just satisfies that [typia](https://github.com/samchon/typia) being introduced in `trpc`'s somewhere documents.

```typescript
import { initTRPC } from "@trpc/server";
import { v4 } from "uuid";
import typia from "typia";

interface IBbsArticle {
    id: string;
    writer: IBbsArticle.IWriter;
    title: string;
    body: string;
    created_at: string;
}
namespace IBbsArticle {
    export interface IStore {
        writer: IWriter;
        title: string;
        body: string;
        /**
         * @minLength 4
         * @maxLength 16
         * @pattern ^[a-zA-Z0-9]+$
         */
        password: string;
    }
    export interface IWriter {
        /**
         * @format uuid
         */
        external_service_id?: string;
        /**
         * @format email
         */
        email: string;
    }
}

const t = initTRPC.create();

export const appRouter = t.router({
    store: t.procedure
        .input(typia.createAssert<IBbsArticle.IStore>())
        .output(typia.createAssert<IBbsArticle>())
        .query(({ input }) => {
            return {
                id: v4(),
                writer: input.writer,
                title: input.title,
                body: input.body,
                created_at: new Date().toString(),
            };
        })
});
export type AppRouter = typeof appRouter;
```

**Comment by sachinraja** [comment]
Since this already works out of the box, I don't think we should include it in the docs. We don't have the ability to test that typia actually works on each change either (precisely since it's AOT compiled).

**Comment by samchon** [comment]
@sachinraja 

`typia` guarantees exact type validation works through thousands of test functions.

Below link can be persuadable?

https://github.com/samchon/typia/actions/runs/4005972939/jobs/6876963436#step:8:2429

**Comment by sachinraja** [comment]
I understand but if we were to include it in the docs, we should at least be able to ensure it works correctly here. I also want to limit the amount of information we have to maintain in the docs.

**Comment by samchon** [comment]
OK, then sending a PR on documents would vulnerable.

**Comment by sachinraja** [comment]
Can you clarify? Not sure what you mean.

**Comment by samchon** [comment]
Just hoped to send a PR adding `typia` in validation section and I mean that sending the PR would be vulnerable because you don't have plan to add more validator in the doucments.

![image](https://user-images.githubusercontent.com/13158709/215650065-7b5287a4-32e4-42a8-8c09-fda735bcc451.png)

**Comment by sachinraja** [comment]
Oh, that's right, yeah sorry I don't think we should include more validators. Closing this now.
