### ISSUE TITLE
docs: some links are not working

### ISSUE THREAD

**Issue by pencilcheck** [trpc/trpc#3681]
### Area of Improvement

https://trpc.io/docs/useQuery

The link to tanstack use query has been returning 404

The old link right now:
[queries](https://react-query.tanstack.com/guides/queries)

The new link (I think):
https://tanstack.com/query/latest/docs/react/guides/queries

### Link to related docs

https://trpc.io/docs/useQuery

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing the suggested changes!

**Comment by juliusmarminge** [comment]
both above link works for me?

**Comment by Neilblaze** [comment]
Yep, it's working for me too!
