### ISSUE TITLE
docs: Add commentary on how to configure global react-query options

### ISSUE THREAD

**Issue by crrobinson14** [trpc/trpc#3684]
### Area of Improvement

I struggled with figuring out how to adjust global `react-query` options, and I think it's because the answer seems fairly obvious on one page of the docs, but it isn't explicitly mentioned as such so it's hard to "search" for.

In https://trpc.io/docs/react#3-add-trpc-providers there is a line where the app is making the queryClient that trpcClient then uses. I had mistakenly assumed this would be done somewhere in the call to `createTRPCReact()` and since most of the installation docs are copy/paste work done and then probably forgotten in the excitement to try out the shiny new thing, it's an easy detail to miss that the app is still creating the queryClient explicitly and thus has direct control over it.

I searched both the docs and Github issues for terms like "global query client config", params like "retry" and "refetchOnWindowFocus" and wasn't finding anything. This suggestion is to add a FAQ section under https://trpc.io/docs/faq that mentions a few extra searchable keywords, because it's natural to reach for these "FAQ/Cookbook" sections of the docs when researching an answer to things like this in a project that has already had tRPC installed for some time.

I would be happy to write a paragraph or two on this but when I reviewed https://github.com/trpc/trpc/blob/main/CONTRIBUTING.md it wasn't obvious to me how to make a documentation contribution.

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR implementing the suggested changes!

<sub>[TRP-50](https://linear.app/trpc/issue/TRP-50/docs-add-commentary-on-how-to-configure-global-react-query-options)</sub>

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/3684">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/3684/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/3684/pledge.svg">
</picture>
</a>

**Comment by sachinraja** [comment]
Feel free to do a PR! Here are the steps to update the docs:
1. fork the repo
2. clone the fork
3. checkout a branch
4. open the `www/docs/further/faq.mdx`
5. edit the file
6. push your changes
7. create a PR
