### ISSUE TITLE
feat: Add ability to call tRPC routes from native Swift code

### ISSUE THREAD

**Issue by nikitavoloboev** [trpc/trpc#3690]
### Describe the feature you'd like to request

I started using tRPC recently and love it. 

However I have a native Swift iOS app (not React Native) and I would love to reuse tRPC routes I have inside the Swift code.

Is this possible to do? Perhaps via an adapter or OpenAPI schema?

Thank you lots.

### Describe the solution you'd like to see

Be able to call into RPC routes I create with tRPC from my Swift iOS app.

### Describe alternate solutions

The only alternate solution which I truly dislike is to recreate all the tRPC routes I need for iOS app via a regular endpoint served somewhere. Or drop tRPC all together to not duplicate routes..

**Comment by juliusmarminge** [comment]
see https://github.com/jlalmes/trpc-openapi
