### ISSUE TITLE
bug: overwrite fetch and call response.json() will generate duplicate requests

### ISSUE THREAD

**Issue by septem1997** [trpc/trpc#3694]
### Provide environment information

```
  System:
    OS: macOS 13.0
    CPU: (8) arm64 Apple M1
    Memory: 55.31 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.1.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /opt/homebrew/bin/yarn
    npm: 9.3.0 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 109.0.5414.119
    Firefox: 108.0.2
    Safari: 16.1
  npmPackages:
    @tanstack/react-query: ^4.3.8 => 4.23.0 
    @trpc/client: ^10.9.0 => 10.9.0 
    @trpc/next: ^10.9.0 => 10.9.0 
    @trpc/react-query: ^10.9.0 => 10.9.0 
    @trpc/server: ^10.9.0 => 10.9.0 
    next: ^13.0.0 => 13.1.6 
    react: ^18.2.0 => 18.2.0 
    typescript: ^4.8.3 => 4.9.4 

```

### Describe the bug

I overwrite fetch like this:
``` javascript
config() {
    return {
      links: [
        httpBatchLink({
          url: `${getBaseUrl()}/api/trpc`,
          fetch:async (url, options) => {
            const res = await fetch(url, options)
            // call res.json() will generate duplicate requests
            res.json()
            return res;
          }
        }),
      ],
    };
  },
```

but if i call response.json(), it will generate duplicate requests

### Link to reproduction

https://codesandbox.io/p/sandbox/blissful-bogdan-nhspjn?file=%2Fsrc%2Futils%2Ftrpc.ts&selection=%5B%7B%22endColumn%22%3A24%2C%22endLineNumber%22%3A57%2C%22startColumn%22%3A24%2C%22startLineNumber%22%3A57%7D%5D

### To reproduce

I modified the Next.js Todo MVC example:
<img width="1798" alt="image" src="https://user-images.githubusercontent.com/13849245/215450891-aa6d599e-7dae-4396-bd9c-7e6d5594abf2.png">

click input and you will see 4 network request

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

**Comment by sachinraja** [comment]
why are you calling res.json?

**Comment by septem1997** [comment]
> why are you calling res.json()? I think it's doing another request because there was an error trying to parse the json from the request (we call `res.json()` inside the client too).

ok, now i found the reason, the body stream already read, maybe i can use `res.clone().json()` instead, thx bro
