### ISSUE TITLE
bug: zod schema exported from same file as tRPC router cause runtime error

### ISSUE THREAD

**Issue by c-ehrlich** [trpc/trpc#3712]
### Provide environment information

```
  System:
    OS: macOS 13.0.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 1.41 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.12.0 - ~/.nvm/versions/node/v18.12.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.12.0/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.0/bin/npm
  Browsers:
    Chrome: 109.0.5414.119
    Firefox: 109.0
    Safari: 16.1
  npmPackages:
    @tanstack/react-query: ^4.20.0 => 4.24.4
    @trpc/client: ^10.9.0 => 10.9.1
    @trpc/next: ^10.9.0 => 10.9.1
    @trpc/react-query: ^10.9.0 => 10.9.1
    @trpc/server: ^10.9.0 => 10.9.1
    next: 13.1.6 => 13.1.6
    react: 18.2.0 => 18.2.0
    typescript: ^4.9.4 => 4.9.5
```

### Describe the bug

When importing zod schema on the client that are exported from the same file as a tRPC router in the backend, a runtime error occurs:

```
Unhandled Runtime Error
Error: You're trying to use @trpc/server in a non-server environment. This is not supported by default.
```

<img width="1460" alt="image" src="https://user-images.githubusercontent.com/8353666/216389364-7f69d2d9-6d62-4a24-a9f4-87fab817935d.png">

### Link to reproduction

https://github.com/c-ehrlich/zod-import-bug

### To reproduce

Either see reproduction repo and:
- `pnpm i`, `pnpm dev`
- visit a working page, where the zod schema is exported from its own file: `http://localhost:3000/working`
- visit a broken page, where the zod schema is exported from the same file as a tRPC router: `http://localhost:3000/broken`

Or:

- export a zod schema and a tRPC router from the same file
- import the zod schema in the frontend and use it in a React component

### Additional information

I assume this is because if you follow the imports for creating a router, you end up at `initTRPC`? Not sure if this is a "bug" that can be solved or just a fact of how imports work, but wanted to raise this as I generally encourage people to put everything related to a route/procedure in the same file

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

**Comment by KATT** [comment]
This is intended behaviour, you can't `import` from the server on the client, that is very dangerous. Other tools that rely on transpilers to work can do this somewhat safely but don't do this in trpc.

Either have a shared directory with schemas or import from the client on the server.
