### ISSUE TITLE
bug: HttpBatchLink and Link undefined headers 

### ISSUE THREAD

**Issue by stychu** [trpc/trpc#3713]
### Provide environment information

```

  System:
    OS: macOS 11.7
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 769.95 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.21.2 - ~/Library/pnpm/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 6.14.17 - ~/Library/pnpm/npm
  Browsers:
    Brave Browser: 109.1.47.186
    Chrome: 109.0.5414.119
    Firefox: 109.0
    Safari: 15.6.1
  npmPackages:
    @tanstack/react-query: ^4.20.0 => 4.22.0 
    @trpc/client: ^10.8.1 => 10.8.1 
    @trpc/next: ^10.8.1 => 10.8.1 
    @trpc/react-query: ^10.8.1 => 10.8.1 
    @trpc/server: ^10.8.1 => 10.8.1 
    next: 13.1.1 => 13.1.1 
    react: 18.2.0 => 18.2.0 
    typescript: ^4.9.4 => 4.9.4 

```

### Describe the bug

Providing headers to the HttpBatchLink or Link with the value of `undefined` results with sending such headers as `'undefined'` strings values.

Instead they should be completely omitted if the value of the header is `undefined`

```js
//client
httpBatchLink({
          url: `${getBaseUrl()}/api/trpc`,
          headers: {
            'x-test1': undefined,
            test2: undefined
          }
        }),
```

```js
//server
  'x-test1': 'undefined',
  test2: 'undefined',
```

### Link to reproduction

...

### To reproduce

Define headers for batchlink for example with `undefined` values. See on the server they are being sent with values as strings.

```js
//client
httpBatchLink({
          url: `${getBaseUrl()}/api/trpc`,
          headers: {
            'x-test1': undefined,
            test2: undefined
          }
        }),
```

```js
//server
  'x-test1': 'undefined',
  test2: 'undefined',
```

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

**Comment by KATT** [comment]
> cc @stychu unsure if we _should_ fix this. It works the same as `fetch()`, we just forward whatever you send:
> 
> https://github.com/trpc/trpc/blob/2832ee17f4c7ce0d9d23b3a25b71fdcf7c329f7b/packages/client/src/links/internals/httpUtils.ts#L141-L144
> 
> WDYT?
> 
> _Originally posted by @KATT in https://github.com/trpc/trpc/issues/3730#issuecomment-1419507785_
>

**Comment by stychu** [comment]
I've verified this and all seems good. Current behaviour is valid. So lets close this and drop the idea
