### ISSUE TITLE
bug: TRPC client cannot build correctly

### ISSUE THREAD

**Issue by Alivers** [trpc/trpc#3740]
### Provide environment information

 System:
    OS: macOS 13.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 119.34 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.12.1/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
  Browsers:
    Chrome: 109.0.5414.119
    Safari: 16.2
  npmPackages:
    @trpc/client: ^10.10.0 => 10.10.0 
    @trpc/server: ^10.10.0 => 10.10.0 
    typescript: ^4.3.5 => 4.7.4 

### Describe the bug

TRPC client cannot build correctly. Build process exit with: 

```bash
src/index.ts(4,14): error TS4023: Exported variable 'getClient' has or is using name 'SerializeObject' from external module "/Users/aliver/workspace/repo/api-service/node_modules/.pnpm/@trpc+server@10.10.0/node_modules/@trpc/server/dist/shared/internal/serialize" but cannot be named.
```

### Link to reproduction

https://stackblitz.com/github/trpc/examples-next-minimal-starter

### To reproduce

This is my code.
```ts
import { type AppRouter } from './routers';
import { createTRPCProxyClient, httpLink } from '@trpc/client';

export const getClient = (url: string) =>
  createTRPCProxyClient<AppRouter>({
    links: [httpLink({ url })],
  });

```

### Additional information

trpc version:  v10.10.0

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

**Comment by WilliamWelsh** [comment]
Try renaming `getClient` to something else

**Comment by KATT** [comment]
Re-open with an actual reproduction
