### ISSUE TITLE
feat: `postMessage` tRPC to communicate between `iframe`s/tabs

### ISSUE THREAD

**Issue by KATT** [trpc/trpc#3752]
### Describe the feature you'd like to request

Sometimes you gotta do `<iframe/>`s for stuff. Sometimes you need to communicate with those iframes.

Would be cool if tRPC could use [`postMessage`](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage)

It would also allow you to communicate between different tabs or windows which maybe could be useful for some cases(?)

### Describe the solution you'd like to see

- `@trpc/adapters/postMessage` (or a third party package) to create tRPC server in the browser
- A `@trpc/client` link that can communicate over `postMessage`

### Describe alternate solutions

Not doing it

### Additional information

Prior art:

- https://github.com/microsoft/postmessage-rpc
- https://github.com/DirtyHairy/worker-rpc

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

**Comment by AlexErrant** [comment]
I use [Comlink](https://github.com/GoogleChromeLabs/comlink) for communication with iframes (also service workers and web workers). It has pretty good cross-boundary type-safety without using runtime checks like Zod. [Penpal](https://github.com/Aaronius/penpal) and [Postmate](https://github.com/dollarshaveclub/postmate) also exist, though I've not used them.

**Comment by KATT** [comment]
I probably won't work on this unless there's a need. At work, we managed to do an event bus using superjson+zod that works well
