### ISSUE TITLE
feat: support merge more than 19 routers

### ISSUE THREAD

**Issue by Abdulrahmanelheyb** [trpc/trpc#3753]
### Describe the feature you'd like to request

Hi I started to use tRPC in today and i looked at to merge routers i saw the merge function can get only 19 router object I think to need we increase this number for merge more routers

### Describe the solution you'd like to see

null

### Describe alternate solutions

null

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

**Comment by KATT** [comment]
There's no hard limit?

**Comment by KATT** [comment]
Are you using `.mergeRouters`? That was mainly designed for interop mode, but maybe we can make it recursive

**Comment by Abdulrahmanelheyb** [comment]
> Are you using `.mergeRouters`? That was mainly designed for interop mode, but maybe we can make it recursive 

Yes I am using .mergeRouters function

**Comment by divmgl** [comment]
Hi, I'm sorry, why is this closed? My team is currently running into this when using `t.mergeRouters`.

Should we at least document this caveat in the docs? Just a small warning that says "only 20 routers supported"? Or is there a different `mergeRouters` we're supposed to use?

**Comment by Abdulrahmanelheyb** [comment]
Thanks for the quick response, Your team closed for other reasons I don't
but anyway, the t.mergeRouters currently support 19 routers max to merge

**Comment by sachinraja** [comment]
Currently it supports as many routers as you want. The issue was closed precisely because of that change.

**Comment by KATT** [comment]
https://github.com/trpc/trpc/releases/tag/v10.11.0
