### ISSUE TITLE
feat: next redirect response

### ISSUE THREAD

**Issue by barrybtw** [trpc/trpc#3764]
### Describe the feature you'd like to request

An ability to redirect the user based on the answer, somewhat similar to NextResponse.redirect.

### Describe the solution you'd like to see

Say you want to redirect the user if they are logged in, and you want to do so through the response and not through checking the response on the client. You would somehow just be able to return a redirect order or something.

### Describe alternate solutions

I have seen the usage of Next.js middleware on Stackoverflow by @c-ehrlich 
https://stackoverflow.com/a/75419813/17695482

But a built in tRPC/next solution would be handy. 

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

**Comment by iduuck** [comment]
What is your proposed way? Having some sort of data that is returning a `redirect` and then the client is fetching this, and automatically redirecting? Or what is your goal with this issue?

**Comment by huzaifahj** [comment]
> Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client

@radeon8 or anyone else, have you found a solution to the above?

**Comment by radeon8** [comment]
> procdure.query({ctx: { res }} => {
>     res.redirect('xxx')
> })

Yes, when I have to use REDIRECT, I found 2 methods
1. just write a router in expressjs (you can write createCaller the tRPC router if needed)
2. client redirect (recommended)

**Comment by sachinraja** [comment]
I believe you can also set the header `'Location': 'your/path'`
