### ISSUE TITLE
Cannot read properties of undefined, res.error.data inside @trpc/server

### ISSUE THREAD

**Issue by Nikola-Milovic** [trpc/trpc#3772]
### Provide environment information

```
  System:
    OS: Linux 5.15 Ubuntu 20.04.5 LTS (Focal Fossa)
    CPU: (16) x64 AMD Ryzen 7 2700 Eight-Core Processor
    Memory: 7.22 GB / 31.30 GB
    Container: Yes
    Shell: 5.0.17 - /usr/bin/bash
  Binaries:
    Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
    Yarn: 1.22.19 - /monorepo/node_modules/.bin/yarn
    npm: 8.16.0 - /monorepo/node_modules/.bin/npm
  Browsers:
    Brave Browser: 107.1.45.118
    Chrome: 107.0.5304.87
    Chromium: 109.0.5414.119
    Firefox: 109.0
```

### Describe the bug

Migrating a large project from plain express server and nextjs frontend to trpc, I first started with a single route and when trying to test it out and send a request, I am getting this error, it's basically thrown from the Zod, and when it's caught we crash because internally `tRPC` looks for `res.error.data` which isn't present

```
 debug:   Server listening on port: 3000 at development mode
 error:   ERROR OCCURED: '[\n' +
   '  {\n' +
   '    "code": "invalid_type",\n' +
   '    "expected": "object",\n' +
   '    "received": "undefined",\n' +
   '    "path": [],\n' +
   '    "message": "Required"\n' +
   '  }\n' +
   ']'
 error:   ERROR OCCURED: "Cannot read properties of undefined (reading 'data')"
 /work/company/monorepo/node_modules/@trpc/server/dist/config-200d5226.js:63
             const data = res.error.data;
                                    ^

 TypeError: Cannot read properties of undefined (reading 'data')
     at /work/company/monorepo/node_modules/@trpc/server/dist/config-200d5226.js:63:36
     at Array.map (<anonymous>)
     at Object.getHTTPStatusCode (/work/company/monorepo/node_modules/@trpc/server/dist/config-200d5226.js:61:38)
     at endResponse (/work/company/monorepo/node_modules/@trpc/server/dist/resolveHTTPResponse-e94bc3b5.js:46:29)
     at Object.resolveHTTPResponse (/work/company/monorepo/node_modules/@trpc/server/dist/resolveHTTPResponse-e94bc3b5.js:194:16)
     at processTicksAndRejections (node:internal/process/task_queues:96:5)
     at async Object.nodeHTTPRequestHandler (/work/company/monorepo/node_modules/@trpc/server/dist/nodeHTTPRequestHandler-b0d356ac.js:52:20)
     at async /work/company/monorepo/node_modules/@trpc/server/dist/adapters/express.js:16:9
 [nodemon] app crashed - waiting for file changes before starting...
```

### Link to reproduction

https://github.com/Nikola-Milovic/trpc-reproduction

#### Setup
```
yarn install
yarn build
yarn dev
```

#### Try it out

Navigate to `localhost:3005` and look at the logs from the backend (in the terminal), it should error out and crash

### Additional information

I have a big project that's migrating to `tRPC` so I tried to have the same setup in the repository I created to reproduce the problem. To reproduce it, I am manually throwing a `tRPC` error 

I am not sure that this is a bug, might be a misunderstanding of `tRPC` errors on my end

The query is from the [throw example from the docs](https://trpc.io/docs/error-handling#throwing-errors) 
```
const appRouter = trpc.router({
    hello: trpc.procedure.query(() => {
        throw new TRPCError({
            code: 'INTERNAL_SERVER_ERROR',
            message: 'An unexpected error occurred, please try again later.',
        });
    }),
});
```

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

**Comment by iduuck** [comment]
After investigating in your repository for some time (thought this would be an issue with the error formatter), I found out, that you have a custom `errorFormatter` function defined.

This function needs to return something actually. Because you are only `console.log`ing, it is returning `void`/`undefined` and breaking the error reporting on the server.

**Comment by Nikola-Milovic** [comment]
@iduuck Thank you for investigating it.

Thankfully it's an easy fix! You can close this issue if it's not relevant anymore
