### ISSUE TITLE
Use different transformers for client<->server

### ISSUE THREAD

**Issue by simonedelmann** [trpc/trpc#378]
First of all I want to say thank you very much for making this library! I was already looking for a library like this for quite some time. 

There is one thing I would like to ask/suggest:

Superjson is great for preserving type information, but has some performance drops for example when using with lots of nested dates. There is another library, devalue, which has a much better performance, but it is not usably for client->server for security reasons. 

Thats why I currently use superjson for client->server and devalue for server->client in some of my apps.

Is it currently possible to use different transformers for each direction? If not, I would like to suggest adding this.

**Comment by KATT** [comment]
Hmm.. there is no such option right now, and I'd be hesitant to build it as it feels a bit like a can of worms to differentiate this in each direction and a bit fiddly to add. If devalue can't be used for serialization from client->server you'd still have the same bottleneck when passing input args from client->server, although they are indeed usually much smaller.

Are you sure you're not doing premature optimization? Is the superjson really _that_ slow?

I do find superjson a bit overkill myself as I only really care about dates and nothing else (and I find date objects a bit annoying as well as equality checks on two different dates - maybe write your own lib called `jsonplusdates`? 


https://github.com/trpc/trpc/blob/8628cb5876a148595935580468f7d9ef8c7cfee3/packages/server/src/transformer.ts#L3-L6

**Comment by simonedelmann** [comment]
Thanks for your very fast answer! I totally see adding this as an option could be difficult.

> Are you sure you're not doing premature optimization? Is the superjson really that slow?

This only occurs in one specific app, where I have a structure like this:
```
```

**Comment by simonedelmann** [comment]
Thanks for your very fast answer! I totally see adding this as an option could be difficult and I absolutely agree that dates are annoying. :D

> Are you sure you're not doing premature optimization? Is the superjson really that slow?

This only occurs in one specific app, where I have a huge collection (~1000) of models and every model contains another collection of models (~50). All models need to have multiple dates. Yes, I could do some optimization (strip non-necessary updatedAt field for example), but still the conversion with superjson would take >300ms.

I made a short test with the benchmark script provided by superjson:

```
Serializing + deserializing a nested object with 50.000 dates

Superjson took 482 ms
Devalue took 70 ms
```

So superjson is not that slow, but devalue still is much faster and in my case I would like to use that extra performance.

Would it take a big effort to modify the transformer interface like this? This should not break any existing implementation.

```ts
export type DataTransformer = {
    serialize(object: any, direction: 'up' | 'down'): any;
    deserialize(object: any, direction: 'up' | 'down'): any;  
}; 
```

PS: Sorry for submitting the comment to early...

**Comment by KATT** [comment]
I was thinking something like this to avoid breaking change

```
export type DataTransformer = {
    serialize(object: any): any;
    deserialize(object: any): any;  
};

export type DataTransformerOption = DataTransformer | { up: DataTransformer, down: DataTransformer }
```

I don't really have time to do this + the tests required, I'd be open to merging it if you could figure it out? I'd open VSCode & search for everywhere in the project where the keyword "transformer" is used and start hacking

**Comment by KATT** [comment]
# Development workflow

```bash
git clone git@github.com:trpc/trpc.git
cd trpc
yarn
```

## Hacking around with it


In one terminal, will run `preconstruct watch` in parallel which builds all `packages/*` on change:

```bash
yarn dev
```

In another terminal, you can for instance navigate to `examples/next-hello-world` and run `yarn dev` & it will update whenever code is changed in the packages.


## Testing

```bash
cd packages/server
yarn test --watch
```

**Comment by simonedelmann** [comment]
Thank you! I will have a look and try to implement that! Probably taking some days playing around with the library first.
