### ISSUE TITLE
docs: trpc server can be run in a browser

### ISSUE THREAD

**Issue by gotjoshua** [trpc/trpc#3781]
### Area of Improvement

It is mentioned that [a trpc server can be run in a browser here](https://github.com/trpc/trpc/blame/main/www/docs/server/adapter/fetch.mdx#L82), but i am missing a link to an example.

Does such an example exist?

### Link to related docs

https://trpc.io/docs/fetch#required-web-apis

### Additional information

Closest thing i found:

https://github.com/jlalmes/trpc-chrome

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing the suggested changes!

**Comment by KATT** [comment]
https://trpc.io/docs/router#runtime-configuration
