### ISSUE TITLE
bug: [ESM] The inferred type of 'middleware'/'mergeRouters' cannot be named without a reference to...

### ISSUE THREAD

**Issue by milohansen** [trpc/trpc#3786]
### Provide environment information

System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 12th Gen Intel(R) Core(TM) i5-12600K
    Memory: 13.49 GB / 31.80 GB
  Binaries:
    Node: 18.12.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 3.4.1 - C:\Program Files\nodejs\yarn.CMD
    npm: 9.2.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1105.0), Chromium (109.0.1518.55)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @trpc/client: 10.11.1 => 10.11.1
    @trpc/react-query: 10.11.1 => 10.11.1
    @trpc/server: 10.11.1 => 10.11.1
    typescript: ^4.9.5 => 4.9.5

### Describe the bug

Under `"moduleResolution": "Node16"` (or `"NodeNext"`), compilation of TypeScript types for the router can fail with error

```
The inferred type of 'middleware' cannot be named without a reference to '../../node_modules/@trpc/server/dist/core/middleware.js'. This is likely not portable. A type annotation is necessary.ts(2742)
```

### Link to reproduction

https://stackblitz.com/edit/trpc-export-ts2742

### To reproduce

See repro:
1. Set up package with Typescript
2. Set "moduleResolution": "Node16"
3. Try to compile types, e.g. via tsc --declaration

### Additional information

Related issues:
#1945, #2717, #2994

The issue with `mergeRouters` started in version `10.11.0` but can be worked around by explicitly typing the export.
```typescript
export const mergeRouters = trpc.mergeRouters as <TRouters extends AnyRouter[]>(...routerList: [...TRouters]) => MergeRouters<TRouters>;
```

The internal types for middleware are not all exported (and are significantly more complicated) so work arounds are aggressively hacky and unsustainable.

One additional note is although `router` and `procedure` can be exported here, using them in a generic way causes the same error.

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

**Comment by juliusmarminge** [comment]
I think this should be resolved by https://github.com/trpc/trpc/pull/3774 just needs go get released so watch out for ^10.11.2

**Comment by KATT** [comment]
This should be resolved by #3774 and we added a test in #3789 to make sure this doesn't happen in the future.

@milohansen can you confirm it's fixed in the latest release `10.12.0`?

**Comment by KATT** [comment]
Updated to `10.12.0` in the stackblitz and it seems to be working: https://stackblitz.com/edit/trpc-export-ts2742-756mzd

**Comment by milohansen** [comment]
@KATT Thanks for the fix! I'm able to export both `middleware` and `mergeRouters` without a problem now.

However, there's one catch.

In #3789 `Overwrite` is no longer exported and as a result routers that use middleware break with the same TS2742 error.

Here's a stackblitz with a repro: https://stackblitz.com/edit/trpc-export-ts2742-jdz415?file=index.ts&view=editor
