### ISSUE TITLE
feat: Route and globally based rate limit

### ISSUE THREAD

**Issue by chrxmvtik** [trpc/trpc#3788]
### Describe the feature you'd like to request

Hi guys 'n' gals,

Whilist moving from Express you can encounter lack of rate limit support in tRPC routes.

It would be nice if you could set rate limit per route and globally natively in tRPC

### Describe the solution you'd like to see

Example of implementation:

```typescript
const routes = router({
  getItems: publicProcedure
    .limit({
       windowMs: 15 * 60 * 1000,
       max: 15,
       message: 'Too many requests from this IP, please try again after 15 minutes.',
       standardHeaders: true, // Return rate limit info in the `RateLimit-*` headers
       legacyHeaders: false, // Disable the `X-RateLimit-*` headers
     })
    .input({...})
    .query({...})
})
```

### Describe alternate solutions

There are no alternate solutions so far.

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

**Comment by juliusmarminge** [comment]
See #3227

**Comment by iduuck** [comment]
This could happen through `meta`, isn't it, @juliusmarminge? You could write some sort of middleware, and then when a meta field exists, just add a rate-limiter of your choice.

**Comment by juliusmarminge** [comment]
> This could happen through `meta`, isn't it, @juliusmarminge? You could write some sort of middleware, and then when a meta field exists, just add a rate-limiter of your choice.

Seems like the lib has been updated since i last saw it and do support per-route limiting

**Comment by sachinraja** [comment]
please continue any other discussion in #3227
