### ISSUE TITLE
docs: Custom Headers `token` example produces TypeScript error

### ISSUE THREAD

**Issue by chammaaomar** [trpc/trpc#3835]
### Area of Improvement

In the [v.10 docs section on Custom Headers](https://trpc.io/docs/header), the following example is suggested for sending an authorization header from the client:

```typescript
// Import the router type from your server file
import type { AppRouter } from '@/server/routers/app';
import { httpBatchLink } from '@trpc/client';
import { createTRPCNext } from '@trpc/next';

export let token: string;

export const trpc = createTRPCNext<AppRouter>({
  config({ ctx }) {
    return {
      links: [
        httpBatchLink({
          url: 'http://localhost:3000/api/trpc',
          /**
           * Headers will be called on each request.
           */
          headers() {
            return {
              Authorization: token,
            };
          },
        }),
      ],
    };
  },
});
```

It is also suggested that `token` should be imported in another source file, and modified appropriately, as in the following code snippet (taken from the same docs and section)
```typescript
// MY ADDITION: There's an implicit: import { token, trpc } from "utils/trpc.ts"
const loginMut = trpc.auth.login.useMutation({
  onSuccess({ accessToken }) {
    token = accessToken;
  },
});
```
However, when I try to follow the above pattern which involves `import { token } from "utils/trpc.ts"`, I end up with a TypeScript error `Cannot assign to 'token' because it is an import`. So it seems to be a read-only reference. To get around this issue, I exported an object from `utils/trpc.ts`, and then would modify a field on the object, as such:
```typescript
export const headers = { authorization: "" };
```

and then I would be able to modify the `headers.authorization` field in any other source file, as desired. This workaround allows us to modify the authorization header sent from the client.

### Link to related docs

https://trpc.io/docs/header

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR implementing the suggested changes!

**Comment by iduuck** [comment]
You can use a function, which is going to set the variable for you (and additionally you could utilise some sort `js-cookie` to even safe the token in the cookies, and then read the token from this state.

Will update with a PR on this to update the docs.

**Comment by juliusmarminge** [comment]
Here's a hacky implementation of what i think the docs are referring too, although you probably shouldn't: https://codesandbox.io/p/github/trpc/next-minimal-starter/draft/infallible-framework?workspaceId=d25ba8ea-7491-43bd-aa0d-5bf8e6e04f85

**Comment by iduuck** [comment]
@juliusmarminge This sandbox is dead, but I made a PR with a example and the docs updated.

**Comment by juliusmarminge** [comment]
> @juliusmarminge This sandbox is dead, but I made a PR with a example and the docs updated.

Oh god i hate codesandbox....

Here's a stackblitz instead: https://stackblitz.com/edit/github-el6we4?file=src/pages/index.tsx

**Comment by iduuck** [comment]
Yeah, exactly. This is what my example is about.

**Comment by chammaaomar** [comment]
Thank you for taking care of this. I'll follow the example in my own code now!
