### ISSUE TITLE
Log internal server errors during development by default

### ISSUE THREAD

**Issue by kripod** [trpc/trpc#384]
Currently, I’m using the following code snippet for Next.js at the `api/trpc/[trpc]` route:

```ts
import * as trpcNext from "@trpc/server/adapters/next";

const __DEV__ = process.env.NODE_ENV !== "production";

export default trpcNext.createNextApiHandler({
  router: appRouter,
  createContext,
  onError: __DEV__
    ? ({ error, type, path, input }) => {
        if (error.code === "INTERNAL_SERVER_ERROR") {
          // eslint-disable-next-line no-console
          console.error("Error:", {
            type,
            path,
            input,
            cause: error.originalError,
          });
        }
      }
    : undefined,
});
```

I think it would be useful to always log unhandled errors (where `error.code === "INTERNAL_SERVER_ERROR"`) to the server’s console like this during development, even when no `onError` is specified.

**Comment by KATT** [comment]
Why wouldn't you want to do this in prod?

Maybe a default logger for development would be useful - feel free to make a PR!

**Comment by KATT** [comment]
I've added you as a contributor https://github.com/trpc/trpc/invitations

**Comment by kripod** [comment]
> Why wouldn't you want to do this in prod?
> 
> Maybe a default logger for development would be useful - feel free to make a PR!

The reason why I wouldn’t emit messages to the console is that HTTP responses will already have an error code of 500, which Vercel and other logging services keep track of. The message about the error returned in production already contains enough information to investigate on.

I’ll try creating some PRs soon – work makes me pretty busy nowadays, sorry about that.

**Comment by KATT** [comment]
I love that you have so many ideas for improvements, if you need any guidance on how to contribute, let me know!

**Comment by KATT** [comment]
Won't fix this - feel free to open PR
