### ISSUE TITLE
bug: NextJS data not being pre-fetched on server during build time

### ISSUE THREAD

**Issue by thomsocialbrothers** [trpc/trpc#3840]
### Provide environment information

```
  System:
    OS: macOS 13.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 88.39 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.18.1 - ~/.volta/tools/image/node/16.18.1/bin/node
    Yarn: 1.22.19 - ~/.volta/tools/image/yarn/1.22.19/bin/yarn
    npm: 8.19.2 - ~/.volta/tools/image/node/16.18.1/bin/npm
    Watchman: 2022.12.12.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 110.0.5481.100
    Safari: 16.2
  npmPackages:
    @tanstack/react-query: ^4.14.5 => 4.24.6 
    @trpc/client: ^10.5.0 => 10.11.1 
    @trpc/next: ^10.5.0 => 10.11.1 
    @trpc/react-query: ^10.5.0 => 10.11.1 
    @trpc/server: ^10.5.0 => 10.11.1 
    next: 12.3.1 => 12.3.1 
    react: 18.2.0 => 18.2.0 
    typescript: 4.8.3 => 4.8.3 
```

### Describe the bug

Hi there,

We are using tRPC in a NextJS project and so far it has been awesome. We are encountering one issue however, when we tried to add incremental static regeneration (ISR) to our pages. 

We have ssr enabled in our tRPC trpc setup, which should populate all the queries server-side. We also have ISR enabled, and have getStaticProps return an empty props object (We are purely adding getStaticProps for the revalidation of this page). This should result in tRPC's `getInitialProps` handle data-fetching during build time and re-generate that page each time a visitor visits this page and the revalidation time has passed.

The issue now is that the page that is generated during build-time will receive an empty `data` object from tRPC's react-query query.  When the page has been re-generated in the background, the data is correctly filled and the page is shown correctly, even though data fetching during build-time and during regeneration should work identical. It seems like the result of `getInitialProps` is not awaited during build time when `getStaticProps` is present.

I am aware of issue #596, but as far as I understand that only impacts the result of getServerSideProps. We are using getStaticProps, and are returning an empty array there so an undefined return wouldn't make a difference. Also worth mentioning, we are trying to accomplish this without the `ssgHelpers`, since we have quite complicated queries, where we have queries deep inside our component tree that depend on other queries' result. Pre-fetching all of this would include quite some logic. 

### Link to reproduction

https://github.com/thomsocialbrothers/trpc-isr-debug

### To reproduce

1. Run `pnpm run build` 
2. Run `pnpm run start`
3. Visit `http://localhost:3000/`
4. There is no JSON data visible (also not fetched client-side).
5. Refresh the page (re-generation happened in the background due to 1 sec revalidation time)
6. JSON data is visible.

Notes: The data is not re-fetched client-side when the component mounts due to a canceled request. This results in no data being visible at all. Re-focusing the window does re-fetch data.

### Additional information

Our tRPC setup: 

```
import { httpBatchLink, httpLink, splitLink } from '@trpc/client';
import { createTRPCNext } from '@trpc/next';
import SuperJSON from 'superjson';

import type { AppRouter } from '@Server/trpc';

import { getTrpcBaseUrl } from './UrlUtils';

export const trpc = createTRPCNext<AppRouter>({
  config: ({ ctx }) => {
    return {
      transformer: SuperJSON,
      queryClientConfig: {
        defaultOptions: {
          queries: {
            refetchOnWindowFocus: false,
            retry: false
          }
        }
      },
      links: [
        httpBatchLink({
          url: `${getTrpcBaseUrl()}/api/trpc`,
          headers: () => {
            return {
              ...(ctx?.req?.headers || {}),
              ...(ctx?.locale ? { 'x-locale': ctx?.locale } : {}),
              'x-ssr': '1'
            };
          }
        })
      ]
    };
  },
  unstable_overrides: {
    useMutation: {
      async onSuccess(opts) {
        await opts.originalFn();

        opts.queryClient.invalidateQueries([['cart']]);
        opts.queryClient.invalidateQueries([['user']]);
        opts.queryClient.invalidateQueries([['auth']]);
        opts.queryClient.invalidateQueries([['order']]);
      }
    }
  },
  ssr: true
});
```

Our getStaticProps setup:
```
import type { GetStaticProps } from 'next';

import { IS_PREVIEW } from '@Constants/configs';
import { duration } from '@Utils/DateUtils';

export const getStaticProps: GetStaticProps = async () => {
  return {
    props: {},
    revalidate: 1 // For testing
  };
};

export { default } from '@Components/pages/Home/Homepage';
```

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

**Comment by KATT** [comment]
You can't use `getStaticProps` / `getServerSideProps` in combination with `ssr: true`

- An existing bug that will likely never be closed: #596
- Documented in info-section here: https://trpc.io/docs/ssr

If I misunderstood your problem, feel free to re-open
