### ISSUE TITLE
bug: Problem with fetch implementation

### ISSUE THREAD

**Issue by arashn0uri** [trpc/trpc#3848]
### Provide environment information

```
  System:
    OS: macOS 13.2.1
    CPU: (8) arm64 Apple M1
    Memory: 72.91 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.18.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.2 - /usr/local/bin/npm
  Browsers:
    Brave Browser: 110.1.48.164
    Chrome: 110.0.5481.177
    Safari: 16.3
  npmPackages:
    @tanstack/react-query: ^4.12.0 => 4.24.9 
    @trpc/client: 10.0.0-proxy-beta.17 => 10.0.0-proxy-beta.17 
    @trpc/next: 10.0.0-proxy-beta.17 => 10.0.0-proxy-beta.17 
    @trpc/react: 10.0.0-proxy-beta.17 => 10.0.0-proxy-beta.17 
    @trpc/server: 10.0.0-proxy-beta.17 => 10.0.0-proxy-beta.17 
    next: 12.3.4 => 12.3.4 
    react: 18.2.0 => 18.2.0 
    typescript: 4.9.4 => 4.9.4 
```

### Describe the bug

Hello guys,

I'm using a library (@easy-email) that asks me to create a mock window on the server side of my app to use the window's object on the server. I tried to use the process, but when I used the code provided by their developers on any page, TRPC crashed with this specific error "Error: No fetch implementation found".

I will add the code provided by the library and the screenshot of the problem. 
Any help will be appreciated.

THE CODE PROVIDED BY THEM:
```
import { JSDOM } from 'jsdom';

const dom = new JSDOM(`<!DOCTYPE html><p>Hello world</p>`);

(global as any).window = dom.window;
global.Element = dom.window.Element;
global.document = dom.window.document;
global.navigator = dom.window.navigator;
global.DOMParser = dom.window.DOMParser;
```

HOW I IMPORT THE FILE:
![Screenshot 2023-02-23 at 14 08 48](https://user-images.githubusercontent.com/110023107/220915425-bc5916f2-dcec-4919-9d34-dfe59f5ae16a.png)

MY TRPC CONFIG FILE:
```
import { initTRPC, TRPCError } from "@trpc/server";
import type { Context } from "./context";
import superjson from "superjson";
import { UserForSession } from "../../types/next-auth";

const t = initTRPC.context<Context>().create({
  transformer: superjson,
  errorFormatter({ shape }) {
    return shape;
  },
});

const isAuthed = t.middleware(({ next, ctx }) => {
  if (!ctx.session || !ctx.session.user || !ctx.session.user.id) {
    throw new TRPCError({ code: "FORBIDDEN" });
  }

  const userForSession: UserForSession = {
    id: ctx.session.user.id,
  };

  return next({
    ctx: {
      user: userForSession,
    },
  });
});

export const protectedProcedure = t.procedure.use(isAuthed);
export const router = t.router;
export const publicProcedure = t.procedure;
```

THE ERROR:
![Screenshot 2023-02-23 at 13 46 52](https://user-images.githubusercontent.com/110023107/220911064-19ab7ebb-2875-4b7e-a419-cca2af56e68e.png)

### Link to reproduction

http://localhost:3000

### To reproduce

You could import the file with the code below, on the server side of the project to create a window mock.
On the first try, everything goes well, but if there is an error (any error on the page, for example, receiving status 500 from the server) and you try to refresh the page, the error I mentioned before, "Error: No fetch implementation found", occurred.

The code: 
```
import { JSDOM } from 'jsdom';
const dom = new JSDOM(`<!DOCTYPE html><p>Hello world</p>`);

(global as any).window = dom.window;
global.Element = dom.window.Element;
global.document = dom.window.document;
global.navigator = dom.window.navigator;
global.DOMParser = dom.window.DOMParser;
```

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

**Comment by kamilogorek** [comment]
When you are in a window-less environment, or overwriting the global window, you must also provide a fetch implementation yourself. Either through `httpLink` or `httpBatchLink` - https://trpc.io/docs/links/httpLink#httplink-options

```
$ npm install whatwg-fetch
```

```js
import { fetch } from 'whatwg-fetch';

// Wherever you configure your tRPC, eg.
const client = createTRPCProxyClient<AppRouter>({
  links: [
    httpLink({
      url: 'http://localhost:3000',
      fetch
    }),
  ],
})
```

**Comment by KATT** [comment]
Not worth the squeeze, feel free to submit a PR if you have a strong motivation on why it would behave this way, but the explicit definition works
