### ISSUE TITLE
[TRP-55] feat: expose fetch function without hook

### ISSUE THREAD

**Issue by darklight9811** [trpc/trpc#3859]
### Describe the feature you'd like to request

Expose the function responsible for fetching data when using `createTRPCNext` or `createTRPCReact` to allow usage without react hooks. This enables people to use dynamically the resource they need without locking them into a single usage type.

### Describe the solution you'd like to see

``` typescript
onst api = createTRPCNext<AppRouter>({ /* config */ })

// allow to use inside of components
function Login () {
   const mutate = api.auth.login.useMutation()
}

// and on non react functions
function onLogin (data: Login) {
  const response = await api.auth.login(data)

  // apply to external store
  /* redux/zustand/etc implementation */

  return response
}
```

Since this is already implemented to be passed to react-query, it would only need to be exposed to the api. Implementation options:

### method with objects
``` typescript
api.auth.login(data)
```

### object property
``` typescript
api.auth.login.mutate(data)
```

This still could work with react query if the query client is passed directly (without providers) to the fetch function. Allowing invalidation, and such.

### Describe alternate solutions

To allow using those functions outside of react components, we would need to implement by hand. Simply removing the differential tRPC has of automatically working. It's all possible within the constraints of react-query and trpc. It's only a matter of scope and if the team thinks it's beneficial to the project.

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

<sub>[TRP-55](https://linear.app/trpc/issue/TRP-55/feat-expose-fetch-function-without-hook)</sub>

**Comment by KATT** [comment]
You can do this?:

```tsx
export default function IndexPage() {
  const { client } = trpc.useContext();

  return (
    <button
      onClick={() => {
        client.doSomething.mutate();
      }}
    >
      click me
    </button>
  );
}
```

**Comment by darklight9811** [comment]
@KATT still locked to a component context (react virtual dom)

**Comment by KATT** [comment]
If you're doing an spa you can just set it to a global variable on first mount - I have written an example for this before somewhere in some discussion thread

**Comment by aprilmintacpineda** [comment]
I also need to do this, I need to be able to call TRPC mutations/queries without needing to rely on `useQuery` or `useMutation` hooks.

**Comment by KATT** [comment]
https://github.com/trpc/trpc/discussions/2926#discussioncomment-5647033

**Comment by aprilmintacpineda** [comment]
Actually the answer is in the homepage of trpc website.

```ts
export const trcpProxyClient = createTRPCProxyClient<AppRouter>({
  links: [trpcHttpBatchLink]
});

// then whenever we need it trcpProxyClient.<your-query-name-here>.<query | mutation>
const result = await trcpProxyClient.validateAuth.query();
```

**Comment by KATT** [comment]
This is a React-limitation and has many known workarounds. The main fix is to set it to `window` or to an exported variable on first render of the React-tree
