### ISSUE TITLE
feat: remove procedure types to [v11](https://github.com/trpc/trpc/issues/3496)

### ISSUE THREAD

**Issue by AlexRMU** [trpc/trpc#3867]
### Describe the feature you'd like to request

An alternative to https://github.com/trpc/trpc/issues/3634.
So, we have functions (procedures) defined on the server. They are divided into 2 types (excluding subscriptions):
- query that simply receives data, it is made by the GET method, a request in the form of a query string
- mutation that makes changes and returns data, it is made by the POST method, a request in the form of a body

After adding https://github.com/trpc/trpc/issues/1939, we can change the request methods as we want, and I think the user should determine the semantic load himself.
And if you also remove the types of procedures, then everything will only get better.

### Calling on the client will become easier:
```ts
client.post.get.query(id)
client.post.add.mutate(data)
↓
client.post.get(id)
client.post.add(data)
```
- there are no other properties in the `post.get` object, then why is it needed?
- I already know what the `post.get` function does, there is nothing to clarify in the form of `.query`
- if I want, I can create `post.get.query` by myself

### Creating routes on the server will become easier:
```ts
export const router = t.router({
    post: {
        get: t.procedure.input(/* ... */).request(/* ... */),
        post: t.procedure.input(/* ... */).request(/* ... */),
    },
    post_old: {
        get: {
            query: t.procedure.input(/* ... */).request(/* ... */),
        },
        post: {
            mutate: t.procedure.input(/* ... */).request(/* ... */),
        },
    }
});
```
The `request` function - the user decides which method it is called, what it does, etc. You can add it separately, or you can replace the current methods with it.

### Describe alternate solutions

Perhaps it can be done in a different way, but I think that in any case it needs to be changed.

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

**Comment by juliusmarminge** [comment]
The `.query` and `.mutate` is what determines the method we use - and it's the only way we can know what type the procedure is. The client doesn't know what type of procedure you have defined it to be on the backend - that's strictly TypeScript. In runtime, we use the proxy path to determine what type it is. This article explains the overview of how the client works: https://trpc.io/blog#-putting-it-all-together

Not sure how this problem would be tackled if we allow for method overloading, I'm guessing that it would need to be an option on a per-request basis: 

```ts
const queryAsPost = trpc.post.byId.query({ id: "my-id" }, { trpc: { method: "POST" } });
```
