### ISSUE TITLE
bug: Nested routers with Fastify plugin not working, HTTP routes not found

### ISSUE THREAD

**Issue by nguyenbry** [trpc/trpc#3886]
### Provide environment information

 System:
    OS: macOS 13.0
    CPU: (10) arm64 Apple M1 Pro
    Memory: 160.72 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.13.0 - /opt/homebrew/opt/node@18/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.3 - /opt/homebrew/opt/node@18/bin/npm
  Browsers:
    Chrome: 110.0.5481.177
    Firefox: 109.0
    Safari: 16.1
  npmPackages:
    @trpc/client: ^10.13.0 => 10.13.0 
    @trpc/server: ^10.13.0 => 10.13.0 
    typescript: ^4.8.3 => 4.9.5 

### Describe the bug

When sending a `GET` request to `http://localhost:2022/trpc/posts/list` using a local version of the Fastify example app, it responds with:
```
{
    "message": "Route GET:/trpc/posts/list not found",
    "error": "Not Found",
    "statusCode": 404
}
```

It seems like nested routers are causing an issue, but un-nesting them and putting the procedures in the outermost app router works fine.

Link to code example https://codesandbox.io/s/elated-wildflower-cojy3t

### Link to reproduction

https://codesandbox.io/s/elated-wildflower-cojy3t

### To reproduce

Clone the code sandbox @ https://codesandbox.io/s/elated-wildflower-cojy3t
Run `yarn install`
Run `yarn dev:server`
Send a curl request to `http://localhost:2022/trpc/posts/list`

### Additional information

Using the tRPC client directly works, but not via HTTP

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

**Comment by juliusmarminge** [comment]
> Using the tRPC client directly works, but not via HTTP

That's cause the url path is separated using `.` and not `/`. Try sending the request to 

`http://localhost:2022/trpc/posts.list`

and it should work
