### ISSUE TITLE
Allow passing no `input` on mutations with optional/no input

### ISSUE THREAD

**Issue by kripod** [trpc/trpc#390]
When no `input` is specified for a mutation on the back-end, the corresponding `useMutation` hook shouldn’t require any variables to be given. Unfortunately, this isn’t the case over here:

<img width="667" alt="image" src="https://user-images.githubusercontent.com/14854048/118673198-1c08a380-b7f9-11eb-908f-569f7e4be556.png">

With code similar to:

```tsx
const { mutate: softCancelSubscription } = trpc.useMutation(["WithoutInput"]);

mutate(); // Type checking fails when no parameter is given
```

**Comment by KATT** [comment]
Does it work with `null` or `undefined`? If so, please close the issue - feel free to update docs to make this more clear

**Comment by KATT** [comment]
I rephrased it, but please let me know if it works with `null`.

**Comment by kripod** [comment]
> Does it work with `null` or `undefined`? If so, please close the issue - feel free to update docs to make this more clear

It works just fine with both `null` and `undefined`. Closing this for now.

**Comment by KATT** [comment]
Re-opening as it'd be a nice feature.
