### ISSUE TITLE
chore: fix flaky websocket tests

### ISSUE THREAD

**Issue by KATT** [trpc/trpc#3908]
### Provide environment information

latest

### Describe the bug

Tests are flaky, this is really annoying when developing.

### Link to reproduction

https://github.com/trpc/trpc

### To reproduce

1. clone
2. install
3. `pnpm run dev`

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

**Comment by kamilogorek** [comment]
Unfortunately can't repro it locally, no matter how long I try 😔

**Comment by KATT** [comment]
I think with `p test-watch` it shows

**Comment by kamilogorek** [comment]
No luck for me after 20 runs with `test-watch`

<img width="466" alt="image" src="https://user-images.githubusercontent.com/1523305/222959663-cbaf11b8-0920-4453-a08b-6fac73a6306a.png">

and after 200 runs with my own script. If anyone wants to give it a try, you can use this script locally and run it inside `packages/tests`.

```sh
#!/usr/bin/env bash

i=1
while true; do
    echo "Run attempt: $i"
    ((i++))
    pnpm vitest server/websockets.test.ts --run
    if [ $? -eq 1 ]; then
        break
    fi
done
```

**Comment by juliusmarminge** [comment]
> No luck for me after 20 runs with `test-watch`
> 
> <img alt="image" width="466" src="https://user-images.githubusercontent.com/1523305/222959663-cbaf11b8-0920-4453-a08b-6fac73a6306a.png">
> 
> and after 200 runs with my own script. If anyone wants to give it a try, you can use this script locally and run it inside `packages/tests`.
> 
> ```shell
> #!/usr/bin/env bash
> 
> i=1
> while true; do
>     echo "Run attempt: $i"
>     ((i++))
>     pnpm vitest server/websockets.test.ts --run
>     if [ $? -eq 1 ]; then
>         break
>     fi
> done
> ```

I think it's mostly the interop test which fail in CI (at least when I check). However, even with that I couldn't repro locally either with 50 runs: 

https://app.warp.dev/block/RJWVn87wUDkd375rfUaPHE

Modified script: 

```diff
-     pnpm vitest server/websockets.test.ts --run
+     pnpm vitest websockets.test.ts --run
```

**Comment by kamilogorek** [comment]
> I think it's mostly the interop test which fail in CI (at least when I check). 

https://github.com/trpc/trpc/actions/runs/4337511952/jobs/7573562904#step:9:234

> @***/tests:test-ci: [0]  FAIL  tests/server/websockets.test.ts > regression test - slow createContext > createContext throws
> @***/tests:test-ci: [0] AssertionError: expected "spy" to be called 1 times

https://github.com/trpc/trpc/actions/runs/4322372536/jobs/7544709290#step:9:240

> @***/tests:test-ci: [0]  FAIL  tests/server/interop/websockets.test.ts > subscriptions are automatically resumed
> @***/tests:test-ci: [0] AssertionError: expected 2 to be 1 // Object.is equality

So both then I guess? 😅

**Comment by juliusmarminge** [comment]
> > I think it's mostly the interop test which fail in CI (at least when I check).
> 
> https://github.com/trpc/trpc/actions/runs/4337511952/jobs/7573562904#step:9:234
> 
> > @_**/tests:test-ci: [0]  FAIL  tests/server/websockets.test.ts > regression test - slow createContext > createContext throws
> > @**_/tests:test-ci: [0] AssertionError: expected "spy" to be called 1 times
> 
> https://github.com/trpc/trpc/actions/runs/4322372536/jobs/7544709290#step:9:240
> 
> > @_**/tests:test-ci: [0]  FAIL  tests/server/interop/websockets.test.ts > subscriptions are automatically resumed
> > @**_/tests:test-ci: [0] AssertionError: expected 2 to be 1 // Object.is equality
> 
> So both then I guess? 😅

Bummer...

That makes sense though since I can't see how the interop would make a differnece- it's just been the interop one each time I've checked.
