### ISSUE TITLE
Context type of queries and mutations isn’t inferred when using React Query

### ISSUE THREAD

**Issue by kripod** [trpc/trpc#391]
When [doing updates optimistically](https://react-query.tanstack.com/guides/optimistic-updates), having a `context` value to roll back failed mutations with is crucial. Unfortunately, the `TContext` type used within React Query isn’t inferred in tRPC’s React Query client, and so the value of `context` will always be `unknown`, e.g. in `onError` handlers.

Providing a fourth generic type parameter, `TContext`, to the underlying `useQuery` and `useMutation` hooks might help – please see the related code snippet for details: https://github.com/trpc/trpc/blob/39129c54eb9ede1542b4cd2093d85bf371cdfa8e/packages/react/src/createReactQueryHooks.tsx#L188-L223

**Comment by KATT** [comment]
That's not a bug, that's a feature, PR very welcome :)

**Comment by KATT** [comment]
Closing as it's stale and no one else has bumped it
