### ISSUE TITLE
feat: add HTTP method override option

### ISSUE THREAD

**Issue by KATT** [trpc/trpc#3910]
### Describe the feature you'd like to request

Make it possible to handle biiiiig input payloads on queries by allowing queries to be sent through HTTP `POST`.

### Describe the solution you'd like to see

- `allowOverride: boolean` on HTTP adapters
  - With this option enabled, we can ignore the checks that make sure that queries are called with GET and mutations as POST
- A custom link that allows you to remap all queries on the upstream as a `POST` _or_ allow `httpBatchLink` to have some option for it

### Describe alternate solutions

#3590

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

<sub>[TRP-58](https://linear.app/trpc/issue/TRP-58/feat-add-http-method-override-option)</sub>

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/3910">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/3910/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/3910/pledge.svg">
</picture>
</a>

**Comment by Nick-Lucas** [comment]
I agree this needs solving, it was next on my mental list to have a look at based on the number of help topics I've seen with size issues.

Is there a reason that GET is necessary at all? Would it be a problem if all invocations were changed to POST with a body rather than adding more configurability?

Some thoughts of my own:

* GET/POST are meaningful in REST, but that doesn't necessarily matter as much for RPC
* URI encoded queries are hard to debug from the network debugger, so moving the query into the body would help a lot with the understandability of what tRPC is doing under the hood

**Comment by juliusmarminge** [comment]
> GET/POST are meaningful in REST, but that doesn't necessarily matter as much for RPC

We have tRPC OpenAPI that lets you expose your trpc router as a rest api though

**Comment by Nick-Lucas** [comment]
Good point, I haven't used it though. I take then it doesn't proxy tRPC with restful methods, it just generates the schema with GET and POST in?

**Comment by KATT** [comment]
> Is there a reason that GET is necessary at all? Would it be a problem if all invocations were changed to POST with a body rather than adding more configurability?

HTTP-level caching is nice to be able to have

**Comment by dtinth** [comment]
Some prior art in Ruby world: [`Rack::MethodOverride`](https://github.com/rack/rack/blob/main/lib/rack/method_override.rb) allows specifying the method via a special parameter `_method`.

It may be possible to allows sending `GET` requests as `POST` by applying the same concept, something like:

```
POST /procedure
Content-Type: x-www-form-urlencoded

_method=GET&input={"x":1}
```

**Comment by KATT** [comment]
Yup, `_method` is what I'm thinking too

**Comment by AlonMiz** [comment]
Totally agree, I find myself trying to read the URL sometimes and my head explodes. it would be super useful to allow ALL params being passed in the request body.
eg. search with useInfiniteQuery, passing many filters and params, hard to tell between queries, hard to tell what's been sent to the server.
in general, whenever I'm implementing search in a regular app, I would choose `POST /items/search`
so I can pass params freely without fearing of encoding and the body is human-readable and predictable.

**Comment by VictorGlindasPaf** [comment]
This would be fantastic. We have the requirement that we are not allowed to send things as query parameters, as each request gets logged, and may contain sensitive information in the URL.

So I've currently added a TRPC patch to always use POST for queries, but having it built in would be super.

**Comment by KATT** [comment]
Thank you @KATT for contributing to close this issue! ⭐

The rewards from this issue, totalling $120, has been shared with you.

**What now?**

1. Create a [Polar](https://polar.sh) account
2. See incoming rewards & setup Stripe to receive them
3. Get payouts as backers finalize their payments

_If you already have a Polar account setup, you don't need to do anything._

**Comment by KATT** [comment]
This feature has been added in the [`next`-branch](https://github.com/trpc/trpc/tree/next) of tRPC, meaning it is available in v11 of tRPC. 

It's possible to start using it _today_, have a look at the migration guide for more info: https://trpc.io/docs/migrate-from-v10-to-v11
