### ISSUE TITLE
bug: one request block another request

### ISSUE THREAD

**Issue by ANDYGE** [trpc/trpc#3914]
### Provide environment information

index.tsx
```
  const result = trpc.greeting.useQuery({ name: 'client' });
  const result2 = trpc.greeting.useQuery({ name: 'client2' });

   <h1>{result.data?.text}</h1>     
   <h1 style={{ color: 'red' }}>{result2.data?.text}</h1>
```

[trpc.ts]
```
    // This is the input schema of your procedure
    // 💡 Tip: Try changing this and see type errors on the client straight away
    .input(
      z.object({
        name: z.string().nullish(),
      })
    )
    .query(async ({ input }) => {
      // This is what you're returning to your client
      if (input.name === 'client')
        await new Promise((r) => setTimeout(r, 3000));
      return {
        text: `hello ${input?.name ?? 'world'}` + dayjs().format(' mm:ss'),
        // 💡 Tip: Try adding a new property here and see it propagate to the client straight-away
      };
    }),
```

### Describe the bug

the first request will wait 3 seconds on server,but the secod won't. but on client,both of the requests must wait 3 seconds then show the content. If I have many requests, the experience will be bad.

### Link to reproduction

https://stackblitz.com/edit/trpc-trpc-xu6uvf?file=src%2Fpages%2Findex.tsx&file=src%2Fpages%2Fapi%2Ftrpc%2F[trpc].ts

### To reproduce

yarn && yarn dev

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

**Comment by kamilogorek** [comment]
This is because you are using `httpBatchLink`, which awaits response data for every requested input.
Use `httpLink` instead if you want them to be independent.

**Comment by KATT** [comment]
- You can disable batching: https://trpc.io/docs/links/httpBatchLink#disabling-request-batching
- You can also disable it on _certain_ requests: https://trpc.io/docs/links/splitLink#disable-batching-for-certain-requests
