### ISSUE TITLE
docs: trpc.io homepage demo is not working

### ISSUE THREAD

**Issue by ethanroday** [trpc/trpc#3922]
### Area of Improvement

The demo on the tPRC homepage is not working on FF 109.0. I'm not getting any syntax highlighting, and the preview shows an error message: 

> Unable to run Embedded Project
> 
> Looks like this project is being embedded without proper isolation headers.
> 
> [Read more about browser support for embedded projects](https://developer.stackblitz.com/platform/webcontainers/browser-support#embedding)

Works fine in edge.

### Link to related docs

https://trpc.io/

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing the suggested changes!

**Comment by kamilogorek** [comment]
This unfortunately will be a `wontfix`, as per StackBlitz docs:

> For that reason, we only support embedding WebContainers-based projects in Chromium-based browsers.

**Comment by QuiiBz** [comment]
Which OS are you using? It's working fine on my side in macOS, with the latest Firefox version (currently 110.0.1):

<img width="1536" alt="Screenshot 2023-03-05 at 19 01 26" src="https://user-images.githubusercontent.com/43268759/222977621-1ce47a60-b477-49bf-8bbc-de743f047bca.png">

**Comment by kamilogorek** [comment]
Ah then same, works for me just fine.

**Comment by juliusmarminge** [comment]
> Yeah, I can reproduce the issue, but @ethanroday also had another problem with syntax highlighting not working, which shouldn't happen.

Maybe he meant intellisense? That doesn't work cause the container isn't actually running so it's essentailly just 2 Monaco Editors.

<img width="1353" alt="CleanShot 2023-03-06 at 14 26 55@2x" src="https://user-images.githubusercontent.com/51714798/223123147-f238a3d7-3195-4b3f-b40b-0ce0de2dffbf.png">

I think we did make an attempt in showing some overlay if you weren't on Chrome - can't remember why we didn't ship that though

**Comment by ethanroday** [comment]
Apologies, I very much did mean Intellisense! Syntax highlighting was fine for me.

**Comment by ethanroday** [comment]
In any case, an overlay on non-Chromium browsers would be helpful :)

**Comment by ixahmedxi** [comment]
Thanks for filing the issue @ethanroday 

I will hopefully work on adding an overlay for non chrome viewers today.

**Comment by sachinraja** [comment]
I think it's okay to leave it - people can fork the demo on stackblitz if they want to try it on a non-chromium browser.

**Comment by c-ehrlich** [comment]
I think the overlay would be a good idea. Types and ts errors are a key part of this demo, and it's likely to not be immediately obvious to users that the reason they don't work is because they're on the wrong browser.

**Comment by KATT** [comment]
I think this should be an issue in StackBlitz - I think they should display a legible error messages for unsupported browsers

**Comment by juliusmarminge** [comment]
> I think this should be an issue in StackBlitz - I think they should display a legible error messages for unsupported browsers

They do, in the `Preview` view, not in the editor

**Comment by KATT** [comment]
> They do, in the `Preview` view, not in the editor

Sounds like a bug to me :)
