### ISSUE TITLE
feat: OpenFaaS adapter

### ISSUE THREAD

**Issue by IsaacLeeWebDev** [trpc/trpc#3935]
### Describe the feature you'd like to request

The free, Open Source, CNCF-endorsed version of AWS Lambda could use its own tRPC adapter! 

### Describe the solution you'd like to see

Nothing beyond what other adapters already do, aside from support for OpenFaaS.

### Describe alternate solutions

Letting tRPC users or other open source projects write their own standalone tRPC OpenFaaS adapter.

### Additional information

I wouldn't say OpenFaaS is the most popular FaaS solution, but I definitely think it's becoming the most popular budget-friendly FaaS solution. I also feel that cultivating even more support for standard open source tooling would be a delightful, forward-looking thing to do! 

Thanks for all your hard work on this so far! I think this project has already accomplished some really interesting things, and I'm really excited to see how it evolves. 

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

**Comment by sachinraja** [comment]
Hey OpenFaaS looks great, but none of us on the team have any experience with it so we cannot maintain it. We'd love to put a userland tRPC OpenFaaS adapter on https://trpc.io/awesome though!
