### ISSUE TITLE
feat: allow `withTRPC()`-HOC on individual pages

### ISSUE THREAD

**Issue by arahansen** [trpc/trpc#3936]
### Provide environment information

```
  System:
    OS: macOS 13.2
    CPU: (8) x64 Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz
    Memory: 335.83 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.17.1 - ~/.nvm/versions/node/v16.17.1/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 110.0.5481.177
    Chrome Canary: 113.0.5634.0
    Firefox: 109.0.1
    Safari: 16.3
    Safari Technology Preview: 14.1
  npmPackages:
    @tanstack/react-query: 4.24.4 => 4.24.4 
    @trpc/client: ^10.12.0 => 10.12.0 
    @trpc/next: ^10.12.0 => 10.12.0 
    @trpc/react-query: ^10.12.0 => 10.12.0 
    @trpc/server: ^10.12.0 => 10.12.0 
    next: 13.1.6 => 13.1.6 
    react: 18.2.0 => 18.2.0 
    typescript: 4.9.5 => 4.9.5 
```

### Describe the bug

My use case is I want to render a trpc-connected react component within Prosemirror. This essentially requires something along the lines of:

```
import { createTRPCNext } from '@trpc/next'

...

const trpc = createTRPCNext({ ... })
const dom = document.createElement('div')
const Component = trpc.withTRPC(() => <SomeComponentUsingTRPC />)

React.createRoot(dom).render(<Component />)
```

This code throws an error with `Cannot read properties of undefined (reading 'trpcState')`

Looking at the source, it looks like `trpc.withTRPC` assumes I'm rendering a full Next app and is looking for `pageProps.trpc.trpcState` ([source](https://github.com/trpc/trpc/blob/33e55fdc9aa208683388d60fca0a8581aef71775/packages/next/src/withTRPC.tsx#L125))

I see a couple paths forward for this:
1. (My current workaround) update to: `<Component pageProps={{ trpc }} />`. If this is preferred, can the type definition be updated to require `pageProps`?
2. Update the linked source to optional chain looking for `pageProps.trpc.trpcState`?
3. I should use something besides `withTRPC` from `@trpc/next`. If this is the case, what would be the preferred solution? Should I use `trpc.Provider` directly and pass in my trpcClient and queryClient?

### Link to reproduction

https://stackblitz.com/edit/github-7x3aij?file=src/pages/index.tsx

### To reproduce

Reproduction can be found at the stackblitz link. You can fix the runtime error by uncommenting `pageProps={{ trpc }}`

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

**Comment by KATT** [comment]
We don't officially support `withTRPC` outside of `_app.tsx`, but it would be nice to have support for that.

Would you be able to do produce a failing test in our test suite? That'd speed this up a lot
