### ISSUE TITLE
bug: getQueryKey type=any does not work as intended

### ISSUE THREAD

**Issue by WesleyYue** [trpc/trpc#3937]
### Provide environment information

```
  System:
    OS: macOS 13.2.1
    CPU: (12) x64 Apple M2 Pro
    Memory: 29.88 MB / 32.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.17.1 - ~/.nvm/versions/node/v16.17.1/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.4.0 - ~/Code/double/node_modules/.bin/npm
  Browsers:
    Chrome: 110.0.5481.177
    Firefox: 110.0
    Safari: 16.3
```

### Describe the bug

With getQueryKey, the docs say that leaving `type` as the default `any` should produce a query key that matches both `query` and `infinite` type. In my testing, I've found that this is not the case. I think this is because trpc is putting the `type` inside the object of the 2nd array item in the example, rather than as the 3rd item in the array.

### Link to reproduction

https://stackblitz.com/edit/github-kuehgz?file=src%2Fpages%2Findex.tsx

### To reproduce

```typescript
  const queryKey = getQueryKey(trpc.greeting, { name: 'client' });
  console.log('getQueryKey', JSON.stringify(queryKey));
  console.log('getQueriesData', JSON.stringify(queryClient.getQueriesData()));
  console.log(
    'getQueryData',
    JSON.stringify(queryClient.getQueryData(queryKey))
  );
```

Output:
```
getQueryKey [["greeting"],{"input":{"name":"client"}}]
getQueriesData [[[["greeting"],{"input":{"name":"client"},"type":"query"}],{"text":"hello client"}]]
getQueryData undefined
```

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

**Comment by juliusmarminge** [comment]
This is the expected behavior, see @TkDodo's response https://github.com/TanStack/query/issues/5111#issuecomment-1464864361
