### ISSUE TITLE
docs: enhance quickstart guide

### ISSUE THREAD

**Issue by Nick-Lucas** [trpc/trpc#3947]
### Area of Improvement

The quickstart guide could use some detail in a number of areas which aren't mentioned yet, and to go deeper in some existing areas. I plan on on contributing this. 

Getting Started Docs like Remix has are much more comprehensive. Some rough planning needs doing which I will put here, but any ideas from others will be very welcome too.

A community member has also recently posted this which structurally looks like great inspiration for where we need to end up: https://ajcwebdev.com/2023/03/08/2023-03-08-a-first-look-at-trpc/ 

### Link to related docs

https://trpc.io/docs/quickstart

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR implementing the suggested changes!

---

### The current docs have these sections:

- [Installation](https://trpc.io/docs/quickstart#installation)
  - [Installation Snippets](https://trpc.io/docs/quickstart#installation-snippets)
- [Defining a backend router](https://trpc.io/docs/quickstart#defining-a-backend-router)
  - [Create a router instance](https://trpc.io/docs/quickstart#create-a-router-instance)
  - [Add a query procedure](https://trpc.io/docs/quickstart#add-a-query-procedure)
  - [Add a mutation procedure](https://trpc.io/docs/quickstart#add-a-mutation-procedure)
- [Using your new backend on the client](https://trpc.io/docs/quickstart#using-your-new-backend-on-the-client)
  - [Setup the tRPC Client](https://trpc.io/docs/quickstart#setup-the-trpc-client)
  - [Querying & mutating](https://trpc.io/docs/quickstart#querying--mutating)
  - [Full autocompletion](https://trpc.io/docs/quickstart#full-autocompletion)
- [Next steps](https://trpc.io/docs/quickstart#next-steps)

### Where I think we should be (_WIP_)

Removing this list for now since I will be maintaining #3963 for a higher level plan then coming back to this

<sub>[TRP-59](https://linear.app/trpc/issue/TRP-59/docs-enhance-quickstart-guide)</sub>

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/3947">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/3947/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/3947/pledge.svg">
</picture>
</a>

**Comment by radeon8** [comment]
It lacks build & deploy steps on a standalone server. By the way how to combine with SQL.

**Comment by gustawdaniel** [comment]
@radeon8 you can use SQL by prisma there are examples in this repo.

**Comment by radeon8** [comment]
The starter project need be a standalone server.
No nextjs,Prisma,Postql etc.
The less new knowledge, the more focusing on tRPC.
I recommend tRPC to my team, they are blocked by so many new technologies in the quickstart.
https://trpc.io/docs/example-apps

**Comment by Nick-Lucas** [comment]
So my goal will very much be to use quite vanilla technologies in the quick-start, a problem right now is definitely that the off-ramp into client/frontend tech throws you in the deep in because there's no dedicated quickstart for those. 

I suspect the closest we'll want to get to documenting how to use SQL will be suggesting some tRPC patterns around Dependency Injection & singletons? The rest really comes down to the docs of whatever ORM/etc you choose

**Comment by radeon8** [comment]
The target users must master some general technologies like Typescript, React, also expressjs. Most of them are fullstack.It is just my opinion.😋

**Comment by KATT** [comment]
cc @Nick-Lucas I guess we can close this now?
