### ISSUE TITLE
feat: Procedure Meta merging

### ISSUE THREAD

**Issue by Nick-Lucas** [trpc/trpc#3948]
### Describe the feature you'd like to request

Currently if you write something like this, tRPC will generate a runtime error:

```ts
publicProcedure.meta({ keyA: 1 }).meta({ keyA: 2, keyB: 3 })
// ^ Error: Duplicate key meta
```

This leads to a little inflexibility where tools like middlewares are concerned, for instance, you have an Authorization middleware which checks a route's access requirements against a user's permissions. In that case the middleware itself needs to coerce an un-set key to a known requirement. I think it would be better if a base procedure could have some defaults defined in the meta and these defaults could be overwritten on a procedure-by-procedure basis.

```ts
const authedProcedure = publicProcedure.use(AuthMiddleware).meta({ requiredRole: 'super' })

const appRouter = router({
  hello: authedProcedure.meta({ requiredRole: 'basic' })
})
```

### Describe the solution you'd like to see

I propose that multiple Meta() calls should stack and _shallow_ merge for middlewares and procedures to consume

### Describe alternate solutions

* Don't do it because there's a really good reason not to allow more than a single meta call per procedure.
* Take a defaultValue like: `initTRPC.meta<Type>(defaultValue)`
  * or support this _and_ shallow merging!

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

**Comment by KATT** [comment]
What should happen with a discriminated union in the `Meta`-type? 🤔

**Comment by Nick-Lucas** [comment]
excellent question, I would theorise it doesn't really matter? Thoughts:

1. merging is opt-in, if you call meta twice you can design your code with the expectation of shallow merging
2. if you call meta twice right now your app won't even start, therefore it's not a breaking change for people using unions already
3. if someone does merge a different union member over the top, then in the worst case there are some extraneous keys still there but hidden by the type system. Extraneous keys in runtime types are sort of quite normal in typescript because of the structural typing system

If point 3 is a worry though we could do something like:

```ts
publicProcedure.meta({ ...a }).meta({ ...b }, { mode: 'merge' | 'replace' })
```

I'd like to avoid adding more complexity and options if possible though, what do you think?

**Comment by radeon8** [comment]
If ``procedire.meta`` can be chained calls.What about ``procedure.query().query()``? May users be confused?

**Comment by Nick-Lucas** [comment]
> If `procedire.meta` can be chained calls.What about `procedure.query().query()`? May users be confused?

Feel free to make a ticket for discussion, I'm not sure what the benefit would be but in any case this isn't the best spot to discuss it :)
