### ISSUE TITLE
feat: create a `@trpc/eslint-plugin` for enforcing best practices

### ISSUE THREAD

**Issue by iduuck** [trpc/trpc#3956]
### Describe the feature you'd like to request

I'd love to contribute by adding a new eslint-plugin specifically for trpc, which brightens the DX even more, and enforces best practices.

Some rules I have in mind: 

- No explicit typing of `.mutation()` or `.query()`
- Warning for empty routers `router({})`
- Based on user preference: Enforcing `mutate` OR `mutateAsync` for `useMutation`s
- Warn when using `createCaller` in another procedure (see "[Server Side Calls](https://trpc.io/docs/server-side-calls)" info box)
- Option for user to disable (getting warnings) promises in middleware, but instead use them in context (only being called, when batched).

Just to list a few, I think we all could find some more extensive ones.

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

<sub>[TRP-12](https://linear.app/trpc/issue/TRP-12/feat-create-a-trpceslint-plugin-for-enforcing-best-practices)</sub>

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/3956">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/3956/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/3956/pledge.svg">
</picture>
</a>

**Comment by Nick-Lucas** [comment]
Love this idea.

Some dreams of mine:

* Include a little fork of rules-of-hooks rules which supports the chained useQuery/useMutation pattern, can contribute this back to react but they've not appeared too motivated so far
* ensure that AppRouter on the client is imported by `type`
* ensure that things like transformers and batching are done the same on both sides (not sure if eslint can actually achieve comparisons between files though)
* Enforce specific patterns in the API like naming patterns for `t`, routers, etc

**Comment by iduuck** [comment]
Thanks, @Nick-Lucas. That's an awesome list.

> Include a little fork of rules-of-hooks rules which supports the chained useQuery/useMutation pattern, can contribute this back to react but they've not appeared too motivated so far

What do you mean by this? 

> ensure that AppRouter on the client is imported by type

I don't know, if this is something, that should be done by us. I am using the [`@typescript-eslint/consistent-type-imports`](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/consistent-type-imports.md) rule here.

> ensure that things like transformers and batching are done the same on both sides (not sure if eslint can actually achieve comparisons between files though)

Same thought as you had. Checking for two files can be tricky with eslint, unless the type-checking engine is enabled (`project` attr in the .eslintrc). 

> Enforce specific patterns in the API like naming patterns for t, routers, appRouter, AppRouter, etc

That's an awesome one, however we might need to add options, so that each single one can be changed to the users liking, so that we are not too opinionated in here.

**Comment by Nick-Lucas** [comment]
Another one coming up today: Enforce that objects containing procedures must be started with a `t.router` call. Users shouldn't be exporting plain objects and attaching them to routers in other files, because that can lead to type errors being misplaced and causing confusion

There is currently an open docs PR from @juliusmarminge to communicate this but the nuance is annoying to communicate

<img width="890" alt="image" src="https://user-images.githubusercontent.com/8896153/225160868-3c640d14-9ce1-4a9c-ac13-ac73ecf42544.png">

**Comment by Delavalom** [comment]
> ### Describe the feature you'd like to request

I would love the lint to make sure things like the terminating link when setting up trpc/client

```ts
const api = createTRPCProxyClient<AppRouter>({
  links: [] // It should have a terminating link 
            // otherwise the tRPC operation will not be sent to the tRPC server.
});
```

**Comment by iduuck** [comment]
I'd love some comments on the essential concept of the PR from @KATT, @juliusmarminge and @t3dotgg and whether it would be merged into core.

I'd love to finish this.

**Comment by juliusmarminge** [comment]
> I'd love some comments on the essential concept of the PR from @KATT, @juliusmarminge and @t3dotgg and whether it would be merged into core.
> 
> I'd love to finish this.

I'm for it!

**Comment by juliusmarminge** [comment]
Closing as per https://github.com/trpc/trpc/pull/4044#issuecomment-1510054457
