### ISSUE TITLE
Next.js bug: queries broken in next 13.2.4

### ISSUE THREAD

**Issue by Manitej66** [trpc/trpc#3971]
### Provide environment information

```
  System:
    OS: macOS 13.2.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 550.84 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh

  Binaries:
    Node: 16.19.0 - ~/.nvm/versions/node/v16.19.0/bin/node
    npm: 8.19.3 - ~/.nvm/versions/node/v16.19.0/bin/npm

  Browsers:
    Chrome: 111.0.5563.64
    Safari: 16.3

  npmPackages:
    @tanstack/react-query: ^4.26.1 => 4.26.1
    @trpc/client: ^10.14.1 => 10.14.1
    @trpc/next: ^10.14.1 => 10.14.1
    @trpc/react-query: ^10.14.1 => 10.14.1
    @trpc/server: ^10.14.1 => 10.14.1
    next: 13.2.4 => 13.2.4
    react: 18.2.0 => 18.2.0
    typescript: ^4.9.5 => 4.9.5
```

### Describe the bug

Updated next version to latest and just restarted the dev server, all queries seems broken.

might be related to [this issue](https://github.com/vercel/next.js/issues/46356)
<img width="1620" alt="image" src="https://user-images.githubusercontent.com/61357713/224341226-ace6e644-6a70-4eea-931e-af71d03929fb.png">

### Link to reproduction

company code so can't share 

### To reproduce

Just update to latest next version

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

**Comment by KATT** [comment]
Closed upstream, please re-open if it's not fixed in the version that correlates to that issue
