### ISSUE TITLE
feat: throttle and debounce

### ISSUE THREAD

**Issue by darklight9811** [trpc/trpc#3972]
### Describe the feature you'd like to request

Since trpc wraps react-query, add the option for trpc to debounce and throttle any changes to the input of queries. To avoid having a wrapper (debounce) of a wrapper (trpc) of a wrapper (react-query) of a wrapper (fetch).

### Describe the solution you'd like to see

``` typescript
const [search, setsearch] = useState("")
const { data } = api.category.index.useQuery({
  search,
  // other params such as pagination
}, {
  throttle: 500,
})
```

### Describe alternate solutions

Currently I have to add an helper function to delay propagation of the state to the useQuery method. This is not ideal since it can't be properly wrapped and add an additional step layer to any implementation required.

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

**Comment by KATT** [comment]
This gets too complicated to do when having complex input since we gotta serialize and normalize the input to see if it has changed.

Add a "debounced value" utility instead.

Example:

```tsx
function MyComp() {
  const search = useDebouncedValue(asStringOrNull(useRouter().query. search));
  
  const { data } = api.category.index.useQuery({ search }};
}
```

I don't think we'll  add this to trpc as it adds a complexity.
