### ISSUE TITLE
bug: examples-next-prisma-websockets-starter infinite queries is broken

### ISSUE THREAD

**Issue by nithiwatter** [trpc/trpc#3981]
### Provide environment information

ystem:
    OS: macOS 13.2.1
    CPU: (8) arm64 Apple M1
    Memory: 154.41 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.19.0 - /opt/homebrew/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 8.19.3 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 110.0.5481.177
    Firefox: 109.0.1
    Safari: 16.3
  npmPackages:
    @tanstack/react-query: ^4.3.8 => 4.26.1 
    @trpc/client: ^10.15.0 => 10.15.0 
    @trpc/next: ^10.15.0 => 10.15.0 
    @trpc/react-query: ^10.15.0 => 10.15.0 
    @trpc/server: ^10.15.0 => 10.15.0 
    next: ^13.2.1 => 13.2.4 
    react: ^18.2.0 => 18.2.0 
    typescript: ^4.8.3 => 4.9.5 

### Describe the bug

The cloned example has an unexpected behavior - specifically, the infinite query hook for messages is not called until the page is refocused.

### Link to reproduction

https://github.com/trpc/examples-next-prisma-websockets-starter

### To reproduce

1. Clone the examples
2. Auth and send some messages
3. Refresh the page - notice that the sent messages are not there - check dev tools and no infinite query event is pushed up the socket
4. Only once clicking on the dev tools then back on the main page to refocus does the query gets pushed and data retrieved.

See the video attached

https://user-images.githubusercontent.com/59894785/224510108-c05ecae1-1bf4-47f4-9f0a-3e79f298eb09.mov

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

**Comment by KATT** [comment]
Just as a reference, it works in prod: https://websockets.trpc.io/

Unsure what's happened here

**Comment by nithiwatter** [comment]
I think I know why - I just upgraded to node 18 and the local now works correctly - I was previously using node 16 and it seems like it is an issue with ssr + no native fetch. I will close this now.
