### ISSUE TITLE
docs: trpc with existed react-query

### ISSUE THREAD

**Issue by yikkwongwong** [trpc/trpc#3987]
### Area of Improvement

Not sure whether it's an error solely from my repo.

In order to integrate with existing react-query, I needed to make a new `QueryClientProvider` with context. If there is no context, the trpc react-query will throw `No QueryClient Set ....`. If there is only one `QueryClientProvider` with context, the existing react-query will throw `No QueryClient Set ....`.

The following code solves my issue.

trpc.ts
```javascript
export const context = createContext<QueryClient | undefined>(undefined);

export const trpc = createTRPCReact<AppRouter>({ reactQueryContext: context });
```

App.tsx
```diff
+ <trpc.Provider client={trpcClient} queryClient={queryClient}>
+    <QueryClientProvider client={queryClient} context={context}>
        <QueryClientProvider client={queryClient}>
            ...app
        </QueryClientProvider>
+    </QueryClientProvider>
+ </trpc.Provider>
```

Related:
[react-query v4 docs](https://tanstack.com/query/v4/docs/react/guides/migrating-to-react-query-4#custom-contexts-for-multiple-providers)
[another issue](https://github.com/trpc/trpc/issues/3316)

### 👨‍👧‍👦 Contributing

- [x] 🙋‍♂️ Yes, I'd be down to file a PR implementing the suggested changes!

**Comment by Nick-Lucas** [comment]
I believe it should be fine to re-use the existing react-query client in trpc. Just import it and use it with tRPC as well

**Comment by juliusmarminge** [comment]
Yea you definetely dont need multiple queryclients. As Nick Said you can reuse the existing one

**Comment by Nick-Lucas** [comment]
Closing this since there's already a solution in place 🙂

**Comment by yikkwongwong** [comment]
I can reuse the queryclient but not the QueryClientProvider. If i pass it without context, trpc wrapper will throw `No QueryClient set`, but existing react-query can run just fine.
