### ISSUE TITLE
feat: support specifying optional `host` on `createHTTPServer`

### ISSUE THREAD

**Issue by balupton** [trpc/trpc#4004]
### Describe the feature you'd like to request

Having the ability to specify which host to listen to will increase [server environment support](https://github.com/bevry/hostenv), and allow specific binding to say `127.0.0.1` or `localhost` or `192.168.x.x`, or `0.0.0.0`.

### Describe the solution you'd like to see

See https://nodejs.org/api/net.html#serverlistenport-host-backlog-callback for the necessary call, which would change https://github.com/trpc/trpc/blob/8abd05abd31d87798917ec03a028870a998bfc52/packages/server/src/adapters/standalone.ts#L49 along with adding the ability to provide the optional host method

### Describe alternate solutions

unsure

### 👨‍👧‍👦 Contributing

- [x] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature! **- maybe... would need to know how to update the types, and tests if need be**

**Comment by Nick-Lucas** [comment]
Good suggestion, it's a pretty simple change if you'd like to open a PR?

You'll find it currently hard-coded in `packages/server/src/adapters/standalone.ts` so it's a few lines and possibly some test/docs tweaks :)

**Comment by balupton** [comment]
Gonna do this now.

**Comment by kamilogorek** [comment]
Will be fixed in v11 via https://github.com/trpc/trpc/pull/4014
Right now you can achieve this by calling `createHTTPServer` but then, instead of `.listen` on returned object, go indirectly through the serve, `createHTTPServer().server.listen(port, host)`.
