### ISSUE TITLE
docs: Code `copy` not working

### ISSUE THREAD

**Issue by dephraiim** [trpc/trpc#4019]
### Area of Improvement

The copy button for this page is not working

### Link to related docs

https://trpc.io/docs/ssg-helpers

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR implementing the suggested changes!

**Comment by c-ehrlich** [comment]
It's working for me, Firefox 111.0 on MacOS 13.0.1. Could you give more details about your system? Do copy buttons on other pages work for you?

**Comment by kamilogorek** [comment]
Confirmed on Safari `16.3` and MacOS `13.2` as well.

**Comment by kamilogorek** [comment]
I tested it further today, and apparently it works fine for other docusaurus-based websites 🤔  eg. https://docsearch.algolia.com/docs/record-extractor

For the ref, here's the implementation: https://github.com/facebook/docusaurus/blob/main/packages/docusaurus-theme-classic/src/theme/CodeBlock/CopyButton/index.tsx

**Comment by KATT** [comment]
Might be because of ```twoslash?

**Comment by kamilogorek** [comment]
From what I tested it's not the issue. Although worth noting that `twoslash` is indeed overriding that functionality - https://github.com/shikijs/twoslash/blob/main/packages/docusaurus-preset-shiki-twoslash/docusaurus-theme-shiki-twoslash/theme/CodeBlock/index.js
However, even after the simple removal of that preset it's not making a dent. It's probably something obvious that I just don't see :3
