### ISSUE TITLE
bug: rawInput undefined

### ISSUE THREAD

**Issue by josejaviersanahuja** [trpc/trpc#4020]
### Provide environment information

IN SERVER
```
System:
    OS: Linux 5.10 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (4) x64 Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz
    Memory: 1.40 GB / 15.52 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 18.1.0 - ~/.nvm/versions/node/v18.1.0/bin/node
    npm: 8.8.0 - ~/.nvm/versions/node/v18.1.0/bin/npm
    Watchman: 20220605.192726.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 110.0.5481.177
    Firefox: 102.8.0esr
  npmPackages:
    @trpc/server: ^10.16.0 => 10.16.0 
    typescript: ^4.9.5 => 4.9.5 
```
IN CLIENT
```
 System:
    OS: Linux 5.10 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (4) x64 Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz
    Memory: 1.33 GB / 15.52 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 18.1.0 - ~/.nvm/versions/node/v18.1.0/bin/node
    npm: 8.8.0 - ~/.nvm/versions/node/v18.1.0/bin/npm
    Watchman: 20220605.192726.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 110.0.5481.177
    Firefox: 102.8.0esr
  npmPackages:
    @trpc/client: ^10.16.0 => 10.16.0 
    next: 13.1.6 => 13.1.6 
    react: 18.2.0 => 18.2.0 
    typescript: 4.9.5 => 4.9.5 

```

### Describe the bug

Every mutate mutation function I send to the server arrives with rawInputs undefined.

The query are ok

some codes.

```typescript
export const appRouter = t.router({
  hello: publicProcedure
    .input(z.object({
      name: z.string()
    }))
    .query(req => {
      return `Hello ${req.input.name}`
    }),
  logToServer: t.procedure.use(t.middleware((all) => {
    debugLog(all.rawInput)
    return all.next()
  }))
    .input(z.object({
      message: z.string()
    }))
    .mutation((req) => {
      debugLog(req.input)
    }),
})
```
output logs:
```
client:dev undefined +5ms
rawInput undefined
```

The next picture is the function throwing the error
![image](https://user-images.githubusercontent.com/82359964/226124367-7ea70918-a54f-4b66-90db-ccf4c2f058bb.png)

### Link to reproduction

https://github.com/josejaviersanahuja/template-trpc-prisma-express-next

### To reproduce

Copy, Download or fork this repo.

After installing dependencies,...

In Server: npm run dev
In Client: npm run dev

That's it!

### Additional information

https://github.com/trpc/trpc/discussions/4018#discussioncomment-5354231

I opened a discussion regarding nested routes, which I can't configure.

I don't know if its related

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

**Comment by Nick-Lucas** [comment]
This is a bug with your middleware setup. I moved the trpc middleware above the json/urlencoded middlewares and the inputs comes through fine. Those middlewares are messing up the data which gets sent on to tRPC

<img width="747" alt="image" src="https://user-images.githubusercontent.com/8896153/226126715-17fa255e-3fbd-4383-ad9c-50d01155ef91.png">
