### ISSUE TITLE
docs: improves next-prisma-starter docs

### ISSUE THREAD

**Issue by KATT** [trpc/trpc#4030]
### Area of Improvement

https://github.com/trpc/examples-next-prisma-starter

- We use pnpm now (we could just nuke yarn/pnpm
- We could probably go over all the scripts to make sure they make sense

### Link to related docs

https://github.com/trpc/examples-next-prisma-starter

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing the suggested changes!

**Comment by iduuck** [comment]
One more thing that could be done:

- Update dependencies
