### ISSUE TITLE
feat: rename `createSSGHelpers`

### ISSUE THREAD

**Issue by KATT** [trpc/trpc#4041]
### Describe the feature you'd like to request

They were never designed only to work with `getStaticProps`. We should have better name for it.

### Describe the solution you'd like to see

- Rename
- Alias to old name with `@deprecated`-notice
- Update docs, especially https://trpc.io/docs/nextjs/ssr that don't mention gSSP at all

### Describe alternate solutions

no

### Additional information

- The new name doesn't have to have `Proxy` in it (that was just to not conflict with interop stuff)
- Don't touch anything in any `**/interop/**`-file

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

**Comment by c-ehrlich** [comment]
Was thinking about the name a while ago. `createSSRandSSGHelpers` is obviously not great.

I think the most important thing about the new name is to communicate clearly how these helpers are different crom `createCaller`. So far I thought about `createPrefetchHelpers` or `prefetchHelpers`, but maybe there's an even better option? Maybe "helpers" isn't even the best word? We don't get many chances to pick a new descriptive name for things, so should make sure to get this right.

**Comment by KATT** [comment]
`createServerSideHelpers`?

**Comment by KATT** [comment]
Not too worried about the "wrong" name, it's easy to rename, deprecate and alias the old
