### ISSUE TITLE
feat: migrate to new turborepo version (package scoped turbo.json)

### ISSUE THREAD

**Issue by iduuck** [trpc/trpc#4045]
### Describe the feature you'd like to request

See this for more information about this: https://turbo.build/blog/turbo-1-8-0#workspace-configurations

### Describe the solution you'd like to see

-

### Describe alternate solutions

-

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

<sub>[TRP-20](https://linear.app/trpc/issue/TRP-20/feat-migrate-to-new-turborepo-version-package-scoped-turbojson)</sub>

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/4045">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/4045/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/4045/pledge.svg">
</picture>
</a>

**Comment by juliusmarminge** [comment]
What's your plan with this? Put turbo.json in every package? Includign all examples?
