### ISSUE TITLE
docs: outdated `next-edge-runtime` example

### ISSUE THREAD

**Issue by stephenasuncionDEV** [trpc/trpc#4048]
### Area of Improvement

Config's runtime edge is not experimental anymore.
```ts
export const config = {
  runtime: 'experimental-edge', 
};
to
export const config = {
  runtime: 'edge', 
};
```
Also getting `Dynamic Code Evaluation (e. g. 'eval', 'new Function', 'WebAssembly.compile') not allowed in Edge Runtime` when building the app. It is because of the `fetchRequestHandler` function.

Seem to work in dev but not when building.

Edit:
It wasn't because of the `fetchRequestHandler` function. I had a library that does not support edge.

### Link to related docs

https://github.com/trpc/trpc/tree/main/examples/next-edge-runtime

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing the suggested changes!

**Comment by juliusmarminge** [comment]
It builds fine locally for me after removing the experimental flag. Even tried deploying it and it works: https://next-edge-runtime.vercel.app

Did you make any changes before getting that error above? Can you share that code if so?

**Comment by stephenasuncionDEV** [comment]
Can close this issue now. My problem was there was a library that I was using inside the routers that do not support edge.
