### ISSUE TITLE
bug: returning `undefined` from server gets stripped on the client

### ISSUE THREAD

**Issue by romeerez** [trpc/trpc#4049]
### Area of Improvement

Please add an explanation to Quickstart of why `user` has type `User | undefined` on the server:

```ts
.query((req) => {
  const input = req.input;
  const user = userList.find((it) => it.id === input);
 
  // TS error if we try accessing user.id here
  user.id
 
   return user;
}),
```

But the client code has a different type which is equal to `User`, but `undefined` type is missing:

```ts
const user = await trpc.userById.query('1');
// hello, runtime error!
user.id;
```

Is it intentional, and how to fix it?

### Link to related docs

https://trpc.io/docs/quickstart#querying--mutating

### Additional information

@trpc/server: 10.17.0
typescript: 4.9.5

have "strict": true in tsconfig

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing the suggested changes!

**Comment by romeerez** [comment]
It refused to believe that such an obvious bug is possible, so assumed it was something with documentation.

Is it a newly introduced bug, and I can downgrade the trpc version?

**Comment by KATT** [comment]
It's just a bug in the documentation :)

**Comment by romeerez** [comment]
I don't understand, `trpc` behaves exactly as documented, so I can have a runtime error on the client. Maybe some step is missing in the documentation to prevent this? What can I do to fix this behavior?

**Comment by romeerez** [comment]
@KATT could you explain what this issue is about?

**Comment by kamilogorek** [comment]
I believe this is indeed a bug, not a documentation issue.

What's happening here is that automatic JSON types introduced in https://github.com/trpc/trpc/pull/3261 are skipping `undefined` value as it's non-serializable, thus coerced to `never` in `T extends NonJsonPrimitive ? never :` clause or `Serialize<T>` type.

And it's internally called via `inferTransformedProcedureOutput` which when the default transformer is not overridden, uses `Simplify<Serialize<TProcedure['_def']['_output_out']>` as it's type, not reintroducing `undefined`

**Comment by KATT** [comment]
Am I missing something? This is just how `.find()` works?

See https://www.typescriptlang.org/play?#code/C4TwDgpgBAqgzhATlAvFA3gWAFBSgSwBMAuKOYRfAOwHMBuHPKgQwFsJTzLaHsBfHAGMA9lXJQArgkRxS8JAG0AuqigLGGDXiKkA5ADNhw3QBotUFuz0AjZolMaB2JbyGjxUpKs8yAdPupCAAoJVAA+SV8iVBQ0AyNdAEocAHoUvAyAPQB+IA
![CleanShot 2023-04-06 at 11 45 22](https://user-images.githubusercontent.com/459267/230339841-f046540f-e5a4-4d94-b643-8a0a6a92d1be.png)

**Comment by romeerez** [comment]
@KATT  yes, `find` works as expected, it's a bug in `trpc`, not in the `find`. @kamilogorek analyzed and explained it very well in the above message.

**Comment by juliusmarminge** [comment]
Added a failing test on #4187

**Comment by romeerez** [comment]
Great that you have fixed it!

I still see a problem in Quickstart, here is a screenshot of editor in the Quickstart:
![image](https://user-images.githubusercontent.com/42248135/232274091-92b67778-8b5a-43d1-bf69-07e2298d2708.png)

Maybe it's because the libraries aren't updated in the embedded editors, but the `undefined` type is still being stripped.

**Comment by sachinraja** [comment]
it's been merged, but a release hasn't been published yet @romeerez

**Comment by romeerez** [comment]
I see, thank you
