### ISSUE TITLE
feat: Automatic data normalisation

### ISSUE THREAD

**Issue by klis87** [trpc/trpc#4055]
### Describe the feature you'd like to request

Hi, I created a https://github.com/klis87/normy library, which can add a similar experience like apollo client automatic data updates from server responses (but for anything, not graphql only) for libraries like `react-query` and `trpc`.

Because `trpc` is based on `react-query`, it already works for queries and mutations, see example - https://github.com/klis87/normy/tree/master/examples/trpc

But the subscriptions are not `react-query` feature, so I need a special place to allow easy integration with `normy`, so that we could have automatic data updates for all subscriptions events too.

### Describe the solution you'd like to see

I need a way to listen to all subscriptions in 1 place. Then I could do some integration with `normy` like I did for mutations here - https://github.com/klis87/normy/blob/master/packages/normy-react-query/src/index.ts#L62

If there is already a way to achieve it, apologies, and I will appreciate a hint how to make it work.

And if not, will you be open to add a way to listen to all subscriptions responses to allow me adding normalisation feature to subscriptions too?

Thanks!

### Describe alternate solutions

I checked `subscriptions` documentation and I cannot find a central way to listed to subscriptions responses to normalize them.

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

<sub>[TRP-14](https://linear.app/trpc/issue/TRP-14/feat-automatic-data-normalisation)</sub>

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/4055">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/4055/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/4055/pledge.svg">
</picture>
</a>

**Comment by KATT** [comment]
I think you can implement this as a data transformer on the client, I did an experiment with a similar idea ~2 years ago (search through PRs with the word "normi")

There are some footguns with this approach that led me not to pursue it, like if you can't guarantee that you always have the same shapes on the backend it's easy to override the wrong entries etc and get odd states in the front-end

**Comment by KATT** [comment]
Closing this as it's been open for over a long time with no one caring enough about it to either offer funding it or building it.

Not sure if we'll ever do this and I think it's already possible with a transformer
