### ISSUE TITLE
feat: add the operation in the header callback of non-batched http link

### ISSUE THREAD

**Issue by tibotiber** [trpc/trpc#4071]
### Describe the feature you'd like to request

This is a follow up to #2018, I'd like to be able to set specific headers per operation when using a non-batch httpLink. 

Context:
I have procedures that can be called publicly or authenticated and will be processed slightly differently on the server. I want to set headers on a per operation basis. I am using httpLink, so no batching involved. The auth context (whether to authenticate or not, as well as a token fetcher) are available in my component (call site) but not via session/cookies/etc., and not at the top of my tree where the httpLink gets configured. So headers being async is great, but I'd love to have the operation's context available there as well.

### Describe the solution you'd like to see

This is what existed in #2024 prior to v10 and was shelved at the time.

https://github.com/trpc/trpc/pull/2024/files#diff-671e79295e2c31c75769e93c3c10ebaea24b2dc466d3a82d0865548a8a1e318dR10-R16

```
type GetHeadersFn = (opts: {
  op: Operation<unknown>;
}) => HTTPHeaders | Promise<HTTPHeaders>;
```

### Describe alternate solutions

@KATT mentioned

> you should be able to work around this by making a custom link that returns a httpLink with the headers you want. I realise this isn't ideal, but could get it working.

but i'm not entirely sure how that would go as the links are setup at a time when my header values do not exist.

Another way:
Thinking about the problem in a different way (might be a really bad idea). Would providing a custom fetcher option on @trpc/react-query be a solution? A bit similar to how graphql-codegen's react-query implementation lets users provide a custom fetcher (https://the-guild.dev/graphql/codegen/plugins/typescript/typescript-react-query#fetcher).

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

**Comment by skovhus** [comment]
Example code

```typescript
const terminationLinkExample: TRPCLink<RootRouter> = () => {
    return (runtime) => ({next, op}) => {
        return observable((observer) => {
            const unsubscribe = next(op).subscribe({
                next(value) {
                    parseOperationalContext(op)
                        .then(({accessToken, skipBatching}) => {
                            // FIXME: conditionally return httpLink and httpBatchLink
                            const headers = accessToken
                              ? { Authorization: `Bearer ${accessToken}` }
                              : {};

                            const link = skipBatching
                              ? httpBatchLink
                              : httpLink;

                            // But how do we correctly call the link? And how do we pass the runtime?
                        })
                        .catch((cause) => {
                            observer.error(TRPCClientError.from(cause))
                        })
                },
                complete() {
                    observer.complete()
                },
            })
            return unsubscribe
        })
    }
}
```

**Comment by skovhus** [comment]
> My use case: do some async work based on the OperationContext in order to compute headers that are passed down to either using a httpLink or httpBatchLink.

I believe I found a way to do this. Does the approach makes sense @KATT @sachinraja @JoshuaKGoldberg? Am I missing something? I must say my observable knowledge is thin, so I'm in doubt if I cancel the everything correctly.

```typescript
function terminationLink(): TRPCLink<RootRouter> {
  return (runtime: TRPCClientRuntime) =>
    ({ op }) => {
      return observable((observer) => {
        let observerCancelled = false;

        parseOperationalContext(op)
          .then(({ accessToken, requestCancelled, skipBatching }) => {
            if (observerCancelled || requestCancelled) {
              return;
            }

            const headers = accessToken
              ? { Authorization: `Bearer ${accessToken}` }
              : {};

            const link = skipBatching ? httpBatchLink : httpLink;
            link({
              url: 'https://api.my-awesome-trpc-powered-thing.io',
              headers,
            })(runtime)({ next, op }).subscribe(observer);
          })
          .catch((cause) => {
            observer.error(TRPCClientError.from(cause));
          });

        return () => {
          observerCancelled = true;
        };
      });
    };
}
```

**Comment by sachinraja** [comment]
That looks right @skovhus, but it should not be necessary to use a custom link there. I believe we could just have `headers()` accept an async function cc @KATT

**Comment by sachinraja** [comment]
That won't batch anything @skovus since you're creating a new link for each operation.

**Comment by skovhus** [comment]
Thanks for checking. I didn’t realize that. 

Any suggestion on how to achieve this with the current API? 

Or are you up for adding support for context awareness in the httpLink/httpBatchLink header functions like https://github.com/trpc/trpc/pull/2024 — I can maybe find some time to help out, but I would need some pointers.

**Comment by KATT** [comment]
Happy to accept a headers callback for `httpLink` and `httpBatchLink` if someone wants to do a PR.

Some ideal return types:

- `HttpBatchLinkOptions.headers`:  `Headers | (opts: { opList: Array<Operation<unknown>> } ) => MaybePromise<Headers>`
- `HttpLinkOptions.headers`: `Headers | (opts: { op: Operation<unknown> } ) => MaybePromise<Headers>`

We already have a `headers`-callback but it contain extra information about the call, so we should be able to add that with different interfaces for batch and single links w/o a breaking change

**Comment by skovhus** [comment]
> Happy to accept a headers callback for httpLink and httpBatchLink if someone wants to do a PR.

Thanks! When reading the code it seems this will change how http*Links behave as the headers will be resolved query time (as it needs to access the operation) and not when the link is created. But I guess that wouldn't be a breaking change?

**Comment by skovhus** [comment]
Do you believe what I'm trying to do in https://github.com/trpc/trpc/issues/4071#issuecomment-1488086215 is even possible with the current API?

**Comment by KATT** [comment]
> Do you believe what I'm trying to do in [#4071 (comment)](https://github.com/trpc/trpc/issues/4071#issuecomment-1488086215) is even possible with the current API?

Yes, I think so but it's ugly :)

**Comment by KATT** [comment]
Probably easier to try to add support for it in tRPC, I can try to get it merged and released tonight or tomorrow

**Comment by skovhus** [comment]
I'll try creating a draft PR so we can discuss this further.
