### ISSUE TITLE
bug: Redundant data in the returned payload for input-less queries

### ISSUE THREAD

**Issue by stychu** [trpc/trpc#4074]
### Provide environment information

```
 System:
    OS: macOS 11.7
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 144.06 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.21.2 - ~/.nvm/versions/node/v14.21.2/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 6.14.17 - ~/Library/pnpm/npm
  Browsers:
    Brave Browser: 111.1.49.120
    Chrome: 111.0.5563.110
    Firefox: 111.0
    Safari: 15.6.1
  npmPackages:
    @tanstack/react-query: 4.28.0 => 4.28.0 
    @trpc/client: 10.17.0 => 10.17.0 
    @trpc/react-query: 10.17.0 => 10.17.0 
    @trpc/server: 10.17.0 => 10.17.0 
    react: 17.0.2 => 17.0.2 
    typescript: 4.9.4 => 4.9.4 
```

### Describe the bug

Given this query procedure with no input param
```js
xyz: procedure.query(async ({ ctx }) =>
    ...
	return 'aa'
  ),
  ```

and calling that procedure with some options
```js
const query = api.xyz.useQuery(
    undefined,
    options,
  )
```
Payload of such batch request is bloated with unnecessary data:

`{"0":{"json":null,"meta":{"values":["undefined"]}}}`

Why? Do we need this? Can't we omit this payload for no query/mutation inputs???

### Link to reproduction

...

### To reproduce

..

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

**Comment by KATT** [comment]
Only happens when you use superjson AFAIK and has no real impact (AFAICT?), not sure if we should address even this.

**Comment by epicmau5time** [comment]
Just to piggyback on this, returning a list from the db with a ton of potential undefined fields, superjson just crams a ton of undefined's in meta:

Actual data: 1711 lines,
Data + Meta: 3028 lines.

Is there a way to prevent superjson from sending "undefined" meta fields or a middleware that runs after the fact to remove them?

![image](https://user-images.githubusercontent.com/13358902/230450921-b0519882-8fab-41d2-9590-a7d73b7dfef0.png)
