### ISSUE TITLE
feat: Static AppRouter type

### ISSUE THREAD

**Issue by Mo-Xiyad** [trpc/trpc#4075]
### Describe the feature you'd like to request

This feature request is based on a discussion between @KATT and @marcusradell: 
 https://discord.com/channels/867764511159091230/1077176270678401035/1088065480339763210

To sum it up, we don't use singletons in our codebase, but wrap all code in functions.
Since tRPC recommends `export type AppRouter = typeof appRouter`, we had to create our own custom TrpcRouter type.

Our solution stopped working when upgrading from tRPC v10.4.3 to v10.17.0 as `RouterDef` was no longer exported publicly. Getting more official support from tRPC would mean that we don't have to use types we don't fully understand, and enable more devs to use types that don't require singleton code.

A small note: it's not that bad that tRPC uses the singleton pattern. But the patterns leaks into the rest of our layers, which is the real issue.

### Describe the solution you'd like to see

Here is a minimal example repo that you can run (`npm i` and `npm run dev`):
https://github.com/WP-Tech-AB/trpc_app_router_type

The TrpcRouter is what we want better support for out of the box, and maybe a Trpc type. See this line for context:
https://github.com/WP-Tech-AB/trpc_app_router_type/blob/main/src/trpc.ts#L21

We used a bunch of `any` types as we aren't sure what to put there instead.

### Describe alternate solutions

Just make `RouterDef` a public export again.

### Additional information

We don't know enough to contribute a general solution, but we have everything of value in our example code, and you are free to pick what you want and use in tRPC.

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

**Comment by marcusradell** [comment]
I'm wondering if we could extend the `TrpcBuilder` that `initTRPC` exposes and have something like:

```ts
type ServiceRouter = {
  greeting: GreetingRouter // GreetingRouter omitted for brevity.
};

export const createTrpc = () => {
  return initTRPC
 .router<ServiceRouter>()
 .create({});
};

export type AppRouter = InferAppRouter<typeof createTrpc>;

export type Trpc = ReturnType<typeof createTrpc>;
```

**Comment by KATT** [comment]
https://github.com/WP-Tech-AB/trpc_app_router_type/pull/1
