### ISSUE TITLE
docs: deploy trpc with websocket to vercel

### ISSUE THREAD

**Issue by ManuRodgers** [trpc/trpc#4086]
### Area of Improvement

https://github.com/trpc/examples-next-prisma-websockets-starter 
In this project, can you guys provide the best practice in terms of how to deploy this project to vercel with normal http server and extra websocket server combined

### Link to related docs

https://trpc.io/docs/subscriptions

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing the suggested changes!

**Comment by KATT** [comment]
Vercel doesn't normal web servers / WSS

**Comment by ManuRodgers** [comment]
> 

so It is better to use something like [Render](https://render.com/) to deploy?

**Comment by ManuRodgers** [comment]
> Vercel doesn't normal web servers / WSS

so It is better to use something like [Render](https://render.com/) to deploy?
