### ISSUE TITLE
feat: create a server adapter for Next.js route handlers (app directory)

### ISSUE THREAD

**Issue by andrewbateman** [trpc/trpc#4088]
### Describe the feature you'd like to request

A function to generate a server handler for the Next.js's experimental app-directory route handlers (see https://beta.nextjs.org/docs/routing/route-handlers).

### Describe the solution you'd like to see

The current createNextApiHandler function in `@trpc/server/adapters/next` is written to handle "classic" Next.js API pages. With the move to the the new Next.js architecture there is a new API for handling requests and generating responses using web Request and Response objects  (see https://beta.nextjs.org/docs/routing/route-handlers). 

The ideal solution would be to implement a new handler generator `trpcNext.createNextRouteHandler` which takes the same arguments as `trpcNext.createNextApiHandler`. Under the hood it would export GET and POST handler functions to deal with queries and mutations respectively.

It might also be best to decompose the request/response handling into a `webHTTPRequestHandler` function similar to the current `nodeHTTPRequestHandler` function. 

Will also need to consider how this would affect middleware.

### Describe alternate solutions

The obvious workaround is to continue running tRPC endpoints under the 'classic' Next.js pages/api directory. However given the direction Next.js is heading this may mean missing out on new features as they are added to the new route handlers. 

You could also consider an adapter approach here - i.e. just write a thin wrapper that converts the new `NextRequest` objects into a `NextApiRequest`, hands off processing to the current `nodeHTTPRequestHandler`, then converts the resultant `NextApiResponse` into a `NextResponse` object for the route handler to return. 

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

**Comment by juliusmarminge** [comment]
You can use the `fetch` adapter for this, as route handlers build on web standard Request/Response:

```ts
import { fetchRequestHandler } from '@trpc/server/adapters/fetch';
import { NextRequest } from 'next/server';
import { appRouter } from '~/server/api/router';

const handler = (req: NextRequest) =>
  fetchRequestHandler({
    endpoint: '/api/trpc',
    req,
    router: appRouter,
    createContext: () => ({ ... })
  });

export { handler as GET, handler as POST };
```

**Comment by andrewbateman** [comment]
Awesome, thanks I totally missed this in the docs. Works perfectly - I am not surprised, it's trpc!
