### ISSUE TITLE
docs: algolia results are out of sync with docs

### ISSUE THREAD

**Issue by c-ehrlich** [trpc/trpc#4090]
### Area of Improvement

When searching for things in the docs, it returns results from pages that presumably contained those words in the past, but no longer do. Have noticed this several times in the last couple of days, below is one example. I guess it has not indexed some recent changes?

### Link to related docs

.

### Additional information

Example: Searching for "zod" finds a result in "Usage with React"
<img width="1392" alt="image" src="https://user-images.githubusercontent.com/8353666/227974744-2b75bdf1-ab41-4352-8573-3e22cded6fc9.png">

But clicking on this search result lands on a page without any mentions of "zod"
<img width="1148" alt="image" src="https://user-images.githubusercontent.com/8353666/227975226-f6402680-cc01-4a80-8339-f137264b1f04.png">

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing the suggested changes!

**Comment by sachinraja** [comment]
cc @KATT can we force it to re-index everything?

**Comment by KATT** [comment]
Ohhh I don't know what's going on, apparently it's been blocked for 23 days 👀 
<img width="1188" alt="CleanShot 2023-04-16 at 14 31 05@2x" src="https://user-images.githubusercontent.com/459267/232310092-27b35506-67ef-4695-8636-e1b397f58804.png">

**Comment by KATT** [comment]
Pressed the red button and seems to work now.

Thanks for bringing it up, I missed this somehow, feel free to @ me on things like this 😓
