### ISSUE TITLE
bug: useMutation does not trigger onError callback in react-native when calling procedure

### ISSUE THREAD

**Issue by sajadghawami** [trpc/trpc#4121]
### Provide environment information

  System:
    OS: macOS 13.2.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 36.42 MB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.14.2/bin/yarn
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
  Browsers:
    Chrome: 111.0.5563.146
    Firefox: 109.0.1
    Safari: 16.3

Also:

    "@tanstack/react-query": "^4.28.0",
    "@trpc/client": "^10.18.0",
    "@trpc/react-query": "^10.18.0",
    "@trpc/server": "^10.18.0",
    "react-native": "0.71.4",
    "react": "18.2.0",

### Describe the bug

I am using trpc@10 with **react-native**, and I have implemented the trpc-api with Next.js. I am trying to use a `trpc.wakeUp.useMutation` function to trigger an onError callback when there is an error during the mutation process.

The `wakeUp` procedure in the trpc API is defined as follows:

```tsx
wakeUp: publicProcedure.mutation(async () => {
  throw new TRPCError({
    code: "BAD_REQUEST",
    message: "not implemented",
  });
}),
```

When I use the following code with `trpc.wakeUp.useMutation`, the onError callback is not triggered:

```tsx
const wakeUp = trpc.wakeUp.useMutation({
  onSuccess: () => {
    console.log("waking up");
  },
  onError: () => {
    console.log("this will never be logged");
  },
});


const handleClick = () => wakeUp.mutate() // <--- will not fire the onError
```

However, when I use the following code with `wakeUp.mutate`, the onError callback is successfully triggered:

```tsx
const handleClick = () =>
  wakeUp.mutate(undefined, {
    onError: () => {
      console.log("this is being logged"); // <---- this will be fired
    },
  });
```

### Link to reproduction

/

### To reproduce

If necessary i can provide a reproducable example.

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

**Comment by juliusmarminge** [comment]
This is the intended behavior. `useMutation` doesn't fire the mutation - it's the `mutate` (or `mutateAsync`) that does that as you've shown in your snippets.

THe `useMutation.onError` is triggered for me when the mutation fires: https://stackblitz.com/edit/github-bnbbb1?file=src/pages/index.tsx

**Comment by sajadghawami** [comment]
@juliusmarminge 

Sorry for not being clear. I just updated my description:
In both cases i am invoking the `.mutate` function. In the case where i do not additionally pass **another** `onError`, the `onError` will not be called.
In the case where i do, the **second** `onError` will be called. 
This is definitely not the intended behaviour.

It seems that there might a bug in the trpc library that prevents the onError callback from being triggered when using the useMutation function. The `onSuccess` will be called without a problem.

**Comment by juliusmarminge** [comment]
It seems my stackblitz didn't quite save cause that's the behavior i intended to show. Fixed it here: https://stackblitz.com/edit/github-bnbbb1?file=src/pages/index.tsx

Also made a demo showing the behavior i think you're after:

https://user-images.githubusercontent.com/51714798/229278959-33ae59b0-aeb2-4aa6-adb1-9f1400992c4a.mp4

**Comment by sajadghawami** [comment]
@juliusmarminge thanks you very much for the effort!

The behavior you recorded is the exact behavior i am also experiencing with the *next-frontend*, but with *react-native* it does not fire.

For the react-native application, i am using the this context from the docs, that wrapps my whole application:

```tsx
export const TRPCProvider: React.FC<{ children: React.ReactNode }> = ({
  children,
}) => {
  const [queryClient] = React.useState(() => new QueryClient());
  const [trpcClient] = React.useState(() =>
    trpc.createClient({
      transformer: superjson,
      links: [
        httpBatchLink({
          url: `${getBaseUrl()}/api/trpc`,
        }),
      ],
    })
  );

  return (
    <trpc.Provider client={trpcClient} queryClient={queryClient}>
      <QueryClientProvider client={queryClient}>{children}</QueryClientProvider>
    </trpc.Provider>
  );
};


```

**Comment by juliusmarminge** [comment]
I only got an Expo app to test with but I am getting the same behavior there:

https://user-images.githubusercontent.com/51714798/229279598-359171fe-fe86-4479-a489-d4e86433074a.mp4

**Comment by sajadghawami** [comment]
My bad! Found something in my code that had side-effects.
