### ISSUE TITLE
docs: "try it out"-section with vanilla node

### ISSUE THREAD

**Issue by KATT** [trpc/trpc#4125]
### Area of Improvement

Our try-it-out section could have a tab bar with a vanilla example using Node.js

### Link to related docs

https://trpc.io/#try-it-out

### Additional information

- Should be linkable (e.g. `trpc.io/?try=node#try-it-out`
- Use minimal example? https://github.com/trpc/trpc/tree/main/examples/minimal

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR implementing the suggested changes!

**Comment by ConnectBhawna** [comment]
I would like to work in this issue
Can you please assign it to me :)

**Comment by Nick-Lucas** [comment]
Go for it! Just let us know if you decide you won't have time or will to finish it off, or un-assign yourself if you're able to 😄

**Comment by KATT** [comment]
Removing assignee as it's been a couple of weeks and it might discourage someone else to pick it up, but feel free to make a PR @ConnectBhawna :)
