### ISSUE TITLE
bug: body undefined in fastify

### ISSUE THREAD

**Issue by princejoogie** [trpc/trpc#4142]
### Provide environment information

```bash
System:
    OS: Linux 5.10 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
    CPU: (16) x64 AMD Ryzen 7 5800X 8-Core Processor
    Memory: 20.87 GB / 24.98 GB
    Container: Yes
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.15.0 - ~/.local/state/fnm_multishells/26222_1680742970821/bin/node
    Yarn: 1.22.19 - /mnt/c/Users/user/scoop/apps/nvm/current/nodejs/nodejs/yarn
    npm: 9.5.0 - ~/.local/state/fnm_multishells/26222_1680742970821/bin/npm
```

### Describe the bug

I think it's related to #1406 but has already been fixed. not really sure where the mistake is. let me explain what happens

when i try to add an input validation with zod in the router: `publicProcedure.input(z.object({url: z.string()})).mutation(...`, i get this:
![image](https://user-images.githubusercontent.com/47204120/230250038-d4e02391-7623-4994-9945-8cecbf3eab23.png)

but when i try log the `body`, `query`, and `params` in the context and in the router, i get this:
![image](https://user-images.githubusercontent.com/47204120/230249664-71c18390-a533-4d16-8149-0e9fa1e5bd7b.png)

what i dont understand is how is this a bad request when i can log it out without the input validator? it feels like it gets stripped away but it doesnt because i can log out the values?

---

another thing i tested is with this:

```ts
...
test: publicProcedure
  .input(z.object({ url: z.string() }).optional()) // i put optional so it goes through
  .mutation(({ input, ctx }) => {
    // here i log out the input and the request body
    return { input, ctx: { body: ctx.req.body } };
}),
```

when i try to hit this endpoint with postman, i get 
![image](https://user-images.githubusercontent.com/47204120/230251917-d39e3ed6-3fc0-42fd-93dc-e01a76c098ed.png)

voila, ctx body has content but input doesnt have.

for my context, it is defined like this:

```ts
export const createContext = async ({
  req,
  res,
}: CreateFastifyContextOptions) => {
  console.log("-------------");
  console.log("THIS IS INSIDE THE CONTEXT");
  console.log("req.body", req.body);
  console.log("req.query", req.query);
  console.log("req.params", req.params);

  const ctx: CreateContextOptions = {
    req,
    res,
    prisma,
  };
  return ctx;
};
```

### Link to reproduction

n/a

### To reproduce

id be happy to add a reproduction when this gets noticed

### Additional information

This is the error when i just `return error` in the `errorFormatter`

```bash
{
  "level": 50,
  "time": 1680741236320,
  "pid": 23414,
  "hostname": "DESKTOP-7JIP2D6",
  "reqId": "req-3",
  "req": {
    "method": "POST",
    "url": "/trpc/conclude.create",
    "hostname": "localhost:4000",
    "remoteAddress": "127.0.0.1",
    "remotePort": 53330
  },
  "res": {
    "statusCode": 500
  },
  "err": {
    "type": "TypeError",
    "message": "Cannot read properties of undefined (reading 'httpStatus')",
    "stack": "TypeError: Cannot read properties of undefined (reading 'httpStatus') at <anonymous> (/home/joogie/Documents/cod
es/node/conclusion/node_modules/.pnpm/@trpc+server@10.18.0/node_modules/@trpc/server/dist/config-055ae8e4.js:64:29) at Array.m
ap (<anonymous>) at Object.getHTTPStatusCode (/home/joogie/Documents/codes/node/conclusion/node_modules/.pnpm/@trpc+server@10.
18.0/node_modules/@trpc/server/dist/config-055ae8e4.js:61:38) at endResponse (/home/joogie/Documents/codes/node/conclusion/nod
e_modules/.pnpm/@trpc+server@10.18.0/node_modules/@trpc/server/dist/resolveHTTPResponse-94b380d2.js:46:29) at Object.resolveHT
TPResponse (/home/joogie/Documents/codes/node/conclusion/node_modules/.pnpm/@trpc+server@10.18.0/node_modules/@trpc/server/dis
t/resolveHTTPResponse-94b380d2.js:195:16) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at fas
tifyRequestHandler (/home/joogie/Documents/codes/node/conclusion/node_modules/.pnpm/@trpc+server@10.18.0/node_modules/@trpc/se
rver/dist/adapters/fastify/index.js:25:20) at Object.<anonymous> (/home/joogie/Documents/codes/node/conclusion/node_modules/.p
npm/@trpc+server@10.18.0/node_modules/@trpc/server/dist/adapters/fastify/index.js:67:9)"
  },
  "msg": "Cannot read properties of undefined (reading 'httpStatus')"
}
```

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

**Comment by princejoogie** [comment]
UPDATE: commenting the transformer out from the context fixes the problem

![image](https://user-images.githubusercontent.com/47204120/230315862-e5521144-2674-452a-93f9-d558f7db4da2.png)

**Comment by KATT** [comment]
When you use superjson, it expects a format compliant to superjson; instead of using postman, make a trpc client and play with that and maybe copy the inputs it creates.

This is not a bug.
