### ISSUE TITLE
feat: export `class TRPCBuilder` for convenience of writing wrapper code

### ISSUE THREAD

**Issue by NexZhu** [trpc/trpc#4145]
### Describe the feature you'd like to request

export `class TRPCBuilder` in `initTRPC.ts` for convenience of writing wrapper code.

### Describe the solution you'd like to see

export `class TRPCBuilder` in `initTRPC.ts` for convenience of writing wrapper code.

### Describe alternate solutions

It's hard to write types extending TRPCBuilder without it being exported

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

**Comment by juliusmarminge** [comment]
Can you give an example of such wrappers?

**Comment by sachinraja** [comment]
please re-open with an example

**Comment by NexZhu** [comment]
@juliusmarminge @sachinraja 
Hi, this is an example integrating tRPC with [Effect](https://github.com/Effect-TS), a FP and effect library.
I'm using forked version of tRPC as it won't be possible to export correct types without importing types such as `TRPCBuilder`
https://github.com/daotl/effect-libs/blob/main/packages/trpc/_src/effectify.ts
