### ISSUE TITLE
feat: Ability to handle error via status code

### ISSUE THREAD

**Issue by roninjin10** [trpc/trpc#4154]
### Describe the feature you'd like to request

Oftentimes I want to proxy a status code I recieved fetching from another endpoint.   To handle this I made this utility.   I think it would be useful to add to trpc core library.   

```typescript
static readonly handleStatus = (statusCode: number, cause?: string) => {
    // BAD_REQUEST	The server cannot or will not process the request due to something that is perceived to be a client error.	400
    // UNAUTHORIZED	The client request has not been completed because it lacks valid authentication credentials for the requested resource.	401
    // FORBIDDEN	The server was unauthorized to access a required data source, such as a REST API.	403
    // NOT_FOUND	The server cannot find the requested resource.	404
    // TIMEOUT	The server would like to shut down this unused connection.	408
    // CONFLICT	The server request resource conflict with the current state of the target resource.	409
    // PRECONDITION_FAILED	Access to the target resource has been denied.	412
    // PAYLOAD_TOO_LARGE	Request entity is larger than limits defined by server.	413
    // METHOD_NOT_SUPPORTED	The server knows the request method, but the target resource doesn't support this method.	405
    // CLIENT_CLOSED_REQUEST	Access to the resource has been denied.	499
    // INTERNAL_SERVER_ERROR	An unspecified error occurred.	500
    if (statusCode === 200) {
      return
    }
    if (statusCode === 400) {
      return new TRPCError({
        code: 'BAD_REQUEST',
        message: 'Bad request',
        cause,
      })
    }
    if (statusCode === 401) {
      return new TRPCError({
        code: 'UNAUTHORIZED',
        message: 'Unauthorized',
        cause,
      })
    }
    if (statusCode === 403) {
      return new TRPCError({
        code: 'FORBIDDEN',
        message: 'Forbidden',
        cause,
      })
    }
    if (statusCode === 404) {
      return new TRPCError({
        code: 'NOT_FOUND',
        message: 'Not found',
        cause,
      })
    }
    if (statusCode === 408) {
      return new TRPCError({
        code: 'TIMEOUT',
        message: 'Timeout',
        cause,
      })
    }
    if (statusCode === 409) {
      return new TRPCError({
        code: 'CONFLICT',
        message: 'Conflict',
        cause,
      })
    }
    if (statusCode === 412) {
      return new TRPCError({
        code: 'PRECONDITION_FAILED',
        message: 'Precondition failed',
        cause,
      })
    }
    if (statusCode === 413) {
      return new TRPCError({
        code: 'PAYLOAD_TOO_LARGE',
        message: 'Payload too large',
        cause,
      })
    }
    if (statusCode === 405) {
      return new TRPCError({
        code: 'METHOD_NOT_SUPPORTED',
        message: 'Method not supported',
        cause,
      })
    }
    if (statusCode === 499) {
      return new TRPCError({
        code: 'CLIENT_CLOSED_REQUEST',
        message: 'Client closed request',
        cause,
      })
    }
    if (statusCode === 500) {
      return new TRPCError({
        code: 'INTERNAL_SERVER_ERROR',
        message: 'Internal server error',
        cause,
      })
    }
  }
```

### Describe the solution you'd like to see

A utility that turns a status code into a TRPCError

### Describe alternate solutions

There are other viable alternatives
- utility that returns only the code.   e.g. getCode(400) === 'BAD_REQUEST'
- Enhance TRPCError to take a code for status instead of string request

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

**Comment by Nick-Lucas** [comment]
Since it doesn’t require any internals, my opinion is it could as easily be a community library.

The other aspect of this, is it’s so trivial for anyone to write this in the most ergonomic way for their use case, that if we provided it most people would just write it themselves without checking if we provide it. 

Example of an alternate use case is you just don’t always want to map error codes 1-1 from an external service. A 401/403 could be a server error because an API key is broken for instance.

**Comment by bautistaaa** [comment]
going to close this, i agree with @Nick-Lucas but if anyone else on the core team feels strongly feel free to reopen

**Comment by mmkal** [comment]
I don't feel strongly about this in general, but it's worth noting that this could only be a community library if `TRPCError` were also in its own library.

**Comment by Nick-Lucas** [comment]
> I don't feel strongly about this in general, but it's worth noting that this could only be a community library if `TRPCError` were also in its own library.

You can use a peerDependency for this no? Just make the @trpc/server package a peer dep and it can be consumed while not dragging in the whole thing as a duplicate dep
