### ISSUE TITLE
bug: Onerror doesn't trigger after fetching multiple time

### ISSUE THREAD

**Issue by zwelhtetyan** [trpc/trpc#4163]
### Provide environment information

  System:
    OS: Linux 5.19 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
    CPU: (4) x64 Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz
    Memory: 2.14 GB / 7.65 GB
    Container: Yes
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.15.1 - ~/.nvm/versions/node/v16.16.0/bin/npm
  Browsers:
    Chrome: 111.0.5563.64
    Firefox: 111.0.1
  npmPackages:
    @tanstack/react-query: ^4.28.0 => 4.28.0 
    @trpc/client: ^10.18.0 => 10.18.0 
    @trpc/next: ^10.18.0 => 10.18.0 
    @trpc/react-query: ^10.18.0 => 10.18.0 
    @trpc/server: ^10.18.0 => 10.18.0 
    next: ^13.2.4 => 13.2.4 
    react: 18.2.0 => 18.2.0 
    typescript: ^5.0.2 => 5.0.3 

### Hi , I am new to trpc

> OnError is not trigger immediately. It does trigger after requesting multiple times.

**server**

```tsx
 getNote: protectedProcedure
    .input(z.object({ noteId: z.string(), topicName: z.string() }))
    .query(async ({ ctx, input: { noteId, topicName } }) => {
      const note = await ctx.prisma.note.findUnique({
        where: { id: noteId },
        include: { topic: true },
      });

      if (
        note?.authorId === ctx.session.user.id &&
        topicName === note?.topic.title
      ) {
        return note;
      } else {
        throw new TRPCError({
          code: "FORBIDDEN",
          message: "You can only get you own note",
        });
      }
    }),
```

**client**
```tsx
  const { data: note, isLoading: loadingNote } = api.note.getNote.useQuery(
    {
      noteId: router.query.noteId as string,
      topicName: selectedTopic.title as string,
    },
    {
      enabled: sessionData?.user !== undefined,
      onError: (err) => {
        if (err.data?.httpStatus === 403) {
          router.push("/");
        }
      },
    }
  );
```

![Screenshot from 2023-04-09 15-37-52](https://user-images.githubusercontent.com/89287841/230764460-ff515c0d-96c7-4edb-b6e8-1a738e7590ff.png)

Onerror is trigger after it.

### Link to reproduction

...

### To reproduce

...

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

**Comment by QuiiBz** [comment]
Hi, could you share an example reproduction link (e.g using Stackblitz, or a GitHub repository)?

**Comment by KATT** [comment]
This is likely due to automatic retries in React query

**Comment by zwelhtetyan** [comment]
> Hi, could you share an example reproduction link (e.g using Stackblitz, or a GitHub repository)?

Sure. https://github.com/zwelhtetyan/fullstack-t3-app

**Comment by zwelhtetyan** [comment]
> This is likely due to automatic retries in React query

Oh yep, my bad, I didn't notice that. Thanks @KATT .
