### ISSUE TITLE
docs: Links to React Query documentation are dead

### ISSUE THREAD

**Issue by mozzius** [trpc/trpc#4165]
### Area of Improvement

Seems like the Tanstack folks have changed around the URL structure of their documentation sites. There are 35 links in the codebase to `https://react-query.tanstack.com`, which all lead to the homepage of the v3 site. The current correct link is `https://tanstack.com/query/v4`.

We just need to go through and find the up to date link. Probably pretty easy to find and replace but it'd be good to check manually that the updated links are correct.

Note - this is most impactful in documentation, where people are likely to click on them, but a lot of instances are in JSDoc comments. Both should probably be fixed.

### Link to related docs

https://trpc.io/docs/nextjs/server-side-helpers

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR implementing the suggested changes!

**Comment by Nick-Lucas** [comment]
Thanks, done a quick PR for this 👍
