### ISSUE TITLE
feat: trpc wrapped/typed version of useIsMutating

### ISSUE THREAD

**Issue by zzzev** [trpc/trpc#4211]
### Describe the feature you'd like to request

TanStack Query provides a [`useIsMutating` hook](https://tanstack.com/query/v4/docs/react/reference/useIsMutating), which takes an options argument that can contain [mutation filters](https://tanstack.com/query/v4/docs/react/guides/filters#mutation-filters).

It would be great if trpc provided a typed version of this corresponding to the routes on your trpc router.

### Describe the solution you'd like to see

For example: if I have some mutation that I use by invoking `trpc.myThing.update.useMutation()`, I'd love to be able to do `trpc.myThing.update.useIsMutating()` and have that be the equivalent of `useIsMutating([/* insert trpc generated mutation key here */])`.

### Describe alternate solutions

You can use the `useIsMutating` hook and figure out the right filter that corresponds to what trpc generates, but that's a lot less convenient. I like how in most situations trpc abstracts away the need to know about those keys, would be great to do that here too.

### Additional information

I am open to trying to implement this, but would love any pointers on where to start.

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

**Comment by juliusmarminge** [comment]
You should use the [`getQueryKey`](https://trpc.io/docs/reactjs/getquerykey) for that.

https://github.com/trpc/trpc/blob/c62df7f95a128ab914a2e40413d3b75598231c85/packages/tests/server/react/getQueryKey.test.tsx#L341-L342
