### ISSUE TITLE
docs: invalid status code in middleware

### ISSUE THREAD

**Issue by alishi973** [trpc/trpc#4212]
### Area of Improvement

The TRPC documentation suggests that middleware can throw a `TRPCError` instance with a specific status code set to return an appropriate error response to the client.

However, there is a bug (or maybe using invalid tools) where all errors thrown from middleware are caught by TRPC and returned as a generic "Internal Server Error" response with a `500` status code, regardless of the specific status code set in the TRPCError instance.

IMO, This behavior is incorrect and may be confusing for developers and end-users.

Could you provide guidance on how to work around this issue until it is resolved, or suggest an alternative solution that would allow middleware to return appropriate error responses with specific status codes?

### Link to related docs

https://trpc.io/docs/server/middlewares

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR implementing the suggested changes!

**Comment by Nick-Lucas** [comment]
This is an interesting point. Feel free to open a PR proposing a fix as it should be quite a simple piece, we have #3496 (drop a note in there too) coming up and it seems a very sensible breaking change to me

for now you can work around the behaviour in errorFormatter

**Comment by KATT** [comment]
- If you throw a `TRPCError` in a middleware, it should go straight through without us touching it.
- If you throw anything else, it'll be an `INTERNAL_SERVER_ERROR` with the original error as `error.cause` in the error formatter (where you can remap it to whatever you want)

If the above doesn't align what we do in practice or in the docs, we should fix it ☺

**Comment by Nick-Lucas** [comment]
So it sounds like we may need a reproduction @alishi973, are you able to share any extra details or code?

**Comment by alishi973** [comment]
Yeah, that's right, I've used `TRPCError` that was imported from the `trpc` library which is not the correct tool, and must use `@trpc/server` instead.

is it possible to rename or change that to avoid any confusion?

BTW, Thanks for your time ✌️
