### ISSUE TITLE
bug: directed to invalid href on searching inferring types

### ISSUE THREAD

**Issue by hussamkhatib** [trpc/trpc#4215]
### Provide environment information

N/A

### Describe the bug

Check `To Reproduce` section.

### Link to reproduction

N/A

### To reproduce

- Go to [trpc.io](https://trpc.io/)
- type "infer-types" and select the first option.
- URL gets changed to [trpc.io/docs/server/infer-types](https://trpc.io/docs/server/infer-types) and a `Page Not Found` message.
- It get's fixed on refresh though as the the route is changed to [trpc.io/docs/client/infer-types](https://trpc.io/docs/client/infer-types) 

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

**Comment by KATT** [comment]
kicked it
