### ISSUE TITLE
docs: the example will be better for improving the UI

### ISSUE THREAD

**Issue by quan-nh2** [trpc/trpc#4228]
### Area of Improvement

The template examples/next-prisma-starter should be improved:
- The layout is quite simple.
- Have some bugs on the client side (below example):
![Screenshot 2023-04-21 at 14 36 30](https://user-images.githubusercontent.com/22234293/233573238-815b47b1-09cc-4add-bf88-71ecdd1bee79.png)

Do you think we should have a good design for the example? 

### Link to related docs

https://github.com/trpc/trpc/tree/main/examples/next-prisma-starter

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR implementing the suggested changes!

**Comment by miguevelasquez1** [comment]
Yes, I'd be down to file a PR implementing the suggested changes!
