### ISSUE TITLE
bug: Disabling batching breaks serialization of string values

### ISSUE THREAD

**Issue by sudo97** [trpc/trpc#4243]
### Provide environment information

```
  System:
    OS: macOS 13.0.1
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 2.14 GB / 16.00 GB
    Shell: 3.5.1 - /usr/local/bin/fish
  Binaries:
    Node: 16.18.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.2 - /usr/local/bin/npm
  Browsers:
    Chrome: 112.0.5615.137
    Firefox: 109.0
    Safari: 16.1
  npmPackages:
    @tanstack/react-query: ^4.18.0 => 4.29.3 
    @trpc/client: ^10.21.1 => 10.21.1 
    @trpc/next: ^10.21.1 => 10.21.1 
    @trpc/react-query: ^10.21.1 => 10.21.1 
    @trpc/server: ^10.21.1 => 10.21.1 
    next: ^13.2.1 => 13.3.1 
    react: ^18.2.0 => 18.2.0 
    typescript: ^4.8.3 => 4.9.5
```

### Describe the bug

When batching is disabled, and the input is supposed to be string (defined with `z.string()`), it is unable properly parse the request body.
The error:

```
{
    "error": {
        "message": "Unexpected number in JSON at position 1",
        "code": -32700,
        "data": {
            "code": "PARSE_ERROR",
            "httpStatus": 400,
            "stack": "TRPCError: Unexpected number in JSON at position 1\n    at getRawProcedureInputOrThrow (file:///PATH/trpc-next-minimal/node_modules/@trpc/server/dist/resolveHTTPResponse-6c8965e4.mjs:24:15)\n    at resolveHTTPResponse (file:///PATH/trpc-next-minimal/node_modules/@trpc/server/dist/resolveHTTPResponse-6c8965e4.mjs:90:26)\n    at file:///PATHs/trpc-next-minimal/node_modules/@trpc/server/dist/nodeHTTPRequestHandler-2718f9d8.mjs:61:30\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async file:///PATH/trpc-next-minimal/node_modules/@trpc/server/dist/adapters/next.mjs:39:9"
        }
    }
}
```

### Link to reproduction

https://stackblitz.com/edit/github-ferjpz?file=src/utils/trpc.ts

### To reproduce

In the stackblitz sandbox, click "As string", observe error. Then basically the same thing, but payload is passed as object with one field, and no problem.

### Additional information

Seems like adding [data transformers](https://trpc.io/docs/server/data-transformers) can fix the issue. But it'd still be great not to have the need to apply this solution

### 👨‍👧‍👦 Contributing

- [x] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

**Comment by Nick-Lucas** [comment]
That's weird, thanks for the reproduction. It also seems to occur with the useMutation hook:

https://stackblitz.com/edit/github-ferjpz-tfao48?file=src/pages/index.tsx 

I'm going to tag this as a bug since it does look like an issue with our handling of strings specifically.

**Comment by Nick-Lucas** [comment]
That's sounds conceivable, the network debugger is definitely showing the right thing so if the Next backend is intercepting and we're just checking if an input is a string to try parsing, this error could occur.

Do let us know the results of your testing, it's greatly appreciated!

If you fancy it you could open a PR with a failing test? Welcome to fix the issue too if you're up for it!

**Comment by sudo97** [comment]
So according to [this](https://nextjs.org/docs/api-routes/request-helpers):
> req.body - An object containing the body parsed by content-type, or null if no body was sent

So, I tried to remove `content-type` from headers [here](https://github.com/trpc/trpc/blob/1b879e18219015f6312762d68f210a7a159afd4d/packages/client/src/links/internals/httpUtils.ts#L140)

And it seems to resolve the issue. I am unsure though if this is a viable solution. If I update `HTTPRequestOptions` to have some options such as `disableApplicationJson?: boolean`, and then `createTRPCNext` could pass `true` in this case, would that be a good solution? @Nick-Lucas

**Comment by sudo97** [comment]
Oh, wait I think I might just disable body-parsing per-route, that should be easiest

**Comment by sudo97** [comment]
So I think options are:
- Make a PR, updating Docs, saying that api route should also include this code:
```ts
export const config = {
  api: {
    bodyParser: false,
  },
}
```
- Do some hacky stuff like override content-type for this case

I don't mind making either PR, but I'd love some input first, @Nick-Lucas

**Comment by Nick-Lucas** [comment]
I think this might be an area where one of the guys who is most familiar with these internals should make the call on how it's built.

To not waste your effort, if you just opened a PR with a failing test, that would give us something to work against? We should have plenty of tests already for you to base the reproduction on under the `packages/tests` directory

**Comment by sudo97** [comment]
I'd love to contribute by fixing, but okay, let me try making a failing test as a start

**Comment by Nick-Lucas** [comment]
I definitely won't stop you attempting a fix! Adding new config options seems the wrong way though, so I don't want to waste your time if we're not sure the correct solution.

Maybe we need to plug in to Next slightly differently to get the raw value, or we should be checking a string starts and ends with " before trying to parse it?

**Comment by sudo97** [comment]
But then question arises whether data transformers will work with this approach

**Comment by Nick-Lucas** [comment]
> But then question arises whether data transformers will work with this approach

Very good question, though I'd theorise they would also be broken right now, so it needs factoring into any tests and fixes which get written

**Comment by sudo97** [comment]
They worked for me initially, I even thought using them as a solution to my problem.  But that's probably because superjson wraps your data into `{ json: <content>}`, hence it's not a serialized string, rather serialized object. So I guess not every transformer would work.

**Comment by sudo97** [comment]
I'll go to discord now to connect with you guys, and discuss the changes I'm attempting to make

**Comment by sudo97** [comment]
@Nick-Lucas  can I violate the rules just this time and `@` you in the thread?
