### ISSUE TITLE
docs: stop over-using destructuring

### ISSUE THREAD

**Issue by KATT** [trpc/trpc#4250]
### Area of Improvement

Let's stop overusing destructuring. We do this in the docs and probably in the codebase too.

I'm going to quote myself (like a twat, haha): 
> If you only use a prop once, all you're doing by destructing it is to add extra code, make discoverability of what else is on the object harder and add indirection on where the variable comes from.
>
> — https://twitter.com/alexdotjs/status/1635012632116854784

That said, most of these examples are because of me, so no one else to blame here than yours truly :D

 

General rule of thumb:

- Destructuring in function arguments is not ok
- Destructuring in body is ok
- Don't destruct a prop if it's only used once

### Link to related docs

https://trpc.io/docs

### Additional information

Example in https://trpc.io/docs/server/middlewares#logging

**Existing / bad**
```tsx
const loggerMiddleware = middleware(async ({ path, type, next }) => {
  const start = Date.now();
  const result = await next();
  const durationMs = Date.now() - start;
  result.ok
    ? logMock('OK request timing:', { path, type, durationMs })
    : logMock('Non-OK request timing', { path, type, durationMs });
 
  return result;
});
```

**Good:**

```ts
const loggerMiddleware = middleware(async (opts) => {
  const start = Date.now();

  const result = await opts.next();

  const durationMs = Date.now() - start;
  const meta = { path: opts.path, type: opts.type, durationMs }; 
 
  result.ok
    ? console.log('OK request timing:', meta)
    : console.error('Non-OK request timing', meta);
 
  return result;
});
```

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR implementing the suggested changes!

**Comment by ahmedhesham6** [comment]
Yes, I'd be down to file a PR implementing the suggested changes!

**Comment by ahmedhesham6** [comment]
According to "Don't destruct a prop if it's only used once" this piece of code should be modified

<img width="763" alt="Screenshot 2023-04-26 at 2 55 57 AM" src="https://user-images.githubusercontent.com/23265119/234438955-af9abce5-e5a8-4f1b-b5d2-4eea9eb48039.png">

but for illustration purposes the type of the input is shown, so do you prefer
- leaving it as it is 
- don't destruct and show the whole type

**Comment by KATT** [comment]
@ahmedhesham6 yes

I'd prefer

```
const isAuthed = t.middleware((opts) => {
  if (!opts.ctx.user?.isAdmin) {
    throw new TRPCError({ code: 'UNAUTHORIZED' });
  }
  return opts.next({
    ctx: {
      user: opts.ctx.user,
    },
  });
});
```

.... or:

```ts
const isAuthed = t.middleware((opts) => {
  const { ctx } = opts;
  if (!ctx.user?.isAdmin) {
    throw new TRPCError({ code: 'UNAUTHORIZED' });
  }
  return opts.next({
    ctx: {
      user: opts.ctx.user,
    },
  });
});
```

**Comment by KATT** [comment]
If you wanna contribute to this, I prefer 10 small PRs than 1 big one :) 

Do it incrementally so one mistake doesn't block the PR from being merged
