### ISSUE TITLE
bug:  trpc alpha versions are released under tag `latest`

### ISSUE THREAD

**Issue by sannajammeh** [trpc/trpc#4264]
### Provide environment information

not needed.

### Describe the bug

@trpc/* packages show latest package being alpha versions. This is not very good for users of `upgrade-interactive` in yarn and pnpm. And even worse for users using `yarn upgrade --latest` or `pnpm upgrade --latest`, they are automatically on alpha versions.

Is this intentional? In that case package version should be a stable version so package managers can autoupdate these deps using semver. 

Because of this, updating to a semver stable version of trpc in a monorepo is as follows:
1. Run `pnpm upgrade --interactive --latest -r`
2. Discover that `@trpc/*` deps can only be upgraded to `-alpha.X`
3. Go to npm and scroll down a long list to finally see latest stable version
4. Cd into each directory in the monorepo which needs trpc and run install script with stable version

Ideally, this should only require step 1.

### Link to reproduction

https://www.npmjs.com/package/@trpc/server?activeTab=versions

### To reproduce

Go to npm https://www.npmjs.com/package/@trpc/server?activeTab=versions

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

**Comment by KATT** [comment]
Fixed. Sorry about that

```sh
npm dist-tag add @trpc/server@10.21.2 latest
npm dist-tag add @trpc/react-query@10.21.2 latest
npm dist-tag add @trpc/client@10.21.2 latest
npm dist-tag add @trpc/next@10.21.2 latest
```
