### ISSUE TITLE
feat: improve our releases

### ISSUE THREAD

**Issue by KATT** [trpc/trpc#4266]
### Describe the feature you'd like to request

I want to run `pnpm lerna publish` and have the releases just work

### Describe the solution you'd like to see

Currently, the git tagging is broken, and it seems every time I touch our scripts, I mess something up: https://github.com/trpc/trpc/blob/ea6da3efd7a65b21d70b32efe9dea907747e5337/package.json#L27-L28

### Describe alternate solutions

#162

### Additional information

The complexity started with the the `prepack`-script that I added that is to run to pin all dependencies to a strict trpc version - e.g. sets `@trpc/client` to expect _exactly_ the equivalent of `@trpc/server` (`@trpc/client@10.21.2` has a `peerDependencies` with `@trpc/server@10.21.2` without any `^10.21.2`)

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

**Comment by TkDodo** [comment]
Off the top of my head, you shouldn't need that custom script with pnpm workspaces and `workspace:*` dependencies - pnpm replaces them automatically during build. We do that in TanStack Query and it works well. 

https://pnpm.io/workspaces#publishing-workspace-packages
