### ISSUE TITLE
feat: @trpc/client: Direct server-side link

### ISSUE THREAD

**Issue by dtinth** [trpc/trpc#4275]
### Describe the feature you'd like to request

I would like a link for `createTRPCProxyClient` that behaves like `router.createCaller`.

This allows a server-side rendered web app to choose whether to use a remote backend or a local backend. See below picture for explanation of the scenario.

<img width="1153" alt="image" src="https://user-images.githubusercontent.com/193136/235290100-47a18440-0a17-4acf-8218-69524cdfe6c3.png">

### Describe the solution you'd like to see

Basic usage:

```ts
// Server-side code
import { createTRPCProxyClient } from '@trpc/client';
import { directLink } from '@trpc/client/????';
import type { AppRouter } from '../server';

function createServerSideClient(authToken?: string) {
  return createTRPCProxyClient<AppRouter>({
    links: [
      directLink({
        router: () => import('../server').then(s => s.AppRouter),
        context: { authToken },
      }),
    ],
  });
}
```

Usage in above scenario

```ts
// Server-side code
import { createTRPCProxyClient, httpLink } from '@trpc/client';
import { directLink } from '@trpc/client/????';
import type { AppRouter } from '../server';

function createServerSideClient(authToken?: string) {
  return createTRPCProxyClient<AppRouter>({
    links: [
      process.env.BACKEND
        ? httpLink({
            url: process.env.BACKEND,
          }),
        : directLink({
            router: () => import('../server').then(s => s.AppRouter),
            context: { authToken },
          }),
    ],
  });
}
```

### Describe alternate solutions

**Alternative A:** We could make an HTTP request to localhost.

- Overhead of making an actual HTTP request (albeit to localhost).
- Sometimes it is unclear which port the server is running on, especially in serverless providers like Vercel/Netlify. On such environments, detecting which port the server is running in may require brittle code that peeks into the serverless runtime’s implementation details. Alternatively we can run a secondary web server from the application side, which could mean more complex code and overhead.

**Alternative B:** Hijack `httpLink`’s `fetch` implementation to send the request directly to the tRPC router instead of making a network call.

- This is what we are using. It is very hacky but works flawlessly!

```ts
import { fetchRequestHandler } from '@trpc/server/adapters/fetch'
import { createTRPCProxyClient, httpLink } from '@trpc/client';
import type { AppRouter } from '../server';

export function createServerSideClient(authToken?: string) {
  const url = process.env.BACKEND || 'http://fake'

  return createTRPCProxyClient<AppRouter>({
    links: [
      httpBatchLink({
        url,
        headers: authToken ? {
          authorization: `Bearer ${authToken}`
        } : {},
        fetch: async (input, init) => {
          if (
            typeof input === 'string' &&
            input.startsWith('http://fake')
          ) {
            const request = new Request(input, init as RequestInit)
            const { createContextFromRequest, AppRouter } = await import('../server')
            return fetchRequestHandler({
              endpoint: prefix,
              req: request,
              router: AppRouter,
              createContext: ({ req }) => {
                return createContextFromRequest(req)
              },
            })
          }
          return fetch(input, init as RequestInit)
        },
      }),
    ],
  })
}
```

### Additional information

See actual implementation here

- https://github.com/creatorsgarten/contentsgarten/blob/258e746519b49e49b93e81e0d19f90553d51f5b4/packages/server-utils/src/index.ts#L9-L34
- https://github.com/creatorsgarten/contentsgarten/blob/258e746519b49e49b93e81e0d19f90553d51f5b4/packages/contentsgarten/src/Contentsgarten.ts#L41-L61

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

**Comment by KATT** [comment]
Duplicate of #3768

You made a really good case though, maybe you wanna emphasize that over there? :)

**Comment by dtinth** [comment]
@KATT Sure, will do. Thanks for the pointer, I didn’t thought of the word "local link."
