### ISSUE TITLE
feat: trpc is assuming the type of the req.query property on all adapters

### ISSUE THREAD

**Issue by fallenfreq** [trpc/trpc#4280]
### Provide environment information

N/A

### Describe the bug

trpc is assuming the type of the req.query property if there is one on all adapters.

I have made an adapter for an augmented node server similar to the express adapter but the AugmentedRequest type passed to NodeHTTPHandlerOptions is not assignable to the type '{ query?: ParsedQs}` used in NodeHTTPRequest type. This is because my query property could be an array like this
>['a', 'b', 'c']

if the search params where like this
> ?0='a'&1='b'&2='c'

It also essentially allows an array to be an array of
>(string | ParsedQs)[]

instead of just
>string[] | ParsedQs[]

```ts
const createMyServerMiddleware = <TRouter extends AnyRouter>(
    opts: NodeHTTPHandlerOptions<TRouter, AugmentedRequest, AugmentedResponse>): MwCall =>
  async function(req, res) {
    await nodeHTTPRequestHandler({req, res, ....})
  }
```

Changing the req.query on my augmented server would be a breaking change and I can't actually find any where in trpc that the req.query that it creates would be accessible to me anyway

The nodeHTTPRequestHandler function in the nodeHTTPRequestHandler file is where the assumption is made despite req.query of type ParsedQs being an express property and not a node server property. Most other servers are probably compatible with this signature but mine is not because URLSearchParams can not take an array and because of the type miss match mentioned above.

```ts
const query = opts.req.query ? new URLSearchParams(opts.req.query) : new URLSearchParams(opts.req.url.split('?')[1])
const req = {
    method: opts.req.method,
    headers: opts.req.headers,
    query,
    body: bodyResult.ok ? bodyResult.data : undefined
}
```

I'm not sure what the wider implications are of just always creating the query property and removing  { query?: ParsedQs } from the NodeHTTPRequest Type be. Is it only there for the ConnectMiddleware<NodeHTTPRequest, NodeHTTPResponse> type used by the middleware property that can be passed to the nodeHTTPRequestHandler? Just to clarify, Im not talking about the middleware used in procedures here because that is obviously passed a context instead. 

If so, it's also a little confusing that the nodeHTTPRequestHandler middleware function's req and res are typed as NodeHTTPRequest and NodeHTTPResponse even though it's passed the same req and res as the nodeHTTPRequestHandler. The types can't be trusted there. It assumes there might be a property called query and that it must be of a certain type despite a plain node server never having a query property and it is unaware of any of the other properties that might be on the augmented req and res that where passed to the nodeHTTPRequestHandler. 

### Link to reproduction

N/A

### To reproduce

Copy the standalone adapter and Pass NodeHTTPHandlerOptions a request type with {query: string[]}

 ```ts
NodeHTTPHandlerOptions<TRouter, http.IncomingMessage & {query:string[]}, http.ServerResponse>;
```
Then use createHTTPHandler function to create your own HTTP Server. With a mock query value for the req

```ts
import { inferAsyncReturnType, initTRPC } from '@trpc/server';
import { createHTTPHandler } from '@trpc/server/adapters/standalone';
import { createServer } from 'http';

const handler = createHTTPHandler({
  router: appRouter,
  createContext() {
    return {};
  },
});

createServer((req, res) => {
  // mock a query value for the req
  handler(Object.assign(req, {
    query: ['a', 'b', 'c']
  }), res);
});

server.listen(3333);
```

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

<sub>[TRP-26](https://linear.app/trpc/issue/TRP-26/feat-trpc-is-assuming-the-type-of-the-reqquery-property-on-all)</sub>

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/4280">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/4280/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/4280/pledge.svg">
</picture>
</a>

**Comment by KATT** [comment]
Happy to widen the types, feel free to submit a PR

**Comment by fallenfreq** [comment]
I've had a quick look without testing anything and widening the types for query has a nock on effect that makes it totally redundant in the first place. It also seems like you could use ConnectMiddleware<TRequest, TResponse> instead of just ConnectMiddleware to get the "connect style" middleware to infer the correct req and res types.

I'll have a proper look later and hopefully submit a PR
