### ISSUE TITLE
bug: Type narrowing `ctx` in middleware no longer works as of v10.21.0

### ISSUE THREAD

**Issue by AdrianGonz97** [trpc/trpc#4321]
### Provide environment information
```
  System:
    OS: Linux 5.15 Ubuntu 20.04.5 LTS (Focal Fossa)
    CPU: (24) x64 AMD Ryzen 9 5900X 12-Core Processor
    Memory: 25.24 GB / 31.30 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 18.15.0 - ~/.volta/tools/image/node/18.15.0/bin/node
    Yarn: 1.22.15 - ~/.volta/bin/yarn
    npm: 9.5.0 - ~/.volta/tools/image/node/18.15.0/bin/npm
  npmPackages:
    @trpc/client: 10.20.0 => 10.20.0 
    @trpc/server: 10.20.0 => 10.20.0 
    typescript: ^5.0.4 => 5.0.4 
```

### Describe the bug

Prior to v10.21.0, we were able to narrow the types of our context in middleware like so:

```ts
// example context
type Context =
  | { user: null; session: null }
  | {
      user: {
        id: string;
        name: string;
      };
      session: {
        id: string;
        state: string;
      };
};

// say that we want to add a middleware for logging
const baseProcedure = t.procedure
  .use(async ({ path, type, next }) => {
    const start = Date.now();
    const result = await next();
    const ms = Date.now() - start;
    console.log(`${result.ok ? 'OK' : 'ERR'} ${type} ${path} - ${ms}ms`);
    return result;
  });

export const protectedProcedure = baseProcedure.use(({ next, ctx }) => {
  // we narrow the type of `user` and `session` by throwing when either are null
  if (!ctx.user || !ctx.session) {
    throw new TRPCError({ code: 'UNAUTHORIZED', message: 'not signed in' });
  }
  return next({ ctx });
});
```

If we try to add another middleware to this procedure, the type of `ctx.user` still states that it can still be `null`, which is incorrect.
```ts
const someOtherProcedure = protectedProcedure.use(async ({ next, ctx }) => {
  // type of `user` should not be null here as we narrowed its type in the first middleware
  ctx.user.id;
  //   ^? user: { id: string; name: string; } | null

  return next({
    ctx: {
      ...ctx,
    },
  });
});
```
If we comment out the middleware for logging, the type of `ctx.user` would now be correct.

The last known version of tRPC that I could find that doesn't exhibit this behavior is v10.20.0.

### Link to reproduction

https://stackblitz.com/edit/github-yrjz6a?file=src%2Fserver%2Ftrpc.ts%3AL52

### To reproduce

Using tRPC v10.20.0 and below narrows both the `session` and `user` types correctly:
https://stackblitz.com/edit/github-yrjz6a-nkddm4?file=src%2Fserver%2Ftrpc.ts%3AL52

Additionally, for the reproduction that uses the [latest version of tRPC v10.25.0](https://stackblitz.com/edit/github-yrjz6a?file=src%2Fserver%2Ftrpc.ts%3AL29), if you comment out the logger middleware for the `baseProcedure`, the `ctx` type is corrected. 

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

**Comment by Nick-Lucas** [comment]
Thank you for the clear explanation and the reproduction, it does look like something which should work. It's believable we've cause this regression with a type change to how we handle Context

**Comment by Nick-Lucas** [comment]
Looks like some optimisation work we did on an internal type has caused this. #4203 - solving it means adapting the type like this: https://stackoverflow.com/a/51691257

#4327 is my WIP to resolve it, and we've now got some type tests to prevent future regressions, just waiting on some tests to pass  and a code-review.

**Comment by Nick-Lucas** [comment]
@AdrianGonz97 we just released this fix, do come back if there are any remaining issues :)
