### ISSUE TITLE
docs: Add Japanese translation to tRPC documentation

### ISSUE THREAD

**Issue by taichi221228** [trpc/trpc#4323]
### Area of Improvement

Hello tRPC maintainers,

I recently discovered tRPC while working with CT3A's documentation, which has support for Japanese. I noticed that tRPC's documentation does not currently include Japanese translations, and I would like to contribute by adding them.

Considering that tRPC's documentation is built with Docusaurus, adding translations should be relatively straightforward. 

To get started, I plan to:

1. Clone the tRPC documentation repository.
2. Create a new branch for the Japanese translation.
3. Follow the Docusaurus i18n [instructions](https://docusaurus.io/docs/i18n/introduction) to set up the Japanese language configuration.
4. Translate the Markdown files and relevant components.
5. Submit a pull request with the added translations.

Please let me know if you are open to this contribution, and if there are any guidelines or recommendations to follow when working on the Japanese translation. I am excited to help make tRPC's documentation more accessible to the Japanese developer community.

Thank you for your time and consideration!

Best regards,

### Additional information

- https://docusaurus.io/docs/i18n/introduction
- https://docusaurus.io/docs/cli#docusaurus-write-translations-sitedir

### 👨‍👧‍👦 Contributing

- [x] 🙋‍♂️ Yes, I'd be down to file a PR implementing the suggested changes!

**Comment by KATT** [comment]
Adding translations is possible, but we don't have any resources to maintain the docs across other languages

**Comment by Nick-Lucas** [comment]
I agree with KATT, even if we did a translation (which would be a multi-month undertaking) the docs are not static and so keeping them updated would be a long term commitment which we can't deliver in the core team.

So translations are likely to be a longer term goal, and we would also want to look at which languages are priorities in that situation - my instinct is Japanese wouldn't be on a short-list though I'm happy to be proven wrong there.

Just to keep things tidy, I am going to close this, though happy to re-open, or see it re-appear in the mid-long term, if a really compelling case can be made for this.
