### ISSUE TITLE
bug: error TS2769: No overload matches this call

### ISSUE THREAD

**Issue by moltar** [trpc/trpc#4339]
### Provide environment information

```
  System:
    OS: macOS 13.3.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 30.62 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.19.1 - ~/Library/Caches/fnm_multishells/79359_1683625947298/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.3 - ~/Library/Caches/fnm_multishells/79359_1683625947298/bin/npm
  Browsers:
    Chrome: 112.0.5615.137
    Firefox: 112.0.2
    Safari: 16.4
  npmPackages:
    @tanstack/react-query: 4.29.5 => 4.29.5 
    @trpc/client: 10.25.0 => 10.25.0 
    @trpc/react-query: 10.25.0 => 10.25.0 
    @trpc/server: 10.25.0 => 10.25.0 
    react: 18.2.0 => 18.2.0 
    typescript: 5.0.4 => 5.0.4 

```

### Describe the bug

Getting a TS build error:

```
node_modules/@trpc/client/src/links/loggerLink.ts:81:30 - error TS2769: No overload matches this call.
  Overload 1 of 2, '(entries: Iterable<readonly [PropertyKey, any]>): { [k: string]: any; }', gave the following error.
    Argument of type 'Record<string, unknown> & FormData' is not assignable to parameter of type 'Iterable<readonly [PropertyKey, any]>'.
      Property '[Symbol.iterator]' is missing in type 'Record<string, unknown> & FormData' but required in type 'Iterable<readonly [PropertyKey, any]>'.
  Overload 2 of 2, '(entries: Iterable<readonly any[]>): any', gave the following error.
    Argument of type 'Record<string, unknown> & FormData' is not assignable to parameter of type 'Iterable<readonly any[]>'.
      Property '[Symbol.iterator]' is missing in type 'Record<string, unknown> & FormData' but required in type 'Iterable<readonly any[]>'.

81         ? Object.fromEntries(rawInput)
                                ~~~~~~~~

  node_modules/typescript/lib/lib.es2015.iterable.d.ts:49:5
    49     [Symbol.iterator](): Iterator<T>;
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    '[Symbol.iterator]' is declared here.
  node_modules/typescript/lib/lib.es2015.iterable.d.ts:49:5
    49     [Symbol.iterator](): Iterator<T>;
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    '[Symbol.iterator]' is declared here.
```

### Link to reproduction

N/A

### To reproduce

This fails on the internal code and is not reliant on application code. I.e. the error occurs in the types, that come with tRPC.

### Additional information

N/A

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

**Comment by KATT** [comment]
I've fixed and released something that I _think_ fixes this now but it's mainly just a guess

If it reoccurs, I need you need to do one or several of these things:

- provide a preproduction, and/or
- provide a failing test, and/or
- convince your employer actually to sponsor the development of trpc since it's clear that you use this for commercial purposes to the point where you can't even share the code of what's failing

**Comment by moltar** [comment]
> actually to sponsor

I know this isn't going to make any meaningful dent in your bottom line, but we just became a sponsor.

<img width="350" alt="screenshot-20230510T132047-Eu3bIbjT@2x" src="https://github.com/trpc/trpc/assets/491247/32a0fa65-4ec2-4b86-a355-d6860ca07faf">

**Comment by moltar** [comment]
Found a way to repro: [Playground Link](https://www.typescriptlang.org/play?target=2&moduleResolution=99&module=100&lib=lib.dom.d.ts&ts=lib.dom.d.ts&jsx=0#code/PTAEAEBsEsCMC5QBEDyBZANKAogZQEwAM+AjAFBkDGA9gHYDOALqAGYAmoAvKLQKYDuoAGLUATgFskAQ0ZSAFAEoy7AHRSADut602cgORS9WPbD1LlY0HJoNmAbQDWWAG4BdUNRas2C0AG8yUCDQG3pqSF4VSGoAczknUGclAF8yIA)

This uses a cool new `// @lib:` option announced [here](https://github.com/microsoft/TypeScript-Website/issues/136#issuecomment-1011161286).

Also found this: https://devblogs.microsoft.com/typescript/announcing-typescript-4-5-beta/#supporting-lib-from-node_modules

**Comment by KATT** [comment]
We have `dom.iterable` in our base compiler options:

https://github.com/trpc/trpc/blob/9409cdd5220b6a383278c827048eff86e10112b5/tsconfig.build.json#L4

**Comment by tachyonicbytes** [comment]
/attempt #4339

Hi! I would like to work on this!

**Comment by KATT** [comment]
Hide the comment from @tachyonicbytes to not push away other people to have a stab.

It's quite common that people have the best intentions of trying to help but never get around to it and therefore we don't allow "assigning" issues :)

**Comment by moltar** [comment]
@kamilogorek I've tested #4355 against our project and it does indeed solve the problem! Thanks!
