### ISSUE TITLE
bug: incorrect infinite query page type

### ISSUE THREAD

**Issue by vinpac** [trpc/trpc#4349]
### Provide environment information

```
  System:
    OS: macOS 13.3.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 153.70 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.14.2 - ~/.nvm/versions/node/v18.14.2/bin/node
    Yarn: 3.3.0 - ~/.nvm/versions/node/v18.14.2/bin/yarn
    npm: 9.5.0 - ~/.nvm/versions/node/v18.14.2/bin/npm
  Browsers:
    Chrome: 113.0.5672.92
    Firefox: 109.0.1
    Safari: 16.4
  npmPackages:
    @tanstack/react-query: ^4.28.0 => 4.28.0 
    @trpc/client: ^10.25.1 => 10.25.1 
    @trpc/next: ^10.25.1 => 10.25.1 
    @trpc/react-query: ^10.25.1 => 10.25.1 
    @trpc/server: ^10.25.1 => 10.25.1 
    next: ^13.4.0 => 13.4.0 
    react: ^18.2.0 => 18.2.0 
    typescript: ^4.6.4 => 4.9.5 
```

### Describe the bug

When using `useInfiniteQuery` the type of the page doesn't match the query result. Using `useQuery` on the same procedure gives the right type. 

Am I missing something?

<img width="759" alt="image" src="https://github.com/trpc/trpc/assets/9030018/8a408b48-1486-4b89-b308-78e09fa85985">
<img width="759" alt="image" src="https://github.com/trpc/trpc/assets/9030018/e5aefeff-f7ea-47f8-a5ef-6d39f94e2c09">
<img width="892" alt="image" src="https://github.com/trpc/trpc/assets/9030018/cfdc5d27-ec10-42a1-a59a-65fc2c406518">

Here's the query

```typescript
function cursor(input: CursorInput) {
  return {
    take: input.limit + 1,
    cursor: input.cursor
      ? {
          id: input.cursor,
        }
      : undefined,
  }
}

/** __description__ */
export default protectedProcedure
  .input(CursorWithSearchInput)
  .query(async ({ input }) => {
    const threads = await db.thread.findMany({
      ...cursor(input),
    })

    return {
      results: threads.slice(0, input.limit),
      nextCursor: threads[input.limit]?.id,
    } as CursorOutput<Thread>
  })
```

schemas
```typescript
export const CursorInput = z.object({
  limit: z.number().min(1).max(100).optional().default(20),
  cursor: z.number().optional(),
})

export const CursorWithSearchInput = CursorInput.extend({
  search: z.string().optional(),
})

export type CursorInput = z.infer<typeof CursorInput>

export interface CursorOutput<T> {
  results: T[]
  nextCursor?: number | string
}

```

### Link to reproduction

https://stackblitz.com/edit/github-jhedg3?file=src/pages/index.tsx

### To reproduce

1. Create [an infinite query](https://trpc.io/docs/reactjs/useinfinitequery)
2. Check the type of the page at `.data.pages[0]`

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

**Comment by KATT** [comment]
I think you need to make a better reproduction b/c we have tests that assert this e.g. https://github.com/trpc/trpc/blob/efba201ee55467cf012988f146607249c8b55bd4/packages/tests/server/react/infiniteQuery.test.tsx#L132

**Comment by vinpac** [comment]
False alarm! Just needed to Reload VS Code 😆
