### ISSUE TITLE
help wanted: app dir example build fails b/c of mysterious reasons

### ISSUE THREAD

**Issue by KATT** [trpc/trpc#4396]
### Context

- https://github.com/trpc/trpc/tree/main/examples/.experimental/next-app-dir fails to build, but **only** within our monorepo
- https://github.com/trpc/examples-next-app-dir works fine
- Demo: #4397
- Has something to do with a combination of using server actions + pnpm symlinks(?). Possibly b/c of an underlying Next.js/React issue
- More minimal repro: #4393

Eligible for the bounty if you fix it or can reproduce it in a standalone repo to send to the Next.js team.

### Error:

> ```
> > next build
> 
> - warn You have enabled experimental feature (serverActions) in next.config.js.
> - warn Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.
> 
> Failed to compile.
> 
> ../../../packages/client/dist/index.mjs + 9 modules
> Cannot get final name for export 'observable' of ../../../packages/server/dist/observable/index.mjs
> 
> 
> > Build failed because of webpack errors
> - info Creating an optimized production build . ELIFECYCLE  Command failed with exit code 1.
> ```

<sub>[TRP-33](https://linear.app/trpc/issue/TRP-33/help-wanted-app-dir-example-build-fails-bc-of-mysterious-reasons)</sub>

**Comment by scshiv29-dev** [comment]
Not only the build , even when running using "pnpm dev" the code gives error on /rsc

<request from rsc
request from rsc
request from client
 << query #2 greeting {
  input: { text: 'streamed server data' },
  result: {
    context: { response: [Response] },
    result: { data: 'hello streamed server data', type: 'data' }
  },
  elapsedMs: 1071,
  context: {}
}
 << query #1 greeting {
  input: { text: 'from server' },
  result: {
    context: { response: [Response] },
    result: { data: 'hello from server', type: 'data' }
  },
  elapsedMs: 2048,
  context: {}
}
 << query #1 greeting {
  input: { text: 'from client' },
  result: {
    context: { response: [Response] },
    result: { data: 'hello from client', type: 'data' }
  },
  elapsedMs: 1918,
  context: {}
}

-  ┌ GET /rsc 200 in 2915ms
   │
   ├──── GET http://localhost:3000/api/trpc/greeting?batch=1&input=%.. 200 in 1018ms (cache: MISS)
   │
   ├──── GET http://localhost:3000/api/trpc/greeting?batch=1&input=%.. 200 in 1892ms (cache: MISS)
   │
   └──── GET http://localhost:3000/api/trpc/greeting?batch=1&input=%.. 200 in 1840ms (cache: MISS)
>

**Comment by juliusmarminge** [comment]
I've now put way too much time into trying to fix this without any luck…. might be time to pull in someone from the Next.js team and see what they think might be wrong…

cc @anthonyshew can you help out here please?

**Comment by SSHari** [comment]
I also spent some time digging into this without very much luck. I _was_ able to get around the error by disabling scope hoisting for the `server` part of the build via the Webpack [ModuleConcatenationPlugin](https://webpack.js.org/plugins/module-concatenation-plugin/#root). Based on the description it seems like that plugin is more useful for browser code, so it _may_ be acceptable to disable it for the `server`.

Either way, it might be good enough for now to unblock development for the app directory stuff _until_ a more proper solution is figured out.

<img width="685" alt="image" src="https://github.com/trpc/trpc/assets/11434879/fe0fa90a-0fe3-4424-a493-fbdc78126064">

**Comment by anthonyshew** [comment]
@juliusmarminge Pinging me on a Webpack error? I thought we were friends.

(Just kidding, obviously.) I'm missing _a lot_ of context on both tRPC internals and Server Actions internals for this. It would probably take me way too long to get up to speed to make myself useful. I guarantee Julius knows this code way better than me and if their report is "I've now put way too much time into trying to fix this without any luck," then I'm out. 😄

Cheating off of Alex's notes:
> Has something to do with a combination of using server actions + pnpm symlinks(?). Possibly b/c of an underlying Next.js/React issue

I'm not sure how solid you are on these findings, @KATT, but it wouldn't surprise me at all if there's some bugginess at the compiler level presently. Knowing that Server Actions are in alpha today and that there's a ton of active "compiler magic" work going on in the React and Next.js cores, I wouldn't be surprised if this error "suddenly disappeared" for you folks randomly one day.

A standalone reproduction would probably be awesome for those teams to have, as Alex has astutely noted. I also think @SSHari's finding is serviceable to get unblocked for today (assuming it does indeed work; I didn't try it but it seems to make sense in my head). I would periodically delete those `webpack` lines as work continues to see if the hack becomes "magically unnecessary" as development keeps up in the cores of the upstreams.

You all's enthusiasm to support these experimental features is **amazing**. If we can get to that minimal repro, that's probably the best bet to speed this along. My gut is that this isn't a tRPC-native problem.
