### ISSUE TITLE
bug: TS2339 error on MiddlewareOKResult<any>

### ISSUE THREAD

**Issue by joshuaja-tangelo** [trpc/trpc#4426]
### Provide environment information

```
System:
    OS: macOS 13.2.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 3.48 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.8.1 - ~/.asdf/installs/nodejs/19.8.1/bin/node
    Yarn: 1.22.19 - ~/.asdf/installs/nodejs/19.8.1/bin/yarn
    npm: 9.5.1 - ~/.asdf/plugins/nodejs/shims/npm
  Browsers:
    Brave Browser: 113.1.51.114
    Safari: 16.3
  npmPackages:
    @trpc/server: ^10.28.0 => 10.28.0
    react: ^18.2.0 => 18.2.0
    typescript: ^5.0.4 => 5.0.4
```

### Describe the bug

```
node_modules/.pnpm/@trpc+server@10.28.0/node_modules/@trpc/server/src/core/internals/procedureBuilder.ts:404:20 - error TS2339: Property 'error' does not exist on type 'MiddlewareResult<any>'.
  Property 'error' does not exist on type 'MiddlewareOKResult<any>'.

404       throw result.error;
```

```
node_modules/.pnpm/@trpc+server@10.28.0/node_modules/@trpc/server/src/deprecated/internals/procedure.ts:244:20 - error TS2339: Property 'error' does not exist on type 'MiddlewareResult<any>'.
  Property 'error' does not exist on type 'MiddlewareOKResult<any>'.

244       throw result.error;
```

### To reproduce

When trying to build via `tsc`, I receive the following error: `Property 'error' does not exist on type 'MiddlewareOKResult<any>'.`

### Additional information
Adding `"skipLibCheck": true,` doesn't work.

_No response_

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

![image](https://github.com/trpc/trpc/assets/128391512/e27a7c4b-e41f-4348-b573-b81ce71cea2a)

<sub>[T-80](https://linear.app/trpc/issue/T-80/bug-ts2339-error-on-middlewareokresultany)</sub>

**Comment by KATT** [comment]
Needs reproduction

**Comment by joshuaja-tangelo** [comment]
> 
@KATT 
I can spend the time creating a reproduction but opening these two files in an IDE shows exactly where the issue is occurring (`@trpc/server/src/core/internals/procedureBuilder.ts` and `@trpc/server/src/deprecated/internals/procedure.ts`) :

![image](https://github.com/trpc/trpc/assets/128391512/6ad78b35-113a-4e53-8650-968558536e99)

**Comment by KATT** [comment]
I mean... I am using trpc and I don't get this errors, we have a bunch of tests, [e.g. this one](https://github.com/trpc/trpc/tree/main/examples/.test/internal-types-export), that are meant to prevent things like this

**Comment by KATT** [comment]
You have a newer TS version than we have, I'm bumping in #4427 to see if something comes up

**Comment by KATT** [comment]
Are you using `strict: true`?

**Comment by joshuaja-tangelo** [comment]
> Are you using `strict: true`?

No

**Comment by KATT** [comment]
![CleanShot 2023-05-26 at 01 19 37@2x](https://github.com/trpc/trpc/assets/459267/c41f337f-75d4-4a2d-8e6a-0d0266e1c537)

**Comment by KATT** [comment]
https://trpc.io/docs/faq#it-doesnt-work-im-getting-any-everywhere

**Comment by KATT** [comment]
It's very late here. Going to bed. Hope you sort it out 🙏

**Comment by joshuaja-tangelo** [comment]
> It's very late here. Going to bed. Hope you sort it out 🙏

Thank you! I'll give it a look over, I appreciate the help.

**Comment by joshuaja-tangelo** [comment]
@KATT - using `"strict": true"` fixed the issue. Thank you for the help. Closing this for now.
