### ISSUE TITLE
feat: support hydration with suspense & streaming

### ISSUE THREAD

**Issue by VictorGlindasPaf** [trpc/trpc#4441]
### Describe the feature you'd like to request

When using suspense in the latest nextjs version, it makes a request on the server, streams the HTML to the client, and then makes another client side request before it considers the hydration to be done.

This results in double the amount of requests, and causes hydration issues when the server data is different than the response the client receives from the requests.

So the  way it works - as far as I understand - is currently:
1. Server starts rendering, suspends, and starts streaming in the HTML as the data arrives.
2. Once the HTML is streamed in, the client starts rendering (hydrating) and suspends while making the same requests **again**.
3. When the client requests are all resolved, the initial HTML no longer matches what the client renders since data has changed between the requests made on the server and client, so the hydration fails.

### Describe the solution you'd like to see

We need a way to stream in the hydration data along with the HTML, so the store is populated before the hydration happens.

### Describe alternate solutions

The alternative is to currently not use suspense at all.

Making the requests only on the client would be "good enough", but I haven't been able to find a way to do so. As soon as we use suspense, requests start to happen on the server automatically.

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/4441">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/4441/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/4441/pledge.svg">
</picture>
</a>

**Comment by juliusmarminge** [comment]
#4375 should solve this but it's a bit tricky since React doesn't want to provide the primitives to do so so we need to hack around it...

**Comment by VictorGlindasPaf** [comment]
> #4375 should solve this but it's a bit tricky since React doesn't want to provide the primitives to do so so we need to hack around it...

This still seems to be an issue even though that PR was merged?

**Comment by Glinkis** [comment]
I believe this will be solved with the update to recat-query 5 and https://tanstack.com/query/v5/docs/react/guides/suspense#suspense-on-the-server-with-streaming

So feel free to close this if you want.
