### ISSUE TITLE
feat(`react-query`): `useSuspenseQueries()`

### ISSUE THREAD

**Issue by KATT** [trpc/trpc#4454]
### Describe the feature you'd like to request

Like `useQueries` but for `Suspense`

### Describe the solution you'd like to see

```tsx
const [result, queries] = trpc.useSuspenseQueries(t => [ t.foo(), t.bar() ])

const [foo, bar] = result;
```

### Describe alternate solutions

Nah

### Additional information

*No response*

### 👨‍👧‍👦 Contributing

* [X] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

<sub>From [SyncLinear.com](https://synclinear.com) | [T-84](https://linear.app/trpc/issue/T-84/feat-usesuspensequeries)</sub>

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/4454">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/4454/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/4454/pledge.svg">
</picture>
</a>

**Comment by Sheraff** [comment]
Just for clarification, this wouldn't work right?

```ts
trpc.useQueries(t => [ t.foo(undefined, {suspense: true}), t.bar(undefined, {suspense: true}) ])
```

I haven't tried but I'm assuming that depending on how react-query it might either do all requests in parallel or all requests one after the other.

**Comment by KATT** [comment]
Yeah, we'll limit it so you have to suspense all of them

**Comment by bfoltyn** [comment]
hey @KATT great project! can I ask, why was the PR for this closed?

**Comment by KATT** [comment]
Because it was a lot of work and I didn't have time to finish it, feel free to pick it up

**Comment by bfoltyn** [comment]
> Because it was a lot of work and I didn't have time to finish it, feel free to pick it up

ok , i will try to make the pr 🙂

**Comment by KATT** [comment]
This feature has been added in the [`next`-branch](https://github.com/trpc/trpc/tree/next) of tRPC, meaning it will be available in v11 of tRPC. 

It's possible to start using it _today_, have a look at the top of the readme of the `next`-branch for more info.
