### ISSUE TITLE
bug: wrong types for initialData

### ISSUE THREAD

**Issue by TkDodo** [trpc/trpc#4486]
### Provide environment information

```
  System:
    OS: Linux 5.15 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (2) x64 AMD EPYC
    Memory: 1.08 GB / 2.01 GB
    Container: Yes
    Shell: 5.1.4 - /bin/bash
  Binaries:
    Node: 16.17.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.15.0 - /usr/local/bin/npm
    Watchman: 20220528.183901.0 - /usr/local/bin/watchman
  npmPackages:
    @tanstack/react-query: 4.29.12 => 4.14.5 
    @trpc/client: 10.29.1 => 10.6.0 
    @trpc/next: 10.29.1 => 10.6.0 
    @trpc/react-query: 10.29.1 => 10.6.0 
    @trpc/server: 10.29.1 => 10.6.0 
    next: ^12.3.1 => 12.3.2 
    react: ^18.2.0 => 18.2.0 
    typescript: ^4.8.3 => 4.8.4 
```

### Describe the bug

it seems that I can pass in anything into the `initialData` field and typescript doesn't complain.

### Link to reproduction

https://codesandbox.io/p/sandbox/immutable-grass-wuw9r2?file=%2Fsrc%2Fpages%2Findex.tsx%3A13%2C26

### To reproduce

in the provided sandbox, I'm passing `initialData: 5` to the standard greeting router, which actually returns `{ text: string }`. I'd expect there to be a type error when passing the wrong initialData.

Note that this works fine with raw react-query, as you can see in this [typescript playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQFA2iSxwDecArqlgIptZQCecAL5wiJcgAEYyAHappuANYB6SnhgBaAI68BtGnDi4Ic+AHNKWGMBlm4AXnaceffgApmBw3B2uA0lj8AFxwANpkMFjyZAC6ADRehr4CAGIyIW4AlA4AfHAACsQgwJwAdJSoEAA2AG5YHnCRAB4wIWQAFlhVVRBwAO7QVQAmZMKZCd5wyspwgLwbgBV7je0lcCt9xLaJqzLA1shVACLI0iEArBPe8vtYACqgWCEAkjIENrv8F0KZANxAA). The error is weird because of our overloads, which will get better in v5 (playground with alpha would be [here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQFA2iSxwDecArqlgIptZQCecAL5wiJcgAEYyAHappuANYB6SnhgBaAI68BZOMuVwY-MFlQAuFABswAC2R04cXBDnwA5pSwxgMj3AAvOycPHz8ABTMNM7OOuEA0lj8VgDaZDDmMGQAugA0MbHxAgBiMlYRAJRBAHxwAArEIMCcAHSUqBDWAG5YUcZYAB4wVmR2WNbWEHAA7tDWACb6QpUFsQZGgLwbgBV7xnYtcAczxP6Fzn7AvsjWACLI0lYArGux8tdYACqgWFYAkjIEC4mF4rADcQA)) 😅 

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

<sub>[T-104](https://linear.app/trpc/issue/T-104/bug-wrong-types-for-initialdata)</sub>

**Comment by jemiluv8** [comment]
I'm looking into this.

/attempt #4486
