### ISSUE TITLE
bug: Transformer on legacy router breaks createTRPCNext() but is required by createTRPCNext() config type

### ISSUE THREAD

**Issue by n-glaz** [trpc/trpc#4493]
### Provide environment information

```
 System:
    OS: macOS 12.6.6
    CPU: (10) arm64 Apple M1 Pro
    Memory: 556.13 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.7.0 - ~/.nvm/versions/node/v18.7.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.7.0/bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v18.7.0/bin/npm
  Browsers:
    Chrome: 113.0.5672.126
    Safari: 16.5
  npmPackages:
    @tanstack/react-query: ^4.18.0 => 4.29.12 
    @trpc/client: ^10.29.1 => 10.29.1 
    @trpc/next: ^10.29.1 => 10.29.1 
    @trpc/react-query: ^10.29.1 => 10.29.1 
    @trpc/server: ^10.29.1 => 10.29.1 
    next: ^13.4.3 => 13.4.4 
    react: ^18.2.0 => 18.2.0 
    typescript: ^5.1.3 => 5.1.3
```

### Describe the bug

I've added and merged a trpc 9-style legacy router to [a fork](https://github.com/n-glaz/examples-next-prisma-starter-with-legacy) of `examples-next-prisma-starter` (trpc v10.29.1).  I followed the [official trpc 9 -> 10 migration guide.](https://trpc.io/docs/migrate-from-v9-to-v10)

If I do not set a transformer on the legacy trpc 9 router, I get the following type error on `config()` inside `trpc = createTRPCNext`:

<img width="704" alt="Screen Shot 2023-06-07 at 3 29 44 PM" src="https://github.com/trpc/trpc/assets/110408478/220022f8-afdb-48dd-ad63-fe6942941939">

```
        Types of property 'transformer' are incompatible.
          Type 'typeof SuperJSON' is not assignable to type '"You must set a transformer on the backend router"'.
```

If I do include a transformer, my router fails with the following error: `Error: You seem to have several transformers`

The merged router:

<img width="742" alt="Screen Shot 2023-06-07 at 3 33 09 PM" src="https://github.com/trpc/trpc/assets/110408478/1ed32d12-65b6-465f-9cbf-718b22e5a1d7">

### Link to reproduction

https://github.com/n-glaz/examples-next-prisma-starter-with-legacy

### To reproduce

See bug description and [my reproduction forked off of the trpc 9 prisma example](https://github.com/n-glaz/examples-next-prisma-starter-with-legacy).

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

**Comment by juliusmarminge** [comment]
createTRPCNext does not support interop - it was a new addition to v10 meant for v10 only. It's mentioned in the docs here: https://trpc.io/docs/client/nextjs/setup#4-create-trpc-hooks

![CleanShot 2023-06-08 at 11 03 45](https://github.com/trpc/trpc/assets/51714798/1bac4c4b-4a78-41dd-90c0-9c77fa4da45b)



Check out the interop example for a working example: https://github.com/trpc/trpc/blob/main/examples/.interop/next-prisma-starter/src/pages/_app.tsx
