### ISSUE TITLE
feat: A priority queue link

### ISSUE THREAD

**Issue by tianhuil** [trpc/trpc#4505]
### Describe the feature you'd like to request

The new `httpBatchStreamLink` (https://trpc.io/docs/client/links/httpBatchStreamLink) is great!  However, it has some key limitations as it does not work on [AWS Lambda](https://trpc.io/docs/client/links/httpBatchStreamLink#compatibility-server-side) and hence does not work on Vercel.

As a stopgap, I wrote a non-terminating priority queue link (with tests):
- The client can specify an optional priority on each query (e.g. 3).
- The priority queue link counts in-flight queries and only releases additional queries when there are no in-flight queries.  The queries are released in batches consisting of all queries of a given priority, starting with the lowest priority number.

As an example, if we add queries of priority 3, 1,  1, and 2, they will be sent in 3 **sequential** batches of:
- priority 1 batch with 2 query
- priority 2 batch with 1 query
- priority 3 batch with 1 query

### Describe the solution you'd like to see

```ts
function priorityLink(opts: {
  priority: (op: Operation) => number
}) {
   ...
}
```

### Describe alternate solutions
1. The default is to release all queries simultaneously in a single batch (`httpBatchLink`).  However, the lower-priority queries might slow down the higher-priority ones on the server.
2. We could use `splitLink` to split queries into separate batches by priority.  However, this fires up 2+ AWS Lambda functions to respond to the multiple simultaneous queries.  These queries might actually be slower because of the warmup cost incurred by the additional lambda functions.  For our app, we typically only have one warmed-up lambda function.  Immediately sending a second lambda function incurs ~6 seconds of warmup, which is slower than waiting for the first query to finish (~2 seconds).
- Obviously, using `httpBatchStreamLink` would be optimal, but it is not available for systems that run on AWS Lambda, like Vercel.

### Additional information

I have a working version (with tests) and would love to contribute it if there's any interest.

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

**Comment by Nick-Lucas** [comment]
Lambda can eventually support the streaming, someone just needs to update the adapter to do so (PRs welcome). This link seems like an interesting user-land link though.

**Comment by KATT** [comment]
Thanks for writing this up!

This sounds like a great user-land feature but not something we're looking to have within the trpc core, it seems like an edge-case seeing that it should be possible to do the streaming in most environments.

Please make a standalone npm module and make a PR to https://trpc.io/awesome! 🙏 ❤️

**Comment by tianhuil** [comment]
I don't know how to update the adapter but if you give me some pointers, can try to upgrade it.  I do want to improve this and use this.
