### ISSUE TITLE
bug(external): Date strings in JSON are not converted back to Date objects using Next 13.4.5 and superjson

### ISSUE THREAD

**Issue by jvandenaardweg** [trpc/trpc#4515]
> **Edit by @KATT**: This is caused by https://github.com/blitz-js/superjson/issues/242, but keeping this open for visibility

### Provide environment information

```
System:
    OS: macOS 13.4
    CPU: (10) arm64 Apple M1 Pro
    Memory: 4.62 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
  Browsers:
    Brave Browser: 101.1.38.111
    Chrome: 114.0.5735.106
    Firefox: 107.0.1
    Firefox Developer Edition: 96.0
    Safari: 16.5
```

See reproduction for package versions. All latest as of today.

### Describe the bug

Date strings in JSON are not converted back to Date objects using NextJS 13.4.5. The `meta.values` in the JSON are missing, so I think that's why `superjson` does not transform it back to a Date object.

I'm using TRPC with Edge Functions.

I've isolated and confirmed it works on Next 13.4.4 and lower, so seems to be a issue introduced in the latest NextJS version.

This is a simplified output on Next 13.4.5. `createdAt` and `updatedAt` are Date strings and the `meta.values` data about `createdAt` and `updatedAt` to be a `Date` is missing:
```json
{
  "result": {
    "data": {
      "json": {
        "content": [
          {
            "title": "Some title",
            "createdAt": "2023-06-09T14:21:21.885Z",
            "updatedAt": "2023-06-10T22:05:03.573Z"
          }
        ]
      },
      "meta": {
        "referentialEqualities": {}
      }
    }
  }
}
```

When I revert back to 13.4.4, the `meta.values` are there and the `createdAt` and `updatedAt` are Date objects in the response in my component.
```json
{
  "result": {
    "data": {
      "json": {
        "content": [
          {
            "title": "Some title",
            "createdAt": "2023-06-09T14:21:21.885Z",
            "updatedAt": "2023-06-10T22:05:03.573Z"
          }
        ]
      },
      "meta": {
        "values": {
          "content.0.createdAt": ["Date"],
          "content.0.updatedAt": ["Date"]
        }
      }
    }
  }
}
```

### Link to reproduction

https://codesandbox.io/p/sandbox/trpc-json-date-next-13-4-5-39q2k7

### To reproduce
13.4.5 (date is string): https://codesandbox.io/p/sandbox/trpc-json-date-next-13-4-5-39q2k7
13.4.4 (date is Date): https://codesandbox.io/p/sandbox/trpc-json-date-next-13-4-4-vpg6jp (forked reproduction, and only changed Next version to 13.4.4)

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

**Comment by kamilogorek** [comment]
Note: I bumped all our dependencies to `13.4.5`, and all tests, including `superjson` transform `Data` passing still work just fine.

**Comment by 1010nishant** [comment]
can I work on this issue? I'm pretty confident about it.

**Comment by kamilogorek** [comment]
Sure, we appreciate all the help! :)

**Comment by 1010nishant** [comment]
thanks @kamilogorek please assign it to me or i directly raise a PR

**Comment by jvandenaardweg** [comment]
@1010nishant looking forward to the fix!

**Comment by kamilogorek** [comment]
Feel free to submit a PR anytime and mark it as `Fixes #4515`, so it'll automatically link with this issue.

**Comment by Andersgee** [comment]
bumped into this aswell, A quick fix is using `devalue` instead of `superjson` as transformer.
```ts
import type { CombinedDataTransformer } from "@trpc/server";
import { parse, stringify } from "devalue";

export const transformer: CombinedDataTransformer = {
  input: {
    serialize: (object) => stringify(object),
    deserialize: (object) => parse(object),
  },
  output: {
    serialize: (object) => stringify(object),
    deserialize: (object) => parse(object),
  },
};
```
supposedly `devalue` is faster/smaller/more performant anyway so Im just gonna stick with it from now on I think?

**Comment by juliusmarminge** [comment]
@1010nishant do you have a WIP? If so, could you open a draft PR.

This is blocking me for some other stuff and so I'm going to put some time into this in the morning and Hopefully find out what's the culprit

**Comment by juliusmarminge** [comment]
Blocked by https://github.com/blitz-js/superjson/issues/242
