### ISSUE TITLE
feat: Bidirectional WebSocket channels

### ISSUE THREAD

**Issue by neo773** [trpc/trpc#4529]
### Describe the feature you'd like to request

I've been thinking about how we can improve tRPC by adding bidirectional communication with multiple input types. 
The current `useSubscription` method is great for one-way communication, but it has its limitations when it comes to more interactive applications that require real-time back-and-forth between the client and server.

By introducing a new API for bidirectional communication, we can overcome the drawbacks of `useSubscription` and allow clients and servers to exchange different types of messages through a single channel. This would make it much easier to build dynamic and engaging web apps that require complex communication flows.

### Describe the solution you'd like to see

This is a draft API design I've come up with. open to feedback.

server.ts
```ts
import { EventEmitter } from "events"
import { initTRPC } from "@trpc/server"
import { z } from "zod"

const ee = new EventEmitter()

const t = initTRPC.create()

export const appRouter = t.router({
  chat: t.procedure
    .context(
      z.object({
        userId: z.string(),
      })
    )
    .inputs({
      sendMessage: z.object({
        userId: z.string().uuid(),
        message: z.string().min(1),
      }),
      setIsTyping: z.boolean(),
    })
    .channel(async ({ send, channel, ctx }) => {
      const onMessage = (data) => {
        send.next(data)
      }

      ee.on(`message:${ctx.userId}`, onMessage)

      channel.on("data", (data) => {
        switch (data.type) {
          case "sendMessage": {
            return ee.emit(`message:${data.data.userId}`, data.data.message)
          }
          case "setIsTyping": {
            // handle isTyping status change
            break
          }
        }
      })

      return () => {
        ee.off(`message:${ctx.userId}`, onMessage)
      }
    }),
})
```

client.ts 
```ts
import { createTRPCClient } from "@trpc/client"

const trpc = createTRPCClient({
  url: "/api/trpc",
})

const chatChannel = trpc.chat.useChannel({
  userId: userId,
})

chatChannel.on("data", (message) => {
  console.log("Received message:", message)
})

chatChannel.on("error", (err) => {
  console.error("Chat error:", err)
})

chatChannel.sendMessage.send({
  userId: 4,
  message: 'Hello'
})

chatChannel.setIsTyping.send(true)

chatChannel.close()

```

### Describe alternate solutions

‎ 

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/4529">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/4529/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/4529/pledge.svg">
</picture>
</a>

**Comment by KATT** [comment]
What are the benefits of doing this over what we have today? It seems like what you describe here can already be achieved with a mutation and subscription (which are communicated through websockets)

**Comment by KATT** [comment]
You can use WebSockets as a transport method for queries and mutations too, that's what [our websocket starter does](https://github.com/trpc/examples-next-prisma-websockets-starter)

**Comment by neo773** [comment]
Interesting I didn't know that, but I still think it'd be better to have consolidated logic instead of it being scattered across multiple mutations

**Comment by KATT** [comment]
I appreciate the feature request, but we won't be implementing this unless it comes from the community. Closing for now.

**Comment by KATT** [comment]
Feel free to re-open in the future with a more legit use-case. There's nothing blocking you from using WebSockets as bidirectional

**Comment by a-eid** [comment]
@KATT what is the difference between an http mutation vs a websockets mutation ? ( for example is a fastify backend context )

**Comment by KATT** [comment]
> @KATT what is the difference between an http mutation vs a websockets mutation ? ( for example is a fastify backend context ) 

No difference

**Comment by a-eid** [comment]
> > @KATT what is the difference between an http mutation vs a websockets mutation ? ( for example is a fastify backend context )
> 
> No difference

sorry, I'm not sure I understand, I would like to have a certain mutation transported over websockets. how do I do so ?

**Comment by KATT** [comment]
https://trpc.io/docs/client/links/wsLink
