### ISSUE TITLE
feat: Add support for multiValueHeaders and cookies in aws-lambda adapter

### ISSUE THREAD

**Issue by thomasedw** [trpc/trpc#4546]
### Describe the feature you'd like to request

For the aws-lambda adapter, multiple cookies cannot be returned currently when using a Rest API - using a comma-separated `Set-Cookie` header returns the first cookie in the header, instead you should use either the `multiValueHeaders` or `cookies` property if using a V2-based API gateway (HTTP-API or WS API).

### Describe the solution you'd like to see

To add support for this, we will need to:

1. Replace the existing comma-separated array joining to instead return two objects: `headers` and `multiValueHeaders` if we are using a v1 response format (for v2 we can just return headers).
1. To support passing `cookies` back when using the V2 response spec, we will need to augment the `HTTPResponse` type by adding an optional `cookies?: string[]` type.

1. If using the v1 lambda response spec:
    1. The multi-value headers can then be passed into the existing response [here](https://github.com/trpc/trpc/blob/main/packages/server/src/adapters/aws-lambda/index.ts#L59) as another field.

1. If using the v2 lambda response spec:
    1. V2-based APIs support comma-separated headers, so the current solution will work
    1. We should also pass `cookies` which can be returned via APIGateway [within this response](https://github.com/trpc/trpc/blob/main/packages/server/src/adapters/aws-lambda/index.ts#L66)

### Describe alternate solutions

I have attempted to return a `Set-Cookie` header as an comma-separated string and an array however only one cookie is currently sent back.

### Additional information

The specification for the lambda response format can be found [here](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-lambda.html).

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/4546">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/4546/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/4546/pledge.svg">
</picture>
</a>

**Comment by beeirl** [comment]
@thomasedw any reason why your pr was discontinued?

**Comment by KATT** [comment]
Should be fairly simple for anyone to pick this up now - https://github.com/trpc/trpc/blob/next/packages/server/src/adapters/aws-lambda/getPlanner.ts

**Comment by beeirl** [comment]
@KATT I started adapting the PR. Given that `resolveResponse` now returns a NodeJS HTTP `Response`, we can't return the relevant `responseMeta` fields there anymore. Do you have any advice how we should go about it? Would it be helpful to push my draft PR?
https://github.com/trpc/trpc/blob/next/packages/server/src/adapters/aws-lambda/index.ts#L69
