### ISSUE TITLE
Update integration with nextjs

### ISSUE THREAD

**Issue by koikiss-dev** [trpc/trpc#4571]
### Area of Improvement

With the new version of **nextjs (13)** you choose not to use the _app file, updating the documentation on that aspect to show how to integrate it is important.

### Link to related docs

https://trpc.io/docs/client/nextjs/setup

### Additional information

On the point 5. Configure `_app.tsx`

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing the suggested changes!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/4571">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/4571/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/4571/pledge.svg">
</picture>
</a>

**Comment by GRA0007** [comment]
Support for the app router is still in progress, you can follow the updates here: https://github.com/trpc/trpc/issues/3297

**Comment by juliusmarminge** [comment]
> With the new version of nextjs (13) you choose not to use the _app file

This isn't accurate. Next 13 and RSC are 2 different things. Our current Next.js integration is for the pages router. First class support for RSC is coming and you can follow the issue linked above

**Comment by koikiss-dev** [comment]
Thanks
