### ISSUE TITLE
chore: run `merge-main` and fix all merge conflicts

### ISSUE THREAD

**Issue by KATT** [trpc/trpc#4572]
### Describe the feature you'd like to request

We have two branches - `main` & `next`. `next` is our "next major" where we collect all big and small breaking changes we want to do in our next release.

I missed how insanely painful #4541 would be to merge.

### Describe the solution you'd like to see

Run `p merge-main`, fix all merge conflicts and open a PR

### Describe alternate solutions

No

### Additional information

Anything called `**/interop/**` can just be deleted (we have deleted interop in the next version)

<sub>From [SyncLinear.com](https://synclinear.com) | [T-113](https://linear.app/trpc/issue/T-113/chore-run-merge-main-and-fix-all-merge-conflicts)</sub>

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/4572">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/4572/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/4572/pledge.svg">
</picture>
</a>

**Comment by MOHIT-PANDEY215** [comment]
Hi @KATT , please assign this issue to me.

**Comment by juliusmarminge** [comment]
> Hi @KATT , please assign this issue to me.

Don't worry I got it. These things are a bit hairy when selecting what to keep and remove
