### ISSUE TITLE
bug: handling 'undefined' values in the blog example when  (ssr: false)

### ISSUE THREAD

**Issue by saoudi-h** [trpc/trpc#4592]
### Provide environment information

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 AMD Ryzen 7 5800X 8-Core Processor
    Memory: 18.04 GB / 31.93 GB
  Binaries:
    Node: 18.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 9.6.7 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.6.5 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Spartan (44.22621.1848.0), Chromium (114.0.1823.67)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @tanstack/react-query: ^4.18.0 => 4.18.0 
    @trpc/client: ^10.33.0 => 10.33.0 
    @trpc/next: ^10.33.0 => 10.33.0 
    @trpc/react-query: ^10.33.0 => 10.33.0 
    @trpc/server: ^10.33.0 => 10.33.0 
    next: ^13.4.7 => 13.4.7 
    react: ^18.2.0 => 18.2.0 
    typescript: ^5.1.3 => 5.1.3
```

## Context
I am currently experiencing an issue with the blog example provided by tRPC. When accessing a specific article using the URL, for example by refreshing the page /post/post_id, two calls are made to trpc.post.byId.useQuery. One call is made with the correct article ID extracted from the URL, while the other call is made with an 'undefined' value.
***
This issue occurs only when SSR (Server-Side Rendering) is set to false in the configuration file located at @/lib/trpc.ts
***

## Expected Behavior
When accessing a specific article using the URL, I expect trpc.post.byId.useQuery to correctly use the extracted article ID from the URL to make a single API call.

## Current Behavior
When accessing a specific article using the URL, two trpc.post.byId.useQuery calls are made. One call succeeds using the extracted article ID from the URL, while the other fails with an error as it receives an 'undefined' value for the article ID.

### Link to reproduction

https://stackblitz.com/github/trpc/examples-next-prisma-starter

### To reproduce

Run the blog example provided by tRPC.
[examples-next-prisma-starter](https://github.com/trpc/examples-next-prisma-starter)
Access a specific article using the URL, for example by refreshing the page http://localhost:3000/post/4d9a7d67-7a12-4f17-b88b-32132ae0445f
Observe the calls to trpc.post.byId.useQuery and any errors in the browser console.

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/4592">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/4592/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/4592/pledge.svg">
</picture>
</a>

**Comment by KATT** [comment]
This is a Next.js limitation that we don't have access to query params instantly

https://stackoverflow.com/questions/61040790/userouter-withrouter-receive-undefined-on-query-in-first-render
