### ISSUE TITLE
docs: monorepo router built

### ISSUE THREAD

**Issue by yovanoc** [trpc/trpc#4620]
### Area of Improvement

I would like to know how to have in a monorepo a packages/api package that is only for the trpc part like this one https://github.com/t3-oss/create-t3-turbo but built. I don't manage to have a build trpc router with tsconfig references or not working. I always ended up with type any with RouterOutput types and it starts working again when I dont built it but it can't be that way in my current monorepo. 

### 👨‍👧‍👦 Contributing

- [x] 🙋‍♂️ Yes, I'd be down to file a PR implementing the suggested changes!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/4620">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/4620/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/4620/pledge.svg">
</picture>
</a>

**Comment by juliusmarminge** [comment]
I think @ixahmedxi is in favor of building all his packages in noodle, instead of only transpiling it

**Comment by ixahmedxi** [comment]
> I think @ixahmedxi is in favor of building all his packages in noodle, instead of only transpiling it

Yeah Noodle doesn't transpile any packages and it also has a packages/api for tRPC. check it out at https://github.com/ixahmedxi/noodle

**Comment by yovanoc** [comment]
Ok so I have found something. 

```json
{
  "$schema": "https://json.schemastore.org/tsconfig",
  "display": "Node Next",
  "extends": "./base.json",
  "compilerOptions": {
    "lib": [
      "ESNext"
    ],
    "module": "ESNext",
    "moduleResolution": "Node",
    "target": "ESNext"
  }
}

```

its working now with this. Just changing moduleResolution to NodeNext gives me the `any` type. Thoughts ?

**Comment by juliusmarminge** [comment]
Whenever I've tried using `nodenext` it's generally broken for most stuff :/

**Comment by yovanoc** [comment]
oh ok I'm not the only one then, sad because its the way for fully esm as I think

**Comment by juliusmarminge** [comment]
Yes. I think @ixahmedxi is the one with the most experience regarding `nodenext` module resolution around here. Maybe he can confirm whether or not tRPC supports it?

**Comment by yovanoc** [comment]
My current monorepo works with 30+ packages/apps with fully esm, just trpc typings seems to not work with it when the router is build

**Comment by ixahmedxi** [comment]
what is the error that you get?

**Comment by yovanoc** [comment]
when I use nodenext I simply get `any` for personal types with RouterOutput

**Comment by sachinraja** [comment]
If you think this error is actually related to tRPC, we need a reproduction to help you.

**Comment by yovanoc** [comment]
@sachinraja Not sure if it's specifically trpc, as @juliusmarminge stated but a nodenext issue, I will do a simple reproduction very soon. Should I put it there or open a new issue? thanks.

**Comment by sachinraja** [comment]
you can post it here and I’ll reopen this.
