### ISSUE TITLE
bug: unable to build using Next.js with Turborepo, getting type errors 

### ISSUE THREAD

**Issue by sebpowell** [trpc/trpc#4624]
### Provide environment information

  System:
    OS: macOS 11.7.6
    CPU: (4) x64 Intel(R) Core(TM) i5-7600K CPU @ 3.80GHz
    Memory: 168.10 MB / 40.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 18.14.0 - ~/.nvm/versions/node/v18.14.0/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.6.6 - ~/.nvm/versions/node/v18.14.0/bin/npm
    pnpm: 8.6.0 - ~/.nvm/versions/node/v18.14.0/bin/pnpm
  Browsers:
    Brave Browser: 112.1.50.114
    Chrome: 114.0.5735.198
    Safari: 15.6
  npmPackages:
    @tanstack/react-query: ^4.29.23 => 4.29.23 
    @trpc/client: ^10.34.0 => 10.34.0 
    @trpc/react-query: ^10.34.0 => 10.34.0 
    @trpc/server: ^10.34.0 => 10.34.0 
    next: ^13.4.1 => 13.4.1 
    react: ^18.2.0 => 18.2.0 
    typescript: ^4.5.2 => 4.5.3 

### Describe the bug

I installed this library this afternoon – it's really nice, thank you for creating it. I'm using it within a Next.js project that is setup using Turborepo. Everything works ok, but when I try building, I get the following error:

```
- info Creating an optimized production build  
- info Compiled successfully
- info Linting and checking validity of types .Failed to compile.

../../node_modules/.pnpm/@trpc+server@10.34.0/node_modules/@trpc/server/dist/core/internals/mergeRouters.d.ts:6:33
Type error: '?' expected.

  4 |  */
  5 | export type MergeRouters<TRouters extends AnyRouter[], TRouterDef extends AnyRouterDef = RouterDef<TRouters[0]['_def']['_config'], {}>> = TRouters extends [
> 6 |     infer Head extends AnyRouter,
    |                                 ^
  7 |     ...infer Tail extends AnyRouter[]
  8 | ] ? MergeRouters<Tail, {
  9 |     _config: TRouterDef['_config'];
```

What is even stranger is that in the attached CodeSandbox, it seems to work without any problems – the same code however is used both on Vercel and locally, and in both cases, the above error shows. 

Any ideas what the problem might be?

### Link to reproduction

https://codesandbox.io/p/github/sebpowell/turborepo-next-basic/draft/condescending-frost

### To reproduce

In theory, if you try deploying the CodeSandbox to Vercel, you should see the same error as I do – unless of course it's a config error somewhere. 

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/4624">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/4624/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/4624/pledge.svg">
</picture>
</a>

**Comment by KATT** [comment]
Hey!

We appreciate the time you've taken to write this issue.

Unfortunately, we don't have the bandwidth to assist with issues without reproduction and this issue does not seem to be related to tRPC itself. 

Feel free to re-open with a solid reproduction repository where we can help you further or post in our help channels on [Discord](https://trpc.io/discord) or in our [GitHub Discussions](https://github.com/trpc/trpc/discussions).

**Comment by sebpowell** [comment]
@KATT apologies for the late response, I was away for a couple of days. I attempted earlier today to start a new project from scratch, and was able to get everything working without any issues, so it must have been down to some config issue somewhere, unsure what it was exactly. 

Just also wanted to say thank you for this library – it really is fantastic, I can see how this is going to make life quite a bit easier when it comes to coordinating frontend / backend, looking forward to working with it more.

**Comment by sebpowell** [comment]
@juliusmarminge – apologies as well – see above, and sorry about the Code Sandbox, I must have not made it public. I did try skipLibCheck and that didn't help, but I'm guessing it was an issue elsewhere as restarting my project from scratch solved things. I'm going to hazard a guess it might have been down to an issue with the Turborepo start project I was originally using.
