### ISSUE TITLE
bug: trpcclienterror: unterminated string in json at position 65337

### ISSUE THREAD

**Issue by WesleyYue** [trpc/trpc#4634]
### Provide environment information

```
  System:
    OS: macOS 13.2.1
    CPU: (12) arm64 Apple M2 Pro
    Memory: 130.44 MB / 32.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 18.15.0 - ~/.nvm/versions/node/v18.15.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.6.7 - ~/Code/double/node_modules/.bin/npm
  Browsers:
    Chrome: 114.0.5735.198
    Firefox: 115.0.2
    Safari: 16.3
```

### Describe the bug

I had a strange bug on production where the response to one of my trpc endpoint was truncated at 2^16 characters. Details:

- The endpoint is a simple SQL execution, which fetches data from the db, then returns a JSON result
- The typical response payload size for this end point is 10s of kB to a few MB
- This was hosted on Vercel
- This only happened with one specific request and response. ie. it was re-occuring for the same request param, which deterministically returned a certain result, but the endpoint works with other request params, which returned different results (that are even larger than the problematic one)
- After adding a singular logging statement for the result immediately before the return statement and re-deploying, the problem went away.
- The trpc handlers are hosted on a Remix server

I'm not sure this is actionable, but I figure I would leave an issue on the repo in case other people have seen the same issue with more clues, or if the maintainers have any ideas. Otherwise, feel free to close the issue.

### Link to reproduction

.

### To reproduce

Unfortunately, not reproducible.

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/4634">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/4634/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/4634/pledge.svg">
</picture>
</a>

**Comment by KATT** [comment]
Hey there! :wave:

We appreciate the time you've taken to write this issue.

Unfortunately, we don't have bandwidth to assist with issues without reproduction and this issue does not seem to be related to tRPC itself. 

Feel free to re-open with a solid reproduction repository where we can help you further or post in our help channels on [Discord](https://trpc.io/discord) or in our [GitHub Discussions](https://github.com/trpc/trpc/discussions).
