### ISSUE TITLE
bug: `inferProcedureOutput` generated type different from the type of real response for field that could be undefined

### ISSUE THREAD

**Issue by ddydng** [trpc/trpc#4645]
### Provide environment information

In [sandbox](https://codesandbox.io/p/sandbox/sleepy-https-2q72lr?file=%2Fnode_modules%2Ftypescript%2Flib%2Flib.es5.d.ts%3A737%2C5)

```
System:
    OS: Linux 5.15 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (2) x64 AMD EPYC
    Memory: 777.03 MB / 2.01 GB
    Container: Yes
    Shell: 5.1.4 - /bin/bash
  Binaries:
    Node: 16.17.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.15.0 - /usr/local/bin/npm
    pnpm: 7.1.0 - /usr/local/bin/pnpm
    Watchman: 20220528.183901.0 - /usr/local/bin/watchman
  npmPackages:
    @trpc/client: ^10.35.0 => 10.35.0 
    @trpc/react-query: ^10.35.0 => 10.35.0 
    @trpc/server: ^10.35.0 => 10.35.0 
    typescript: ^5.1.3 => 5.1.3 
```

### Describe the bug

The output of the `inferProcedureOutput` is different from the type of real response if a field can be undefined.  The type inferred will be `{fieldName: [type] | undefined}`, while the type of the real response will be `{fieldName?: [type] | undefined}`. The field name from the returned response is marked as optional, in addition to having an `undefined` type union. 

### Link to reproduction

https://codesandbox.io/p/sandbox/sleepy-https-2q72lr?file=%2Fpackage.json%3A1%2C1

### Inferred type
```
const helloProcedure = publicProcedure.input(z.string()).query(
  (opts) => {
    return {
      hello: Math.random() > 0.5 ? 'hello' : undefined;
    }
  }
);

// type helloProcedure = {
//   hello: string | undefined;
// }
export type helloProcedure = inferProcedureOutput<typeof helloProcedure>;
```

<img width="662" alt="image" src="https://github.com/trpc/trpc/assets/7049188/f548aaf3-7d24-479e-8f35-7e2b93485abf">

### Real type
```
 // const hello: {
 //   hello?: string | undefined;
 // }
 const hello = await trpc.hello.query("123");
```
If I define a function that takes the inferred type as argument, passing the real response into it won't work
<img width="476" alt="image" src="https://github.com/trpc/trpc/assets/7049188/41bd7db5-7387-4b8b-a6fc-568949bd19ac">
-------------------
<img width="633" alt="image" src="https://github.com/trpc/trpc/assets/7049188/4a2d7400-3ee7-43f3-ba11-862d0b733f1b">

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/4645">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/4645/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/4645/pledge.svg">
</picture>
</a>

**Comment by KATT** [comment]
See #4706
