### ISSUE TITLE
docs: Proxy usage is undocumented

### ISSUE THREAD

**Issue by justinfagnani** [trpc/trpc#4653]
### Area of Improvement

I'm a newcomer trying to find out why tRPC uses Proxies, and I don't see ay information on that in the docs or in jsdoc comments in the code.

I'm using `createTRPCProxyClient` to create a client, and my methods are returning `Proxy` objects, so Im' presuming that "Proxy" in the name might actually refer to JS Proxies as opposed to a client that proxies the server, but I can't really tell. `createTRPCProxyClient` has no jsdocs, and no useful docs [here](https://trpc.io/docs/typedoc/client/Functions/function.createTRPCProxyClient-1).

The type `CreateTRPCProxyClient ` has [docs](https://trpc.io/docs/typedoc/client/Type%20Aliases/type-alias.CreateTRPCProxyClient) that only say "Creates a proxy client" but I can't find anywhere that says what a "proxy client" actually _is_.

Some things that would be useful to know about the usage of Proxies:
* Why is tRPC proxying the return value of remote methdos?
* Is tRPC tracking access to object properties?
* Is tRPC wrapping methods and function-valued properties?
* Do the proxies have stable identity? Are they cached? When are they cleaned up?
* Can I use tRPC without proxies on values*?

\* I ask because I use the return values of all tRPC method to create other objects with, and most code never interacts with these proxies. A simple data object would suffice.

### Link to related docs

https://trpc.io/docs/client/vanilla/setup

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing the suggested changes!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/4653">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/4653/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/4653/pledge.svg">
</picture>
</a>

**Comment by juliusmarminge** [comment]
> I don't see ay information on that in the docs or in jsdoc comments in the code

It's an implementation detail that users shouldn't need to care about.

To answer your question, the proxy we refer to is a [JavaScript Proxy object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy) that allows us to do the router traversal on the frontend. We wrote a blog post here about how you can write your own client that explains a bit how and what the proxy does: https://trpc.io/blog/tinyrpc-client

**Comment by justinfagnani** [comment]
Thanks for the link!

At a glance that seems to explain why the client is implemented with a Proxy, but my question is more about why the return values are proxies instead of regular objects. Is there some observability of data fields happening?

> It's an implementation detail that users shouldn't need to care about.

I don't think this is true. Proxies have non-transparent behavior - they can break maps and private fields if not handled correctly, and in general you may have to think about identity carefully. The specifics of the whys and hows of Proxy usage could definitely affect someone's decision to use a library.

**Comment by juliusmarminge** [comment]
> why the return values are proxies instead of regular objects

not sure what you mean? the query result should be regular javascript objects
