### ISSUE TITLE
feat: Add a way to do some kind of TRPC-integrated client side validation?

### ISSUE THREAD

**Issue by Angelelz** [trpc/trpc#4654]
### Describe the feature you'd like to request

Integrate some type of input validation on the client, (should obviously be the same as the server) so that TRPC can update the error without doing an over-the-wire request.

### Describe the solution you'd like to see

Be able to provide the same validation schema that you provide to the router in the server to `useMutation` function.
That way the error can be updated in the client without having to do an over the wire request.
Now, I understand, this can be done in some other way, but the convenience of using only one source of truth for the error would be nice.

### Describe alternate solutions

TRPC could also provide a way to update the error from the context. Similar to how you can update the cache with `setData`, maybe expose a `setError` function to do the same with the error.

### Additional information

In Monorepo setups the validation schema can be easily be shared from a package to the server and the client.

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/4654">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/4654/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/4654/pledge.svg">
</picture>
</a>

**Comment by juliusmarminge** [comment]
Alex made a hacky way to fetch the validator here: https://github.com/KATT/next-trpc-form-proc/pull/1

Still requires a request to the backend, but only a single one since when the validator has been fetched it lives on the client.

Not the best approach but I don't think you can do any better without server components.

**Comment by KATT** [comment]
Also, you might be interested in https://kitchen-sink.trpc.io/react-hook-form

**Comment by KATT** [comment]
- You are able to make an endpoint to fetch validation schema as show in https://github.com/KATT/next-trpc-form-proc/pull/1 -(https://github.com/KATT/next-trpc-form-proc/blob/639b6d23e6bad109913a50d0379315b0154c30aa/src/pages/api/trpc/%5Btrpc%5D.ts#L37-L64)
- You are able to import the same schema by putting it in a shared folder https://kitchen-sink.trpc.io/react-hook-form


Doing this automatically without a HTTP-request requires a compilation-step which extracts the schema somewhere automagically. We're not planning on going to go down the route of doing compilation steps.
