### ISSUE TITLE
feat: useLazyQuery hook for react integration

### ISSUE THREAD

**Issue by etareduction** [trpc/trpc#4659]
### Describe the feature you'd like to request

I think it would be strongly beneficial for trpc react api to have a hook which allows you to create a query without providing parameters, created query would be disabled by default and return a function that allows you to provide params and run it. Like so:
```tsx
const [exampleQuery, fetchExampleQuery] = api.example.multiplyByTwo.useLazyQuery()
const input = 5

return <button onClick={() => fetchExampleQuery({ value: input })} />
```
It is a feature in tanstack query which is implemented by `{ enabled: boolean }` parameter of `useQuery`, but it doesn't allow full type safety this way. Proposed way does while achieving same functionality.

### Describe the solution you'd like to see

Addition of a new `useLazyQuery` hook for react which accepts all the usual parameters of `useQuery` except the first one (query arguments) being wrapped in `Partial<>`. Unfortunately it would also require passing in an input types resolver which exactly matches query inputs by signature, so we can verify that params set is now complete and query can be enabled.

The implementation could look something like this:
```ts
const [params, setParams] = useState(initialParams)

const query = useQuery(
    params as Required<typeof params>,
    { ...options, enabled: schema.safeParse(params).success }
)

return [query, (newParams) => setParams(newParams)]
```

### Describe alternate solutions

Alternatives for this usecase which i found are:

- Doing unsafe null-assertions with `enabled` option of `useQuery`, which is prone to accidentally forgetting to set `enabled`
   ```ts
   const query = useQuery({ value: trustMeBro! }, { enabled: !!trustMeBro })
   ```
- Decomposing the query into it's own component and rendering it conditionally, which adds complexity and is not always desirable
- Marking whole input object or some of it's fields optional on the server side, and doing runtime validation in the resolver. It is runtime errors instead of compile-time errors, so obviously not a good choice

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/4659">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/4659/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/4659/pledge.svg">
</picture>
</a>

**Comment by bharatchhabraai** [comment]
What's the current way to do this? I want to call useQuery when I will have data from API call? How to do that as of now?

**Comment by KATT** [comment]
`enabled: false`

**Comment by etareduction** [comment]
@KATT What's your opinion on this feature? Would you accept if it is implemented?

**Comment by capaj** [comment]
@KATT `enabled: false` can certainly be used, but coming from apollo client I was a bit confused how to do this.
Please consider it for addition. It's not just an alias, it's also a different return from the hook which is so nice to have. For a lazy query you don't need to return props like `data` and `isLoading` from the hook.

Just in the past month I have seen other devs on code reviews I've done: 
 - using a mutation instead of a query because to avoid the query call on initial render
 - calling the query on init with empty values and then refetching later basically abusing the BE
 
 
 like you I told them to use `enabled:false`, but for them a much better experience would be if they just had lazy query as another method.
 We have `useInfiniteQuery`, IMHO `useLazyQuery` is even more useful.

**Comment by KATT** [comment]
If you convince the React Query-peeps to add it, we'll add it in tRPC too :)

But for now, we won't add it in tRPC as it'll increase maintenance burden + bundle size and I'm not convinced it's needed, you can probably to a wrapper around your query client to add this.

**Comment by etareduction** [comment]
> If you convince the React Query-peeps to add it, we'll add it in tRPC too :)
> 
> But for now, we won't add it in tRPC as it'll increase maintenance burden + bundle size and I'm not convinced it's needed, you can probably to a wrapper around your trpc instance to add this.

I think it couldn't be implemented in React Query the way I've described in the topic. It requires type knowledge which only TRPC has. Maybe a lot more generic version could be implemented in React Query but I'm not sure how that would look like. Implementation I've described seems very simple.

What do you mean by a wrapper? My own proxy object which is cast to trpc type plus my own? That sounds kinda hard. Do you have any example libraries in mind which do that?

**Comment by KATT** [comment]
Best reference I can think of is https://trpc.io/blog/tinyrpc-client

**Comment by umutbozdag** [comment]
Even though with `enabled: false`, I need to set the params undefined or null so I must change my tRPC procedure structure to accept undefined or null as input values and this felt so wrong.
