### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by wststone** [trpc/trpc#4667]
### Provide environment information

System:
    OS: macOS 13.1
    CPU: (8) arm64 Apple M1
    Memory: 71.97 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.12.0 - /usr/local/opt/nvm/versions/node/v18.12.0/bin/node
    Yarn: 1.22.19 - /usr/local/opt/nvm/versions/node/v18.12.0/bin/yarn
    npm: 8.19.2 - /usr/local/opt/nvm/versions/node/v18.12.0/bin/npm
    pnpm: 8.6.0 - /usr/local/opt/nvm/versions/node/v18.12.0/bin/pnpm
    Watchman: 2022.08.22.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 115.0.5790.114
    Safari: 16.2
  npmPackages:
    @tanstack/react-query: ^4.3.8 => 4.3.8 
    @trpc/client: latest => 10.34.0 
    @trpc/next: latest => 10.34.0 
    @trpc/react-query: latest => 10.34.0 
    @trpc/server: latest => 10.36.0 
    next: ^13.0.0 => 13.0.0 
    react: ^18.2.0 => 18.2.0 
    typescript: ^4.8.3 => 4.8.3 

### Describe the bug

reproduction repo https://github.com/wststone/trpc-proxyclient-helper-issue/

`createServerSideHelpers` with client does not work with ssr, as you can see in the screenshots

index.tsx
![image](https://github.com/trpc/trpc/assets/42225395/d2e5ac49-e0ea-4aad-b1f0-1f543b9e0392)

not-working.tsx
![image](https://github.com/trpc/trpc/assets/42225395/7e3f24a3-da35-4762-a502-6acef70ce64b)

when i inspected the data from `helpers.dehydrate()`, it already has the query state, however there it's warning that basically says `JSON.parse` failed? 

![image](https://github.com/trpc/trpc/assets/42225395/2ef125e8-edf9-4c76-a779-2c691e23d8a9)

so I commented out the `superjson` transformer in both the trpc server file and the proxyclient file, it gives an error of undefined is not serializable.

Not sure if this the intended behavior, i basically just followed the documentation https://trpc.io/docs/client/nextjs/server-side-helpers here and example https://github.com/trpc/trpc/tree/main/examples/.test/ssg here.

### Link to reproduction

https://stackblitz.com/~/github.com/wststone/trpc-proxyclient-helper-issue

### To reproduce

run the example project and inspect the html file generated during ssr

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/4667">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/4667/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/4667/pledge.svg">
</picture>
</a>

**Comment by lucasfranzolin** [comment]
Yep, same here! And, no examples using `createProxySSGHelpers`... that would help a lot!

**Comment by juliusmarminge** [comment]
I'm not sure what you're referring to, your sandbox is working fine?

https://github.com/trpc/trpc/assets/51714798/aa9b836a-2169-4bd9-a221-c017d94a88d1

Also tested locally and had no issues getting it working with a client

**Comment by juliusmarminge** [comment]
> Yep, same here! And, no examples using `createProxySSGHelpers`... that would help a lot!

We have multiple examples using the ssg helpers, maybe none that uses a client though.

- https://github.com/trpc/trpc/tree/main/examples/.test/ssg
- https://github.com/trpc/trpc/tree/main/examples/next-prisma-todomvc

**Comment by wststone** [comment]
> I'm not sure what you're referring to, your sandbox is working fine?
> 
>  CleanShot.2023-07-29.at.22.45.52.mp4 
> Also tested locally and had no issues getting it working with a client

Thanks for looking into it so quickly, the none working example is at /not-working, maybe try that in the stackblitz enviorment? You would see a brief flash of the `Loading...` on the first render.

**Comment by juliusmarminge** [comment]
> Thanks for looking into it so quickly, the none working example is at /not-working, maybe try that in the stackblitz enviorment? You would see a brief flash of the Loading... on the first render.

That's cause you're not fetching the correct URL on the server. Add the pathname to the end and it works:

<img width="408" alt="CleanShot 2023-07-30 at 10 53 20@2x" src="https://github.com/trpc/trpc/assets/51714798/a5e07d8d-61f5-494f-bfbc-2a8da21933e1">
