### ISSUE TITLE
feat: Passing Additional State to Create Context in Fetch Request Handler

### ISSUE THREAD

**Issue by willpuckett** [trpc/trpc#4676]
### Describe the feature you'd like to request

I'm still relatively new to tRPC, but I have been having a great time getting to know it. Put another way, it's entirely possible that this feature request already exists and I'm just not using the software as intended.

I've been exploring using tRPC with Fresh. I implemented the fetch request handler at /api/[trpc].ts. 

I also am using DenoKV OAuth to authenticate users. KV Oauth sits in a root level middleware in the fresh project so that the app wrapper can show the correct login/out and page buttons in the header.

The create context function seems to only accept req and resHeaders, but I am trying to pass my loggedIn state from the Fresh middleware into tRPC. 

If I revalidate the oauth session from the req in the create context function, it's noticeably slower, which is undesirable, but it also seems unreasonable to not generate the user state in the high level middleware.

### Describe the solution you'd like to see

What I think makes sense is to add a tertiary parameter to the fetch request handler that can accept an arbitrary state object. This would allow passing ctx from a framework into createContext from the fetch request handler [here](https://github.com/trpc/trpc/blob/176c0dbeb420cb8bd946bd2338eca0b0e41c85e8/packages/server/src/adapters/fetch/fetchRequestHandler.ts#L19C5-L19C5). 

### Describe alternate solutions

I'm currently working around this by not using context in tRPC and handling all the authentication via Fresh middlewares. It's less than ideal, but works for a smaller project.

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/4676">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/4676/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/4676/pledge.svg">
</picture>
</a>

**Comment by juliusmarminge** [comment]
I think this is what you're looking for:

```ts
// api/trpc/[trpc].ts
import { createContext } from "~/server/trpc/context";
...

function handler(request: Request) {
  const myObj = doSomethingWithRequest(request);

  return fetchRequestHandler({
    endpoint: '/trpc',
    req: request,
    router: appRouter,
    createContext: (opts) => createContext({ req: request, myObj }),
  });
}

// server/trpc/context.ts
import { FetchCreateContextFnOptions } from '@trpc/server/adapters/fetch';

interface CreateContextOptions extends FetchCreateContextFnOptions {
  myObj: foobarbaz
}

function createContext(opts: CreateContextOptions) {
  ...
}
```

**Comment by willpuckett** [comment]
Thanks so much works great!
