### ISSUE TITLE
bug:  The trouble with Cloudflare Worker example

### ISSUE THREAD

**Issue by Heezay** [trpc/trpc#4684]
### Provide environment information

  System:
    OS: Linux 5.10 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
    CPU: (24) x64 AMD Ryzen 9 5900X 12-Core Processor
    Memory: 24.33 GB / 24.98 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 16.20.1 - ~/.nvm/versions/node/v16.20.1/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 8.19.4 - ~/.nvm/versions/node/v16.20.1/bin/npm
  npmPackages:
    @trpc/server: ^10.36.0 => 10.36.0

### Describe the bug

I followed the guide and faced the error when using `npx wrangler dev` command with text below:

`{"error":{"message":"No \"query\"-procedure on path \"\"","code":-32004,"data":{"code":"NOT_FOUND","httpStatus":404,"stack":"TRPCError: No \"query\"-procedure on path \"\"\n    at callProcedure (index.js:356:11)\n    at inputToProcedureCall (index.js:500:24)\n    at index.js:612:49\n    at Array.map (<anonymous>)\n    at resolveHTTPResponse (index.js:612:28)","path":""}}}`

Is this expected behavior or what gonna wrong? I created repo in github. Link to see that below. 

### Link to reproduction

https://github.com/Heezay/CF-Worker

### To reproduce

Install deps:
`pnpm add @trpc/server zod`
Then install wrangler globally:
`npm install -g wrangler`
And use the command:
`npx wrangler dev` 

### Additional information

Will be glad to see some solves of this problem. 

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/4684">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/4684/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/4684/pledge.svg">
</picture>
</a>

**Comment by KATT** [comment]
Not a bug - it seems like something is doing a request to `/`?

**Comment by Heezay** [comment]
Request to `http://127.0.0.1:8787/trpc` . The url of my clouflare worker

**Comment by KATT** [comment]
It's simply saying you don't have a procedure at path `''` which is likely `/trpc`

If you add a procedure like `hello: t.procedure.query(() => 'hello')` you'll be able to access that at `http://127.0.0.1:8787/trpc/hello`

**Comment by KATT** [comment]
Please ask questions on Discord or GitHub discussions if you have further questions.
