### ISSUE TITLE
Middleware return type isn't typed correctly

### ISSUE THREAD

**Issue by laneme** [trpc/trpc#4702]
### Provide environment information

```sh
  System:
    OS: Linux 6.2 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
  npmPackages:
    typescript: ^5.1.3 => 5.1.6
```

### Describe the bug

When writing middlewares, and returning context conditionally, it only picks up one return type. Lemme show you
```ts
const buggedMiddleware = (props?: { silent?: boolean }) =>
  trpcMiddleware(async (opts) => {
    const { req } = opts.ctx;

    try {
      // check token in cookies
      const token = req.headers["authorization"];
      if (!token) throw new Error("expected token");

      return opts.next({
        ctx: { user: { email: "successfull@success.tree" } },
      });
    } catch (error) {
      if (props?.silent) {
        return opts.next({ ctx: { user: undefined } });
      }

      throw error;
    }
  });
```

Return type should be 
```ts
(property) ctx: {
    user: user | undefined
}
```
But is just `{ctx: { user }}`. Definitely not what I exptect.

### Link to reproduction

https://github.com/laneme/trpc-middleware-type-bug

### To reproduce

Clone https://github.com/laneme/trpc-middleware-type-bug and run `yarn`

Go to `server/index.ts` and hover over `opts.ctx.user`. It'll show its typed

```ts
(property) user: {
    email: string;
}
```

But if you inspect buggedMiddleware, you'll see the `user` isn't gauranteed. It should've been typed `user | undefined`, not as above.

### Additional information

Look at this conditional return
```ts
if (someCondition) return opts.next({ ctx: { user: undefined } });
else return opts.next({ ctx: { user: "I am a user" } });
``` 
Whatever you throw at `someCondition`, `ctx` will always be `{user: undefined}` inside your queries. Doesnt matter if that condition is an optional argument, unknown, or anything.

It just picks up the first return type.

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/4702">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/4702/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/4702/pledge.svg">
</picture>
</a>

**Comment by KATT** [comment]
That's not a big, it's just impossible to infer in TS. Do two middleware or do an explicit type like


```ts
const notBuggedMiddleware = (props?: { silent?: boolean }) =>
  trpcMiddleware(async (opts) => {
    const { req } = opts.ctx;

    type User = { 
      email: "hello@example.com"
    }
    type Return = User | undefined;
    try {
      // check token in cookies
      const token = req.headers["authorization"];
      if (!token) throw new Error("expected token");

      const user: Return = { email: "successfull@success.tree" };
      return opts.next({
        ctx: { user },
      });
    } catch (error) {
      const user: Return = undefined;
      if (props?.silent) {
        return opts.next({ ctx: { user } });
      }

      throw error;
    }
  });
```

**Comment by KATT** [comment]
Try to avoid control flow that is based on try/catch blocks. Especially if you want inference.

**Comment by KATT** [comment]
A much better way of writing your middleware:


```ts

async function getUserFromReq(req: Request) {
    // check token in cookies
    const token = req.headers["authorization"];
    if (!token) {
      return null;
    }

    return {
      email: "hello@example.com",
    };
}
const notBuggedMiddleware = (props?: { silent?: boolean }) =>
  trpcMiddleware(async (opts) => {
    const { req } = opts.ctx;

    const user = await getUserFromRequest(req);
    return opts.next({
      ctx: { user },
    });
  });
  ```

**Comment by laneme** [comment]
> A much better way of writing your middleware:

You cleaned it up, i get that. I just missed the inference part.

Like if you just add this condition, inference doesn't work anymore
```ts 
  if (!token) {
    if (!silent) throw new Error("Unauthorized");
    return null;
  }
```
As you said, its impossible to infer this way. So i'll just do two middlewares for this case.

Can probably be solved by a generic too I suppose. This way this is explicit.
Like this simple cases can be solved

```ts
function test<S extends boolean>(silent: S): S extends true ? string : number;

function test(silent: boolean) {
  if (silent) return "fsdfd";
  return 500;
}
```

Thank you for the help.

Btw, would you have time to look at this [discussion](https://github.com/trpc/trpc/discussions/4690) please?
