### ISSUE TITLE
docs: update Nextjs intergration guide with app-router

### ISSUE THREAD

**Issue by ishowman** [trpc/trpc#4730]
### Area of Improvement

I would like to see how to add tRPC to newest NextJS which use `app-router` default

### Link to related docs

https://trpc.io/docs/client/nextjs

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing the suggested changes!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/4730">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/4730/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/4730/pledge.svg">
</picture>
</a>

**Comment by KATT** [comment]
This will happen when we have an official stable package, for now see https://trpc.io/docs/faq#does-trpc-work-with-nextjs-13-app-layouts--rsc
