### ISSUE TITLE
bug: Upgrading trpc fails at `inferRouterOutputs` - AppRouter does not satisfy the constraint 'AnyRouter'

### ISSUE THREAD

**Issue by mkosir** [trpc/trpc#4738]
### Provide environment information

```sh
  System:
    OS: macOS 13.5.1
    CPU: (12) arm64 Apple M2 Max
    Memory: 92.08 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.17.1 - ~/.nvm/versions/node/v18.17.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.17.1/bin/yarn
    npm: 9.6.7 - ~/.nvm/versions/node/v18.17.1/bin/npm
  Browsers:
    Chrome: 116.0.5845.96
    Safari: 16.6
  npmPackages:
    @tanstack/react-query: 4.33.0 => 4.33.0 
    @trpc/client: 10.34.1 => 10.34.1 
    @trpc/react-query: 10.34.1 => 10.34.1 
    @trpc/server: 10.34.1 => 10.34.1 
    next: 13.4.19 => 13.4.19 
    react: 18.2.0 => 18.2.0 
    typescript: 5.1.6 => 5.1.6 
```

### Describe the bug

Hey all, happy user of tRPC here 🚀 

Importing trpc type definitions (AppRouter) from [separate (BE) repo](https://github.com/mkosir/trpc-api-boilerplate/blob/main/trpc-api-export/dist/index.d.ts) to [(FE) repo](https://github.com/mkosir/trpc-fe-boilerplate/blob/main/src/common/trpc-api-boilerplate/types.ts#L8), which up until `v10.34.0` works ok.
If I try to upgrade (any) version higher than that it fail with an error:
```sh
Type 'CreateRouterInner<RootConfig<{ ctx: { req: express.Request<express_serve_static_core.ParamsDictionary, any, any, qs.ParsedQs, Record<string, any>>; res: express.Response<any, Record<string, any>>; }; meta: object; errorShape: DefaultErrorShape; transformer: typeof SuperJSON; }>, { ...; }>' does not satisfy the constraint 'AnyRouter'.
  The types returned by 'createCaller(...)' are incompatible between these types.
    Type 'DecoratedProcedureRecord<{ batch: CreateRouterInner<RootConfig<{ ctx: { req: express.Request<express_serve_static_core.ParamsDictionary, any, any, qs.ParsedQs, Record<string, any>>; res: express.Response<any, Record<string, any>>; }; meta: object; errorShape: DefaultErrorShape; transformer: typeof SuperJSON; }>, { ....' is not assignable to type 'DecoratedProcedureRecord<any> & { query: inferHandlerFn<any>; mutation: inferHandlerFn<any>; subscription: inferHandlerFn<any>; }'.
      Type 'DecoratedProcedureRecord<{ batch: CreateRouterInner<RootConfig<{ ctx: { req: express.Request<express_serve_static_core.ParamsDictionary, any, any, qs.ParsedQs, Record<string, any>>; res: express.Response<any, Record<string, any>>; }; meta: object; errorShape: DefaultErrorShape; transformer: typeof SuperJSON; }>, { ....' is not assignable to type 'DecoratedProcedureRecord<any>'.
        Property 'query' is incompatible with index signature.
          Type 'inferHandlerFn<{}>' is not assignable to type 'DecoratedProcedureRecord<any> | DecorateProcedure<any>'.
            Type 'inferHandlerFn<{}>' is not assignable to type 'DecorateProcedure<any>'.
              Types of parameters 'path' and 'input' are incompatible.
                Type 'any' is not assignable to type 'never'.ts(2344)
```
![image](https://github.com/trpc/trpc/assets/3073826/b6ecfb18-86dd-40a6-a836-d69828d9f57d)

### Link to reproduction

https://github.com/mkosir/trpc-fe-boilerplate

### To reproduce

- clone the [repo](https://github.com/mkosir/trpc-fe-boilerplate)
- run `npm i`
- run `npm run tsc` -> no error
- Upgrade trpc packages by replacing lines 20-23 in `package.json` with:
```sh
    "@trpc/client": "10.34.1",
    "@trpc/react-query": "10.34.1",
    "@trpc/server": "10.34.1",
```
- run `npm i`
- run `npm run tsc` -> error

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/4738">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/4738/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/4738/pledge.svg">
</picture>
</a>

**Comment by KATT** [comment]
Hey, thanks for the detailed repro!

Could it be that the `"trpc-api-boilerplate"` has a hard dependency on tRPC 10.34.0? The tRPC versions gotta match

**Comment by KATT** [comment]
For the base package in https://github.com/mkosir/trpc-api-boilerplate/tree/main, I think you should split it up a bit:

- Separate the concept of the _server_ and the _library_ which is the API
- The _library_ has:
  - probably no hard dependencies 
  - tRPC should have a peer-dep (not a dep like it is now) on a specific tRPC version
  - exports a trpc router, but has no dep on cors/express/etc
 - The frontend uses the library
 - The server repo uses the library (maybe that could be embedded in the same repo)

**Comment by KATT** [comment]
Let me know if it works after upgrading the backend package's trpc version
