### ISSUE TITLE
feat: add a listener to standalone server

### ISSUE THREAD

**Issue by luixo** [trpc/trpc#4740]
### Describe the feature you'd like to request

I use tRPC as a helper tool to manage databases yielding in my test backbone.
To run starting setup [I need to wait](https://github.com/luixo/receipt-app/pull/2/files?diff=split&w=1#diff-6a0dad1153b6b44d0d07bf1db78d7c7b26021aae5940150b440f2d558094b88aR29-R32) until the server is bootstrapped, but I have no option for that with a standalone server package.

### Describe the solution you'd like to see

Add a listener passed to the `http` server instance. The patch [can be found](https://github.com/luixo/receipt-app/pull/2/files?diff=split&w=1#diff-76e074d8439d47f302e7eb34678ef817ac4af0cf44e9b0d378535e5370d3399d) in my repo.

### Describe alternate solutions

Use external methods of checking server listening

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/4740">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/4740/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/4740/pledge.svg">
</picture>
</a>

**Comment by KATT** [comment]
I don't really see how this is related to tRPC? Can't you use e.g. `npx wait-port ...`?

I think this is out of scope of what we want to do

**Comment by KATT** [comment]
Yeah, I'm pretty sure we won't do this - we just wanna do wrapper around existing providers like express/fastify/vanilla/etc but not add functionality as then we have to make sure we do the same for all

**Comment by luixo** [comment]
> I don't really see how this is related to tRPC? Can't you use e.g. npx wait-port ...?
I think this is out of scope of what we want to do

`createHTTPServer` is a thin wrapper around `server.listen` and I don't see why we can't pass all the same arguments to that function (currently we reuse `port`, but it seems like we can always use `server.address().port` to get `actualPort`) limiting it to just `hostname / port`.

I wouldn't consider that new functionality, just a more convenient way to use standalone adapter.

**Comment by sachinraja** [comment]
yeah, after reading your patch - this is fine

**Comment by sachinraja** [comment]
see @kamilogorek's comment https://github.com/trpc/trpc/pull/4756#issuecomment-1699180543
