### ISSUE TITLE
bug: AbortController's cancel() called after every outgoing request finishes

### ISSUE THREAD

**Issue by kieranm** [trpc/trpc#4750]
For background, we use TRPC for server <> server communication, which is not the primary use case, but it does work really well. This post concerns the TRPC client's HTTP link, and talks about **outgoing** requests to other TRPC services from a client perspective. When we initialise the `HTTPLink`, we pass in an `AbortController` from the `adobe-fetch` library. We use `adobe-fetch` because it has the best HTTP/2 support.

We're seeing sporadic `AbortError`s being thrown sometimes (on the client side) when we try to make requests from one service to another. It's very unclear to me why this is happening at the moment, I'm investigating it.

I noticed something curious. The abort() method on the AbortController (passed into the HTTP link as an argument) seems to be being called at the end of every outgoing request, regardless of whether or not that request was successful.

<img width="555" alt="Screenshot 2023-08-26 at 16 50 19" src="https://github.com/trpc/trpc/assets/232283/579cb6d8-888f-45a7-b50b-6066e01f6a56">

Looking in the code here.
https://github.com/trpc/trpc/blob/main/packages/client/src/links/internals/httpUtils.ts#L200-L202

```
export function httpRequest(
  opts: HTTPRequestOptions,
): PromiseAndCancel<HTTPResult> {
  const ac = opts.AbortController ? new opts.AbortController() : null;
  const meta = {} as HTTPResult['meta'];

  const promise = new Promise<HTTPResult>((resolve, reject) => {
    fetchHTTPResponse(opts, ac)
      .then((_res) => {
        meta.response = _res;
        return _res.json();
      })
      .then((json) => {
        meta.responseJSON = json;
        resolve({
          json: json as TRPCResponse,
          meta,
        });
      })
      .catch((err) => {
        reject(TRPCClientError.from(err, { meta }));
      });
  });
  const cancel = () => {
    ac?.abort();
  };
  return { promise, cancel };
}
```

The `cancel` function here ultimately ends up being given to the observable as a cleanup function [here](https://github.com/trpc/trpc/blob/main/packages/client/src/links/httpLink.ts#L76-L78C13)

I didn't expect this, I'm sorry if I'm missing something, but I would only expect `cancel()` to be invoked when the requester actually wants to cancel a request that is currently in flight, and not every time after a request has completed.

Is this behaviour intentional? What is the rationale behind this approach? I can't be certain this has something to do with the errors we're seeing but it feels like it might.

Thanks!

_Originally posted by @kieranm in https://github.com/trpc/trpc/discussions/4749_

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/4750">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/4750/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/4750/pledge.svg">
</picture>
</a>

**Comment by kieranm** [comment]
More broadly I'm struggling to understand the approach to request cancellation from the docs and code.

The docs say here that in order to cancel an in-flight request, a signal can be used as follows...
```
// @filename: server.ts
import { createTRPCProxyClient, httpBatchLink } from '@trpc/client';
import type { AppRouter } from 'server.ts';
 
const proxy = createTRPCProxyClient<AppRouter>({
  links: [
    httpBatchLink({
      url: 'http://localhost:3000/trpc',
    }),
  ],
});
 
// 1. Create an AbortController instance - this is a standard javascript API
const ac = new AbortController();
 
// 2. Pass the signal to a query or mutation
const query = proxy.userById.query('id_bilbo', { signal: ac.signal });
 
// 3. Cancel the request if needed
ac.abort();
```

However I can't see anywhere in the HTTP Link where this signal ends up being passed into the `fetch` method to allow the in flight request to be cancelled. The only signal that is passed into the `fetch` method is one initialised at request time [here](https://github.com/trpc/trpc/blob/main/packages/client/src/links/internals/httpUtils.ts#L171).

In my head (I could be missing something big) the signal from step (2) above would be passed straight through to the `fetch` call, if the signal is provided. There is otherwise no need to create/initialise an AbortController at runtime.

Hope someone can help me understand this better! Thanks again

**Comment by KATT** [comment]
Yeah, the issue is that the underlying observable will always call the cleanup function of a link and therefore the abort will be called regardless

**Comment by KATT** [comment]
Yeah, the issue is that the underlying observable will always call the cleanup function of a link and therefore the abort will be called regardless

**Comment by KATT** [comment]
Yeah, the issue is that the underlying observable will always call the cleanup function of a link and therefore the abort will be called regardless
