### ISSUE TITLE
feat: guard middlewares

### ISSUE THREAD

**Issue by pepyta** [trpc/trpc#4760]
### Describe the feature you'd like to request

It would be nice if tRPC had a built in feature to handle permissions checks. We could have an additional `useGuard` hook that would receive the same inputs as the underlying procedure, but would just run until all of the `guard middlewares` have finished running.

### Describe the solution you'd like to see

As opposed to the alternate solution described below, I think this would give a better DX:

### Backend

```typescript
router({
    example: protectedProcedure
        // we are using guard instead of middleware for permission checks
        .guard(async (opts) => {
            const permissions = await getPermissions(opts.ctx.user);

            if(!permissions.includes("EXAMPLE_PERMISSION")) {
                throw new TRPCError({
                    message: "You don't have permission to do this!",
                    code: "FORBIDDEN",
                });
            }

            return opts.next();
        })
        .mutation(...),
});    
```

### Frontend

```typescript
const ExampleComponent = () => {
    const { hasPermisison, error } = trpc.example.useGuard();
    const { mutate, isLoading } = trpc.example.useMutation();

    return (
        <Button onClick={mutate} loading={isLoading} disabled={!hasPermisison}>
                {error.message ?? "Click me!"}
        </Button>
    );
};
```

The `useGuard` hook could work just as a regular `useQuery`, and would return a boolean indicating that the guards have passed all of the checks (or would return undefined until the server don't respond). If an error occured during permission checks, then we would just return the error as if it was a regular query.

### Describe alternate solutions

Currently, we are using middlewares to handle permission checks like this:

### Backend

```typescript
router({
    example: protectedProcedure
        .use(async (opts) => {
            const permissions = await getPermissions(opts.ctx.user);
            if(!permissions.includes("EXAMPLE_PERMISSION")) {
                throw new TRPCError({
                    message: "You don't have permission to do this!",
                    code: "FORBIDDEN",
                });
            }

            return opts.next();
        })
        .mutation(...),

    permission: router({
        list: protectedProcedure
                  .query((opts) => getPermissions(opts.ctx.user)),
    }),
});    
```

### Frontend

```typescript
const ExampleComponent = () => {
    const [permissions] = trpc.permission.list.useSuspenseQuery();
    const { mutate, isLoading } = trpc.example.useMutation();

    if(!permissions.includes("EXAMPLE_PERMISSION")) {
        return "You don't have permission to do this!";
    }

    return (
        <Button onClick={mutate} loading={isLoading}>
                Click me!
        </Button>
    );
};
```

As you can see, this works, but we have to write a permission checks both on frontend and backend. It becomes a problem, when we edit the backend and not the frontend (or vice versa).

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/4760">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/4760/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/4760/pledge.svg">
</picture>
</a>

**Comment by sachinraja** [comment]
I think this is too much to add on top of how tRPC already works. It's not really tRPC's concern in the first place, but there is a nice way of doing this that @KATT has already explored.

I can't seem to find it anywhere so I'll just give you a summary of how it works (although it would likely be difficult to implement without knowledge of the internals):
- `permissions: string[]` in `meta`
- define permissions for each procedure
- have another procedure `getPermissions` which takes in a string input
- `getPermissions` looks up the input (a procedure path) in the router and accesses the permissions that the procedure requires (stored in `meta`)
- checks if the user has those permissions

this is what it would look like:
```ts
// trpc.usePermission is a hook that calls trpc.getPermissions with the procedure path
// this utility is necessary to make the types/DX nice
const { hasPermission, error } = trpc.usePermission(trpc.example);
const { mutate, isLoading } = trpc.example.useMutation();

return (
    <Button onClick={mutate} loading={isLoading} disabled={!hasPermisison}>
            {error.message ?? "Click me!"}
    </Button>
)
```
