### ISSUE TITLE
bug: unstable_httpBatchStreamLink returns broken json response when deployed with SST

### ISSUE THREAD

**Issue by pieter-berkel** [trpc/trpc#4765]
### Provide environment information

```
System:
    OS: macOS 13.5.1
    CPU: (8) arm64 Apple M1
    Memory: 218.00 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.17.1 - /opt/homebrew/opt/node@18/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.6.7 - /opt/homebrew/opt/node@18/bin/npm
    pnpm: 8.7.0 - /opt/homebrew/bin/pnpm
  Browsers:
    Chrome: 116.0.5845.110
    Safari: 16.6
```

### Describe the bug

When testing locally or when building and starting locally everything works correct, but when deployed with SST to AWS servers I get a JSON response with extra numbers. This results in a client side error. 

I think the problem has to do with AWS lambda not having full stream support.

### Link to reproduction

https://google.nl

### To reproduce

This is when using a client side hook like useQuery or useSuspenseQuery and deploy the NextJS project with SST to AWS.

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/4765">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/4765/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/4765/pledge.svg">
</picture>
</a>

**Comment by juliusmarminge** [comment]
AWS Lambda doensn't support streaming afaik? Services like Vercel has their own layer to support this: https://vercel.com/blog/streaming-for-serverless-node-js-and-edge-runtimes-with-vercel-functions
