### ISSUE TITLE
feat: Speed up with `fast-json-stringify`

### ISSUE THREAD

**Issue by FishOrBear** [trpc/trpc#4767]
### Describe the feature you'd like to request

We have zod, and we have type annotations. It seems that it is not difficult to achieve this. I don’t know if this is available now, but I think can try it?

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/4767">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/4767/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/4767/pledge.svg">
</picture>
</a>

**Comment by sachinraja** [comment]
type annotations cannot be accessed at runtime. however we are working on an external tool that could do what you're asking for. it will not be integrated into the official library though.
