### ISSUE TITLE
feat: Support SvelteKit

### ISSUE THREAD

**Issue by macmillen** [trpc/trpc#4768]
### Describe the feature you'd like to request

It would be nice to have an official SvelteKit integration.

### Describe the solution you'd like to see

.

### Describe alternate solutions

.

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/4768">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/4768/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/4768/pledge.svg">
</picture>
</a>

**Comment by sachinraja** [comment]
There's a maintained integration here: https://github.com/icflorescu/trpc-sveltekit

We also have a fetch adapter and vanilla client which should work well in SvelteKit too. We won't have an official integration as no one in the core team uses SvelteKit so we cannot maintain it.
