### ISSUE TITLE
feat: Stable context during next navigation and thus fewer rerendering

### ISSUE THREAD

**Issue by enex** [trpc/trpc#4773]
### Describe the feature you'd like to request

It would be beneficial if the context provided by `withTrpc` that is accessible via `useContext` is stable when navigating in next. I have several places where i Use mutations in my code that trigger unnecessary rerenders on every url search param change which in my application is relatively frequent.

### Describe the solution you'd like to see

I would want the object generated at https://github.com/trpc/trpc/blob/main/packages/react-query/src/shared/hooks/createHooksInternal.tsx#L78-L241 to be memoized so it is stable.

### Describe alternate solutions

I could extract all TRPC code into its own component and memoize the callbacks so that this wrapping component is the only thing being rerendered and the child components only get callbacks that are momoized using useEventCallback or similar, this is however both inconvenient and error prone.

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/4773">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/4773/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/4773/pledge.svg">
</picture>
</a>

**Comment by KATT** [comment]
I thought it was stable, this should be the case indeed

**Comment by KATT** [comment]
This feature has been added in the [`next`-branch](https://github.com/trpc/trpc/tree/next) of tRPC, meaning it will be available in v11 of tRPC. 

It's possible to start using it _today_, have a look at the top of the readme of the `next`-branch for more info.
