### ISSUE TITLE
feat: export types for external public client

### ISSUE THREAD

**Issue by yovanoc** [trpc/trpc#4778]
### Describe the feature you'd like to request

I think we could have a way to easily export the app router types like is doing this example

https://github.com/mkosir/trpc-api-boilerplate/

but without the need to clean the generated types after because it's including context, and so, maybe too much information about the server. So, I was thinking it could be in this repo because a lot of use case have separate repos for back and front, and the need to have 'safe' types exposed to clients

### Describe the solution you'd like to see

A clean way to export client types without too much information about the backend.

e.g: just inputs/outputs of procedures to create a client 

### Describe alternate solutions

https://github.com/mkosir/trpc-api-boilerplate/

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/4778">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/4778/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/4778/pledge.svg">
</picture>
</a>

**Comment by sachinraja** [comment]
this is difficult because in some integrations, we need the context on the per-procedure level

**Comment by yovanoc** [comment]
Good to know you see the use case too. But I'm not sure what do you mean by "context on the procedure level". Context is a backend thing no? Why could we have the need to have it in the client?

**Comment by juliusmarminge** [comment]
I think #4709 would help with this, no? With that, we'd have much simpler types for each procedure which could be used for a client to infer from while also omitting the context and whatnot?

**Comment by yovanoc** [comment]
Yeah that's a good start I think

**Comment by KATT** [comment]
#4709 will fix this so the `.d.ts` only includes `input` and `output`, marking as duplicate
