### ISSUE TITLE
bug: bun workspaces - Uncaught (in promise) TRPCClientError: Unexpected end of input at TRPCClientError.from

### ISSUE THREAD

**Issue by jalexw** [trpc/trpc#4809]
### Provide environment information

  System:
    OS: macOS 13.4
    CPU: (8) arm64 Apple M1 Pro
    Memory: 408.00 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 9.6.7 - ~/.npm-global/bin/npm
  Browsers:
    Chrome: 116.0.5845.187
    Safari: 16.5

Bun 1.0.0
@trpc/client: 10.38.2
@trpc/server: 10.38.2
react: 18.2.0
next: 13.4.19
typescript: 5.1.6

### Describe the bug

I'm attempting to use tRPC in a new project using [bun 1.0.0](https://bun.sh/) workspaces... I created a [minimal reproduction of the error](https://github.com/jalexw/trpc-minimal-error) from my private project:
![Screenshot 2023-09-19 at 2 13 37 PM](https://github.com/trpc/trpc/assets/51729845/1f641f22-060e-48ac-b09d-9da8cc1916b7)

tRPC correctly sends a batch request, the server responds to it correctly, but the client appears to throw an uncaught error in parsing the response.

On the client:
```typescript
await trpcContext.client.greeting.query({ name });
```

On the server:
```typescript
export const appRouter = router({
  greeting: publicProcedure
    .input(
      z.object({
        name: z.string(),
      }),
    )
    .query(async (opts) => {
      console.log("Received greeting request");
      return {
        message:  `Greetings ${opts.input.name}, from the tRPC server!`
      }
    }),
});
```

### Link to reproduction

https://github.com/jalexw/trpc-minimal-error

### To reproduce

```bash
git clone https://github.com/jalexw/trpc-minimal-error.git
cd trpc-minimal-error
bun install

# Build types and client for tRPC server into package for frontend Next app
bun run refresh-trpc-client
```

Start the backend tRPC server and the frontend Next app server. Run the next two commands (in 2 separate terminals):

```bash
# Start the tRPC backend dev server on port 8080
bun run dev:server
```

```bash
# Start the Next.js frontend dev server (in a new shell) on port 3000 
bun run dev:web
```

### Additional information

Thoughts?

Stop using Bun and switch back to Yarn? Are my build settings incorrect? CORS issue?

1. As you can see in the earlier screenshot's error log, the response is being received by the client... I'm going to keep investigating this to try to get it working, but I thought that I would make an issue in case anyone else has experienced this...

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/4809">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/4809/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/4809/pledge.svg">
</picture>
</a>

**Comment by KATT** [comment]
This is really strange & I can't figure it out. I tried reproducing it inside a test in tRPC itself:


1. Run your project's server using `bun run dev:server`
2. Test #4814
```bash
git clone git@github.com:trpc/trpc.git && cd trpc && git checkout issues/4809 && pnpm i && pnpm build
pnpm vitest 4809
```

**Comment by KATT** [comment]
Can you help me do a reproduction that works inside a test file? That'd help a lot, otherwise I will work under assumption that it has _something_ to do with the build

**Comment by lucasthevenet** [comment]
I've tried the reproduction example and I think you have CORS set up incorrectly. If I remember correctly, setting the request mode as 'no-cors' doesn't actually solve the CORS problem and makes the response 'opaque' which makes it so tRPC can't read it.

If you remove the 'no-cors' mode on your fetch config and set basic CORS headers like this:

```
/**
 * Configure basic CORS headers
 */

function setCorsHeaders(res: Response) {
  res.headers.set("Access-Control-Allow-Origin", "*");
  res.headers.set("Access-Control-Request-Method", "*");
  res.headers.set("Access-Control-Allow-Methods", "OPTIONS, GET, POST");
  res.headers.set("Access-Control-Allow-Headers", "*");
}

Bun.serve({
  port,
  hostname: '0.0.0.0',
  fetch: async function (req: Request) {
   const response = await fetchRequestHandler({
      endpoint: '/trpc',
      router: appRouter,
      createContext,
      req,
    });
    setCorsHeaders(response);
    return response;
  },
  development: process.env.NODE_ENV === 'development'
})
```

Everything seems to work properly.

**Comment by jalexw** [comment]
Interesting, thanks for teaching me something new!

I didn't realize that the browser did another CORS check post-flight after the response was received; I had assumed CORS was set up fine because I could see the response being received in the Network tab...

I think it would be great if `@trpc/client` caught this error and threw a more informative error message here. For example: `Response from server received, but client failed to open response body. Response may have invalid CORS headers sent from the server?`, or something along those lines? Or is this not possible because the client "cannot see" the response at all when `no-cors` is set on the client?

**Comment by KATT** [comment]
> Interesting, thanks for teaching me something new!
> 
> I didn't realize that the browser did another CORS check post-flight after the response was received; I had assumed CORS was set up fine because I could see the response being received in the Network tab...
> 
> I think it would be great if `@trpc/client` caught this error and threw a more informative error message here. For example: `Response from server received, but client failed to open response body. Response may have invalid CORS headers sent from the server?`, or something along those lines? Or is this not possible because the client "cannot see" the response at all when `no-cors` is set on the client?

Feel free to open a PR to try to catch that!
