### ISSUE TITLE
bug(external): Next.js starter with Prisma, next-auth, WebSockets, and subscriptions does not work out of the box

### ISSUE THREAD

**Issue by baatten** [trpc/trpc#4810]
### Provide environment information

  System:
    OS: macOS 13.5.2
    CPU: (8) x64 Apple M1 Pro
    Memory: 26.74 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.16.0/bin/yarn
    npm: 10.1.0 - ~/.nvm/versions/node/v18.16.0/bin/npm
    pnpm: 8.7.6 - ~/.nvm/versions/node/v18.16.0/bin/pnpm
    Watchman: 2023.08.14.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 117.0.5938.88
    Safari: 16.6
  npmPackages:
    @tanstack/react-query: ^4.18.0 => 4.35.3 
    @trpc/client: ^10.38.3 => 10.38.3 
    @trpc/next: ^10.38.3 => 10.38.3 
    @trpc/react-query: ^10.38.3 => 10.38.3 
    @trpc/server: ^10.38.3 => 10.38.3 
    next: ^13.4.8 => 13.5.1 
    react: ^18.2.0 => 18.2.0 
    typescript: ^5.1.3 => 5.2.2 

### Describe the bug

Socket cannot connect: error in browser: "WebSocket connection to 'ws://localhost:3000/' failed: Could not connect to the server." in dev

and similar error in production but with no port.

### Link to reproduction

http://dev1.uptimus.dk

### To reproduce

install template, run as production with app ws ports set to 3000. 

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/4810">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/4810/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/4810/pledge.svg">
</picture>
</a>

**Comment by baatten** [comment]
It looks like it's not really a trpc issue. but the solution in the template only runs with next 13.4.12 and below. maybe someone can figure out what happen to the solution after?

**Comment by baatten** [comment]
closed by mistake

**Comment by KATT** [comment]
Not likely a bug in tRPC if it works with an older Next.js version

**Comment by baatten** [comment]
Agreed, but perhaps the template needs to be Updated for newer releasens of next?

**Comment by KATT** [comment]
It's broken between minors though, if it was it works in "12.x.y" but broken in "13.0.0" I'd think differently

**Comment by KATT** [comment]
It can probably be reproduced without tRPC altogether

**Comment by avarayr** [comment]
Can probably be resolved by merging https://github.com/trpc/examples-next-prisma-websockets-starter/pull/73/files

**Comment by KATT** [comment]
Oh shit, I don't look at that repo, it gets automatically pushed from the examples folder here.


Cc @dougkulak, could you open the same PR here on the trpc repo?
