### ISSUE TITLE
bug: [fastify adapter] error in nestjs/fastify-adapter FastifyError: Content type parser 'application/json' already present.

### ISSUE THREAD

**Issue by Innei** [trpc/trpc#4820]
### Provide environment information

```
 System:
    OS: macOS 14.0
    CPU: (12) arm64 Apple M2 Max
    Memory: 933.14 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.17.1 - ~/.n/bin/node
    npm: 8.19.4 - ~/.n/bin/npm
    pnpm: 8.7.4 - ~/.n/bin/pnpm
    Watchman: 2023.09.18.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 116.0.5845.187
    Chrome Canary: 119.0.6020.2
    Safari: 17.0
  npmPackages:
    @trpc/server: 10.38.4 => 10.38.4 
```

server side only

### Describe the bug

```ts
 applyMiddleware(app: NestFastifyApplication) {
    app.register(fastifyTRPCPlugin, {
      prefix: '/trpc',
      trpcOptions: { router: this.appRouter, createContext },
    })
  }
```

And I apply fastify plugin, and throw an error.

```


 ERROR  FastifyError: Content type parser 'application/json' already present.                                                                                                        23:38:11
    at ContentTypeParser.add (/Users/innei/git/innei-repo/MetaMuse/node_modules/.pnpm/fastify@4.22.2/node_modules/fastify/lib/contentTypeParser.js:50:11)
    at Object.addContentTypeParser (/Users/innei/git/innei-repo/MetaMuse/node_modules/.pnpm/fastify@4.22.2/node_modules/fastify/lib/contentTypeParser.js:337:30)
    at fastifyTRPCPlugin (/Users/innei/git/innei-repo/MetaMuse/node_modules/.pnpm/@trpc+server@10.38.4/node_modules/@trpc/server/dist/adapters/fastify/index.js:91:13)
    at Plugin.exec (/Users/innei/git/innei-repo/MetaMuse/node_modules/.pnpm/avvio@8.2.1/node_modules/avvio/plugin.js:130:19)
    at Boot.loadPlugin (/Users/innei/git/innei-repo/MetaMuse/node_modules/.pnpm/avvio@8.2.1/node_modules/avvio/plugin.js:272:10)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
```

### Link to reproduction

https://github.com/Innei/trpc-fastify-repro

### To reproduce

This bug is similar https://github.com/nestjs/nest/issues/5607

```
pnpm i
pnpm run dev

```

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/4820">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/4820/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/4820/pledge.svg">
</picture>
</a>

**Comment by KATT** [comment]
Hey there! :wave:

We appreciate the time you've taken to write this issue.


Please make a smaller reproduction or a full file of code that we can copy/paste in order to trigger this error.

**Comment by Innei** [comment]
@KATT Hi,I have simplified the minimal reproduction, please take a look at this reproduce repo again.

**Comment by Innei** [comment]
The key path are `apps/core/src/processors/trpc/trpc.service.ts` and `apps/core/src/bootstrap.ts`

**Comment by Innei** [comment]
The `@nestjs/platform-fastify` is already register json parser.


```js
 registerJsonContentParser(rawBody) {
        const contentType = 'application/json';
        const withRawBody = !!rawBody;
        const { bodyLimit } = this.getInstance().initialConfig;
        this.useBodyParser(contentType, withRawBody, { bodyLimit }, (req, body, done) => {
            const { onProtoPoisoning, onConstructorPoisoning } = this.instance.initialConfig;
            const defaultJsonParser = this.instance.getDefaultJsonParser(onProtoPoisoning || 'error', onConstructorPoisoning || 'error');
            defaultJsonParser(req, body, done);
        });
    }
```

**Comment by KATT** [comment]
Could you reproduce it by creating a fork of tRPC and using the tests we have? https://github.com/trpc/trpc/blob/main/packages/tests/server/adapters/fastify.test.ts

If you do that, we'll fix it straight away

```shell
git clone git@github.com:trpc/trpc.git
cd trpc && pnpm i
pnpm vitest fastify
```

**Comment by Innei** [comment]
It is currently unable to work properly with NestJS. I have provided the minimum reproduction.

**Comment by KATT** [comment]
I don't know Fastify well enough to understand why #4854 changes the behavior. Help @Lilja or @Innei 🙏 

```shell
gh pr checkout 4854
pnpm i
pnpm build
pnpm vitest fastify
```

**Comment by skarab42** [comment]
@KATT @Innei  https://github.com/trpc/trpc/pull/4854#discussion_r1341924898
