### ISSUE TITLE
feat: Enable support for CloudFlare Workers Websockets

### ISSUE THREAD

**Issue by BeBoRE** [trpc/trpc#4822]
### Describe the feature you'd like to request

I would like to be able to use subscriptions when using Cloudflare workers using the Websocket API they provide.
https://developers.cloudflare.com/workers/runtime-apis/websockets/use-websockets/

### Describe the solution you'd like to see

Looking at the documentation Cloudflare provides and the current wssApply implementation, I feel like it would be pretty easy to implement. All that you would need to do is put the connection handler into a seperate function (because you cannot listen for connections with CloudFlare WebSockets), make the handler accept a Cloudflare Websocket client. This would probably require the connection handler to be a little bit more generic, so you can use both ws and the Cloudflare client.

### Describe alternate solutions

I could probably start by ripping out what is already provided by the ws adaptar and place it into my own project to test my theory. I don't know how to develop for a package. I would like to contribute to this issue, but I would probably need a little help to get started.

### Additional information

Because of how simple it seems to implement I feel like I might be wrong on how simple it is. 

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/4822">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/4822/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/4822/pledge.svg">
</picture>
</a>

**Comment by kevinmarrec** [comment]
I'm also looking for such feature.

The only thing I found online and which is more than 1 year old is the following project :
https://github.com/cleaton/cloudflare-trpc-websocket

Sounds really complex.

It would be really awesome to have an `applyWSSHandler` edge-compatible !

**Comment by KATT** [comment]
Feel free to build it as a third-party library, we won't be adding more adapters in tRPC because it's a lot to maintain.

If there are internals you need in tRPC that we don't support, feel free to make PRs to export them
