### ISSUE TITLE
bug: tRPC Error Handling

### ISSUE THREAD

**Issue by ChrisK1982** [trpc/trpc#4874]
### Provide environment information

System:
    OS: macOS 14.0
    CPU: (10) arm64 Apple M2 Pro
    Memory: 939.66 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.7.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 10.1.0 - /opt/homebrew/bin/npm
    pnpm: 8.8.0 - /opt/homebrew/bin/pnpm
  Browsers:
    Chrome: 117.0.5938.132
    Edge: 111.0.1661.44
    Safari: 17.0
  npmPackages:
    @trpc/server: 10.26.0 => 10.26.0
    typescript: ~4.9.4 => 4.9.5

### Describe the bug

According to the tRPC error handling documentation: https://trpc.io/docs/server/error-handling , when throwing a TRPCError from a procedure, the result is the original TRPCError thrown. However, when I use this inside of an AWS API Gateway endpoint handler, the resulting error code defaults to `INTERNAL_SERVER_ERROR` instead of the original code set.

### Link to reproduction

https://stackblitz.com/edit/github-zn9wg8?file=package.json,src%2Fpages%2Fapi%2Ftrpc%2F[trpc].ts

### To reproduce

1. Create a configurable tRPC router
2. Use the exported router to create a new router with configured routes pointing to procedures
3. Inside of the procedure, throw a TRPCError and set the code to something other than `INTERNAL_SERVER_ERROR`
4. Deploy the handler as an AWS API Gateway endpoint handler
5. Call the endpoint and observe that the code is defaulted to `INTERNAL_SERVER_ERROR`

### Additional information

In the link above I am sharing a link to the nextjs example code that seems to work as expected. I am not sure how to replicate these conditions without an AWS Stack running in some local environment. Please advise and/or ask followup questions as needed.

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/4874">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/4874/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/4874/pledge.svg">
</picture>
</a>

**Comment by KATT** [comment]
Upgrade to latest version of tRPC and reopen if it persists. We've fixed this already.

**Comment by ChrisK1982** [comment]
Thank you for the reply. Once updated to the latest release `10.38.5` the issue is resolved.
