### ISSUE TITLE
bug: Trpc requests much slower. Need help troubleshooting

### ISSUE THREAD

**Issue by nnennajohn** [trpc/trpc#4897]
### Provide environment information

```
  System:
    OS: macOS 13.5.2
    CPU: (10) arm64 Apple M1 Max
    Memory: 413.66 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.17.1 - ~/.nvm/versions/node/v18.17.1/bin/node
    npm: 9.6.7 - ~/.nvm/versions/node/v18.17.1/bin/npm
    pnpm: 8.7.0 - ~/Library/pnpm/pnpm
    Watchman: 2023.05.22.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 117.0.5938.149
    Safari: 16.6
  npmPackages:
    @tanstack/react-query: ^4.36.1 => 4.36.1 
    @trpc/client: ^10.40.0 => 10.40.0 
    @trpc/next: ^10.40.0 => 10.40.0 
    @trpc/react-query: ^10.40.0 => 10.40.0 
    @trpc/server: ^10.40.0 => 10.40.0 
    next: latest => 13.5.4 
    react: latest => 18.2.0 
    typescript: latest => 5.2.2 
```

### Describe the bug

My requests are much slower than expected. Even when using the new `createTRPCNextAppDirServer`.

My setup uses prisma accelerate. On average, most requests with prismaClient edge takes 2- 10ms. But the trpc call always takes over 1000ms. I could use prisma directly in place of the new createTRPCNextAppDirServer, but I am trying to maintain feature parity with both web and mobile(expo).

All run locally.

Not sure if others have encountered this, so thought I'd share here to see if I am missing something.

I've attached my serverComponent setup. And a screenshot of the actual call timing, both from prisma and trpc.

Please let me know if something in my setup is causing the huge gap in response timing.

Thank you.

ServerComponent setup
<img width="1052" alt="Screenshot 2023-10-08 at 4 45 05 AM" src="https://github.com/trpc/trpc/assets/1761197/c5c33d6a-fa30-473d-acdb-b5e6d9ee70af">

Called in layout.tsx
<img width="753" alt="Screenshot 2023-10-08 at 4 40 08 AM" src="https://github.com/trpc/trpc/assets/1761197/2e2e144a-c881-448c-b9fc-361331c56d2b">

Actual router implementation:
(Note): ctx just decodes userToken from cookies and passes along the userId
<img width="767" alt="Screenshot 2023-10-08 at 4 40 24 AM" src="https://github.com/trpc/trpc/assets/1761197/2e134471-bd7d-43f0-9cd5-df68ec33d65b">

Request timing:
(Note): Params and duration are from prisma. "Ok Request timing" is from trpc.
<img width="564" alt="Screenshot 2023-10-08 at 4 45 51 AM" src="https://github.com/trpc/trpc/assets/1761197/6daa9680-17c9-4c52-87b4-03a6b3596de8">

### Link to reproduction

https://stackblitz.com/github/trpc/examples-next-minimal-starter?file=README.md

### To reproduce

Create a starter nextjs project with app router. Setup prisma and use prisma in trpc router. Enable query event logging in prisma and enable logging middleware in trpc. Now setup trpc with server component, and compare the response timing in the logs.

This is probably a bit more involved. But I'll make this report for now and come back with a proper repro.

### Additional information

Did not test with client trpc as it was already slower than I liked, hence the attempt to use server components. I use it across other aspects of the app and can update here with another comparison.

Thank you.

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/4897">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/4897/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/4897/pledge.svg">
</picture>
</a>

**Comment by KATT** [comment]
Hey there! :wave:

We appreciate the time you've taken to write this issue.

Unfortunately, we don't have the bandwidth to assist with issues without a reproduction repository and this issue does not seem to be related to tRPC itself. 

Please feel free to re-open with a solid reproduction repository where we can help you further or post in our help channels on [Discord](https://trpc.io/discord) or in our [GitHub Discussions](https://github.com/trpc/trpc/discussions).
