### ISSUE TITLE
feat: Middleware specific input and/or merging middleware and procedure inputs

### ISSUE THREAD

**Issue by ahkhanjani** [trpc/trpc#4947]
### Describe the feature you'd like to request

I'm trying to abstract a logic in some of my routes. From my research I figured out that the regular middleware doesn't have a proper input support. Most of the previously asked related discussions are pointing towards the `experimental_standaloneMiddleware`. The idea is great but there seems to be a flaw in the implementation as of now. Please correct me if I'm wrong.

The type we provide for the generic `T` in `experimental_standaloneMiddleware<T>` has to match that of `.input()`'s. So if we have different routes with different inputs -that have a shared set of params for the middleware- it won't work.

### Describe the solution you'd like to see

What I had expected was to at least have a partial validation or merging of the two types for only the shared part of the inputs between the middleware and the procedure.

In other words: The `.input()` type must include the middleware params, but it can include other items as well.

### Describe alternate solutions

```ts
const schemaA = z.object({ valueA: z.string() });

const setQuizAnswerMiddleware = experimental_standaloneMiddleware(schemaA).create((opts) => {
  // The type-safe input
  const { input } = opts;

  // Create a new context value from the input...

  return opts.next({ ctx: { ... } });
});

const schemaB = z.object({ valueB: z.string() });

publicProcedure.input(schemaB).use(setQuizAnswerMiddleware)
            // Merged inputs
  .query(({ input: { valueA, valueB }, ctx: { ... } }): => ('Hello world');
```

### Additional information

There could also be an "isolated middleware" that takes it's own input, but doesn't expose them to the procedure. Its job is only to do some internal computation and add some values to the `ctx` object.

### 👨‍👧‍👦 Contributing

- [x] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/4947">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/4947/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/4947/pledge.svg">
</picture>
</a>

**Comment by jussisaurio** [comment]
There indeed seems to be an error in the way `input` is propagated forward when using multiple standalone middlewares -- i.e. they are not merged properly. I'll try to look into it

**Comment by jussisaurio** [comment]
To clarify @ahkhanjani , is this something along the lines of what you want?

```
test('standalone middlewares -- inputs are merged properly when using multiple standalone middlewares', () => {
  const t = initTRPC.create();
  const schemaA = z.object({ valueA: z.string() });
  const schemaB = z.object({ valueB: z.string() });

  const valueAUppercaserMiddleware = experimental_standaloneMiddleware<{
    input: z.infer<typeof schemaA>;
  }>().create((opts) => {
    // The type-safe input
    const { input } = opts; // { valueA: string }

    // Create a new context value from the input...

    return opts.next({
      ctx: { valueAUppercase: input.valueA.toUpperCase() },
    });
  });

  const setQuizAnswerMiddleware = experimental_standaloneMiddleware<{
    input: z.infer<typeof schemaB>;
  }>().create((opts) => {
    return opts.next({
      ctx: { quizAnswer: opts.input.valueB },
    });
  });

  const schemasMerge = schemaA.merge(schemaB);

  t.procedure
    .input(schemasMerge)
    .use(valueAUppercaserMiddleware)
    .use(setQuizAnswerMiddleware)
    .query(
      ({ input: { valueA, valueB }, ctx: { valueAUppercase, quizAnswer } }) =>
        `valueA: ${valueA}, valueB: ${valueB}, valueAUppercase: ${valueAUppercase}, quizAnswer: ${quizAnswer}`,
    );
});
```

**Comment by ahkhanjani** [comment]
> To clarify @ahkhanjani , is this something along the lines of what you want?

In your example, this is not clear to me: Can the schema in `.input()` have properties that neither `valueAUppercaserMiddleware` nor `setQuizAnswerMiddleware` have?

**Comment by jussisaurio** [comment]
> > To clarify @ahkhanjani , is this something along the lines of what you want?
> 
> @jussisaurio In your example, this is not clear to me: Can the schema in `.input()` have properties that neither `valueAUppercaserMiddleware` nor `setQuizAnswerMiddleware` have?

Sorry, the example could've been better. Check out this test from the linked PR:

https://github.com/trpc/trpc/pull/4948/files#diff-19910652d286a53e922d11f765ab3da381f9555ecf978b929ae5507ea1cc5650R28

**Comment by ahkhanjani** [comment]
Can we have something like this: `experimental_standaloneMiddleware().input(z.object({ ... })).create()`?

If you see the idea fitting, I'll gladly help implementing it.

**Comment by ahkhanjani** [comment]
> Sorry, the example could've been better. Check out this test from the linked PR:
> 
> [#4948 (files)](https://github.com/trpc/trpc/pull/4948/files#diff-19910652d286a53e922d11f765ab3da381f9555ecf978b929ae5507ea1cc5650R28)

Yes that seems to be exactly what I was looking for. So it was a bug and not a design decision? If that's the case we can close this issue. Thanks for your help.

Should I open another issue/discussion for the other features I requested or are they a no no for this project?

**Comment by ahkhanjani** [comment]
> #4948 (files)

I think we should add this example to the docs.

**Comment by jussisaurio** [comment]
> Can we have something like this: `experimental_standaloneMiddleware().input(z.object({ ... })).create()`?
> 
> If you see the idea fitting, I'll gladly help implementing it.

The current API has bad DX simply because it was the _only way_ I could figure out how to make it work with tRPC's existing internal types. Having partial type parameter inference in TypeScript would help a lot. I'm sure there's a way to make your suggestion work, but it's certainly not easy, at least for me

**Comment by ahkhanjani** [comment]
> The current API has bad DX simply because it was the _only way_ I could figure out how to make it work with tRPC's existing internal types. Having partial type parameter inference in TypeScript would help a lot. I'm sure there's a way to make your suggestion work, but it's certainly not easy, at least for me

I see. I will look into it and let you know if I can figure a way out. I'm totally unfamiliar with the tRPC source code so I may need to ask some questions later on Discord.



> There could also be an "isolated middleware" that takes it's own input, but doesn't expose them to the procedure. Its job is only to do some internal computation and add some values to the `ctx` object.

How about this by the way? Is this related to the same DX problem? Do you think we can have that?

**Comment by jussisaurio** [comment]
> How about this by the way? Is this related to the same DX problem? Do you think we can have that?

Can you give an example use case with pseudocode?

**Comment by ahkhanjani** [comment]
> Can you give an example use case with pseudocode?

Something like this:

```ts
const nameSchema= z.object({ firstName: z.string(), lastName: z.string() });

const computeFullName = arbitrary_isolatedMiddleware().input(nameSchema).create((opts) => {
  const { firstName, lastName } = opts;
  const fullName = firstName + ' ' + lastName;
  return opts.next({ ctx: { fullName } });
});

const otherSchema = z.object({ greetingValue: z.enum(['Hello', 'Goodbye']) });

publicProcedure.input(otherSchema).use(computeFullName)
  // The `input` object doesn't include `firstName` or `lastName`.
  .query(({ input: { greetingValue }, ctx: { fullName } }): => (`${greetingValue} ${fullName}`);
```

The React code (with TanStack Query):

```ts
									// Here, we require all values.
const { data } = api.(...).useQuery({ greetingValue: 'Hello', firstName: 'A', lastName: 'B' })
```

**Comment by ahkhanjani** [comment]
@juliusmarminge Hi. what do you think about this?
