### ISSUE TITLE
feat: trpc/react-query for react-query 5 and next 14

### ISSUE THREAD

**Issue by doneumark** [trpc/trpc#4970]
### Describe the feature you'd like to request

Two major release have been made recently:

- @tanstack/react-query@5
- nextjs@14

I'm wondering what's the most suitable way to enjoy this days, trpc with the latest majors in both packages.
As today they dependencies just doens't sync up.

### Describe the solution you'd like to see

An next.js 14 app, working with trpc 5, fetching with trpc/react-query.

### Describe alternate solutions

Keep using nextjs 13, or react-query 4.

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/4970">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/4970/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/4970/pledge.svg">
</picture>
</a>

**Comment by KATT** [comment]
- #4218
- https://trpc.io/docs/faq#does-trpc-work-with-nextjs-13-app-layouts--rsc / #3297
