### ISSUE TITLE
bug: experimental_standaloneMiddleware input merge is incorrect on the frontend

### ISSUE THREAD

**Issue by ahkhanjani** [trpc/trpc#4972]
### Provide environment information

System:
OS: Windows 10 10.0.22621
CPU: (8) x64 Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
Memory: 10.22 GB / 19.84 GB
Binaries:
Node: 20.9.0 - C:\Program Files\nodejs\node.EXE
Yarn: 3.5.0 - C:\Program Files\nodejs\yarn.CMD
npm: 10.2.1 - C:\Program Files\nodejs\npm.CMD
pnpm: 8.10.0 - C:\Program Files\nodejs\pnpm.CMD
Browsers:
Edge: Chromium (118.0.2088.69)
Internet Explorer: 11.0.22621.1
npmPackages:
@tanstack/react-query: ^4.36.1 => 4.36.1
@trpc/client: ^10.43.0 => 10.43.0
@trpc/next: ^10.43.0 => 10.43.0
@trpc/react-query: ^10.43.0 => 10.43.0
@trpc/server: ^10.43.0 => 10.43.0
next: ^13.5.6 => 13.5.6
react: ^18.2.0 => 18.2.0
typescript: ^5.2.2 => 5.2.2

### Describe the bug

The bug mentioned in #4947 has fixed the input merge problem on the backend procedure `input`. But in the react query mutation on the frontend, the input type only shows the inputs needed for the middleware, and ignores the one provided in the `input()` call. Example:

Backend:
```ts
const mwSchema= z.object({ a: z.string() })
const mw = experimental_standaloneMiddleware<{ input: z.infer<typeof mwSchema> }>().create(...)

createTRPCRouter({
	create: publicProcedure.input(z.object({ b: z.string() }).merge(mwSchema)).use(mw).mutation(...)
})
```

Frontend:
```ts
const { mutate: create } = api.create.useMutation()

create({ a: "str",  b: "str" })
			// errors for `b`
```

@jussisaurio would you please have a look.

### Link to reproduction

-

### To reproduce

-

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/4972">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/4972/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/4972/pledge.svg">
</picture>
</a>

**Comment by jussisaurio** [comment]
I'll look at this when I have time, but in the meantime could you post a minimal reproduction repository?

**Comment by jussisaurio** [comment]
Actually probably no need for a repro repository, I just need to find the time to fix this
