### ISSUE TITLE
feat: Use query helpers outside of Context

### ISSUE THREAD

**Issue by sachinahya** [trpc/trpc#4974]
### Describe the feature you'd like to request

Like `useUtils` but can be accessed from outside of React context. Basically [this context value](https://github.com/trpc/trpc/blob/a98dc662d6ade1bcfdae09a274d508c9dc347235/packages/react-query/src/shared/hooks/createHooksInternal.tsx#L79) to be made available from a function that is called with a `client` and `queryClient`.

This would help us do prefetching of data at the router level, where context is not accessible. Having the full set of query utils would also be useful at this level for actions where we might want to perform cache invalidation after a mutation.

It's a [recommended pattern in the TanStack Query docs](https://tanstack.com/query/latest/docs/react/guides/prefetching#router-integration) for implementing prefetching and enabling fetch-as-you-render patterns with the now stable Suspense support.

### Describe the solution you'd like to see

A function that creates the same object as `useUtils`. It would take in the `client` and `queryClient` as parameters.

```ts
import { createQueryUtils } from '@trpc/react-query';

const utils = createQueryUtils({ client, queryClient });
await utils.post.all.prefetch();
```

Example usage in a React Router loader, a function which executes before React rendering and has no access to Context or hooks.

```tsx
import { createQueryUtils } from '@trpc/react-query';

const routes = [{
  path: ':postId',
  element: <Post />,
  loader: ({ params }) => {
    // Assume we have a way of getting the client instances into here depending on server/client.
    const utils = createQueryUtils({ client, queryClient });
    
    // Don't navigate until main content is ready.
    await utils.post.byId.prefetch(params.postId);

    // Start fetching comments early but don't block navigation.
    void utils.post.comments.prefetch(params.postId);
  },
}];
```

### Describe alternate solutions

`createServerSideHelpers` only works on the server, meaning we could only do this kind of prefetching for the initial SSR load. We can't perform prefetching or implement these same fetching patterns on the client.

It's more useful to have this at the router level so we can have the same prefetching logic working seamlessly on both server and client.

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/4974">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/4974/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/4974/pledge.svg">
</picture>
</a>

**Comment by KATT** [comment]
This feature has been added in the [`next`-branch](https://github.com/trpc/trpc/tree/next) of tRPC, meaning it will be available in v11 of tRPC. 

It's possible to start using it _today_, have a look at the top of the readme of the `next`-branch for more info.
