### ISSUE TITLE
feat: Upgrade @tanstack/react-query from "4.18.0" to "^5.4.3"

### ISSUE THREAD

**Issue by ben-ikt** [trpc/trpc#4988]
### Describe the feature you'd like to request

Please use the last major version of @tanstack/react-query

### Describe the solution you'd like to see

install @tanstack/react-query@^5.4.3

### Describe alternate solutions

No alternate solution

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/4988">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/4988/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/4988/pledge.svg">
</picture>
</a>

**Comment by juliusmarminge** [comment]
https://github.com/trpc/trpc/issues/4218
