### ISSUE TITLE
bug: Too long input causes failure HTTP 431 

### ISSUE THREAD

**Issue by ottovw** [trpc/trpc#4993]
### Provide environment information

```
 System:
    OS: Linux 5.15 Ubuntu 20.04.4 LTS (Focal Fossa)
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 12.16 GB / 15.55 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
  npmPackages:
    @tanstack/react-query: ^4.36.1 => 4.36.1
    @trpc/client: ^10.42.0 => 10.42.0
    @trpc/react-query: ^10.42.0 => 10.42.0
    @trpc/server: ^10.42.0 => 10.42.0
    next: 13.4.19 => 13.4.19
    react: 18.2.0 => 18.2.0
    typescript: 5.1.6 => 5.1.6
```

### Describe the bug

When using a query and encoded input is too long, the request fails with HTTP 431

Usecase: Complex search query with multiple filters

### Link to reproduction

http://example.com/not-necessary

### To reproduce

Use `useQuery` with an input that is longer than ~2000 characters (take 5000 to be sure)

### Additional information

There are discussions about a solution, in terms of a feature. 
- https://github.com/trpc/trpc/discussions/1936#discussioncomment-2818346
- https://github.com/trpc/trpc/issues/1939

This should be considered a bug and a solution should be expedited.

Either this should be solved
or defined as a limitation in the docs: 
- could include a log warning
- an entry in the troubleshooting section

That being said, is there are workaround for the current version?

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/4993">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/4993/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/4993/pledge.svg">
</picture>
</a>

**Comment by KATT** [comment]
Not a bug, not sure why you need a query of thousands of characters, feel free to sponsor or implement the features you references

**Comment by ottovw** [comment]
First of all thanks for the work you're doing with the lib, @KATT. I'd also be happy to help to resolve this, probably your procedure overwrite is the best solution.

FYI: Here's the usecase for a complex query (imagine amazon product search). Semantically it's a query, not a mutation.
The following example is ~400 chars (json.stringify, urlencoded). It's easy imagineable to have more filter. filter combinations (and/or)

```
{
    query: 'laptop for open source development',
    filters: {
        brands: ['Apple', 'Lenovo'],
        memory: [ '16gb', '32gb', '64gb'],
        cpu: ['intel xy'],
    },
    sort:  [{key: 'cpu', order: 'asc'}, {key: 'memory', order: 'asc'}],
    page: 1
}
```
