### ISSUE TITLE
docs: react-query v5 gets installed when following the react-query setup tutorial 

### ISSUE THREAD

**Issue by spirobel** [trpc/trpc#5006]
### Area of Improvement

https://trpc.io/docs/client/react/setup
react-query v5 gets installed when following the react-query setup tutorial and copying the command from the docs:
``` bash
bun add @trpc/client @trpc/server @trpc/react-query @tanstack/react-query
```

I personally fixed it for me by installing the @next versions. But another possible solution would be to use the v4 of react-query.
``` bash
bun add @trpc/client@next @trpc/server@next @trpc/react-query@next
```

which fix do you prefer?

### Link to related docs

https://trpc.io/docs/client/react/setup

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR implementing the suggested changes!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/5006">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/5006/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/5006/pledge.svg">
</picture>
</a>

**Comment by KATT** [comment]
Yeah we should update the installation instructions to be `^4.0.0`-range of the RQ deps until v11 is out
