### ISSUE TITLE
feat: error handling on server side

### ISSUE THREAD

**Issue by romeerez** [trpc/trpc#5010]
### Describe the feature you'd like to request

[handling errors](https://trpc.io/docs/server/error-handling#handling-errors) docs sections show how to intercept errors in Next.js only. It seems like it's not implemented in other adapters, I looked specifically into fastify-related code and example - no error handling.

### Describe the solution you'd like to see

There must be a way to handle errors in all trpc adapters.

I'd like to log errors in a way I can see a stack trace when developing.

In case of a known error that can be shared with a user, for example, record is not found, the error handler could send an appropriate error message.

And in case of an unexpected error, due to a bug in the code, such an error won't be shared with the user, only logged.

### Describe alternate solutions

Instead of handling errors in one place, we can handle them in each route individually, but it does not have to be in this way.

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/5010">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/5010/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/5010/pledge.svg">
</picture>
</a>

**Comment by KATT** [comment]
You can do this with [a middleware](https://trpc.io/docs/server/middlewares#logging) or using the [`onError`-callback](https://trpc.io/docs/server/error-handling#handling-errors) in the adapter (I think all should have it the same way)

**Comment by romeerez** [comment]
I found what I was looking for in [Error Formatting](https://trpc.io/docs/server/error-formatting).
