### ISSUE TITLE
bug: Date type suddenly mangles to string

### ISSUE THREAD

**Issue by dvv** [trpc/trpc#5018]
### Provide environment information

```
  System:
    OS: Linux 6.1 Arch Linux
    CPU: (6) x64 AMD Ryzen 5 4500U with Radeon Graphics
    Memory: 5.11 GB / 14.99 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 20.9.0 - /usr/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 10.2.1 - /usr/bin/npm
  Browsers:
    Chromium: 118.0.5993.117
```

### Describe the bug

It seems the output type of a procedure is wrongly inferred or mangled. I wonder if it is bug or feature or whatever I may be doing wrong?

### Link to reproduction

https://typescript-ovwrdt.stackblitz.io

### To reproduce

Open the link above. Hover the mouse upon `.query` in line 46 `rpc.Foo.query({})` to see the inferred type. Notice the x' type mangled.

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/5018">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/5018/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/5018/pledge.svg">
</picture>
</a>

**Comment by KATT** [comment]
Well, since it's sent as JSON, to the client it will become a string. See #5012

Also, that repro link  doesn't work

**Comment by dvv** [comment]
```ts
import type {
  CreateRouterInner,
  DefaultErrorShape,
  DefaultDataTransformer,
  Procedure,
  RootConfig,
} from '@trpc/server';
type ProtocolTrpcRouter = CreateRouterInner<
  RootConfig<{
    ctx: object;
    meta: object;
    errorShape: DefaultErrorShape;
    transformer: DefaultDataTransformer;
  }>,
  {
    Foo: Procedure<
      'query',
      {
        _config: RootConfig<{
          ctx: object;
          meta: object;
          errorShape: DefaultErrorShape;
          transformer: DefaultDataTransformer;
        }>;
        _meta: object;
        _ctx_out: object;
        _input_in: { a: Date };
        _input_out: { a: Date };
        _output_in: { x: Date };
        _output_out: { x: Date }; // notice x' type is Date
        // (property) _output_out: {
        //   x: Date;
        // }
      }
    >;
  }
>;

import { createTRPCProxyClient, httpBatchLink } from '@trpc/client';
export const rpc = createTRPCProxyClient<ProtocolTrpcRouter>({
  links: [
    httpBatchLink({
      url: `http://127.0.0.1:8080/trpc`,
    }),
  ],
});

console.log(
  rpc.Foo.query({ a: new Date() }) // the type is below, notice x' Date became string
  // (property) query: (input: {
  //     a: Date;
  // }, opts?: ProcedureOptions | undefined) => Promise<{
  //     x: string;
  // }>
);
```

**Comment by KATT** [comment]
See https://github.com/trpc/trpc/discussions/5012#discussioncomment-7512490

**Comment by dvv** [comment]
In the above nothing is really placed on the wire. Still it infers mangled type. I believe this may be a bug in type system, hence the report.

**Comment by dvv** [comment]
Interesting that replacing `DefaultDataTransformer` with `typeof transformer` where `const transformer = {}` does solve the typing issue.

**Comment by KATT** [comment]
You're using the `@trpc/client` which will use JSON for its transport, hence it is inferred as a `string`.

When using [`.createCaller()`](https://trpc.io/docs/server/server-side-calls) server-side the types won't be changed 
When using [a transformer](https://trpc.io/docs/server/data-transformers), the types won't be changed

**Comment by dvv** [comment]
Thank you!
