### ISSUE TITLE
feat: Make trpc.useUtils() a first-class citizen

### ISSUE THREAD

**Issue by dcramer** [trpc/trpc#5025]
### Describe the feature you'd like to request

There are many situations where you simply need access to a raw trpc client (akin to where you'd just want to operate with fetch on a traditional API). With the changes from V-1 to V-Current the focus for React integration has been either Next (which I dont use), or React-Query (which I do, but cant universally apply).

### Describe the solution you'd like to see

I think it'd be good to elevate, at least in the docs (but maybe with API naming) the useUtils functionality, and ideally uniformly name things.

For example, exposing a trpc.useClient() (vs useUtils), and exposing .query and .mutation on it.

e.g. I need something like this:

```
     const utils = trpc.useUtils();

     # ...
      onQuery={async (query) => {
        const { results } = await utils.entityList.fetch({ query });
        return results;
      }}
```

But as a novice tRPC user, I have no idea why I'm calling .fetch() here, and .query() elsewhere. It also wasnt obvious to me that useUtils would just translate to a tRPC client instance.

### Describe alternate solutions

.

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/5025">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/5025/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/5025/pledge.svg">
</picture>
</a>

**Comment by dcramer** [comment]
Too dumb to understand tRPC source code or I'd toss up a PR :)

**Comment by juliusmarminge** [comment]
what are you asking for here that isn't covered by

```tsx
const { client } = trpc.useUtils();

const entityList = client.entityList.query();
// or
useQuery({
  queryKey: ["somekey"],
  queryFn: () => {
    // do something i guess?
    const entityList = await client.entityList.query();
    // do something else maybe?
    return something;
  },
});
```

**Comment by dcramer** [comment]
> what are you asking for here that isn't covered by
> 
> ```tsx
> const { client } = trpc.useUtils();
> 
> const entityList = client.entityList.query();
> // or
> useQuery({
>   queryKey: ["somekey"],
>   queryFn: () => {
>     // do something i guess?
>     const entityList = await client.entityList.query();
>     // do something else maybe?
>     return something;
>   },
> });
> ```

Two fold:

1) documentation side I think it could be more obvious that this exists since it’s a common need

2) there’s dx issues where APIs are named slightly differently throughout (fetch vs query as an example)

It’d be a lot more obvious if you could just:

```
const client = trpc.useClient();
await client.rpcName.query(); // or .mutate()
```

As a developer I’m not trying to learn the internals of a library I use so trying to understand why operations are hidden or renamed just decreases productivity.

**Comment by juliusmarminge** [comment]
> documentation side I think it could be more obvious that this exists since it’s a common need

https://trpc.io/docs/client/react/useUtils#proxy-client

**Comment by dcramer** [comment]
> > documentation side I think it could be more obvious that this exists since it’s a common need
> 
> https://trpc.io/docs/client/react/useUtils#proxy-client
> 
> > It’d be a lot more obvious if you could just:
> > ```
> > const client = trpc.useClient();
> > ```
> 
> You could make your own wrapper:
> 
> ```ts
> export const useTRPCClient = () => trpc.useUtils().client;
> 
> // ...
> 
> const client = useTRPCCLient();
> client.foo.mutate()
> ```

Take me feedback however you want but the issue isn’t “can I do it, technically”. It’s that as a new user of trpc I didn’t even know to look at “useUtils” because it’s not obvious how that would have related to what I was trying to do.

**Comment by juliusmarminge** [comment]
> Take me feedback however you want but the issue isn’t “can I do it, technically”. It’s that as a new user of trpc I didn’t even know to look at “useUtils” because it’s not obvious how that would have related to what I was trying to do.

Fair, but you also gotta consider the user experience of the majority use case and we don't want to "litter" the autocompletion more than necessary. There is already quite a lot of stuff exposed when you type `trpc.` and hit tab, and it's a thin line if adding more is better or worse.

**Comment by dcramer** [comment]
I think that’s fine - like I said it could just be a docs issue there. I still think the different terms for making queries is confusing as a new adopter and I just blindly do whatever seems rational.

**Comment by juliusmarminge** [comment]
Come to think of it, I think it might have been "more obvious" with the previous naming `trpc.useContext()` which was renamed to `useUtils` cause most stuff in there is related to utilities around the query client - so maybe the actual client should be pulled out to it's own hook now? What do you think @Nick-Lucas given that you were the one pushing for the rename

**Comment by Nick-Lucas** [comment]
useUtils is a bag of escape hatches & helpers, and documented pretty prominently on the site. 

What you want to do here is access an escape hatch and do something that in _most cases_ is inadvisable when working with react-query, so making it a first-class citizen isn't really in-scope. 

Plus the argument of not having seen the escape hatch because you didn't read the docs fully isn't going to cease being a problem just because we moved it around a little - new users would still have to read the docs and discover this feature. End of the day tRPC is a pretty high level set of abstractions, and so understanding the things we're abstracting is quite important to get the most out of it.

I think we have to be quite direct here and say we're not going to do this, but feel free to come join us on Discord for advice and guidance, as we're very happy to help people learn more about tRPC 🙂

**Comment by dcramer** [comment]
> useUtils is a bag of escape hatches & helpers, and documented pretty prominently on the site.
> 
> What you want to do here is access an escape hatch and do something that in _most cases_ is inadvisable when working with react-query, so making it a first-class citizen isn't really in-scope.

react-query is your approach to supporting React though (at least seemingly via the deprecation path), and it doesnt work with every use case even in standard React code. I had actually gone down the rabbit hole of building my own context provider, and figured I'd dig to see if there was some way to use the existing react (guised as react-query, which imo is part of the problem) context provider instead. React isn't just react-query and Next.js after all. Most importantly, I'm using Remix and there's _no reason_ for a Remix specific integration when all the components needed are (nearly) first-class citizens in the existing support.

Anyways feel free to close the ticket. I usually have a pretty good eye for DX, and if I have to go read "all of the docs" to use something that to me is an opportunity for improvement.
