### ISSUE TITLE
feat: createWSClient lazy mode

### ISSUE THREAD

**Issue by ItzDerock** [trpc/trpc#5028]
### Describe the feature you'd like to request

I am using `wsLink` inside of a `splitLink` and would like a way to only open a WS connection if it's needed since only a small portion of my site needs the live feed.

It looks like #2765 implemented this, but from what I can tell, it was never merged. If there's a reason behind this, please let me know as I was unable to find any additional information.

### Describe the solution you'd like to see

an option in `createWSClient` that, when toggled, will only open a WS connection when required and will close the connection after a certain idle time.

### Describe alternate solutions

I'm unaware of any workarounds for this except recreating your the createWSClient function, which is tricky because the current implementation uses imports from files that are not exported. This makes it so that I would have to fork trpc and edit the source and package my own version, or copy-paste a bunch of internal code, or reimplement everything from scratch.

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/5028">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/5028/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/5028/pledge.svg">
</picture>
</a>

**Comment by KATT** [comment]
Feel free to rewrite the wsLink with breaking changes if you target the `next` branch
