### ISSUE TITLE
bug: types are [x: string]: uknown and [x:number]: unknown

### ISSUE THREAD

**Issue by omridevk** [trpc/trpc#5034]
### Provide environment information

I am using trpc and creating a schema like this:

my schema (I am using Ajv):
```
export const userSchema = {
  type: 'object',
  properties: {
    id: {type: 'string', format: 'uuid'},
    first_name: {type: 'string', minLength: 1},
    middle_name: {type: 'string', nullable: true, minLength: 1},
    last_name: {type: 'string', minLength: 1},
    phone: {type: 'string', minLength: 1},
    email: {type: 'string', format: 'email'},
    status: {type: 'string', enum: ['ACTIVE', 'INACTIVE', 'FROZEN']},
    created_at: {type: 'string', format: 'date-time'},
    updated_at: {type: 'string', format: 'date-time'},
    deleted_at: {type: 'string', format: 'date-time', nullable: true},
    role_group: {type: 'string', enum: Object.values(UserRoleGroups)},
    tenant_id: {type: 'integer'},
  },
  minProperties: 1,
  required: ['id'],
} as const
```

When I add `additionalProperties: false` the issue is solved, but this is not what I want. 

This is what I am getting in the build output, however, when I develop, in webstorm it shows that the types are of:
<img width="723" alt="CleanShot 2023-11-13 at 15 47 15@2x" src="https://github.com/trpc/trpc/assets/9701896/dc2f1635-abfe-4f34-8448-449d52f201b0">

```
 _output_in: {
                [x: string]: unknown;
                status?: "ACTIVE" | "INACTIVE" | "FROZEN" | undefined;
                email?: string | undefined;
                phone?: string | undefined;
                tenant_id?: number | undefined;
                role_group?: import("users-types").UserRoleGroups | undefined;
                created_at?: string | undefined;
                updated_at?: string | undefined;
                deleted_at?: string | null | undefined;
                first_name?: string | undefined;
                middle_name?: string | null | undefined;
                last_name?: string | undefined;
                guarantor_id?: string | undefined;
                is_guarantor?: boolean | undefined;
                id: string;
            }[];

```

I am trying to create a reproduction case but this is a closed source and I need to replicate the way we wrap Ajv.

### Describe the bug

Types incorrectness when using Ajv

### Link to reproduction

https://stackblitz.com/edit/trpc-trpc-wjwcuz?file=src%2Fpages%2Fapi%2Ftrpc%2F%5Btrpc%5D.ts,src%2Fpages%2Findex.tsx,package.json

### To reproduce

I wasn't able to reproduce it in the stackblitz using Zod catchall but still I see the right types in the output I posted. 

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/5034">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/5034/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/5034/pledge.svg">
</picture>
</a>

**Comment by omridevk** [comment]
Here is a stackblitz with issue:
https://stackblitz.com/edit/trpc-trpc-wjwcuz?file=src%2Fpages%2Fapi%2Ftrpc%2F%5Btrpc%5D.ts,src%2Fpages%2Findex.tsx,package.json


Downgrading to all trpc versions to -> 10.9.0 resolves the issue.

Seems like a regression.

**Comment by omridevk** [comment]
I suspect this is related to this:
https://github.com/trpc/trpc/pull/3789/files

Haven't verified, but was able to verify that this breaking changed occurred between version 10.11.0 -> 10.12.0 (as in working in 10.11.0 and stopped working in 10.12.0 until now)

**Comment by omridevk** [comment]
Thanks for a great library guys!

**Comment by jussisaurio** [comment]
> I suspect this is related to this: https://github.com/trpc/trpc/pull/3762/files
> 
> Haven't verified, but was able to verify that this breaking changed occurred between version 10.11.0 -> 10.11.1 (as in working in 10.11.0 and stopped working in 10.11.1 until now)

It's a bit strange that this change would make the difference, because to me it looks like it's ´UndefinedToOptional` that messes up this type. I'll try to take a look

**Comment by jussisaurio** [comment]
For some reason, omitting properties from a type with an index signature behaves like this:

```
type Test = {
  [x: string]: unknown;
  name: string;
};

type Foo = Omit<Test, "lol">; // { [x: string]: unknown; [x: number]: unknown; }
```

**Comment by jussisaurio** [comment]
This is apparently intended behavior: https://github.com/microsoft/TypeScript/issues/45367

**Comment by jussisaurio** [comment]
Just to clarify: do you have a reproduction repo available where the behavior you reported occurs? And does that reproduction show that the regression 100% surely happened between 10.11.1 and 10.11.0?

I have run out of time to investigate this right now, but it does seem that because Pick/Omit use `keyof` internally and objects with an index signature return `string` from `keyof` that this has something to do with the types breaking. I have no idea why it would happen between those two specific versions though.

**Comment by omridevk** [comment]
@jussisaurio  thanks a lot for the quick response.
Yes indeed, if look at my example it is currently uses version 10.11.0 which is working fine:
<img width="656" alt="CleanShot 2023-11-13 at 20 35 53@2x" src="https://github.com/trpc/trpc/assets/9701896/5f36681a-5af1-4d67-9e93-660592861214">


Changing the package version to 10.11.1 you can see the issue right away.

**Comment by omridevk** [comment]
I didn't really check that the PR i mentioned is the root cause, however I was able to verify the breaking change is between 10.11.0 and 10.11.1 and looking at the change log that PR looks the most relevant.

**Comment by jussisaurio** [comment]
> @jussisaurio thanks a lot for the quick response. Yes indeed, if you look at my example it is currently uses version 10.11.0 which is working fine: <img alt="CleanShot 2023-11-13 at 20 35 53@2x" width="656" src="https://user-images.githubusercontent.com/9701896/282555911-5f36681a-5af1-4d67-9e93-660592861214.png">
> 
> Changing the package version to 10.11.1 you can see the issue right away.

The screenshot you posted shows the type as `SerializeObject<UndefinedToOptional<T>>`. What the `Simplify` change between the two versions did was remove the indirection and show the type in object form. If you look at your reproduction and hover on `result.data.name` in the same file, the type of `name` is `never`. So to me it looks like this didn't work properly even in 10.11.0, the `Simplify` change just made it more apparent.

**Comment by KATT** [comment]
Please try out `10.43.4` and open a new issue if you encounter anything related 🙏

**Comment by Glinkis** [comment]
@KATT I upgraded to the latest version, and now all `Record` types become `{}`.

**Comment by jussisaurio** [comment]
> @KATT I upgraded to the latest version, and now all `Record` types become `{}`.

PR to fix: https://github.com/trpc/trpc/pull/5058
