### ISSUE TITLE
feat: update react-query to 5.8.4

### ISSUE THREAD

**Issue by yuriy-yarosh** [trpc/trpc#5046]
### Describe the feature you'd like to request

It would've been nice to update the react-query to 5.8.4

### Describe the solution you'd like to see

Update the react-query dependency and test it for compatibility.

### Describe alternate solutions

None.

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/5046">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/5046/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/5046/pledge.svg">
</picture>
</a>

**Comment by juliusmarminge** [comment]
#4218
