### ISSUE TITLE
Batching - safeguard for max url length

### ISSUE THREAD

**Issue by KATT** [trpc/trpc#506]
> **:wave: Do you want to pick this up?** See https://github.com/trpc/trpc/issues/506#issuecomment-1016626260

---

**Challenge described:**

- Max characters for a url is ~2k characters (I think)
- Currently the batching lumps everything in a request as `/api/trpc/posts.byId,posts.byId.query,posts.byId?batch=1&input=${encodeURIComponent(JSON.stringify(input))}`

This could potentially lead to situations where the client constructs a url that is too long.

**A few things we could do to prevent this**

- Change the way we build the query
  - Given query, this could be built like like `/api/trpc/3*posts.byId?batch=x`
- Make sure the data loader splits up the queries into separate requests when exceeding limit of `x` 
- What I **don't** want to do is to use anything but `GET` for queries

---

Refs in the code

- https://github.com/trpc/trpc/blob/main/packages/client/src/internals/dataLoader.ts
- https://github.com/trpc/trpc/blob/main/packages/client/src/internals/httpRequest.ts

---

I think the best interface way of handling this is to allow doing `httpBatchLink({ maxURILength: 2048 })`.

**Comment by KATT** [comment]
> I just ran into a URL too long error (I think).
> 
> I'm sending a batch (~300) of UUIDs in a query and it falls over on the server (browser doesn't seem to mind the 25,000 character url lol). It can handle up to 182 UUIDs but any more and it gives me a `The page you were looking for cannot be served.` error.

Sounds like you ran into it indeed!

Wow - how come you need to send 300 ids in a query? 😳 Can you explain a bit how this works in your app?

I'm surprised the browser didn't choke on it! 

Maybe you can rewrite it as a list query instead somehow?



> Is there currently a way to increase the max query string length? (or is this a Next.js limitation?)

I don't think it's a Next.js limitation per se, but rather a [Node.js](https://stackoverflow.com/a/32763588/590396)-thing. 

> 
> I could rewrite it as a mutation but this would be a huge pain. I know you've said you don't want to use anything but `GET`s for queries, but is this a valid use case? Maybe if it was opt-in per query?

For now, the `GET` is the only way to do queries, I'll give it a think, maybe we can do a POST query with a `?method=GET`-query or something. 


I'll give this some thought but I won't pick this up for at least a few days so please see if you can find a way to avoid doing this.



cc @mmkal - a penny for your thoughts 🪙😊

**Comment by ecwyne** [comment]
I'm running into this issue as well. Currently I've worked around it with an intersection observer that only loads when the element is in view but something like a `httpBatchLink({ maxURILength: 2048 })` or `httpBatchLink({ maxBatchSize: 20 })` would be very very helpful.

**Comment by darioielardi** [comment]
I've just ran into this as well, is there some work being done on this I can contribute to or maybe a workaround? 
My use case is a table with 20-100 rows, and `maxBatchSize` sounds like the perfect solution.

**Comment by KATT** [comment]
Yes! Here's some rough steps:

- [ ] Add `maxBatchSize?: number` to [`httpBatchLink`](https://github.com/trpc/trpc/blob/main/packages/client/src/links/httpBatchLink.ts)
  - [ ] Note: create new `interface HTTPBatchLinkOptions extends HTTPLinkOptions { maxBatchSize?: number }`
- [ ] Add new `opts?: { maxBatchSize?: number }` to https://github.com/trpc/trpc/blob/main/packages/client/src/internals/dataLoader.ts#L23
- [ ] Forward the options from `httpBatchLink` to `dataLoader`
- [ ] Add circuit-breaker to call `dispatch()` if length exceeds `maxBatchSize` here: https://github.com/trpc/trpc/blob/main/packages/client/src/internals/dataLoader.ts#L71
- [ ] Add a test similar to https://github.com/trpc/trpc/blob/main/packages/server/test/index.test.tsx#L543
- [ ] Add to docs in https://github.com/trpc/trpc/blob/main/www/docs/client/links.md or break the batching out to it's own page

**Comment by KATT** [comment]
Fixed by #1468

**Comment by KATT** [comment]
https://github.com/trpc/trpc/releases/tag/v9.18.0
