### ISSUE TITLE
bug: `useSuspenseQuery` runs on server even with `ssr: false`

### ISSUE THREAD

**Issue by relsunkaev** [trpc/trpc#5068]
#### System:
  - OS: macOS 14.1
  - CPU: (10) arm64 Apple M1 Pro
  - Memory: 155.34 MB / 16.00 GB
  - Shell: 5.9 - /bin/zsh
#### Binaries:
  - Node: 18.18.2 - ~/Library/Caches/fnm_multishells/54599_1700496575917/bin/node
  - npm: 9.8.1 - ~/Library/Caches/fnm_multishells/54599_1700496575917/bin/npm
  - pnpm: 8.10.2 - ~/Library/pnpm/pnpm
#### Browsers:
  - Chrome: 119.0.6045.159
  - Edge: 119.0.2151.72
  - Safari: 17.1
 #### Packages:
  - typescript: 5.3.2
  - next: 14.0.3
  - react: 18.2.0
  - @trpc/server: 10.43.6
  - @trpc/client: 10.43.6
  - @trpc/react-query: 10.43.6
  - @trpc/next: 10.43.6
  - @tanstack/react-query: 4.36.1

### Describe the bug

When using `useSuspenseQuery` the query runs a fetch during SSR even when `ssr` is set to false in the api client config. Beside double-fetching, this causes issues during rendering if you have auth on your routes as the SSR server doesn't seem to pass through the cookies to the tRPC route. I am currently using the pages directory with Next.js

### Link to reproduction

https://github.com/relsunkaev/trpc-ssr-suspense-repro

### To reproduce

Disable SSR in the api config and add a `useSuspenseQuery` in a component. Check the server console and you'll see the query runs on the server.

### Additional information

Down to file a PR with some guidance.

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

**Comment by KATT** [comment]
Not a bug - you can't disable suspense queries, we should perhaps omit remove the `ssr` option the same way we omit `enabled`

**Comment by KATT** [comment]
No, we likely won't build this.

Disabling it conditionally would force us to have the return type change to nullable which is hairy
