### ISSUE TITLE
bug: with uWebsockets as a backend

### ISSUE THREAD

**Issue by yovanoc** [trpc/trpc#5076]
### Provide environment information

System:
    OS: macOS 14.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 24.91 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.2.0 - ~/Library/Caches/fnm_multishells/23322_1700558163187/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 10.2.3 - ~/Library/Caches/fnm_multishells/23322_1700558163187/bin/npm
    pnpm: 8.10.5 - ~/Library/Caches/fnm_multishells/23322_1700558163187/bin/pnpm
    bun: 1.0.13 - ~/.bun/bin/bun
  Browsers:
    Safari: 17.1
  npmPackages:
    typescript: 5.2.2 => 5.2.2

### Describe the bug

```
TRPCClientError: Unexpected token '<', "<h1>HTTP V"... is not valid JSON
    at TRPCClientError.from (file:///Users/devchris/code/project/node_modules/.pnpm/@trpc+client@10.43.6_@trpc+server@10.43.6/node_modules/@trpc/client/dist/TRPCClientError-0de4d231.mjs:37:16)
    at file:///Users/devchris/code/project/node_modules/.pnpm/@trpc+client@10.43.6_@trpc+server@10.43.6/node_modules/@trpc/client/dist/httpUtils-f58ceda1.mjs:128:36
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  meta: {
    response: Response {
      [Symbol(realm)]: null,
      [Symbol(state)]: {
        aborted: false,
        rangeRequested: false,
        timingAllowPassed: true,
        requestIncludesCredentials: true,
        type: 'default',
        status: 505,
        timingInfo: {
          startTime: 739.0314900279045,
          redirectStartTime: 0,
          redirectEndTime: 0,
          postRedirectStartTime: 739.0314900279045,
          finalServiceWorkerStartTime: 0,
          finalNetworkResponseStartTime: 0,
          finalNetworkRequestStartTime: 0,
          endTime: 787.544527053833,
          encodedBodySize: 0,
          decodedBodySize: 0,
          finalConnectionTimingInfo: null
        },
        cacheState: '',
        statusText: 'HTTP Version Not Supported',
        headersList: HeadersList {
          cookies: null,
          [Symbol(headers map)]: Map(0) {},
          [Symbol(headers map sorted)]: null
        },
        urlList: [ URL {} ],
        body: {
          stream: ReadableStream {
            [Symbol(kType)]: 'ReadableStream',
            [Symbol(kState)]: [Object],
            [Symbol(nodejs.webstream.isClosedPromise)]: [Object],
            [Symbol(nodejs.webstream.controllerErrorFunction)]: [Function: bound error]
          }
        }
      },
      [Symbol(headers)]: Headers {
        [Symbol(headers list)]: HeadersList {
          cookies: null,
          [Symbol(headers map)]: Map(0) {},
          [Symbol(headers map sorted)]: null
        },
        [Symbol(guard)]: 'immutable',
        [Symbol(realm)]: null
      }
    }
  },
  shape: undefined,
  data: undefined,
  [cause]: SyntaxError: Unexpected token '<', "<h1>HTTP V"... is not valid JSON
      at JSON.parse (<anonymous>)
      at parseJSONFromBytes (node:internal/deps/undici/undici:4763:19)
      at successSteps (node:internal/deps/undici/undici:4734:27)
      at fullyReadBody (node:internal/deps/undici/undici:1447:9)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async specConsumeBody (node:internal/deps/undici/undici:4743:7)
}

Node.js v21.2.0
```

### Link to reproduction

sorry

### To reproduce

If we send lots of requests at the same time uwebsockets send status 505 and I don't know where to handle this crash client side ? thanks

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/5076">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/5076/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/5076/pledge.svg">
</picture>
</a>

**Comment by KATT** [comment]
Idk but we don't have a uWebsocket adapter and no repro. Life is too short to do wild goose chases for free

**Comment by yovanoc** [comment]
Wow. Didn't mean to offend you. Sorry

**Comment by Nick-Lucas** [comment]
If you can provide a full reproduction we can have a look, but like Katt says we don’t officially support that backend.

in any case it looks like your own code is returning HTML instead of JSON, which usually implies a web server misconfiguration and not a bug in trpc

**Comment by yovanoc** [comment]
Yes I know that maybe I don't use the right words, sorry for my English. I should ask uwebsockets maintainer why this is sending an `HTTP Version Not Supported`  when I stress test the server it doesn't make any sense for me. sorry again

**Comment by KATT** [comment]
Hey again 👋 

We appreciate you taking the time to report this issue. Apologies if my previous response seemed abrupt; I noticed a bug on whilst on my phone and responded promptly.

Unfortunately, we don't have the capacity to assist with issues without a reproduction repository and this issue does not seem to be related to tRPC itself. 

For effective assistance, reopening the issue with a reproduction repository would be immensely helpful. Alternatively, you can try to get help on our [Discord](https://trpc.io/discord) or in [GitHub Discussions](https://github.com/trpc/trpc/discussions).

Thank you for your understanding and cooperation!

**Comment by yovanoc** [comment]
Appears to be fixed with your fix about trimming slashes, good
