### ISSUE TITLE
bug: mutation result isLoading is reset to `false` before `isSuccess` is set to `true`

### ISSUE THREAD

**Issue by garrettg123** [trpc/trpc#5086]
### Provide environment information

```
  System:
    OS: macOS 13.4.1
    CPU: (12) x64 Apple M2 Max
    Memory: 417.26 MB / 32.00 GB
    Shell: 3.6.1 - /usr/local/bin/fish
  Binaries:
    Node: 20.9.0 - /usr/local/bin/node
    npm: 10.1.0 - /usr/local/bin/npm
    pnpm: 8.6.12 - ~/Library/pnpm/pnpm
    bun: 1.0.11 - ~/.bun/bin/bun
    Watchman: 2023.08.14.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 119.0.6045.159
    Safari: 16.5.1
```

### Describe the bug

I can't seem to get my mutation to run once. Upon inspection, it runs twice because `isLoading` is reset to `false` before the mutation succeeds, so the same hook is called again:
```ts
useEffect(() => {
    if (
      mutationResult.isError ||
      mutationResult.isSuccess ||
      !router.query.code
    ) {
      return
    }

    if (mutationResult.isLoading) {
      track(EVENT.INTEGRATING, {
        integrationName,
      })
      return
    }

    console.log(
      'Adding %o integration',
      integrationName,
      router.query,
      mutationResult
    )
    mutationResult.mutate({
      code: router.query.code as string,
      state: router.query.state as string,
    })
  }, [
    mutationResult.isLoading,
    mutationResult.isError,
    mutationResult.isSuccess,
    router.query.code,
  ])
```

### Link to reproduction

https://stackblitz.com/edit/github-5mxpk5?file=src%2Fpages%2Findex.tsx

### To reproduce

```
  useEffect(() => {
    if (result.isLoading || result.isSuccess) {
      return;
    }

    console.log('Mutating', result);
    result.mutate({ name: 'client' });
  }, [result.isLoading, result.isSuccess]);
```

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/5086">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/5086/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/5086/pledge.svg">
</picture>
</a>

**Comment by Nick-Lucas** [comment]
This is react-query not tRPC, you should go over to them https://github.com/TanStack/query
