### ISSUE TITLE
bug:  requests from components (client and server) in nextjs is in pending state indefinitely and not resolving .

### ISSUE THREAD

**Issue by iamrahulrnair** [trpc/trpc#5117]
### Provide environment information

  System:
    OS: Linux 5.10 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (8) x64 Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz
    Memory: 10.41 GB / 12.37 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.19.0 - ~/.nvm/versions/node/v18.19.0/bin/node
    Yarn: 1.22.17 - /mnt/c/Users/rahul/AppData/Roaming/npm/yarn
    npm: 10.2.3 - ~/.nvm/versions/node/v18.19.0/bin/npm
    pnpm: 8.11.0 - ~/.local/share/pnpm/pnpm
  npmPackages:
    @tanstack/react-query: ^4.35.0 => 4.36.1 
    @trpc/client: 10.36.0 => 10.36.0 
    @trpc/next: 10.36.0 => 10.36.0 
    @trpc/react-query: 10.36.0 => 10.36.0 
    @trpc/server: 10.36.0 => 10.36.0 
    next: ^14.0.3 => 14.0.3 
    react: 18.2.0 => 18.2.0 
    typescript: ^5.3.2 => 5.3.2 

### Describe the bug

When a page is loaded child components calls queries, these batched queries are not resolved, its always in pending state.

![image](https://github.com/trpc/trpc/assets/55950758/ef107e6e-347f-4c39-a970-e4752a58effd)
![image](https://github.com/trpc/trpc/assets/55950758/1befe20d-43a2-4cbc-aadc-4a75bdf9c338)
 

### Link to reproduction

NA

### To reproduce

NA

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/5117">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/5117/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/5117/pledge.svg">
</picture>
</a>

**Comment by iamrahulrnair** [comment]
can't be able to reproduce it. is there any way to know this from the specs i have shared?

**Comment by iamrahulrnair** [comment]
The issue was related to using top level await in Router module, is that a bug? or should i raise a new issue reasoning that?

**Comment by KATT** [comment]
Hey again 👋 

We appreciate you taking the time to report this issue.

Unfortunately, we don't have the capacity to assist with issues without a reproduction repository and this issue does not seem to be related to tRPC itself. 

For effective assistance, reopening the issue with a reproduction repository would be immensely helpful. Alternatively, you can try to get help on our [Discord](https://trpc.io/discord) or in [GitHub Discussions](https://github.com/trpc/trpc/discussions).

Thank you for your understanding and cooperation!
