### ISSUE TITLE
feat: Query Client Utility Methods outside React Context

### ISSUE THREAD

**Issue by sebasptsch** [trpc/trpc#5129]
### Describe the feature you'd like to request

In my project I would like to be able to prefetch a query by using the `ensureData()` function in a react-router-loader to pre-populate the query client cache.

### Describe the solution you'd like to see

I would like to see a generic `utils` instead of `useUtils()` so that ensureData may be called outside of the react context but still be typed with tRPC and populate the QueryClient query cache.

### Describe alternate solutions

Currently in my project I'm defining a vanilla trpc client and using getQueryKey to find the key for the query I wish to pre-fetch. 
```ts
const result = await queryClient.ensureQueryData({
    queryKey: getQueryKey(trpc.auth.status),
    queryFn: () => trpcProxyClient.auth.status.query(),
  });
  ```

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/5129">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/5129/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/5129/pledge.svg">
</picture>
</a>

**Comment by sebasptsch** [comment]
duplicate of #4974

**Comment by KATT** [comment]
This feature has been added in the [`next`-branch](https://github.com/trpc/trpc/tree/next) of tRPC, meaning it will be available in v11 of tRPC. 

It's possible to start using it _today_, have a look at the top of the readme of the `next`-branch for more info.
