### ISSUE TITLE
bug(external): an issue in dependency react-ssr-prepass

### ISSUE THREAD

**Issue by luixo** [trpc/trpc#5133]
### Provide environment information

tRPC v10.35.0

### Describe the bug

Hello,
I tried to update my project from nextjs 13 to nextjs 14 and stumbled upon error in SSR: `TypeError: useInsertionEffect only works in Client Components. Add the "use client" directive at the top of the file to use it.`.
Diving deeper, I found that error disappears when I turn off `ssr: true` in `createTRPCNext` function.
The ssr prepass that tRPC runs is powered by `react-ssr-prepass` which fails on `useInsertionEffect` that is being added to react quite recently.
There is a [PR](https://github.com/FormidableLabs/react-ssr-prepass/pull/85) to add this hooks handling in the repo, but maintainer seems to be inactive.``

### Link to reproduction

-

### To reproduce

- Create a tRPC Next.js example
- Add `useInsertionEffect` hook
- Add `ssr: true` to `createTRPCNext` function
- Error in node.js console and failure to render the page

### Additional information

I'm not sure how to go around this, actually.
`react-ssr-prepass` maintainer [mentioned](https://github.com/reactwg/react-18/discussions/37#discussioncomment-837686) that React 18 Suspense SSR architecture might make the library redundant, but I'm not that proficient in React to understand how exactly this should work.

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/5133">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/5133/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/5133/pledge.svg">
</picture>
</a>

**Comment by KATT** [comment]
With `pages/` becoming deprecated I don't see it likely that we in the core team will do major efforts in working around this. 

But we're open to contributions to rewrite [`withTRPC.tsx`](https://github.com/trpc/trpc/blob/main/packages/next/src/withTRPC.tsx) without the need for `react-ssr-prepass` if that is actually doable now. If you do a PR to the `next`-branch we can bump the peer dep on React for `@trpc/next` too.

**Comment by luixo** [comment]
There are a few issues that stop me from migrating to app dir, unfortunately.
Currently [there is no plan](https://twitter.com/leeerob/status/1631163470879096832) to deprecate pages in foreseeable future, though I understand that this will happen eventually.

> But we're open to contributions to rewrite [withTRPC.tsx](https://github.com/trpc/trpc/blob/main/packages/next/src/withTRPC.tsx) without the need for react-ssr-prepass if that is actually doable now.

I'm not sure why there was a need in using `react-ssr-prepass` in the first place.
We're waiting for all the queries to be resolved anyways and rerender the tree on any such a case.

Could it be that it was to help with queries that were made outside of tRPC queryClient?

It seems like removing it completely and just rendering the tree as it is could be as effective, we'll wait for queries to get resolved and rerender the tree the same amount of runs and in the same points of time.

**Comment by KATT** [comment]
Could work!

**Comment by luixo** [comment]
I found out it was already addressed in a PR, but was closed because tRPC still has `react >= 16.8.0` dependency and this change will only work in React 18+.

**Comment by KATT** [comment]
> I found out it was already addressed in a PR, but was closed because tRPC still has `react >= 16.8.0` dependency and this change will only work in React 18+.

We can move it to `react >= 18.2.0` in [`next`](https://github.com/trpc/trpc/tree/next)

**Comment by luixo** [comment]
A [PR](https://github.com/trpc/trpc/pull/3343) I mentioned was opened by @skyriverbend, can you reopen it?

**Comment by KATT** [comment]
I've added you as a contributor so you should be able to push to that now and get it up to date etc

**Comment by luixo** [comment]
Sorry, I don't get it.
I will not be able to push to a repository owned by another user.
I can copypaste the code and open a similar PR though. Is that what you expect?

**Comment by xiaolongkipsi** [comment]
following, we are having exact issue

**Comment by KATT** [comment]
This feature has been added in the [`next`-branch](https://github.com/trpc/trpc/tree/next) of tRPC, meaning it will be available in v11 of tRPC. 

It's possible to start using it _today_, have a look at the top of the readme of the `next`-branch for more info.

Otherwise, wait for #5201 which we _might_ merge
