### ISSUE TITLE
feat: Native Bun.serve adapter

### ISSUE THREAD

**Issue by sean256** [trpc/trpc#5140]
### Describe the feature you'd like to request

A trpc adapter to integrate with Bun's fast serve for both http and web sockets 

### Describe the solution you'd like to see

I'm new to both Bun and TRPC, but something like this:

```ts
import * as trpcBun from '@trpc/server/adapters/bun';

const server = Bun.serve(trpcBun({ port: 3000 }));

console.log(`Listening on localhost: ${server.port}`);
```

### Describe alternate solutions

Using any of the other adapters will work in Bun, however the performance claims by using Bun.serve are something that may be worth looking into.

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/5140">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/5140/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/5140/pledge.svg">
</picture>
</a>

**Comment by sebasptsch** [comment]
The https://trpc.io/docs/server/adapters/fetch adapter uses the standard fetch API so should work with bun and you should get all the benefits.

**Comment by sean256** [comment]
Including web sockets?

**Comment by sebasptsch** [comment]
> Including web sockets?

No, I think that would require a dedicated adapter. At the moment most examples use the node 'ws' package which has a different API than Bun's websocket. You might be able to adapt from one to the other.

https://bun.sh/docs/api/websockets

See the section under the collapse 'An API designed for speed'

**Comment by cah4a** [comment]
Was able to run subscriptions on Bun: https://gist.github.com/cah4a/c7d444c9601cb5f951e2a4355fc5cd0b.

I adapted [applyWSSHandler](https://github.com/trpc/trpc/blob/main/packages/server/src/adapters/ws.ts) as @sebasptsch suggest.

Seems working well and stable.

**Comment by sebasptsch** [comment]
> Was able to run subscriptions on Bun: https://gist.github.com/cah4a/c7d444c9601cb5f951e2a4355fc5cd0b.
> 
> I adapted [applyWSSHandler](https://github.com/trpc/trpc/blob/main/packages/server/src/adapters/ws.ts) as @sebasptsch suggest.
> 
> Seems working well and stable.
> 
> I could open PR, btw...
> 
> 

That's awesome, a PR would be nice!

**Comment by KATT** [comment]
I'm not sure if we want to have the maintenance burden of an official Bun adapter unless someone from the Bun-team builds and maintains the adapter and/or if @oven-sh sponsors tRPC financially. We work on tRPC on largely unpaid & limited time.

**Comment by cah4a** [comment]
https://github.com/cah4a/trpc-bun-adapter
