### ISSUE TITLE
bug: @trpc/react-query doesn't work with @tanstack/react-query@5

### ISSUE THREAD

**Issue by cah4a** [trpc/trpc#5157]
### Provide environment information

```
  System:
    OS: macOS 13.2.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 1.95 GB / 16.00 GB
    Shell: 3.5.1 - /usr/local/bin/fish
  Binaries:
    Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
    Yarn: 1.22.5 - ~/.yarn/bin/yarn
    npm: 10.1.0 - ~/.nvm/versions/node/v20.9.0/bin/npm
    pnpm: 8.5.1 - ~/Library/pnpm/pnpm
    bun: 1.0.15 - /usr/local/bin/bun
  Browsers:
    Brave Browser: 114.1.52.122
    Chrome: 120.0.6099.109
    Safari: 16.3
    Safari Technology Preview: 16.4
  npmPackages:
    @tanstack/react-query: ^5.13.4 => 5.13.4 
    @trpc/client: ^10.44.1 => 10.44.1 
    @trpc/next: ^10.44.1 => 10.44.1 
    @trpc/react-query: ^10.44.1 => 10.44.1 
    @trpc/server: ^10.44.1 => 10.44.1 
    next: ^14.0.1 => 14.0.4 
    react: ^18.2.0 => 18.2.0 
    typescript: ^5.1.3 => 5.3.3
 ```

### Describe the bug

After upgrading @tanstack/react-query to version 5 project is no longer building:

```
import { useQuery, useQueryClient, useMutation, hashQueryKey, useInfiniteQuery, useQueries } from '@tanstack/react-query';
                                                ^^^^^^^^^^^^
SyntaxError: The requested module '@tanstack/react-query' does not provide an export named 'hashQueryKey'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:131:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:213:5)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:431:15) {
  page: '/'
}
```

More info here: https://tanstack.com/query/v5/docs/react/guides/migrating-to-v5#hashquerykey-has-been-renamed-to-hashkey

### Link to reproduction

https://github.com/cah4a/trpc-minimal-starter/commit/cbebec5316ec02111d9ce71b628ccc6a0c3a1dfa

### To reproduce

```
git clone https://github.com/cah4a/trpc-minimal-starter
cd trpc-minimal-starter
pnpm install
pnpm dev
```

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/5157">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/5157/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/5157/pledge.svg">
</picture>
</a>

**Comment by KATT** [comment]
Search through issues
