### ISSUE TITLE
bug: TRPCError class, public readonly cause?: Error; this line should have override keyword according to error

### ISSUE THREAD

**Issue by me-imfhd** [trpc/trpc#5194]
### Provide environment information

  System:
    OS: Linux 6.2 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
    Memory: 1.40 GB / 7.66 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 20.6.1 - ~/.nvm/versions/node/v20.6.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v20.6.1/bin/yarn
    npm: 10.1.0 - ~/.nvm/versions/node/v20.6.1/bin/npm
    pnpm: 8.8.0 - ~/.nvm/versions/node/v20.6.1/bin/pnpm
  Browsers:
    Chrome: 119.0.6045.199
  npmPackages:
    @turbocell/api: workspace:* => 0.0.0 
    @turbocell/db: workspace:* => 0.0.0 
    @turbocell/eslint-config: workspace:* => 0.0.0 
    @turbocell/trpc-express: workspace:* => 0.0.0 
    @turbocell/tsconfig: workspace:* => 0.0.0 
    @types/bcrypt: ^5.0.2 => 5.0.2 
    @types/body-parser: ^1.19.3 => 1.19.5 
    @types/cookie-parser: ^1.4.4 => 1.4.6 
    @types/cors: ^2.8.14 => 2.8.17 
    @types/express: ^4.17.19 => 4.17.21 
    @types/express-session: ^1.17.8 => 1.17.10 
    @types/formidable: ^3.4.3 => 3.4.5 
    @types/jsonwebtoken: ^9.0.3 => 9.0.5 
    @types/node: 20.8.0 => 20.8.0 
    @types/swagger-ui-express: ^4.1.6 => 4.1.6 
    bcrypt: ^5.1.1 => 5.1.1 
    body-parser: ^1.20.2 => 1.20.2 
    concurrently: ^8.2.2 => 8.2.2 
    cookie-parser: ^1.4.6 => 1.4.6 
    cors: ^2.8.5 => 2.8.5 
    dotenv: ^16.3.1 => 16.3.1 
    esbuild: ^0.14.38 => 0.14.54 
    esbuild-register: ^3.3.2 => 3.5.0 
    eslint: ^8.50.0 => 8.56.0 
    express: ^4.18.2 => 4.18.2 
    express-session: ^1.17.3 => 1.17.3 
    formidable: ^3.5.1 => 3.5.1 
    helmet: ^7.0.0 => 7.1.0 
    js-cookie: ^3.0.5 => 3.0.5 
    jsonwebtoken: ^9.0.2 => 9.0.2 
    nodemon: ^3.0.1 => 3.0.2 
    prettier: ^3.0.3 => 3.1.1 
    swagger-ui-express: ^5.0.0 => 5.0.0 
    tsc-alias: ^1.8.8 => 1.8.8 
    tsconfig-paths: ^4.2.0 => 4.2.0 
    typescript: ^5.2.2 => 5.3.3 
    zod: ^3.22.2 => 3.22.4 

### Describe the bug

hey i am trying to use the TRPCError for throwing errors in my apps, but i am getting this error, changing the line
from public readonly cause?: Error;
to public override readonly cause?: Error;
fixes the problem the problem but i am doing that in node_modules which is not how this gets resolved,
how do i resolve this?

when trying to use module arugmentation, i am getting an dupliate declare class error meaning the TRPCError class has already be declared in TRPCError.d.ts file

please help me resolve this issue,

i am using turborepo,
this error was not there before, but since i was doing some migration of my trpc code to a seperate trpc package, i am getting these errrors

### Link to reproduction

https://github.com/me-imfhd/turbocell/tree/trpc-bug

### To reproduce

clone the repo 
checkout branch named trpc-bug
pnpm install
run docker compose up for database (might not be needed)
pnpm build

### 👨‍👧‍👦 Contributing

- [x] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/5194">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/5194/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/5194/pledge.svg">
</picture>
</a>

**Comment by KATT** [comment]
The PR has been merged, you can use it straight away using the `@canary`-tag of tRPC which is deployed automatically from `main`:


Update your `package.json` to use the latest version of tRPC:

```diff
-    "@trpc/client": "^x.y.z",
-    "@trpc/next": "^x.y.z",
-    "@trpc/react-query": "^x.y.z",
-    "@trpc/server": "^x.y.z",
+    "@trpc/client": "canary",
+    "@trpc/next": "canary",
+    "@trpc/react-query": "canary",
+    "@trpc/server": "canary",
```

Then run `npm install` or similar. Reopen the issue if updating to the canary doesn't solve it.
