### ISSUE TITLE
docs: How does one log errors in trpc procedures

### ISSUE THREAD

**Issue by BartlomiejLewandowski** [trpc/trpc#5212]
### Area of Improvement

I'm trying to figure out how to log errors in the serverside that are thrown as part of a procedure call.

Seems that the docs are describing the next js integration, while I'm using fastAPI

https://trpc.io/docs/server/error-handling

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing the suggested changes!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/5212">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/5212/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/5212/pledge.svg">
</picture>
</a>

**Comment by iulspop** [comment]
I'm having the same issue. The documentation doesn't explain this at all. I'm using the Lambda integration.

**Comment by iulspop** [comment]
So far this is the only work around I found:
```
export const t = initTRPC.context<Context>().create({
  errorFormatter(opts) {
    const { shape, error } = opts
    console.error(error)
    return shape
  },
})
```

I'd expect to have to be able to write some kind of middleware where I can handle all my errors in one place, so far haven't figured that out.

**Comment by juliusmarminge** [comment]
the `onError` function exists for all backend adapters?

**Comment by BartlomiejLewandowski** [comment]
I figured it out eventually

```
const server = fastify({
    maxParamLength: 5000,
});
server.register(fastifyTRPCPlugin, {
    prefix: '/trpc',
    trpcOptions: { router: appRouter, createContext, onError: (opts: any) => {
            const { error, type, path, input, ctx, req } = opts;
            console.error('Error:', error);
        } },
});

```
