### ISSUE TITLE
bug: Incorrect type inference with discriminated unions.

### ISSUE THREAD

**Issue by virtuallyunknown** [trpc/trpc#5215]
### Provide environment information

```
  System:
    OS: Linux 6.5 Linux Mint 21.2 (Victoria)
    CPU: (24) x64 AMD Ryzen 9 7900 12-Core Processor
    Memory: 24.78 GB / 30.53 GB
    Container: Yes
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 20.10.0 - /usr/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 10.2.5 - /usr/bin/npm
    pnpm: 8.12.1 - /usr/bin/pnpm
  Browsers:
    Chromium: 120.0.6099.109
  npmPackages:
    typescript: ^5.3.3 => 5.3.3
```

### Describe the bug

Hey folks, I am having a really weird issue. I asked about it on the Discord server and was told to submit an issue.

Basically I have a function that returns an object of the `Difference`, which is a union of 3 other types:

```ts
interface DifferenceCreate {
    type: "CREATE";
    value: any;
}

interface DifferenceRemove {
    type: "REMOVE";
    oldValue: any;
}

interface DifferenceChange {
    type: "CHANGE";
    value: any;
    oldValue: any;
}

export type Difference = DifferenceCreate | DifferenceRemove | DifferenceChange;

function myFunction(): Difference {
    return { type: 'CREATE', value: 1 }
}
```

_[These types are coming from the microdiff library](https://github.com/AsyncBanana/microdiff/blob/master/index.ts#L1-L20), I have simplified them a bit for this example._

I have created a router and a procedure that returns the result of `myFunction`. I then call this function on the **client** like this:

```ts
const test:Difference = await client.test.query();
```

However, I am getting a type error because it seems TRPC is modifying the `Difference` union and the `value` property is optional now:

```ts
Type '{ type: "CREATE"; value?: any; } | { type: "REMOVE"; oldValue?: any; } | { type: "CHANGE"; value?: any; oldValue?: any; }' is not assignable to type 'Difference'.
  Type '{ type: "CREATE"; value?: any; }' is not assignable to type 'Difference'.
    Type '{ type: "CREATE"; value?: any; }' is not assignable to type 'DifferenceCreate'.
      Property 'value' is optional in type '{ type: "CREATE"; value?: any; }' but required in type 'DifferenceCreate'.
```

I have skipped some parts where I define my router and procedures here, but you can find them in my minimal reproducible example in the TypeScript playground link below.

That said, any idea what might be causing this issue and how it can be resolved?

### Link to reproduction

https://tsplay.dev/WJB1kW

### To reproduce

Check out the TypeScript playground link.

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/5215">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/5215/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/5215/pledge.svg">
</picture>
</a>

**Comment by virtuallyunknown** [comment]
Just to further clarify.

The return type of the normal `myFunction` function is:

```ts
{ type: "CREATE"; value: any; } |
{ type: "REMOVE"; oldValue: any; } |
{ type: "CHANGE"; value: any; oldValue: any; }
```
But the return type of the procedure `client.test.query()` changes it to:

```ts
{ type: "CREATE"; value?: any; } |
{ type: "REMOVE"; oldValue?: any; } |
{ type: "CHANGE"; value?: any; oldValue?: any; }
```

So after it goes through the trpc "meatgrinder" it changes the return type and thus I get errors.

**Comment by microdev1** [comment]
As part tRPC's type inference, a serialization step is performed to ensure correct type post `JSON.parse(JSON.stringify())`.
JSON doesn't have `undefined` fields so they are converted to `optional` in the inferred type.
The generated type is correct. In your case, `value` is `any` which extends `undefined` and hence the conversion.

**Comment by virtuallyunknown** [comment]
> As part of tRPC's type inference, a serialization step is performed to ensure correct type post `JSON.parse(JSON.stringify())`. JSON doesn't have `undefined` fields so they are converted to `optional` in the inferred type. The generated type is correct. In your case, `value` is `any` which extends `undefined` and hence the conversion.

Well, that is unfortunate for me, but I have to agree the explanation makes total sense. May I ask if there any common/accepted way to deal with this problem?

For example, do I need to use a "data transformer" such as superjson (which seems to support `undefined` values), or is there any other alternative approach which doesn't operate a runtime? My issue is extra tricky too because the `Difference` type is coming from a 3rd party library so I have little control over it's types, and even if I did, in real life the `value` property could be a plethora of different things so typing that would be a challenge.

I would actually be happy to add superjson, but I wonder what the performance impact would be compared to not using it.

Well, I will do some tests tomorrow, but any possible insight would be appreciated. Cheers and merry Christmas!

**Comment by Nick-Lucas** [comment]
Adding a transformer is always worth it with trpc, nobody is here for ultra-performance, it’s the rich features that matter 

See if it resolves the problem and let us know, it’s definitely the more beaten track!

**Comment by bradennapier** [comment]
I have to disagree and instead I think it's time to look at the root of your problem - using "any" type ... anywhere. 

I REFUSE to believe that any is the proper serialization in your case. 

type Value = null | string | number | Value[] | Record<PropertyKey, Value>

{ ...value: Value } 

Etc 

any should only be used in typescript in the very rare cases you NEED it so that typescript enables others to tell typescript how inference should work.  This is almost exclusively useful for library authors (or specific utility typing)  and as someone who has used typescript every day since version 2.x you'll be hard pressed to convince me it's ever needed outside of that (well it used to be back then lol) 

Imo the use of any types is a sure fire sign of someone that either should not use typescript because they are lazy or just has more to learn. 

The idea of any being used for a client / server makes me wonder why you don't just use a regular server? TRPC is way too heavy for you, slow af, and a heavy tech debt investment.  

To clarify I don't feel that way about TRPC in general... as the other poster said here, TRPC is not for performance conscious users, it's there for the utility of it... and using any is removing the utility from it almost completely... 

Replace all this with switch(res.type) ... if(res.value) ... you'll end up doing typeof checks on such a type anyway in any decent code base. 

I'm sorry if this sounds harsh or judgmental.  It's not my intent at all.  Everyone has their own needs, but I felt it worth pointing out in a direct manner as I would with any developer I were doing a code review for. 

Maybe there are absolute needs for any I'm not aware of in direct runtime code... just haven't seen it!

**Comment by bradennapier** [comment]
I guess if you're intent though you could just modify the type easily enough by inferring it with "& { value: {} }" or "Required<typeof...>"

Responding from phone so sorry not nicely formatted!

**Comment by bradennapier** [comment]
So I wrote out a huge reply already but felt it gave off a bit of an aggressive demeanor which was not my intent. 

I do want to directly and strongly point out that the `any` type being part of any of your runtime code is a sign of issues you should address.  There are many ways to fix it.  If the 3rd party library is actually typed this way then it prob a sign something is amiss as it should prob be using generics or similar.

[You could fix this on your own ofc ](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzsAdsGAVASgBQMJwC+cAZlBCHAOQACMUYAxgPQDOAplAG6dUDcAKFCRYiOIyjsAhjHbZ8OcgA8AnngA2wdinjEyFanQYtGm7TH4CBMFWHZwAalPUBXObfsBeOK3qoA5nAAPnAoLurqwaEuIABGnFEQsQBW7IzwIU6u7nYA2gC6VqiyUCRSjPYAIsAkJJzaFXiSMvYIAnAdcDZ2AFxwAER4WACiAIIYw-2CnXBczm59UigqgoRFOpxlFXDVtfUoFVjsIBA8iO2d3ex9-SMAsgDyDpPTnRDqACZZC3BLKwJrIQbUrlKo1OqSA7sPAACyW-laFw6VxueAAEqMAHIAcReSNm82uv2Wrw67y+hMWJIBVnYShE8CuO3B+223l2EIa0OasiiHNZ7COJzOIX5kMacJQCKsAmYzGQJDgKggLlC7HYHy6EDgAGt1WBiSoujDtEqVeIVZ84B9tXTZCgPqw4A8wDBgBAUM4ADxirlNaSyAB8cAA-ECSlt7ABNFVQX1Q-0tL0OOB27SOxyEjAeODeb45djBtMOp3xxo8xEzFEDIZjCZTfFzbJ9ByrdYR0FwGMuOMs8WC46ndjJ1NKe0Z-PZuy5zPZKeF0fj0t9rlCofnKseG73J54mbk-Mttvhzad7u9vb92Hw4cp4sTrM5vOPuxFsfp5eXv2ShEby5bmsMRxPdOibH5W3xA9KUcY86QZLoc3PMtb0XD9ZzcecZ0nDxg28JCVwTCtk2DEJ8K-KE1x4YiojIzkEx-W9A0EAQSBcA43Q9OAQBUAAxNj0ndFAAAoAEo-w6SQYB7FAxGrKha3GYYqAAGgJZs4AARiIHwZGAVgSC0J1aIFGkrEYD1fC6GdUHQeQ8AAOgkAN2FEwRzJQSypDAMAsBVEoZxgezyBcEohLaKt2F8PpArAcgKg+Ht2HsgBHNwoBUITRNzYNuL49jBNEkSARE5j3Ms0wtB0GcnJaOzFAgVQNEqmAvSuCBFS8ny-M4QMwrgTQUB1Vg+gKIgSrMiz4EkVhwngbwpAAdykdBxDMHR7NkXwUrSjKxNYXT9MMrtY2Q2V5U6AA9MMgA)

This way you actually retain strong typing.

[I would personally prefer the added ability to infer](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzsAdsGAVASgBQMJwC+cAZlBCHAOQACMUYAxgPQDOAplAG6dUDcAKFCRYiOIyjsAhjHbZ8OcgA8AnngA2wdinjEyFanQYtGm7TH4CBMFWHZwAalPUBXObfsBeOK3qoA5nAAPnAoLurqwaEuIABGnFEQsQBW7IzwIU6u7nYA2gC6VqiyUCRSjPYAIsAkJJzaFQBCUhwAPA5w7EqyKAAmrI7ObhgeAHyIAnBTcDZ2AFzUeFgAogCCGMtUUVQrALIA8g6b23gAEqsAcgDim4LTcFxD7AD8Cw530xDqvVlur46CQhFHScMoVODVWr1FAVPCSGTsdqdbrafqDbIjOxwby-HLscZdHpoyF1SQw9jNNoOcYISbTWbsBYAIiWaw2TI+U0e2TenLgXx+T3+Lj67BIqHYvUBwJKYKqNVJDXYWHYIAgPCRhNRA1xmK86OGY2RRIGJOhTRaiOpE3uDOZe0Oyw5dK5QoWIt6YolUpd-O+uN5AiBQhBpXK8qhZNhAAspCh-FbjdqDXjsSm9QSUX1TQrzRTLe0ab67XAWedrk6+dy3IH7gKAwCg1YuiJ4AyIbmo4mtdn0x407qjd4zV24dJZIWoiOlSq1RrrSFp+S8LH41bRlYBCQRelgBAUHAQCoAGI7mB7lAACgAlAsl+DafdJDAXFAD0gS1RWetNgAaB5PAsACMRBwE2ViMPuvgzGmqDoPIeAAHQSOO7A3oIkEoNBUhgGAWAQC4JRpjAiHkIRnCXo+9LsL4CwkWA5AVL0r7sIhACObhQCol43ti4xHqeMLnvuN7XkG16CAImHQaYWg6GmKEIghigQKoGhyTArQMhAJBwDheEESUoyUXAmgoAA1qwCwFEQEkQVB8CSKw4QwHenZKmmUgAO5SOg4hmDoiGyL47GcdxYnMMw9wAHrPFYkWhBAXlwF59iMHGyAoKSnQtMA6gqEUumXk5LlBf2ngVYsKw-lQ142tM0mOTRLkAExpiV6gwHyCXTLF4E1HAl4AIRDR1JH1k8dVUVMjVwGNADM7XNZ13VRb1cXBgNw2jctJHVuwU2+rNY0ACxLc5K2+j1Ux9ZtRVjWVWIVd4X7VRsWxBCED3ts91AOkctX1TNDlzbtACs50uatMUbUAA) in unknown cases like this so simple type checks are always valid  and easy to do.  The extending of the base type here is unnecessary but useful to provide a direct reference of what all other types should conform to.

**Comment by virtuallyunknown** [comment]
Okay, so there is quite a lot to unpack here, so let me try to respond as short as possible without wasting too much of your time.

I've read both the replies including the deleted one, and none of them come as aggressive, they came off as direct which is actually something I appreciate, so no offense taken whatsoever.

Next, I have tried adding superjson and it immediately solved the issue, both in compile and runtime. Perhaps I should have tried it before opening the issue, but I only figured out what the core of the problem is after your assistance, so it would have taken me hours and hours to figure it out on my own. I am yet to decide on whether or not this what I will end up using.

A short bit on performance. I try to be "performance-aware" in every bit of code I write. This is the first project I am using trpc with, and it's just for a developer tool I'm going to use, and I won't be serving millions of requests, the only client is me or other developers so "blazing fast" performance is not critical, it's not going to run in production environments. This project also serves as a nice trpc learning experience, but none of this is to say I won't be using trpc in the future, which is why I asked about performance.

As for the main issue in hand, I completely agree that using `any` is a bad practice to be avoided, it also became clear that it's the main culprit here, not fault of trpc.

I have checked your examples, and I came up with my own solution. The problem I have is that the `Difference` type comes from a 3rd party library so I can't modify the `ReturnType` of it's functions, so I made a wrapper function.

```ts
import type { Difference } from 'microdiff';

type Diff<T extends Difference = Difference> = T extends T
    ? { [K in keyof T]:
        K extends 'value'
        ? string
        : K extends 'oldValue'
        ? string
        : T[K]
    }
    : never;

export function diffWrapper(difference: Difference[]): Diff[] {
    return difference.map(diff => {
        return ({
            ...diff,
            ...'value' in diff && { value: typeof diff.value === 'undefined' ? '' : String(diff.value) },
            ...'oldValue' in diff && { oldValue: typeof diff.oldValue === 'undefined' ? '' : String(diff.oldValue) },
        })
    })
}
```

After reading your replies it occurred to me that even if trpc inferred the procedure return type as `any` (instead of optional property), it would still be kind of an issue that I would have to deal with on the client side. And my use case here is that I have a bunch of objects in a database, I need to perform some comparison and find the differences on the server side, then send them to the client for inspection. But for this inspection, I only need a basic preview so I can see what changed, this is why I can get away with converting everything to string.

```ts
type BaseRule = {
    type: "problem" | "suggestion" | "layout" | null;
    name: string;
    description: string;
    url: string;
    library: "eslint" | "@typescript-eslint/eslint-plugin" | "eslint-plugin-react" | "eslint-plugin-unicorn" | "@stylistic/eslint-plugin";
    fixable: "code" | "whitespace" | null;
    deprecated: boolean;
    recommended: string | boolean;
    hasSuggestions: boolean;
    extendsBaseRule: string | boolean;
    requiresTypeChecking: boolean;
    replacedBy: string[];
    schema: (any[] | Record<string, any>) & (any[] | Record<string, any> | undefined);
}
```

![image](https://github.com/trpc/trpc/assets/24871108/7d8b11f9-88c9-4739-88d3-d5b1654ec771)

In theory I could probably hack the type system even further to get better inference and send the real value to client rather than string, then do the processing there, but to put this on a web page I would need a string representation anyway, so for my use case this method is easier.

Anyway, I don't want to write walls of text, but I really appreciate your comments. It helped me understand what happens behind the scenes, and it's rare to see library developers provide such in-depth responses, so thank you very much for that.

I will also close the issue because obviously this is not a bug. Cheers!

**Comment by bradennapier** [comment]
Beautifully done.  Without your code base or spending the time necessary to interact back and forth and determine your exact needs I attempted to give you ways to consider the problem from differing point of views. 

I admit, I assumed I failed as I wrote it at 5 am on Christmas morning when it caught my eyes in an email. 

Examined, considered, Replied, solved like a true engineer. I do sometimes forget engineers often understand directness which most do not.. at... all, even when prefacing that you are about to do so before you do. :) 

I actually wrote a very similar solution in a PR to the application but I got too tired trying to consider all their needs for application. lol.

In typescript, you will be amazed what can be done purely in the type checks to reduce a runtime problem to null or near-null as long as you apply it at the right place with the right precision. 

It looks to me you accomplished this, congrats! Happy holidays.

**Comment by bradennapier** [comment]
One piece of advice I'd give any typescript user - NEVER and I mean NEVER underestimate the power that "satisfies" operator provides.

In my mind it is the single feature which contributed more to typescript in the last couple years than any other... between generics and satisfies you can do an amazing number of things...

[Never forget that typescript is Turing complete! ](https://github.com/microsoft/TypeScript/issues/14833)

**Comment by bradennapier** [comment]
On performance, performance is generally over appreciated in many code bases but fatally under appreciated in all code bases that get it wrong. 

To simplify, your performance is directly determined by your own code base and needs... and many developers consider performance more important than ever needed and waste tons of time implementing better performance (which is expensive laboriously), that being said - once you get it wrong it becomes fatal quickly.  Luckily that SHOULD show itself quickly if you pay attention. In some form or another that makes no sense for the first 3-4 hours you spend on it ;)

**Comment by virtuallyunknown** [comment]
Cheers for the follow up, and yeah, once again I completely agree with everything you said (starting to notice a pattern here haha).

I do have the tendency to prematurely-optimize stuff that first needs to be made working instead, not the other way around. Recently I even started learning go because I was fascinated on how fast things can run, and wrote [a small cli tool](https://github.com/virtuallyunknown/npminit) as my first project to get my hands dirty with it.

But holy guacamole, it made me realize and appreciate the value of the JS/TS ecosystem, because if this took me ~1 week to code, I could have done the equivalent tool in a single afternoon with javascript. Of course, I regret absolutely nothing because learning new things is what keeps the developer interested.

Well, I don't have anything more interesting to add, so I wish you all happy holidays :)
