### ISSUE TITLE
docs/www: update docusaurus and typedoc

### ISSUE THREAD

**Issue by KATT** [trpc/trpc#5217]
### Area of Improvement

Docusaurus has released v3: https://docusaurus.io/blog/releases/3.0. Would be nice to update.

As part of this, I think we need to update typedoc, but not sure

### Additional information

- I had a stab at this in #5181 but it required more time and effort than I had that day.
- See https://github.com/trpc/trpc/tree/main/www

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/5217">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/5217/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/5217/pledge.svg">
</picture>
</a>

**Comment by iprime2** [comment]
Can you give me more details about this?

**Comment by KATT** [comment]
What do toy mean?

**Comment by iprime2** [comment]
I don't know toy?

**Comment by KATT** [comment]
What do you mean? * 😅

**Comment by vickonrails** [comment]
Hi @KATT, is someone working on this already? I have some time and would love to take this as my first contribution.

**Comment by KATT** [comment]
If it's not closed, consider it up for grabs! ❤️
