### ISSUE TITLE
feat: Automatic Conversion of tRPC Method Names from CamelCase to Kebab-Case for URLs

### ISSUE THREAD

**Issue by jon9090** [trpc/trpc#5224]
### Describe the feature you'd like to request

This feature request proposes an enhancement to the tRPC framework to automatically convert method names from camelCase (e.g., pathUrl) to kebab-case (e.g., path-url) for the generated URL paths. This feature aims to bridge the gap between JavaScript's naming conventions and the common practice of using kebab-case in URLs for better readability and SEO.

Motivation
The JavaScript community widely uses camelCase for naming functions and methods. However, in the context of URLs, kebab-case is often preferred for its readability and SEO advantages. This discrepancy can lead to inconsistencies in how routes are named in the code versus how they are represented in URLs. By introducing automatic conversion within tRPC, developers can maintain their camelCase naming conventions in JavaScript while seamlessly adhering to kebab-case URL structures.

Detailed Design
The feature would involve tRPC internally converting route names from camelCase to kebab-case when generating HTTP requests. This conversion would be an automatic part of the tRPC framework, requiring no additional configuration from the developer.

Example Implementation:

JavaScript call (client-side): trpc.pathUrl.useQuery()
Generated HTTP request (server-side): GET /path-url

The pathUrl method name would be automatically translated to path-url for the corresponding HTTP request. This feature would be a part of tRPC's core functionality, ensuring that any camelCase method name is appropriately converted to kebab-case for its URL representation.

Use Cases
Ensuring consistency between JavaScript naming conventions and URL best practices.
Simplifying the development process by removing the need for manual URL name adjustments.
Enhancing the readability and SEO-friendliness of URLs in applications using tRPC.
Alternatives Considered
Currently, developers might manually redefine or adjust URLs to match kebab-case, which can be cumbersome and error-prone. This feature would eliminate the need for such manual interventions.

### Additional information

This feature would be particularly beneficial in full-stack applications where tRPC is used in conjunction with frameworks that favor or require kebab-case URL structures, such as Next.js or Express.js.

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

**Comment by KATT** [comment]
Hey there! :wave:

We appreciate the time you've taken to write this issue.

I think this would just add a layer of obscurity between the URL and the RPC-call. For SEO, you shouldn't map tRPC calls to URLs, so that doesn't apply.

What is the actual problem you're facing that this should address?

**Comment by jon9090** [comment]
@KATT thank you.
I am currently working with tRPC and facing an issue. I have a URL `/trpc/listUser,` but I want to format it as `/trpc/list-user`.

I would like to achieve this without changing the procedure name from `userList` to something like `router({'user-list': ...}).` 

Is there a way in tRPC to modify the URL path while keeping the original procedure name intact?

**Comment by KATT** [comment]
Why do you want to format it as `/trpc/list-user`? Is there a technical reason?
