### ISSUE TITLE
feat: Passing createCaller return value to trpc.Provider

### ISSUE THREAD

**Issue by timvandam** [trpc/trpc#5248]
### Feature
I would like to be able to pass `createCaller` return value to `trpc.Provider`'s `client` prop. Allowing this makes SSR with trpc much easier. 

---

### Context

I am aware that SSR is officially supported for nextjs, but I am using a custom Vite server. I have investigated the nextjs ssr code, but replicating it by simply passing `ssrContext` did not work for me (it seems like I need to pass props everywhere if I understood it correctly). 

My Vite server uses react-query's (de)hydration utils to hydrate the front end with whatever react-query did during the server-side render, leading to this server entrypoint:
```ts
export const render = async (req: Connect.IncomingMessage) => {
    const queryClient = new QueryClient();
    const trpcClient = trpc.createClient({
        links: [
            httpLink({
                url: 'http://localhost:5173/trpc',
                headers() {
                    return {
                        cookie: req.headers?.cookie,
                    };
                },
            }),
        ],
    });

    const Document = () => (
        <trpc.Provider client={trpcClient} queryClient={queryClient}>
            <QueryClientProvider client={queryClient}>
                <App />
            </QueryClientProvider>
        </trpc.Provider>
    );

    await ssrPrepass(<Document />);

    const html = renderToString(<Document />);

    const state = dehydrate(queryClient);

    return { html, state };
};
```

This can be much simpler (and a bit faster) by simply being able to provide the context to the TRPCClient directly, instead of having to replicate a request coming from the frontend. I.e. `trpcClient` would become:
```ts
const trpcClient = appRouter.createCaller(createContext(req));
```

### Describe the solution you'd like to see

Changing the prop type to allow this

(despite the types not matching, passing the `createCaller` does work for me)

### Describe alternate solutions

Making requests that are formed like the ones from the frontend (as done above)

### 👨‍👧‍👦 Contributing

- [x] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/5248">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/5248/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/5248/pledge.svg">
</picture>
</a>

**Comment by juliusmarminge** [comment]
You can do this with a custom link:

```ts
const context = createContext(req);

const trpcClient = createTRPCClient<typeof appRouter>({
  links: [
    () =>
      ({ op }) =>
        observable((observer) => {
          callProcedure({
            procedures: appRouter._def.procedures,
            path: op.path,
            getRawInput: () => Promise.resolve(op.input),
            ctx: context,
            type: op.type,
          })
          .then((data) => {
            observer.next({ result: { data } });
            observer.complete();
          })
          .catch((cause: TRPCErrorResponse) => {
            observer.error(TRPCClientError.from(cause));
          });
        }),
  ],
});
```

> (despite the types not matching, passing the createCaller does work for me)

This seems weird as createCaller and a client doesn't have the same call signatures (no `.query()` in createCaller).

**Comment by timvandam** [comment]
Perfect, that works! I think `client.query` is just never called in my case. I am using `useSuspenseQuery` so it seems like it is calling `useQuery` on the recursive proxy.

Feel free to close this issue if its not something that fits

**Comment by juliusmarminge** [comment]
useQuery calls client.query by default: https://github.com/trpc/trpc/blob/4e101e3af7ce3ee92eb5c3f7d167d2a800e73a55/packages/react-query/src/shared/hooks/createHooksInternal.tsx#L324

But it's not using proxy so maybe that's why it works then 😅
