### ISSUE TITLE
bug: bundle size increase 10.44.1 -> 10.45.0

### ISSUE THREAD

**Issue by enricoros** [trpc/trpc#5249]
### Provide environment information

```
   System:
    OS: Windows 11 10.0.22631
    CPU: (24) x64 AMD Ryzen 9 5900X 12-Core Processor
    Memory: 41.21 GB / 63.91 GB
  Binaries:
    Node: 20.8.1 - C:\P\apps\nodejs\node.EXE
    npm: 10.1.0 - C:\P\apps\nodejs\npm.CMD
    pnpm: 8.10.5 - ~\AppData\Local\pnpm\pnpm.EXE
  Browsers:
    Edge: Chromium (120.0.2210.91)
  npmPackages:
    @tanstack/react-query: ~4.36.1 => 4.36.1
    @trpc/client: 10.45.0 => 10.45.0
    @trpc/next: 10.45.0 => 10.45.0
    @trpc/react-query: 10.45.0 => 10.45.0
    @trpc/server: 10.45.0 => 10.45.0
    next: ^14.0.4 => 14.0.4
    react: ^18.2.0 => 18.2.0
    typescript: ^5.3.3 => 5.3.3
 ```

### Describe the bug

(Forgive me with this one, I may be doing something wrong or it's a side effect of something else being triggered by the update of this package)

Updating tRPC from 10.44.1 to 10.45.0 increases the size of my bundle (NextJS 14.0.4) considerably: +18kb.

I don't have the skills to trace the culprit, so I tried many permutation of packages versions (with fresh builds) to verify that this update triggered the size increase.

This is a bundle analysis - on the Left side 10.44.1, on the right side, 10.45.0. You can see the 2 files `react-dom-server.browser.production.min.js` and `react-dom-server.legacy.browser.production.min.js`. Note that I don't use anything related to server components.
![image](https://github.com/trpc/trpc/assets/32999/7bfcd2ca-4be2-4b2f-8e32-e717d55c486a)

I see that this release removed the dependency to `react-ssr-prepass`, which may be related?

Does anyone else experience this?

### Link to reproduction

https://github.com/enricoros/big-AGI/commit/edd36ea78037103347a6b354c6f2e6c22a8fe0de

### To reproduce

I wish I could repro here. I guess one can check out the following code with and without the increase:
 - [size increase with 10.45.0]  https://github.com/enricoros/big-AGI/commit/edd36ea78037103347a6b354c6f2e6c22a8fe0de
 - [no increase with 10.44.1] https://github.com/enricoros/big-AGI/commit/4f6a596cc7c13e291689013ce3dd1422978793ed

### Additional information

Sorry for the non-repro, this is outside of my comfort zone.

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/5249">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/5249/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/5249/pledge.svg">
</picture>
</a>

**Comment by juliusmarminge** [comment]
Probably from this: https://github.com/trpc/trpc/pull/5201

cc @KATT

**Comment by KATT** [comment]
Hmm - it's dynamically imported so it should only happen serverside - think this can be a false positive

**Comment by KATT** [comment]
As far as I know, that code path where the dynamic import happens should only execute on the server?

**Comment by KATT** [comment]
(cc @luixo)

**Comment by KATT** [comment]
cc @enricoros can you confirm that a page load in the browser actually includes the bundle specified above?

**Comment by KATT** [comment]
I did measurements using bundlejs and at a first glance it looks like you're right here, but I don't know if this is another false positive

- https://bundlejs.com/?q=%40trpc%2Fnext%4010.44.1&treeshake=%5B%7BwithTRPC%7D%5D&text=%22withTRPC%28%29%3B%22 ![CleanShot 2024-01-05 at 00 54 33@2x](https://github.com/trpc/trpc/assets/459267/b8515a55-7f53-437f-b043-d51cfe38fe26)
- https://bundlejs.com/?q=%40trpc%2Fnext%4010.45.0&treeshake=%5B%7BwithTRPC%7D%5D&text=%22withTRPC%28%29%3B%22 ![CleanShot 2024-01-05 at 00 54 26@2x](https://github.com/trpc/trpc/assets/459267/28c86008-686e-43d5-b403-61140d8f5e11)

**Comment by KATT** [comment]
I'm pretty sure this is invalid - the compiled js doesn't have a top-level import of React - https://www.npmjs.com/package/@trpc/next?activeTab=code


Here's a big ugly screenshot after navigating to `dist/index.mjs`:


![www npmjs com_package_@trpc_next_activeTab=code](https://github.com/trpc/trpc/assets/459267/c18a98b4-8b30-48b3-b6dd-6099ebee9d1a)

This code path is impossible in the browser and only happens on the server when you have [`ssr: true`](https://trpc.io/docs/client/nextjs/ssr)

**Comment by KATT** [comment]
This is a false-positive.

If you look at the bundle with removing `react-dom/server` (which is included dynamically), it's actually **smaller**:


- https://bundlejs.com/?q=%40trpc%2Fnext%4010.44.1&treeshake=%5B%7BwithTRPC%7D%5D&text=%22withTRPC%28%29%3B%22&config=%7B%22esbuild%22%3A%7B%22external%22%3A%5B%22react-dom%2Fserver%22%5D%7D%7D
- https://bundlejs.com/?q=%40trpc%2Fnext%4010.45.0&treeshake=%5B%7BwithTRPC%7D%5D&text=%22withTRPC%28%29%3B%22&config=%7B%22esbuild%22%3A%7B%22external%22%3A%5B%22react-dom%2Fserver%22%5D%7D%7D

Please reopen it if you can show that it shows up in a browser bundle

**Comment by enricoros** [comment]
I understand this is not executed on the client, but the 20kb are gonna reduce some web metrics/scores right?

All the users will need to download that code (it's bundled) even if not executed. Is there a way to avoid it?

**Comment by KATT** [comment]
> Update: will look if the download size is different.
> 
> I understand this is not executed on the client, but the 20kb are gonna reduce some web metrics/scores right? @KATT
> 
> All the users will need to download that code (it's bundled) even if not executed. Is there a way to avoid it?

Will they? Can you prove this somehow?

AFAICT, it will create a bundle for react-dom but it will only be downloaded on the server if you're using `ssr: true`

**Comment by KATT** [comment]
cc @enricoros if you see this ever being downloaded in the browser, please open a new issue
