### ISSUE TITLE
docs: @trpc/next@10.45.0 uses @tanstack/react-query@4.18.0 whereas in documentation of trpc installation in nextjs it installs @tanstack/react-query@4.0.0 , it is conflict error

### ISSUE THREAD

**Issue by yashpatel21102002** [trpc/trpc#5263]
### Area of Improvement

just modify the command from @tanstack/react-query@4.0.0 to @tanstack/react-query@4.18.0
![Screenshot (61)](https://github.com/trpc/trpc/assets/89585732/ebe0e64a-5258-42a8-9dd5-c1b04830a990)

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing the suggested changes!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/5263">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/5263/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/5263/pledge.svg">
</picture>
</a>

**Comment by KATT** [comment]
Doesn't `(npm|yarn|pnpm) install @tanstack/react-query@^4.0.0` install the latest `4.x.x` in all package managers...?

**Comment by yashpatel21102002** [comment]
No in my case, it was giving conflicting error, but when I downloaded the latest one , the error was gone :)

I used npm for installation

**Comment by juliusmarminge** [comment]
I believe the only package manager that doesn't install latest is pnpm between 8.0 and 8.5 so i think this is a non-issue

**Comment by belgattitude** [comment]
Explicitly add the react query dep version, pnpm dedupe or npm dedupe or yarn dedupe just after and it should work

**Comment by KATT** [comment]
Updating in #5280. Tested with a new npm repo and it seems to work to do just `@4`. Reopen if it doesn't
