### ISSUE TITLE
bug: observable automatically calls cleanup function with bun

### ISSUE THREAD

**Issue by gpichot** [trpc/trpc#5268]
### Provide environment information

```
  Binaries:
    Node: 21.1.0 - ~/.nvm/versions/node/v21.1.0/bin/node
    Yarn: 1.22.18 - /opt/homebrew/bin/yarn
    npm: 10.2.0 - ~/.nvm/versions/node/v21.1.0/bin/npm
    pnpm: 8.6.0 - ~/Library/pnpm/pnpm
    bun: 1.0.19 - /opt/homebrew/bin/bun
  Browsers:
    Chrome: 120.0.6099.129
    Edge: 115.0.1901.188
    Safari: 17.2
  npmPackages:
    @trpc/server: next => 11.0.0-next-alpha.152+972c8bea5
    @tanstack/react-query: ^5.17.5 => 5.17.5
    @trpc/client: next => 11.0.0-next-alpha.152+972c8bea5
    @trpc/react-query: next => 11.0.0-next-alpha.152+972c8bea5
    react: ^18.2.0 => 18.2.0
    typescript: ^5.2.2 => 5.2.2
 ```

### Describe the bug

I am using bun to run a trpc application (no native adapter).

In this application I have a subscription:

```typescript
const router = router({
  onUpdate: publicProcedure.subscription(() => {
    return observable<NoteType>((emit) => {
        const onUpdate = () => { /* do stuff */ };
        console.log("subscribing");
        bus.on("noteUpdated", onUpdate);

      return () => {
        console.log("unsubscribing");
        bus.off("noteUpdated", onUpdate);
      };
    });
  }),
})
```

With bun, as soon as the observable is subscribed it's unsubscribed. So it prints:
```
subscribing
unsubscribing
```

I have pinpoint the issue down to the following line in ws adapter file, `client.OPEN` is undefined:
```typescript
        if (client.readyState !== client.OPEN) {
```
Source: https://github.com/trpc/trpc/blob/main/packages/server/src/adapters/ws.ts#L162

Which comes from the fact that in ws package, OPEN value is set like this:
```javascript
Object.defineProperty(WebSocket, 'OPEN', {
  enumerable: true,
  value: readyStates.indexOf('OPEN')
});
```
Source:https://github.com/trpc/trpc/blob/main/packages/server/src/adapters/ws.ts#L162

So it seems bun implement defineProperty differently than Node: the static property is not defined for instances. (Honestly I don't know what should be the right behavior).

For now I a patched @trpc/server like this (using pnpm patch):
```diff
diff --git a/dist/adapters/ws.mjs b/dist/adapters/ws.mjs
index ede24773b777d2745ae5a04e051121ae3d7bf77c..18906c1a8f56606eefd0a710a37a82087a1e7c2f 100644
--- a/dist/adapters/ws.mjs
+++ b/dist/adapters/ws.mjs
@@ -1,3 +1,4 @@
+import { WebSocket } from 'ws';
 import { e as callProcedure } from '../router-f9ce121f.mjs';
 import { T as TRPCError, g as getTRPCErrorFromUnknown } from '../TRPCError-7e8e2a1b.mjs';
 import '../config-50853f49.mjs';
@@ -125,7 +126,7 @@ function applyWSSHandler(opts) {
                         });
                     }
                 });
-                /* istanbul ignore next -- @preserve */ if (client.readyState !== client.OPEN) {
+                /* istanbul ignore next -- @preserve */ if (client.readyState !== WebSocket.OPEN) {
                     // if the client got disconnected whilst initializing the subscription
                     // no need to send stopped message if the client is disconnected
                     sub1.unsubscribe();
```
To use the static property in place of the instance one.
 
 
 What do you think about this?
 
 I can open a PR for this one.

### Link to reproduction

-

### To reproduce

-

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/5268">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/5268/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/5268/pledge.svg">
</picture>
</a>

**Comment by KATT** [comment]
Seems like this should be opened in https://github.com/websockets/ws instead?

**Comment by gpichot** [comment]
@KATT Yes, I am not sure about the repo ownership of this one.

In the doc, they don't use the `client.OPEN` (neither in their codebase). Code samples on the README is:

```
      if (client !== ws && client.readyState === WebSocket.OPEN) {
        client.send(data, { binary: isBinary });
      }
```

They use the value from the class not from the instance.

I am ok to open an issue on ws. 
@KATT  Can you confirm me this?

**Comment by KATT** [comment]
Maybe Bun doesn't implement WS the same as node, I don't know.

Please do a PR with your fix to https://github.com/trpc/trpc/blob/main/packages/server/src/adapters/ws.ts
