### ISSUE TITLE
Mutations with no return value stall forever

### ISSUE THREAD

**Issue by kripod** [trpc/trpc#527]
When a `resolve` callback’s return type is either:

- `Promise<void>`
- `Promise<null>`
- `Promise<undefined`

tRPC doesn’t ever close the response stream, thus, stalling the client indefinitely.

The following code **doesn’t work:**

```ts
trpc.router<Context>()
  .mutation("update", {
    input: z.object({ id: z.string() }),
    resolve: async ({ ctx, input }): Promise<void> => {
      await updateSection(input);
      // `return undefined` or `return null` wouldn’t solve the case
    },
  });
```

But the following return value change **does the trick:**

```ts
trpc.router<Context>()
  .mutation("update", {
    input: z.object({ id: z.string() }),
    resolve: async ({ ctx, input }): Promise<{ [key: string]: never }> => {
      await updateSection(input);
      return {};
    },
  });
```

**Comment by KATT** [comment]
Seems related to #512. 

@kripod - could you add a failing test?

**Comment by kripod** [comment]
@KATT Thanks for your quick response. Unfortunately, things are going pretty busy for me nowadays, so I won’t be able to add a test anytime soon.

**Comment by simonedelmann** [comment]
@KATT This is not related to #512 , but might be an indication for the same problem. I think we should generally add tests for these non-defined cases, so we can catch bugs like this or like #512. (We need tests for undefined/null/{}/void input and output.)
I just saw, you've already added a test now. If you need help, I can add some more tests regarding that later today.

**Comment by KATT** [comment]
@all-contributors add @kripod for bug reporting

**Comment by KATT** [comment]
@simonedelmann happy if you can review the PR ❤️ and challenge the way I did it
