### ISSUE TITLE
bug: Unable to call createServerSideHelpers on RSC - NextJS 14 App Router 

### ISSUE THREAD

**Issue by dellorogiulio** [trpc/trpc#5293]
### Provide environment information

  System:
    OS: Windows 11 10.0.22621
    CPU: (16) x64 12th Gen Intel(R) Core(TM) i7-1260P
    Memory: 1.12 GB / 15.69 GB
  Binaries:
    Node: 18.18.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.6.3 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.10.5 - ~\AppData\Local\pnpm\pnpm.EXE
  Browsers:
    Edge: Chromium (120.0.2210.77)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @tanstack/react-query: ^5.17.9 => 5.17.9
    @trpc/client: 11.0.0-next-alpha.162 => 11.0.0-next-alpha.162+ab22b41f7
    @trpc/next: 11.0.0-next-alpha.162 => 11.0.0-next-alpha.162+ab22b41f7
    @trpc/react-query: 11.0.0-next-alpha.162 => 11.0.0-next-alpha.162+ab22b41f7
    @trpc/server: 11.0.0-next-alpha.162 => 11.0.0-next-alpha.162+ab22b41f7
    next: 13.5.6 => 13.5.6
    react: ^18 => 18.2.0
    typescript: ^5 => 5.3.3

### Describe the bug

I'm working to let prefech working with the **latest version** of trpc and Next14 with app router.
See link below to a demo repo reproducing the error.

The problem is quite obvious, when I try to call 
```ts
const helpers = createServerSideHelpers({
    router: appRouter,
    ctx: {},
  });
```
on the main `layout.tsx` it throws an error:  

```
Server Error
Error: (0 , react__WEBPACK_IMPORTED_MODULE_2__.createContext) is not a function

This error happened while generating the page. Any console logs will be displayed in the terminal window.
```

I do not understand, since reading the [official server-side-helpers doc](https://trpc.io/docs/client/nextjs/server-side-helpers) it seem to me that `createServerSideHelpers` is there exactly for this scope.
So I would like to prefetch on the server by using

```ts
// THIS THROWS useContext error
  const helpers = createServerSideHelpers({
    router: appRouter,
    ctx: {},
  });
  await helpers.say_hello.prefetch();
  const dehydratedState = helpers.dehydrate();
```

I was able to correctly prefetch the query by manipulating directly the queryClient and using a [server-side call]( https://trpc.io/docs/server/server-side-calls)

```ts
  // THIS WORKS
  const serverCaller = createServerCaller(appRouter);
  const queryClient = getQueryClient();

  await Promise.all([
    queryClient.prefetchQuery({
      queryKey: [["say_hello"], { type: "query" }], // I HAD TO USE DEVTOOLS TO INSPECT THE QUERY
      queryFn: async () => await serverCaller.say_hello(),
    }),
  ]);
  const dehydratedState = dehydrate(queryClient);


// for completeness, this is the definition of createServerCaller  in trpc.ts
export const createServerCaller = (appRouter: AppRouterType) =>
  t.createCallerFactory(appRouter)({});

```

However this require a **manual** set of the `queryKey` that has to be prefetched, and I find no way to retrieve that via code (i inspect using the ReactQueryDevtools)

I attach the complete log trace of the error, the problem seems related to `utilsProxy`
[log.txt](https://github.com/trpc/trpc/files/13875652/log.txt)

### Link to reproduction

https://github.com/dellorogiulio/trpc-prefetch

### To reproduce

Clone the repo, go to `src/app/layout.tsx` and un-comment line 15-20 and comment 23-32

```ts

import "./globals.css";
import { appRouter } from "@/trpc";
import Providers from "@/components/Providers";
import { createServerCaller } from "@/trpc/trpc";
import getQueryClient from "@/utils/getQueryClient";
import { dehydrate } from "@tanstack/react-query";
import { createServerSideHelpers } from "@trpc/react-query/server";

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // THIS THROWS useContext error
  // const helpers = createServerSideHelpers({
  //   router: appRouter,
  //   ctx: {},
  // });
  // await helpers.say_hello.prefetch();
  // const dehydratedState = helpers.dehydrate();

  // THIS WORKS
  const serverCaller = createServerCaller(appRouter);
  const queryClient = getQueryClient();

  await Promise.all([
    queryClient.prefetchQuery({
      queryKey: [["say_hello"], { type: "query" }], // I HAD TO USE DEVTOOLS TO INSPECT THE QUERY
      queryFn: async () => await serverCaller.say_hello(),
    }),
  ]);
  const dehydratedState = dehydrate(queryClient);

  return (
    <html lang="en">
      <body>
        <Providers dehydrateState={dehydratedState}>{children}</Providers>
      </body>
    </html>
  );
}


```

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/5293">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/5293/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/5293/pledge.svg">
</picture>
</a>

**Comment by KATT** [comment]
Had a glance. Seems like `createServerSideHelpers()` imports something that calls `React.createContext` which isn't available in RSC. 

Will have a closer look tomorrow.
