### ISSUE TITLE
Further documentation on the wire spec

### ISSUE THREAD

**Issue by delaneyj** [trpc/trpc#533]
One of the big benefits Twirp has over gRPC is the ability to easily curl/postman the calls when testing or c/p to co-workers.  It would be nice to have a more detailed specification of what GET/POST/PATCH makes up a valid call (minus any transforms of course).

**Comment by KATT** [comment]
@delaneyj https://trpc.io/docs/further-reading#internals

There's some there. It is hard to use postman etc for queries (`GET`) as the inputs are by `?input=${encodeURIComponent(JSON.stringify(transformer.serialize(input)))`

I agree it would be nice; might be possible to support an alternative way of doing queries for this purpose - do you have any ideas?

**Comment by KATT** [comment]
FYI I'm also refactoring it all to be JSON-RPC 2.0-compliant #532

**Comment by delaneyj** [comment]
I think moving to a JSON-RPC compliant interface is a great idea! Batching, notification baked into the spec.  If you really want to push it you could auto gen a OpenRPC doc and respond to `rpc.discover` requests based on the types and typedoc comments!  
Getting all the benefits of a playground for free is super exciting

**Comment by KATT** [comment]
See https://trpc.io/docs/rpc
