### ISSUE TITLE
Open-Rpc discussion

### ISSUE THREAD

**Issue by delaneyj** [trpc/trpc#534]
Per #532 #533 with the move to be JSONRpc v2 compliance there is an opportunity to piggyback off of [existing tools](https://open-rpc.org/developers).  Specifically if TRPC can generate and respond to  [the extended spec](https://spec.open-rpc.org/#introduction) we get a lot of the kind of introspection that can be valueable for documentation and exploring APIs.  

Thoughts?

**Comment by KATT** [comment]
I know very little of this spec, but reading it it seems quite straight-forward except getting the inputs and outputs right as it's all done by type inference.

You seem to have worked with JSONRPC more than me, please review #532! 🙏

**Comment by delaneyj** [comment]
I actually haven't dealt with JSONRpc other than quick tests in Go.  Ironically I read the spec seeing if there was a good way to automate some of it using TS types.  I'll be happy to look at the PR but don't know if I'm qualified to really know what it's missing.  

In regards to OpenRPC its real value would be if you could discern type information automatically.  My hope was you could do it without the overhead of runtime reflection (like reflect-metadata) and could be created just from the type info.  While decorators are common its adding an extra requirement that is not ideal.
