### ISSUE TITLE
bug: Context & InnerContext sample not working

### ISSUE THREAD

**Issue by SiNONiMiTY** [trpc/trpc#5344]
### Provide environment information

v10.45

### Describe the bug

I tried to follow the instructions located at this page
https://trpc.io/docs/server/context#inner-and-outer-context

However, I am having difficulty accessing the res & req objects on my API procedures.

Searching through GH, I found an earlier issue
https://github.com/trpc/trpc/pull/3325#issuecomment-1335060254

I have tried this one too,
![image](https://github.com/trpc/trpc/assets/9588282/e4c1605a-e61c-44a3-90f8-5184ab6f0e61)

But here, you can see that the res & req objects are also undefined. How did this happen? Am I missing something here?

### Link to reproduction

N/A

### To reproduce

Just follow the samples on the documentation

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/5344">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/5344/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/5344/pledge.svg">
</picture>
</a>

**Comment by SiNONiMiTY** [comment]
Here is the whole tRPC initialization file

```
import { initTRPC } from '@trpc/server'
import type { CreateFastifyContextOptions } from '@trpc/server/adapters/fastify'
import superjson from 'superjson'

import dbClient from '../../drizzle/index.js'
import * as dbSchema from '../../drizzle/schema.js'

/**
 * Your context holds data that all of your tRPC procedures will have access to,
 * and is a great place to put things like database connections or authentication information.
 * https://trpc.io/docs/server/context
 */

export function createInnerContext(
    dbClientOverride: typeof dbClient | null = null,
) {
    return {
        dbSchema,
        dbClient: dbClientOverride || dbClient,
    }
}

export function createContext({ req, res }: CreateFastifyContextOptions) {
    const innerContext = createInnerContext()
    return { ...innerContext, req, res }
}

export type Context = Awaited<ReturnType<typeof createInnerContext>>

/**
 * Initialization of tRPC backend
 * Should be done only once per backend!
 */

const t = initTRPC.context<Context>().create({
    transformer: superjson,
})

/**
 * Export reusable router and procedure helpers
 * that can be used throughout the router
 */

export const router = t.router
export const publicProcedure = t.procedure

export const apiProcedure = publicProcedure.use((opts) => {
    if (!opts.ctx.req || !opts.ctx.res) {
        throw new Error('You are missing `req` or `res` in your call.')
    }
    return opts.next({
        ctx: {
            // We overwrite the context with the truthy `req` & `res`, which will also overwrite the types used in your procedure.
            req: opts.ctx.req,
            res: opts.ctx.res,
        },
    })
})

export const middleware = t.middleware
export const createCallerFactory = t.createCallerFactory
```

**Comment by juliusmarminge** [comment]
> export type Context = Awaited<ReturnType<typeof createInnerContext>>

Your `createInnerContext` doesn't have req/res on it so this type-error makes sense

**Comment by SiNONiMiTY** [comment]
> > export type Context = Awaited<ReturnType>
> 
> Your `createInnerContext` doesn't have req/res on it so this type-error makes sense.
> 
> Docs are likely wrong here cause this shouldn't work if you ask me

Yes this is what I am also puzzled about, it seems that on the documentation, this works seamlessly but I can't make it work. Maybe I'm missing something here or the documentation is likely wrong as you have said.
