### ISSUE TITLE
docs: Incorrect Order of Version List in Dropdown

### ISSUE THREAD

**Issue by ThomasCode92** [trpc/trpc#5351]
### Area of Improvement

When users click on the dropdown for selecting a version, the list is not displayed in the correct order. This can create confusion for users trying to choose a specific version.

### Link to related docs

https://trpc.io/

### Additional information

![image](https://github.com/trpc/trpc/assets/108367944/a817b480-532f-4438-abe9-ca012436a088)

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR implementing the suggested changes!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/5351">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/5351/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/5351/pledge.svg">
</picture>
</a>

**Comment by ThomasCode92** [comment]
I'm a newcomer to the project, and I'm not familiar with Docusaurus (yet). Could you please inform me about the file where the list is displayed?

**Comment by KATT** [comment]
- https://github.com/trpc/trpc/blob/a421c14c0c697463e6bffb597b33be849f9d8424/www/docusaurus.config.js#L201-L227
- See https://github.com/trpc/trpc/tree/next/www for how to run it
- Docusaurus docs: https://docusaurus.io/docs/2.x

**Comment by parthmanhas** [comment]
@ThomasCode92  I hope you don't mind (if my PR fixes the issue that is)

**Comment by ThomasCode92** [comment]
@parthmanhas not at all, it’s open source after all. I’m just here to learn more about the project and by reading the docs I find some “bugs”
