### ISSUE TITLE
bug: `router.path.revalidate()` returns `undefined` instead of revalidation result in next app directory.

### ISSUE THREAD

**Issue by dalechyn** [trpc/trpc#5370]
### Provide environment information

```
  System:
    OS: macOS 14.1.1
    CPU: (12) arm64 Apple M2 Pro
    Memory: 57.56 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.10.0 - ~/.nvm/versions/node/v20.10.0/bin/node
    Yarn: 1.22.19 - ~/Library/pnpm/yarn
    npm: 10.2.3 - ~/.nvm/versions/node/v20.10.0/bin/npm
    pnpm: 8.10.5 - ~/.nvm/versions/node/v20.10.0/bin/pnpm
  Browsers:
    Chrome: 120.0.6099.234
    Safari: 17.1
  npmPackages:
    @tanstack/react-query: 5.17.9 => 5.17.9
    @trpc/client: next => 11.0.0-next-beta.190+fc3e467c5
    @trpc/next: next => 11.0.0-next-beta.190+fc3e467c5
    @trpc/react-query: next => 11.0.0-next-beta.190+fc3e467c5
    @trpc/server: next => 11.0.0-next-beta.190+fc3e467c5
    next: ^14.0.4 => 14.0.4
    react: canary => 18.3.0-canary-c5b937576-20231219
    typescript: ^5.3.3 => 5.3.3
```

### Describe the bug

I can't get the route to invalidate and have to double refresh the page that queries a route from a RSC component, so I decided to log the output of `revalidate()` function:
![Screenshot 2024-01-20 at 14 08 23](https://github.com/trpc/trpc/assets/35642018/cb4685e2-396a-4b1f-bef2-dbd8426f8977)

This is the output:
![Screenshot 2024-01-20 at 14 08 35](https://github.com/trpc/trpc/assets/35642018/e71c7b14-3822-4759-8365-26fc7fdf01f3)

Although the types say a specific shape has to be returned:
![Screenshot 2024-01-20 at 14 09 13](https://github.com/trpc/trpc/assets/35642018/bd16dc47-b88f-41f0-9267-224148152849)

### Link to reproduction

Really need a next-experimental reproduction template :)

### To reproduce

Log the output of `.revalidate()`

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/5370">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/5370/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/5370/pledge.svg">
</picture>
</a>

**Comment by KATT** [comment]
Please fork https://github.com/trpc/examples-next-app-dir and create a reproduction 🙏

**Comment by KATT** [comment]
Hey @dalechyn! :wave:

We appreciate the time you've taken to write this issue.

Unfortunately, we can't assist with issues without a reproduction repository.

Please re-open with a reproduction repository where we can help you further. 🙏 🙏
