### ISSUE TITLE
bug(next): bundle size increase between `10.44.1` -> `10.45.0`

### ISSUE THREAD

**Issue by enricoros** [trpc/trpc#5378]
> @enricoros if you see this ever being downloaded in the browser, please open a new issue
> _Originally posted by @KATT in https://github.com/trpc/trpc/issues/5249#issuecomment-1902621329_

Hello, as per #5249, I'm following up on this. Note that this is possibly something idiosyncratic to my application [https://github.com/enricoros/big-agi](github.com/enricoros/big-agi)

As per @KATT's request, this is what I see in the browser on 10.44.1 vs 10.45.0.

![10.44.1](https://github.com/trpc/trpc/assets/32999/86cd3a25-34a6-45e4-a6f1-8e80fd5c56c6)

![10.45.0](https://github.com/trpc/trpc/assets/32999/9323cfd1-ee1a-425a-a3f4-b30addf04539)

Also note that while there's an increase in the "framework" JS file, there's a smaller reduction in "app", maybe some code gets packaged differently by NextJS.

I haven't seen other complaints about this increase (which is modest, in the order of a couple of small npm modules) so I'm pretty sure it's the way Big-AGI (my app) or NextJS prevent tree-shaking.

However, I'm documenting this as requested. Thanks for a great project!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/5378">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/5378/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/5378/pledge.svg">
</picture>
</a>

**Comment by KATT** [comment]
Thanks for reposting.

This is odd to me, we're following the docs here: https://nextjs.org/docs/app/building-your-application/optimizing/lazy-loading#loading-external-libraries

Potentially Next.js handles node_modules differently than the rest.. Hm.

**Comment by enricoros** [comment]
I wonder if other dependencies are triggering broader code inclusion, or if the nextjs bundler does not understand that the code won't be reached at runtime.

Again, probably this doesn't apply to others and is idiosyncratic of my app and [its package.json](https://github.com/enricoros/big-AGI/blob/main/package.json).

**Comment by KATT** [comment]
Yeah, Hmm, seems legit. Somehow it's included in `framework.js` even if it is lazy-loaded 😿 

https://github.com/vercel/next.js/discussions/49795

**Comment by KATT** [comment]
FWIW culprit is most likely (almost guaranteed) #5201 

@luixo do you have any ideas here? It seems impossible not to get rid of `react-dom/server` from the bundle

- see https://github.com/trpc/examples-next-minimal-starter/pull/3 / https://examples-next-minimal-starter-git-issues-537810441-trpc.vercel.app/
- https://github.com/trpc/examples-next-minimal-starter/pull/2 / https://examples-next-minimal-starter-git-issues-537810450-trpc.vercel.app/

The "framework.js" is 47.2kb vs ~61.4kb

**Comment by KATT** [comment]
I got an ugly hack in #5426 so that the penalty of this lib isn't paid by people who aren't using `ssr: true`

Hopeful that we'll find a better hack.

**Comment by KATT** [comment]
This fix will be added in the [`next`-branch](https://github.com/trpc/trpc/tree/next) of tRPC, meaning it is available in v11 of tRPC. 

It's possible to start using it _today_, have a look at the migration guide for more info: https://trpc.io/docs/migrate-from-v10-to-v11

If you're on `10.x.y`, stick to `10.44.1` if this is causing you grievances

**Comment by KATT** [comment]
If someone does a PR to `main` with the corresponding fix as #5426 we'll merge it, but we won't spend time on doing this for v10 otherwise
