### ISSUE TITLE
bug:  useMutation hook error with latest @tanstack/react-query version

### ISSUE THREAD

**Issue by Virous77** [trpc/trpc#5382]
### Provide environment information

System:
    OS: macOS 14.2.1
    CPU: (8) arm64 Apple M1
    Memory: 78.80 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.8.0 - ~/.nvm/versions/node/v20.8.0/bin/node
    Yarn: 1.22.21 - ~/Desktop/Personal-Projects/Reetesh/frontend/node_modules/.bin/yarn
    npm: 10.1.0 - ~/.nvm/versions/node/v20.8.0/bin/npm
    Watchman: 2023.12.04.00 - /opt/homebrew/bin/watchman
  Browsers:
    Brave Browser: 120.1.61.116
    Chrome: 120.0.6099.234
    Firefox: 121.0.1
    Safari: 17.2.1
  npmPackages:
    @tanstack/react-query: ^5.17.19 => 5.17.19 
    @trpc/client: ^10.45.0 => 10.45.0 
    @trpc/next: ^10.45.0 => 10.45.0 
    @trpc/react-query: ^10.45.0 => 10.45.0 
    @trpc/server: ^10.45.0 => 10.45.0 
    next: 14.1.0 => 14.1.0 
    react: 18 => 18.2.0 
    typescript: 5.3.3 => 5.3.3 

### Describe the bug

![Image 23-01-24 at 9 41 PM](https://github.com/trpc/trpc/assets/101452588/d17f2bdb-9859-4991-8b3e-03ae36ad3486)

I got this error while working with @tanstack/react-query latest version. While its working well with @tanstack/react-query version 4.18.0.

also i checked react-query as standalone so it was working well.

### Link to reproduction

https://stackblitz.com/edit/github-ahnobk?file=next-trpc%2Fapp%2Fapi%2Ftrpc%2F[trpc]%2Froute.ts,next-trpc%2Fpackage.json,next-trpc%2Ftrpc%2Fcontext.ts,next-trpc%2Ftrpc%2Findex.ts,next-trpc%2Ftrpc%2Frouter.ts,next-trpc%2Ftrpc-client%2Fclient.ts,next-trpc%2Ftrpc-client%2Fserver-client.ts,next-trpc%2Flib%2FreactQuery-provider.tsx,next-trpc%2Fapp%2Fpage.tsx,next-trpc%2Fapp%2Flayout.tsx

### To reproduce

Use the latest Next.js version and latest @tanstack/react-query version.

 - Package.json
 
 "@tanstack/react-query": "^5.17.19",
    "@trpc/client": "^10.45.0",
    "@trpc/next": "^10.45.0",
    "@trpc/react-query": "^10.45.0",
    "@trpc/server": "^10.45.0"

###  Additional information

I have added the code in stackblitz fork and folder name is `next-trpc`

```[tasklist]
### Tasks
```

**Comment by KATT** [comment]
V10 does not support RQ 5. Upgrade to v11 https://trpc.io/docs/migrate-from-v10-to-v11
