### ISSUE TITLE
bug: Cursor not reset when invalidating data in an infiniteQuery

### ISSUE THREAD

**Issue by martenbjork** [trpc/trpc#5412]
### Provide environment information

  System:
    OS: macOS 14.0
    CPU: (12) arm64 Apple M2 Max
    Memory: 3.99 GB / 96.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.7.0 - ~/.nvm/versions/node/v20.7.0/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.1.0 - ~/.nvm/versions/node/v20.7.0/bin/npm
    bun: 1.0.7 - ~/.bun/bin/bun
  Browsers:
    Chrome: 118.0.5993.70
    Safari: 17.0

### Describe the bug

When invalidating an infinite query, the cursor of the infinite query is not being reset.

### Expected
- Page 0: Cursor 0
- Page 1: Cursor 1
- Page 2: Cursor 2
- (invalidate)
- Page 0: Cursor 0
- Page 1: Cursor 1
- Page 2: Cursor 2

### Actual
- Page 0: Cursor 0
- Page 1: Cursor 1
- Page 2: Cursor 2
- (invalidate)
- Page 0: Cursor 3
- Page 1: Cursor 4
- Page 2: Cursor 5

The useQuery docs state that:

> When an infinite query becomes stale and needs to be refetched, each group is fetched sequentially, starting from the first one. This ensures that even if the underlying data is mutated, we're not using stale cursors and potentially getting duplicates or skipping records. If an infinite query's results are ever removed from the queryCache, the pagination restarts at the initial state with only the initial group being requested.

Therefore, I would expect that all the previous pages would be fetched using the previous page params.

### Link to reproduction

https://stackblitz.com/edit/github-6aj2fp?file=src%2Fpages%2F_app.tsx,src%2Fpages%2Fapi%2Ftrpc%2F[trpc].ts,src%2Fpages%2Findex.tsx

### To reproduce

- Fetch data using an infinite query
- Invalidate (e.g. `trpc.myData.invalidate()`)
- The data begins to refetch at the last cursor instead of setting the cursor to `undefined`

### Additional information

Maybe this is a misunderstanding on my part, but I thought it worth filing a big / raising this question.

My use case: I need an infinite query and that query needs to be refetched whenever my data is invalidated.

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

**Comment by ramoneres** [comment]
I'm also getting this. 

`    "@tanstack/react-query": "^5.17.19",
    "@trpc/client": "^11.0.0-next-beta.228",
    "@trpc/next": "^11.0.0-next-beta.228",
    "@trpc/react-query": "^11.0.0-next-beta.228",
    "@trpc/server": "^11.0.0-next-beta.228",
`

I upgraded to the @latest. I did not try with earlier versions so i don't know if that's the problem.

**Comment by KATT** [comment]
Ummm.... I don't understand why `getNextPageParam()` is called before they're efetched but it seems like it.. might be an issue in RQ 👀

**Comment by KATT** [comment]
The PR has been merged, you can use it straight away using the `@canary`-tag of tRPC which is deployed automatically from `main`:


Update your `package.json` to use the latest version of tRPC:

```diff
-    "@trpc/client": "^x.y.z",
-    "@trpc/next": "^x.y.z",
-    "@trpc/react-query": "^x.y.z",
-    "@trpc/server": "^x.y.z",
+    "@trpc/client": "canary",
+    "@trpc/next": "canary",
+    "@trpc/react-query": "canary",
+    "@trpc/server": "canary",
```

Then run `npm install` or similar. Reopen the issue if updating to the canary doesn't solve it.

**Comment by KATT** [comment]
This feature has been added in the [`next`-branch](https://github.com/trpc/trpc/tree/next) of tRPC, meaning it is available in v11 of tRPC. 

It's possible to start using it _today_, have a look at the migration guide for more info: https://trpc.io/docs/migrate-from-v10-to-v11

**Comment by KATT** [comment]
Seems to work now: https://stackblitz.com/edit/github-6aj2fp-rfz2g4?file=src%2Fpages%2Fapi%2Ftrpc%2F[trpc].ts
