### ISSUE TITLE
feat: server side calls global error handling

### ISSUE THREAD

**Issue by mateuszaliyev** [trpc/trpc#5413]
### Describe the feature you'd like to request

I would love the ability to globally handle errors that happen when making server side calls with `createCaller()` to avoid repeating the same error handling code in many different places.

### Describe the solution you'd like to see

For example, Next.js exposes a [`notFound()`](https://nextjs.org/docs/app/api-reference/functions/not-found) function that throws `NEXT_NOT_FOUND` error and terminates rendering of the route segment in which it was thrown. I would like to catch every tRPC's `NOT_FOUND` error and call Next.js' `notFound()` instead. It would be great if I could define that custom error handling logic once, when creating a caller or caller factory.

```ts
import { notFound } from "next/navigation";

// t = initTRPC.create({ ... });

const createCaller = t.createCallerFactory(router);

const caller = createCaller(createServerContext, {
  onError: ({ ctx, error, input, path, req, type }) => {
    if (error.code === "NOT_FOUND") notFound();
    throw error; // rethrow other errors to be handled at the procedure call level
  },
});
```

### Describe alternate solutions

I have considered:

- Calling `notFound()` inside of the procedures (tRPC catches the error)
- Using middleware (tRPC catches the error)
- Using [create-t3-app's implementation of the RSC client](https://github.com/t3-oss/create-t3-app/blob/main/cli/template/extras/src/trpc/server.ts) and a custom link instead of the `t.createCallerFactory()` (tRPC catches the error but it could have been due to my lack of understanding how links work)
- Creating a wrapper function that takes a procedure path as an argument, calls the procedure, catches the error and implements error handling logic (requires some more advanced knowledge of TypeScript to preserve type-safety and changes the API to something similar to `callerWrapper((caller) => caller.subrouter.procedure())`)
- Using JavaScript [`Proxy`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy) to intercept every method call and handle the errors (I think it's possible to do but I wasn't able to make it work)
- Defining `handleNotFound()` function and appending `.catch(handleNotFound)` to every procedure call that requires it (this is what I'm using at the moment, but requires code repetition).

### Additional information

Similar discussion but this one is about global error handling on the client side (https://github.com/trpc/trpc/discussions/2036).

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

**Comment by KATT** [comment]
I guess our error-catching to guarantee you always get a TRPCError is working well :)

But yeah, this would be nice to do similarly to how you use [Error Formatting](https://trpc.io/docs/server/error-formatting) to change the HTTP-response, it'd be nice to do something here too.

**Comment by KATT** [comment]
Have you considered _returning_ an error?

**Comment by mateuszaliyev** [comment]
Sorry for a late response, been busy lately.

> Have you considered _returning_ an error?

Yes, I did consider returning an error, but if I understand correctly it would only make sense when the server side caller is the only client consuming the tRPC api. If I returned the error instead of throwing it, the React Query client calling the same procedure would incorrectly assume `status === "success"` instead of `"error"` and some external client using trpc-openapi would receive a status `200 OK` instead of `404 Not Found` (correct me if I am wrong!).

Appending `.catch(handleNotFound)` to every procedure in server side calls works fine for me as of now, I just thought it would be a nice quality of life improvement if I could remove this repeated code :)

**Comment by focux** [comment]
This would be so useful with server components. I'm using Next.js and I'd love to be able to throw/redirect users to the sign in page when using a protected procedure.

This is what I'm trying to do:

```typescript
export const protectedProcedure = t.procedure.use(({ ctx, next }) => {
  if (!ctx.session?.userId || !ctx.session.user) {
    redirect("/sign-in");
  }
  return next({
    ctx: {
      // infers the `session` as non-nullable
      session: {
        ...ctx.session,
        user: ctx.session.user,
      },
    },
  });
});
```

But TRPC is converting the "redirect error" to a TRPCError instance, so the redirect is not working.

**Comment by KATT** [comment]
I'm working on something to allow returning errors over at #5554 which should help server actions

**Comment by focux** [comment]
Yesss! This is the missing piece to make tRPC work seamlessly with server components.

**Comment by KATT** [comment]
cc @focux, feel free to share some DX snippets of what your dream scenario could be like.

(My hunch is that in eg RSC/queries you more often than not would like to propagate errors to the nearest error boundary but in server actions / mutations you'd more often than not want to handle all errors explicitly? (In both cases you'd likely want a server-side onError-callback-thingie))

**Comment by focux** [comment]
Yeah, I think that your hunch is right, I agree with you in both cases—actions and server components, specially in actions, where I think the DX could be improved a lot. Using a sign up action from one of my projects as an example, this is how my dream DX would look:

**Current**
```typescript
export const signUp = async (
  prevState: { error?: string },
  formData: FormData
) => {
  try {
    await api.auth.signUp({
      email: formData.get("email") as string,
      firstName: formData.get("firstName") as string,
      lastName: formData.get("lastName") as string,
      password: formData.get("password") as string,
    });
  } catch (err) {
    if (err?.cause instanceof ZodError) {
      const errorMessage = (err.cause as ZodError).issues?.[0]?.message;
      return { error: errorMessage };
    }

    if (err instanceof TRPCError && err.code !== "INTERNAL_SERVER_ERROR") {
      return { error: err.message };
    }

    return {
      error: "Something went wrong. Contact support if the error persists.",
    };
  }

  redirect("/");
};
```

**Dream Scenario 🙌** 
```typescript
// i'd expect errors from zod and tRPC error instances to be in the error property and also being able to format it
// using an  `errorFormatted` thing but i'd also expect `notFound()` and `redirect()` not to be catch inside the error
// but instead thrown so it can be handled by next.js
const { data, error } = await api.auth.signUp({
    email: formData.get("email") as string,
    firstName: formData.get("firstName") as string,
    lastName: formData.get("lastName") as string,
    password: formData.get("password") as string,
  });

  if (error && error.code !== 'INTERNAL_SERVER_ERROR') {
    return { error: error.message };
  }

  redirect("/");
```

**Comment by focux** [comment]
Another exploration:

```typescript
 const data = await api.auth
    .signUp({
      email: formData.get("email") as string,
      firstName: formData.get("firstName") as string,
      lastName: formData.get("lastName") as string,
      password: formData.get("password") as string,
    })
    .onSuccess((data) => {
      // do something
      redirect("/");
    })
    .catchError("ZodError", (error) => {
      return { error: err.cause.issues?.[0]?.message };
    })
    .catchError("TRPCError", (error) => {
      return { error: error.message };
    })
    .catchAll((error) => {
      return {
        error: "Something went wrong. Contact support if the error persists.",
      };
    });
```

**Comment by KATT** [comment]
I should really have started a separate discussion about this, this is quite off-topic from the original issue.

..... but, anyway, here's what we're toying with enabling:

```ts
// trpc.ts

// [.... initTRPC etc]

export const authedProcedure = publicProcedure.use((opts) => {
  if (!opts.ctx.session) {
    // 👀 *returning* errors makes them inferrable and returned rather than just thrown
    return trpcError({
      code: "UNAUTHORIZED",
      foo: "bar" as const, // <-- any extra props can be inferred too
    });
  }
  return opts.next({
    ctx: {
      session: opts.ctx.session,
    },
  });
});

export const createAction = experimental_createServerActionHandler(t, {
  async createContext() {
    const session = await auth();

    return {
      session,
    };
  },
  onError(opts): void {
    // .... generic server-side handling of errors
  },
});
```

```ts
// /post/add/_action.ts
import { authedProcedure, createAction } from "~/utils/trpc";

export const addPost = createAction(
  authedProcedure
    .input(
      z.object({
        title: z.string(),
        text: z.string(),
      })
    )
    .mutation((opts) => {
      const post = await db.post.create({
        data: opts.input,
      });

      redirect(`/post/${post.slug}`);
    })
);
```

```tsx
// /post/add/page.tsx
"use client";

import { addPost } from "./_action";

export default function Page() {
  const [state, formAction] = useFormState(addPost, {});
  //     ^^^^^ infers return of mutation AND errors from either input validation or any `return trpcError({...})`

  state?.error?.code;
  //              ^? undefined | "UNAUTHORIZED" | "BAD_REQUEST"

  if (state?.error?.code === "UNAUTHORIZED") {
    state.error.foo;
    //           ^? "bar"
  }
  return (
    <form action={formAction}>
      <div>
        <label htmlFor="text">Title</label>
        <input type="text" name="title" initialValue={state?.input?.text} />
        {!state?.fieldErrors?.title && (
          <div>{state.errors.fieldErrors.title}</div>
        )}
      </div>

      <div>
        <label htmlFor="text">Title</label>
        <input type="text" name="title" initialValue={state?.input?.text} />
        {!state?.fieldErrors?.title && (
          <div>{state.errors.fieldErrors.title}</div>
        )}
      </div>

      {state?.error?.code === "UNAUTHORIZED" && <div></div>}
      <SubmitButton>Add post</SubmitButton>
    </form>
  );
}

function SubmitButton(props: { children: string }) {
  const { pending } = useFormStatus();
  return <button disabled={pending}>{props.children}</button>;
}
```

**Comment by focux** [comment]
Oooh that's even better. I really like it!

 Also, are you gonna be able to use that action inside client components as well? You know that there's the limitation that to use an action in client components you need to put the action in a file with an `user server` directive at the top of the file.
