### ISSUE TITLE
bug: `Cannot assign to read-only property 'path'` whilst using `useMutation` hook within React Native components

### ISSUE THREAD

**Issue by LeeBrooks3** [trpc/trpc#5429]
### Provide environment information

  System:
    OS: macOS 14.1
    CPU: (12) arm64 Apple M3 Pro
    Memory: 94.47 MB / 18.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.10.0 - ~/.nvm/versions/node/v20.10.0/bin/node
    Yarn: 1.22.21 - ~/.nvm/versions/node/v20.10.0/bin/yarn
    npm: 10.2.3 - ~/.nvm/versions/node/v20.10.0/bin/npm
    Watchman: 2023.12.04.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 121.0.6167.139
    Safari: 17.1
  npmPackages:
    @tanstack/react-query: ^4.36.1 => 4.36.1 
    @trpc/client: ^10.45.0 => 10.45.0 
    @trpc/react-query: ^10.45.0 => 10.45.0 
    @trpc/server: ^10.45.0 => 10.45.0 
    react: 18.2.0 => 18.2.0 
    typescript: ^5.1.3 => 5.3.3 
    
    react-native: 0.73.2

### Describe the bug

Hello!

See [this line](https://github.com/trpc/trpc/blob/d61ece329f271b69c16a6a262c1979259b7fd366/packages/react-query/src/internals/useHookResult.ts#L16).

I've followed all these [steps](https://trpc.io/docs/client/react/setup) to setup the tRPC + React Query integration within my React Native application. When attempting to use the `useMutation` hook within a component I'm receiving the following error:
```
Cannot assign to read-only property 'path'
```
_Note: using the `useQuery` hook works fine._

It's been killing me all day! I'm trying to resolve why the `ref` being passed through is immutable vs mutable but I've not been having much luck.

I wonder if there's any ideas that spring to mind on your end or whether a change could be required to safely handle this scenario?

For now I've commented out the line to continue my local development and all seems to work fine without it.

Really appreciate the help!

Cheers,
Lee

### Link to reproduction

https://github.com/LeeBrooks3/trpc-react-native

### To reproduce

I've been unable to reproduce the issue in isolation from my main product monorepo (despite using the same versions of everything), but I've provided a link to the experimental repository anyway - and I continue to investigate.

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/5429">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/5429/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/5429/pledge.svg">
</picture>
</a>

**Comment by KATT** [comment]
Hmm, doesn't look like a trpc bug to me (even if it would be better written as a useMemo) - are you using some Object.seal or Object.freeze?

BTW, upgrade to v11, we likely won't do any non critical fixes to v11

**Comment by KATT** [comment]
Not on my laptop, but if you do a PR to `main` I'll approve and a v10 canary release will be triggered automatically 

```ts
export function useHookResult(
  value: TRPCHookResult['trpc'],
): TRPCHookResult['trpc'] {
  const { path } = value;
  return useMemo(() => ({ path }), [path])
}
```

Like the above but with correct linting

**Comment by KATT** [comment]
#5433 has been merged, you can use it straight away using the `@canary`-tag of tRPC which is deployed automatically from `main`:


Update your `package.json` to use the latest version of tRPC:

```diff
-    "@trpc/client": "^x.y.z",
-    "@trpc/next": "^x.y.z",
-    "@trpc/react-query": "^x.y.z",
-    "@trpc/server": "^x.y.z",
+    "@trpc/client": "canary",
+    "@trpc/next": "canary",
+    "@trpc/react-query": "canary",
+    "@trpc/server": "canary",
```

Then run `npm install` or similar. Close the issue if updating to the canary solves it 🙏

**Comment by LeeBrooks3** [comment]
Hi @KATT, thank you for looking into this so swiftly!

I can confirm that the issue has been resolved by these changes and this canary release 🙌

I'll be sure to upgrade to v11 once the issue is resolved on that version too, I only dropped down to v10 in hopes that it would fix the problem.

Cheers again, legend ⭐️
