### ISSUE TITLE
bug: Argument type () => any[] is not assignable to parameter type ProcedureResolver<unknown, unknown, unknown, unknown, unknown, unknown> 

### ISSUE THREAD

**Issue by fendyk** [trpc/trpc#5437]
### Provide environment information

  System:
    OS: Windows 11 10.0.22631
    CPU: (24) x64 13th Gen Intel(R) Core(TM) i7-13700K
    Memory: 11.69 GB / 31.77 GB
  Binaries:
    Node: 20.10.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.2.3 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.15.1 - ~\AppData\Local\pnpm\pnpm.EXE
  Browsers:
    Edge: Chromium (121.0.2277.98)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    typescript: ^5.3.3 => 5.3.3

### Describe the bug

When I clone `create-t3-turbo` from https://github.com/t3-oss/create-t3-turbo, I receive a warning from my editor (Jetbrains Ultimate Intelij) :

```
Argument type () => any[] is not assignable to parameter type ProcedureResolver<unknown, unknown, unknown, unknown, unknown, unknown> 
```

### Link to reproduction

https://github.com/t3-oss/create-t3-turbo

### To reproduce

- use Jetbrains Intelij Ultimate (2023.3.2)
- clone repository
- run `pnpm i`
- locate the `packages/api` folder
- open `src/router/auth.ts`
- change it into something minimal:
```tsx
import { createTRPCRouter, publicProcedure } from "../trpc";

export const authRouter = createTRPCRouter({
  getSomething: publicProcedure.query(( ) => {
    return [];
  }),
});
```

![image](https://github.com/trpc/trpc/assets/56702979/29ffcb51-4981-4a49-bd86-0db6f5634607)

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/5437">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/5437/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/5437/pledge.svg">
</picture>
</a>

**Comment by KATT** [comment]
Umm, this sounds like either a bug in JetBrains?

**Comment by fendyk** [comment]
> Umm, this sounds like a bug in JetBrains' Intellij?

Fixed the issue - turns out my `node_modules` folder was excluded in the project settings, so it couldn't recognize the typings. All good now!
