### ISSUE TITLE
bug: Getting error using trpc with Cloudflare D1

### ISSUE THREAD

**Issue by maitreya00** [trpc/trpc#5439]
### Provide environment information

  System:
    OS: Linux 5.15 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (32) x64 AMD Ryzen 9 7950X3D 16-Core Processor
    Memory: 53.80 GB / 61.96 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 20.11.0 - ~/.nvm/versions/node/v20.11.0/bin/node
    Yarn: 1.22.21 - ~/.nvm/versions/node/v20.11.0/bin/yarn
    npm: 10.2.4 - ~/.nvm/versions/node/v20.11.0/bin/npm
    pnpm: 8.15.1 - ~/.nvm/versions/node/v20.11.0/bin/pnpm
  npmPackages:
    @tanstack/react-query: ^4.18.0 => 4.36.1
    @trpc/client: ^10.45.0 => 10.45.0
    @trpc/next: ^10.45.0 => 10.45.0
    @trpc/react-query: ^10.45.0 => 10.45.0
    @trpc/server: ^10.45.0 => 10.45.0
    next: ^14.1.0 => 14.1.0
    react: 18.2.0 => 18.2.0
    typescript: ^5.3.3 => 5.3.3

### Describe the bug

I'm using Cloudflare's D1 Sqlite database with drizzle(t3 stack). 

```
  getLatest: publicProcedure.query(({ ctx }) => {
    return ctx.db.query.posts.findFirst({
      orderBy: (posts, { desc }) => [desc(posts.createdAt)],
    });
  }),
```

Running this query I get the following error:
```
 TRPCClientError: Cannot read properties of undefined (reading 'prepare')
      at TRPCClientError.from 
```

However I'm able to read/write to my db using the regular nextjs route:
```
export async function GET(_request: NextRequest) {
  const time: number = Date.now();

  await db
    .insert(posts)
    .values({ name: "New post..." })
    .returning({ id: posts.id });

  const allPosts = await db.select().from(posts);

  return new Response("All posts: " + JSON.stringify(allPosts) + " " + time);
}
```

Any idea why the db is not working inside trpc? 

Thanks

### Link to reproduction

https://github.com/maitreya00/t3-app-d1

### To reproduce

This is bootstraped t3 app with only change to use D1 database instead of Sqlite.

Access the homepage, trpc is queried returning the error.

The route `/api/add-post` which inserts a row and fetches the `post` table works.

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/5439">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/5439/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/5439/pledge.svg">
</picture>
</a>

**Comment by Nick-Lucas** [comment]
This is definitely not going to be a bug with tRPC, there's something wrong in your drizzle setup

I need to close because this isn't an 'issue' and appears to be drizzle at fault. Did find this in some brief googling though unanswered: https://www.answeroverflow.com/m/1173460518019813396

**Comment by maitreya00** [comment]
hey @Nick-Lucas 

> This is definitely not going to be a bug with tRPC, there's something wrong in your drizzle setup
> 
> I need to close because this isn't an 'issue' and appears to be drizzle at fault. Did find this in some brief googling though: https://www.answeroverflow.com/m/1173460518019813396

thanks for the response.

I'm using the same drizzle query in my regular nextjs api route? Any idea why this error only occurs inside trpc?

**Comment by Nick-Lucas** [comment]
Feel free to bring it to [discord](https://discord.com/channels/867764511159091230/1020132255567454310) and someone may be able to assist, but very likely there's some config different between the two runtime environments, some console logging might be worthwhile

Afraid I don't have any experience with D1+drizzle and limited experience mixing wrangler with nextjs though
