### ISSUE TITLE
Transformers at server level

### ISSUE THREAD

**Issue by delaneyj** [trpc/trpc#545]
https://trpc.io/docs/data-transformers show transformer at the client and in next handlers.  Would it be possible to match the client interface ala

```ts
const appRouter = router<Context>({
  transformer:superjson
})
```
so it working without being tied to Next.js

**Comment by KATT** [comment]
There was a reason for this design that I have now forgotten.... wanna take a stab at it? I'd be happy to do the change.

Indeed this would be nicer... could be done as part of next major, #532 also has breaking changes.

**Comment by KATT** [comment]
_If_ you do, start off with a fork of `feature/refactor-rpc`
