### ISSUE TITLE
docs: valibot +  @decs/typeschema  is unnecessary

### ISSUE THREAD

**Issue by FlatMapIO** [trpc/trpc#5460]
### Area of Improvement

When users use valibot, the tRPC documentation guides them to use `@decs/typeschema` for wrap, but in reality, this is redundant. The typeschema library is very complex, and if the project is built with the goal of creating a cloudflare worker, it will also cause a series of problems. I think the typeschema should be removed from the documentation, and instead, the user should be told to provide a validate function:

```tsx
// valibot-trpc.ts
import type { BaseSchema } from 'valibot'
import * as v from 'valibot'

export const validate = <T extends BaseSchema>(schema: T) => 
  (input: unknown) => v.parse(schema, input)

// router.ts
protectedProcedure.input( validate(v.object( {} ) ).query( ( { input } ) => { ... } )
```

### Additional information

<img width="1239" alt="image" src="https://github.com/trpc/trpc/assets/1720349/53fe9b5c-fa7e-4486-ba04-c0d62d9ace94">

### 👨‍👧‍👦 Contributing

- [x] 🙋‍♂️ Yes, I'd be down to file a PR implementing the suggested changes!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/5460">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/5460/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/5460/pledge.svg">
</picture>
</a>

**Comment by juliusmarminge** [comment]
i don't think your solution works with input_in / input_out i.e. when the input is transformed. that's where typeschema comes in to get the proper types?

**Comment by juliusmarminge** [comment]
but i don't really agree with some decisions in typeschema and even though they've done a fantastic job it's very prone to errors at any time when some bundler doesn't adhere to some norms...

if there's a small wrapper we can document that will work with transformed inputs i'd be inclined to recommend that

**Comment by juliusmarminge** [comment]
Here you can see the issue https://stackblitz.com/edit/github-mjs98b?file=server%2Findex.ts

**Comment by FlatMapIO** [comment]
Thank you for your response. Frankly, I hadn’t considered this issue. As a library author, it’s indeed necessary to cover all aspects, but if it causes build problems, as a user, I would rather refrain from my additional requirements. Perhaps we could mention this in the documentation and let the user decide for themselves.

**Comment by KATT** [comment]
I'm happy typeschema exists, we couldn't find a method to nicely wrap every possible lib out there.

Will close this for now, but would love contributions to our parser to make typeschema redundant

**Comment by KATT** [comment]
Also thankful if you wanna edit the docs to help a future person in your position 🙏
