### ISSUE TITLE
bug: Slashes in RPC methods breaks tRPC

### ISSUE THREAD

**Issue by isaac-mcfadyen** [trpc/trpc#5469]
### Provide environment information

```
  System:
    OS: macOS 14.3
    CPU: (10) arm64 Apple M1 Max
    Memory: 751.97 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.9.0 - ~/Library/Caches/fnm_multishells/41364_1707487006902/bin/node
    npm: 10.1.0 - ~/Library/Caches/fnm_multishells/41364_1707487006902/bin/npm
    pnpm: 8.14.1 - ~/Library/Caches/fnm_multishells/41364_1707487006902/bin/pnpm
    bun: 1.0.24 - ~/.bun/bin/bun
  Browsers:
    Chrome: 121.0.6167.160
    Safari: 17.3
  npmPackages:
    @trpc/server: 10.45.1 => 10.45.1 
    typescript: ^5.3.3 => 5.3.3 
```

### Describe the bug

When using a tRPC RPC name with a slash in the url, tRPC doesn't URL-encode the slash and so a 404 error is thrown.

For example, with a tRPC RPC name of `libraries/get`, then the following URL is used, which 404s:
`http://127.0.0.1:8080/trpc/libraries/get?batch=1&input=<removed>`

You can test this by manually hitting the URL (getting a 404). However, if you replace the slash with the proper URL-encoded slash (`%20`) so `http://127.0.0.1:8080/trpc/libraries%20get?batch=1&input=<removed>` then it works.

### Link to reproduction

https://stackblitz.com/edit/github-gkgxsr?file=src%2Fpages%2Fapi%2Ftrpc%2F%5Btrpc%5D.ts

### To reproduce

1. Create an RPC with a name that includes a forward slash. E.x. `libraries/get`
2. Using the regular tRPC HTTP server and client (or Fastify, reproducible with both) send the RPC.
3. Observe that an error is generated because the request returns a 404 error code. You can also manually hit the URL and observe that a 404 is generated.

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/5469">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/5469/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/5469/pledge.svg">
</picture>
</a>

**Comment by KATT** [comment]
Rename your api handler from `[trpc].ts` to `[...trpc].ts` and it should work. Won't work with a batch link though.

**Comment by KATT** [comment]
Reopen if it doesn't work.

(or simply don't use slashes since we don't encourage the usage of that)

**Comment by isaac-mcfadyen** [comment]
> Rename your api handler from `[trpc].ts` to `[...trpc].ts` and it should work. Might not work with a batch link though.

Works on the Next adapter, thank you!

Wondering if this should be changed on the Fastify adapter as well, given that you don't actually specify routes there (it's handled by the adapter for you)?

**Comment by KATT** [comment]
Should be easy. You can look at the source of both  
and try to make a PR. I won't spend time on this myself
