### ISSUE TITLE
feat: Server-side batching

### ISSUE THREAD

**Issue by luixo** [trpc/trpc#5470]
### Describe the feature you'd like to request

Hello,
In my project I have a need to fetch multiple queries (with the same handler).
tRPC does a great job of batching the request client-side.
Is server-side part of the batching out of scope? Or is there a chance helpers could be included in the package?
I found [single discord discussion](https://discord-questions.trpc.io/m/1116448153017782443) on that topic, but with no examples. I hope my example will guide other tRPC users in case helpers will never end up in the lib.

### Describe the solution you'd like to see

Say, I had a handler to fetch a user:
```ts
// server/handlers/user.ts
import type { Context } from "@server/trpc";

const getUser = async (cxt: Context, id: string) => {
  // get user from DB
  return user;
}

const remapUser = (rawUser: Awaited<ReturnType<typeof getUser>>) => {
  // some remapping, may raise a TRPCServerError!
}

const procedure = procedure
  .input(z.string())
  .query(({ input: id, ctx }) => getUser(ctx, id));
```

Now what my helpers look like:
```ts
// common/utils.ts
export const createPromise = <R, E = unknown>() => {
  let resolve: ((result: R) => void) | undefined;
  let reject: ((reason?: E) => void) | undefined;
  const promise = new Promise<R>((resolveFn, rejectFn) => {
    resolve = resolveFn;
    reject = rejectFn;
  });
  return { resolve: resolve!, reject: reject!, wait: () => promise };
};
export type ControlledPromise<R = void, E = unknown> = ReturnType<
  typeof createPromise<R, E>
>;
```

```ts
// common/context.ts
import type { ProcedureCall } from "@trpc/server/http";
import type { NodeHTTPCreateContextFnOptions } from "@trpc/server/dist/adapters/node-http";

export type Context = {
  batch?: {
    id: string;
    calls: ProcedureCall[];
  };
  // the rest of the context
};

export const createContext = (
  opts: NodeHTTPCreateContextFnOptions<unknown, unknown>
): Context => ({
  batch: opts.info.isBatchCall ? { id: Math.random().toString(), calls: opts.info.calls } : undefined,
  // the rest of the context
});
```

```ts
// server/batch.ts
import type { ControlledPromise } from "@common/utils";
import { createPromise } from "@common/utils";
import type { Context } from "@server/trpc";

type BatchedObject<I, O> = {
  input: I;
  promise: ControlledPromise<O>;
};

export const queueCallFactory = <C extends UnauthorizedContext, I, O, M>(
  getData: (ctx: C, inputs: I[]) => Promise<M>,
  getSingleValue: (ctx: C, input: I, values: M) => Promise<O>,
) => {
  const batches: Record<string, BatchedObject<I, O>[]> = {};
  const runCalls = async (
    ctx: C,
    batchedObjects: BatchedObject<I, O>[],
  ): Promise<void> => {
    try {
      const inputs = batchedObjects.map(({ input }) => input);
      const results = await getData(ctx, inputs);
      batchedObjects.forEach(async ({ promise, input }) => {
        try {
          const result = await getSingleValue(ctx, input, results);
          promise.resolve(result);
        } catch (e) {
          promise.reject(e);
        }
      });
    } catch (e) {
      batchedObjects.forEach(({ promise }) => promise.reject(e));
    }
  };
  return async (ctx: C, input: I, path: string): Promise<O> => {
    if (!ctx.batch) {
      return getSingleValue(ctx, input, await getData(ctx, [input]));
    }
    const { batch } = ctx;
    if (!batches[batch.id]) {
      batches[batch.id] = [];
    }
    const promise = createPromise<O>();
    batches[batch.id]!.push({ promise, input });
    if (
      batches[batch.id]!.length ===
      batch.calls.filter((call) => call.path === path).length
    ) {
      void runCalls(ctx, batches[batch.id]!).then(() => {
        delete batches[batch.id];
      });
    }
    return promise.wait();
  };
};
```

With helper usage:
```ts
// server/handlers/user.ts
import type { Context } from "@server/trpc";
import { queueCallFactory } from "@server/batch";

const getUsers = async (cxt: Context, ids: string[]) => {
  // get users from DB
  return users;
}

const remapUser = (rawUser: Awaited<ReturnType<typeof getUsers>>[number]) => {
  // some remapping, may raise a TRPCServerError!
}

const queueUser = queueCallFactory<
  Context,
  string,
  ReturnType<typeof remapUser>,
  Awaited<ReturnType<typeof getUsers>>
>(
  getUsers,
  async (ctx, id, users) => {
    const user = users.find((user) => user.id === id);
    if (!user) {
      // throw an error
    }
    return remapUser(user);
  },
);

const procedure = procedure
  .input(z.string())
  .query(({ input: id, ctx, path }) => queueUser(ctx, id, path));
```

### Describe alternate solutions

Keep userland implementation without designated helpers from tRPC.

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/5470">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/5470/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/5470/pledge.svg">
</picture>
</a>

**Comment by KATT** [comment]
Seems like what you're looking for is a [dataloader](https://github.com/graphql/dataloader), you can initialize one for each lower level thing as part of your request context to dedupe and parallelise calls like this - that's what I used to do in graphql. 

If it's the same procedure being called in trpc itself, you can make a custom link to dedupe

**Comment by KATT** [comment]
We have implemented our own dataloader pattern too as part of tRPC that supports batching, but it's not really general purpose currently

**Comment by luixo** [comment]
Thanks for the tip, apparently I implemented a simple dataloader :)

How do you suggest using it in tRPC?
Adding to a procedure `query` function will not work as there will be multiple of those.
Adding a bunch of dataloaders (for users, for posts etc.) to the context seems like an overkill as it will create a lot of objects while using them sparsely and keeping them away from the procedures.
Making dataloader an optional property in a context which then will be filled in a procedure seems dirty.

Did you find a clean way to do that?

**Comment by luixo** [comment]
Just found a discussion on that happened about 2 years ago: https://github.com/trpc/trpc/discussions/1287

**Comment by KATT** [comment]
Yup, I think that covers it. Create it somewhere tied to the request - you can do a lazy getter or some async storage thing that creates them lazily if you wanna be fancy.
