### ISSUE TITLE
feat: Type helpers to infer the context type (and maybe also the validator type) from a specific procedure/router

### ISSUE THREAD

**Issue by dBianchii** [trpc/trpc#5473]
### Describe the feature you'd like to request

Today we have great type helpers like `inferRouterInputs` and `inferRouterOutputs`.
Would be good to be able to do the same to get the `context` (ctx) type of a Router (for example `inferRouterContext`), and maybe also of a specific procedure.

In addition, I would suggest that maybe we can also provide a helper to get the type of a validator/parser from a router.(`inferRouterParser`) or something like this

### Describe the solution you'd like to see

`inferRouterContext` is something that already exists. However, I believe it is not possible to get a 'leaf' router like we can with `inferRouterInputs`. 

I can't seem to be able to get a specific router endpoint's context:
```ts
import type { inferRouterContext } from "@trpc/server";

type RootCtx = inferRouterContext<AppRouter> // <-- The root AppRouter type works and gets us the context of a the context root
type PostByIdCtx = inferRouterContext<AppRouter>['post']['byId'] // <-- This will not work. inferRouterContext gets the immediate context of the AppRouter only
```

### Describe alternate solutions

I don't know how to get the type from a router, however, as described by @KATT  here: https://github.com/trpc/trpc/discussions/5472#discussioncomment-8442432, you can do something like this to get the context of a specific procedure:

```ts
type ProtectedProcedure = typeof protectedProcedure 
type ProtectedProcedureOptions = Parameters<Parameters<ProtectedProcedure['query']>[0]>[0]
type ProtectedProcedureContext = ProtectedProcedureOptions['ctx']
```

### Additional information

I see that cal.com's codebase for example has a lot of trpc handlers that have the context manually defined, and not infered from the router/procedure directly. Just look at all .handler files they have: https://github.com/calcom/cal.com/blob/main/packages/trpc/server/routers/loggedInViewer/appById.handler.ts#L9).
This becomes hard to maintain if the context of a router/procedure is extended.

I also _suggest_ in this feature request we add a way to get type of the entire Options object. (including the Validator/Parser type). The main reason for it would be to simplify a lot the ability to create handlers like cal.com is doing.

I'd be down to file a PR implementing this feature, but tbh I have little experience with contributing for libraries. I might give it a shot.

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/5473">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/5473/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/5473/pledge.svg">
</picture>
</a>

**Comment by KATT** [comment]
Doing it as a router helper would cause a circular dependency when you use it so it has to be a router helper based on a "base procedure" / procedure builder.
