### ISSUE TITLE
NextJS App router specific documentation.

### ISSUE THREAD

**Issue by alexander-densley** [trpc/trpc#5495]
### Area of Improvement

I would like to see specific app router documentation in the nextjs section

### Link to related docs

https://trpc.io/docs/client/nextjs/setup

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing the suggested changes!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/5495">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/5495/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/5495/pledge.svg">
</picture>
</a>

**Comment by graup** [comment]
Possible duplicate: #5277
