### ISSUE TITLE
@trpc/react: Recommended for non-Next.js React projects

### ISSUE THREAD

**Issue by akomm** [trpc/trpc#551]
From this: https://trpc.io/docs/quickstart#installation
I don't get why it is recommended for **non** next.js react apps?

In "using with next.js" you go straight ahead and use it:
https://trpc.io/docs/nextjs#add-trpc-to-existing-nextjs-project

But there is no usage shown without it. 

I guess I could use SSR and not need hooks in that case or similar, but its kind of confusing to start with, when things contradict. :)

**Comment by KATT** [comment]
Yeah... the point I'm trying to make is that it works on your existing CRA projects or whatnot...

**Comment by KATT** [comment]
How would you want the docs to be structured?

**Comment by akomm** [comment]
I don't know yet, because I'v just started analyzing the library for my use. I like the idea, but reading it I was not quite sure why you wrote that and even after reading another 2 times still not. I just have vague guesses and for that to confirm I need to make tests and checks outside of "getting started" to figure out.

Its just usually people don't write stuff just for fun, so this point kind of sticks on me currently. What I currently do is, I just don't install the @trpc/react and see how else I can get data and wheather I need @trpc/react at the end or not. I mean getting started should not explain everything, but I think if you mention something, you should kind of explain it, or leave it out or it just confuses :D

**Comment by delaneyj** [comment]
@akomm I'm using fastify and vue so I can tell you you don't need react or next, but you miss out on some of the work that has been done so far.  In its current state its really geared towards @KATT use case.  With further pestering its becoming more generic. :smile:

**Comment by akomm** [comment]
@delaneyj 
I think we have an missunderstanding.
I use next & react. 

The "getting started" tells, that @trpc/react is recommended for **non** next.js usage, but then goes on using it for next.js usage example.

**Comment by KATT** [comment]
@akomm - if you're using next.js, I think it's easiest to start with the [example projects](https://trpc.io/docs/example-apps)

**Comment by akomm** [comment]
@katt thanks, it is useful, but it does the same thing: it uses @trpc/react :) I did check those already. So the confusion still remains.

**Comment by KATT** [comment]
Oh I see, well, with nextjs you use **both** `@trpc/react` & `@trpc/next` - the latter depends on the former

**Comment by akomm** [comment]
Okay thanks

**Comment by akomm** [comment]
On my side this is now clear. I still think its confusing for beginners maybe. But if you don't want to bother with it you can close.
