### ISSUE TITLE
feat(react-query): Pass useInfiniteQuery direction param to procedure input

### ISSUE THREAD

**Issue by brian-bourdon** [trpc/trpc#5514]
### Describe the feature you'd like to request

Since tanstack query v5, useInfiniteQuery passes the direction in addition to pageParam to QueryFunctionContext (https://tanstack.com/query/v5/docs/framework/react/guides/query-functions#queryfunctioncontext).

This is very useful, probably essential for bi-directional infinite queries, as it provides the information on which direction to fetch. Currently trpc v11 only passes the pageParam as a cursor in the procedure input.

### Describe the solution you'd like to see

direction passed in addition to pageParam, which is already passed to the procedure input as the cursor.

### Describe alternate solutions

I don't really see any other good solution.

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/5514">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/5514/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/5514/pledge.svg">
</picture>
</a>

**Comment by juliusmarminge** [comment]
Good suggestion, I don't see a reason not to do this so feel free to submit a PR!
