### ISSUE TITLE
bug: create createTRPCProxyClient fail

### ISSUE THREAD

**Issue by githublaohu** [trpc/trpc#5517]
### Provide environment information

node: v20.10.0
jest: 29.5.12
trpc: 10.43.6
`
/nodejs/bin/node --require /webstorm/WebStorm-232.10227.9/plugins/javascript-impl/helpers/jest-intellij/lib/jest-intellij-stdin-fix.js /next/node_modules/jest/bin/jest.js --runInBand --testTimeout=7200000 --colors --reporters /webstorm/WebStorm-232.10227.9/plugins/javascript-impl/helpers/jest-intellij/lib/jest-intellij-reporter.js --verbose --testNamePattern=^test_trpc$ --runTestsByPath /next/__test__/test.ts
`

### Describe the bug

error
`
Waiting for the debugger to disconnect...

  ● Test suite failed to run

    __test__/server/test.ts:6:45 - error TS2345: Argument of type '{ links: TRPCLink<CreateRouterInner<RootConfig<{ ctx: { headers: Headers; session: Session | { user: { id: string; name: string; email: string; }; } | null; blob: S3Provider; db: PrismaClient<Prisma.PrismaClientOptions, never, DefaultArgs>; }; meta: object; errorShape: { ...; }; transformer: typeof SuperJSON; }>, { ...' is not assignable to parameter of type 'CreateTRPCClientOptions<CreateRouterInner<RootConfig<{ ctx: { headers: Headers; session: Session | { user: { id: string; name: string; email: string; }; } | null; blob: S3Provider; db: PrismaClient<PrismaClientOptions, never, DefaultArgs>; }; meta: object; errorShape: { ...; }; transformer: typeof SuperJSON; }>, { ....'.
      Property 'transformer' is missing in type '{ links: TRPCLink<CreateRouterInner<RootConfig<{ ctx: { headers: Headers; session: Session | { user: { id: string; name: string; email: string; }; } | null; blob: S3Provider; db: PrismaClient<Prisma.PrismaClientOptions, never, DefaultArgs>; }; meta: object; errorShape: { ...; }; transformer: typeof SuperJSON; }>, { ...' but required in type '{ transformer: typeof SuperJSON; }'.

      6 let trpc = createTRPCProxyClient<AppRouter>({
                                                    ~
      7     links: [
        ~~~~~~~~~~~~
    ... 
     17     ],
        ~~~~~~
     18 });
        ~

      node_modules/.pnpm/@trpc+client@10.45.1_@trpc+server@10.45.1/node_modules/@trpc/client/dist/internals/TRPCUntypedClient.d.ts:20:5
        20     transformer: TRouter['_def']['_config']['transformer'] extends CombinedDataTransformer ? DataTransformerOptions : TRouter['_def']['_config']['transformer'];
               ~~~~~~~~~~~
        'transformer' is declared here.
`

### Link to reproduction

https://stackblitz.com/edit/github-ub5pbt?file=__test__%2Ftest.ts,jest.config.ts,src%2Fserver%2Fapi%2Fuser.ts,src%2Fserver%2Fapi%2Froot.ts

### To reproduce

code
`
import { createTRPCProxyClient, httpBatchLink } from '@trpc/client';
import { AppRouter } from "../../src/server/api/root";


const trpc = createTRPCProxyClient<AppRouter>({
    links: [
        httpBatchLink({
            url: 'http://localhost:3000/api/trpc',
            fetch(url, options) {
                return fetch(url, {
                    ...options,
                    credentials: "include",
                });
            },
        }),
    ],
});

console.log("1");
it("test_trpc",() => {
    const users =  trpc.user.getCurrent();
    console.log('Users:', users);
});
`

### Additional information

_No response_

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

<!-- POLAR PLEDGE BADGE START -->
## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/5517">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/5517/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/5517/pledge.svg">
</picture>
</a>
<!-- POLAR PLEDGE BADGE END -->

**Comment by KATT** [comment]
Unfortunately, we don't have the capacity to assist with issues without a reproduction - your reproduction has a bunch of unrelated issues - and this issue does not seem to be a bug and related to tRPC itself. Might be that you're just missing a transformer, I don't know.

For effective assistance, reopening the issue with a reproduction repository would be immensely helpful. Alternatively, you can try to get help on our [Discord](https://trpc.io/discord) or in [GitHub Discussions](https://github.com/trpc/trpc/discussions).

Thank you for your understanding and cooperation!
