### ISSUE TITLE
feat: Explicit Content-Type checks

### ISSUE THREAD

**Issue by BeBoRE** [trpc/trpc#5522]
### Describe the feature you'd like to request

Forms can easily be used to execute CSRF attacks, since they are not blocked by CORS. Endpoints that are especially vulnerable are endpoints that expect no input. Endpoints that do require input and only accept `application/json` as Content-Type header are safe from form based CSRF attacks, since forms cannot send `application/json`.

### Describe the solution you'd like to see

Explicit checks on the Content-Type header. The Fetch / Edge runtime adapters already check the Content-Type header, but from my testing the standalone, express, fastify and Next.JS adapters all do not check the Content-Type header, leaving them more vulnerable to form based CSRF attacks.

I have prepared [a little demo](https://github.com/BeBoRE/trpc-csrf-test) to showcase how the vulnerability works.

### Describe alternate solutions

For now I have just added a custom Content-Type check to my tRPC handler endpoint:
```ts
if (
  req.body &&
  !req.headers['content-type']?.startsWith('application/json')
  ) {
  res
    .status(400)
    .json({ code: 'BAD_REQUEST', message: 'Invalid Content-Type' });
  return undefined;
}
```

I have seen that there are plans to allow for more content-types to be accepted, please do not allow `application/x-www-form-urlencoded`, `multipart/form-data` and `text/plain` by default.

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/5522">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/5522/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/5522/pledge.svg">
</picture>
</a>

**Comment by KATT** [comment]
Good idea, we can add this for v11!

**Comment by KATT** [comment]
This feature has been added in the [`next`-branch](https://github.com/trpc/trpc/tree/next) of tRPC, meaning it is available in v11 of tRPC. 

It's possible to start using it _today_, have a look at the migration guide for more info: https://trpc.io/docs/migrate-from-v10-to-v11
