### ISSUE TITLE
feat: Optional router

### ISSUE THREAD

**Issue by adamsuskin** [trpc/trpc#5529]
### Describe the feature you'd like to request

Hey, pretty new here so I may be overlooking something. I'd like optional routers to be a thing. Basically as you combine routers, if there was a way to mark them as optional so that clients can infer they may not be served by the server.

My use case is to host a router that only works in development for serving some debugging information.

### Describe the solution you'd like to see

I would strongly prefer the client to not have to use any shared logic to determine if the router is being served or not. It seems like if we made the router under `trpc` optional, that would be enough.

server:
```
export const appRouter = t.router({
    users: usersRouter,
    ...(ENV.SERVE_DEBUG ? { debug: debugRouter } : {}),
});
```

client:
```
if (trpc.debug) {
    trpc.debug.getDebugInfo.useQuery(...);
}
```

### Describe alternate solutions

I don't really know other solutions that could work.

### Additional information

Right now if you try this in 10.x at least, you get `undefined` as the inferred type for `debug` in the app router.

I've also tried:
```
export const appRouter = t.router({
    users: usersRouter,
    debug: ENV.SERVE_DEBUG ? debugRouter : undefined, // @ts-error for assigning undefined to router
});

export const appRouter = t.router({
    users: usersRouter,
    debug: ENV.SERVE_DEBUG ? debugRouter : noopRouter, // @ts-error, type hint needed to infer app router
});
```

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/5529">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/5529/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/5529/pledge.svg">
</picture>
</a>

**Comment by adamsuskin** [comment]
Worth calling out that I can get away with this by supporting the `debug` router no matter what and raising a not found error when `ENV.SERVE_DEBUG` is not enabled. This just means my client can't statically infer that it may not be served.

**Comment by KATT** [comment]
If it's for debugging or testing just typecast it as non-nullable

**Comment by adamsuskin** [comment]
> If it's for debugging or testing just typecast it as non-nullable

I'm saying that the inferred type of the optional router is `undefined` only (no router shape) so non-nullable type-casting would lead to `never`.

**Comment by KATT** [comment]
```tsx
export const appRouter = t.router({
    users: usersRouter,
    ...(ENV.SERVE_DEBUG ? { debug: debugRouter } : ({} as never /* this is the key */)),
});
```

I think this should work ⬆️ , that will lead it to "always being there" and then you just have to ensure you don't ship any code using that in prod. I do something very similar in my app where I have a testing router that only exists in test/dev mode

I don't think we want to support optional routers as a first-class property

**Comment by adamsuskin** [comment]
That totally works for me and ensuring to not ship it makes sense. I think the way I have it anyways, any procedures under the `debugRouter` have a `use` middleware that checks against `ENV.SERVE_DEBUG` and throws a `NOT_FOUND` trpc error if not `true`.

Appreciate the help in the workaround! That's a nice little trick with the `as never` in one of the ternary branches.
