### ISSUE TITLE
bug: When using wsLink and the fastify adapter, after 16kB of messages sent to the server no further messages are processed.

### ISSUE THREAD

**Issue by mat-sz** [trpc/trpc#5530]
### Provide environment information

```
  System:
    OS: Linux 6.7 Arch Linux
    CPU: (24) x64 AMD Ryzen 9 3900X 12-Core Processor
    Memory: 54.47 GB / 62.71 GB
    Container: Yes
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.6.2 - /usr/bin/node
    Yarn: 4.0.2 - /usr/bin/yarn
    npm: 10.4.0 - /usr/bin/npm
    Watchman: 4.9.0 - /usr/bin/watchman
  Browsers:
    Chromium: 122.0.6261.69
```

### Describe the bug

After sending 16kB of WebSocket messages via the `wsLink` using fastify on the backend, the backend can no longer process messages from that client.

This issue comes from both the hacky way of handling backpressure in `@fastify/websocket` (reported there: https://github.com/fastify/fastify-websocket/issues/289) and the improper way of accessing the `WebSocket` object in `@trpc/server`.

https://github.com/trpc/trpc/blob/466e6ca1de358a2ce99a6a57d5711bb11a772371/packages/server/src/adapters/fastify/fastifyTRPCPlugin.ts#L66

Creating an empty handler like this causes `Duplex` objects to be created while they aren't actually used, which leads in the underlying `WebSocket`s getting paused. `@fastify/websocket` has a way of handling that that is kind of broken and only works if using the recommended way of accessing the objects from the handler (that is left empty here).

### Link to reproduction

https://github.com/mat-sz/trpc-wslink-bug-reproduction

### To reproduce

1. Clone the repository.
2. `yarn install`
3. `yarn build`
4. `yarn dev`
5. Go to http://localhost:3000/
6. Click the button and observe received/sent counts.

The button sends 8192 bytes worth of text, after two clicks, the further attempts result in no response (no errors either).

### Additional information

The solution is to export the `connection` handler separately from `adapters/ws.ts` and use that instead of `applyWSSHandler`. I can submit a pull request here since I have a working version of this.

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/5530">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/5530/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/5530/pledge.svg">
</picture>
</a>

**Comment by KATT** [comment]
Appreciate you taking so much time to make this issue and supplying a reproduction.

Haven't taken the time to properly grok this, but it seems like the problem is in fastify and can be fixed downstream?

If there's a clear workaround with `applyWSSHandler`, we can change the default approach for v11 and forward

**Comment by mat-sz** [comment]
@KATT `@fastify/websocket` is using `ws` in an improper way, that can be fixed there and would fix the issue here as well. (The change would be breaking on their end though and would require a TRPC update as well.)

...but, the way in which `@trpc/server` is using `@fastify/websocket` also isn't proper. The workaround I proposed would result in `@trpc/server` doing it the *recommended* way (as in, using the `WebSocket` object provided by `@fastify/websocket` instead of attaching your own event listeners to the underlying server object).

I can submit a pull request here to address this (both right now, and later when `@fastify/websocket` gets updated) if you want me to, just let me know. I'm working on a PR there as well.

**Comment by KATT** [comment]
Thanks so much for this @mat-sz ❤️

**Comment by mat-sz** [comment]
@KATT Thank you for making this awesome piece of software :)

Meanwhile, I'll try to get the upstream (`@fastify/websocket`) fixed as well. Depending on the changes I'll make another PR to make this compatible.
