### ISSUE TITLE
The following input `z.array(z.number()).readonly()` is inferred as `Array<number>` but it should be `ReadonlyArray<number>`

### ISSUE THREAD

**Issue by PeterMK85** [trpc/trpc#5538]
### Provide environment information

Reproducible on latest tRPC playground as well:
https://trpc.io/?try=next-minimal-starter#try-it-out

### Describe the bug

When an input uses `readonly()` the inferred type ignores that.

Example
```ts
publicProcedure.input(z.array(z.string()).readonly())
```

:bug: Inferred as:
```ts
number[]
```

:green: Should be inferred as:
```ts
ReadonlyArray<number>
```

Example repo:

### Link to reproduction

https://stackblitz.com/edit/github-syvwad?file=src%2Fserver%2Findex.ts

### To reproduce

`byId` inferred type should be `ReadonlyArray`

### Additional information

Typescript and zod plays properly together on this it seems, [playground](https://www.typescriptlang.org/play#code/JYWwDg9gTgLgBAbzgLzgXzgMyhEcDkyEAJvgFBkDGEAdgM7x2UAWApiAIZwC8KAdBABGAK1aUYACgRk4suHVYAbMTACyJVgC5+i4DFZQOiifmA1iwAG7BiAVyP4AlABoZchcvGtiASWJ1tZD4OKEMATwkgmlsQQQMJR0c+KFYOYlpFCJcyNEcKGDCwVjgADR5+M0wDAB4CoohMeRZ2DgA+MgB6DrkAPQB+IA)

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/5538">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/5538/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/5538/pledge.svg">
</picture>
</a>

**Comment by PeterMK85** [comment]
@KATT 

I'm facing the issue when I'm trying to use `byId`.
<img width="361" alt="image" src="https://github.com/trpc/trpc/assets/3931377/82c088e5-ea25-42b8-8880-ba71434170eb">

**Comment by KATT** [comment]
@PeterMK85 

You're calling something on another machine & mutability doesn't have any meaning here. Does it actually block you from calling the procedure or is it a cosmetic issue to you?

If you use a transformer, we don't change the type here fyi

**Comment by KATT** [comment]
Actually, we seem to be doing this correctly. We're using the `_input` from the zod schema which gives us `string[]`, not `readonly string[]`

See https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgLzgXzgMyhEcDkyEAJvgFBkDGEAdgM7x2UAWApiAIZwC8KAdByhQOATwAUyPgyjAaAczEBKRXyisOxWgBtxiikzacA2vgD6ssAFcY+ALpkA9A7gvXcAHoB+fS3YcTphDWVjb2Tm5uXkA

```ts
import { z } from 'zod'

const schema = z.array(z.string()).readonly()

schema['_input']
//       ^?

schema['_output']
//        ^?
```

If this is seems wrong to you, open an issue over at the zod repo

**Comment by TkDodo** [comment]
> Does it actually block you from calling the procedure or is it a cosmetic issue to you?

@KATT i think if we have a readonly array from somewhere (e.g. a prop), we can't pass it as input to this function if it expects a mutable array (assignability works the other way around). So we defined it as readonly in the schema and still got the same error. If you're saying it's an issue with zod itself, we'll file the issue over there.

**Comment by juliusmarminge** [comment]
I expect zod to handle the `.readonly()` similar to transform and other refinements, so the input_in will be the normal string.

Seems like a Zod issue in that they should treat readonly differently so that the input_in type is `readonly string[]` and not just apply it to the `input_out` type

**Comment by KATT** [comment]
I don't know what to do about this - we use zod correctly AFAICT.

Maybe you can hack it somewhere along the lines of this:
https://www.typescriptlang.org/play?jsx=0#code/FASwtgDg9gTgLgAjgTwgUwQbwQLSgEwBVU0AaXA49AETQDMBfBOmKMBAcgC8COBuUJFiJsXBExZtOPfB2DAAxlAB2AZ0Qw0AQ3wqANsgCCMGFuQIAvAgA8hAJLLyhWnQRoAHnDTL8qikRIXJwB5AFc4AD4AClUFAAs0MC0ALn8qNFsHJyCEQjDIgEpLCKxgBAQlNUQUdEsELgA6LRMzGPjErQKGzR19ZCiCgXlyzThQmGUkEgQtP1DlAGtlKAB3SdmEYLAQOGsatChXffIOAH0QZQhwjhKAMlLy8vPL8NSAJW1dZQNM5QBtAC6ETK4hB5WADEUKnUCFiCSSdR6XwMxlM-Ua6hgFwA5gMCvI4R0-mcLlc4BwAcAAPRUx50hAAPQA-PIoVVYe0kgAmOqNZpoqIYuBY5S4gpdJF9AbAQnc4nPMkU4BAA


It could also be changed in zod by changing

https://github.com/colinhacks/zod/blob/e5e86195022c1ba231478852e414c17bf74f230b/src/types.ts#L4835

to

```ts
  MakeReadonly<T["_input"]>
```
