### ISSUE TITLE
docs: Documentation regarding multiple TRPC Providers

### ISSUE THREAD

**Issue by shayant98** [trpc/trpc#5544]
### Area of Improvement

I would love to see more documentation regarding multiple TRPC providers and how to set it up.

### Additional information

Currently I have a monorepo consisting of 2 NextJS Apps (T3) and a seperate shared-api package. Both apps have their own TRPC Context but also use the Client provided by the shared-api package. The issue i'm facing is that it always goes to the lowest nested Provider instead of the first one that has the route.

```jsx
<SharedTRPCReactProvider cookies={cookies().toString()}>
        <TRPCReactProvider cookies={cookies().toString()}>
          {children}
        </TRPCReactProvider>
      </SharedTRPCReactProvider>
```

### example 1:
accessing route: users.getUser

SharedTRPC --> has User router
TRPC --> Does not have user router

#### expect:
To access SharedTRPC and get all users

current results:
tRPC failed on user.getUser: No "query"-procedure on path "user.getUser"

#### accessing route: items.getItems
SharedTRPC --> does not have item router
TRPC --> has Item router

#### expect:
Access TRPC and get Items

#### results:
Accesses items and gets all items as expected.

If i were to switch the order in the JSX **example 1** would work, while **example 2** would fail.

PS:
Both apps have a seperate API endpoint for each instance:
- /trpc/[tpc]
- /shared-trpc/[trpc]

Both TRPC instances have their own context from which they are accessed
- import { sharedApi} from "@tech/trpc/react";
- import { api } from "~/trpc/react";

so even when accessing endpoints defined specifically in either endpoint, it still goes to the wrong context.

would love to have some documentation on how to set this up properly.

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing the suggested changes!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/5544">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/5544/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/5544/pledge.svg">
</picture>
</a>

**Comment by KATT** [comment]
See https://github.com/trpc/trpc/blob/next/packages/tests/server/react/multiple-trpc-providers.test.tsx

**Comment by shayant98** [comment]
I Seem to have almost the same setup, differing using T3 & Turborepo setup. Do you know why it does not access the right Context

**Comment by shayant98** [comment]
I found the issue:

For your nested TRPC Providers. pass the following:
```typescript
createTRPCReact<sharedAppRouter>({
    context: createContext(null),
}),
```

in this case I added   **context: createContext(null)**  and seems to use the correct TRPC Context for each route.

@KATT I would love to know how passing **createContext(null)** solves this issue.

Thank you!
