### ISSUE TITLE
bug: Context type generic removes private properties

### ISSUE THREAD

**Issue by BryceDalbey** [trpc/trpc#5546]
### Provide environment information

from the stackblitz: 

  System:
    OS: Linux 5.0 undefined
    CPU: (6) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.18.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.3 - /usr/local/bin/pnpm
  npmPackages:
    @trpc/server: ^10.25.0 => 10.25.0 
    typescript: ^4.8.3 => 4.8.3 

### Describe the bug

Private, protected, and #hash properties on the type used in context construction are removed from the type available in procedures

### Link to reproduction

https://stackblitz.com/edit/github-yrjz6a-sb7qge?file=src%2Fserver%2Ftrpc.ts

### To reproduce

see stackblitz

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/5546">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/5546/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/5546/pledge.svg">
</picture>
</a>

**Comment by KATT** [comment]
Context shouldn't be an instance as it depends on spreading when using eg [base procedures](https://trpc.io/docs/server/procedures#reusable-base-procedures).

We could potentially support this, but you'll have to add it yourself

For now, context should be a `Record`
