### ISSUE TITLE
bug: importing from `@trpc/client` pulls in `@types/node`

### ISSUE THREAD

**Issue by bug-brain** [trpc/trpc#5557]
### Provide environment information

  ```
  npmPackages:
    @trpc/client: ^10.45.1 => 10.45.1
    @trpc/server: ^10.45.1 => 10.45.1
    typescript: ^5.3.3 => 5.3.3
```

### Describe the bug

I want to use `@trpc/client` to make calls to the backend and noticed that `process.env` is not an error according to TypeScript.

### Link to reproduction

https://stackblitz.com/edit/github-bu2owm?file=tsconfig.json,index.ts

### To reproduce

Import the `@trpc/client` package, see reproduction link.

### Additional information

There are several references to `NodeJS.ReadableStream` in the code. Maybe they should be rewritten in the style it has been done for `fetch` (see `FetchEsque` etc.) but I'm not certain this is the real cause.

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/5557">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/5557/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/5557/pledge.svg">
</picture>
</a>

**Comment by KATT** [comment]
We don't have any explicit import of `@types/node` and AFAIK every js runtime has a `process.env`

What issue are you actually experiencing in a real world project?

**Comment by KATT** [comment]
`ReadableStream` is only referenced if you include the experimental formdata handler

**Comment by bug-brain** [comment]
I have tracked this down to [here](https://github.com/trpc/trpc/blob/next/packages/client/src/internals/types.test.ts#L2) where node-fetch and undici are imported both of which reference the node types. The file is included in the client tsconfig but shouldn't because it runs in a different environment. For the client package `compilerOptions.types` should be empty. That will then force an API design that - from TypeScripts perspective - does not require the node environment.

**Comment by KATT** [comment]
`.test`-files are omitted before npm publish so that's not it https://www.npmjs.com/package/@trpc/client/v/11.0.0-next-beta.316?activeTab=code:

![CleanShot 2024-03-11 at 14 26 39](https://github.com/trpc/trpc/assets/459267/b8d46564-3d92-4640-9841-ff1678509fac)


I don't know exactly how `import`ing `@trpc/client` causes this behavior, but this isn't it... 🤔

**Comment by KATT** [comment]
Ignore my last message, you might be right on that one! We'll try to do a test w/o it and see if it works.

**Comment by bug-brain** [comment]
What I wrote was just from trying some things in the code of this repo. You are right I should have checked the actual downloaded package as well. There are `/// <reference types="node" />` comments in the files that use the `NodeJS` namespace (packages/client/src/internals/types.ts and packages/client/src/links/internals/parseJSONStream.ts) that pull in all the globals.

This is another case for https://github.com/microsoft/TypeScript/issues/50424 but that does not seem to be solved any time soon.

**Comment by KATT** [comment]
I tested #5562 and it seems to be satisfactory: https://stackblitz.com/edit/github-bu2owm-t9unrv?file=index.ts,package.json

Re-open if it isn't! This will autoclose once that is merged. Thank you for this report!
