### ISSUE TITLE
Skip queries on condition

### ISSUE THREAD

**Issue by FleetAdmiralJakob** [trpc/trpc#5566]
### Describe the feature you'd like to request

Skipping the query if a value is not there like here for example in convex: https://docs.convex.dev/client/react#skipping-queries

### Describe the solution you'd like to see

Something similar like in convex

### Describe alternate solutions

If I have to handle the value on the Backend I need to make a request to the server and I don't want this extra cost. 

### Additional information

Original problem that I'm facing: https://discord.com/channels/867764511159091230/1217568021934116956 and a little bit more discussed here: https://discord.com/channels/1088780748028379146/1217572507176013874

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/5566">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/5566/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/5566/pledge.svg">
</picture>
</a>

**Comment by KATT** [comment]
https://trpc.io/docs/client/react/disabling-queries#typesafe-conditional-queries-using-skiptoken
