### ISSUE TITLE
feat: middleware after the .query

### ISSUE THREAD

**Issue by itelo** [trpc/trpc#5575]
### Describe the feature you'd like to request

let's suppose that I have a TRPC method, getStudentGradeById, that accepts the gradeId. I want to return the grade only if the student owns it. I don't want to use the [output](https://trpc.io/docs/server/validators#with-zod) because it would require me to write the output schema for each method. Additionally, I don't want to include any permission management within the .query. Is it possible to achieve this? Should I attempt to make the necessary changes and submit a pull request?

### Describe the solution you'd like to see

something like

```ts
protectecProcedure
  .input(z.object({
    gradeId: z.string()
  }))
  .query(() => prisma.grade.findById(gradeId))
  .use(({ctx, result}) => {
    if (result.studentId !== ctx.studentId) {
      throw new TrpcError()
    }
  })
```

### Describe alternate solutions

the alternate solution would be doing it inside the .query, but I don't think this is a good solution.

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/5575">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/5575/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/5575/pledge.svg">
</picture>
</a>

**Comment by KATT** [comment]
It's better to to the permission check before and scope all database queries etc according to the users permissions / ownerships 

The method you're proposing here wouldn't work at all for mutations - doing permission check after is too late. You should have an authorization mechanism that works the same. 

I appreciate the effort you put into this request but we won't build this
