### ISSUE TITLE
bug: fetchRequestHandler not catching errors

### ISSUE THREAD

**Issue by hansoksendahl** [trpc/trpc#5576]
### Provide environment information

```
  System:
    OS: macOS 14.3
    CPU: (12) arm64 Apple M2 Pro
    Memory: 102.70 MB / 16.00 GB
    Shell: 3.6.1 - /usr/local/bin/fish
  Binaries:
    Node: 20.3.1 - ~/.local/share/nvm/v20.3.1/bin/node
    Yarn: 1.22.21 - ~/.local/share/nvm/v20.3.1/bin/yarn
    npm: 9.6.7 - ~/.local/share/nvm/v20.3.1/bin/npm
    pnpm: 8.14.1 - ~/.local/share/nvm/v20.3.1/bin/pnpm
    bun: 1.0.28 - ~/.bun/bin/bun
  Browsers:
    Chrome: 122.0.6261.129
    Safari: 17.3
  npmPackages:
    @trpc/client: ^10.44.1 => 10.45.2 
    @trpc/server: ^10.44.1 => 10.45.2 
```

### Describe the bug

Sometime recently it seems that fetchRequestHandler stopped catching errors. Any error thrown in a procedure kills the server.

### Link to reproduction

https://github.com/hansoksendahl/trpc-not-catch-error

### To reproduce

```
git clone git@github.com:hansoksendahl/trpc-not-catch-error.git
cd trpc-not-catch-error
```

# PNPM
```
pnpm install
pnpm run dev
```

# NPM
```
npm install
npm run dev
```

### Additional information

I really like tRPC this is the only major headache I have had so far. If I can find a fix I'm happy to submit it.

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/5576">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/5576/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/5576/pledge.svg">
</picture>
</a>

**Comment by KATT** [comment]
Will have a look at this tomorrow 👀

**Comment by KATT** [comment]
Did a quick test and it seems like it works in my test... could it be something in vinxi/Seroval? Never heard of those before

**Comment by KATT** [comment]
Seems to be something outside of tRPC that is the problem

Changing your code to 

```ts
const hello = createAsync(() => api.example.hello.query("world").catch(err => 'err'));
```

makes it work and just show "err", so it appears it's something else that doesn't handle (the serialization?) of the error...

the error contains the `Response` object and I notice some error about response already being read.

I don't know the stack so I have a hard time helping here - unsure if there's an action to be taken on our end

**Comment by hansoksendahl** [comment]
@KATT Thank you for quickly responding

The stack trace begins with the error thrown in the procedure. The error continues to propagate up the stack because nothing is catching it.

The additional error messages can most likely be disregarded.

**Comment by hansoksendahl** [comment]
@KATT I tried the fix you suggested and that does seem to stop the error.

However, I want to clarify my understanding of the tRPC client though. If the server throws an error then the tRPC client will throw as well? That's a bit of a surprise for me but something I can adjust to if needed.

Perhaps the fix is just that the documentation for the tRPC clients needs to be updated with an example of error handling.

**Comment by KATT** [comment]
Yes, both throws - how did you expect it to work on the client if the server responds with an error?

**Comment by KATT** [comment]
Feel free to do a PR to the docs! 🙏

**Comment by hansoksendahl** [comment]
@KATT I guess it was just a surprise. I made some changes to the minimal repro repo to make it clearer what was happening. There were additional error messages that were being created by the fact the front-end was being server side rendering.

It's now clear that the client throws when the server throws.

In answer to your question I guess I am used to APIs that return JSON no matter what if there is an error they just return it as an additional field. My best guess is that I didn't encounter this problem previously because I was returning errors from the server rather than throwing them.

**Comment by KATT** [comment]
We do exactly what you're describing. We return the error as json but to emulate an rpc call we throw in a similar way the server threw
