### ISSUE TITLE
bug: go to definition not working with project references and `disableSourceOfProjectReferenceRedirect`

### ISSUE THREAD

**Issue by relsunkaev** [trpc/trpc#5580]
### Provide environment information

```
System:
  OS: macOS 14.3.1
  CPU: (10) arm64 Apple M1 Pro
  Memory: 112.91 MB / 16.00 GB
  Shell: 5.9 - /bin/zsh
Binaries:
  Node: 16.18.1 - ~/Library/Caches/fnm_multishells/66181_1711122384805/bin/node
  Yarn: 1.22.19 - ~/Library/Caches/fnm_multishells/66181_1711122384805/bin/yarn
  npm: 9.2.0 - ~/Library/Caches/fnm_multishells/66181_1711122384805/bin/npm
  pnpm: 7.26.2 - ~/Library/Caches/fnm_multishells/66181_1711122384805/bin/pnpm
Browsers:
  Chrome: 123.0.6312.59
  Edge: 122.0.2365.92
  Safari: 17.3.1
npmPackages:
  typescript: ^5.4.3 => 5.4.3
```

### Describe the bug

As described in the title, when using project references with `disableSourceOfProjectReferenceRedirect` set to `true` and declaration maps enabled, go to definition stops working. Works fine if `disableSourceOfProjectReferenceRedirect` is set to `false`.

It seems going to definition just brings you to the closing bracket of the outermost router.

### Link to reproduction

https://github.com/relsunkaev/ts-declaration-map-repro

### To reproduce

Try going to definition of a router from api client. See where that gets ya.

### Additional information

I have a suspicion that this is a typescript bug, but wanted to check with you guys first before submitting an issue there. Our repo has gotten quite large and `disableSourceOfProjectReferenceRedirect` is the difference between waiting 5-10 seconds on every change and instant feedback in VSCode

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/5580">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/5580/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/5580/pledge.svg">
</picture>
</a>

**Comment by KATT** [comment]
I'm very excited to see the outcome of your work here, but I honestly don't know if this is how TypeScript is meant to work with `disableSourceOfProjectReferenceRedirect` or not

I wonder if I can make a wild @mattpocock appear? 👀

**Comment by KATT** [comment]
I doubt this has anything to do with tRPC and rather how `disableSourceOfProjectReferenceRedirect` works...?

**Comment by KATT** [comment]
Can you share a repo of what did work?

**Comment by KATT** [comment]
Hey there! :wave:


I'll close this issue as this issue does not seem to be related to tRPC itself. Suuper interested in what you come with though and you're more welcome to edit the docs if you find something nice 🙏 

Please feel free to re-open with a solid reproduction repository where we can help you further or post in our help channels on [Discord](https://trpc.io/discord) or in our [GitHub Discussions](https://github.com/trpc/trpc/discussions).
