### ISSUE TITLE
docs: v11 React Query Integration "Install dependencies" section lists unnecessary packages

### ISSUE THREAD

**Issue by vittis** [trpc/trpc#5588]
### Area of Improvement

The Install dependencies section (https://trpc.io/docs/client/react/setup#1-install-dependencies)

Is listing 
`npm install @trpc/server@next @trpc/client@next @trpc/react-query@next @trpc/next@next @tanstack/react-query@latest`

I believe  `@trpc/next@next` should not be included, as this is not anything related to Next?

I'm not sure, but is `@trpc/server@next` also not required? I tested not installing it and got no errors whatsoever

### Link to related docs

https://trpc.io/docs/client/react/setup

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing the suggested changes!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/5588">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/5588/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/5588/pledge.svg">
</picture>
</a>

**Comment by KATT** [comment]
Feel free to click the edit button and remove it!
