### ISSUE TITLE
Cancelling mutations should throw an `AbortError` instead of `new Error('Done')`

### ISSUE THREAD

**Issue by kripod** [trpc/trpc#559]
Since upgrading to v7, I’ve noticed that the exception handling mechanism in use by our company doesn’t work anymore:

```js
const { client } = trpc.useContext();
let cancelablePromise;
try {
  cancelablePromise = client.mutation("something", { param: "example" });
  setTimeout(() => {
    cancelablePromise.cancel()
  }, 0);
  return await cancelablePromise;
} catch (error) {
  const originalError =
    error instanceof TRPCClientError ? error.originalError : error;
  if (
    originalError instanceof DOMException &&
    originalError.name === "AbortError"
  ) {
    // We should reach this branch
    throw new CancelledError();
  }
  // But instead, `new Error('Done')` is called via `.cancel()`
  throw error;
}
```

I think I found the guilty code snippet:

https://github.com/trpc/trpc/blob/4a5654b36ca3a520d7e369cd45f6eab4c95c6e57/packages/client/src/createTRPCClient.ts#L251-L256

It should be corrected to throw an `AbortError` instead, just like DOM APIs (e.g. `fetch`) do.

My use-case would be distinguishing regular and cancellation errors (the latter are caused by a debouncing mechanism).

**Comment by kripod** [comment]
As weird as it might sound, the issue doesn’t seem to be affecting Firefox, but it’s reproducible in Chrome.

**Comment by KATT** [comment]
Make a PR with a failing test and I'll fix it and make sure it'll never happen again.
