### ISSUE TITLE
bug: Error: No QueryClient set, use QueryClientProvider to set one

### ISSUE THREAD

**Issue by Kylar13** [trpc/trpc#5597]
### Provide environment information

System:
    OS: macOS 14.2.1
    CPU: (12) arm64 Apple M2 Pro
    Memory: 42.77 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.1 - ~/Library/pnpm/node
    npm: 10.2.4 - ~/Library/pnpm/npm
    pnpm: 8.15.2 - /opt/homebrew/bin/pnpm
    bun: 1.0.26 - /opt/homebrew/bin/bun
  Browsers:
    Safari: 17.2.1
  npmPackages:
    @tanstack/react-query: ^4.18.0 => 4.36.1 
    @trpc/client: 10.45.0 => 10.45.0 
    @trpc/react-query: 10.45.0 => 10.45.0 
    @trpc/server: 10.45.0 => 10.45.0 
    next: ^14.0.4 => 14.0.4 
    react: ^18.2.0 => 18.2.0 
    typescript: ^5.3.3 => 5.3.3 

### Describe the bug

When using App router and layouts, we have the issue that locally everything works but during the vercel build we get this error.

```
web:build: Error: No QueryClient set, use QueryClientProvider to set one
web:build:     at f (/vercel/path0/apps/web/.next/server/chunks/178.js:18:48607)
web:build:     at P (/vercel/path0/apps/web/.next/server/chunks/178.js:18:49438)
web:build:     at Object.useQuery (/vercel/path0/apps/web/.next/server/chunks/178.js:18:58827)
web:build:     at /vercel/path0/apps/web/.next/server/chunks/178.js:18:63385
web:build:     at Object.apply (/vercel/path0/apps/web/.next/server/chunks/178.js:18:64064)
web:build:     at P (/vercel/path0/apps/web/.next/server/chunks/404.js:1:9562)
web:build:     at nP (/vercel/path0/node_modules/.pnpm/next@14.0.4_@babel+core@7.23.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:45321)
web:build:     at nP (/vercel/path0/node_modules/.pnpm/next@14.0.4_@babel+core@7.23.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:59120)
web:build:     at n$ (/vercel/path0/node_modules/.pnpm/next@14.0.4_@babel+core@7.23.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:61978)
web:build:     at nj (/vercel/path0/node_modules/.pnpm/next@14.0.4_@babel+core@7.23.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:64628)
```

This is our root layout:

```
import { SpeedInsights } from "@vercel/speed-insights/next";

import { Providers } from "~/app/providers";

export default async function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body>
                <SpeedInsights />
                <Providers>{children}</Providers>
            </body>
        </html>
    );
}
```

And this is our providers.tsx

```
"use client";

import { useEffect, useMemo, useState } from "react";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { unstable_httpBatchStreamLink } from "@trpc/client";
import SuperJSON from "superjson";

import { getBaseUrlServer } from "~/utils/getBaseUrl";
import { createBrowserComponentClient } from "~/utils/supabase-client";
import { api } from "~/utils/trpc-client";

export const Providers = ({ children }: { children: React.ReactNode }) => {
    const [queryClient] = useState(
        () =>
            new QueryClient({
                defaultOptions: {
                    queries: {
                        staleTime: 15 * 1000,
                    },
                },
            }),
    );

    const [authToken, setAuthToken] = useState<string | undefined>();

    const trpcClient = useMemo(() => {
        return api.createClient({
            transformer: SuperJSON,
            links: [
                unstable_httpBatchStreamLink({
                    url: `${getBaseUrlServer()}/api/trpc`,
                    headers: {
                        Authorization: `Bearer ${authToken}`,
                    },
                }),
            ],
        });
    }, [authToken]);

    const supabase = createBrowserComponentClient();
    useEffect(() => {
        const {
            data: { subscription },
        } = supabase.auth.onAuthStateChange((_, session) => {
            if (session) {
                setAuthToken(session.access_token);
            }
        });

        return subscription.unsubscribe;
    }, [supabase.auth]);

    return (
        <api.Provider client={trpcClient} queryClient={queryClient}>
            <QueryClientProvider client={queryClient}>{children}</QueryClientProvider>
        </api.Provider>
    );
};
```

Again this is the root layout, so anything we render should be under `QueryClientProvider`. 

Any idea why we're getting this error?

### Link to reproduction

https://stackblitz.com/github/trpc/examples-next-minimal-starter?file=README.md

### To reproduce

Unsure how to reproduce because as I said locally using `next dev` everything works.

Also unsure if this issue should be here or in nextjs.

Any help would be appreciated

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/5597">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/5597/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/5597/pledge.svg">
</picture>
</a>

**Comment by KATT** [comment]
Hey there! :wave:

We appreciate the time you've taken to write this issue.

Unfortunately, we don't have the capacity to assist with issues without a reproduction repository and this issue does not seem to be related to tRPC itself. 

Please feel free to re-open with a solid reproduction repository where we can help you further or post in our help channels on [Discord](https://trpc.io/discord) or in our [GitHub Discussions](https://github.com/trpc/trpc/discussions).
