### ISSUE TITLE
feat: `useUtils` exposes `setQueryData` but not `setQueriesData`

### ISSUE THREAD

**Issue by etcd** [trpc/trpc#5598]
### Describe the feature you'd like to request

The [helper methods](https://trpc.io/docs/client/react/useUtils#helpers) exposed by `useUtils` do not include [`setQueriesData`](https://tanstack.com/query/v5/docs/reference/QueryClient#queryclientsetqueriesdata), which is [necessary for partial query key matching](https://tanstack.com/query/v5/docs/reference/QueryClient#queryclientsetquerydata):

> To update multiple queries at once and match query keys partially, you need to use [queryClient.setQueriesData](https://tanstack.com/query/v5/docs/reference/QueryClient#queryclientsetqueriesdata) instead.

### Describe the solution you'd like to see

I'd like to see the utils expose `setQueriesData` as a helper so I can update cached data by partial query key matching.

### Describe alternate solutions

Just opening a feature request, as the [documentation suggests](https://trpc.io/docs/client/react/useUtils#-the-function-i-want-isnt-here). In the mean time, I know I can import and use the function directly.

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/5598">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/5598/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/5598/pledge.svg">
</picture>
</a>

**Comment by nabeelvalley** [comment]
Hi, can I take a look at this?

**Comment by KATT** [comment]
yes
