### ISSUE TITLE
bug: Beta versioning is broken

### ISSUE THREAD

**Issue by ravshansbox** [trpc/trpc#5599]
### Provide environment information

  System:
    OS: macOS 14.4.1
    CPU: (12) arm64 Apple M3 Pro
    Memory: 2.34 GB / 36.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.12.0 - ~/.volta/tools/image/node/20.12.0/bin/node
    Yarn: 1.22.22 - ~/.volta/tools/image/yarn/1.22.22/bin/yarn
    npm: 10.5.0 - ~/.volta/tools/image/node/20.12.0/bin/npm
    pnpm: 8.15.5 - ~/.volta/bin/pnpm
    Watchman: 2024.03.25.00 - /opt/homebrew/bin/watchman
  Browsers:
    Safari: 17.4.1

### Describe the bug

Version `11.0.0-next-beta.318`  is considered newer than `11.0.0-next.327` by npm. If you install latest `next` (eg. `11.0.0-next.327`) and then delete lockfile and run `npm install` again version with `0-next-beta` patch will be installed.

### Link to reproduction

https://stackblitz.com/~/github.com/ravshansbox/trpc-demo

### To reproduce

Run `npm install` (stackblitz should do automatically) and open `package-lock.json`

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/5599">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/5599/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/5599/pledge.svg">
</picture>
</a>

**Comment by KATT** [comment]
Semver is so annoying, we swapped from `next-beta` because we got reports of the opposite, see #5578

**Comment by ravshansbox** [comment]
I think "next" should not be used as version token at all, "alpha" and "beta" are good candidates here, they are properly sorted alphabetically, next can be used just a tag for the next version

**Comment by ravshansbox** [comment]
Also, please, don't hurry to close a ticket, this would discourage people from reporting bugs at all

**Comment by KATT** [comment]
We already accidentally published a `-next`, which fucked both the words "alpha" and "beta" since they're alphabetically before "next" and hence (sometimes) interpreted as older

**Comment by KATT** [comment]
I released an `-rc` which should be both alphabetically after `n` and has a higher number so I really hope it's fixed now 😅

**Comment by ravshansbox** [comment]
Yeah, I can confirm it's fixed now
