### ISSUE TITLE
bug: `useSubscription` `onData` does not use ref in v11

### ISSUE THREAD

**Issue by puchm** [trpc/trpc#5609]
### Provide environment information

@trpc/react-query@11.0.0-rc.330

(Rest is not applicable)

### Describe the bug

I was debugging an issue for several hours today which ended up being of my own doing, but while I was doing that I stumbled upon something on the `next` branch that I think may be worth looking at.

#4222 made sure that the callback functions passed to `useSubscription` were called via a ref, allowing people to change the callback functions and pass unmemoized functions as callbacks. The following merge commit #4261 contains these changes as well for both `onError` and `onStarted`, but does not contain the same change for `onData`. 

Is this intentional? I am pretty sure this may cause issues and I couldn't find any indication of this being intentional.

The main branch also uses refs but the next branch doesn't in the instance of `onData`.

### Link to reproduction

N/A

### To reproduce

As I said, the issue I was having does not have anything to do with this - I just stumpled upon this when looking at the source code. Since there is nothing to reproduce, I don't think a reproduction is needed.

### Additional information

Tagging @iamnafets and @KATT as you are the authors of the commits in question.

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/5609">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/5609/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/5609/pledge.svg">
</picture>
</a>

**Comment by KATT** [comment]
Thanks for this report! Must've been a bad merge or a typo that we've missed to change `opts.onData` to `optsRef.current.onData`
