### ISSUE TITLE
bug: Getting "property collision with a built-in method" in client apps when used trpc server with nestjs

### ISSUE THREAD

**Issue by akashdevcc** [trpc/trpc#5614]
### Provide environment information

```
  System:
    OS: Linux 6.5 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 2.58 GB / 15.48 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 20.10.0 - ~/.nvm/versions/node/v20.10.0/bin/node
    npm: 10.2.3 - ~/.nvm/versions/node/v20.10.0/bin/npm
    pnpm: 8.15.0 - ~/.nvm/versions/node/v20.10.0/bin/pnpm
    Watchman: 2024.01.22.00 - /home/linuxbrew/.linuxbrew/bin/watchman
  Browsers:
    Chrome: 121.0.6167.184
  npmPackages:
    typescript: ^5.3.3 => 5.3.3 
```

### Describe the bug

I tried to integrate tRPC with nestjs to leverage the "dependency injection" pattern in my apps. I was able to do it successfully up to the server app part, but when I am using the `AppRouter` in client apps i.e. "nextjs" and "expo" apps, I am getting the below TypeScript error at multiple places:

```bash
Property createClient does not exist on type
 in your router collides with a built-in method, rename this router or procedure on your backend." | "The property useUtils' in your router collides with a built-in method, rename this router or procedure on your backend." | ... 4 more ... | "The property useDehydratedState' in your route...'.
```

However, the server app runs successfully and I am able to perfrom tRPC operations on tRPC playground, as defined in the "To reproduce" and "Additional information" sections.

I was expecting that the client apps "nextjs" & "expo" should have properly inferred the types from `AppRouter` without any TypeScript errors.

### Link to reproduction

https://github.com/akashdevcc/zero-stack

### To reproduce

To reproduce the issue, follow the steps below:

### 1. Prerequisites

- Node v20.10.0
- NPM
- PNPM v8.15.0

### 2. Clone the repository

Clone this repository to your local machine.

### 3. Setup dependencies

```bash
# Install dependencies
pnpm i
```

### 4. Build all the packages & apps

```bash
pnpm build
```

Except "nextjs" and "expo" apps, everything else should have been built successfully. "nextjs" build fails with error (most probably due to the same issue, described on top).

### 5. Review "PROBLEMS" tab section

In VSCode's "PROBLEMS" tab section, you will find the same issue mentioned below at multiple places.

```bash
Property createClient does not exist on type
 in your router collides with a built-in method, rename this router or procedure on your backend." | "The property useUtils' in your router collides with a built-in method, rename this router or procedure on your backend." | ... 4 more ... | "The property useDehydratedState' in your route...'.
```

### Check server app and tRPC Playground

The server apps compile successfully and tRPC Playground works perfectly.

1. Run below command:

   ```bash
   pnpm -F server dev
   ```

2. Go to url: http://localhost:4000/playground

3. Paste the below queries/mutations on the left side.

   ```ts
   await trpc.greeting.hello.query({ name: "acme" })

   await trpc.post.all.query()

   await trpc.post.byId.query({ id: 2 })

   await trpc.post.create.mutate({ title: "new post title", content: "new post content" })

   await trpc.post.delete.mutate(3)

   export {}
   ```

4. Run each operation one by one, they should be performed successfully.

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/5614">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/5614/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/5614/pledge.svg">
</picture>
</a>

**Comment by juliusmarminge** [comment]
You have incorrect usage of `createRouterFactory`. You should pass your router to `createCallerFactory` like this:

```ts
const createCaller = createCallerFactory(appRouter)
```
> See https://github.com/t3-oss/create-t3-turbo/blob/main/packages/api/src/index.ts#L14

and then you create a caller with the context:

```ts
const caller = createCaller(createContext)
```
> See https://github.com/t3-oss/create-t3-turbo/blob/main/apps/nextjs/src/trpc/server.ts#L21

I don't know how to do this with your Nest.js setup, but it looks like you have your api as a separate server so you probably shouldn't be using server-side calls.

**Comment by akashdevcc** [comment]
@juliusmarminge Thank you for quick response and pointing out my mistake.

Yes, I have a separate `server` app that has "nestjs + fastify" setup, which I intend to use with my expo app.
My main goal is to make "expo" app work with "nestjs + fastify" server app, "nextjs" app is not my primary concern.

The `packages/api` however just contains the logic to combine all tRPC sub-routers to `AppRouter`.
This `packages/api` is being used by both `apps/nextjs` and `apps/server`.

I have managed to get `appRouter` instance from `packages/api` and corrected the usage of `createCallerFactory` in `apps/nextjs`.

Now, the `nextjs` web app is compiling and running successfully (but with one warning "Critical dependency: the request of a dependency is an expression" in nestjs packages).
Also, `expo` app is working with both `nextjs` and `nestjs` server.

**But, the main issue of the "property collision" TypeScript error still remains, both in "nextjs" and "expo" apps.**
due to which I am not getting auto-complete of tRPC query/mutation in the client apps, which is the main benefit of using tRPC.

**Comment by KATT** [comment]
Hey 👋 

We appreciate you taking the time to report this issue.

Unfortunately, we don't have the capacity to assist here as this issue does not seem to be related to tRPC itself. 

For effective assistance, reopening the issue with a reproduction repository that proofs there's an issue in tRPC would be immensely helpful. Alternatively, you can try to get help on our [Discord](https://trpc.io/discord) or in [GitHub Discussions](https://github.com/trpc/trpc/discussions).

Thank you for your understanding and cooperation!

**Comment by akashdevcc** [comment]
Hi @KATT 

Thank you for the great work you have done with tRPC. I know the core team must be busy with v11 release.

I will try to get help on Discord and GitHub discussions. But if it's possible for core team members (@KATT @sachinraja @Nick-Lucas) to have a look whenever they get capacity, please do. As I believe many developers would want a monorepo setup with dependency injection to support large complex projects.

**Comment by akashdevcc** [comment]
@KATT 
Also, when I was trying to dig deeper into the issue, I saw that after the build of my `packages/api`, the generated `dist/index.d.ts` shows `_trpc_server_dist_unstable_core_do_not_import.BuiltRouter` as `/*unresolved*/` (refer to line no. 44 in the attached screenshot). 

This is same for other types which I needed to import from "unstable core" i.e. 
```
DecorateCreateRouterOptions
TRPC_ERROR_CODE_NUMBER
QueryProcedure
MutationProcedure
Router
RouterCaller
```

Whereas the `inferRouterInputs` and `inferRouterOutputs` which are also part of "unstable core" are able to get resolved successfully. May be because they have been exported [here](https://github.com/trpc/trpc/blob/next/packages/server/src/%40trpc/server/index.ts#L18) directly.

Also, it has been mentioned in comments of file [unstable-core-do-not-import.ts](https://github.com/trpc/trpc/blob/next/packages/server/src/unstable-core-do-not-import.ts#L9) "If you seem to need to import anything from here, please open an issue"

I am not an expert in typescript, but I think making these types available out of "unstable core" just like `inferRouterInputs` and `inferRouterOutputs`, will resolve this issue.

This issue might not be coming for those who are using ES modules, because monorepo trpc examples are working perfectly like [t3-oss/create-t3-turbo](https://github.com/t3-oss/create-t3-turbo/) but in my case I had to use "commonjs" because of "nestjs and fastify" server setup.
