### ISSUE TITLE
bug: `tsc` fails in example project

### ISSUE THREAD

**Issue by wangwalton** [trpc/trpc#5647]
### Provide environment information

  System:
    OS: macOS 14.4.1
    CPU: (8) arm64 Apple M1
    Memory: 104.13 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.7.1 - ~/.nvm/versions/node/v21.7.1/bin/node
    Yarn: 1.22.22 - ~/.nvm/versions/node/v21.7.1/bin/yarn
    npm: 10.5.0 - ~/.nvm/versions/node/v21.7.1/bin/npm
    pnpm: 8.6.2 - ~/dev/node_modules/.bin/pnpm
    Watchman: 2024.04.15.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 124.0.6367.61
    Safari: 17.4.1
  npmPackages:
    @tanstack/react-query: ^5.25.0 => 5.29.2
    @trpc/client: npm:@trpc/client@next => 11.0.0-rc.342+96bcf23a7
    @trpc/next: npm:@trpc/next@next => 11.0.0-rc.342+96bcf23a7
    @trpc/react-query: npm:@trpc/react-query@next => 11.0.0-rc.342+96bcf23a7
    @trpc/server: npm:@trpc/server@next => 11.0.0-rc.342+96bcf23a7
    next: ^14.1.4 => 14.2.2
    react: ^18.2.0 => 18.2.0
    typescript: ^5.4.0 => 5.4.5

### Describe the bug

can't complete tsc

### Link to reproduction

n/a

### To reproduce

In my project `tsc` fails on node_modules/trpc with a bunch of TS1005 errors.

Tried reproducing in the examples repo
```
 pnpm create next-app --example https://github.com/trpc/trpc --example-path examples/next-prisma-starter trpc-prisma-starter
```

running
```
tsc
```

also fails
e.g.
```
node_modules/.pnpm/@prisma+client@5.12.1_prisma@5.12.1/node_modules/@prisma/client/runtime/library.d.ts:1328:35 - error TS1005: '?' expected.

1328     select: infer S extends object;
                                       ~

node_modules/.pnpm/@prisma+client@5.12.1_prisma@5.12.1/node_modules/@prisma/client/runtime/library.d.ts:1330:36 - error TS1005: '?' expected.

1330     include: infer I extends object;
                                        ~

node_modules/.pnpm/@trpc+next@11.0.0-rc.342_@tanstack+react-query@5.29.2_@trpc+client@11.0.0-rc.342_@trpc+react-_h5wwhb4cigumqow4c4gwl76hq4/node_modules/@trpc/next/dist/createTRPCNext.d.ts:20:41 - error TS1005: '>' expected.

20     withTRPC: ReturnType<typeof withTRPC<TRouter, TSSRContext>>;
                                           ~

node_modules/.pnpm/@trpc+next@11.0.0-rc.342_@tanstack+react-query@5.29.2_@trpc+client@11.0.0-rc.342_@trpc+react-_h5wwhb4cigumqow4c4gwl76hq4/node_modules/@trpc/next/dist/createTRPCNext.d.ts:20:63 - error TS1005: '(' expected.

20     withTRPC: ReturnType<typeof withTRPC<TRouter, TSSRContext>>;
```

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/5647">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/5647/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/5647/pledge.svg">
</picture>
</a>

**Comment by juliusmarminge** [comment]
The TRPC errors you're getting looks related to inatantiation expressions which were released in 4.7: https://devblogs.microsoft.com/typescript/announcing-typescript-4-7/#instantiation-expressions

But your env info says you're on 5.4 so that error doesn't make any sense.

You generally don't want to typecheck external libs which you can do by enabling `skipLibCheck: true`.

Without a reproduction repo, can't really say much more than that...
