### ISSUE TITLE
feat: support form-data and octet-streams in remaining adapters

### ISSUE THREAD

**Issue by Nick-Lucas** [trpc/trpc#5648]
### Describe the feature you'd like to request

https://github.com/trpc/trpc/pull/5613 added support for FormData and Blob/File/Uint8array Octet Streams, but only in the node-http adapters (standalone, express, nextjs)

Other adapters only received JSON support but are now extensible to support additional content types

### Describe the solution you'd like to see

* Fetch: form-data
* Fetch: octets
* Fastify: form-data
* Fastify: octets
* Lambda: form-data
* Lambda: octets
* Next AppRouter: form-data
* Next AppRouter: octets

These don't need to all be done at once, folk from the community should feel free to contribute just one at a time for their own needs

### Describe alternate solutions

No

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/5648">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/5648/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/5648/pledge.svg">
</picture>
</a>

**Comment by KATT** [comment]
Closed by #5684
