### ISSUE TITLE
bug: Cannot find module '@web3-storage/multipart-parser'

### ISSUE THREAD

**Issue by ravshansbox** [trpc/trpc#5650]
### Provide environment information

  System:
    OS: macOS 14.4.1
    CPU: (12) arm64 Apple M3 Pro
    Memory: 3.97 GB / 36.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.12.2 - ~/.nvm/versions/node/v20.12.2/bin/node
    Yarn: 1.22.22 - ~/.nvm/versions/node/v20.12.2/bin/yarn
    npm: 10.5.0 - ~/.nvm/versions/node/v20.12.2/bin/npm
    pnpm: 9.0.3 - ~/.nvm/versions/node/v20.12.2/bin/pnpm
    Watchman: 2024.04.15.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 124.0.6367.62
    Safari: 17.4.1

### Describe the bug

<img width="1313" alt="image" src="https://github.com/trpc/trpc/assets/1499188/3eadeb2e-b316-4a05-bc35-b35312e01ef6">

### Link to reproduction

https://stackblitz.com/~/github.com/ravshansbox/trpc-demo

### To reproduce

`npm start`

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/5650">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/5650/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/5650/pledge.svg">
</picture>
</a>

**Comment by ravshansbox** [comment]
Only reproducible on 11.0.0-rc.345, not reproducible in 11.0.0-rc.342

**Comment by oxdev03** [comment]
Hi,
the reproduction link, only has a package.json?

**Comment by ravshansbox** [comment]
Sorry, it was outdated. Updated.

**Comment by mgreenw** [comment]
I also hit this

**Comment by juliusmarminge** [comment]
Sorry bout this, this is a regression from the introduction of built-in formdata and octet support where the node adapter uses this stuff.

We'll have a fix up shortly, for now just revert to the version before
