### ISSUE TITLE
bug: initializing websockets

### ISSUE THREAD

**Issue by Fesyse** [trpc/trpc#5663]
### Provide environment information

System:
    OS: Windows 10 10.0.19045
    CPU: (6) x64 Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz
    Memory: 6.53 GB / 15.94 GB
  Binaries:
    Node: 21.6.1 - C:\Program Files\nodejs\node.EXE
    npm: 10.2.4 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.0.4 - C:\Program Files\nodejs\pnpm.CMD
  Browsers: {}
  npmPackages:
    @tanstack/react-query: ^5.25.0 => 5.28.9
    @trpc/client: next => 11.0.0-rc.330+c89fb11f2
    @trpc/next: next => 11.0.0-rc.330+c89fb11f2
    @trpc/react-query: next => 11.0.0-rc.330+c89fb11f2
    @trpc/server: next => 11.0.0-rc.330+c89fb11f2
    next: ^14.2.2 => 14.2.2
    react: 18.2.0 => 18.2.0
    typescript: ^5.4.2 => 5.4.3

### Describe the bug

Websocket server is initializing with error: 
`Error: "headers" was called outside a request scope.`
The server is running and i can even connect to it, but when im trying to send a message to websocket it doesnt do much

**server/wsServer.ts**
```
export const initWebsocketServer = () => {
  const wss = new WebSocketServer({
    port: 3001,
  })

  const handler = applyWSSHandler({ wss, router: appRouter, createContext })

  wss.on("connection", ws => {
    console.log(`➕➕ Connection (${wss.clients.size})`)
    ws.once("close", () => {
      console.log(`➖➖ Connection (${wss.clients.size})`)
    })
  })
  console.log("✅ WebSocket Server listening on ws://localhost:3001")

  process.on("SIGTERM", () => {
    console.log("SIGTERM")
    handler.broadcastReconnectNotification()
    wss.close()
  })
}
```
**trpc/server.ts**
```
// checking if port is open or not, fixes the bug when file runs every time any file in project changes and port is already open
isPortOpen(3001).then(isOpen => (isOpen ? initWebsocketServer() : null))
```
**server/api/routers/message.ts**
```
const ee = new EventEmitter()

export const messagesRoute = createTRPCRouter({
  onAdd: protectedProcedure.subscription(({ ctx }) => {
    // return an `observable` with a callback which is triggered immediately
    return observable<Message>(emit => {
      const onAddMessage = (data: Message) => {
        // emit data to client
        emit.next(data)
      }
      ee.on("addMessage", onAddMessage)

      return () => {
        ee.off("addMessage", onAddMessage)
      }
    })
  }),
  add: protectedProcedure
    // ...
    .mutation(async ({ ctx, input: { content, conversationId } }) => {
      const message = await ctx.db.message.create({
        data: {
          content,
          userId: ctx.session.user.id,
          conversationId,
        },
      })

      ee.emit("addMessage", message)
      return message
    }),
})
```

### Link to reproduction

https://github.com/Fesyse/ysefy

### To reproduce

Source repo: <https://github.com/Fesyse/ysefy>

### Additional information

im using initWebSocket function, instead of just leaving intialization in wsServer.ts file as itself, because ws server is not running at all 

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/5663">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/5663/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/5663/pledge.svg">
</picture>
</a>

**Comment by Fesyse** [comment]
update: just tried to connect to websocket with insomnia, and it works i can even send something
so i think theres problem with message route itself or with createContext function (im passing it to applyWSSHandler)
```
export const createContext = cache(() => {
  const heads = new Headers(headers())
  heads.set("x-trpc-source", "rsc")

  return createTRPCContext({
    headers: heads,
  })
})
```

**Comment by Fesyse** [comment]
update: tried to check if im event "addMessage" is even existing on ws server
`setInterval(() => console.log(wss.eventNames()), 1000)`

the result: `[ 'connection' ]`
so it doesnt even adding listeners on it

after 20 mins as i was writing this comment, ws server is not even running anymore, i didnt change anything in wsServer.ts
```
export const initWebsocketServer = () => {
  const wss = new WebSocketServer({
    port: 3001,
  })

  const handler = applyWSSHandler({ wss, router: appRouter, createContext })

  wss.on("connection", ws => {
    setInterval(() => console.log(ws.url), 1000)
    console.log(`➕➕ Connection (${wss.clients.size})`)
    ws.once("close", () => {
      console.log(`➖➖ Connection (${wss.clients.size})`)
    })
  })
  console.log("✅ WebSocket Server listening on ws://localhost:3001")

  process.on("SIGTERM", () => {
    console.log("SIGTERM")
    handler.broadcastReconnectNotification()
    wss.close()
  })
}
```

**Comment by KATT** [comment]
@Fesyse I'm guessing you solved it for yourself?
