### ISSUE TITLE
feat: Expose `TRPCBuilder` class or interface

### ISSUE THREAD

**Issue by opiation** [trpc/trpc#5666]
### Describe the feature you'd like to request

I'd like to be able to use TRPC in vanilla JavaScript using JSDoc and TypeScript for type-checking. To define a context type, the TRPC API expects that we use type parameters like so:

```typescript
const t = initTRPC.context<MyAppContext>().create();
```

This is convenient when using TypeScript but not usable in JavaScript to get correctly-typed contexts. In many cases, the absence of type parameters in some APIs can be compensated for by specifying the type of the variable that gets the return value. e.g.:

```typescript
// TypeScript library
declare function example<ExplicitType>(): MyCollection<ExplicitType>

// JavaScript call site
/** @type {MyCollection<ExplicitType>} */
const collection = example();
```

Unfortunately, the type returned by `initTRPC.context()` (`TRPCBuilder<...>`) is not exported so that's not an option and if I instead annotate the type returned by `.create()` after it, the return type of `create` is an object literal that's even more verbose so annotating that type would be extremely cumbersome and defeats the purpose of the existing API.

### Describe the solution you'd like to see

Export the `TRPCBuilder` class or at least its type as that would make it trivial to annotate the context type with JSDoc like so:

```javascript
import { initTRPC } from "@trpc/server";

/** @type {import("@trpc/server").TRPCBuilder<{ ctx: MyAppContext }>} */
const init = initTRPC.context();

const t = init.create(); // explicitly typed context for procedures, middleware and subscriptions.
```

### Describe alternate solutions

Explicitly define and export the type returned by `TRPCBuilder#create()` so the initial workaround I described could work 🤷?

### Additional information

This was requested before in #4145 but was closed because no example use case was provided. Some example was provided later but the thread was locked shortly after. Since type-checking JavaScript with JSDoc annotations leverages TypeScript's excellent type checker without build tools, this seems like a valid use case to support.

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

**Comment by KATT** [comment]
> I'd like to be able to use TRPC in vanilla JavaScript using JSDoc and TypeScript for type-checking

why?

**Comment by opiation** [comment]
> > I'd like to be able to use TRPC in vanilla JavaScript using JSDoc and TypeScript for type-checking
> 
> why?

Using JavaScript with TypeScript syntax in JSDoc annotations grants all the benefits of the type checker without the need for any build tools, source maps, etc at the expense of a little verbosity. I've been writing type-checked code like this for a few years now but it seems like a more supportable use case now since bigger OSS projects like [Svelte have also gone this route](https://news.ycombinator.com/item?id=35892250).

I appreciate the type inference and type parameters being important part of TRPC's convenient API. Is there something about `TRPCBuilder` that requires it being private even though `initTRPC` is an exported instance of this class?
