### ISSUE TITLE
feat: Lazy load WS connection as needed

### ISSUE THREAD

**Issue by sean256** [trpc/trpc#5683]
### Describe the feature you'd like to request

I'm using a split link so only subscriptions go over web sockets. It would be very nice if the WS connection didn't open until an active subscription is initiated.

For context, here is how I'm using splitLink
```
splitLink({
	condition(op) {
		return op.type === 'subscription';
	},
	true: wsLink({
		client: wsClient,
	}),
	false: httpBatchLink({
		url: '/trpc',
	}),
}),
```

### Describe the solution you'd like to see

`wsLink` should only create a ws client when needed.

### Describe alternate solutions

Haven't found one yet...

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/5683">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/5683/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/5683/pledge.svg">
</picture>
</a>

**Comment by KATT** [comment]
Already available in v11
