### ISSUE TITLE
bug: 'hashQueryKey' is not exported from '@tanstack/react-query'

### ISSUE THREAD

**Issue by TheOrcDev** [trpc/trpc#5698]
### Provide environment information

```
System:
    OS: macOS 14.4.1
    CPU: (10) arm64 Apple M2 Pro
    Memory: 47.42 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.6.1 - /opt/homebrew/bin/node
    Yarn: 4.0.0 - /opt/homebrew/bin/yarn
    npm: 10.5.0 - /opt/homebrew/bin/npm
    pnpm: 8.6.0 - /usr/local/bin/pnpm
  Browsers:
    Chrome: 124.0.6367.119
    Safari: 17.4.1
  npmPackages:
    @tanstack/react-query: ^5.32.1 => 5.32.1
    @trpc/client: 10.45.2 => 10.45.2
    @trpc/next: 10.45.2 => 10.45.2
    @trpc/react-query: 10.45.2 => 10.45.2
    @trpc/server: 10.45.2 => 10.45.2
    next: 14.2.3 => 14.2.3
    react: ^18.3.1 => 18.3.1
    typescript: ^5.4.5 => 5.4.5
```

### Describe the bug

After updating tRPC to `v10.45.2` on Next.js

Getting this error:
```
Attempted import error: 'hashQueryKey' is not exported from '@tanstack/react-query' (imported as 'hashQueryKey').
```

### Link to reproduction

https://github.com/TheOrcDev/orcish-ai-nextjs-framework

### To reproduce

https://github.com/TheOrcDev/orcish-ai-nextjs-framework

Do `pnpm up --latest` on the repo, and try to run the project.

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/5698">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/5698/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/5698/pledge.svg">
</picture>
</a>

**Comment by TheOrcDev** [comment]
Update: After downgrading `@tanstack/react-query` from `v5.32.0` to `v4.18.0`, everything is working.

So temporary solution is to put this inside `package.json`

```
"@tanstack/react-query": "^4.18.0"
```

**Comment by KATT** [comment]
If you want to use RQ 5, use trpc v11. You likely had peer dependency warnings that you didn't see ahead of encountering this bug

**Comment by TheOrcDev** [comment]
> If you want to use RQ 5, use trpc v11. You likely had peer dependency warnings that you didn't see ahead of encountering this bug

tRPC 11 is still in beta.
