### ISSUE TITLE
bug: cannot get router type output

### ISSUE THREAD

**Issue by Yorizel** [trpc/trpc#5705]
### Provide environment information

 System:
    OS: Windows 10 10.0.19045
    CPU: (16) x64 Intel(R) Xeon(R) CPU E5-2650 v2 @ 2.60GHz
    Memory: 6.51 GB / 15.94 GB
  Binaries:
    Node: 20.12.2 - C:\Program Files\nodejs\node.EXE
    npm: 10.5.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.0.6 - ~\AppData\Roaming\npm\pnpm.CMD
    bun: 1.1.6 - ~\AppData\Roaming\npm\bun.CMD
  Browsers:
    Edge: Chromium (124.0.2478.51)
    Internet Explorer: 11.0.19041.3636

### Describe the bug

Cannot get infered type on route

![image](https://github.com/trpc/trpc/assets/64708198/9c3bb03b-d498-4202-8a59-7abc19e3cfd4)

![image](https://github.com/trpc/trpc/assets/64708198/9cac0d0d-a24e-44dd-9799-80821d035f5e)

### Link to reproduction

a

### To reproduce

Cannot get infered type on route

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/5705">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/5705/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/5705/pledge.svg">
</picture>
</a>

**Comment by KATT** [comment]
Hey again 👋 

We appreciate you taking the time to report this issue.

Unfortunately, we don't have the capacity to assist with issues without a reproduction repository and this issue does not seem to be related to tRPC itself (we test this code and use it in prod a lot) and it's also missing a reproduction. 

For effective assistance, reopening the issue with a reproduction repository would be immensely helpful. Alternatively, you can try to get help on our [Discord](https://trpc.io/discord) or in [GitHub Discussions](https://github.com/trpc/trpc/discussions).

Thank you for your understanding and cooperation!
