### ISSUE TITLE
bug: Dependency mismatch for `@tanstack/react-query`

### ISSUE THREAD

**Issue by danielz-mnx** [trpc/trpc#5729]
### Provide environment information

```
  System:
    OS: macOS 14.4.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 32.08 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
    Yarn: 1.22.21 - ~/.nvm/versions/node/v20.9.0/bin/yarn
    npm: 10.1.0 - ~/.nvm/versions/node/v20.9.0/bin/npm
    pnpm: 9.1.1 - ~/Library/pnpm/pnpm
    Watchman: 2024.04.08.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 124.0.6367.209
    Safari: 17.4.1
  npmPackages:
    @tanstack/react-query: ^5.37.1 => 5.37.1 
    @trpc/client: ^10.45.2 => 10.45.2 
    @trpc/react-query: ^10.45.2 => 10.45.2 
    @trpc/server: ^10.45.2 => 10.45.2 
    react: ^18.3.1 => 18.3.1 
    typescript: ^5.4.5 => 5.4.5 
```

### Describe the bug

`@trpc/react-query` complains about missing peer dependency because of mismatch between what's in [github](https://github.com/trpc/trpc/blob/next/packages/react-query/package.json) and what is published in [npm](https://www.npmjs.com/package/@trpc/react-query?activeTab=code)
```
pkg/app
├─┬ @trpc/react-query 10.45.2
│ └── ✕ unmet peer @tanstack/react-query@^4.18.0: found 5.37.1
```

### Link to reproduction

https://stackblitz.com/github/trpc/examples-next-minimal-starter

### To reproduce

run the following commands in the shell:
```
pnpm rm @trpc/react-query
pnpm i @trpc/react-query
```

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/5729">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/5729/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/5729/pledge.svg">
</picture>
</a>

**Comment by KATT** [comment]
Use trpc v11 if you want to us RQ v5 

https://github.com/trpc/trpc/issues/4218#issuecomment-1902763406
