### ISSUE TITLE
docs: httpBatchLink can only be used with API Gateway + Lambda if using a single resource for the router

### ISSUE THREAD

**Issue by andrestone** [trpc/trpc#5738]
### Area of Improvement

Maybe it's worth mentioning this in the docs. 

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing the suggested changes!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/5738">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/5738/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/5738/pledge.svg">
</picture>
</a>

**Comment by KATT** [comment]
I'm sorry, I don't follow?

Could you just go to the page in question and edit it? I don't use the lambda adapter myself
