### ISSUE TITLE
bug: Disconnected subscriptions don't re-subscribe after reconnecting

### ISSUE THREAD

**Issue by SiNONiMiTY** [trpc/trpc#5748]
### Provide environment information

"@trpc/client": "11.0.0-rc.374",
"@trpc/server": "11.0.0-rc.374",

### Describe the bug

Disconnected subscriptions don't re-subscribe after reconnecting. This can be caused by intermittent network connections.

### Link to reproduction

N/A

### To reproduce

- Create a simple subscription
- Use it in the client
- Terminate the server
- Check the client as it attempts to reconnect
- Bring back the server online
- Client will be connected once again, but the subscriptions are never restored

### Additional information

Add a way to catch/detect broken connections? onError and onStop does not detect broken network connections

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/5748">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/5748/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/5748/pledge.svg">
</picture>
</a>

**Comment by KATT** [comment]
I'm fairly confident we have tests for exactly this but we will double-check if we can repro

**Comment by KATT** [comment]
I'm fairly confident we have tests for exactly this but we will double-check if we can repro

**Comment by SiNONiMiTY** [comment]
Thanks @KATT, I have been double checking this on my end and simply cannot see the subscription resuming

Here is a sample. This is the first connection attempt

![image](https://github.com/trpc/trpc/assets/9588282/b83660ff-aefe-4411-bf5a-839369db7689)

Afterwards, I turned off the backend server for a few seconds. You will notice that while the WebSocket was able to reconnect. The subscription was never resumed.

![image](https://github.com/trpc/trpc/assets/9588282/2a51f0bb-fd28-4274-9e77-52634d8f1e61)

**Comment by KATT** [comment]
We were skipping that test because it was flaky and forgot to add it back before we (assumingly) broke it 😬

**Comment by KATT** [comment]
Will have a look at this sometime during the week

**Comment by KATT** [comment]
I need a reproduction - I tested this more properly (and revived our old tests in #5778)

You can test yourself by running using our [standalone-server](https://github.com/trpc/trpc/tree/next/examples/standalone-server) example and uncomment the stuff that stops the subscription: https://github.com/trpc/trpc/blob/076ab93081fb2c063ba5935bfc119db89666a1b6/examples/standalone-server/src/client.ts#L53-L57

And run `dev:server` and `dev:client` in separate tabs. The client's subscription will seamlessly resume after it has reconnected

**Comment by KATT** [comment]
Here's an example: 

https://stackblitz.com/edit/github-6askkg?file=src%2Fserver.ts,src%2Fclient.ts&terminal=dev&view=editor


https://github.com/trpc/trpc/assets/459267/fed90359-c5dd-4956-9171-d42eafa8fcc4

**Comment by SiNONiMiTY** [comment]
I will create a minimal reproduction and post it here.

**Comment by SiNONiMiTY** [comment]
@KATT

I forgot to mention that I am using the tRPC/Fastify Adapter

Reproduction
https://stackblitz.com/~/github.com/SiNONiMiTY/trpc-trpc-issue-5748

Subscription do resume when `broadcastReconnectNotification` is enabled in Fastify
https://github.com/SiNONiMiTY/trpc-trpc-issue-5748/blob/9146ef82fe61f613673a95a28e1ae4684301e23b/packages/backend/src/fastify/handler.ts#L57

However, not all disconnection issues are caused by the API server stopping, some are caused by bad network connectivity.

I purposely removed the event handlers for `broadcastReconnectNotification` to see if the subscriptions can still reconnect when the reconnect notification was not received.

**Comment by SiNONiMiTY** [comment]
I forgot to mention that I am using the tRPC/Fastify Adapter

Subscription do resume when `broadcastReconnectNotification` is enabled in Fastify
https://github.com/SiNONiMiTY/trpc-trpc-issue-5748/blob/9146ef82fe61f613673a95a28e1ae4684301e23b/packages/backend/src/fastify/handler.ts#L57

However, not all disconnection issues are caused by the API server stopping, some are caused by bad network connectivity.

I purposely removed the event handlers for `broadcastReconnectNotification` to see if the subscriptions can still reconnect when the reconnect notification was not received.

**Comment by KATT** [comment]
Would you mind giving me a full line of bash that I can use to run this? Or a smaller repro

It really shouldn't matter if you use fastify or not - resuming subscriptions is handled by the WS link / client - I'm still a bit skeptical it's a bug and not a problem with the usage

**Comment by SiNONiMiTY** [comment]
You will be needing 2 terminals, one for the frontend & the backend

frontend
`cp packages/frontend/.env.example packages/frontend/.env`
`cd packages/frontend`
`pnpm dev`

backend
`cp packages/frontend/.env.example packages/backend/.env`
`cd packages/backend`
`pnpm dev`

**Comment by KATT** [comment]
![CleanShot 2024-06-09 at 12 29 24@2x](https://github.com/trpc/trpc/assets/459267/5e141fbd-506d-45e6-93c7-dae53881470d)

**Comment by KATT** [comment]
Might be your client setup that is wrong - does `trpcClientStore` ever yield multiple instances? I don't know why it isn't just an exported object but I also don't know Svelte

**Comment by SiNONiMiTY** [comment]
> Might be your client setup that is wrong - does `trpcClientStore` ever yield multiple instances? I don't know why it isn't just an exported object but I also don't know Svelte

I will also take a look at this angle @KATT

**Comment by SiNONiMiTY** [comment]
> ![CleanShot 2024-06-09 at 12 29 24@2x](https://private-user-images.githubusercontent.com/459267/337965015-5e141fbd-506d-45e6-93c7-dae53881470d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc5MzM2MDEsIm5iZiI6MTcxNzkzMzMwMSwicGF0aCI6Ii80NTkyNjcvMzM3OTY1MDE1LTVlMTQxZmJkLTUwNmQtNDVlNi05M2M3LWRhZTUzODgxNDcwZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwOVQxMTQxNDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZmYzYmYxYmU1NjRlZDI0N2YxY2NlNmNmYjYyZThkYWM3OGZlODFhNWYyZmE0Njg4ZDFhMTRmOTBiZWJmNzc5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.An8I_3VBIBoPYtoCA5c_H_gbDvK9FgG883kWOlNh_j8)

This error occurs when the environment variable APP_CORS_ALLOWED_HOSTS was not defined or the .env file was not read

**Comment by SiNONiMiTY** [comment]
> Might be your client setup that is wrong - does `trpcClientStore` ever yield multiple instances? I don't know why it isn't just an exported object but I also don't know Svelte

Tested just right now, did not use a store for the client, just the plain `createTRPCClient` declaration. Same problem :(

**Comment by SiNONiMiTY** [comment]
@KATT I have deployed an application using this stripped down template. For some reason, the Subscriptions are working as expected without further changes to the code. Will investigate as to why on local development, it does not resume whereas on the actual deployment, it works.

**Comment by KATT** [comment]
Ok, will close. this, feel free to open a new issue if you think it's on tRPC's side.
