### ISSUE TITLE
docs: Missing App Router information

### ISSUE THREAD

**Issue by Qodestackr** [trpc/trpc#5749]
### Area of Improvement

Is there any enough information on how to build with Nextjs 14 with App router, I mean stable recommended guides.

### 👨‍👧‍👦 Contributing

- [x] 🙋‍♂️ Yes, I'd be down to file a PR implementing the suggested changes!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/5749">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/5749/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/5749/pledge.svg">
</picture>
</a>

**Comment by infodusha** [comment]
It all depends of your needs, in general you have tho choises:
In case you want to use _server actions_ via tRPC layer then the only way to go is experimental for now - [blog post](https://trpc.io/blog/trpc-actions)
In case you don't really need server actions, but the thing you are reffering to for app router is RSC, that the way is to have [tprc as data layer](https://trpc.io/docs/server/server-side-calls) for RSC and[ regular react-query integration](https://trpc.io/docs/client/react/setup) for client components. You can get the template of this setup with [t3-app](https://github.com/t3-oss/create-t3-app)

**Comment by ceejay-ai** [comment]
> It all depends of your needs, in general you have tho choises: In case you want to use _server actions_ via tRPC layer then the only way to go is experimental for now - [blog post](https://trpc.io/blog/trpc-actions) In case you don't really need server actions, but the thing you are reffering to for app router is RSC, that the way is to have [tprc as data layer](https://trpc.io/docs/server/server-side-calls) for RSC and[ regular react-query integration](https://trpc.io/docs/client/react/setup) for client components. You can get the template of this setup with [t3-app](https://github.com/t3-oss/create-t3-app)

using this app directory. and the caller api, I cant seem to get useInfiniteQuery. please how do i achieve that ?

**Comment by infodusha** [comment]
> it correctly automatically infers useQuery
Actually, it just infers the inputs. If you refer to the part that has triggers to load next page and all of that when you say "i want to use infinite query", that is not possible at all (all the server components have to be stateless).

However, you can put your page in queryParams and call `router.navigate` once the page gets changed to load more date up to your page.

Alternatively you could use server action that triggers next page to get what you want.

Also, the easiest way would be just to use `.useInfiniteQuery` and there initial data with the first page

**Comment by ceejay-ai** [comment]
> > it correctly automatically infers useQuery
> > Actually, it just infers the inputs. If you refer to the part that has triggers to load next page and all of that when you say "i want to use infinite query", that is not possible at all (all the server components have to be stateless).
> 
> However, you can put your page in queryParams and call `router.navigate` once the page gets changed to load more date up to your page.
> 
> Alternatively you could use server action that triggers next page to get what you want.
> 
> Also, the easiest way would be just to use `.useInfiniteQuery` and put there `initialData` with the first page

.useInfinteQuery is not available in that API at all, that was my point

**Comment by KATT** [comment]
> [!NOTE]  
> - **Your procedure needs to accept a `cursor` input of any type (`string`, `number`, etc) to expose this hook.**
> - [ ...]
> 
> — https://trpc.io/docs/client/react/useInfiniteQuery

**Comment by KATT** [comment]
We have docs and a blog post now and more is coming, reopen specific requests of what is missing (or just do a PR) please 🙏
