### ISSUE TITLE
bug: WebSockets not working with Bun 1.1.12

### ISSUE THREAD

**Issue by jnsdrssn** [trpc/trpc#5781]
### Provide environment information

```
  System:
    OS: macOS 14.4.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 126.83 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
    Yarn: 1.22.21 - ~/.nvm/versions/node/v20.9.0/bin/yarn
    npm: 10.1.0 - ~/.nvm/versions/node/v20.9.0/bin/npm
    pnpm: 9.2.0 - ~/Library/pnpm/pnpm
    bun: 1.1.12 - ~/.bun/bin/bun
  Browsers:
    Chrome: 125.0.6422.142
    Safari: 17.4.1
  npmPackages:
    @trpc/client: npm:@trpc/client@next => 11.0.0-rc.396+e2bcb75a9
    @trpc/react-query: npm:@trpc/react-query@next => 11.0.0-rc.396+e2bcb75a9
    @trpc/server: npm:@trpc/server@next => 11.0.0-rc.396+e2bcb75a9
    typescript: ^5.4.0 => 5.4.5
```

### Describe the bug

When using the `standalone-server` example with bun, subscriptions are not working.
Expected output of client:
```
Waiting for localhost:2022.
Connected!
helloResponse Hello, world!
createPostResponse {
  id: '0.7195333754303633',
  title: 'hello world',
  text: 'check out https://tRPC.io'
}
received { randomNumber: 0.46011740304710946 }
received { randomNumber: 0.20228265360227604 }
received { randomNumber: 0.4908613495972599 }
received { randomNumber: 0.1502009201762743 }
```

Output of client when using bun
```
Waiting for localhost:2022.
Connected!
helloResponse Hello, world!
createPostResponse {
  id: "0.2480596888928387",
  title: "hello world",
  text: "check out https://tRPC.io",
}
```

### Link to reproduction

https://github.com/jnsdrssn/standalone-server-bun/tree/main

### To reproduce
Clone the repo, then
`bun install` then `bun dev:server` then `bun dev:client`

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/5781">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/5781/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/5781/pledge.svg">
</picture>
</a>

**Comment by KATT** [comment]
Please create the issue in Bun instead - Bun should be compatible with Node.js

**Comment by jnsdrssn** [comment]
Thanks for the quick response.
Opened an issue for bun: https://github.com/oven-sh/bun/issues/11728
