### ISSUE TITLE
bug: quick start does not work

### ISSUE THREAD

**Issue by misogihagi** [trpc/trpc#5788]
### Provide environment information

package.json:

```json
{
  "name": "trpctest",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
"type":"module",
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@trpc/server": "^10.45.2",
    "zod": "^3.23.8"
  }
}
```

### Describe the bug

I followed the quick start but it didn't work. although simplified.

### Link to reproduction

none

### To reproduce

here is simple trpc server

```javascript
import { initTRPC } from '@trpc/server';
import { z } from 'zod';
import { createHTTPServer } from '@trpc/server/adapters/standalone';

const t = initTRPC.create();

const router = t.router;
const publicProcedure = t.procedure;

const colors=['red','blue','green']

const appRouter = router({
  color: publicProcedure
    .input(z.string())
    .query((req) => {
      const { input } = req;
      return colors[Number(input)]
  }),
});

  
const server = createHTTPServer({
  router: appRouter,
});
 
server.listen(3000);
```
and my client

```javascript
import { createTRPCProxyClient, httpBatchLink } from '@trpc/client';

export const tRPClient = createTRPCProxyClient({
    links: [
      httpBatchLink({
        url: '/trpc',
      }),
    ],
});

const result=tRPClient.color.query('1')
result.then(console.log);  
```

but with tweaking, works fine.

```diff
import { initTRPC } from '@trpc/server';
import { z } from 'zod';
import { createHTTPServer } from '@trpc/server/adapters/standalone';

const t = initTRPC.create();

const router = t.router;
const publicProcedure = t.procedure;

const colors=['red','blue','green']

const appRouter = router({
  color: publicProcedure
>     .input(data => z.string().parse(data.json))
<     .input(z.string())
    .query((req) => {
      const { input } = req;
      return colors[Number(input)]
  }),
});

  
const server = createHTTPServer({
  router: appRouter,
});
 
server.listen(3000);
```

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/5788">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/5788/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/5788/pledge.svg">
</picture>
</a>

**Comment by KATT** [comment]
Click the edit button at the page your found it at and submit a PR? :)

**Comment by misogihagi** [comment]
If this is a specification rather than a bug, this would seem to apply to all examples.
Are there any related issues?

**Comment by KATT** [comment]
uhm where is the quick start that showed you the code above? 

it looks fine here https://trpc.io/docs/quickstart#3-using-input-parser-to-validate-procedure-inputs

**Comment by misogihagi** [comment]
The examples I have shown, the examples you have shown, and the examples other documents have shown all seem to be the same.
After much trial and error, my client may be wrong?
My client's request is
```
http://localhost:3000/trpc/color?batch=1&input=%7B%220%22%3A%7B%22json%22%3Anull%2C%22meta%22%3A%7B%22values%22%3A%5B%22undefined% 22%5D%7D%7D
```
Is this current client behavior?
