### ISSUE TITLE
Pages Router: ReadableStream accessible only at the end of generator / (unstable_httpBatchStreamLink, iterablesAndDeferreds)

### ISSUE THREAD

**Issue by hsab** [trpc/trpc#5794]
### Provide environment information

```
  System:
    OS: Linux 6.6 Manjaro Linux
    CPU: (32) x64 AMD Ryzen Threadripper 1950X 16-Core Processor
    Memory: 50.62 GB / 62.65 GB
    Container: Yes
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 18.19.0 - ~/.nvm/versions/node/v18.19.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.19.0/bin/yarn
    npm: 10.5.0 - ~/.nvm/versions/node/v18.19.0/bin/npm
    pnpm: 9.3.0 - ~/.local/share/pnpm/pnpm
  Browsers:
    Brave Browser: 125.1.66.118
    Chromium: 126.0.6478.55
  npmPackages:
    @tanstack/react-query: ^5.45.0 => 5.45.0 
    @trpc/client: 11.0.0-rc.401 => 11.0.0-rc.401+91720833b 
    @trpc/next: 11.0.0-rc.401 => 11.0.0-rc.401+91720833b 
    @trpc/react-query: 11.0.0-rc.401 => 11.0.0-rc.401+91720833b 
    @trpc/server: 11.0.0-rc.401 => 11.0.0-rc.401+91720833b 
    next: ^14.1.4 => 14.2.4 
    react: ^18.3.1 => 18.3.1 
    typescript: ^5.4.0 => 5.4.5 
```

### Describe the bug

I've been experimenting with generators following this [example](https://trpc.io/docs/client/links/httpBatchStreamLink#generators) to build LLM powered chatbots. The issue I'm running into is that the response is not really "streamed" but essentially accumulates until the end of the iterator and is then returned as a whole. 

The video below demonstrates this in more detail. My expectation is that numbers show up on the client (left white screen) as they are printed to the console. 

**EDIT**: I also explored this problem without hooks, using trpc.utils to no avail. 

https://github.com/trpc/trpc/assets/11205091/e8fb8291-4979-46f0-8721-d7aa6c768543

**EDIT 2**: Seems like the the client waits for the entire generator to finish before making the response accessible? I can see that streaming works as expected when using curl. But on the browser it's buffered until finish, and then made available. 

https://github.com/trpc/trpc/assets/11205091/e12e4676-0511-4550-9391-c2d361f339ba

### Link to reproduction

https://stackblitz.com/github/trpc/examples-next-minimal-starter

### To reproduce

Adjust the starter with the following files

`package.json`
```json
{
  "name": "examples-next-minimal",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "lint": "eslint --cache --ext \".js,.ts,.tsx\" src",
    "start": "next start"
  },
  "dependencies": {
    "@tanstack/react-query": "^5.45.0",
    "@trpc/client": "11.0.0-rc.401",
    "@trpc/next": "11.0.0-rc.401",
    "@trpc/react-query": "11.0.0-rc.401",
    "@trpc/server": "11.0.0-rc.401",
    "next": "^14.1.4",
    "react": "^18.3.1",
    "react-dom": "^18.3.1",
    "zod": "^3.0.0"
  },
  "devDependencies": {
    "@types/node": "^20.10.0",
    "@types/react": "^18.3.1",
    "@types/react-dom": "^18.3.0",
    "eslint": "^8.56.0",
    "typescript": "^5.4.0"
  }
}

```

`server/trpc.ts`
```tsx

import { initTRPC } from "@trpc/server";

const t = initTRPC.create({
  experimental: {
    iterablesAndDeferreds: true,
  }
});

export const publicProcedure = t.procedure;

export const router = t.router;
```

`pages/api/trpc/[trpc].ts`
```tsx
import * as trpcNext from "@trpc/server/adapters/next";
import { publicProcedure, router } from "~/server/trpc";

const appRouter = router({
  iterable: publicProcedure.query(async function* () {
    for (let i = 0; i < 15; i++) {
      await new Promise((resolve) => setTimeout(resolve, 500));
      console.log(i);
      yield i;
    }
  }),
});

export type AppRouter = typeof appRouter;

export default trpcNext.createNextApiHandler({
  router: appRouter,
  createContext: () => ({}),
});
```

`utils/trpc.ts`
```tsx
import { unstable_httpBatchStreamLink } from "@trpc/client";
import { createTRPCNext } from "@trpc/next";
import { ssrPrepass } from "@trpc/next/ssrPrepass";
import type { AppRouter } from "../pages/api/trpc/[trpc]";

function getBaseUrl() {
  if (typeof window !== "undefined") return "";
  if (process.env.VERCEL_URL) return `https://${process.env.VERCEL_URL}`;
  return `http://localhost:${process.env.PORT ?? 3000}`;
}

export const trpc = createTRPCNext<AppRouter>({
  config() {
    return {
      links: [
        unstable_httpBatchStreamLink({
          url: getBaseUrl() + "/api/trpc",
        }),
      ],
    };
  },
  ssr: true,
  ssrPrepass,
});
```

`pages/index.tsx`
```tsx
export default function IndexPage() {
  const query = trpc.iterable.useQuery(undefined, {
    enabled: true,
    gcTime: 0,
    staleTime: 0,
  });

  useEffect(() => {
    query.refetch();
  }, [])
  
  return (
    <div style={styles}>
       Data:
      {query.data?.length && query.data?.map((chunk, index) => (
        <Fragment key={index}>{chunk}</Fragment>
      ))}
    </div>
  );
}
```

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/5794">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/5794/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/5794/pledge.svg">
</picture>
</a>

**Comment by hsab** [comment]
Upon further examination I can see that this is not an issue with the server. Seems like something on the client needs to be adjusted? Or maybe I'm having a hard time wrapping my head around how `useQuery` / `utils.query()` operate?


https://github.com/trpc/trpc/assets/11205091/25f3bc6f-7478-4ab0-b2c3-076d2cc71c1a

**Comment by KATT** [comment]
The network tab in chrome is a bit weird with streamed responses so it does show as "blank" until it's done

You can see that the [minimal example](https://github.com/trpc/trpc/tree/next/examples) does work:

Uploading CleanShot 2024-06-14 at 15.11.43.mp4…

g
Where do you deploy? If you deploy on Vercel you have to use the fetch adapter to get streaming working, their lambda adapter doesn't support it (AFAIK)

And yes, in React query you get `data` as an array that continuously update, here's the test: https://github.com/trpc/trpc/blob/3b26c27d5a2b202dc2b4e99d1a29b7e82a8c42a5/packages/tests/server/react/useQuery.test.tsx#L229-L318

The documentation for `useQuery()` it iterators you can find here: https://trpc.io/docs/client/react/useQuery#streaming


Maybe something is missing from the documentation? I don't think what you're encountering is a bug

**Comment by hsab** [comment]
Hey @KATT  thank you for the thoughtful response. I can confirm that the server works fine, something is missing on the client and I can't figure it out. This is an example repository that I'm investigating the issue in:
https://github.com/hsab/trpc-issue-5794

Once I run the dev server, I can confirm server behaves as expected with 
```bash
curl -H "Accept:application/json" --location 'http://localhost:3000/api/trpc/iterable' \
--header 'trpc-accept: application/jsonl' --no-buffer
```

But the client is giving me a hard time. For production I deploy to Vercel. But the prod repo is pretty complex, and I'm using the App router.

I feel like if I can figure this out in this test env, I should be able to easily port to my prod env.

**Comment by hsab** [comment]
Hey @KATT! I actually managed to get this working when using Next's App Router. Not sure why this is not working with the Pages Router. 

Here is the working repo using Next 14 and the app router: https://github.com/hsab/trpc-issue-5794-app-router

Would love to hear your thoughts

**Comment by KATT** [comment]
If there's any documentation that could've helped you, please find a related page and trpc.io and click the edit button 🙏 🙏

**Comment by hsab** [comment]
@KATT I wanted to edit the [docs](https://trpc.io/docs/client/links/httpBatchStreamLink#generators) but didn't find the elusive edit button :)) Just wanted to mention that adding a compatibility notice for Next.js would have been nice on the streaming doc page. 

Something along the lines of "For Next.js projects `fetchRequestHandler` must be used to support AsyncIterables. This requires using [Route Handlers](https://trpc.io/docs/server/adapters/nextjs#route-handlers). `createNextApiHandler` Does not support streaming"

Cheers

**Comment by KATT** [comment]
> @KATT I wanted to edit the [docs](https://trpc.io/docs/client/links/httpBatchStreamLink#generators) but didn't find the elusive edit button :)) Just wanted to mention that adding a compatibility notice for Next.js would have been nice on the streaming doc page.
> 
> Something along the lines of "For Next.js projects `fetchRequestHandler` must be used to support AsyncIterables. This requires using [Route Handlers](https://trpc.io/docs/server/adapters/nextjs#route-handlers). `createNextApiHandler` Does not support streaming"
> 
> Cheers

It does support streaming as long as you run a standalone server though
