### ISSUE TITLE
feat(react-query): `createTRPCQueryUtils` should support mutations

### ISSUE THREAD

**Issue by simonecervini** [trpc/trpc#5800]
### Provide environment information

```
  System:
    OS: macOS 14.5
    CPU: (10) arm64 Apple M1 Max
    Memory: 4.26 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.5.1 - ~/.nvm/versions/node/v20.5.1/bin/node
    npm: 9.8.0 - ~/.nvm/versions/node/v20.5.1/bin/npm
    bun: 1.0.25 - /opt/homebrew/bin/bun
  Browsers:
    Chrome: 126.0.6478.61
    Edge: 126.0.2592.56
    Safari: 17.5
  npmPackages:
    @tanstack/react-query: ^5.39.0 => 5.45.0
    @trpc/client: next => 11.0.0-rc.403+ab71a1be6
    @trpc/react-query: next => 11.0.0-rc.403+ab71a1be6
    @trpc/server: next => 11.0.0-rc.403+ab71a1be6
    next: ^14.2.1 => 14.2.4
    react: ^18.3.0 => 18.3.1
    typescript: ^5.4.2 => 5.4.5
```

### Describe the bug

The type of `createTRPCQueryUtils({ queryClient, client }).anyRouter.anyMutationProcedure` is always `never`.

If this is intentional, I believe it's not ideal, because there are some `queryClient` methods that can be useful for mutations, such as [queryClient.setMutationDefaults](https://tanstack.com/query/v5/docs/reference/QueryClient/#queryclientsetmutationdefaults), which is crucial for implementing proper offline mutation persistence (see https://github.com/trpc/trpc/discussions/5797)

### Link to reproduction

https://github.com/simonecervini/trpc-issue-mutations-create_trpc_query_utils

### To reproduce

Open `/src/app/page.tsx` and check the types of `ThisIsCorrectlyTyped` and `ThisIsNotCorrectlyTyped`

### Additional information

Probably related: https://discord-questions.trpc.io/m/1236883887871754260

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/5800">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/5800/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/5800/pledge.svg">
</picture>
</a>

**Comment by KATT** [comment]
This isn't a bug, but feel free to implement it or sponsor it with a few hundred dollars if you need it

**Comment by simonecervini** [comment]
@KATT Yeah, after looking into the tRPC code a bit more, I realized myself that it might not be a bug. 

However, I wasn't entirely sure because it seems that the implementation is generally very "query-centric," especially in the type definitions. For example, some parts of this work depend on `QueryType` defined for `getQueryKey`, which would need to be modified to also extend to mutations, and it's not clear to me why mutations were excluded from the `"any" | "infinite" | "query"` type, even after looking at the PR that introduced the function.

Moving on, do you think the `setMutationDefaults` function should be a pure wrapper of `queryClient.setMutationDefaults` from TanStack Query, or can we consider a more opinionated behavior? For example, it might be interesting (and reasonable in the context of tRPC) to be able to call `clientUtils.post.update.setMutationDefaults()` without arguments to automatically set the mutation function, which in a tRPC context might not make sense to modify.
