### ISSUE TITLE
bug: Infinite render loop when referencing utils as dependency

### ISSUE THREAD

**Issue by Csszabi98** [trpc/trpc#5808]
### Provide environment information

  System:
    OS: macOS 14.5
    CPU: (10) arm64 Apple M2 Pro
    Memory: 91.06 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.19.0 - ~/Library/Caches/fnm_multishells/3059_1718376229215/bin/node
    npm: 10.2.3 - ~/Library/Caches/fnm_multishells/3059_1718376229215/bin/npm
  Browsers:
    Brave Browser: 121.1.62.165
    Chrome: 126.0.6478.62
    Edge: 126.0.2592.61
    Safari: 17.5
  npmPackages:
    @tanstack/react-query: ^5.39.0 => 5.45.1
    @trpc/client: next => 11.0.0-rc.413+87f0cbc94
    @trpc/next: next => 11.0.0-rc.413+87f0cbc94
    @trpc/react-query: next => 11.0.0-rc.413+87f0cbc94
    @trpc/server: next => 11.0.0-rc.413+87f0cbc94
    next: ^14.2.1 => 14.2.4
    react: ^18.3.0 => 18.3.1
    typescript: ^5.4.2 => 5.4.5

### Describe the bug

When hook dependencies contain the result of the `trpc.useUtils` call, react will run into an infinite loop.

Expectation:

The returned objects from trpc.useUtils are stable and can be used as dependencies.

### Link to reproduction

https://github.com/Csszabi98/trpc-infinite-loop-bug

### To reproduce

```typescript
const hello = api.post.hello.useQuery({ text: "from tRPC" });
const utils = trpc.useUtils()

useEffect(() => {
   utils.post.hello.invalidate()
}, [utils.post.hello])

```

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/5808">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/5808/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/5808/pledge.svg">
</picture>
</a>

**Comment by KATT** [comment]
Does the same thing happen if you use `api` as a dep?

Not sure if we will fix this, it's a recursive proxy 🤔 🤔

**Comment by Csszabi98** [comment]
Indeed supplying the whole utils object as a dependency seems to work around the issue.
```typescript
useEffect(() => {
  void utils.post.hello.invalidate();
}, [utils]);
```

Nonetheless the LSP auto fix action (in VSCode) includes the whole path on the object by default, and it is quite easy to provide unstable dependencies this way to memoized values.

**Comment by KATT** [comment]
We fixed this but it caused other issues - reverting our fix for now
