### ISSUE TITLE
bug: useInfiniteQuery's `select` method expects wrong return type

### ISSUE THREAD

**Issue by abecks** [trpc/trpc#5809]
### Provide environment information

``` 
System:
    OS: macOS 14.1.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 63.06 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.1 - ~/.nvm/versions/node/v20.11.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.17.0/bin/yarn
    npm: 10.2.4 - ~/.nvm/versions/node/v20.11.1/bin/npm
    pnpm: 9.1.1 - ~/.nvm/versions/node/v20.11.1/bin/pnpm
  Browsers:
    Chrome: 126.0.6478.62
    Safari: 17.1
  npmPackages:
    @tanstack/react-query: ^5.45.1 => 5.45.1 
    @trpc/client: 11.0.0-rc.413 => 11.0.0-rc.413+87f0cbc94 
    @trpc/react-query: 11.0.0-rc.413 => 11.0.0-rc.413+87f0cbc94 
    @trpc/server: 11.0.0-rc.413 => 11.0.0-rc.413+87f0cbc94 
    react: ^18.3.1 => 18.3.1 
    typescript: ^5.3.3 => 5.3.3 
```

### Describe the bug

When using `useInfiniteQuery` with a `select` method, `select` expects `TQueryData` as the return type, instead of `InfiniteData<TQueryData>`

```
  const resultsQuery = trpc.response.list.useInfiniteQuery(
    {
      companyId: company._id,
    },
    {
      getNextPageParam: (lastData) => lastData.nextCursor,
      select: (data) => {
        return data
      },
    }
  )
  ```

This throws a TypeScript error on the `select` method. The `data` argument is typed as `InfiniteData`, but throws an error if it is returned without modification.

`is missing the following properties from type '{ data: ..., nextCursor: Date | undefined; }': data, nextCursor`

The difference here is that `InfiniteData` paginates the query data from the endpoint, resulting in an object that looks like this:
```
{
   pages: [],
   pageParams: []
}
```

but the `select` method seems to want the data for each individual page:
```
{
   data: ...,
   nextCursor: ...
}
```

This bug does not exist when using React Query by itself:

```
  useInfiniteQuery({
    queryKey: ['test'],
    queryFn: () => 1234,
    initialPageParam: 0,
    getNextPageParam: (lastPage) => lastPage + 1,
    select: (data) => {
      return data
    }
  })
  ```

No TypeScript errors are thrown.

### Link to reproduction

Template is broken 

### To reproduce

Use the `select` method with a `useInfiniteQuery`, and return the data without modification:

```
  const resultsQuery = trpc.response.list.useInfiniteQuery(
    {
      companyId: company._id,
    },
    {
      getNextPageParam: (lastData) => lastData.nextCursor,
      select: (data) => {
        return data
      },
    }
  )
  ```

As an aside, the StackBlitz minimal starter template appears to be broken:
```
   Downloading swc package @next/swc-wasm-nodejs...
 ⚠ Attempted to load @next/swc-linux-x64-gnu, but an error occurred: Cannot load native addon because loading addons is disabled: /home/projects/parippgbo.github/node_modules/.pnpm/@next+swc-linux-x64-gnu@14.2.4/node_modules/@next/swc-linux-x64-gnu/next-swc.linux-x64-gnu.node
 ⚠ Attempted to load @next/swc-linux-x64-musl, but an error occurred: Cannot load native addon because loading addons is disabled: /home/projects/parippgbo.github/node_modules/.pnpm/@next+swc-linux-x64-musl@14.2.4/node_modules/@next/swc-linux-x64-musl/next-swc.linux-x64-musl.node
 ⨯ Failed to load SWC binary for linux/x64, see more info here: https://nextjs.org/docs/messages/failed-loading-swc
 ```

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/5809">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/5809/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/5809/pledge.svg">
</picture>
</a>

**Comment by KATT** [comment]
Seems like we don't support `select()` on useInfiniteQuery, we need to pass some more generics over to tanstack query.

Wanna try to have a stab at this, @abecks?

- Code you should modify lives in https://github.com/trpc/trpc/blob/next/packages/react-query/src/createTRPCReact.tsx
- Test you should modify to assert it lives in https://github.com/trpc/trpc/blob/next/packages/tests/server/react/useInfiniteQuery.test.tsx
  - easiest is likely to copy the first test in that file and readapt 
  - you re-run tests by doing eg `pnpm test-watch useInfin`
