### ISSUE TITLE
bug: Improper server side max batch size handling

### ISSUE THREAD

**Issue by kishore03109** [trpc/trpc#5825]
### Provide environment information

  System:
    OS: macOS 12.6
    CPU: (8) arm64 Apple M1 Pro
    Memory: 86.84 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.20.3 - ~/.nvm/versions/node/v18.20.3/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 10.7.0 - ~/.nvm/versions/node/v18.20.3/bin/npm
  Browsers:
    Chrome: 126.0.6478.63
    Edge: 126.0.2592.68
    Safari: 16.0
  npmPackages:
    @tanstack/react-query: ^4.36.1 => 4.36.1 
    @trpc/client: 10.45.0 => 10.45.0 
    @trpc/next: 10.45.0 => 10.45.0 
    @trpc/react-query: 10.45.0 => 10.45.0 
    @trpc/server: 10.45.0 => 10.45.0 
    next: ^14.2.3 => 14.2.3 
    react: ^18.2.0 => 18.2.0 
    typescript: ^5.2.2 => 5.2.2 

### Describe the bug

Batching uses  `,` to separate different TRPC calls, and the size of the batch is limited to the header size. A payload could be crafted to just pass in a string of commas `,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,` which could be in the 
This can potentially lead to multiple 404s being returned for a single call. I would expect to have some sort of batch limiting that is enforced on the server side, but currently, the [documentation](https://trpc.io/docs/client/links/httpBatchLink#setting-a-maximum-url-length) limits it to the client side. 

### Link to reproduction

any trpc with batch enabled

### To reproduce

eg, for the request 
```
curl --request GET \
  --url '<url>/api/trpc/example.procedureName,,,,,,,,,,,,,,,,,,,,,,,?batch=1&input=<input that works for the first procedure>'
```

we get a return response 
```
[
	{
		"result": {
			"data": {
                <valid response for the first procedure call>
			}
		}
	},
	{
		"error": {
			"json": {
				"message": "No \"query\"-procedure on path \"\"",
				"code": -32004,
				"data": {
					"code": "NOT_FOUND",
					"httpStatus": 404,
					"path": "",
					"zodError": null
				}
			}
		}
	},
	{
		"error": {
			"json": {
				"message": "No \"query\"-procedure on path \"\"",
				"code": -32004,
				"data": {
					"code": "NOT_FOUND",
					"httpStatus": 404,
					"path": "",
					"zodError": null
				}
			}
		}
	},
	{
		"error": {
			"json": {
				"message": "No \"query\"-procedure on path \"\"",
				"code": -32004,
				"data": {
					"code": "NOT_FOUND",
					"httpStatus": 404,
					"path": "",
					"zodError": null
				}
			}
		}
	},
	{
		"error": {
			"json": {
				"message": "No \"query\"-procedure on path \"\"",
				"code": -32004,
				"data": {
					"code": "NOT_FOUND",
					"httpStatus": 404,
					"path": "",
					"zodError": null
				}
			}
		}
	},
	{
		"error": {
			"json": {
				"message": "No \"query\"-procedure on path \"\"",
				"code": -32004,
				"data": {
					"code": "NOT_FOUND",
					"httpStatus": 404,
					"path": "",
					"zodError": null
				}
			}
		}
	},
	{
		"error": {
			"json": {
				"message": "No \"query\"-procedure on path \"\"",
				"code": -32004,
				"data": {
					"code": "NOT_FOUND",
					"httpStatus": 404,
					"path": "",
					"zodError": null
				}
			}
		}
	},
	{
		"error": {
			"json": {
				"message": "No \"query\"-procedure on path \"\"",
				"code": -32004,
				"data": {
					"code": "NOT_FOUND",
					"httpStatus": 404,
					"path": "",
					"zodError": null
				}
			}
		}
	},
	{
		"error": {
			"json": {
				"message": "No \"query\"-procedure on path \"\"",
				"code": -32004,
				"data": {
					"code": "NOT_FOUND",
					"httpStatus": 404,
					"path": "",
					"zodError": null
				}
			}
		}
	},
	{
		"error": {
			"json": {
				"message": "No \"query\"-procedure on path \"\"",
				"code": -32004,
				"data": {
					"code": "NOT_FOUND",
					"httpStatus": 404,
					"path": "",
					"zodError": null
				}
			}
		}
	},
	{
		"error": {
			"json": {
				"message": "No \"query\"-procedure on path \"\"",
				"code": -32004,
				"data": {
					"code": "NOT_FOUND",
					"httpStatus": 404,
					"path": "",
					"zodError": null
				}
			}
		}
	},
	{
		"error": {
			"json": {
				"message": "No \"query\"-procedure on path \"\"",
				"code": -32004,
				"data": {
					"code": "NOT_FOUND",
					"httpStatus": 404,
					"path": "",
					"zodError": null
				}
			}
		}
	},
	{
		"error": {
			"json": {
				"message": "No \"query\"-procedure on path \"\"",
				"code": -32004,
				"data": {
					"code": "NOT_FOUND",
					"httpStatus": 404,
					"path": "",
					"zodError": null
				}
			}
		}
	},
	{
		"error": {
			"json": {
				"message": "No \"query\"-procedure on path \"\"",
				"code": -32004,
				"data": {
					"code": "NOT_FOUND",
					"httpStatus": 404,
					"path": "",
					"zodError": null
				}
			}
		}
	},
	{
		"error": {
			"json": {
				"message": "No \"query\"-procedure on path \"\"",
				"code": -32004,
				"data": {
					"code": "NOT_FOUND",
					"httpStatus": 404,
					"path": "",
					"zodError": null
				}
			}
		}
	},
	{
		"error": {
			"json": {
				"message": "No \"query\"-procedure on path \"\"",
				"code": -32004,
				"data": {
					"code": "NOT_FOUND",
					"httpStatus": 404,
					"path": "",
					"zodError": null
				}
			}
		}
	},
	{
		"error": {
			"json": {
				"message": "No \"query\"-procedure on path \"\"",
				"code": -32004,
				"data": {
					"code": "NOT_FOUND",
					"httpStatus": 404,
					"path": "",
					"zodError": null
				}
			}
		}
	},
	{
		"error": {
			"json": {
				"message": "No \"query\"-procedure on path \"\"",
				"code": -32004,
				"data": {
					"code": "NOT_FOUND",
					"httpStatus": 404,
					"path": "",
					"zodError": null
				}
			}
		}
	},
	{
		"error": {
			"json": {
				"message": "No \"query\"-procedure on path \"\"",
				"code": -32004,
				"data": {
					"code": "NOT_FOUND",
					"httpStatus": 404,
					"path": "",
					"zodError": null
				}
			}
		}
	},
	{
		"error": {
			"json": {
				"message": "No \"query\"-procedure on path \"\"",
				"code": -32004,
				"data": {
					"code": "NOT_FOUND",
					"httpStatus": 404,
					"path": "",
					"zodError": null
				}
			}
		}
	},
	{
		"error": {
			"json": {
				"message": "No \"query\"-procedure on path \"\"",
				"code": -32004,
				"data": {
					"code": "NOT_FOUND",
					"httpStatus": 404,
					"path": "",
					"zodError": null
				}
			}
		}
	},
	{
		"error": {
			"json": {
				"message": "No \"query\"-procedure on path \"\"",
				"code": -32004,
				"data": {
					"code": "NOT_FOUND",
					"httpStatus": 404,
					"path": "",
					"zodError": null
				}
			}
		}
	},
	{
		"error": {
			"json": {
				"message": "No \"query\"-procedure on path \"\"",
				"code": -32004,
				"data": {
					"code": "NOT_FOUND",
					"httpStatus": 404,
					"path": "",
					"zodError": null
				}
			}
		}
	},
	{
		"error": {
			"json": {
				"message": "No \"query\"-procedure on path \"\"",
				"code": -32004,
				"data": {
					"code": "NOT_FOUND",
					"httpStatus": 404,
					"path": "",
					"zodError": null
				}
			}
		}
	}
]
```

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/5825">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/5825/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/5825/pledge.svg">
</picture>
</a>

**Comment by KATT** [comment]
Your `createContext` receives an `info`-object with the batch calls, you can implement logic about that there

**Comment by KATT** [comment]
```ts
  if (opts.info.calls.length > 10) {
    throw new TRPCError({
      code: 'BAD_REQUEST',
      message: `You are making ${opts.info.calls.length} requests in a single call, which is not allowed`,
    });
  }
```

**Comment by KATT** [comment]
Feel free to make a PR to the documentation.

**Comment by KATT** [comment]
Closing this. Feel free to open a PR to the documentation or a more specific feature request.

There's no bug AFAICT, this should be handled in `createContext()`

**Comment by kishore03109** [comment]
Hey @KATT, I am not sure if I misunderstood this.

Following the [docs](https://trpc.io/docs/server/context), one can create a context as such
```
export const createContext = async (opts: CreateNextContextOptions) => {
 ...
}
```
This opts it typed to a `CreateNextContextOptions`, which only has `req` and `res`. When inspecting the object at runtime, I also could not find the key `info` on the `opts` object. 

I understand there is no documentation to refer to regarding limiting the batch size at the client side. Where can I refer to get more info of getting the `info` from the `opt` object?

**Comment by KATT** [comment]
Upgrade to v11 where we have that info property, we won't do any non-critical security issues on the v10 branch

https://github.com/trpc/trpc/blob/a63766476796e04c8157483409f25273618381f9/packages/server/src/adapters/node-http/types.ts#L94-L98

**Comment by KATT** [comment]
The main thing you need to do to upgrade

- Search & replace `onLoading` with `onPending`
- Move the `transformer` https://trpc.io/docs/migrate-from-v10-to-v11#transformers-are-moved-to-links-breaking

**Comment by kishore03109** [comment]
Hi @KATT, thanks for the timely response! 

I do differ in opinion on this being a non-critical security issue. When this is run in a dockerised environment, using just one api call but spamming the requests within just one batch, I was able to observe some level of DOS within the service. 

The below seems to fix this in v10. 
```
export const createContext = async (opts: CreateNextContextOptions) => {
  const trpcReq = opts.req.query.trpc
  const req = Array.isArray(trpcReq) ? _.flatten(trpcReq) : trpcReq
  const count = req?.toString().split(',').length || 0
  if (count > 10) {
    throw new TRPCError({ code: 'TOO_MANY_REQUESTS' })
  }

```

Would this be something that you would consider fixing in v10? 

[Outside the scope of this bug]
Noticed that the v11 branch is still in beta, am wondering if there are plans to release the non-beta branch soon. It seems like some of the libraries that we are using are expecting the stable branch to be in order to release support for [this](https://github.com/jlalmes/trpc-openapi/issues/434).
