### ISSUE TITLE
bug: Transformers break when `async/await` is used

### ISSUE THREAD

**Issue by codesfromshad** [trpc/trpc#5844]
### Provide environment information

```
  System:
    OS: Windows 11 10.0.22621
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Memory: 1.04 GB / 15.43 GB
  Binaries:
    Node: 20.14.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.7.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.15.4 - ~\AppData\Local\Microsoft\WinGet\Packages\pnpm.pnpm_Microsoft.Winget.Source_8wekyb3d8bbwe\pnpm.EXE
    bun: 1.1.15 - ~\.bun\bin\bun.EXE
  Browsers:
    Edge: Chromium (126.0.2592.81)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    @tanstack/react-query: ^5.39.0 => 5.44.0
    @trpc/client: next => 11.0.0-rc.401+91720833b
    @trpc/react-query: next => 11.0.0-rc.401+91720833b
    @trpc/server: next => 11.0.0-rc.401+91720833b
    next: ^14.2.4 => 14.2.4
    react: ^18.3.1 => 18.3.1
    typescript: ^5.4.2 => 5.4.5
```

### Describe the bug

When trying to use custom transformers that use async/await, the client throws `TRPCClientError: Invalid response or stream interrupted`. I am using the T3 stack and trying to implement asymmetric encryption between the client and the server.

### Link to reproduction

https://stackblitz.com/github/trpc/examples-next-minimal-starter?file=src%2Futils%2Ftrpc.ts

### To reproduce

Try async/await with your transformers.

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/5844">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/5844/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/5844/pledge.svg">
</picture>
</a>

**Comment by KATT** [comment]
This is not a bug, we just don't support the serialize/deserialize fn to return a promise

Describe closer what you want to achieve and we might be able to help you.

**Comment by codesfromshad** [comment]
Hi, @KATT! Great fan of tRPC.! Thank you for getting back to me quickly. I was hoping to use `RSA-OAEP` encryption to asymmetrically encrypt the communication between the server and the client. So when the client opens up the network tab, it'll be all gibberish. I have already been able to get symmetric encryption (`AES-CBC`) working ([see here](https://github.com/trpc/trpc/discussions/5843#discussion-6882081)) by using the same key on both client and server, however, no luck with asymmetric encryption. Do you know how I can achieve asymmetric encryption?

**Comment by KATT** [comment]
I'm no security expert but I'm missing the point of this - SSL should already fulfill doing secure communication and this is not e2e encryption between users

**Comment by codesfromshad** [comment]
Doing this to hide the request signature. Bad approach?

**Comment by KATT** [comment]
I don't see the point, it's security but obscurity

**Comment by KATT** [comment]
I don't see the point, it's security by obscurity
