### ISSUE TITLE
bug: Stream Link does not abort

### ISSUE THREAD

**Issue by enricoros** [trpc/trpc#5851]
### Provide environment information

```
  System:
    OS: Windows 11 10.0.22631
    CPU: (32) x64 AMD Ryzen 9 7950X 16-Core Processor
    Memory: 46.84 GB / 63.65 GB
  Binaries:
    Node: 20.13.1 - C:\P\apps\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 10.5.2 - C:\P\apps\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (126.0.2592.81)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    @trpc/client: next => 11.0.0-rc.436+fbb4a2fb4
    @trpc/server: next => 11.0.0-rc.436+fbb4a2fb4
    typescript: ^5.5.0 => 5.5.3
```

### Describe the bug

The AbortController signal seems ignored by Stream Links with async generators.

We'd expect an interruption on the server side, and on the client side, but packets continue to be produced by the async generator, flow to the client, and the client keeps awaiting and receiving them.

I don't know what the correct behavior would be, but right now the signal seems to be completely ignored on both ends.

### Link to reproduction

https://github.com/enricoros/trpc-repro-stream-unabort

### To reproduce

In summary:
1. The client creates a Stream Link, and queries with a `{signal: ac.signal}`, like this (minimal):
```typescript
const trpc = createTRPCClient<AppRouter>({
  links: [unstable_httpBatchStreamLink({url: 'http://localhost:3000',})],
});

const ac = new AbortController();

const iterable = await trpc.examples.iterable.query(undefined, { signal: ac.signal });
```

2. The server implements a procedure with an async generator, like this (minimal):
```typescript
    iterable: publicProcedure.query(async function* () {
      for (let i = 0; i < 8; i++) {
        await new Promise((resolve) => setTimeout(resolve, 500));
        yield i;
      }
    }),
```

3. We would expect both the server and the client to be aborted, but execution continues on both.
This is the output:
![image](https://github.com/trpc/trpc/assets/32999/b4175a3f-7e46-486f-81e4-7008a4014e86)

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/5851">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/5851/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/5851/pledge.svg">
</picture>
</a>

**Comment by KATT** [comment]
I think if you stop consuming the result and break in your `for await` it'll do what you expect

**Comment by enricoros** [comment]
Tried this, and it stops the client, but the server keeps producing (yielding).

For a client only solution I would not need the AbortController, but the assumption is that by passing the signal there will be some effect, but right now I don't see any effect on it.

Pushed a branch [variant-client-quit](https://github.com/enricoros/trpc-repro-stream-unabort/commits/variant-client-quit/), with [this commit](https://github.com/enricoros/trpc-repro-stream-unabort/commit/151e0a78642f13acfd50d7721d886e7638278e0b), but the output shows that the server keeps producing as if abort was never called.

![image](https://github.com/trpc/trpc/assets/32999/63a86790-b168-4c0d-af81-e5361e20ef6e)

**Comment by KATT** [comment]
Interesting. Feels like we should address this indeed. 

The code is a bit involved - this link handles streaming and batching requests so one abort shouldn't necessarily abort everything unless all requests are aborted.

It'll likely take me some hours to debug this and think of a good solution, client side cancellation slipped my mind when doing the implementation.

If you need this solved, consider adding a bounty.

**Comment by enricoros** [comment]
Thanks, I understand it's not easy - this is very advanced. For my usage I don't need the batching part, I don't know if there could be a simplification where abort() terminated all the connections of the batch.

The other issue is that after throwing on the server side, the connection seems to stay open (while it closes without throwing) -- maybe it's related to batching too.

I've added a bounty using polar. I understand it's not much, but it's almost all my GitHub income for the month (and beats the issues with no bounty! :).

**Comment by KATT** [comment]
The PR has been released as a tmp release, you can use it straight away using the `@tmp`-tag of tRPC


Update your `package.json` to use the latest version of tRPC:

```diff
-    "@trpc/client": "^x.y.z",
-    "@trpc/next": "^x.y.z",
-    "@trpc/react-query": "^x.y.z",
-    "@trpc/server": "^x.y.z",
+    "@trpc/client": "tmp",
+    "@trpc/next": "tmp",
+    "@trpc/react-query": "tmp",
+    "@trpc/server": "tmp",
```

Then run `npm install` or similar. Let me now how it works. It's not a great hack.

**Comment by KATT** [comment]
Both 

1. `return`ing in the `for await` , and
1. using an abort signal

should work, please try verifying both with a real usecase 🙏

**Comment by enricoros** [comment]
Thanks! What a code change - Impressive. Testing in progress... ⌛

**Comment by KATT** [comment]
> Thanks! What a code change - Impressive. Testing in progress... ⌛

I hated how I did it so I ended up spending 3-4 hours refactoring after 😬

**Comment by enricoros** [comment]
This is working incredibly well. I am VERY glad I am basing this AI stack on tRPC, as this is working wonders already.

Evaluation below - in short, this is great and looks like magic to me - only 1 question below.

- [x] **Abort on the Client-side** (rRPC API call / for await ...):
  - This is unbelievable and looks like magic to me
  - Works by passing the signal to the tRPC Api call (code below)
  - [x] Client side stops correctly and instantaneously at the `for await ....`
  - [x] Socket closed
  - love this pattern (or catching at higher levels):
  ```typescript
    const stream = await aixApi.lowlevel.chatGenerateContentStream.mutate({ ... }, { signal: abortSignal });
    try {
      for await (const update of stream) {
        // use the update object here...
      }
    } catch (error) {
      console.error('Client Catch', error);
    }
  ```
  - Note on the 'error' object contents: see below at the bottom

- [x] **Abort on the Server-side** (tRPC procedure):
  - [x] the client->server socket seems to close, exactly like _fetch_ calls
  - [ ] there's no exception thrown or signal catchable on the server-side, but it's probably okay as execution seems to stall
  - [ ] **Question**: on the server-side, I do open a connection to OpenAI/Anthropic/etc., and _could pass an abort signal_ to that upstream fetch, to terminate it alonside the tRPC procedure - is this possible?

- [x] **Throwing from the server-side** raises a TRPCClientError on the client side:
  ```typescript
  {
    data: { code: "INTERNAL_SERVER_ERROR", httpStatus: 500, path: _the full name of the procedure,_ ... },
    message: _the message thrown on the server side_,
    name: "TRPCClientError",
    cause: undefined,
    ...
  }
  ```
  - throwing a TRPCError on the server side allows to also to change _code_/_status_ (and cause) in addition to the message
  - [x] the HTTP code stays the same (200) which is ok
  - [x] Socket is closed (before this change the connection remained open - fixed!)


Misc. notes:
- 1. The exception raised on the client side seems to be a DOMException, with a 'cause.name' set to 'AbortError':
  ![image](https://github.com/trpc/trpc/assets/32999/19334e2c-7540-4efd-a918-484daee18a9e)
  - The typical AbortError has `error.name = 'AbortError'`, as per [this MDN note](https://developer.mozilla.org/en-US/docs/Web/API/AbortController/abort)
  - I would advise to set the `name` of the error thrown as `'AbortError'`, so that it's compatible with existing catching code

- 2. Somehow with Chrome dev tools I cannot see the Preview/Response for the request once done - not a big deal

---

Thanks again for this great work; would love to hear on the server-side question (are there events/signals to catch or pass on to the upstream OpenAI connection).

**Comment by KATT** [comment]
>  Question: on the server-side, I do open a connection to OpenAI/Anthropic/etc., and could pass an abort signal to that upstream fetch, to terminate it alonside the tRPC procedure - is this possible?

If you pass the `req` from `createContext` down you should be able to do this:

```ts
function myFn(opts: { ctx: Context }) {
  const ac = new AbortController();
  opts.ctx.req.once('aborted', () => {
    ac.abort();
  });
  const res = await fetch({
    // [...]
   signal: ac.signal
  })
  // [[..]
}

```

We could potentially add a signal in `opts.ctx.info.signal` or something too, wdyt?

**Comment by enricoros** [comment]
I'm watching the branch and commits while I tried to debug it myself (got stuck inside some 'undici').
I am eager to try this out - seems amazing.

**Comment by enricoros** [comment]
**Update**: Testing in progress... ⌛

**Comment by enricoros** [comment]
Works perfectly! I confirm that the signal passed from the context `request.signal` works really well.
![image](https://github.com/trpc/trpc/assets/32999/c0e23e69-008e-40f4-aa7d-13ac72878697)

As an example, I started 4 OpenAI Generations and interrupted them right at the beginning, and the servers show the following stats:
![image](https://github.com/trpc/trpc/assets/32999/615abea0-8c06-4cd9-b1f7-5fd90dd52754)

This shows that the signal is really used from the request, passed to the fetch which terminates the upstream connection, and the user saves tokens.

As of now, the client and server work great. I don't see any other improvement (I didn't check if `error.name = 'AbortError'`, but it can be worked around too).

Thanks!

**Comment by KATT** [comment]
Merged this now and we appreciate the pledge - if you want to do a real dent in longevity of tRPC, please consider to sponsor [or get your employer to sponsor] on a monthly basis 🙏

**Comment by enricoros** [comment]
@KATT thanks, this is huge news! When my startup gets funding I'll pay it forward and sponsor the project.

So far, I'm incredibly happy with Streaming via tRPC, especially because it induces correctness upstream via generators/async generators. The new API is so clean, and have infinite room for scalability, which I'm still early in exploring. Cannot wait to remove all my old stream transformation code and manual endpoints.

I hope I can make my tRPC AI library a bit more independent from the rest of the App, because it's a more flexible alternative to the Vercel AI sdk.

**Comment by KATT** [comment]
Thank you @enricoros, this whole interaction with you has been 10/10
