### ISSUE TITLE
feat: add support for datadog

### ISSUE THREAD

**Issue by alyahmedaly** [trpc/trpc#5852]
### Describe the feature you'd like to request

I'm trying to adopt trpc within express.js codebase and we are using datadog to monitor our app

the thing is when I tried trpc for some routes with the integration trpc currently have I can only see the report in datadog or the main route for example `/api/trpc/` which kind make sense as the is the main url for my trpc client, but I would like to see each request in datadog separately not sure how!

### Describe the solution you'd like to see

some ideas
* push the info about the route in datadog manually not sure how yet!
* datadog can add support for trpc as they curruntly do for express and they patch the layer methods
* trpc can act somehow for express as separate routes

### Describe alternate solutions

Null 😃 

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/5852">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/5852/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/5852/pledge.svg">
</picture>
</a>

**Comment by KATT** [comment]
https://trpc.io/docs/server/middlewares#logging

**Comment by alyahmedaly** [comment]
Thanks for quick reply, as I see in datadog there already a span created for each call, so i'm not sure if much can be handled on trpc side, just thinking out load

**Comment by KATT** [comment]
I will close this, I don't see the point here - try adding a logger middleware and feel free to reopen if it doesn't suit your needs
