### ISSUE TITLE
bug: regression in nodeHTTPRequestHandler, introduced in 11.0.0-rc.419 

### ISSUE THREAD

**Issue by realityfilter** [trpc/trpc#5857]
### Provide environment information

System:
    OS: macOS 14.4.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 95.42 MB / 32.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 18.19.1 - ~/.nvm/versions/node/v18.19.1/bin/node
    npm: 10.2.4 - ~/.nvm/versions/node/v18.19.1/bin/npm
  Browsers:
    Chrome: 126.0.6478.127
    Chrome Canary: 128.0.6573.0
    Edge: 126.0.2592.87
    Safari: 17.4.1
    Safari Technology Preview: 17.4
  npmPackages:
    @trpc/client: ^11.0.0-rc.419 => 11.0.0-rc.419+343b6de2e 
    @trpc/server: ^11.0.0-rc.419 => 11.0.0-rc.419+343b6de2e 
    typescript: 5.4.5 => 5.4.5 

### Describe the bug

We are using trpc with its express middleware adapter. The release of 11.0.0-rc.419 introduced changes in `nodeHTTPRequestHandler`.  

Our further stack is:

- nestjs
- serverless-express
 
In versions prior to 11.0.0-rc.419  the results were successfully written via `node_stream.Readable.fromWeb(response.body).pipe(opts.res);`

With 11.0.0-rc.419 https://github.com/trpc/trpc/blob/fbb4a2fb4b71d2f5ab7ee97617d951f3a92517c8/packages/server/src/adapters/node-http/nodeHTTPRequestHandler.ts#L85

and serverless-express returning `void` from the write method this leads to a hang and an internal server error from the lambda runtime. I issued a bug report there: https://github.com/CodeGenieApp/serverless-express/issues/683

But some folks might still be on older version of serverless-express because of changes to the owner of the package. So it might be a good idea to check for `boolean` return value from write and handle this gracefully.

### Link to reproduction

https://github.com/realityfilter/serverless-express-write-bugreport

### To reproduce

- download repository https://github.com/realityfilter/serverless-express-write-bugreport
- `npm install`
- `vitest`

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/5857">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/5857/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/5857/pledge.svg">
</picture>
</a>

**Comment by KATT** [comment]
I forgot why I changed that, but it caused some issues somewhere somehow 😅 

That said, I don't see how we're doing anything wrong here, it seems like `serverless-express` is just not handling it correctly

**Comment by KATT** [comment]
See #5861 - would that fix it?
