### ISSUE TITLE
docs: usage of maxBatchSize

### ISSUE THREAD

**Issue by eensander** [trpc/trpc#5892]
### Area of Improvement / Question

Hello all,

I'm confused by the intended implementation of the `maxBatchSize` configuration option, as described in the [documentation](https://trpc.io/docs/v9/links#setting-a-maximum-batch-size). 
There are various signs that this configuration option is not considered or used in the code:
1. My editor doesn't provide suggestions for this configuration option and it is red-underlined,
2. When searching for the exact term "`maxBatchSize`" in this repository, the only found occurrence I find is in the documentation,

This configuration option is currently exactly what I need to split up a very large request in multiple chunks. One thing to note is that the configuration option `maxURLLength` does somewhat work as expected: the large promise request is splitted up into multiple requests. Though, it would be more convenient to have more control over the amount of promises included per requests, instead of interpreted based on the URL length. 

My main question is: is the option `maxBatchSize` as described in the documentation, currently supported? Should it be manually implemented?

### Link to related docs

https://trpc.io/docs/v9/links#setting-a-maximum-batch-size

### Additional information

For context: I am using nuxt-trpc, although I checked and it seems that @trpc/client's `httpBatchLink` method also does not accept the `maxBatchSize` key.  The intended use is to process the following in multiple batches of about the same size:

```ts
const promises = []

for (const note of notes) {
  promises.push($trpc.note.create.mutate(note))
}

Promise.all(promises)
```

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing the suggested changes!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/5892">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/5892/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/5892/pledge.svg">
</picture>
</a>

**Comment by KATT** [comment]
You're linking v9 docs, look at the version you're actually using

**Comment by KATT** [comment]
You're looking at an outdated version

![CleanShot 2024-07-13 at 13 50 18](https://github.com/user-attachments/assets/6e728580-d248-418a-8bec-7e4b9893fa1b)

See either

- https://trpc.io/docs/client/links/httpBatchLink#setting-a-maximum-url-length
- https://trpc.io/docs/v10/client/links/httpBatchLink#setting-a-maximum-url-length

The option of a max batch size has been removed in favor of `maxURLLength`
