### ISSUE TITLE
bug: `.useSubscription()` results in `undefined` in `data.data` of `onData()`

### ISSUE THREAD

**Issue by Katli95** [trpc/trpc#5900]
### Provide environment information

System:
    OS: [can provide on explicit request]
    CPU: [can provide on explicit request]
    Memory: 2.00 GB / 32.00 GB
    Shell: /bin/zsh
  Binaries:
    Node: 20.11.0 - nvm (v20.11.0)
    npm: 10.2.4 - same 
  Browsers:
    Chrome: 126.0.6478.127
    Safari: 17.5
    Firefox: 128.0 (64-bit)  --- Used for testing
  npmPackages:
    @tanstack/react-query: ^5.51.1 => 5.51.1 
    @trpc/client: ^11.0.0-rc.461 => 11.0.0-rc.461+f178d3fed 
    @trpc/next: ^11.0.0-rc.461 => 11.0.0-rc.461+f178d3fed 
    @trpc/react-query: ^11.0.0-rc.461 => 11.0.0-rc.461+f178d3fed 
    @trpc/server: ^11.0.0-rc.461 => 11.0.0-rc.461+f178d3fed 
    next: ^14.2.4 => 14.2.4 
    react: ^18.2.0 => 18.3.1 
    typescript: 5.2.2 => 5.2.2 

### Describe the bug

What it says on the tin pretty much, using `.useSubscription()` results in `undefined` in `data.data` of `onData()`. 
```ts
trpc.x.useSubscription(
    {
        id: item.id,
    },
    {
        onData(payload) {
            console.log("subscription.onData", payload);
        },
    }
);
```

<img width="502" alt="image" src="https://github.com/user-attachments/assets/e139245e-9478-4f27-93b7-6f9815ee551c">

Network tab for proof of data being present:
<img width="322" alt="image" src="https://github.com/user-attachments/assets/1026dc50-1462-48d1-b281-1f6abe6ce8ee">

May be related to the use of transformers (`devalue` using `uneval` & `eval`).

### Link to reproduction

https://stackblitz.com/edit/github-3c8xbf?file=src%2Fpages%2Findex.tsx

### To reproduce

Open the reproduction, `npm run dev`, open `/index`, see what's rendered on screen (JSON stringified response of `id` & `data`)

### Additional information

The code is simplified, I originally had some logic ofc, but for demo purposes I'm just `yield`-ing directly.

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/5900">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/5900/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/5900/pledge.svg">
</picture>
</a>

**Comment by BeBoRE** [comment]
You have your transformer setup incorrectly, if you change that it'll work

**Comment by Katli95** [comment]
Oh, weird, how so? It seems to be working for the regular query, if you check the repro again you can see that it's working for a regular query returning a date object.

Could you point out exactly what I'm doing wrong? I've been using an equivalent set-up (that is unless I transferred it wrong into the repro) for some time without issue.

**Comment by BeBoRE** [comment]
Idk useSubscription uses the input deserializer instead of the output deserializer (like the other links) to consume the stream, idk if that is a bug

**Comment by BeBoRE** [comment]
Is this intentional @KATT? https://github.com/trpc/trpc/blob/755f28799f40eb7fb56d065b6793af10271d407c/packages/client/src/links/httpSubscriptionLink.ts#L98

Seems like everywhere else the output transformer is used:
https://github.com/trpc/trpc/blob/755f28799f40eb7fb56d065b6793af10271d407c/packages/client/src/links/httpBatchStreamLink.ts#L101
https://github.com/trpc/trpc/blob/755f28799f40eb7fb56d065b6793af10271d407c/packages/client/src/links/httpBatchLink.ts#L106
https://github.com/trpc/trpc/blob/755f28799f40eb7fb56d065b6793af10271d407c/packages/client/src/links/httpLink.ts#L114

**Comment by KATT** [comment]
Looks wrong indeed, nice find
