### ISSUE TITLE
bug: Subscription function keeps running on the server even after client disconnects (sse)

### ISSUE THREAD

**Issue by devunt** [trpc/trpc#5917]
### Provide environment information

```
  System:
    OS: macOS 14.4.1
    CPU: (14) arm64 Apple M3 Max
    Memory: 215.14 MB / 36.00 GB
    Shell: 3.7.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 20.14.0 - ~/.local/share/mise/installs/node/20/bin/node
    npm: 10.7.0 - ~/.local/share/mise/installs/node/20/bin/npm
    bun: 1.1.20 - ~/.bun/bin/bun
  Browsers:
    Safari: 17.4.1
```

```
"@trpc/server": "^11.0.0-rc.466",
"@trpc/client": "^11.0.0-rc.466",
```

### Describe the bug

Subscription function on the server side keeps running even after client disconnects.

Server code:
```ts
  stream: sessionProcedure.subscription(async function* () {
    let i = 0;

    while (true) {
      yield i++;
      console.log(i);
      await Bun.sleep(1000);
    }
  }),
```

I'm using `unstable_httpSubscriptionLink` in the client side.
After refreshing the browser several time, I expected that the server still prints once a second, but instead it prints out numbers several times a second simultaneously.
I think this will constantly consume the server resources as more client connects and disconnects.

### Link to reproduction

-

### To reproduce

-

### Additional information

To workaround, I'm using `ctx.req.signal` to break out infinite while loop.

```ts
  stream: sessionProcedure.subscription(async function* ({ ctx }) {
    let i = 0;

    while (true) {
      if (ctx.req.signal.aborted) {
        break;
      }

      yield i++;
      await Bun.sleep(1000);
    }
  }),
```

Is this approach right and should I handle the abort signal manually each time? Or is there a way could TRPC somehow automatically cancel the async generator from yielding value after client disconnects?

Sorry for my bad english and thanks in advance!

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/5917">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/5917/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/5917/pledge.svg">
</picture>
</a>

**Comment by KATT** [comment]
Hey there! :wave:

We appreciate the time you've taken to write this issue.

Unfortunately, we don't have the capacity to assist with issues without a reproduction repository and this issue does not seem to be related to tRPC itself. It would also help if the reproduction didn't use Bun as it still has some intricacies where it works differently than Node.

Please feel free to re-open with a solid reproduction repository where we can help you further or post in our help channels on [Discord](https://trpc.io/discord) or in our [GitHub Discussions](https://github.com/trpc/trpc/discussions).
