### ISSUE TITLE
bug: wrong react provider used when multiple providers are composed

### ISSUE THREAD

**Issue by adamsuskin** [trpc/trpc#5921]
### Provide environment information

  System:
    OS: macOS 14.3
    CPU: (8) arm64 Apple M2
    Memory: 71.59 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.19.0 - ~/.nvm/versions/node/v18.19.0/bin/node
    npm: 10.2.3 - ~/.nvm/versions/node/v18.19.0/bin/npm
    pnpm: 9.5.0 - ~/.nvm/versions/node/v18.19.0/bin/pnpm
    bun: 1.0.14 - /opt/homebrew/bin/bun
  Browsers:
    Chrome: 126.0.6478.183
    Safari: 17.3
  npmPackages:
    @trpc/client: catalog: => 10.45.1
    @trpc/server: catalog: => 10.45.1
    typescript: catalog: => 5.3.3

### Describe the bug

Unfortunately, I am getting TS 7056 for an excessively deep router. As a result, I am splitting my server into two TRPC services mounted on the same Fastify instance.

In the front-end, that means I have `AppRouter` and `AppRouter2` and two different `trpc` and `trpc2`.

When I create providers to wrap the app in, I do it like so:
```
<Trpc2Provider>
    <TrpcProvider>
        <Main />
    </TrpcProvider>
</Trpc2Provider>
```

Unfortunately, even with this set-up, if there is a component that uses `trpc2`, it uses the API url provided by `TrpcProvider` (i.e. router 1) even though I am using `trpc2` when I create the hook:
```
    // this actually uses trpc's provider
    const [data, query] = trpc2.group.endpoint.useSuspenseQuery(...);
```

### Link to reproduction

https://stackblitz.com/github/trpc/examples-next-minimal-starter

### To reproduce

I don't think I can set this up in the repro env but hopefully the description makes sense.

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/5921">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/5921/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/5921/pledge.svg">
</picture>
</a>

**Comment by KATT** [comment]
Hey there! :wave:

We appreciate the time you've taken to write this issue.

Unfortunately, we don't have the capacity to assist with issues without a reproduction repository and this issue does not seem to be related to tRPC itself. 

Please feel free to re-open with a solid reproduction repository where we can help you further or post in our help channels on [Discord](https://trpc.io/discord) or in our [GitHub Discussions](https://github.com/trpc/trpc/discussions).


---

For multiple providers you can have a look at https://github.com/trpc/trpc/blob/next/packages/tests/server/react/multiple-trpc-providers.test.tsx

If your router becomes too big, you should be able to split it up in a monorepo that makes the compilation incremental and faster. Another hack to split up the inference I've outlined here https://gist.github.com/KATT/af6079e6fcc31f292776266dd76dadbb
