### ISSUE TITLE
bug: `return` from async generator not sent to frontend

### ISSUE THREAD

**Issue by oscartbeaumont** [trpc/trpc#5927]
### Provide environment information

  System:
    OS: macOS 14.5
    CPU: (10) arm64 Apple M1 Pro
    Memory: 168.69 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.7.1 - ~/.local/state/fnm_multishells/4103_1722527915863/bin/node
    Yarn: 1.22.22 - /opt/homebrew/bin/yarn
    npm: 10.5.0 - ~/.local/state/fnm_multishells/4103_1722527915863/bin/npm
    pnpm: 9.6.0 - ~/Library/pnpm/pnpm
    bun: 1.0.26 - ~/.bun/bin/bun
    Watchman: 2024.07.15.00 - /opt/homebrew/bin/watchman
  Browsers:
    Brave Browser: 125.1.66.118
    Chrome: 127.0.6533.74
    Safari: 17.5

### Describe the bug

A `return` statement in an async generator returned from a query does not work correctly.

### Link to reproduction

https://stackblitz.com/edit/github-jhedg3-smjqp5

### To reproduce

Given the following router:
```ts
const appRouter = router({
  iterable: publicProcedure.mutation(async function* () {
    for (let i = 0; i < 3; i++) {
      await new Promise((resolve) => setTimeout(resolve, 500));
      yield i;
    }

    // This return type is never transmitted over the network (checked in devtools)!
    return 'final return';
  }),
});
```

and the following client code:
```ts
const result = trpc.iterable.useMutation({
  onSuccess: async (result) => {
    const iterator = result[Symbol.asyncIterator]();
    let r;
    while (!(r = await iterator.next()).done) {
      console.log(`Yielded value ${r.value}`);
    }
    // The bug is that this always logs `undefined`, ignoring the `return` statement on the server.
    console.log(`Returned value ${r.value}`);
  },
});
```

I would expect the final `r.value` to log `'final return'` but it will always logs `undefined`.

If I check the network tab of my browser I can't see `'final return'` anywhere so I assume this is a bug in `@trpc/server`.

Finally to confirm the behavior, i've written basically the same thing but without tRPC and it runs as expected logging "final return":
```ts
async function* todo() {
  for (let i = 0; i < 3; i++) {
    await new Promise((resolve) => setTimeout(resolve, 500));
    yield i;
  }

  // This return type is never transmitted over the network (checked in devtools)!
  return "final return";
}

const iterator = todo()[Symbol.asyncIterator]();
let r;
while (!(r = await iterator.next()).done) {
  console.log(`Yielded value ${r.value}`);
}
// This correctly prints 'final return' as I would expect tRPC to also do.
console.log(`Returned value ${r.value}`);
```

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/5927">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/5927/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/5927/pledge.svg">
</picture>
</a>

**Comment by KATT** [comment]
Yeah, we're actually only returning an `AsyncIterable` at the moment which doesn't have a return - it shows up wrong in the types when you use a transformer

**Comment by KATT** [comment]
```tsx
const result = await client.iterable.query();
//      ^? const result: AsyncIterable<number>
```
