### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by martijnmichel** [trpc/trpc#5932]
### Provide environment information

Ubuntu 22.04.4 LTS (GNU/Linux 5.15.0-107-generic x86_64) on a dedicated Strato server with Plesk.
Node: 20.11.0
NextJS: 14.2.5
Latest version of trpc

command response (ran with root)
sh: 1: envinfo: Permission denied

### Describe the bug

First of all: this does not occur on my Mac Mini M2. But solely on my server. To make it even more weird, building with node:20-alpine on my mac works perfectly but gives (i dont know how) the same error on the server. 

The error itself has nothing to do with what it says I think, because when I comment my latest commit (which has nothing to do with trpc) it builds fine. The commit has an api route **(not a trpc api route)** to generate some images. Removing the folder or the generate script, makes the build work. But the same script is ran in another folder (again not trpc)

```
Collecting page data  ...Error: You're trying to use @trpc/server in a non-server environment. This is not supported by default.
    at Y.create (/root/apps/sonid-test/.next/server/app/api/trpc/[trpc]/route.js:4:2894)
    at 97329 (/root/apps/sonid-test/.next/server/app/api/trpc/[trpc]/route.js:4:60648)
    at t (/root/apps/sonid-test/.next/server/webpack-runtime.js:1:143)
    at a (/root/apps/sonid-test/.next/server/app/api/trpc/[trpc]/route.js:8:146775)
    at /root/apps/sonid-test/.next/server/app/api/trpc/[trpc]/route.js:8:146813
    at t.X (/root/apps/sonid-test/.next/server/webpack-runtime.js:1:1291)
    at /root/apps/sonid-test/.next/server/app/api/trpc/[trpc]/route.js:8:146788
    at Object.<anonymous> (/root/apps/sonid-test/.next/server/app/api/trpc/[trpc]/route.js:8:146841)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)

> Build error occurred
Error: Failed to collect page data for /api/trpc/[trpc]
    at /root/apps/sonid-test/node_modules/next/dist/build/utils.js:1268:15
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  type: 'Error'
}
```

### Link to reproduction

https://stackblitz.com/github/trpc/examples-next-minimal-starter?file=README.md

### To reproduce

Unfortunately I can not give a repro :( any info you need I can supply though.

### Additional information

Setting const blob = undefined or removing the interval directory makes the build work. The generateVexflow script has no reference to trpc and is also being used in the handler for scale and chord api routes.

There is no error in development. Only when building on the server. Again, works fine on my mac.

<img width="1279" alt="Screenshot 2024-08-08 at 15 15 59" src="https://github.com/user-attachments/assets/705022b9-dad2-4c33-a293-a16fb56c47c4">

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/5932">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/5932/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/5932/pledge.svg">
</picture>
</a>

**Comment by KATT** [comment]
Thanks for posting this. 

No idea what the error is here, but seems unlikely that it has anything to do with trpc and rather something with Nextjs, a specific version of node, corrupted node_modules, Linux permission issues, or something else.

We don't have capacity spend time figuring this out without a reproduction.
