### ISSUE TITLE
bug: Thrown TRPCError always returning a httpStatus code of 500. 

### ISSUE THREAD

**Issue by lukeorriss** [trpc/trpc#5935]
### Provide environment information

```
System:
    OS: macOS 14.5
    CPU: (8) arm64 Apple M1
    Memory: 69.27 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.15.1 - /opt/homebrew/opt/node@20/bin/node
    npm: 10.7.0 - /opt/homebrew/opt/node@20/bin/npm
  Browsers:
    Chrome: 127.0.6533.100
    Safari: 17.5
  npmPackages:
    @tanstack/react-query: ^5.50.0 => 5.51.23
    @trpc/client: ^11.0.0-rc.446 => 11.0.0-rc.477+a467f8314
    @trpc/react-query: ^11.0.0-rc.446 => 11.0.0-rc.477+a467f8314
    @trpc/server: ^11.0.0-rc.446 => 11.0.0-rc.477+a467f8314
    next: ^14.2.4 => 14.2.5
    react: ^18.3.1 => 18.3.1
    typescript: ^5.5.3 => 5.5.4
```

### Describe the bug

When throwing a `TRPCError` inside of a `createTRPCRouter` function, the specified `code` is always returning `INTERNAL_SERVER_ERROR` with a `httpStatus` of 500. This happens regardless of the environment (dev/prod). 

I have declared a thrown error to be as follows: 
```
throw new TRPCError({
    code: "NOT_FOUND",
    message: "Forced error being thrown.",
});
```
So, I would expect the error that is returned to the error.tsx page to be 404. It seems that whichever error code i specify, the same `INTERNAL_SERVER_ERROR` is thrown, almost as if it's being overwritten somewhere. 

The error page is displayed inside of `app/error.tsx` with the following: 
```
interface Props {
  error: TRPCError;
  reset: () => void;
}

const error = ({ error, reset }: Props) => {
  const httpCode = getHTTPStatusCodeFromError(error); // This is always 500
  console.log(error, httpCode);
  return (
    <div className="bg-background flex min-h-[100dvh] flex-col items-center justify-center px-4 py-12 sm:px-6 lg:px-8">
      <div className="mx-auto max-w-md text-center">
        <div className="text-primary mx-auto h-12 w-12" />
        <h1 className="text-foreground mt-4 text-3xl font-bold tracking-tight sm:text-4xl">
          Error: {httpCode}
        </h1>
        <p className="text-muted-foreground mt-4">{error.message}</p>
      </div>
    </div>
  );
};
```

### Link to reproduction

https://github.com/lukeorriss/trpc-server-error-example.git

### To reproduce

A production example of this can be found [https://trpc-error.orriss.dev](https://trpc-error.orriss.dev).
Alternatively, the github repo: [https://github.com/lukeorriss/trpc-server-error-example.git](https://github.com/lukeorriss/trpc-server-error-example.git)
To reproduce: 
- create t3 stack nextjs application
- force an error to be thown in the provided post.ts route example
- httpStatus will be 500, regardless of specified error code. 

### Additional information

This was created using the T3 Stack, so this might well not be the place for this error. Please let me know if this is the case, and I will recreate it elsewhere. 

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/5935">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/5935/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/5935/pledge.svg">
</picture>
</a>

**Comment by wiktrek** [comment]
error.tsx gets type Error which doesn't have a httpStatus code. That means that you pass undefined as a code and that's why it returns code 500 [error documentation nextjs](https://nextjs.org/docs/app/api-reference/file-conventions/error#error)
![image](https://github.com/user-attachments/assets/f2323a9a-4cf8-4422-836c-7b14a0dc3fab)

**Comment by darkship** [comment]
Hello,
This doesn't seam to be a TRPC issue but more an issue with `next`:

If you catch the error in `src/app/page.tsx`

![image](https://github.com/user-attachments/assets/c28e6584-d062-4308-8eb6-16285366b26b)

And use `Error` in `src/app/error.tsx`

![image](https://github.com/user-attachments/assets/4edad499-b592-4999-8104-32dbbdbaf211)


you will get 
![image](https://github.com/user-attachments/assets/3c5fca94-1dce-46e6-b6ab-5fc209fa2756)
