### ISSUE TITLE
bug: onData in useSubscription doesn't return promise

### ISSUE THREAD

**Issue by bikoevD** [trpc/trpc#5954]
### Provide environment information

-

### Describe the bug

After updating to the latest version, I had compatibility issues. Previously, onData supported the asynchronous function, now it doesn't https://github.com/trpc/trpc/blob/9e6825aa83b969dc3b3d698ed0a5281806c1670a/packages/react-query/src/shared/hooks/types.ts#L139

### Link to reproduction

-

### To reproduce

-

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/5954">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/5954/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/5954/pledge.svg">
</picture>
</a>

**Comment by KATT** [comment]
I don't think we ever properly supported that `onData` was a async function, can you share more context on how you use this?

**Comment by KATT** [comment]
The types are more correct now, we never handled this and the types were too permissive. You can still do it but the ts error now is correct
