### ISSUE TITLE
feat: Add support for fetchQuery and fetchInfiniteQuery in @trpc/react-query/rsc

### ISSUE THREAD

**Issue by kamyarkaviani** [trpc/trpc#5963]
### Describe the feature you'd like to request

I'm using `npm create t3-app` to bootstrap a new next.js app with trpc. There, the recommended way to add the hydration helpers in v11 is to import `createHydrationHelpers` from `@trpc/react-query/rsc`. Then we can destructure and use the trpc object retuned by `createHydrationHelpers` to prefetch queries on the server components and then wrap the result in `HydrateClient`. That all works fine, but I also need to see the result of the query on the server-side, for many reasons. For example, if the procedure throws some known error, I might need to redirect or render a different UI. Currently, the only available options are `prefetch` and `prefetchInfinite` both will return a `Promise<void>`. It would be really useful if you can also add `fetch` and `fetchInfinite`, so that data and errors thrown in the query become available in the server component that is pre-rendering.  My `suspenseQuery` calls in the client component unfortunately crashes the whole page when a `TRPCError` is thrown, and that does not provide any opportunity to act on query errors before client component is rendered. I hope this isn't too complicated to add. Thanks for considering.

### Describe the solution you'd like to see

`fetch` and `fetchInfinite` become available options in `createHydrationHelpers`.

### Describe alternate solutions

An alternate solution would be to call the procedure in the server component with the help of `createCallerFactory`. But calling the procedure does not prefetch and hydrate the query on the client. I would have to first call it, then use `prefetch`, hitting the endpoint twice.

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/5963">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/5963/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/5963/pledge.svg">
</picture>
</a>

**Comment by juliusmarminge** [comment]
If you need the data just call the proc without `.prefetch()` etc.

There are reasons why it was bad to also populate the cache here so that's why it's not tied to the react query cache, but you just get the data.

```tsx
async function Page() {
  const data = await trpc.foo.bar(); // <-- just invoke and you get data
  
  void trpc.foo.bar.prefetch(); // <-- will prefetch and populate query cache with pending promise
}
```

If you really need the data both on the server and in client cache, you'll need to populate the cache yourself (by calling `queryClient.setQueryData()`), but we're explicitely not advocating for this and that's why it's not the default behavior

**Comment by kamyarkaviani** [comment]
@juliusmarminge it's not just the data, it's more so the errors I need while it is prefetching. And yes, I could call the procedure and then again call `prefetch`, but that will double the network latency, the database load, and will essentially double my request times everywhere. It's interesting that you take this very strong opinion in `createHydrationHelpers`, yet both `fetch` and `fetchInfinite` are currently available in [`createServerSideHelpers`](https://trpc.io/docs/client/nextjs/server-side-helpers). May I know why that is? Isn't the `createHydrationHelpers` the app router's equivalent of `createServerSideHelpers`?

**Comment by juliusmarminge** [comment]
The difference is that server components doesn't rerender, so given

1. A server component calls `.fetch()` to get data to show in some UI
2. A client component picks up this data with `useSuspenseQuery`
3. A mutation is made client side, that then `invalidate()`' s the query
4. The client component refetches, getting the new state. But the server component will not, displaying stale data that's out of sync in different places throughout your app.

That's why we want you to make a very explicit choice when seeding the cache with data you also use on the server. If we put `.fetch()` on the proxy people will use it for the convenience of having the data both on the server and client without being aware of these pitfalls.

---

As for the error handling, with Suspense you probably want an Error Boundary so that when the _useSuspenseQuery_ fails, the error boundary picks it up.

**Comment by kamyarkaviani** [comment]
@juliusmarminge Imagine a scenario where I have a procedure that throws some known error, and whenever that page is requested, when the error occurs, I want to, say, redirect to a different page. The `prefetch` call in the server component fails silently without throwing anything, so the client component will run `useSuspenseQuery` and crash the page. Then `error.tsx` from Next.js takes over with a much-stripped-down version of the error object, containing nothing but a message and a digest. Remember, error boundaries on Next.js are client components for security reasons, so if I were to redirect inside of `error.tsx`, I would have to rely on nothing but the `error.message` to determine the nature of the error. Even worse, let's look at what the user experiences: the user requests the page. They will see a white page for a good five to ten seconds as the QueryClient continues to retry the `suspenseQuery` and fail in their browser in the background. Perhaps we can set `retry` to 0 in the `QueryClient` config, but really, we are putting more and more bandaid, instead of addressing the real issue. With `prefetch`, we are really flying blind in the server component and have no clue as to whether it succeeded or not, and have no way to control the flow of the logic in the server. You make a very good point about `fetch` being abused by beginners, not understanding that server component data is not owned by the client and will never re-sync. And this point is made very clearly in the React Query [documentation](https://tanstack.com/query/latest/docs/framework/react/guides/advanced-ssr#data-ownership-and-revalidation). But it's important to note that, even though the abuse of `fetchQuery` is possible, React Query does not incapacitate the developers. They still make it available through the API, and explain to us how to not abuse it. I sincerely believe tRPC should as well. Or at the very least, expose a custom API through your proxy that prefetches and also throws the errors during prefetch.

**Comment by juliusmarminge** [comment]
So what you're saying is you don't care about the data in the server component t but you do care about handling errors in a `.catch()` type of way instead of error boundaries

What do you think @TkDodo, given you we're "against" wrapping fetchQuery back when this was implemented. You have some good docs explaining the footguns to avoid.

**Comment by TkDodo** [comment]
The reasoning @juliusmarminge has shown [here](https://github.com/trpc/trpc/issues/5963#issuecomment-2313403306) is exactly the reason why we don't recommend calling `.fetch()` in a server component. Users will likely start rendering that data in a server component then, and it will likely get out of date with client side refetches.

You can simply call `queryClient.getQueryState(queryKey)` after prefetching to check if your query is in error state. This is similar in complexity to calling `fetchQuery` with try/catch.

**Comment by kamyarkaviani** [comment]
@TkDodo thank you for this helpful suggestion. I went ahead and exported the caller `const getQueryClient = cache(createQueryClient);` in my `/lib/trpc/server.ts` and now I can get access to the `QueryClient` instance in the server and check for the query status after `prefetch`. It does solve my problem, but it's definitely not nicer nor simpler than try catch or a catch() block because now I have to manually hard-code the keys in the `getQueryState` call, and if the function name or signature ever changes in the router, I'll have to update the query keys one by one everywhere. I guess one of the big wins with tRPC was that we never have to deal with keys ourselves, but it seems since you are so dead-set on not making fetchQuery available, we have no other choice.

**Comment by kamyarkaviani** [comment]
@TkDodo Do you this it's doable to expose `getQueryState` from `createHydrationHelpers`? This would make it possible to have `const state = trpc.routerName.procName.getQueryState(input)`.

**Comment by TkDodo** [comment]
@kamyarkaviani afaik, trpc has helper methods to access the queryKey from a procedure: https://trpc.io/docs/client/react/getQueryKey

if  `getQueryState` will be exposed or not is question @juliusmarminge needs to answer. From React Query perspective, there isn't anything to do.
