### ISSUE TITLE
bug: Incorrect typing when retrieving dates from Postgres DB, Prisma integration

### ISSUE THREAD

**Issue by dabenor** [trpc/trpc#5972]
### Provide environment information

System:
    OS: Windows 11 10.0.22631
    CPU: (20) x64 13th Gen Intel(R) Core(TM) i7-13700H
    Memory: 1.90 GB / 15.68 GB
  Binaries:
    Node: 20.10.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.4.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.7.1 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    @tanstack/react-query: ^5.53.1 => 5.53.1
    @trpc/client: 11.0.0-rc.490 => 11.0.0-rc.490+b6a851870
    @trpc/next: 11.0.0-rc.490 => 11.0.0-rc.490+b6a851870
    @trpc/react-query: 11.0.0-rc.490 => 11.0.0-rc.490+b6a851870
    @trpc/server: 11.0.0-rc.490 => 11.0.0-rc.490+b6a851870
    next: 14.2.5 => 14.2.5
    react: ^18 => 18.3.1
    typescript: ^5 => 5.5.4

### Describe the bug

```typescript
model Chat {
  id          Int       @id @default(autoincrement())
  user        User      @relation(fields: [], references: [])
  userId      String    @map("user_id")
  recipient   Recipient @relation(fields: [recipientId], references: [])
  recipientId String    @map("recipient_id")
  message     String
  timestamp   DateTime  @default(now())
}
```

This model is defined in my prisma.schema file. I ran npx generate and npx db push to ensure that my db was up to date, also, when I run:
```
SELECT column_name, data_type
FROM information_schema.columns
WHERE table_name = 'Chat' AND column_name = 'timestamp';
```

In my Postgresql DB (Neon DB) I get data_type is "timestamp without time zone"
When I log it in the server I get "Object" as the data type of timestamp.

Given the way it's stored in the DB, I would expect trpc to expect a Date object on the client side, yet type safety is warning me to accept a String.

```
Type '{ id: number; userId: string; recipientId: string; message: string; timestamp: string; recipient: {fullName: string; email: string | null; profilePicture: string | null; }; }[]' is not assignable to type 'ChatsWithRecipient[]'.
  Type '{ id: number; userId: string; recipientId: string; message: string; timestamp: string; recipient: {fullName: string; email: string | null; profilePicture: string | null; }; }' is not assignable to type 'ChatsWithRecipient'.
    Type '{ id: number; userId: string; recipientId: string; message: string; timestamp: string; recipient: {fullName: string; email: string | null; profilePicture: string | null; }; }' is not assignable to type '{ id: number; userId: string; recipientId: string; message: string; timestamp: Date; }'.
      Types of property 'timestamp' are incompatible.
        Type 'string' is not assignable to type 'Date'.ts(2322)
```

When I check the type in my client, it confirms with TRPC that it's a String. Basically, I want to reuse my Prisma data objects to retrieve data from the DB, and I can't do that if it's recognizing date fields as strings. I need to create and maintain multiple schemas, some for client side and some for server side, which TRPC is built to avoid anyways.

Happy to share any additional details, or to work on fixing this issue if it's really a bug and not an ID10T issue

### Link to reproduction

Pretty quick to do, not sure how to mock this well...

### To reproduce

Create a Prisma schema with a DateTime object

```typescript
model TestDB {
  timestamp   DateTime  @default(now())
}
```
retrieve timestamp using trpc and check type

### Additional information

I'm pretty new to open source contributions, would love to help if there's a way I can

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/5972">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/5972/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/5972/pledge.svg">
</picture>
</a>

**Comment by KATT** [comment]
JSON doesn't support `Date`s.

When you `JSON.stringify({ date: new Date() })`  you get e.g. `'{"date":"2024-08-30T18:33:39.990Z"}'`, which will be typed as `{ date: string }` in tRPC as we try to mimic what JSON does.

If you do want to retain a `Date` over the wire, you need a transformer like superjson, see https://trpc.io/docs/server/data-transformers
