### ISSUE TITLE
docs: tRPC Name

### ISSUE THREAD

**Issue by rm-rf-etc** [trpc/trpc#5984]
### Area of Improvement

Is this project related to [the trpc-group project](https://github.com/trpc-group/trpc)? They don't appear to reference each other.

### Additional information

I tried searching your README, I didn't find any instances of CPP or Golang, which are the languages that trpc-group is supporting. I'd recommend mentioning these and clarifying what's the relationship between the two projects (or lack thereof).

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing the suggested changes!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/5984">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/5984/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/5984/pledge.svg">
</picture>
</a>

**Comment by KATT** [comment]
No correlation, not sure why they decided to name their project the same as another well-known project

**Comment by KATT** [comment]
See https://github.com/trpc-group/trpc/issues/24
