### ISSUE TITLE
docs: use git LFS for storing documentation images

### ISSUE THREAD

**Issue by viliusddd** [trpc/trpc#5986]
### Area of Improvement

[server-side-calls](https://trpc.io/docs/server/server-side-calls) contains couple of images that are served from   githubusercontent.com. It's not ideal when serving trpc documentation offline locally :)
It would be nice to see images content even when viewing docs locally and with no internet connection.

### Link to related docs

https://trpc.io/docs/server/server-side-calls

### Additional information

I've opened pull request, but am not able to push LFS files, get the message:
```sh
can not upload new objects to public fork
```

It seems to be long standing issue with github: https://github.com/git-lfs/git-lfs/issues/1906

Adding images to repo w/o git LFS is probably not an option?

My Draft PR: https://github.com/trpc/trpc/pull/5985

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR implementing the suggested changes!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/5986">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/5986/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/5986/pledge.svg">
</picture>
</a>

**Comment by KATT** [comment]
you can make a PR to https://github.com/trpc/assets with the assets which are served through a cdn on https://assets.trpc.io
