### ISSUE TITLE
bug: Websocket does not gracefully resume/reconnect on iOS

### ISSUE THREAD

**Issue by bnussman** [trpc/trpc#5998]
### Provide environment information

```
 System:
    OS: Linux 6.9 Pop!_OS 22.04 LTS
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 8.56 GB / 15.26 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 22.8.0 - ~/.volta/tools/image/node/22.8.0/bin/node
    Yarn: 1.22.19 - ~/.volta/tools/image/yarn/1.22.19/bin/yarn
    npm: 10.8.2 - ~/.volta/tools/image/node/22.8.0/bin/npm
    pnpm: 9.9.0 - ~/.local/share/pnpm/pnpm
    bun: 1.1.28 - ~/.bun/bin/bun
  npmPackages:
    @tanstack/react-query: ^5.56.2 => 5.56.2 
    @trpc/client: ^11.0.0-rc.502 => 11.0.0-rc.502+2a8c56027 
    @trpc/react-query: ^11.0.0-rc.502 => 11.0.0-rc.502+2a8c56027 
    @trpc/server: ^11.0.0-rc.502 => 11.0.0-rc.502+2a8c56027 
    react: 18.2.0 => 18.2.0 
    typescript: ^5.6.2 => 5.6.2 
 ```

### Describe the bug

I think I am seeing two bugs with `wsLink` specific on iOS on React Native

- Active subscriptions do not resume when woken up from being locked 😴 
- If `lazy` is enabled, an iOS device will not reconnect to the websocket server at all when woken up from being locked 😴 

I get this error in the wsLink's `onError` whenever I wakeup my iOS device form being locked
<img src="https://github.com/user-attachments/assets/b527a5c9-ab45-439a-bd46-ef8bb1b1cfa8" height="600" />

### Link to reproduction

https://github.com/bnussman/trpc-ws-issue

### To reproduce

1. Downlaod [Expo Go](https://apps.apple.com/us/app/expo-go/id982107779) on your iOS device
2.  Clone the reproduction repository 
3.  Install dependencies with
    ```
    bun install
    ```
4.  Start the dev servers with 
    ```
    bun start
    ```
5. On your iOS device, open Expo Go and open this project
6. Observe the counter is counting up (meaning the subscription is working and connected)
7. Lock your iOS device's screen and wait for the server to register that the device disconnected
8. Unlock your iOS device and observe that the WS connections, but the tRPC subscription does not resume
9. Repeat steps 5-8 with lazy mode enabled. Observe that when your iOS device is woken up from sleep, the WS does not reconnect at all

### Additional information

This also happens in my production iOS app, so I have confirmed that this is not specific to Expo Go. 

It might be a React Native bug, but I haven't found anything documenting if this is the case. It maybe me something tRPC needs to address for compatibility with React Native

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/5998">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/5998/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/5998/pledge.svg">
</picture>
</a>

**Comment by KATT** [comment]
I don't have specific expertise in RN to know how the platform works differently when it comes to websockets etc.

Could you have a peek and see if you can debug or see what is wrong? Most of the code is in here https://github.com/trpc/trpc/blob/next/packages/client/src/links/wsLink.ts

**Comment by bnussman** [comment]
I'll poke around a bit and see if I can narrow it down 👀

**Comment by KATT** [comment]
I need help debugging this to understand the cause, I don't have the time to look into this for a while

**Comment by KATT** [comment]
Should be possible to symlink trpc to your example and play around with it

**Comment by KATT** [comment]
Should be possible to symlink trpc to your example and play around with it

```shell
pnpm i && pnpm dev
```

Should be enough to get the dev environment working, then symlink it and mess around

**Comment by BeBoRE** [comment]
My experience with RN and tRPCs wsLink is that when the phone locks, the subscription gets closed, but when you unlock your phone it should create a new subscription. I haven't encountered it not creating a new subscription.
