### ISSUE TITLE
feat: Remove `meta` from response

### ISSUE THREAD

**Issue by brunolm** [trpc/trpc#6001]
### Describe the feature you'd like to request

I'd like to remove `meta` that returns in a tRPC response.

### Describe the solution you'd like to see

A config option to remove it

### Describe alternate solutions

a header that can be passed with the tRPC call to supress the meta response

### Additional information

Issues that this causes:

- **Cannot parse JSON**: https://github.com/trpc/trpc/discussions/4554
- **Response too large**: https://stackoverflow.com/q/78990307/340760

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/6001">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/6001/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/6001/pledge.svg">
</picture>
</a>

**Comment by KATT** [comment]
This comes from superjson, not trpc

**Comment by brunolm** [comment]
Can you make this dependency something you can configure? (like providing a custom json serializer)

Is there a workaround? (maybe convert all dates to string before returning?)

**Comment by KATT** [comment]
If you don't use transformer, it'll become strings as that's what json.stringify does. You can write your own transformer but I wouldn't recommend it

Not sure what you're asking for - you don't have to use superjson to use trpc, just remove `tranformer: x` everywhere
