### ISSUE TITLE
feat: @trpc/client should export observable

### ISSUE THREAD

**Issue by incompletude** [trpc/trpc#6013]
I have separated libs for client and server, and since @trpc/client doesn't export the observable function and type I also have to install @trpc/server just to use this function and type, which is weird. I think this function should be exported in both packages.

**Comment by KATT** [comment]
We might do a `@trpc/core`-glue package but it created a heap of _The inferred type of 'xxxx' cannot be named without a reference to '.pnpm/@trpc+core@[.....]'. This is likely not portable. A type annotation is necessary issues last time we tried

**Comment by KATT** [comment]
We won't re-export, but we might do a core package
