### ISSUE TITLE
bug: zod input schema .refine() type refinements with type predicates get lost

### ISSUE THREAD

**Issue by DrJume** [trpc/trpc#6044]
### Provide environment information

```
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.20.3 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    @trpc/client: ^10.45.2 => 10.45.2 
    @trpc/react-query: ^10.45.2 => 10.45.2 
    @trpc/server: ^10.45.2 => 10.45.2 
    typescript: ^5.6.2 => 5.6.2
```

### Describe the bug

Using a zod schema with `.refine()` and type predicates for input validation loses the type refinements in `inferRouterInputs`
```ts
export const inputSchema = z.object({
  name: z.string().refine((s): s is 'alice' | 'bob' => true),
});

type b = z.infer<typeof inputSchema>;
//   ^? { name: "alice" | "bob" }
```

- https://github.com/colinhacks/zod#type-refinements

But using `inferRouterInputs` gives only the type:
```ts
{ name: string }
```

### Link to reproduction

https://stackblitz.com/edit/github-njdk1n?file=src%2Fclient.ts&view=editor

### To reproduce

1. Create a trpc query endpoint with input schema:
```ts
z.object({
  name: z.string().refine((s): s is 'alice' | 'bob' => true),
});
```

2. Use `inferRouterInputs<AppRouter>[...]` to get the inferred input type.

3. Type will be only
```ts
{ name: string }
```
instead of (z.infer<typeof inputSchema>)
```
{ name: "alice" | "bob" }
```

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/6044">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/6044/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/6044/pledge.svg">
</picture>
</a>

**Comment by KATT** [comment]
This works as intended

The input can still be any `string` even if you later refine that to something else

```ts
const inputSchema = z.object({
  name: z.string().refine((s): s is 'alice' | 'bob' => true),
});

inputSchema['_input']
inputSchema['_output']
```

What you can pass to the procedure is the `_input` and what the procedure gets in the resolver is the `_output`

**Comment by KATT** [comment]
You might want to look at e.g. `z.enum()` or similar
