### ISSUE TITLE
bug: Documented error codes not available on types

### ISSUE THREAD

**Issue by mattpocock** [trpc/trpc#6052]
### Describe the bug

Some of the error codes on trpc's error handling docs are not available on the type level.

### Link to reproduction

https://tsplay.dev/NBr5dN

### To reproduce

Look at the TS playground above. Notice the errors on 415 and 502-504.

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/6052">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/6052/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/6052/pledge.svg">
</picture>
</a>

**Comment by KATT** [comment]
add `// types: next`: https://tsplay.dev/mbDQ2w

Version 11 is what you should be using. We should make a proper bump to 11.0.0 soon™, I'm just a commitment-phobe
