### ISSUE TITLE
feat: subscriptions should work together with output parsers

### ISSUE THREAD

**Issue by lbguilherme** [trpc/trpc#6062]
### Describe the feature you'd like to request

Currently it is impossible to write something as:

```typescript
export const test = t.procedure
  .output(z.string())
  .subscription(async function* () {
    yield "hello";
    await sleep(1000);
    yield "world";
  });
```

It won't compile with a TypeScript error and also will fail at runtime because a `AsyncIterable<string>` is not a `string`.  
Client types happen to generate correctly.

It should be allowed, it should correctly type the function and it should validate the subscribed data, not the subscription itself.

### Describe the solution you'd like to see

The above code should be allowed and work as expected. Nothing new needs to be added for this to work.

### Describe alternate solutions

The current solution is to skip using output parsers and instead provide the type manually, without any runtime safety:

```typescript
export const test = t.procedure
  .subscription<string>(async function* () {
    yield "hello";
    await sleep(1000);
    yield "world";
  });
```

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/6062">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/6062/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/6062/pledge.svg">
</picture>
</a>

**Comment by KATT** [comment]
I appreciate the work you've put in here but this is already possible as shown in #5903, so I'm not sure we want to implement the feature outlined in #6063

- https://github.com/trpc/trpc/blob/574777bc247cfda69809cc1adb9f1777bcb79087/packages/tests/server/streaming.test.ts#L88-L96
- https://github.com/trpc/trpc/blob/574777bc247cfda69809cc1adb9f1777bcb79087/packages/tests/server/streaming.test.ts#L26-L39

We should however probably document this better

**Comment by KATT** [comment]
Actually, that above doesn't work with subscriptions.... fixing 👀

**Comment by KATT** [comment]
I've made an update now that should make it clearer how to use subscription output parsers + made a fix for the typing on subscriptions.

Making it a simple `z.output(x)` sounds good in theory but subscriptions could eventually allow the return value from `AsyncGenerator` and that structure won't allow for that

**Comment by KATT** [comment]
Please re-open a new issue if you're experiencing issues!

**Comment by KATT** [comment]
Unsolicited PRs to improve our docs are also always welcome! 🙏

**Comment by lbguilherme** [comment]
Oh nice! I have tried that before and it hasn't worked. Thanks for the quick fix for the typings!

Everything working fine now.

**Comment by KATT** [comment]
I improved it further in #6066
