### ISSUE TITLE
bug: Query data is available before return of `select`

### ISSUE THREAD

**Issue by kluplau** [trpc/trpc#6067]
### Provide environment information

```

  System:
    OS: macOS 12.7.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Memory: 87.72 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 22.8.0 - ~/.nvm/versions/node/v22.8.0/bin/node
    npm: 10.8.2 - ~/.nvm/versions/node/v22.8.0/bin/npm
    pnpm: 9.9.0 - ~/Library/pnpm/pnpm
    Watchman: 2024.05.06.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 129.0.6668.60
    Safari: 17.6

### Describe the bug

I expect getData to be empty, before I run the `select` function on `useQuery`.

```typescript
  const utils = trpc.useUtils();

  const result = trpc.notifications.getAll.useQuery(undefined, {
    select: (notifications) => {
      // This should return nothing, as the select haven't returned yet...
      const previousNotifications = utils.notifications.getAll.getData() || [];

      const newNotifications = notifications.filter(
        (notification) => !previousNotifications.includes(notification)
      );

      // This will never happen
      newNotifications.forEach((notification) => {
        alert('Yay, new notification!');
      });

      return notifications;
    },
  });
  ```
  
  However it is already populated when first select executes.

### Link to reproduction

https://stackblitz.com/edit/github-8v6jku-xjeic1?file=src%2Fpages%2Findex.tsx

### To reproduce

Call `getData()` before select has been executed.

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/6067">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/6067/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/6067/pledge.svg">
</picture>
</a>

**Comment by juliusmarminge** [comment]
This is the behavior of using React Query. 

I added the raw RQ equivalent to your sandbox and they behave exactly the same: https://stackblitz.com/edit/github-8v6jku-jpp8n5?file=src%2Fpages%2Findex.tsx
