### ISSUE TITLE
feat: Using `@trpc/client` and `@trpc/react-query` simultaneously 

### ISSUE THREAD

**Issue by Mnigos** [trpc/trpc#6069]
### Describe the feature you'd like to request

I'm using trpc inside nextjs app with external trpc server that uses `nestjs-trpc`. I want to have acces for both `query` and `useQuery` since `query` will be useful in react server components for fetching data on server and react query hooks will be useful for client components fe. infinite query pagination.

### Describe the solution you'd like to see

I would like to extend an existing trpc client with react query.

Example:

`trpc.ts`
```ts
import { createTRPCClient, httpBatchLink } from '@trpc/client'

import type { AppRouter } from '../../api'

import { env } from './env'

export const trpc = createTRPCClient<AppRouter>({
  links: [
    httpBatchLink({
      url: `${env.API_URL}/trpc`,
    }),
  ],
})
```

`layout.tsx`
```ts
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { httpBatchLink } from '@trpc/client';
import React, { useState } from 'react';
import { trpc } from './utils/trpc';
export function App() {
  const [queryClient] = useState(() => new QueryClient());
  const [trpcClient] = useState(() =>
    trpc.createReactQueryClient(),
  );
  return (
    <trpc.Provider client={trpcClient} queryClient={queryClient}>
      <QueryClientProvider client={queryClient}>
        {/* Your app here */}
      </QueryClientProvider>
    </trpc.Provider>
  );
}
```

### Describe alternate solutions

Maybe add `.extend` and use it like this

`trpc.ts`
```ts
export const trpc = createTRPCClient<AppRouter>({
  links: [
    httpBatchLink({
      url: `${env.API_URL}/trpc`,
    }),
  ],
}).extend(createTRPCReact<AppRouter>())
```

I just need any way to extend vanilla trpc client with react-query hooks.

### Additional information

https://discord.com/channels/867764511159091230/1290004736006946816

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/6069">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/6069/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/6069/pledge.svg">
</picture>
</a>

**Comment by Nick-Lucas** [comment]
What do you need that's not already possible?

```tsx
import { trpc } from './utils/trpc';

export function Greeting() {
  const greeting = trpc.greeting.useQuery({ name: 'tRPC user' });
  
  trpc.useUtils().client.greeting.query({name: 'hello I am client'})
  
  return <div>{greeting.data?.text}</div>;
}
```

**Comment by Mnigos** [comment]
> What do you need that's not already possible?
> 
> ```tsx
> import { trpc } from './utils/trpc';
> 
> export function Greeting() {
>   const greeting = trpc.greeting.useQuery({ name: 'tRPC user' });
>   
>   trpc.useUtils().client.greeting.query({name: 'hello I am client'})
>   
>   return <div>{greeting.data?.text}</div>;
> }
> ```
> 
> It's also totally fine to create a dedicated client as well as the react-query client, they don't need to be combined

Yeah, finally i decided to create two separated clients for client and server.
