### ISSUE TITLE
bug: Procedure not found when using nextjs basePath config

### ISSUE THREAD

**Issue by Asher-JH** [trpc/trpc#6086]
### Provide environment information

```System:
    OS: macOS 13.5.2
    CPU: (8) arm64 Apple M2
    Memory: 163.22 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.6.1 - ~/.nvm/versions/node/v20.6.1/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.8.1 - ~/.nvm/versions/node/v20.6.1/bin/npm
    pnpm: 8.15.4 - ~/.nvm/versions/node/v20.6.1/bin/pnpm
  Browsers:
    Chrome: 129.0.6668.90
    Safari: 16.6
  npmPackages:
    @tanstack/react-query: ^5.54.1 => 5.56.2 
    @trpc/client: 11.0.0-rc.553 => 11.0.0-rc.553+9b629cc67 
    @trpc/react-query: 11.0.0-rc.553 => 11.0.0-rc.553+9b629cc67 
    @trpc/server: 11.0.0-rc.553 => 11.0.0-rc.553+9b629cc67 
    next: ^14.2.4 => 14.2.5 
    react: ^18.3.1 => 18.3.1 
    typescript: ^5.5.3 => 5.5.4 
```

### Describe the bug

In the current nextJS project, `basePath` config is being set. And the issue only appears when `basePath` is set.

The `basePath` config is being set to = '/dashboard'

When using a `useQuery` hook, it will error out with: 
```No procedure found on path "ovider.profile.getPayoutProviderOnboardingLink"'```

The procedure in question is correctly located @ `serviceProvider.profile.getPayoutProviderOnboardingLink`

Weird thing is that, if I have two `useQuery` hooks on the same page, only the first one will have the error, the remaining queries work as expected, this is likely due to using the HTTPBatchLink.

One thing to note is that, from the error, exactly 9 characters are missing in the start, which is the same number of characters my basePath config is set to. I tested with different number of characters for the basePath and the error always states they are short that same amount.

I have updated my trpc helpers to use the correct basePath when calling trpc apis as well, and can confirm it does work without basePath set.

### Link to reproduction

-

### To reproduce

1. Init NextJS app
2. use basePath in next.config.json
3a. Use 2 useQuery hooks on the same page, first one will fail while second succeeds
3b. Use 1 useQuery hooks should also fail

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/6086">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/6086/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/6086/pledge.svg">
</picture>
</a>

**Comment by Asher-JH** [comment]
I'll try and setup a reproduction in the meantime

**Comment by miaobuao** [comment]
Me too, and i use Astro

**Comment by miaobuao** [comment]
maybe you forgot to update your endpoint 
![image](https://github.com/user-attachments/assets/68bcaed9-3fc1-440b-91f0-3c7f5a5eae90)

**Comment by miaobuao** [comment]
maybe you forgot to update endpoint
![image](https://github.com/user-attachments/assets/3ddd8345-113d-4917-a174-544fcf0e6c83)
I meet same problem in astro. Solved by updating endpoint.
