### ISSUE TITLE
bug: Next.js 15 async headers error on trpc call

### ISSUE THREAD

**Issue by Itsnotaka** [trpc/trpc#6093]
### Provide environment information

```System:
    OS: macOS 15.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 68.78 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.8.0 - ~/.local/state/fnm_multishells/25403_1728431331338/bin/node
    npm: 10.8.2 - ~/.local/state/fnm_multishells/25403_1728431331338/bin/npm
    pnpm: 9.12.0 - ~/Library/pnpm/pnpm
    bun: 1.1.29 - ~/.bun/bin/bun
  Browsers:
    Safari: 18.1
  npmPackages:
    typescript: ^5.6.3 => 5.6.3
```

### Describe the bug

The error shows when using tRPC with Next.js 15 on canary.
This would not effect the call for now but would like to know how to fix such problem.This would not affect the call for now, but I would like to know how to fix such a problem.

### Link to reproduction

https://github.com/Itsnotaka/debug-t3-turbo

### To reproduce

Clone the repo, input the env, start the app and you would see the error in the terminal

### Additional information

https://github.com/Itsnotaka/debug-t3-turbo

Decide to quickly look into it what I did in this repo.
 -Cloned create t3 turbo
- Remove unused apps
- Bump nextjs to latest canary
- Add env
- Dev error would show up
- Added async/await on functions that showed errors. Then trpc type error shows
 
![image](https://github.com/user-attachments/assets/02be1f91-7d5a-4297-9698-395a0039034b)

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/6093">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/6093/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/6093/pledge.svg">
</picture>
</a>

**Comment by juliusmarminge** [comment]
I am guessing that this comes from next-auth and they are already on it: https://github.com/nextauthjs/next-auth/pull/12002

You can patch the lib locally until they ship the next version with the awaited headers

**Comment by juliusmarminge** [comment]
Yea confirmed if you remove next-auth from this repro it doesn't warn. Closing as it's tracked on their end and this is not trpc specific
