### ISSUE TITLE
bug: TRPC may create an invalid URL that crashes the server

### ISSUE THREAD

**Issue by ivan-kleshnin** [trpc/trpc#6094]
### Provide environment information

Machine agnostic

### Describe the bug

Some bots or spammers might send invalid requests with URLs like:
```
hotmail-com.olc.protection.outlook.com%3A25... 
```
We've met the above, and here's a 3rd party library showcasing the same signature: https://github.com/sbordeyne/fastapi_spammer_protection/blob/fd4a3982c23cd4ab0f4761c9db603994c06fa19c/fastapi_spammer_protection/vulnerable_urls.py#L174

We've got some auxiliary servers, with exposed IPs, crashed by bots. Our main servers work behing Nginx which prevents the above from happening. 

Here's where it happens:

https://github.com/trpc/trpc/blob/next/packages/server/src/adapters/node-http/incomingMessageToRequest.ts#L70

```ts
const url = `http://${headers.get('host')}${req.url}`;
```

The above code is buggy because `req.url` might be invalid, in particular not starting with a slash! So `${headers.get('host')}${req.url}` becomes
something malformed of `{domain}{domain}` shape.

It leads to a **hard crash** of the server – it does not just return 400 or 500 or something, but completely stops to accept new connections, basically goes offline❗Some of this behavior might be NodeJS specific, but the issue starts in TRPC code. Couldn't investigate in more details due to the lack of time.

### Proposed Solution

Validate that `req.url` starts with `/`. 

### Link to reproduction

I don't have enough time to prepare a sandbox, sorry, maybe a bit later. 
It looks like a TRPC bug to me.

### To reproduce

Create a server with `http-node` adapter and send a GET/POST with an invalid  URL. E.g.

```
$ printf 'GET hotmail-com.olc.protection.outlook.com HTTP/1.1\r\nHost: localhost\r\n\r\n' | nc localhost 2000
```

If anything – I'll contribute a sandbox next week.

### Additional information

Copied from:
https://github.com/trpc/trpc/discussions/6091#discussioncomment-10882424

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/6094">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/6094/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/6094/pledge.svg">
</picture>
</a>

**Comment by juliusmarminge** [comment]
tried your reproduction:

```js
import { once } from 'node:events';
import * as Http from 'node:http';
import * as Net from 'node:net';

const host = 'localhost';
const port = 3000;

const server = Http.createServer()
  .on('request', (req, res) => {
    res.writeHead(200);
    res.end('Hello World\n');
  })
  .on('connection', () => {
    console.log('Server got connection');
  })
  .listen(port, () => console.log('Listening on port ' + port));
await once(server, 'listening');

// Create a socket connection
const client = Net.createConnection(port, host, () => {
  // Construct the HTTP request
  const request =
    'GET hotmail-com.olc.protection.outlook.com HTTP/1.1\r\n' +
    'Host: localhost\r\n' +
    '\r\n';

  // Send the request
  client.write(request);
})
  .on('connect', () => {
    console.log('Client connected to server');
  })
  .on('data', (data) => {
    console.log('Response from server:\n', data.toString());
    client.end(); // Close the connection after receiving the response
  })
  .on('error', (err) => {
    console.error('Connection error:', err);
  })
  .on('end', () => {
    console.log('Disconnected from server');
  });
```

Output:

```
Listening on port 3000
Client connected to server
Server got connection
Response from server:
 HTTP/1.1 400 Bad Request
Connection: close


Disconnected from server
```

**Comment by KATT** [comment]
I did a small test in 421186e too, I can't reproduce it either

https://github.com/trpc/trpc/blob/421186e7345fdd59ee4581e2a5a739496e99bdbd/test.sh#L1-L7

Output:

```shell
response 1
HTTP/1.1 400 Bad Request
Connection: close




response 2:
HTTP/1.1 200 OK
content-type: application/json
vary: trpc-accept
Date: Thu, 10 Oct 2024 00:30:19 GMT
Connection: keep-alive
Keep-Alive: timeout=5
Transfer-Encoding: chunked

21
{"result":{"data":"Hello World"}}
0
```

**Comment by KATT** [comment]
We may, however, have a dangling promise here that maybe could crash the server due to a unhandled promise rejection if a middleware or similar throws.... 🤔 

`createServer` should receive a `(req, res) => void`, but is receiving a `(req, res) => Promise<void>`

https://github.com/trpc/trpc/blob/421186e7345fdd59ee4581e2a5a739496e99bdbd/packages/server/src/adapters/standalone.ts#L51-L52
https://github.com/trpc/trpc/blob/421186e7345fdd59ee4581e2a5a739496e99bdbd/packages/server/src/adapters/standalone.ts#L31-L32

Not sure if this may be related to your crash reports or not

**Comment by ivan-kleshnin** [comment]
Hi, folks. Thanks for exploring the issue.

@juliusmarminge what you've tried is a pure NodeJS / Bun, the error occurs in TRPC code.

We've tried a new version and the error is now in a different place, but still present:

```
✔ 05:44:21     [api-main] Listening on 'http://127.0.0.1:2000'
1 | function toURL(urlOrPathname) {
2 |     const url = urlOrPathname.startsWith('/') ? `http://127.0.0.1${urlOrPathname}` : urlOrPathname;
3 |     return new URL(url);
               ^
TypeError: "hotmail-com.olc.protection.outlook.com" cannot be parsed as a URL.
      at toURL (/Users/xxx/Documents/Projects/xxx/node_modules/@trpc/server/dist/unstable-core-do-not-import/http/toURL.mjs:3:12)
      at /Users/xxx/Documents/Projects/xxx/node_modules/@trpc/server/dist/adapters/standalone.mjs:8:21
      at /Users/xxx/Documents/Projects/xxx/node_modules/@trpc/server/dist/adapters/standalone.mjs:7:19
      at /Users/xxx/Documents/Projects/xxx/api-main/bin/server.ts:76:21
      at emit (node:events:181:48)
      at fetch (node:http:533:14)
```

When we sand a bad request, ^ this happens and then the server is stuck forever.

We'll explore it more and prepare a sandbox, hopefuly his weekend, so don't spend your time on this for now 🙏

**Comment by juliusmarminge** [comment]
> @juliusmarminge what you've tested is a pure NodeJS / Bun, the error occurs in TRPC code.

Yea but it doesn't even reach the request handler, so it would error before any trpc code would run???

**Comment by ivan-kleshnin** [comment]
> Yea but it doesn't even reach the request handler, so it would error before any trpc code would run?

Looks like Bun behaves differently. It doesn't check for invalid URL, being a less mature tool. 
We've rechecked the isssue in more details:

1. It was observable only in Bun.
2. It's fixed with the recent update.

Here's a repro sandbox:
https://github.com/scabbiaza/trpc-issue-6094

Fails in Bun with TRCC `rc-544`, `rc-566`. Works in NodeJS
Since `rc-571` works fine in both Bun and NodeJS.
