### ISSUE TITLE
bug: [Server-Sent Events] Client never makes a request to the server

### ISSUE THREAD

**Issue by jnsdrssn** [trpc/trpc#6116]
### Provide environment information

```
  System:
    OS: macOS 14.4.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 129.94 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
    Yarn: 1.22.21 - ~/.nvm/versions/node/v20.9.0/bin/yarn
    npm: 10.1.0 - ~/.nvm/versions/node/v20.9.0/bin/npm
    pnpm: 9.2.0 - ~/Library/pnpm/pnpm
    bun: 1.1.30 - ~/.bun/bin/bun
    Watchman: 2024.09.30.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 129.0.6668.91
    Safari: 17.4.1
  npmPackages:
    @trpc/client: ^11.0.0-rc.571 => 11.0.0-rc.571+a70e169ce 
    @trpc/server: ^11.0.0-rc.571 => 11.0.0-rc.571+a70e169ce 
```

### Describe the bug

The tRPC client never makes a request to the server. It also doesn't error when no server is running.
The repo has a standalone bun server and an elysia server. Both work fine when using curl.

### Link to reproduction

https://github.com/jnsdrssn/elysia-trpc-sse/tree/main

### To reproduce

```bun install```
```bun run src/elysia.ts```
```bun run src/client.ts```

See the repo README for more info.

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/6116">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/6116/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/6116/pledge.svg">
</picture>
</a>

**Comment by KATT** [comment]
Please provide a repro without bun as we've seen a several bugs todo with bun, esp around aync generators which we use in trpc for this.

It can also be that you need a polyfill for Eventsource.
