### ISSUE TITLE
bug: Trpc routes are not accessible after Vercel production deployment

### ISSUE THREAD

**Issue by tsironis13** [trpc/trpc#6120]
### Provide environment information

reproduced in prod env

### Describe the bug

I have a monorepo repo (https://github.com/tsironis13/nx-suite) with an AnalogJs app(eshop-admin) with SSR enabled. Trpc routes are accessible under `/api/trpc`
![image](https://github.com/user-attachments/assets/74106194-5707-40fe-9385-d6dd81dda7e9)
These routes are called as expected without errors during local development. But after deploying to production using Vercel the following error is returned:
![image](https://github.com/user-attachments/assets/2aaaca25-6439-428b-9e0b-dc21d9073578)
![image](https://github.com/user-attachments/assets/cfaf0d1d-bcb7-484b-827b-395dbae7f752)

### Link to reproduction

https://nx-suite-eshop-admin.vercel.app/categories

### To reproduce

https://nx-suite-eshop-admin.vercel.app/categories

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/6120">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/6120/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/6120/pledge.svg">
</picture>
</a>

**Comment by juliusmarminge** [comment]
I highly doubt this is trpc specific and your repro link doesn't work and your linked repo is too big. It's likely an issue in how you've setup your api route or similar server routing behavior.

Please re-open and provide a minimal reproduciton.more .
