### ISSUE TITLE
bug: zod inferred type differs from `inferRouterInputs` type when using zods `transform`

### ISSUE THREAD

**Issue by smndtrl** [trpc/trpc#6124]
### Provide environment information

    @trpc/client: 11.0.0-rc.477 => 11.0.0-rc.577+6b5a608eb 
    @trpc/server: 11.0.0-rc.477 => 11.0.0-rc.577+6b5a608eb 
    typescript: ^5.5 => 5.5.4

### Describe the bug

While trying to change the casing in a `zod` object saw the following behavior as outcome of the shared reproduction 

```ts
type TestSchema = {
    myLowerKey: z.ZodString;
}
```

while on the client 

```ts
type TestInputSchema = {
    my_lower_key: string;
}
```

Am I missing something? I couldn't find any mention on https://trpc.io/docs/client/vanilla/infer-types regarding applied transforms.

The validation still applies to `MyLowerKey` and the client side `TestInputSchema` type wants to have `my_lower_key`.

Thanks in advance

### Link to reproduction

see code

### To reproduce

```ts
const testSchema = z.object({
  my_lower_key: z.string()
})
  .transform(data => {
    return { myLowerKey: z.string() }
  })

type TestSchema = z.infer<typeof testSchema>

type TestInputSchema = inferRouterInputs<AppRouter>["secrets"]["test"]

export const secretRouter = router({
  test: secretsManagerProcedure
    .input(testSchema)
    .query(async (opts) => {
    })
})
``

**Comment by KATT** [comment]
- The result of `inferRouterInputs` should be `schema._input` as it's what is sent from a client perspective
- The result in the resolver (aka `.query(opts) => opts.input)` should be `schema._output`

**Comment by smndtrl** [comment]
Then it was a misunderstanding on my side. I think I never fully understood until now that the `transform` function transforms just data parsed afterwards and not the schema validated. The docs state it but not the other resources I read.

Great work with tRPC and thanks!!
