### ISSUE TITLE
bug: Cannot compile trpc-server without having `skipLibCheck` enabled

### ISSUE THREAD

**Issue by SimonSimCity** [trpc/trpc#6136]
### Provide environment information

```
  System:
    OS: macOS 14.4.1
    CPU: (8) arm64 Apple M1
    Memory: 59.11 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.10.0 - ~/.nvm/versions/node/v20.10.0/bin/node
    npm: 10.2.3 - ~/.nvm/versions/node/v20.10.0/bin/npm
    pnpm: 9.12.2 - ~/.nvm/versions/node/v20.10.0/bin/pnpm
  Browsers:
    Chrome: 129.0.6668.101
    Safari: 17.4.1
  npmPackages:
    @trpc/server: 11.0.0-rc.580 => 11.0.0-rc.580+26ac97c0e 
    typescript: ^5.6.3 => 5.6.3 
```

### Describe the bug

When trying to compile my project with `tsc`, I get the following error message:

```plain
node_modules/.pnpm/@trpc+server@11.0.0-rc.580/node_modules/@trpc/server/dist/unstable-core-do-not-import/stream/sse.d.ts:66:30 - error TS2552: Cannot find name 'EventSourceInit'. Did you mean 'EventSource'?

66     init: () => MaybePromise<EventSourceInit> | undefined;
                                ~~~~~~~~~~~~~~~

  node_modules/.pnpm/@types+node@22.7.6/node_modules/@types/node/globals.d.ts:564:9
    564     var EventSource: typeof globalThis extends { onmessage: any; EventSource: infer T } ? T
                ~~~~~~~~~~~
    'EventSource' is declared here.


Found 1 error in node_modules/.pnpm/@trpc+server@11.0.0-rc.580/node_modules/@trpc/server/dist/unstable-core-do-not-import/stream/sse.d.ts:66
```

It compiles after setting `skipLibCheck` to `true`.

### Link to reproduction

https://stackblitz.com/edit/github-efvgvu?file=tsconfig.json

### To reproduce

Run `tsc` in the console.

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/6136">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/6136/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/6136/pledge.svg">
</picture>
</a>

**Comment by KATT** [comment]
`skipLibCheck: true` is kinda reocmmended for making apps - however, I'm fixing this in #6084 

Thanks fore reporting, we do want trpc to work without any specific type deps
