### ISSUE TITLE
Nullable inputs with default values are still required by the client

### ISSUE THREAD

**Issue by Xetera** [trpc/trpc#615]
When defining a route, it would be really convenient if the client can omit an input if there's a default value defined in the zod schema and make sure it's not typed as nullable on the server side.

Currently when you mark a type with something like `z.number().default(0)` the type stays `number` for both client and server which prevents the client from omitting it in the input.

When you mark it as `z.number().default(0).optional()` the type of that resolves to `number | undefined` on both the client and server which prevents the server from assuming the input is non-null.

Here's a fork of the example codesandbox on the site that demonstrates the issue
https://codesandbox.io/s/eloquent-golick-uhbsi?file=/src/server.ts

Apologies if this is a zod issue and not a trpc one. I figured it might be more relevant here since I'm guessing trpc controls the distinction between client and server input types.

**Comment by KATT** [comment]
Thanks for supplying a reproduction! 🙏


This does indeed sound like a zod issue - did a quick skim through the issues, maybe this is relevant? https://github.com/colinhacks/zod/issues/425

Feel free to close if you conclude its zod and not trpc ☺

**Comment by KATT** [comment]
I don't think this is possible with zod.. don't think you can infer the input type _and_ the output type of a schema.

I reckon you're better off making it optional/nullish & relying the `?? 0` inline rather than zod's `.default()`. That's what I still do as I haven't used these new zod 3 features much

**Comment by Xetera** [comment]
The issue you linked is pretty similar to what I'm asking but not exactly the same thing. I ended up loosening the "promise" made in the router side where I default to a 0 like you mentioned. It's a little unfortunate since zod feels so versatile but it gets the job done here. Thank you for the response 👍
