### ISSUE TITLE
bug: Cannot access context injected via middleware in onError handler

### ISSUE THREAD

**Issue by williamgoulois** [trpc/trpc#6157]
### Provide environment information

```
System:
    OS: macOS 14.7
    CPU: (8) arm64 Apple M1 Pro
    Memory: 541.69 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.15.0 - ~/.local/state/fnm_multishells/91576_1729759671410/bin/node
    Yarn: 1.22.19 - ~/Library/pnpm/yarn
    npm: 10.7.0 - ~/.local/state/fnm_multishells/91576_1729759671410/bin/npm
    pnpm: 9.12.1 - ~/Library/pnpm/pnpm
    bun: 1.1.30 - /opt/homebrew/bin/bun
  Browsers:
    Chrome: 130.0.6723.70
    Edge: 130.0.2849.56
    Safari: 18.0.1
  npmPackages:
    @tanstack/react-query: 5.51.15 => 5.51.15
    @trpc/client: 11.0.0-rc.467 => 11.0.0-rc.467+8f72171d6
    @trpc/react-query: 11.0.0-rc.467 => 11.0.0-rc.467+8f72171d6
    @trpc/server: 11.0.0-rc.467 => 11.0.0-rc.467+8f72171d6
    next: 14.1.0 => 14.1.0
    react: 18.3.1 => 18.3.1
	typescript: 5.5.4 => 5.5.4
````

## Context
We use tRPC in a monorepo containing :
- one backed using Fastify with tRPC plugin
- multiple frontends consuming this backend

We are building some kind of big funnel/stepper with some global progress state.
We get this global progress state from a database and inject it inside the `ctx` using tRPC middleware to access it inside queries/mutations.
We throw `TRPCError`s inside our queries/mutations and handle them inside the `onError` callback defined in the tRPC adapter.

## BUG
Inside the `onError` handler, the `ctx` does not contain data injected to procedures via middlewares. 
We only have access to the "global" context, instantiated with the Fastify adapter and not to the one injected via middleware.

### Link to reproduction

https://stackblitz.com/edit/github-y9mdyw?file=src%2Fpages%2Fapi%2Ftrpc%2F%5Btrpc%5D.ts

### To reproduce

Stackblitz link should be self-explanatory.
I just created a global context with a `globalContextValue` accessible inside procedure and `onError` handler.
Nevertheless `injectedContextValue` is accessible inside procedure but not inside `onError` handler.

### Additional information

I think the problem relies on the architecture of the error handling, where the `catch` does happen outside the procedure and we do not have access to it's enhanced context.

The bug is not specific to Fastify adapter implementation because I managed to reproduce it using the `next-minimal-starter` on Stackblitz

## QUESTIONS
1. Is it expected behavior ? I cannot see it documented in the website nor inside issues.
2. How could we fix our problem ?
- One solution would be to inject the global context inside the Error cause. We want to avoid this as we already use this to provide context specific to the error (not contained in global progress data). 
- Could we somehow catch the error ourselves and augment it with data before we loose injected context ?

I would love to contribute/help if I can !

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/6157">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/6157/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/6157/pledge.svg">
</picture>
</a>

**Comment by KATT** [comment]
This is expected behavior, if you want more meta data to the error thrown, you can try sub-classing our errors or something

**Comment by williamgoulois** [comment]
@KATT Wouldn't it be possible to :
1. First, extract all middlewares defined for a procedure and execute all of them sequentially 
2. Update `ctx`, `input`... with potentially modified data
3. Then Execute query/mutation part of the procedure with try catch like you already do
4. Get context enhanced with middleware data inside all error handling

**Comment by KATT** [comment]
Yeah, but the type could lie to you then since something from the original context could be overwritten so we'd have to do `ctx: unknown` on the `onError`-callback

**Comment by KATT** [comment]
Feel free to do a PR to update the docs for error handling once you've solved your problem, I don't see the issue with the current way of doing things and "fixing" it will cause other problems
