### ISSUE TITLE
feat: Toggle Transformer per Router

### ISSUE THREAD

**Issue by ZetabS** [trpc/trpc#6225]
### Describe the feature you'd like to request

Currently, when uploading `formData` in tRPC with `zod-form-data`, transformers such as `SuperJSON` attempt to parse the data even when it is `NonJsonSerializable`. This disrupts the handling of `formData`, causing validation errors.
```
[
  {
    "code": "invalid_type",
    "expected": "string",
    "received": "undefined",
    "path": ["name"],
    "message": "Required"
  },
  {
    "code": "custom",
    "message": "Input not instance of File",
    "fatal": true,
    "path": ["image"]
  }
]
```

I would like to suggest a feature that allows toggling the transformer on a per-router basis or automatically disabling it when the input data meets the `isNonJsonSerializable` condition. This could help prevent unnecessary parsing and improve handling of non-JSON serializable data types.

### Describe the solution you'd like to see

```
export const roomRouter = router({
  sendMessage: publicProcedure
    .disableTransformer() // add option to disable transformer somewhere
    .input(uploadFileSchema)
    .mutation(async (opts) => {
      return {
        image: await writeFileToDisk(opts.input.image),
      };
    }),
});
```

### Describe alternate solutions

The only solution I’ve found so far is to not use the transformer altogether.

I tried to bypass transformer when an object is `isNonJsonSerializable` like this:
```
const transformer = {
  serialize: (object) => {
    if (isNonJsonSerializable(object)) {
      return object;
    }
    return SuperJSON.serialize(object);
  },
  deserialize: (object) => {
    if (isNonJsonSerializable(object)) {
      return object;
    }
    return SuperJSON.deserialize(object);
  },
};

```
However, this approach didn’t work because simply calling the transformer itself seems to set the body to undefined and stop the file stream. (I'm not entirely sure, but that’s what it seems like)

### Additional information

You can reproduce the issue in [this fork](https://github.com/ZetabS/examples-next-formdata-transformer)

Steps to Reproduce
1. Clone the repository and install dependencies.
2. Run the development server.
3. Attempt to upload formData with an image.

### 👨‍👧‍👦 Contributing

- [x] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/6225">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/6225/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/6225/pledge.svg">
</picture>
</a>

**Comment by ZetabS** [comment]
@KATT Thank you for your response. I’ve already reviewed the `trpc/examples-next-formdata` and modified it to try applying a transformer. The fork is included in the Additional Information section and is also linked [here](https://github.com/ZetabS/examples-next-formdata-transformer).

Could you please take a look? I believe it highlights the exact problem that isn’t addressed in the provided example.

**Comment by ZetabS** [comment]
The exact problem is that the only option is to either apply the transformer to the entire instance or not use it at all. This is problematic because tRPC follows the singleton pattern, meaning formData procedures must be included alongside "normal" JSON procedures within the same instance. However, you can't use a transformer with a formData procedure, and I still want to use a transformer in my "normal" JSON procedures.

Am I missing something here?

**Comment by dhatGuy** [comment]
This might help https://github.com/trpc/trpc/issues/1937#issuecomment-2267163025

**Comment by ZetabS** [comment]
@dhatGuy Thank you for pointing that out. I hadn't thought about separating the transformer... That comment resolves the issue for me.
