### ISSUE TITLE
bug: Incorrect Type on Async Generators

### ISSUE THREAD

**Issue by iamnafets** [trpc/trpc#6226]
### Provide environment information

Stackblitz Below

### Describe the bug

It seems like the client-side type of a procedure with a generator is `AsyncGenerator` but it lacks a `.next()` method, which throws if you depend on it. I think the proper type currently is `AsyncIterable` but ideally the resulting object would have the full set of methods that an `AsyncGenerator` has.

### Link to reproduction

https://stackblitz.com/edit/trpc-trpc-yfcdjw?file=src%2Fclient%2Findex.ts

### To reproduce

When you run the stackblitz you get no compile-time errors but it throws a type error at runtime. The compiler error below is intentional: this should be failing compilation.

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/6226">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/6226/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/6226/pledge.svg">
</picture>
</a>

**Comment by KATT** [comment]
We lie in the type. What we actually return is an iterator, not a generator

**Comment by KATT** [comment]
Or actually an `AsyncIterableIterator` I think

**Comment by KATT** [comment]
I've fixed the typing now. 

I guess we could return an `AsyncGenerator` instead - would that have any benefits?
