### ISSUE TITLE
bug: nested routers are type never on client

### ISSUE THREAD

**Issue by alita-moore** [trpc/trpc#6237]
### Provide environment information

checkout the codesandbox here: https://codesandbox.io/p/devbox/84v3vw

### Describe the bug

<img width="521" alt="Screenshot 2024-11-15 at 3 50 11 AM" src="https://github.com/user-attachments/assets/9338fcce-b66d-4e30-9f68-a79d3036707a">

as you can see in the picture above when you hover over the merged router it is of type never

### Link to reproduction

https://codesandbox.io/p/devbox/84v3vw

### To reproduce

hover over the nested router

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/6237">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/6237/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/6237/pledge.svg">
</picture>
</a>

**Comment by KATT** [comment]
- use the same version on client and server (you should have a dependency warning) 
- this is ony available in v11

**Comment by Michaelp1994** [comment]
hey there alita, you have different versions of @trpc/client and @trpc/server. If you update them to the same version it should solve your problem.

**Comment by alita-moore** [comment]
Thanks for your reply, it does not fix the problem

**Comment by alita-moore** [comment]
actually it seems that that fixes the problem in the repro I provided but in my code it doesn't fix the issue

**Comment by alita-moore** [comment]
actually it seems that pnpm was still using the old versions in its cache despite the package.json having the latest versions. So I deleted node_modules and reinstalled and it fixed the issue. Thanks guys!
