### ISSUE TITLE
bug: the subscription payload on the onData callback for the useSubscription hook has type "any" in release v11.0.0-rc.637 and above (633 works)

### ISSUE THREAD

**Issue by tokenosopher** [trpc/trpc#6243]
### Provide environment information

  System:
    OS: macOS 15.0.1
    CPU: (8) arm64 Apple M3
    Memory: 428.25 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.17.0 - ~/.nvm/versions/node/v20.17.0/bin/node
    npm: 10.8.2 - ~/.nvm/versions/node/v20.17.0/bin/npm
    pnpm: 9.11.0 - ~/.nvm/versions/node/v20.17.0/bin/pnpm
  Browsers:
    Safari: 18.0.1
  npmPackages:
    @tanstack/react-query: ^5.59.15 => 5.60.2 
    @trpc/client: next => 11.0.0-rc.638+09a76869e 
    @trpc/react-query: next => 11.0.0-rc.638+09a76869e 
    @trpc/server: next => 11.0.0-rc.638+09a76869e 
    next: ^15.0.2 => 15.0.3 
    react: ^18.3.1 => 18.3.1 
    typescript: ^5.6.2 => 5.6.3 

### Describe the bug

You can run the examples-next-see-chat to reproduce - I see the same behaviour on my project as well.

The payload has the right type in rc.633 and lower, but anything above it has type any. I will revert to version 633 until this gets resolved, but thought I'd flag.

### Link to reproduction

https://github.com/trpc/examples-next-sse-chat

### To reproduce

Clone the examples-next-sse-chat repo, go to src/app/channels/[channelId]/hooks.ts and check the type for the onData payload - you will see it's of type "any".

How to patch: downgrade trpc to 11.0.0-rc.633, you will see it has the correct type.

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/6243">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/6243/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/6243/pledge.svg">
</picture>
</a>

**Comment by KATT** [comment]
Pro due to fixing #6226

**Comment by KATT** [comment]
I found what it is, you're using an older version of TypeScript in your project or your editor


`AsyncIterable` before `5.6` was defined as

```ts
interface AsyncIterable<T> {
```


now it is


```ts
interface AsyncIterator<T, TReturn = any, TNext = undefined> {
```

& we use those args, will see if we can make it backwards compat 👀

**Comment by KATT** [comment]
Solution for now: bump your typescript to `>=5.6.2` - we might bump our minimal TS requirement or we might do a workaround

**Comment by KATT** [comment]
We're just going to bump the minimal TypeScript version-needed

**Comment by tokenosopher** [comment]
ah great thanks!

**Comment by tokenosopher** [comment]
Will bump up my TS
