### ISSUE TITLE
bug: Can't create "createClient"  after creating "createTRPCReact<AppRouter>()"

### ISSUE THREAD

**Issue by YuraGB** [trpc/trpc#6252]
### Provide environment information

  System:
    OS: Windows 11 10.0.22631
    CPU: (12) x64 AMD Ryzen 5 5600X 6-Core Processor
    Memory: 10.76 GB / 31.95 GB
  Binaries:
    Node: 18.19.1 - C:\Program Files\nodejs\node.EXE
    npm: 10.2.4 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.15.4 - ~\AppData\Local\pnpm\pnpm.EXE
  Browsers:
    Edge: Chromium (130.0.2849.68)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    @tanstack/react-query: ^5.60.6 => 5.60.6
    @trpc/client: ^11.0.0-rc.638 => 11.0.0-rc.638+09a76869e
    @trpc/react-query: ^11.0.0-rc.638 => 11.0.0-rc.638+09a76869e
    @trpc/server: ^11.0.0-rc.638 => 11.0.0-rc.638+09a76869e
    next: 15.0.3 => 15.0.3
    react: 19.0.0-rc-66855b96-20241106 => 19.0.0-rc-66855b96-20241106
    typescript: ^5 => 5.6.3

### Describe the bug

After creating an object from the method  "createTRPCReact" there is no the method "createClient" or any procedures in it.

`const trpc = createTRPCReact<AppRouter>();

trpc.<...no createClient or procedures..>`

### Link to reproduction

https://stackblitz.com/edit/github-is5mgb?file=src%2Fserver%2Ftrpc.ts

### To reproduce

It's easy to reproduce - clean Nextjs project  and instructions from quickstart from react query integration

### Additional information

I investigated working code  from @jherr [repo](https://github.com/jherr/trpc-on-the-app-router.git)  the file createTRPCReact.tsx was much changed - almost 300 rows were added  and the main method "createTRPCReact" was changed

/------ working version of the method --------/
`export function createTRPCReact<
  TRouter extends AnyRouter,
  TSSRContext = unknown,
  TFlags = null,
>(
  opts?: CreateTRPCReactOptions<TRouter>,
): CreateTRPCReact<TRouter, TSSRContext, TFlags> {
  const hooks = createHooksInternal<TRouter, TSSRContext>(opts);
  const proxy = createHooksInternalProxy<TRouter, TSSRContext, TFlags>(hooks);

  return proxy as any;
}`
/------------------------------------------------/

/---------------- not working -----------------/
`export function createTRPCReact<
  TRouter extends AnyRouter,
  TSSRContext = unknown,
>(
  opts?: CreateTRPCReactOptions<TRouter>,
): CreateTRPCReact<TRouter, TSSRContext> {
  const hooks = createRootHooks<TRouter, TSSRContext>(opts);
  const proxy = createHooksInternal<TRouter, TSSRContext>(hooks);

  return proxy as any;
}
`

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/6252">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/6252/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/6252/pledge.svg">
</picture>
</a>

**Comment by KATT** [comment]
I don't understand this bug report - the stackblitz doesn't really run, but think there's some misconfiguration. We have this working everywhere

As an example:
https://github.com/trpc/trpc/blob/6c8fc969889045f0e08d43aa0d7c385cecf89805/examples/minimal-react/client/src/App.tsx#L7-L26

**Comment by KATT** [comment]
Hey there! :wave:

We appreciate the time you've taken to write this issue.

Unfortunately, we don't have the capacity to assist with issues without a reproduction repository and this issue does not seem to be related to tRPC itself. 

Please feel free to re-open with a solid reproduction repository where we can help you further or post in our help channels on [Discord](https://trpc.io/discord) or in our [GitHub Discussions](https://github.com/trpc/trpc/discussions).
