### ISSUE TITLE
bug: @trpc/server@next also installing Next.js (regression in 11.0.0-rc.630)

### ISSUE THREAD

**Issue by isaac-mcfadyen** [trpc/trpc#6254]
### Provide environment information

```
  System:
    OS: macOS 15.1.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 272.78 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.9.0 - ~/.local/state/fnm_multishells/33847_1732119510341/bin/node
    Yarn: 1.22.22 - ~/.local/state/fnm_multishells/33847_1732119510341/bin/yarn
    npm: 10.8.2 - ~/.local/state/fnm_multishells/33847_1732119510341/bin/npm
    pnpm: 9.12.1 - ~/.local/state/fnm_multishells/33847_1732119510341/bin/pnpm
    bun: 1.1.26 - ~/.bun/bin/bun
  Browsers:
    Chrome: 131.0.6778.70
    Safari: 18.1.1
  npmPackages:
    typescript: ^5.6.3 => 5.6.3 
```

### Describe the bug

Hey! 👋 

Apologies if I missed an existing issue for this.

It looks like `@trpc/server` is now installing Next.js as a dependency.

Looks like this was a regression introducred in `11.0.0-rc.630` based on my testing. Installing `11.0.0-rc.621` locally doesn't bring in Next, but as soon as I install `11.0.0-rc.630` it starts pulling in Next.

This is significantly bloating any installs because I don't use Next.js with tRPC (especially on the server), and it's a 20MB (+40MB for SWC) install that's being pulled in with `@trpc/server`.

### Link to reproduction

https://stackblitz.com/edit/node-6i9dpd?file=index.js

Note: just run `pnpm install` and then look in `node_modules/.pnpm` and you'll see that Next and React DOM has been installed (when only `@trpc/server@11.0.0-rc.630` was installed).

### To reproduce

- Start blank Node.js project (best reproduced without any other dependencies). 
- Install `@trpc/server@11.0.0-rc.621`
- Notice how install completes almost immediately and Next is not installed.
- Install `@trpc/server@11.0.0-rc.630`
- Observe as Next.js is seemingly downloaded (I can see it downloading 20MB + 40MB for SWC on my slow connection, might not be as noticeable on a faster connection).

### 👨‍👧‍👦 Contributing

- [x] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/6254">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/6254/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/6254/pledge.svg">
</picture>
</a>

**Comment by MattIPv4** [comment]
It looks like `next` is an optional dependency of the `server` package: https://github.com/trpc/trpc/blob/5c3057a917ab078fb7d0620e614f884a9c65d682/packages/server/package.json#L157

Looking at https://docs.npmjs.com/cli/v9/configuring-npm/package-json#optionaldependencies, they're going to get installed by default unless the user explicitly opts out of installing them.

I imagine instead these should be peer dependencies, with the peer dependency meta obj marking them as optional? I think that might behave better?

**Comment by KATT** [comment]
Thanks. It's an easy fix, will fix tmrw unless @trpc/trpc-core beats me to it

**Comment by juliusmarminge** [comment]
> I imagine instead these should be peer dependencies, with the peer dependency meta obj marking them as optional? I think that might behave better?

Optional peerDependencies is a myth that I don't think any package manager honors... better to just remove them i think

**Comment by MattIPv4** [comment]
Both the pnpm and npm docs explicitly call out peerDependenciesMeta and setting a package as optional, so I would think it is honored?

**Comment by juliusmarminge** [comment]
yea they're supposed to - and in the simple cases they do but i have multiple monorepos where they're complaining about peer deps that's caused by optional peer deps being pulled in where they shouldn't

**Comment by juliusmarminge** [comment]
here you have an example of it breaking:

```json
{
  "name": "pnpm",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "ai": "^3",
    "typescript": "^5.6.3"
  },
  "packageManager": "pnpm@9.6.0"
}
```

where the `ai` SDK has all of these as optional:

![CleanShot 2024-11-22 at 12 41 24@2x](https://github.com/user-attachments/assets/b230bc92-7a53-4f0c-880c-dfae761db543)

yet they are installed:

![CleanShot 2024-11-22 at 12 40 32@2x](https://github.com/user-attachments/assets/5891bb8f-e0d1-40dc-b88c-7d283c4d60a9)
