### ISSUE TITLE
bug: stream returns once instead of sequentially with cloudflare

### ISSUE THREAD

**Issue by alirv90** [trpc/trpc#6285]
### Provide environment information

```
OS: MacOS 15.0.1
Node: v22.11.0
```

### Describe the bug

My repo: https://github.com/alirv90/cfplay

trpc stream works well on nodejs with standalone adapter, but with cloudflare and fetch adapter it waits until the stream is complete before returning results

### Link to reproduction

https://github.com/alirv90/cfplay

## Node

```
pnpm dev:node
npx tsx ./src/client.ts
```

Stream will work
1, 2, 3 will be logged after each second

## Cloudflare

```
pnpm dev:cloudflare
npx tsx ./src/client.ts
```

Stream will not work
1, 2, 3 will be logged at once

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/6285">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/6285/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/6285/pledge.svg">
</picture>
</a>

**Comment by KATT** [comment]
Does cf support streaming? If so, can you point to a vanilla setup with cf that does it?

**Comment by alirv90** [comment]
@KATT  Cloudflare supports streams https://developers.cloudflare.com/workers/runtime-apis/streams/, but when I test with vanilla setup and hono, the same problem occurs as with trpc. Look like this is problem of Cloudflare.
