### ISSUE TITLE
Error handling best practices

### ISSUE THREAD

**Issue by sam3d** [trpc/trpc#631]
Hello 👋  First of all thank you so much for this amazing project, it's _awesome_ to use and we're adopting it for some of our public facing services as an alternative to GraphQL at utility-company scale

Question about error handling best practices; the JSON-RPC spec includes the following description:

> The error codes from and including -32768 to -32000 are reserved for pre-defined errors. Any code within this range, but not defined explicitly below is reserved for future use. The error codes are nearly the same as those suggested for XML-RPC at the following url: http://xmlrpc-epi.sourceforge.net/specs/rfc.fault_codes.php

> The remainder of the space is available for application defined errors.

https://www.jsonrpc.org/specification#error_object

However, TRPC errors appear limited to the subset defined in the spec:

![image](https://user-images.githubusercontent.com/8385528/124611553-76bd9380-de69-11eb-9912-b7bbf48116b1.png)

Does this mean that best practices for error handling is to return them as a standard result of the request instead of as a special error thrown:

```typescript
// I.e. this
return { error: "CUSTOM_ERROR" }; // This would also now be typed correctly on the client
// Instead of this
throw new TRPCError({ code: "CUSTOM_ERROR" }); // This is a type error
```

Once again, thank you so much for this amazing library!

**Comment by cyrus-za** [comment]
I agree that we can expand from general HTTP errors to JSON-RPC spec. I'll wait for @KATT to respond when he is back next week

**Comment by KATT** [comment]
Hey, I'll respond properly when I'm at a laptop in a few days

Here's just some points really quickly:

- tRPC is not really intended for public services as the contract of the api is inferred rather than declared, so be careful if doing that, or consider if graphql would be a better fit
- I think I've exposed more error codes than I've meant, the main ones I rely on in my application code are: unauthorized, forbidden, internal server error, bad request.
- if you want custom errors or more granular control, look into formatError  https://trpc.io/docs/error-formatting

**Comment by sam3d** [comment]
Thank you for the quick response! I think the biggest issue I've faced is with using `mutateAsync` and losing inferred typing in the error thrown (as exceptions don't have types, vs the error object in just `mutate`). Would there be some way to transform the returned response from Zod if input validation fails into an `errors` object in the standard response, similar to the behaviour of graphql?

**Comment by KATT** [comment]
I think I understand what you mean and yes, that's exactly the purpose of `formatError` - see the example in the link above.

**Comment by sam3d** [comment]
Thank you for the quick reply! Sorry I deleted my comment so I could word it better as I think I wrote it too late at night to be making sense 😄 

All of your replies make total sense - this is entirely an internal service so I have no worries about maintaining an explicit contract, having it inferred is already a massive time saver! I think what I'm maybe trying to do is to intercept the Zod input validation pipeline to prevent the error getting sent back as something that makes the client `throw` on `mutateAsync` (i.e. 200 instead of 400 like it is now)?

I've been able to add context aware error handling by composing hooks around that which trpc provides:

```ts
const trpc = createReactQueryHooks<AppRouter>();
type UseQuery = typeof trpc.useQuery;

function handleError(err: TRPCClientError<AppRouter>, router: NextRouter) {
  switch (err.shape?.data.code) {
    case "UNAUTHORIZED":
      router.push("/login");
  }
}

export const useMutation: UseMutation = (path, opts) => {
  const router = useRouter();

  return trpc.useMutation(path, {
    retry: false,
    onError: (err) => handleError(err, router),
    ...opts,
  });
};
```

But when calling `mutateAsync` I'm looking for a type safe way to handle that error (like how just `mutate` can with the `{ errors }` destructure), which I can't do within the flow of normal exception handling, as that remains untyped. I tried wrapping the returned `mutateAsync` function from the `useMutation` hook but it lost the correct type discriminator when I tried.

If you could point me towards a better way to do this instead of either having to coerce the type on the client or preventing input validation from throwing a bad request exception on the server (which it does feel like it _should_ do and I probably wouldn't want to interfere with that), that would be super appreciated!

**Comment by KATT** [comment]
Hmm, if you don't want the input validation to throw you could do an empty pass through function in input, then do the validation yourself and return another output.

On my phone, so hard to type code, but for example - -

```ts
input: (v) => v, 
async resolve({input}) {
// do your zod validation, return something if bad / or throw custom error to handle in formatError
// else return something else
// .. 
```

**Comment by sam3d** [comment]
I considered doing that but yeah exactly I didn't want to lose implicit type safety. I'll continue to see if I can wrap `mutateAsync` to return `{ data, errors }` and also add an options object with something like axios's `validateStatus`. Thank you for your help (and again for making this awesome library!) ❤️

**Comment by KATT** [comment]
Again, check out https://trpc.io/docs/error-formatting

It might be what you are looking for.

**Comment by sam3d** [comment]
At the time I posted this issue I had already used these docs to return the zod validation error (and thank you for your perfect example there), but I couldn’t figure out how to modify this to return a different error code from the validation.

**Comment by KATT** [comment]
Again, check out https://trpc.io/docs/error-formatting

It might be what you are looking for.

**Comment by sam3d** [comment]
Can it do that?
