### ISSUE TITLE
bug: useUtils gives undefined state in updated callback on a paginated endpoint

### ISSUE THREAD

**Issue by misbahkhalilaz** [trpc/trpc#6312]
### Provide environment information

```  System:
    OS: macOS 15.1.1
    CPU: (8) arm64 Apple M1
    Memory: 127.38 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.4.1 - ~/.nvm/versions/node/v22.4.1/bin/node
    Yarn: 1.22.22 - ~/.nvm/versions/node/v22.4.1/bin/yarn
    npm: 10.8.1 - ~/.nvm/versions/node/v22.4.1/bin/npm
  Browsers:
    Chrome: 131.0.6778.140
    Edge: 131.0.2903.70
    Safari: 18.1.1
  npmPackages:
    @tanstack/react-query: ^4.36.1 => 4.36.1 
    @trpc/client: ^10.43.6 => 10.45.2 
    @trpc/next: ^10.43.6 => 10.45.2 
    @trpc/react-query: ^10.43.6 => 10.45.2 
    @trpc/server: ^10.43.6 => 10.45.2 
    next: ^14.2.9 => 14.2.9 
    react: ^18.3.1 => 18.3.1 
    typescript: ^5.5.4 => 5.5.4```

### Describe the bug

```ts
trpcUtils.notification.getNotifications.setInfiniteData( // also tried with .setData
      undefined, // also tried pagination args here
      (currState) => {
                  // currState is always undefined here
         }
)
```
In the sample code snippet above, getNotifications is a paginated trpc endpoint; in the updater CB of setInfiniteData, currState is always undefined. It works fine if we don't implement pagination, but it's not working with pagination.

### Link to reproduction

I'll provide this later

### To reproduce

- Create a cursor base paginated trpc endpoint.
- Try to update the trpc client state using trpc.useUtils().

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/6312">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/6312/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/6312/pledge.svg">
</picture>
</a>

**Comment by KATT** [comment]
Hey there! :wave:

We appreciate the time you've taken to write this issue.

Unfortunately, we don't have the capacity to assist with issues without a reproduction repository and this issue does not seem to be related to tRPC itself. 

Please feel free to re-open with a solid reproduction repository where we can help you further or post in our help channels on [Discord](https://trpc.io/discord) or in our [GitHub Discussions](https://github.com/trpc/trpc/discussions).

---


You can see our tests for `setInfiniteData` below:


https://github.com/trpc/trpc/blob/3957a7dc564b14f52ce6ba5078490e73b6b6be98/packages/tests/server/react/useUtils.test.tsx#L535-L632
