### ISSUE TITLE
bug: @types/node type pollution

### ISSUE THREAD

**Issue by trizau** [trpc/trpc#6315]
### Provide environment information

  System:
    OS: macOS 15.2
    CPU: (8) arm64 Apple M3
    Memory: 99.75 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.12.0 - ~/.version-fox/temp/1734105600-12302/nodejs/bin/node
    npm: 10.9.0 - ~/.version-fox/temp/1734105600-12302/nodejs/bin/npm
    pnpm: 9.15.0 - ~/.version-fox/temp/1734105600-12302/nodejs/bin/pnpm
  Browsers:
    Chrome: 131.0.6778.140
    Safari: 18.2

### Describe the bug

In a project with separated front-end and back-end, the front-end project references the @trpc/server type, causing type pollution in the front-end project. For example, before the server type is introduced, the return value of `setTimeout()` is `number`, but after the reference, it becomes `NodeJS.Timeout`

<img width="779" alt="image" src="https://github.com/user-attachments/assets/d1821f22-e3bb-448b-ac70-7e8b7824d0ce" />

### Link to reproduction

https://github.com/codingwithmanny/trpc-siwe-monorepo

### To reproduce

Clone `https://github.com/codingwithmanny/trpc-siwe-monorepo` and install dependencies, write code in `packages/react`

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/6315">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/6315/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/6315/pledge.svg">
</picture>
</a>

**Comment by KATT** [comment]
Uhm, how is this related to trpc? You're installing `@types/node` which adds stuff to the global scope
