### ISSUE TITLE
bug: standalone server subscription listeners not aborted on client disconnect, when run with deno  

### ISSUE THREAD

**Issue by HernanFdz** [trpc/trpc#6317]
### Provide environment information

```
  System:
    OS: macOS 15.1.1
    CPU: (14) arm64 Apple M4 Pro
    Memory: 225.63 MB / 48.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.11.0 - ~/.nvm/versions/node/v22.11.0/bin/node
    Yarn: 1.22.22 - ~/.nvm/versions/node/v22.11.0/bin/yarn
    npm: 10.9.0 - ~/.nvm/versions/node/v22.11.0/bin/npm
    pnpm: 9.15.0 - ~/.nvm/versions/node/v22.11.0/bin/pnpm
  Browsers:
    Chrome: 131.0.6778.140
    Safari: 18.1.1
  npmPackages:
    @trpc/client: ^11.0.0-rc.648 => 11.0.0-rc.660+74625d5e4 
    @trpc/react-query: ^11.0.0-rc.648 => 11.0.0-rc.660+74625d5e4 
    @trpc/server: ^11.0.0-rc.648 => 11.0.0-rc.660+74625d5e4 
    react: ^19.0.0 => 19.0.0     
```

### Describe the bug

I have a very simple router with an even simpler subscription route, created as documented (notice the signal being passed down to the listener)

```tsx
t.procedure.
subscription(async function* (opts) {
        for await (
            const [data] of on(ee, eventName, {
                signal: opts.signal,
            })
        ) {
            ...

            yield data;
        }
    }),
```

from which a handler is created, to be exposed through an http server

```tsx
const handler = createHTTPHandler({
    router: appRouter,
    middleware: cors(),
});

const server = createServer(handler);

server.listen(3001);
``` 

which a super simple react app is setup to connect to

```tsx
export function App() {
  const [queryClient] = useState(() => new QueryClient());
  const [trpcClient] = useState(() =>
    trpc.createClient({
      links: [
        splitLink({
          // uses the httpSubscriptionLink for subscriptions
          condition: (op) => op.type === "subscription",

          true: unstable_httpSubscriptionLink({
            url: "http://localhost:3001",
          }),

          false: httpBatchLink({
            url: `http://localhost:3001`,
          }),
        }),
      ],
    })
  );

  return (
    <trpc.Provider client={trpcClient} queryClient={queryClient}>
      <QueryClientProvider client={queryClient}>
        <View />
      </QueryClientProvider>
    </trpc.Provider>
  );
}
```

so that this minimal view can make use of the router

```tsx
export function View() {
    const { mutateAsync: test } = trpc.test.useMutation();

    trpc.onTest.useSubscription(undefined, {
        onData: (data) => {
            console.log("-->   ~ data:", data);
        },
    });

    return <button onClick={() => test()}>test</button>;
}
```

And this all works perfectly fine when running the server with `tsx`, but when run with `deno`, which I would have expected to behave the same, it does not throw any sort of error or complain, it seems to work fine as well, but...

There's a critical issue: the subscription listener keeps running even after the client disconnect, which makes it unusable. 

From what I can tell, this seems to happen because the request signal is never aborted. Now, why that is, I have no idea.

From reading Deno docs, they do push away from `node`'s `createServer()` into their built-in `Deno.serve()`.
So I tried moving there, but apparently it uses completely different request/response interfaces, which makes it incompatible with `trpc`'s current `createHTTPHandler()` adaptor.

So I guess the proper way to handle it would be to implement a `deno`-specific adaptor, but I would need some help on how to go about doing so.

### Link to reproduction

https://github.com/HernanFdz/trpc-deno

### To reproduce

1) `npm i`
2) `npm run client`

_on another terminal tab..._

-----------------------------
**A. success case**

3) `npm run server:node`

**B. failure case**

3) `npm run server:deno`
-----------------------------

4) go to [http://localhost:5173](http://localhost:5173)

5) refresh the browser tab a few times, so that multiple subscriptions are stablished
6) click the `test` button
7) look at the terminal logs comming from the subscription listener ( `"test subscription listener received:"` ):
     A. **success case (`node`)** -> _only one log (previous listeners are aborted on client disconnect/refresh)_
     B. **failure case (`deno`)** -> _multiple identical logs (all previous listeners remain active)_

### Additional information

I'd really love to contribute, but I fear the ultimate issue here is beyond my knowledge...

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/6317">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/6317/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/6317/pledge.svg">
</picture>
</a>

**Comment by KATT** [comment]
Sounds like a deno bug, likely they don't support the abort signal in `on()`

**Comment by KATT** [comment]
Might be a Deno-equivalent of https://github.com/oven-sh/bun/issues/14187 - see my minimal repro [here](https://github.com/oven-sh/bun/issues/14187#issuecomment-2377981305)


We test against Node.js as primary target - both Deno and Node should be largely(fully?) Node compatible. If you find something that looks like a bug in tRPC when running Deno but it works with Node.js, it's likely a Den-issue and not a tRPC one.
