### ISSUE TITLE
bug: Regression with subscription output types

### ISSUE THREAD

**Issue by changesbyjames** [trpc/trpc#6320]
### Provide environment information

Working:
```
  System:
    OS: macOS 15.1.1
    CPU: (12) arm64 Apple M3 Pro
    Memory: 103.11 MB / 36.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.2.0 - ~/.nvm/versions/node/v22.2.0/bin/node
    npm: 10.9.0 - ~/Developer/personal/alveus/census/clips/provider/node_modules/.bin/npm
    pnpm: 9.7.1 - ~/Library/pnpm/pnpm
    bun: 1.1.21 - ~/.bun/bin/bun
  Browsers:
    Chrome: 131.0.6778.140
    Edge: 131.0.2903.99
    Safari: 18.1.1
  npmPackages:
    @trpc/client: 11.0.0-rc.632 => 11.0.0-rc.632+3df8b21be 
    @trpc/server: 11.0.0-rc.632 => 11.0.0-rc.632+3df8b21be 
```

Not working:
```
  System:
    OS: macOS 15.1.1
    CPU: (12) arm64 Apple M3 Pro
    Memory: 107.80 MB / 36.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.2.0 - ~/.nvm/versions/node/v22.2.0/bin/node
    npm: 10.9.0 - ~/Developer/personal/alveus/census/clips/provider/node_modules/.bin/npm
    pnpm: 9.7.1 - ~/Library/pnpm/pnpm
    bun: 1.1.21 - ~/.bun/bin/bun
  Browsers:
    Chrome: 131.0.6778.140
    Edge: 131.0.2903.99
    Safari: 18.1.1
  npmPackages:
    @trpc/client: 11.0.0-rc.637 => 11.0.0-rc.637+19da060cb 
    @trpc/server: 11.0.0-rc.637 => 11.0.0-rc.637+19da060cb
   ```

### Describe the bug

I think there's a regression in the inferring of the output types of a subscription. Without making any other changes, aside from changing the package version and restarting the TS server, I either get or don't get the correct output types on the client. This isn't working for me on -637, or newer and it is working for me on -633. 

Working:
<img width="980" alt="image" src="https://github.com/user-attachments/assets/0217782c-05e5-41d3-a846-3d12c436dac9" />

Not working:
<img width="736" alt="image" src="https://github.com/user-attachments/assets/74ea4597-8dbd-4cfa-939d-e97044fe442c" />

### Link to reproduction

https://codesandbox.io/p/github/changesbyjames/examples-next-minimal-starter/older

### To reproduce

This issue exists in your base minimal starter without any changes. Here is a code sandbox with the default `next` versions:
https://codesandbox.io/p/github/changesbyjames/examples-next-minimal-starter/main
<img width="661" alt="image" src="https://github.com/user-attachments/assets/ce431a29-29eb-4346-8fa2-9d70b05a8791" />

Here is a codesandbox with the -633
https://codesandbox.io/p/github/changesbyjames/examples-next-minimal-starter/older
<img width="586" alt="Safari 2024-12-18 13 46 28" src="https://github.com/user-attachments/assets/44ab203c-e9e9-4ccd-821d-fe81044a1e34" />

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/6320">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/6320/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/6320/pledge.svg">
</picture>
</a>

**Comment by changesbyjames** [comment]
It looks like this was the commit that caused the issue: https://github.com/trpc/trpc/commit/19da060cb0e05c75682ec813c606b51c6c52ee19

**Comment by KATT** [comment]
I can't open your repro, can you push it in a repository?

Also, make sure you're on latest typescript, we bumped minimum peer dependency recently

**Comment by KATT** [comment]
We didn't bump enough - fixing in #6326
