### ISSUE TITLE
bug: [v11] [react] utils from createTRPCQueryUtils don't match trpc.useUtils for react, missing client

### ISSUE THREAD

**Issue by danielpza** [trpc/trpc#6335]
### Provide environment information

```
  System:
    OS: Linux 6.12
  Binaries:
    Node: 22.10.0
    Yarn: 4.5.1
    npm: 10.9.0
  npmPackages:
    @tanstack/react-query: 5.62.8 => 5.62.8 
    @trpc/client: 11.0.0-rc.666 => 11.0.0-rc.666+99556c074 
    @trpc/react-query: 11.0.0-rc.666 => 11.0.0-rc.666+99556c074 
    @trpc/server: 11.0.0-rc.666 => 11.0.0-rc.666+99556c074 
    react: 17.0.2 => 17.0.2 
    typescript: 5.5.3 => 5.5.3 
```

### Describe the bug

> https://trpc.io/docs/client/react/createTRPCQueryUtils#helpers
> Much like useUtils, createTRPCQueryUtils gives you access to same set of helpers. The only difference is that you need to pass in the queryClient and client objects.

Using the `utils` object returned from `createTRPCQueryUtils` as described in https://trpc.io/docs/client/react/createTRPCQueryUtils doesn't have all the helpers as [trpc.useUtils](https://trpc.io/docs/client/react/useUtils) does.

Namely, it's missing the `client` helper.

```ts
const utils = trpc.useUtils();
utils.client.operation.mutate;

const clientUtils = createTRPCQueryUtils({ queryClient, client: trpcClient });
clientUtils.client.operation.mutate;
// TypeScript Error: client does not exist in clientUtils
```

![image](https://github.com/user-attachments/assets/872a1b6a-7ef8-4efb-8928-f3c8ac70fa29)

### Link to reproduction

https://stackblitz.com/edit/vitejs-vite-2s7btcpj?file=src%2Ftrpc.ts

### To reproduce

https://stackblitz.com/edit/vitejs-vite-2s7btcpj?file=src%2Ftrpc.ts

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

**Comment by KATT** [comment]
I don't think this is a bug, but rather a bug in the documentation.

If you need `.client`, why not just use the object directly? 

`createTRPCQueryUtils` is made to be used "outside" of a React-tree etc, so if you have access to the result of `createTRPCQueryUtils` you should also have access to `client`

**Comment by danielpza** [comment]
> If you need .client, why not just use the object directly?

I'm not sure I follow, how can I use client directly? or which client?

I tried using trpcClient (returned from trpc.createClient) and it doesn't have the types either

![image](https://github.com/user-attachments/assets/9ad5b001-bdc8-440f-b876-908bd38a23c7)

**Comment by KATT** [comment]
You declare the client on line 8 in the stackblitz above

**Comment by danielpza** [comment]
I might be missing something, using `trpcClient.operation.mutate` gives me the same error:
https://stackblitz.com/edit/vitejs-vite-nbmvrdtf?file=src%2Ftrpc.ts

are perhaps the types wrong for trpcClient?

**Comment by KATT** [comment]
Ohhh, that helper shouldn't create an untyped helper I think 👀

**Comment by KATT** [comment]
I think this is solved now, StackBlitz is a bit confusing as it is running an old version of TypeScript which isn't compatible with tRPC anymore

**Comment by KATT** [comment]
But `.mutate()` is available now: https://stackblitz.com/edit/vitejs-vite-p3ixrhve?file=src%2Ftrpc.ts,src%2FApp.tsx,server%2Frouter.ts,package.json,node_modules%2F%40trpc%2Fclient%2Fdist%2FcreateTRPCClient.d.ts
