### ISSUE TITLE
bug: tRPC Docs page styling bug

### ISSUE THREAD

**Issue by Antonio476587** [trpc/trpc#6342]
### Provide environment information

.

### Describe the bug

It's a bug with the Dark and Light themes, when you click on the guide in a doc page, it will show the dark and light code snippet

### Link to reproduction

https://trpc.io/docs/quickstart#defining-a-backend-router

### To reproduce

Go to a doc page like https://trpc.io/docs/quickstart#defining-a-backend-router and try to click on the guide with the dark theme on

### Additional information

[Screencast from 12-29-2024 12:17:46 PM.webm](https://github.com/user-attachments/assets/2d8e1067-5b0f-472f-a913-9e232aa5b3c3)

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

**Comment by KATT** [comment]
Wanna fix it?

**Comment by Antonio476587** [comment]
Okay, I made it. I will make a pull request

**Comment by KATT** [comment]
I can't reproduce the bug in neither Chrome nor Firefox though

**Comment by KATT** [comment]
## Firefox


https://github.com/user-attachments/assets/a15b707e-2962-4a45-8f54-116e749295fc


## Chrome


https://github.com/user-attachments/assets/5ab8564b-baec-4950-88bc-4451a1cb23f5

**Comment by Antonio476587** [comment]
It appears when you click on a link by this side when it's in dark mode

![Screenshot from 2024-12-29 20-38-23](https://github.com/user-attachments/assets/610013f8-8459-4e89-b752-4eca858ed38e)
![image](https://github.com/user-attachments/assets/867b05b9-a3fe-4078-93bd-61cacd6c2935)

**Comment by KATT** [comment]
Oh jeez, that's strange. Thanks for the fix!
