### ISSUE TITLE
bug: Subscriptions never stopped

### ISSUE THREAD

**Issue by strblr** [trpc/trpc#6348]
### Provide environment information

System:
    OS: Linux 5.15 Ubuntu 24.04.1 LTS 24.04.1 LTS (Noble Numbat)
    CPU: (32) x64 AMD Ryzen 9 5950X 16-Core Processor
    Memory: 27.55 GB / 31.30 GB
    Container: Yes
    Shell: 5.2.21 - /bin/bash
  Binaries:
    Node: 23.3.0 - ~/.nvm/versions/node/v23.3.0/bin/node
    Yarn: 1.22.22 - ~/.nvm/versions/node/v23.3.0/bin/yarn
    npm: 10.9.0 - ~/.nvm/versions/node/v23.3.0/bin/npm
    pnpm: 9.15.0 - ~/.nvm/versions/node/v23.3.0/bin/pnpm
    bun: 1.1.38 - ~/.bun/bin/bun
  npmPackages:
    @tanstack/react-query: ^5.62.11 => 5.62.11 
    @trpc/client: ^11.0.0-rc.678 => 11.0.0-rc.678+29a2f0d18 
    @trpc/react-query: ^11.0.0-rc.678 => 11.0.0-rc.678+29a2f0d18 
    @trpc/server: ^11.0.0-rc.678 => 11.0.0-rc.678+29a2f0d18 
    react: ^18.3.1 => 18.3.1 
    typescript: ^5.7.2 => 5.7.2

### Describe the bug

The generator of a subscription never gets cancelled, regardless if the component that triggered it unmounts or if the tab is closed or refreshed. New generators get started but the old ones never stop. This is regardless if we use `try finally` or check `signal.aborted`.

This can be seen without any change in the minimal starter repo. Just refresh the page and check the console:

```
[2] 🔄 loop 1
[1] 🔄 loop 192
[2] 🔄 loop 2
[1] 🔄 loop 193
[2] 🔄 loop 3
[1] 🔄 loop 194
[2] 🔄 loop 4
[1] 🔄 loop 195
[2] 🔄 loop 5
[1] 🔄 loop 196
[2] 🔄 loop 6
[1] 🔄 loop 197
[2] 🔄 loop 7
[1] 🔄 loop 198
[2] 🔄 loop 8
[1] 🔄 loop 199
[2] 🔄 loop 9
[1] 🔄 loop 200
```

Same happens with streamed queries.

### Link to reproduction

https://stackblitz.com/github/trpc/examples-next-minimal-starter?file=src%2Fpages%2Fapi%2Ftrpc%2F%5Btrpc%5D.ts

### To reproduce

Go on the minimal starter example, refresh the rendered page on the right. Every refresh triggers a new generator, without stopping the previous ones.

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

**Comment by KATT** [comment]
I think this is a StackBlitz-issue, have you tried running it locally?

**Comment by strblr** [comment]
Yes. This is what I have locally:

```ts
export const appRouter = router({
  getUser: publicProcedure
    .input(
      z.object({
        id: z.string()
      })
    )
    .subscription(async function* (opts) {
      try {
        for (let i = 0; i < 1000; i++) {
          if (opts.signal?.aborted) {
            console.log("Aborted");
            break;
          }
          yield { id: i };
          console.log("Yielding", i);
          await new Promise(resolve => setTimeout(resolve, 200));
        }
      } finally {
        console.log("Closing");
      }
    })
});
```

```tsx
import { trpc } from "./trpc";

function App() {
  const { data } = trpc.getUser.useSubscription({ id: "45" });
  return (
    <>
      <h1>Vite + React</h1>
      <div className="card">
        <p>
          Edit <code>src/App.tsx</code> and save to test HMR
        </p>
      </div>
      <p className="read-the-docs">
        Click on the Vite and React logos to learn more
      </p>
      <pre>{JSON.stringify(data, null, 2)}</pre>
    </>
  );
}

export default App;
```

Exact same issue.
I also tried with streamed queries, same problem.

Also, when a generator ends, it seems to be automatically restarted. For example this:

```ts
export const appRouter = router({
  getUser: publicProcedure
    .input(
      z.object({
        id: z.string()
      })
    )
    .subscription(async function* (opts) {
      yield 42;
    })
});
```

The subscription is called every second from the client.

**Comment by KATT** [comment]
What api adapter are you using locally? The signal currently doesn't work for the Fetch-adapter as `Request` doesn't have any information about requests being aborted afaik, but it should work anyway since `Response` is a stream and will `.return()` the iteratable when it cancels

Subscriptions are infinite and will automatically restart, that's intended behavior, if you want a finite stream, use the [batch stream link](https://trpc.io/docs/client/links/httpBatchStreamLink).

**Comment by strblr** [comment]
This is the file with the links that I'm using:

```tsx
import {
  createTRPCReact,
  unstable_httpBatchStreamLink,
  loggerLink,
  splitLink,
  unstable_httpSubscriptionLink
} from "@trpc/react-query";
import { QueryClient } from "@tanstack/react-query";
import type { AppRouter } from "../../backend/src/router";

export const trpc = createTRPCReact<AppRouter>();

export const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      refetchOnWindowFocus: false
    }
  }
});

export const trpcClient = trpc.createClient({
  links: [
    loggerLink(),
    splitLink({
      condition: op => op.type === "subscription",
      true: unstable_httpSubscriptionLink({
        url: "http://localhost:3030/trpc"
      }),
      false: unstable_httpBatchStreamLink({
        url: "http://localhost:3030/trpc"
      })
    })
  ]
});
```

I'm trying to implement a live query system where you fetch a query, then register the generator in some store with some key derived from the query name and arguments, and have an `invalidate` function server-side that could be called from anywhere. Basically following this pattern: https://github.com/n1ru4l/graphql-live-query

The problem with streamed queries is that:
- Just like subscriptions, it doesn't get aborted under any circumstance
- The client-side useQuery keeps all previous values and accumulates them in an array. Not what I want for live queries with "updated" data being streamed in.

I also don't wanna combine queries and subscription because I simply don't like the pattern.

So I'm trying to built this on top of subscriptions alone, but the subscriptions never being aborted makes it impossible to know when a "live query" should be removed from my store and not trigger updates anymore.

**Comment by KATT** [comment]
If you want a live query, you probably indeed want to use subscriptions - a simple way would be that the first call gives you the full entity and each yield gives a patch 

On subscriptions not stopping, I need to see your actual code, because I just pulled down the stackblitz above as-is and it works fine:


https://github.com/user-attachments/assets/66b1e73c-ffa8-4cd7-9567-22f64ff066bf

**Comment by strblr** [comment]
Yeah either patches as JSON diffs or full updated payloads.

As for the code, It's even more basic than the starter demo, so I suspect it's gonna work just fine if you pull it. I've joined the zip to this message anyway.

[test.zip](https://github.com/user-attachments/files/18271360/test.zip)

**Comment by strblr** [comment]
Side note: not sure why, but `data` is always `any` in this demo. Whether I use subscriptions or queries. Inputs are correctly typed though.

**Comment by KATT** [comment]
I missed that you mentioned Bun. This is likely a bug in Bun.

I replaced `bun` with `tsx` in your `package.json`s and it works fine

https://github.com/user-attachments/assets/7e7997af-0646-4591-8127-c694134e6d50

**Comment by KATT** [comment]
> Side note: not sure why, but `data` is always `any` in this demo. Whether I use subscriptions or queries. Inputs are correctly typed though.

Likely that your VSCode isn't using the latest version of TypeScript:

- https://trpc.io/docs/faq#it-doesnt-work-im-getting-any-everywhere
- https://trpc.io/docs/migrate-from-v10-to-v11#typescript-version-572-is-now-required-non-breaking

**Comment by strblr** [comment]
Confirmed, running with tsx works! Thank you so much! Is this a known issue with Bun?

For TS, will check and come back to you.

**Comment by KATT** [comment]
I think it's that Bun isn't correctly implementing the events we need for the abort controller. This is what we do:

https://github.com/trpc/trpc/blob/94bea97e302162974b3b46cd81363fd64610a457/packages/server/src/adapters/node-http/incomingMessageToRequest.ts#L137-L146


Please report an issue in Bun instead.

**Comment by strblr** [comment]
For the output types, I've tried the VSCode settings described here: https://trpc.io/docs/migrate-from-v10-to-v11#typescript-version-572-is-now-required-non-breaking

Still the same issue. Everything is correctly typed except the output.

**Comment by KATT** [comment]
In your case you need to do 

```json
{
    "typescript.tsdk": "backend/node_modules/typescript/lib",
    "typescript.enablePromptUseWorkspaceTsdk": true
  }
```

since you haven't done a proper monorepo where you have a root package.json which contains typescript

**Comment by strblr** [comment]
Sorry, doesn't work either.
Is there a starter boilerplate somewhere that doesn't use Next? Just plain React + vite and a basic server?

**Comment by KATT** [comment]
https://github.com/trpc/examples-minimal-react but it doesn't have VSCode settings

I don't have more time to help you out, you gotta figure out how to get your editor to use the latest VSCode version yourself

**Comment by strblr** [comment]
Yeah I'll figure it out. Thanks

**Comment by KATT** [comment]
We're planning to change this - let us know what you think

See #6460
