### ISSUE TITLE
Client does not enforce 'no input' when an endpoint declared without 'input'

### ISSUE THREAD

**Issue by danielyogel** [trpc/trpc#672]
Example

`
const appRouter = trpc
  .router()
  .query('getData', {
    async resolve() {
      return data;
    },
  })
`

`
 await api.query('getData', 'some unneeded input');
`

Runtime error - 'no input expected'.

Expected Behaviour:
Client should enforce no input on using the compiler.

**Comment by KATT** [comment]
<img width="974" alt="testy" src="https://user-images.githubusercontent.com/459267/126222305-c0845385-4653-42f0-ade1-c5391cee1de1.png">


Hmm - can't reproduce, see this test case

**Comment by KATT** [comment]
Do you have strict mode on in `tsconfig.json`?

**Comment by danielyogel** [comment]
This is my client's tsconfig.json:
<img width="323" alt="Screen Shot 2021-07-21 at 11 59 17" src="https://user-images.githubusercontent.com/2037064/126461718-21cc6c92-6692-46eb-b9f9-5f37407f4bae.png">

This is the type I get for a query with no input (arguments are 'unknown' not 'null/undefined'):
<img width="435" alt="Screen Shot 2021-07-21 at 12 06 08" src="https://user-images.githubusercontent.com/2037064/126462733-04729bc0-08d0-49d5-a0d7-68e160cd0ab8.png">

I think the problem is related to the fact I use seperate tsconfig files for client and server, I will research that.

**Comment by KATT** [comment]
Make sure both have `"strict": true`... could be that, but I'm just guessing

**Comment by danielyogel** [comment]
They both have `strict: true`
Actually, I've just verified this problem reproduces in tRPC's original 'standalone-server' example:

<img width="488" alt="Screen Shot 2021-07-21 at 17 50 58" src="https://user-images.githubusercontent.com/2037064/126509817-b2fbc3cd-2a43-4cda-873e-0d9044eed78e.png">


<img width="764" alt="Screen Shot 2021-07-21 at 17 51 49" src="https://user-images.githubusercontent.com/2037064/126509727-bfa7ad0e-22a9-4f06-bfe2-de23032de6fb.png">


VSCode's TS version is 4.3.5

**Comment by KATT** [comment]
Ohhh --- you're right. 

Try changing this line in the tests though to `await client.query('q', 'something');` and you'll get error correctly.

https://github.com/trpc/trpc/blob/d903a65f4506fb1f74bd6dc9f0e185fa94438b2c/packages/server/test/index.test.tsx#L172


Your guess is as good as mine, I tried throwing some tsconfig settings around but haven't hit the nail yet!

**Comment by danielyogel** [comment]
Thanks! 
I will do me best to find a solution as time allows me.

For now, at least from TS's side, [this may be a starting point](https://stackoverflow.com/a/54119811/1598423)
