### ISSUE TITLE
Discriminate and extract return type

### ISSUE THREAD

**Issue by sam3d** [trpc/trpc#682]
Hello 👋 

Is there a way to discriminate the return type of a hook so it can be accessed from the client? Something like the following psuedo-ish code (where "projects.findAll" is the name of the query in trpc router):

```ts
type Project = ReturnType<typeof useQuery>["data"]<"projects.findAll">[0];
```

**Comment by KATT** [comment]
Hey @sam3d 

Seems like you're looking for this! 👇

https://github.com/trpc/trpc/blob/fdc5e071cb566335071e70b8f58299e846fa6d83/examples/next-prisma-starter/src/utils/trpc.ts#L15-L21

**Comment by sam3d** [comment]
Wow that was fast and EXACTLY what I was looking for, thank you so much! Worked perfectly

I vote best open source maintainer award for @KATT 🏆

**Comment by KATT** [comment]
FYI it's also possible to do this with inputs of course 

https://github.com/KATT/typescript.careers/blob/0469f6e5d1e981ebe540e83c8f66674bf079a10d/src/utils/trpc.ts#L26-L28
