### ISSUE TITLE
API Gateway adapter?

### ISSUE THREAD

**Issue by mmkal** [trpc/trpc#709]
Would you be open to adding an API Gateway adapter? I haven't dived in deeply enough to the express and standalone ones to know exactly what it'd entail, but here's our current approach:

```ts
import * as trpc from '@trpc/server'
import * as trpcExpress from '@trpc/server/adapters/express'
import {z} from 'zod'
import serverless from 'serverless-http'
import express from 'express'

const appRouter = trpc.router<{foo: string}>().query('getUser', {
  input: z.string(),
  async resolve(req) {
    return {id: req.input, name: 'Bilbo', now: Date.now()}
  },
})

export const app = express()

app.use(
  trpcExpress.createExpressMiddleware({
    router: appRouter,
    createContext: () => ({foo: 'bar'}),
  }),
)

export const handler = serverless(app)

export type AppRouter = typeof appRouter
```

Which is fine, but we're relying on the `serverless-http` library to do all the magic hacks that make our _entire_ backend work. And it doesn't feel right that we need express and serverless-http as prod dependencies at all, since API Gateway lambdas are actually already kind of closer to what trpc/server does in the first place, I think (just functions that take inputs and return promise outputs, rather than weird `res.status(...).send(...)` side-effects). How I imagine it could look:

```ts
import * as trpc from '@trpc/server'
import * as trpcApiGateway from '@trpc/server/adapters/apiGateway'
import {z} from 'zod'

const appRouter = trpc.router<{foo: string}>().query('getUser', {
  input: z.string(),
  async resolve(req) {
    return {id: req.input, name: 'Bilbo', now: Date.now()}
  },
})

export const handler = trpcApiGateway.createApiGatewayHandler({
  router: appRouter,
  createContext: () => ({foo: 'bar'}),
})

export type AppRouter = typeof appRouter
```

So I think it fits pretty neatly in alongside the other adapters. A simple API Gateway handler looks something like:

```ts
export const handler = async event => {
  return {
    statusCode: 200,
    headers: {'x-foo': 'bar'},
    body: JSON.stringify({
      result: `Hello ${event.queryStringParameters.abc} ${event.body.def}`,
    }),
  }
}
```

**Comment by KATT** [comment]
This would be a great addition to the adapters! I was talking to a company that would want a very similar thing, I think - @thisdotrob, can you share what you ended up with?

You can use `trpc.createHttpHandler` straight off - see example code here: https://github.com/trpc/trpc/discussions/655#discussioncomment-996126.

If you want to add an official adapter, you can like at the [next.js one for a reference implementation](https://github.com/trpc/trpc/blob/main/packages/server/src/adapters/next.ts). Also happy to [jump on a call](https://calendly.com/alexdotjs/30min) and talk through the codebase if you're interested in contributing.
