### ISSUE TITLE
Fastify plugin for TRPC for easy config.

### ISSUE THREAD

**Issue by Unbuttun** [trpc/trpc#715]
A config for fastify can make lot's of things easier when it comes to configuring trpc onto some route of fastify.
In the example file of [fastify.test.tsx](https://github.com/trpc/trpc/blob/main/packages/server/test/adapters/fastify.test.tsx), although it's shown there, but the process looks a bit cumbersome and not easy enough to understand.

There is also a quick plugin done by @KATT on https://github.com/trpc/trpc/issues/524.

So if we can get a fastify plugin for trpc, it will make things a lot easier to use it on existing setup.

**Comment by KATT** [comment]
Thanks for the suggestion and for looking through the issues.

I don't use fastify myself so I won't spend time writing a specific adapter for it, but I'd happily review & merge if someone else did a PR. Look at the next adapter if you want a reference.
