### ISSUE TITLE
Utility type to infer query type

### ISSUE THREAD

**Issue by gabrielsch** [trpc/trpc#768]
It's common to pass values returned by a query to components as a prop in react, however it seems like it's difficult to get the `typeof` of a query without having to touch `AppRouter['_def']['queries']['queryName']` which looks a bit verbose. 

Should TRPC export an utility type that makes it easier? Maybe something like `typeof inferQuery<AppRouter, 'query.name'>`

**Comment by KATT** [comment]
Hey @gabrielsch - looks like this is what you want 👇 
https://github.com/trpc/trpc/issues/682#issuecomment-883385653

**Comment by gabrielsch** [comment]
that's exactly what I was looking for, thank you @KATT !
