### ISSUE TITLE
Type input without using zod/validation?

### ISSUE THREAD

**Issue by sam3d** [trpc/trpc#971]
Hello 👋 

Is there a way to type the input object without using validation? I'm trying to re-create the behaviour of this Blitz example: 

https://github.com/blitz-js/blitz/blob/63af540c879fe71dfad561d814b4da57dcafe576/examples/auth/app/projects/queries/getProjects.ts#L9

**Comment by KATT** [comment]
Yes, but you should really, really **not** do this

```tsx
function passThroughAsNumber(input: unknown) {
  return input as number;
}
const router = trpc.router().query('num', {
  input: passThroughAsNumber,
  resolve({ input }) {
    expectTypeOf(input).toBeNumber();
    return {
      input,
    };
  },
});
```
