### ISSUE TITLE
initialData is typed for the procedure input instead of the procedure output

### ISSUE THREAD

**Issue by sam3d** [trpc/trpc#990]
Bit of a weird one, it seems as though when using `useQuery` the `initialData` expects the same typings as the query's input parameters instead of the output. I tried having a look at the typings to figure out why but I'm afraid the typescript wizardry of TRPC is a little beyond me!

![image](https://user-images.githubusercontent.com/8385528/134337567-7fe4c327-fd29-4594-ab9e-2000fb6cf469.png)

**Comment by sam3d** [comment]
Reproduction link: https://github.com/sam3d/trpc-repro

**Comment by KATT** [comment]
Seems to be a react-query bug - see https://github.com/tannerlinsley/react-query/pull/2715
